#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'AllergyIntolerance (fhir-spec 'AllergyIntolerance "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance" 'type)
  #:schema (type-schema 'AllergyIntolerance #f 'DomainResource "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.identifier" #f)
    (schema-field 'clinicalStatus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.clinicalStatus" #f)
    (schema-field 'verificationStatus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.verificationStatus" #f)
    (schema-field 'type 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.type" #f)
    (schema-field 'category 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.category" #f)
    (schema-field 'criticality 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.criticality" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.code" #f)
    (schema-field 'patient 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.patient" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.encounter" #f)
    (schema-field 'recordedDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.recordedDate" #f)
    (schema-field 'recorder 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.recorder" #f)
    (schema-field 'asserter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.asserter" #f)
    (schema-field 'lastOccurrence 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.lastOccurrence" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.note" #f)
    (schema-field 'reaction 0 '* (vector 'type 'AllergyIntoleranceReaction) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction" #f)
    (schema-field 'onsetDateTime 0 1 (vector 'prim "dateTime") 'onset "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" #f)
    (schema-field 'onsetAge 0 1 (vector 'type 'Age) 'onset "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" #f)
    (schema-field 'onsetPeriod 0 1 (vector 'type 'Period) 'onset "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" #f)
    (schema-field 'onsetRange 0 1 (vector 'type 'Range) 'onset "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" #f)
    (schema-field 'onsetString 0 1 (vector 'prim "string") 'onset "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" #f)
             ) #f #f))
(register-element! "AllergyIntolerance.identifier" (fhir-spec (string->symbol "AllergyIntolerance.identifier") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.identifier" 'element))
(register-element! "AllergyIntolerance.clinicalStatus" (fhir-spec (string->symbol "AllergyIntolerance.clinicalStatus") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.clinicalStatus" 'element))
(register-element! "AllergyIntolerance.verificationStatus" (fhir-spec (string->symbol "AllergyIntolerance.verificationStatus") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.verificationStatus" 'element))
(register-element! "AllergyIntolerance.type" (fhir-spec (string->symbol "AllergyIntolerance.type") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.type" 'element))
(register-element! "AllergyIntolerance.category" (fhir-spec (string->symbol "AllergyIntolerance.category") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.category" 'element))
(register-element! "AllergyIntolerance.criticality" (fhir-spec (string->symbol "AllergyIntolerance.criticality") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.criticality" 'element))
(register-element! "AllergyIntolerance.code" (fhir-spec (string->symbol "AllergyIntolerance.code") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.code" 'element))
(register-element! "AllergyIntolerance.patient" (fhir-spec (string->symbol "AllergyIntolerance.patient") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.patient" 'element))
(register-element! "AllergyIntolerance.encounter" (fhir-spec (string->symbol "AllergyIntolerance.encounter") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.encounter" 'element))
(register-element! "AllergyIntolerance.recordedDate" (fhir-spec (string->symbol "AllergyIntolerance.recordedDate") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.recordedDate" 'element))
(register-element! "AllergyIntolerance.recorder" (fhir-spec (string->symbol "AllergyIntolerance.recorder") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.recorder" 'element))
(register-element! "AllergyIntolerance.asserter" (fhir-spec (string->symbol "AllergyIntolerance.asserter") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.asserter" 'element))
(register-element! "AllergyIntolerance.lastOccurrence" (fhir-spec (string->symbol "AllergyIntolerance.lastOccurrence") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.lastOccurrence" 'element))
(register-element! "AllergyIntolerance.note" (fhir-spec (string->symbol "AllergyIntolerance.note") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.note" 'element))
(register-element! "AllergyIntolerance.reaction" (fhir-spec (string->symbol "AllergyIntolerance.reaction") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction" 'element))
(register-element! "AllergyIntolerance.onset[x]" (fhir-spec (string->symbol "AllergyIntolerance.onset[x]") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" 'element))
(register-element! "AllergyIntolerance.onset[x]" (fhir-spec (string->symbol "AllergyIntolerance.onset[x]") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" 'element))
(register-element! "AllergyIntolerance.onset[x]" (fhir-spec (string->symbol "AllergyIntolerance.onset[x]") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" 'element))
(register-element! "AllergyIntolerance.onset[x]" (fhir-spec (string->symbol "AllergyIntolerance.onset[x]") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" 'element))
(register-element! "AllergyIntolerance.onset[x]" (fhir-spec (string->symbol "AllergyIntolerance.onset[x]") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.onset[x]" 'element))

(register-type! 'AllergyIntoleranceReaction (fhir-spec 'AllergyIntoleranceReaction "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction" 'type)
  #:schema (type-schema 'AllergyIntoleranceReaction #f 'BackboneElement "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction"
             (list
    (schema-field 'substance 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.substance" #f)
    (schema-field 'manifestation 1 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.manifestation" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.description" #f)
    (schema-field 'onset 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.onset" #f)
    (schema-field 'severity 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.severity" #f)
    (schema-field 'exposureRoute 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.exposureRoute" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.note" #f)
             ) #f #f))
(register-element! "AllergyIntolerance.reaction.substance" (fhir-spec (string->symbol "AllergyIntolerance.reaction.substance") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.substance" 'element))
(register-element! "AllergyIntolerance.reaction.manifestation" (fhir-spec (string->symbol "AllergyIntolerance.reaction.manifestation") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.manifestation" 'element))
(register-element! "AllergyIntolerance.reaction.description" (fhir-spec (string->symbol "AllergyIntolerance.reaction.description") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.description" 'element))
(register-element! "AllergyIntolerance.reaction.onset" (fhir-spec (string->symbol "AllergyIntolerance.reaction.onset") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.onset" 'element))
(register-element! "AllergyIntolerance.reaction.severity" (fhir-spec (string->symbol "AllergyIntolerance.reaction.severity") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.severity" 'element))
(register-element! "AllergyIntolerance.reaction.exposureRoute" (fhir-spec (string->symbol "AllergyIntolerance.reaction.exposureRoute") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.exposureRoute" 'element))
(register-element! "AllergyIntolerance.reaction.note" (fhir-spec (string->symbol "AllergyIntolerance.reaction.note") "https://hl7.org/fhir/R4/allergyintolerance.html#AllergyIntolerance.reaction.note" 'element))

