#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Appointment (fhir-spec 'Appointment "https://hl7.org/fhir/R4/appointment.html#Appointment" 'type)
  #:schema (type-schema 'Appointment #f 'DomainResource "https://hl7.org/fhir/R4/appointment.html#Appointment"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.status" #f)
    (schema-field 'cancelationReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.cancelationReason" #f)
    (schema-field 'serviceCategory 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.serviceCategory" #f)
    (schema-field 'serviceType 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.serviceType" #f)
    (schema-field 'specialty 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.specialty" #f)
    (schema-field 'appointmentType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.appointmentType" #f)
    (schema-field 'reasonCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.reasonCode" #f)
    (schema-field 'reasonReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.reasonReference" #f)
    (schema-field 'priority 0 1 (vector 'prim "unsignedInt") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.priority" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.description" #f)
    (schema-field 'supportingInformation 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.supportingInformation" #f)
    (schema-field 'start 0 1 (vector 'prim "instant") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.start" #f)
    (schema-field 'end 0 1 (vector 'prim "instant") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.end" #f)
    (schema-field 'minutesDuration 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.minutesDuration" #f)
    (schema-field 'slot 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.slot" #f)
    (schema-field 'created 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.created" #f)
    (schema-field 'comment 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.comment" #f)
    (schema-field 'patientInstruction 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.patientInstruction" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.basedOn" #f)
    (schema-field 'participant 1 '* (vector 'type 'AppointmentParticipant) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.participant" #f)
    (schema-field 'requestedPeriod 0 '* (vector 'type 'Period) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.requestedPeriod" #f)
             ) #f #f))
(register-element! "Appointment.identifier" (fhir-spec (string->symbol "Appointment.identifier") "https://hl7.org/fhir/R4/appointment.html#Appointment.identifier" 'element))
(register-element! "Appointment.status" (fhir-spec (string->symbol "Appointment.status") "https://hl7.org/fhir/R4/appointment.html#Appointment.status" 'element))
(register-element! "Appointment.cancelationReason" (fhir-spec (string->symbol "Appointment.cancelationReason") "https://hl7.org/fhir/R4/appointment.html#Appointment.cancelationReason" 'element))
(register-element! "Appointment.serviceCategory" (fhir-spec (string->symbol "Appointment.serviceCategory") "https://hl7.org/fhir/R4/appointment.html#Appointment.serviceCategory" 'element))
(register-element! "Appointment.serviceType" (fhir-spec (string->symbol "Appointment.serviceType") "https://hl7.org/fhir/R4/appointment.html#Appointment.serviceType" 'element))
(register-element! "Appointment.specialty" (fhir-spec (string->symbol "Appointment.specialty") "https://hl7.org/fhir/R4/appointment.html#Appointment.specialty" 'element))
(register-element! "Appointment.appointmentType" (fhir-spec (string->symbol "Appointment.appointmentType") "https://hl7.org/fhir/R4/appointment.html#Appointment.appointmentType" 'element))
(register-element! "Appointment.reasonCode" (fhir-spec (string->symbol "Appointment.reasonCode") "https://hl7.org/fhir/R4/appointment.html#Appointment.reasonCode" 'element))
(register-element! "Appointment.reasonReference" (fhir-spec (string->symbol "Appointment.reasonReference") "https://hl7.org/fhir/R4/appointment.html#Appointment.reasonReference" 'element))
(register-element! "Appointment.priority" (fhir-spec (string->symbol "Appointment.priority") "https://hl7.org/fhir/R4/appointment.html#Appointment.priority" 'element))
(register-element! "Appointment.description" (fhir-spec (string->symbol "Appointment.description") "https://hl7.org/fhir/R4/appointment.html#Appointment.description" 'element))
(register-element! "Appointment.supportingInformation" (fhir-spec (string->symbol "Appointment.supportingInformation") "https://hl7.org/fhir/R4/appointment.html#Appointment.supportingInformation" 'element))
(register-element! "Appointment.start" (fhir-spec (string->symbol "Appointment.start") "https://hl7.org/fhir/R4/appointment.html#Appointment.start" 'element))
(register-element! "Appointment.end" (fhir-spec (string->symbol "Appointment.end") "https://hl7.org/fhir/R4/appointment.html#Appointment.end" 'element))
(register-element! "Appointment.minutesDuration" (fhir-spec (string->symbol "Appointment.minutesDuration") "https://hl7.org/fhir/R4/appointment.html#Appointment.minutesDuration" 'element))
(register-element! "Appointment.slot" (fhir-spec (string->symbol "Appointment.slot") "https://hl7.org/fhir/R4/appointment.html#Appointment.slot" 'element))
(register-element! "Appointment.created" (fhir-spec (string->symbol "Appointment.created") "https://hl7.org/fhir/R4/appointment.html#Appointment.created" 'element))
(register-element! "Appointment.comment" (fhir-spec (string->symbol "Appointment.comment") "https://hl7.org/fhir/R4/appointment.html#Appointment.comment" 'element))
(register-element! "Appointment.patientInstruction" (fhir-spec (string->symbol "Appointment.patientInstruction") "https://hl7.org/fhir/R4/appointment.html#Appointment.patientInstruction" 'element))
(register-element! "Appointment.basedOn" (fhir-spec (string->symbol "Appointment.basedOn") "https://hl7.org/fhir/R4/appointment.html#Appointment.basedOn" 'element))
(register-element! "Appointment.participant" (fhir-spec (string->symbol "Appointment.participant") "https://hl7.org/fhir/R4/appointment.html#Appointment.participant" 'element))
(register-element! "Appointment.requestedPeriod" (fhir-spec (string->symbol "Appointment.requestedPeriod") "https://hl7.org/fhir/R4/appointment.html#Appointment.requestedPeriod" 'element))

(register-type! 'AppointmentParticipant (fhir-spec 'AppointmentParticipant "https://hl7.org/fhir/R4/appointment.html#Appointment.participant" 'type)
  #:schema (type-schema 'AppointmentParticipant #f 'BackboneElement "https://hl7.org/fhir/R4/appointment.html#Appointment.participant"
             (list
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.type" #f)
    (schema-field 'actor 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.actor" #f)
    (schema-field 'required 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.required" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.status" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.period" #f)
             ) #f #f))
(register-element! "Appointment.participant.type" (fhir-spec (string->symbol "Appointment.participant.type") "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.type" 'element))
(register-element! "Appointment.participant.actor" (fhir-spec (string->symbol "Appointment.participant.actor") "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.actor" 'element))
(register-element! "Appointment.participant.required" (fhir-spec (string->symbol "Appointment.participant.required") "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.required" 'element))
(register-element! "Appointment.participant.status" (fhir-spec (string->symbol "Appointment.participant.status") "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.status" 'element))
(register-element! "Appointment.participant.period" (fhir-spec (string->symbol "Appointment.participant.period") "https://hl7.org/fhir/R4/appointment.html#Appointment.participant.period" 'element))

