#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'CarePlan (fhir-spec 'CarePlan "https://hl7.org/fhir/R4/careplan.html#CarePlan" 'type)
  #:schema (type-schema 'CarePlan #f 'DomainResource "https://hl7.org/fhir/R4/careplan.html#CarePlan"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.identifier" #f)
    (schema-field 'instantiatesCanonical 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 '* (vector 'prim "uri") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.instantiatesUri" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.basedOn" #f)
    (schema-field 'replaces 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.replaces" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.status" #f)
    (schema-field 'intent 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.intent" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.category" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.title" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.description" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.encounter" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.period" #f)
    (schema-field 'created 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.created" #f)
    (schema-field 'author 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.author" #f)
    (schema-field 'contributor 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.contributor" #f)
    (schema-field 'careTeam 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.careTeam" #f)
    (schema-field 'addresses 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.addresses" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.supportingInfo" #f)
    (schema-field 'goal 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.goal" #f)
    (schema-field 'activity 0 '* (vector 'type 'CarePlanActivity) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.note" #f)
             ) #f #f))
(register-element! "CarePlan.identifier" (fhir-spec (string->symbol "CarePlan.identifier") "https://hl7.org/fhir/R4/careplan.html#CarePlan.identifier" 'element))
(register-element! "CarePlan.instantiatesCanonical" (fhir-spec (string->symbol "CarePlan.instantiatesCanonical") "https://hl7.org/fhir/R4/careplan.html#CarePlan.instantiatesCanonical" 'element))
(register-element! "CarePlan.instantiatesUri" (fhir-spec (string->symbol "CarePlan.instantiatesUri") "https://hl7.org/fhir/R4/careplan.html#CarePlan.instantiatesUri" 'element))
(register-element! "CarePlan.basedOn" (fhir-spec (string->symbol "CarePlan.basedOn") "https://hl7.org/fhir/R4/careplan.html#CarePlan.basedOn" 'element))
(register-element! "CarePlan.replaces" (fhir-spec (string->symbol "CarePlan.replaces") "https://hl7.org/fhir/R4/careplan.html#CarePlan.replaces" 'element))
(register-element! "CarePlan.partOf" (fhir-spec (string->symbol "CarePlan.partOf") "https://hl7.org/fhir/R4/careplan.html#CarePlan.partOf" 'element))
(register-element! "CarePlan.status" (fhir-spec (string->symbol "CarePlan.status") "https://hl7.org/fhir/R4/careplan.html#CarePlan.status" 'element))
(register-element! "CarePlan.intent" (fhir-spec (string->symbol "CarePlan.intent") "https://hl7.org/fhir/R4/careplan.html#CarePlan.intent" 'element))
(register-element! "CarePlan.category" (fhir-spec (string->symbol "CarePlan.category") "https://hl7.org/fhir/R4/careplan.html#CarePlan.category" 'element))
(register-element! "CarePlan.title" (fhir-spec (string->symbol "CarePlan.title") "https://hl7.org/fhir/R4/careplan.html#CarePlan.title" 'element))
(register-element! "CarePlan.description" (fhir-spec (string->symbol "CarePlan.description") "https://hl7.org/fhir/R4/careplan.html#CarePlan.description" 'element))
(register-element! "CarePlan.subject" (fhir-spec (string->symbol "CarePlan.subject") "https://hl7.org/fhir/R4/careplan.html#CarePlan.subject" 'element))
(register-element! "CarePlan.encounter" (fhir-spec (string->symbol "CarePlan.encounter") "https://hl7.org/fhir/R4/careplan.html#CarePlan.encounter" 'element))
(register-element! "CarePlan.period" (fhir-spec (string->symbol "CarePlan.period") "https://hl7.org/fhir/R4/careplan.html#CarePlan.period" 'element))
(register-element! "CarePlan.created" (fhir-spec (string->symbol "CarePlan.created") "https://hl7.org/fhir/R4/careplan.html#CarePlan.created" 'element))
(register-element! "CarePlan.author" (fhir-spec (string->symbol "CarePlan.author") "https://hl7.org/fhir/R4/careplan.html#CarePlan.author" 'element))
(register-element! "CarePlan.contributor" (fhir-spec (string->symbol "CarePlan.contributor") "https://hl7.org/fhir/R4/careplan.html#CarePlan.contributor" 'element))
(register-element! "CarePlan.careTeam" (fhir-spec (string->symbol "CarePlan.careTeam") "https://hl7.org/fhir/R4/careplan.html#CarePlan.careTeam" 'element))
(register-element! "CarePlan.addresses" (fhir-spec (string->symbol "CarePlan.addresses") "https://hl7.org/fhir/R4/careplan.html#CarePlan.addresses" 'element))
(register-element! "CarePlan.supportingInfo" (fhir-spec (string->symbol "CarePlan.supportingInfo") "https://hl7.org/fhir/R4/careplan.html#CarePlan.supportingInfo" 'element))
(register-element! "CarePlan.goal" (fhir-spec (string->symbol "CarePlan.goal") "https://hl7.org/fhir/R4/careplan.html#CarePlan.goal" 'element))
(register-element! "CarePlan.activity" (fhir-spec (string->symbol "CarePlan.activity") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity" 'element))
(register-element! "CarePlan.note" (fhir-spec (string->symbol "CarePlan.note") "https://hl7.org/fhir/R4/careplan.html#CarePlan.note" 'element))

(register-type! 'CarePlanActivity (fhir-spec 'CarePlanActivity "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity" 'type)
  #:schema (type-schema 'CarePlanActivity #f 'BackboneElement "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity"
             (list
    (schema-field 'outcomeCodeableConcept 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.outcomeCodeableConcept" #f)
    (schema-field 'outcomeReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.outcomeReference" #f)
    (schema-field 'progress 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.progress" #f)
    (schema-field 'reference 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.reference" #f)
    (schema-field 'detail 0 1 (vector 'type 'CarePlanActivityDetail) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail" #f)
             ) #f #f))
(register-element! "CarePlan.activity.outcomeCodeableConcept" (fhir-spec (string->symbol "CarePlan.activity.outcomeCodeableConcept") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.outcomeCodeableConcept" 'element))
(register-element! "CarePlan.activity.outcomeReference" (fhir-spec (string->symbol "CarePlan.activity.outcomeReference") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.outcomeReference" 'element))
(register-element! "CarePlan.activity.progress" (fhir-spec (string->symbol "CarePlan.activity.progress") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.progress" 'element))
(register-element! "CarePlan.activity.reference" (fhir-spec (string->symbol "CarePlan.activity.reference") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.reference" 'element))
(register-element! "CarePlan.activity.detail" (fhir-spec (string->symbol "CarePlan.activity.detail") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail" 'element))

(register-type! 'CarePlanActivityDetail (fhir-spec 'CarePlanActivityDetail "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail" 'type)
  #:schema (type-schema 'CarePlanActivityDetail #f 'BackboneElement "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail"
             (list
    (schema-field 'kind 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.kind" #f)
    (schema-field 'instantiatesCanonical 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 '* (vector 'prim "uri") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.instantiatesUri" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.code" #f)
    (schema-field 'reasonCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.reasonCode" #f)
    (schema-field 'reasonReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.reasonReference" #f)
    (schema-field 'goal 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.goal" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.statusReason" #f)
    (schema-field 'doNotPerform 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.doNotPerform" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.location" #f)
    (schema-field 'performer 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.performer" #f)
    (schema-field 'dailyAmount 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.dailyAmount" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.quantity" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.description" #f)
    (schema-field 'scheduledTiming 0 1 (vector 'type 'Timing) 'scheduled "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.scheduled[x]" #f)
    (schema-field 'scheduledPeriod 0 1 (vector 'type 'Period) 'scheduled "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.scheduled[x]" #f)
    (schema-field 'scheduledString 0 1 (vector 'prim "string") 'scheduled "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.scheduled[x]" #f)
    (schema-field 'productCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'product "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.product[x]" #f)
    (schema-field 'productReference 0 1 (vector 'type 'Reference) 'product "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.product[x]" #f)
             ) #f #f))
(register-element! "CarePlan.activity.detail.kind" (fhir-spec (string->symbol "CarePlan.activity.detail.kind") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.kind" 'element))
(register-element! "CarePlan.activity.detail.instantiatesCanonical" (fhir-spec (string->symbol "CarePlan.activity.detail.instantiatesCanonical") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.instantiatesCanonical" 'element))
(register-element! "CarePlan.activity.detail.instantiatesUri" (fhir-spec (string->symbol "CarePlan.activity.detail.instantiatesUri") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.instantiatesUri" 'element))
(register-element! "CarePlan.activity.detail.code" (fhir-spec (string->symbol "CarePlan.activity.detail.code") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.code" 'element))
(register-element! "CarePlan.activity.detail.reasonCode" (fhir-spec (string->symbol "CarePlan.activity.detail.reasonCode") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.reasonCode" 'element))
(register-element! "CarePlan.activity.detail.reasonReference" (fhir-spec (string->symbol "CarePlan.activity.detail.reasonReference") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.reasonReference" 'element))
(register-element! "CarePlan.activity.detail.goal" (fhir-spec (string->symbol "CarePlan.activity.detail.goal") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.goal" 'element))
(register-element! "CarePlan.activity.detail.status" (fhir-spec (string->symbol "CarePlan.activity.detail.status") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.status" 'element))
(register-element! "CarePlan.activity.detail.statusReason" (fhir-spec (string->symbol "CarePlan.activity.detail.statusReason") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.statusReason" 'element))
(register-element! "CarePlan.activity.detail.doNotPerform" (fhir-spec (string->symbol "CarePlan.activity.detail.doNotPerform") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.doNotPerform" 'element))
(register-element! "CarePlan.activity.detail.location" (fhir-spec (string->symbol "CarePlan.activity.detail.location") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.location" 'element))
(register-element! "CarePlan.activity.detail.performer" (fhir-spec (string->symbol "CarePlan.activity.detail.performer") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.performer" 'element))
(register-element! "CarePlan.activity.detail.dailyAmount" (fhir-spec (string->symbol "CarePlan.activity.detail.dailyAmount") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.dailyAmount" 'element))
(register-element! "CarePlan.activity.detail.quantity" (fhir-spec (string->symbol "CarePlan.activity.detail.quantity") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.quantity" 'element))
(register-element! "CarePlan.activity.detail.description" (fhir-spec (string->symbol "CarePlan.activity.detail.description") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.description" 'element))
(register-element! "CarePlan.activity.detail.scheduled[x]" (fhir-spec (string->symbol "CarePlan.activity.detail.scheduled[x]") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.scheduled[x]" 'element))
(register-element! "CarePlan.activity.detail.scheduled[x]" (fhir-spec (string->symbol "CarePlan.activity.detail.scheduled[x]") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.scheduled[x]" 'element))
(register-element! "CarePlan.activity.detail.scheduled[x]" (fhir-spec (string->symbol "CarePlan.activity.detail.scheduled[x]") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.scheduled[x]" 'element))
(register-element! "CarePlan.activity.detail.product[x]" (fhir-spec (string->symbol "CarePlan.activity.detail.product[x]") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.product[x]" 'element))
(register-element! "CarePlan.activity.detail.product[x]" (fhir-spec (string->symbol "CarePlan.activity.detail.product[x]") "https://hl7.org/fhir/R4/careplan.html#CarePlan.activity.detail.product[x]" 'element))

