#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'CodeSystem (fhir-spec 'CodeSystem "https://hl7.org/fhir/R4/codesystem.html#CodeSystem" 'type)
  #:schema (type-schema 'CodeSystem #f 'DomainResource "https://hl7.org/fhir/R4/codesystem.html#CodeSystem"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.copyright" #f)
    (schema-field 'caseSensitive 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.caseSensitive" #f)
    (schema-field 'valueSet 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.valueSet" #f)
    (schema-field 'hierarchyMeaning 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.hierarchyMeaning" #f)
    (schema-field 'compositional 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.compositional" #f)
    (schema-field 'versionNeeded 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.versionNeeded" #f)
    (schema-field 'content 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.content" #f)
    (schema-field 'supplements 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.supplements" #f)
    (schema-field 'count 0 1 (vector 'prim "unsignedInt") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.count" #f)
    (schema-field 'filter 0 '* (vector 'type 'CodeSystemFilter) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter" #f)
    (schema-field 'property 0 '* (vector 'type 'CodeSystemProperty) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property" #f)
    (schema-field 'concept 0 '* (vector 'type 'CodeSystemConcept) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept" #f)
             ) #f #f))
(register-element! "CodeSystem.url" (fhir-spec (string->symbol "CodeSystem.url") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.url" 'element))
(register-element! "CodeSystem.identifier" (fhir-spec (string->symbol "CodeSystem.identifier") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.identifier" 'element))
(register-element! "CodeSystem.version" (fhir-spec (string->symbol "CodeSystem.version") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.version" 'element))
(register-element! "CodeSystem.name" (fhir-spec (string->symbol "CodeSystem.name") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.name" 'element))
(register-element! "CodeSystem.title" (fhir-spec (string->symbol "CodeSystem.title") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.title" 'element))
(register-element! "CodeSystem.status" (fhir-spec (string->symbol "CodeSystem.status") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.status" 'element))
(register-element! "CodeSystem.experimental" (fhir-spec (string->symbol "CodeSystem.experimental") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.experimental" 'element))
(register-element! "CodeSystem.date" (fhir-spec (string->symbol "CodeSystem.date") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.date" 'element))
(register-element! "CodeSystem.publisher" (fhir-spec (string->symbol "CodeSystem.publisher") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.publisher" 'element))
(register-element! "CodeSystem.contact" (fhir-spec (string->symbol "CodeSystem.contact") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.contact" 'element))
(register-element! "CodeSystem.description" (fhir-spec (string->symbol "CodeSystem.description") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.description" 'element))
(register-element! "CodeSystem.useContext" (fhir-spec (string->symbol "CodeSystem.useContext") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.useContext" 'element))
(register-element! "CodeSystem.jurisdiction" (fhir-spec (string->symbol "CodeSystem.jurisdiction") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.jurisdiction" 'element))
(register-element! "CodeSystem.purpose" (fhir-spec (string->symbol "CodeSystem.purpose") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.purpose" 'element))
(register-element! "CodeSystem.copyright" (fhir-spec (string->symbol "CodeSystem.copyright") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.copyright" 'element))
(register-element! "CodeSystem.caseSensitive" (fhir-spec (string->symbol "CodeSystem.caseSensitive") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.caseSensitive" 'element))
(register-element! "CodeSystem.valueSet" (fhir-spec (string->symbol "CodeSystem.valueSet") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.valueSet" 'element))
(register-element! "CodeSystem.hierarchyMeaning" (fhir-spec (string->symbol "CodeSystem.hierarchyMeaning") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.hierarchyMeaning" 'element))
(register-element! "CodeSystem.compositional" (fhir-spec (string->symbol "CodeSystem.compositional") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.compositional" 'element))
(register-element! "CodeSystem.versionNeeded" (fhir-spec (string->symbol "CodeSystem.versionNeeded") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.versionNeeded" 'element))
(register-element! "CodeSystem.content" (fhir-spec (string->symbol "CodeSystem.content") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.content" 'element))
(register-element! "CodeSystem.supplements" (fhir-spec (string->symbol "CodeSystem.supplements") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.supplements" 'element))
(register-element! "CodeSystem.count" (fhir-spec (string->symbol "CodeSystem.count") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.count" 'element))
(register-element! "CodeSystem.filter" (fhir-spec (string->symbol "CodeSystem.filter") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter" 'element))
(register-element! "CodeSystem.property" (fhir-spec (string->symbol "CodeSystem.property") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property" 'element))
(register-element! "CodeSystem.concept" (fhir-spec (string->symbol "CodeSystem.concept") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept" 'element))

(register-type! 'CodeSystemFilter (fhir-spec 'CodeSystemFilter "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter" 'type)
  #:schema (type-schema 'CodeSystemFilter #f 'BackboneElement "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.code" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.description" #f)
    (schema-field 'operator 1 '* (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.operator" #f)
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.value" #f)
             ) #f #f))
(register-element! "CodeSystem.filter.code" (fhir-spec (string->symbol "CodeSystem.filter.code") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.code" 'element))
(register-element! "CodeSystem.filter.description" (fhir-spec (string->symbol "CodeSystem.filter.description") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.description" 'element))
(register-element! "CodeSystem.filter.operator" (fhir-spec (string->symbol "CodeSystem.filter.operator") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.operator" 'element))
(register-element! "CodeSystem.filter.value" (fhir-spec (string->symbol "CodeSystem.filter.value") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.filter.value" 'element))

(register-type! 'CodeSystemProperty (fhir-spec 'CodeSystemProperty "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property" 'type)
  #:schema (type-schema 'CodeSystemProperty #f 'BackboneElement "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.code" #f)
    (schema-field 'uri 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.uri" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.description" #f)
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.type" #f)
             ) #f #f))
(register-element! "CodeSystem.property.code" (fhir-spec (string->symbol "CodeSystem.property.code") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.code" 'element))
(register-element! "CodeSystem.property.uri" (fhir-spec (string->symbol "CodeSystem.property.uri") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.uri" 'element))
(register-element! "CodeSystem.property.description" (fhir-spec (string->symbol "CodeSystem.property.description") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.description" 'element))
(register-element! "CodeSystem.property.type" (fhir-spec (string->symbol "CodeSystem.property.type") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.property.type" 'element))

(register-type! 'CodeSystemConcept (fhir-spec 'CodeSystemConcept "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept" 'type)
  #:schema (type-schema 'CodeSystemConcept #f 'BackboneElement "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.code" #f)
    (schema-field 'display 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.display" #f)
    (schema-field 'definition 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.definition" #f)
    (schema-field 'designation 0 '* (vector 'type 'CodeSystemConceptDesignation) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation" #f)
    (schema-field 'property 0 '* (vector 'type 'CodeSystemConceptProperty) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property" #f)
    (schema-field 'concept 0 '* (vector 'type 'CodeSystemConcept) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.concept" #f)
             ) #f #f))
(register-element! "CodeSystem.concept.code" (fhir-spec (string->symbol "CodeSystem.concept.code") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.code" 'element))
(register-element! "CodeSystem.concept.display" (fhir-spec (string->symbol "CodeSystem.concept.display") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.display" 'element))
(register-element! "CodeSystem.concept.definition" (fhir-spec (string->symbol "CodeSystem.concept.definition") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.definition" 'element))
(register-element! "CodeSystem.concept.designation" (fhir-spec (string->symbol "CodeSystem.concept.designation") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation" 'element))
(register-element! "CodeSystem.concept.property" (fhir-spec (string->symbol "CodeSystem.concept.property") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property" 'element))
(register-element! "CodeSystem.concept.concept" (fhir-spec (string->symbol "CodeSystem.concept.concept") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.concept" 'element))

(register-type! 'CodeSystemConceptDesignation (fhir-spec 'CodeSystemConceptDesignation "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation" 'type)
  #:schema (type-schema 'CodeSystemConceptDesignation #f 'BackboneElement "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation"
             (list
    (schema-field 'language 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation.language" #f)
    (schema-field 'use 0 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation.use" #f)
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation.value" #f)
             ) #f #f))
(register-element! "CodeSystem.concept.designation.language" (fhir-spec (string->symbol "CodeSystem.concept.designation.language") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation.language" 'element))
(register-element! "CodeSystem.concept.designation.use" (fhir-spec (string->symbol "CodeSystem.concept.designation.use") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation.use" 'element))
(register-element! "CodeSystem.concept.designation.value" (fhir-spec (string->symbol "CodeSystem.concept.designation.value") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.designation.value" 'element))

(register-type! 'CodeSystemConceptProperty (fhir-spec 'CodeSystemConceptProperty "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property" 'type)
  #:schema (type-schema 'CodeSystemConceptProperty #f 'BackboneElement "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.code" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" #f)
             ) #f #f))
(register-element! "CodeSystem.concept.property.code" (fhir-spec (string->symbol "CodeSystem.concept.property.code") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.code" 'element))
(register-element! "CodeSystem.concept.property.value[x]" (fhir-spec (string->symbol "CodeSystem.concept.property.value[x]") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" 'element))
(register-element! "CodeSystem.concept.property.value[x]" (fhir-spec (string->symbol "CodeSystem.concept.property.value[x]") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" 'element))
(register-element! "CodeSystem.concept.property.value[x]" (fhir-spec (string->symbol "CodeSystem.concept.property.value[x]") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" 'element))
(register-element! "CodeSystem.concept.property.value[x]" (fhir-spec (string->symbol "CodeSystem.concept.property.value[x]") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" 'element))
(register-element! "CodeSystem.concept.property.value[x]" (fhir-spec (string->symbol "CodeSystem.concept.property.value[x]") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" 'element))
(register-element! "CodeSystem.concept.property.value[x]" (fhir-spec (string->symbol "CodeSystem.concept.property.value[x]") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" 'element))
(register-element! "CodeSystem.concept.property.value[x]" (fhir-spec (string->symbol "CodeSystem.concept.property.value[x]") "https://hl7.org/fhir/R4/codesystem.html#CodeSystem.concept.property.value[x]" 'element))

