#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Device (fhir-spec 'Device "https://hl7.org/fhir/R4/device.html#Device" 'type)
  #:schema (type-schema 'Device #f 'DomainResource "https://hl7.org/fhir/R4/device.html#Device"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/device.html#Device.identifier" #f)
    (schema-field 'definition 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/device.html#Device.definition" #f)
    (schema-field 'udiCarrier 0 '* (vector 'type 'DeviceUdiCarrier) #f "https://hl7.org/fhir/R4/device.html#Device.udiCarrier" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/device.html#Device.status" #f)
    (schema-field 'statusReason 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/device.html#Device.statusReason" #f)
    (schema-field 'distinctIdentifier 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.distinctIdentifier" #f)
    (schema-field 'manufacturer 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.manufacturer" #f)
    (schema-field 'manufactureDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/device.html#Device.manufactureDate" #f)
    (schema-field 'expirationDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/device.html#Device.expirationDate" #f)
    (schema-field 'lotNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.lotNumber" #f)
    (schema-field 'serialNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.serialNumber" #f)
    (schema-field 'deviceName 0 '* (vector 'type 'DeviceDeviceName) #f "https://hl7.org/fhir/R4/device.html#Device.deviceName" #f)
    (schema-field 'modelNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.modelNumber" #f)
    (schema-field 'partNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.partNumber" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/device.html#Device.type" #f)
    (schema-field 'specialization 0 '* (vector 'type 'DeviceSpecialization) #f "https://hl7.org/fhir/R4/device.html#Device.specialization" #f)
    (schema-field 'version 0 '* (vector 'type 'DeviceVersion) #f "https://hl7.org/fhir/R4/device.html#Device.version" #f)
    (schema-field 'property 0 '* (vector 'type 'DeviceProperty) #f "https://hl7.org/fhir/R4/device.html#Device.property" #f)
    (schema-field 'patient 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/device.html#Device.patient" #f)
    (schema-field 'owner 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/device.html#Device.owner" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactPoint) #f "https://hl7.org/fhir/R4/device.html#Device.contact" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/device.html#Device.location" #f)
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/device.html#Device.url" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/device.html#Device.note" #f)
    (schema-field 'safety 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/device.html#Device.safety" #f)
    (schema-field 'parent 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/device.html#Device.parent" #f)
             ) #f #f))
(register-element! "Device.identifier" (fhir-spec (string->symbol "Device.identifier") "https://hl7.org/fhir/R4/device.html#Device.identifier" 'element))
(register-element! "Device.definition" (fhir-spec (string->symbol "Device.definition") "https://hl7.org/fhir/R4/device.html#Device.definition" 'element))
(register-element! "Device.udiCarrier" (fhir-spec (string->symbol "Device.udiCarrier") "https://hl7.org/fhir/R4/device.html#Device.udiCarrier" 'element))
(register-element! "Device.status" (fhir-spec (string->symbol "Device.status") "https://hl7.org/fhir/R4/device.html#Device.status" 'element))
(register-element! "Device.statusReason" (fhir-spec (string->symbol "Device.statusReason") "https://hl7.org/fhir/R4/device.html#Device.statusReason" 'element))
(register-element! "Device.distinctIdentifier" (fhir-spec (string->symbol "Device.distinctIdentifier") "https://hl7.org/fhir/R4/device.html#Device.distinctIdentifier" 'element))
(register-element! "Device.manufacturer" (fhir-spec (string->symbol "Device.manufacturer") "https://hl7.org/fhir/R4/device.html#Device.manufacturer" 'element))
(register-element! "Device.manufactureDate" (fhir-spec (string->symbol "Device.manufactureDate") "https://hl7.org/fhir/R4/device.html#Device.manufactureDate" 'element))
(register-element! "Device.expirationDate" (fhir-spec (string->symbol "Device.expirationDate") "https://hl7.org/fhir/R4/device.html#Device.expirationDate" 'element))
(register-element! "Device.lotNumber" (fhir-spec (string->symbol "Device.lotNumber") "https://hl7.org/fhir/R4/device.html#Device.lotNumber" 'element))
(register-element! "Device.serialNumber" (fhir-spec (string->symbol "Device.serialNumber") "https://hl7.org/fhir/R4/device.html#Device.serialNumber" 'element))
(register-element! "Device.deviceName" (fhir-spec (string->symbol "Device.deviceName") "https://hl7.org/fhir/R4/device.html#Device.deviceName" 'element))
(register-element! "Device.modelNumber" (fhir-spec (string->symbol "Device.modelNumber") "https://hl7.org/fhir/R4/device.html#Device.modelNumber" 'element))
(register-element! "Device.partNumber" (fhir-spec (string->symbol "Device.partNumber") "https://hl7.org/fhir/R4/device.html#Device.partNumber" 'element))
(register-element! "Device.type" (fhir-spec (string->symbol "Device.type") "https://hl7.org/fhir/R4/device.html#Device.type" 'element))
(register-element! "Device.specialization" (fhir-spec (string->symbol "Device.specialization") "https://hl7.org/fhir/R4/device.html#Device.specialization" 'element))
(register-element! "Device.version" (fhir-spec (string->symbol "Device.version") "https://hl7.org/fhir/R4/device.html#Device.version" 'element))
(register-element! "Device.property" (fhir-spec (string->symbol "Device.property") "https://hl7.org/fhir/R4/device.html#Device.property" 'element))
(register-element! "Device.patient" (fhir-spec (string->symbol "Device.patient") "https://hl7.org/fhir/R4/device.html#Device.patient" 'element))
(register-element! "Device.owner" (fhir-spec (string->symbol "Device.owner") "https://hl7.org/fhir/R4/device.html#Device.owner" 'element))
(register-element! "Device.contact" (fhir-spec (string->symbol "Device.contact") "https://hl7.org/fhir/R4/device.html#Device.contact" 'element))
(register-element! "Device.location" (fhir-spec (string->symbol "Device.location") "https://hl7.org/fhir/R4/device.html#Device.location" 'element))
(register-element! "Device.url" (fhir-spec (string->symbol "Device.url") "https://hl7.org/fhir/R4/device.html#Device.url" 'element))
(register-element! "Device.note" (fhir-spec (string->symbol "Device.note") "https://hl7.org/fhir/R4/device.html#Device.note" 'element))
(register-element! "Device.safety" (fhir-spec (string->symbol "Device.safety") "https://hl7.org/fhir/R4/device.html#Device.safety" 'element))
(register-element! "Device.parent" (fhir-spec (string->symbol "Device.parent") "https://hl7.org/fhir/R4/device.html#Device.parent" 'element))

(register-type! 'DeviceUdiCarrier (fhir-spec 'DeviceUdiCarrier "https://hl7.org/fhir/R4/device.html#Device.udiCarrier" 'type)
  #:schema (type-schema 'DeviceUdiCarrier #f 'BackboneElement "https://hl7.org/fhir/R4/device.html#Device.udiCarrier"
             (list
    (schema-field 'deviceIdentifier 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.deviceIdentifier" #f)
    (schema-field 'issuer 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.issuer" #f)
    (schema-field 'jurisdiction 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.jurisdiction" #f)
    (schema-field 'carrierAIDC 0 1 (vector 'prim "base64Binary") #f "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.carrierAIDC" #f)
    (schema-field 'carrierHRF 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.carrierHRF" #f)
    (schema-field 'entryType 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.entryType" #f)
             ) #f #f))
(register-element! "Device.udiCarrier.deviceIdentifier" (fhir-spec (string->symbol "Device.udiCarrier.deviceIdentifier") "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.deviceIdentifier" 'element))
(register-element! "Device.udiCarrier.issuer" (fhir-spec (string->symbol "Device.udiCarrier.issuer") "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.issuer" 'element))
(register-element! "Device.udiCarrier.jurisdiction" (fhir-spec (string->symbol "Device.udiCarrier.jurisdiction") "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.jurisdiction" 'element))
(register-element! "Device.udiCarrier.carrierAIDC" (fhir-spec (string->symbol "Device.udiCarrier.carrierAIDC") "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.carrierAIDC" 'element))
(register-element! "Device.udiCarrier.carrierHRF" (fhir-spec (string->symbol "Device.udiCarrier.carrierHRF") "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.carrierHRF" 'element))
(register-element! "Device.udiCarrier.entryType" (fhir-spec (string->symbol "Device.udiCarrier.entryType") "https://hl7.org/fhir/R4/device.html#Device.udiCarrier.entryType" 'element))

(register-type! 'DeviceDeviceName (fhir-spec 'DeviceDeviceName "https://hl7.org/fhir/R4/device.html#Device.deviceName" 'type)
  #:schema (type-schema 'DeviceDeviceName #f 'BackboneElement "https://hl7.org/fhir/R4/device.html#Device.deviceName"
             (list
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.deviceName.name" #f)
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/device.html#Device.deviceName.type" #f)
             ) #f #f))
(register-element! "Device.deviceName.name" (fhir-spec (string->symbol "Device.deviceName.name") "https://hl7.org/fhir/R4/device.html#Device.deviceName.name" 'element))
(register-element! "Device.deviceName.type" (fhir-spec (string->symbol "Device.deviceName.type") "https://hl7.org/fhir/R4/device.html#Device.deviceName.type" 'element))

(register-type! 'DeviceSpecialization (fhir-spec 'DeviceSpecialization "https://hl7.org/fhir/R4/device.html#Device.specialization" 'type)
  #:schema (type-schema 'DeviceSpecialization #f 'BackboneElement "https://hl7.org/fhir/R4/device.html#Device.specialization"
             (list
    (schema-field 'systemType 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/device.html#Device.specialization.systemType" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.specialization.version" #f)
             ) #f #f))
(register-element! "Device.specialization.systemType" (fhir-spec (string->symbol "Device.specialization.systemType") "https://hl7.org/fhir/R4/device.html#Device.specialization.systemType" 'element))
(register-element! "Device.specialization.version" (fhir-spec (string->symbol "Device.specialization.version") "https://hl7.org/fhir/R4/device.html#Device.specialization.version" 'element))

(register-type! 'DeviceVersion (fhir-spec 'DeviceVersion "https://hl7.org/fhir/R4/device.html#Device.version" 'type)
  #:schema (type-schema 'DeviceVersion #f 'BackboneElement "https://hl7.org/fhir/R4/device.html#Device.version"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/device.html#Device.version.type" #f)
    (schema-field 'component 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/device.html#Device.version.component" #f)
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/device.html#Device.version.value" #f)
             ) #f #f))
(register-element! "Device.version.type" (fhir-spec (string->symbol "Device.version.type") "https://hl7.org/fhir/R4/device.html#Device.version.type" 'element))
(register-element! "Device.version.component" (fhir-spec (string->symbol "Device.version.component") "https://hl7.org/fhir/R4/device.html#Device.version.component" 'element))
(register-element! "Device.version.value" (fhir-spec (string->symbol "Device.version.value") "https://hl7.org/fhir/R4/device.html#Device.version.value" 'element))

(register-type! 'DeviceProperty (fhir-spec 'DeviceProperty "https://hl7.org/fhir/R4/device.html#Device.property" 'type)
  #:schema (type-schema 'DeviceProperty #f 'BackboneElement "https://hl7.org/fhir/R4/device.html#Device.property"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/device.html#Device.property.type" #f)
    (schema-field 'valueQuantity 0 '* (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/device.html#Device.property.valueQuantity" #f)
    (schema-field 'valueCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/device.html#Device.property.valueCode" #f)
             ) #f #f))
(register-element! "Device.property.type" (fhir-spec (string->symbol "Device.property.type") "https://hl7.org/fhir/R4/device.html#Device.property.type" 'element))
(register-element! "Device.property.valueQuantity" (fhir-spec (string->symbol "Device.property.valueQuantity") "https://hl7.org/fhir/R4/device.html#Device.property.valueQuantity" 'element))
(register-element! "Device.property.valueCode" (fhir-spec (string->symbol "Device.property.valueCode") "https://hl7.org/fhir/R4/device.html#Device.property.valueCode" 'element))

