#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Dosage (fhir-spec 'Dosage "https://hl7.org/fhir/R4/datatypes.html#Dosage" 'type)
  #:schema (type-schema 'Dosage #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#Dosage"
             (list
    (schema-field 'sequence 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.sequence" #f)
    (schema-field 'text 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.text" #f)
    (schema-field 'additionalInstruction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.additionalInstruction" #f)
    (schema-field 'patientInstruction 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.patientInstruction" #f)
    (schema-field 'timing 0 1 (vector 'type 'Timing) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.timing" #f)
    (schema-field 'site 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.site" #f)
    (schema-field 'route 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.route" #f)
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.method" #f)
    (schema-field 'doseAndRate 0 '* (vector 'type 'DosageDoseAndRate) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate" #f)
    (schema-field 'maxDosePerPeriod 0 1 (vector 'type 'Ratio) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.maxDosePerPeriod" #f)
    (schema-field 'maxDosePerAdministration 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.maxDosePerAdministration" #f)
    (schema-field 'maxDosePerLifetime 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.maxDosePerLifetime" #f)
    (schema-field 'asNeededBoolean 0 1 (vector 'prim "boolean") 'asNeeded "https://hl7.org/fhir/R4/datatypes.html#Dosage.asNeeded[x]" #f)
    (schema-field 'asNeededCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'asNeeded "https://hl7.org/fhir/R4/datatypes.html#Dosage.asNeeded[x]" #f)
             ) #f #f))
(register-element! "Dosage.sequence" (fhir-spec (string->symbol "Dosage.sequence") "https://hl7.org/fhir/R4/datatypes.html#Dosage.sequence" 'element))
(register-element! "Dosage.text" (fhir-spec (string->symbol "Dosage.text") "https://hl7.org/fhir/R4/datatypes.html#Dosage.text" 'element))
(register-element! "Dosage.additionalInstruction" (fhir-spec (string->symbol "Dosage.additionalInstruction") "https://hl7.org/fhir/R4/datatypes.html#Dosage.additionalInstruction" 'element))
(register-element! "Dosage.patientInstruction" (fhir-spec (string->symbol "Dosage.patientInstruction") "https://hl7.org/fhir/R4/datatypes.html#Dosage.patientInstruction" 'element))
(register-element! "Dosage.timing" (fhir-spec (string->symbol "Dosage.timing") "https://hl7.org/fhir/R4/datatypes.html#Dosage.timing" 'element))
(register-element! "Dosage.site" (fhir-spec (string->symbol "Dosage.site") "https://hl7.org/fhir/R4/datatypes.html#Dosage.site" 'element))
(register-element! "Dosage.route" (fhir-spec (string->symbol "Dosage.route") "https://hl7.org/fhir/R4/datatypes.html#Dosage.route" 'element))
(register-element! "Dosage.method" (fhir-spec (string->symbol "Dosage.method") "https://hl7.org/fhir/R4/datatypes.html#Dosage.method" 'element))
(register-element! "Dosage.doseAndRate" (fhir-spec (string->symbol "Dosage.doseAndRate") "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate" 'element))
(register-element! "Dosage.maxDosePerPeriod" (fhir-spec (string->symbol "Dosage.maxDosePerPeriod") "https://hl7.org/fhir/R4/datatypes.html#Dosage.maxDosePerPeriod" 'element))
(register-element! "Dosage.maxDosePerAdministration" (fhir-spec (string->symbol "Dosage.maxDosePerAdministration") "https://hl7.org/fhir/R4/datatypes.html#Dosage.maxDosePerAdministration" 'element))
(register-element! "Dosage.maxDosePerLifetime" (fhir-spec (string->symbol "Dosage.maxDosePerLifetime") "https://hl7.org/fhir/R4/datatypes.html#Dosage.maxDosePerLifetime" 'element))
(register-element! "Dosage.asNeeded[x]" (fhir-spec (string->symbol "Dosage.asNeeded[x]") "https://hl7.org/fhir/R4/datatypes.html#Dosage.asNeeded[x]" 'element))
(register-element! "Dosage.asNeeded[x]" (fhir-spec (string->symbol "Dosage.asNeeded[x]") "https://hl7.org/fhir/R4/datatypes.html#Dosage.asNeeded[x]" 'element))

(register-type! 'DosageDoseAndRate (fhir-spec 'DosageDoseAndRate "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate" 'type)
  #:schema (type-schema 'DosageDoseAndRate #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.type" #f)
    (schema-field 'doseRange 0 1 (vector 'type 'Range) 'dose "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.dose[x]" #f)
    (schema-field 'doseQuantity 0 1 (vector 'type 'Quantity) 'dose "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.dose[x]" #f)
    (schema-field 'rateRatio 0 1 (vector 'type 'Ratio) 'rate "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.rate[x]" #f)
    (schema-field 'rateRange 0 1 (vector 'type 'Range) 'rate "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.rate[x]" #f)
    (schema-field 'rateQuantity 0 1 (vector 'type 'Quantity) 'rate "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.rate[x]" #f)
             ) #f #f))
(register-element! "Dosage.doseAndRate.type" (fhir-spec (string->symbol "Dosage.doseAndRate.type") "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.type" 'element))
(register-element! "Dosage.doseAndRate.dose[x]" (fhir-spec (string->symbol "Dosage.doseAndRate.dose[x]") "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.dose[x]" 'element))
(register-element! "Dosage.doseAndRate.dose[x]" (fhir-spec (string->symbol "Dosage.doseAndRate.dose[x]") "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.dose[x]" 'element))
(register-element! "Dosage.doseAndRate.rate[x]" (fhir-spec (string->symbol "Dosage.doseAndRate.rate[x]") "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.rate[x]" 'element))
(register-element! "Dosage.doseAndRate.rate[x]" (fhir-spec (string->symbol "Dosage.doseAndRate.rate[x]") "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.rate[x]" 'element))
(register-element! "Dosage.doseAndRate.rate[x]" (fhir-spec (string->symbol "Dosage.doseAndRate.rate[x]") "https://hl7.org/fhir/R4/datatypes.html#Dosage.doseAndRate.rate[x]" 'element))

