#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ElementDefinition (fhir-spec 'ElementDefinition "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition" 'type)
  #:schema (type-schema 'ElementDefinition #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition"
             (list
    (schema-field 'path 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.path" #f)
    (schema-field 'representation 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.representation" #f)
    (schema-field 'sliceName 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.sliceName" #f)
    (schema-field 'sliceIsConstraining 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.sliceIsConstraining" #f)
    (schema-field 'label 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.label" #f)
    (schema-field 'code 0 '* (vector 'type 'Coding) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.code" #f)
    (schema-field 'slicing 0 1 (vector 'type 'ElementDefinitionSlicing) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing" #f)
    (schema-field 'short 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.short" #f)
    (schema-field 'definition 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.definition" #f)
    (schema-field 'comment 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.comment" #f)
    (schema-field 'requirements 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.requirements" #f)
    (schema-field 'alias 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.alias" #f)
    (schema-field 'min 0 1 (vector 'prim "unsignedInt") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.min" #f)
    (schema-field 'max 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.max" #f)
    (schema-field 'base 0 1 (vector 'type 'ElementDefinitionBase) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base" #f)
    (schema-field 'contentReference 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.contentReference" #f)
    (schema-field 'type 0 '* (vector 'type 'ElementDefinitionType) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type" #f)
    (schema-field 'meaningWhenMissing 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.meaningWhenMissing" #f)
    (schema-field 'orderMeaning 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.orderMeaning" #f)
    (schema-field 'example 0 '* (vector 'type 'ElementDefinitionExample) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example" #f)
    (schema-field 'maxLength 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxLength" #f)
    (schema-field 'condition 0 '* (vector 'prim "id") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.condition" #f)
    (schema-field 'constraint 0 '* (vector 'type 'ElementDefinitionConstraint) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint" #f)
    (schema-field 'mustSupport 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mustSupport" #f)
    (schema-field 'isModifier 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.isModifier" #f)
    (schema-field 'isModifierReason 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.isModifierReason" #f)
    (schema-field 'isSummary 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.isSummary" #f)
    (schema-field 'binding 0 1 (vector 'type 'ElementDefinitionBinding) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding" #f)
    (schema-field 'mapping 0 '* (vector 'type 'ElementDefinitionMapping) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping" #f)
    (schema-field 'defaultValueBase64Binary 0 1 (vector 'prim "base64Binary") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueBoolean 0 1 (vector 'prim "boolean") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueCanonical 0 1 (vector 'prim "canonical") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueCode 0 1 (vector 'prim "code") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueDate 0 1 (vector 'prim "date") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueDateTime 0 1 (vector 'prim "dateTime") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueDecimal 0 1 (vector 'prim "decimal") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueId 0 1 (vector 'prim "id") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueInstant 0 1 (vector 'prim "instant") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueInteger 0 1 (vector 'prim "integer") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueMarkdown 0 1 (vector 'prim "markdown") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueOid 0 1 (vector 'prim "oid") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValuePositiveInt 0 1 (vector 'prim "positiveInt") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueString 0 1 (vector 'prim "string") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueTime 0 1 (vector 'prim "time") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueUri 0 1 (vector 'prim "uri") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueUrl 0 1 (vector 'prim "url") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueUuid 0 1 (vector 'prim "uuid") 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueAddress 0 1 (vector 'type 'Address) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueAge 0 1 (vector 'type 'Age) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueAnnotation 0 1 (vector 'type 'Annotation) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueAttachment 0 1 (vector 'type 'Attachment) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueCoding 0 1 (vector 'type 'Coding) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueContactPoint 0 1 (vector 'type 'ContactPoint) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueCount 0 1 (vector 'type 'Count) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueDistance 0 1 (vector 'type 'Distance) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueDuration 0 1 (vector 'type 'Duration) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueHumanName 0 1 (vector 'type 'HumanName) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueIdentifier 0 1 (vector 'type 'Identifier) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueMoney 0 1 (vector 'type 'Money) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValuePeriod 0 1 (vector 'type 'Period) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueQuantity 0 1 (vector 'type 'Quantity) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueRange 0 1 (vector 'type 'Range) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueRatio 0 1 (vector 'type 'Ratio) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueReference 0 1 (vector 'type 'Reference) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueSampledData 0 1 (vector 'type 'SampledData) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueSignature 0 1 (vector 'type 'Signature) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueTiming 0 1 (vector 'type 'Timing) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueContactDetail 0 1 (vector 'type 'ContactDetail) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueContributor 0 1 (vector 'type 'Contributor) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueDataRequirement 0 1 (vector 'type 'DataRequirement) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueExpression 0 1 (vector 'type 'Expression) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueUsageContext 0 1 (vector 'type 'UsageContext) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueDosage 0 1 (vector 'type 'Dosage) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'defaultValueMeta 0 1 (vector 'type 'Meta) 'defaultValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" #f)
    (schema-field 'fixedBase64Binary 0 1 (vector 'prim "base64Binary") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedBoolean 0 1 (vector 'prim "boolean") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedCanonical 0 1 (vector 'prim "canonical") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedCode 0 1 (vector 'prim "code") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedDate 0 1 (vector 'prim "date") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedDateTime 0 1 (vector 'prim "dateTime") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedDecimal 0 1 (vector 'prim "decimal") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedId 0 1 (vector 'prim "id") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedInstant 0 1 (vector 'prim "instant") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedInteger 0 1 (vector 'prim "integer") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedMarkdown 0 1 (vector 'prim "markdown") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedOid 0 1 (vector 'prim "oid") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedPositiveInt 0 1 (vector 'prim "positiveInt") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedString 0 1 (vector 'prim "string") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedTime 0 1 (vector 'prim "time") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedUnsignedInt 0 1 (vector 'prim "unsignedInt") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedUri 0 1 (vector 'prim "uri") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedUrl 0 1 (vector 'prim "url") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedUuid 0 1 (vector 'prim "uuid") 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedAddress 0 1 (vector 'type 'Address) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedAge 0 1 (vector 'type 'Age) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedAnnotation 0 1 (vector 'type 'Annotation) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedAttachment 0 1 (vector 'type 'Attachment) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedCoding 0 1 (vector 'type 'Coding) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedContactPoint 0 1 (vector 'type 'ContactPoint) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedCount 0 1 (vector 'type 'Count) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedDistance 0 1 (vector 'type 'Distance) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedDuration 0 1 (vector 'type 'Duration) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedHumanName 0 1 (vector 'type 'HumanName) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedIdentifier 0 1 (vector 'type 'Identifier) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedMoney 0 1 (vector 'type 'Money) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedPeriod 0 1 (vector 'type 'Period) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedQuantity 0 1 (vector 'type 'Quantity) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedRange 0 1 (vector 'type 'Range) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedRatio 0 1 (vector 'type 'Ratio) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedReference 0 1 (vector 'type 'Reference) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedSampledData 0 1 (vector 'type 'SampledData) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedSignature 0 1 (vector 'type 'Signature) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedTiming 0 1 (vector 'type 'Timing) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedContactDetail 0 1 (vector 'type 'ContactDetail) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedContributor 0 1 (vector 'type 'Contributor) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedDataRequirement 0 1 (vector 'type 'DataRequirement) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedExpression 0 1 (vector 'type 'Expression) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedUsageContext 0 1 (vector 'type 'UsageContext) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedDosage 0 1 (vector 'type 'Dosage) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'fixedMeta 0 1 (vector 'type 'Meta) 'fixed "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" #f)
    (schema-field 'patternBase64Binary 0 1 (vector 'prim "base64Binary") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternBoolean 0 1 (vector 'prim "boolean") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternCanonical 0 1 (vector 'prim "canonical") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternCode 0 1 (vector 'prim "code") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternDate 0 1 (vector 'prim "date") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternDateTime 0 1 (vector 'prim "dateTime") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternDecimal 0 1 (vector 'prim "decimal") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternId 0 1 (vector 'prim "id") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternInstant 0 1 (vector 'prim "instant") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternInteger 0 1 (vector 'prim "integer") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternMarkdown 0 1 (vector 'prim "markdown") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternOid 0 1 (vector 'prim "oid") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternPositiveInt 0 1 (vector 'prim "positiveInt") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternString 0 1 (vector 'prim "string") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternTime 0 1 (vector 'prim "time") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternUnsignedInt 0 1 (vector 'prim "unsignedInt") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternUri 0 1 (vector 'prim "uri") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternUrl 0 1 (vector 'prim "url") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternUuid 0 1 (vector 'prim "uuid") 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternAddress 0 1 (vector 'type 'Address) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternAge 0 1 (vector 'type 'Age) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternAnnotation 0 1 (vector 'type 'Annotation) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternAttachment 0 1 (vector 'type 'Attachment) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternCoding 0 1 (vector 'type 'Coding) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternContactPoint 0 1 (vector 'type 'ContactPoint) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternCount 0 1 (vector 'type 'Count) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternDistance 0 1 (vector 'type 'Distance) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternDuration 0 1 (vector 'type 'Duration) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternHumanName 0 1 (vector 'type 'HumanName) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternIdentifier 0 1 (vector 'type 'Identifier) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternMoney 0 1 (vector 'type 'Money) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternPeriod 0 1 (vector 'type 'Period) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternQuantity 0 1 (vector 'type 'Quantity) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternRange 0 1 (vector 'type 'Range) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternRatio 0 1 (vector 'type 'Ratio) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternReference 0 1 (vector 'type 'Reference) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternSampledData 0 1 (vector 'type 'SampledData) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternSignature 0 1 (vector 'type 'Signature) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternTiming 0 1 (vector 'type 'Timing) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternContactDetail 0 1 (vector 'type 'ContactDetail) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternContributor 0 1 (vector 'type 'Contributor) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternDataRequirement 0 1 (vector 'type 'DataRequirement) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternExpression 0 1 (vector 'type 'Expression) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternUsageContext 0 1 (vector 'type 'UsageContext) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternDosage 0 1 (vector 'type 'Dosage) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'patternMeta 0 1 (vector 'type 'Meta) 'pattern "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" #f)
    (schema-field 'minValueDate 0 1 (vector 'prim "date") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValueDateTime 0 1 (vector 'prim "dateTime") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValueInstant 0 1 (vector 'prim "instant") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValueTime 0 1 (vector 'prim "time") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValueDecimal 0 1 (vector 'prim "decimal") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValueInteger 0 1 (vector 'prim "integer") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValuePositiveInt 0 1 (vector 'prim "positiveInt") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'minValueQuantity 0 1 (vector 'type 'Quantity) 'minValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" #f)
    (schema-field 'maxValueDate 0 1 (vector 'prim "date") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValueDateTime 0 1 (vector 'prim "dateTime") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValueInstant 0 1 (vector 'prim "instant") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValueTime 0 1 (vector 'prim "time") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValueDecimal 0 1 (vector 'prim "decimal") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValueInteger 0 1 (vector 'prim "integer") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValuePositiveInt 0 1 (vector 'prim "positiveInt") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
    (schema-field 'maxValueQuantity 0 1 (vector 'type 'Quantity) 'maxValue "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" #f)
             ) #f #f))
(register-element! "ElementDefinition.path" (fhir-spec (string->symbol "ElementDefinition.path") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.path" 'element))
(register-element! "ElementDefinition.representation" (fhir-spec (string->symbol "ElementDefinition.representation") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.representation" 'element))
(register-element! "ElementDefinition.sliceName" (fhir-spec (string->symbol "ElementDefinition.sliceName") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.sliceName" 'element))
(register-element! "ElementDefinition.sliceIsConstraining" (fhir-spec (string->symbol "ElementDefinition.sliceIsConstraining") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.sliceIsConstraining" 'element))
(register-element! "ElementDefinition.label" (fhir-spec (string->symbol "ElementDefinition.label") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.label" 'element))
(register-element! "ElementDefinition.code" (fhir-spec (string->symbol "ElementDefinition.code") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.code" 'element))
(register-element! "ElementDefinition.slicing" (fhir-spec (string->symbol "ElementDefinition.slicing") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing" 'element))
(register-element! "ElementDefinition.short" (fhir-spec (string->symbol "ElementDefinition.short") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.short" 'element))
(register-element! "ElementDefinition.definition" (fhir-spec (string->symbol "ElementDefinition.definition") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.definition" 'element))
(register-element! "ElementDefinition.comment" (fhir-spec (string->symbol "ElementDefinition.comment") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.comment" 'element))
(register-element! "ElementDefinition.requirements" (fhir-spec (string->symbol "ElementDefinition.requirements") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.requirements" 'element))
(register-element! "ElementDefinition.alias" (fhir-spec (string->symbol "ElementDefinition.alias") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.alias" 'element))
(register-element! "ElementDefinition.min" (fhir-spec (string->symbol "ElementDefinition.min") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.min" 'element))
(register-element! "ElementDefinition.max" (fhir-spec (string->symbol "ElementDefinition.max") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.max" 'element))
(register-element! "ElementDefinition.base" (fhir-spec (string->symbol "ElementDefinition.base") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base" 'element))
(register-element! "ElementDefinition.contentReference" (fhir-spec (string->symbol "ElementDefinition.contentReference") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.contentReference" 'element))
(register-element! "ElementDefinition.type" (fhir-spec (string->symbol "ElementDefinition.type") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type" 'element))
(register-element! "ElementDefinition.meaningWhenMissing" (fhir-spec (string->symbol "ElementDefinition.meaningWhenMissing") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.meaningWhenMissing" 'element))
(register-element! "ElementDefinition.orderMeaning" (fhir-spec (string->symbol "ElementDefinition.orderMeaning") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.orderMeaning" 'element))
(register-element! "ElementDefinition.example" (fhir-spec (string->symbol "ElementDefinition.example") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example" 'element))
(register-element! "ElementDefinition.maxLength" (fhir-spec (string->symbol "ElementDefinition.maxLength") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxLength" 'element))
(register-element! "ElementDefinition.condition" (fhir-spec (string->symbol "ElementDefinition.condition") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.condition" 'element))
(register-element! "ElementDefinition.constraint" (fhir-spec (string->symbol "ElementDefinition.constraint") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint" 'element))
(register-element! "ElementDefinition.mustSupport" (fhir-spec (string->symbol "ElementDefinition.mustSupport") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mustSupport" 'element))
(register-element! "ElementDefinition.isModifier" (fhir-spec (string->symbol "ElementDefinition.isModifier") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.isModifier" 'element))
(register-element! "ElementDefinition.isModifierReason" (fhir-spec (string->symbol "ElementDefinition.isModifierReason") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.isModifierReason" 'element))
(register-element! "ElementDefinition.isSummary" (fhir-spec (string->symbol "ElementDefinition.isSummary") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.isSummary" 'element))
(register-element! "ElementDefinition.binding" (fhir-spec (string->symbol "ElementDefinition.binding") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding" 'element))
(register-element! "ElementDefinition.mapping" (fhir-spec (string->symbol "ElementDefinition.mapping") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.defaultValue[x]" (fhir-spec (string->symbol "ElementDefinition.defaultValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.defaultValue[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.fixed[x]" (fhir-spec (string->symbol "ElementDefinition.fixed[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.fixed[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.pattern[x]" (fhir-spec (string->symbol "ElementDefinition.pattern[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.pattern[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.minValue[x]" (fhir-spec (string->symbol "ElementDefinition.minValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.minValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))
(register-element! "ElementDefinition.maxValue[x]" (fhir-spec (string->symbol "ElementDefinition.maxValue[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.maxValue[x]" 'element))

(register-type! 'ElementDefinitionSlicing (fhir-spec 'ElementDefinitionSlicing "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing" 'type)
  #:schema (type-schema 'ElementDefinitionSlicing #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing"
             (list
    (schema-field 'discriminator 0 '* (vector 'type 'ElementDefinitionSlicingDiscriminator) #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.description" #f)
    (schema-field 'ordered 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.ordered" #f)
    (schema-field 'rules 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.rules" #f)
             ) #f #f))
(register-element! "ElementDefinition.slicing.discriminator" (fhir-spec (string->symbol "ElementDefinition.slicing.discriminator") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator" 'element))
(register-element! "ElementDefinition.slicing.description" (fhir-spec (string->symbol "ElementDefinition.slicing.description") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.description" 'element))
(register-element! "ElementDefinition.slicing.ordered" (fhir-spec (string->symbol "ElementDefinition.slicing.ordered") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.ordered" 'element))
(register-element! "ElementDefinition.slicing.rules" (fhir-spec (string->symbol "ElementDefinition.slicing.rules") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.rules" 'element))

(register-type! 'ElementDefinitionSlicingDiscriminator (fhir-spec 'ElementDefinitionSlicingDiscriminator "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator" 'type)
  #:schema (type-schema 'ElementDefinitionSlicingDiscriminator #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator"
             (list
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator.type" #f)
    (schema-field 'path 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator.path" #f)
             ) #f #f))
(register-element! "ElementDefinition.slicing.discriminator.type" (fhir-spec (string->symbol "ElementDefinition.slicing.discriminator.type") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator.type" 'element))
(register-element! "ElementDefinition.slicing.discriminator.path" (fhir-spec (string->symbol "ElementDefinition.slicing.discriminator.path") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.slicing.discriminator.path" 'element))

(register-type! 'ElementDefinitionBase (fhir-spec 'ElementDefinitionBase "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base" 'type)
  #:schema (type-schema 'ElementDefinitionBase #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base"
             (list
    (schema-field 'path 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base.path" #f)
    (schema-field 'min 1 1 (vector 'prim "unsignedInt") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base.min" #f)
    (schema-field 'max 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base.max" #f)
             ) #f #f))
(register-element! "ElementDefinition.base.path" (fhir-spec (string->symbol "ElementDefinition.base.path") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base.path" 'element))
(register-element! "ElementDefinition.base.min" (fhir-spec (string->symbol "ElementDefinition.base.min") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base.min" 'element))
(register-element! "ElementDefinition.base.max" (fhir-spec (string->symbol "ElementDefinition.base.max") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.base.max" 'element))

(register-type! 'ElementDefinitionType (fhir-spec 'ElementDefinitionType "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type" 'type)
  #:schema (type-schema 'ElementDefinitionType #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type"
             (list
    (schema-field 'code 1 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.code" #f)
    (schema-field 'profile 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.profile" #f)
    (schema-field 'targetProfile 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.targetProfile" #f)
    (schema-field 'aggregation 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.aggregation" #f)
    (schema-field 'versioning 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.versioning" #f)
             ) #f #f))
(register-element! "ElementDefinition.type.code" (fhir-spec (string->symbol "ElementDefinition.type.code") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.code" 'element))
(register-element! "ElementDefinition.type.profile" (fhir-spec (string->symbol "ElementDefinition.type.profile") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.profile" 'element))
(register-element! "ElementDefinition.type.targetProfile" (fhir-spec (string->symbol "ElementDefinition.type.targetProfile") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.targetProfile" 'element))
(register-element! "ElementDefinition.type.aggregation" (fhir-spec (string->symbol "ElementDefinition.type.aggregation") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.aggregation" 'element))
(register-element! "ElementDefinition.type.versioning" (fhir-spec (string->symbol "ElementDefinition.type.versioning") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.type.versioning" 'element))

(register-type! 'ElementDefinitionExample (fhir-spec 'ElementDefinitionExample "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example" 'type)
  #:schema (type-schema 'ElementDefinitionExample #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example"
             (list
    (schema-field 'label 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.label" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueContributor 0 1 (vector 'type 'Contributor) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" #f)
             ) #f #f))
(register-element! "ElementDefinition.example.label" (fhir-spec (string->symbol "ElementDefinition.example.label") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.label" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))
(register-element! "ElementDefinition.example.value[x]" (fhir-spec (string->symbol "ElementDefinition.example.value[x]") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.example.value[x]" 'element))

(register-type! 'ElementDefinitionConstraint (fhir-spec 'ElementDefinitionConstraint "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint" 'type)
  #:schema (type-schema 'ElementDefinitionConstraint #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint"
             (list
    (schema-field 'key 1 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.key" #f)
    (schema-field 'requirements 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.requirements" #f)
    (schema-field 'severity 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.severity" #f)
    (schema-field 'human 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.human" #f)
    (schema-field 'expression 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.expression" #f)
    (schema-field 'xpath 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.xpath" #f)
    (schema-field 'source 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.source" #f)
             ) #f #f))
(register-element! "ElementDefinition.constraint.key" (fhir-spec (string->symbol "ElementDefinition.constraint.key") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.key" 'element))
(register-element! "ElementDefinition.constraint.requirements" (fhir-spec (string->symbol "ElementDefinition.constraint.requirements") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.requirements" 'element))
(register-element! "ElementDefinition.constraint.severity" (fhir-spec (string->symbol "ElementDefinition.constraint.severity") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.severity" 'element))
(register-element! "ElementDefinition.constraint.human" (fhir-spec (string->symbol "ElementDefinition.constraint.human") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.human" 'element))
(register-element! "ElementDefinition.constraint.expression" (fhir-spec (string->symbol "ElementDefinition.constraint.expression") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.expression" 'element))
(register-element! "ElementDefinition.constraint.xpath" (fhir-spec (string->symbol "ElementDefinition.constraint.xpath") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.xpath" 'element))
(register-element! "ElementDefinition.constraint.source" (fhir-spec (string->symbol "ElementDefinition.constraint.source") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.constraint.source" 'element))

(register-type! 'ElementDefinitionBinding (fhir-spec 'ElementDefinitionBinding "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding" 'type)
  #:schema (type-schema 'ElementDefinitionBinding #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding"
             (list
    (schema-field 'strength 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding.strength" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding.description" #f)
    (schema-field 'valueSet 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding.valueSet" #f)
             ) #f #f))
(register-element! "ElementDefinition.binding.strength" (fhir-spec (string->symbol "ElementDefinition.binding.strength") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding.strength" 'element))
(register-element! "ElementDefinition.binding.description" (fhir-spec (string->symbol "ElementDefinition.binding.description") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding.description" 'element))
(register-element! "ElementDefinition.binding.valueSet" (fhir-spec (string->symbol "ElementDefinition.binding.valueSet") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.binding.valueSet" 'element))

(register-type! 'ElementDefinitionMapping (fhir-spec 'ElementDefinitionMapping "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping" 'type)
  #:schema (type-schema 'ElementDefinitionMapping #f 'BackboneElement "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping"
             (list
    (schema-field 'identity 1 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.identity" #f)
    (schema-field 'language 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.language" #f)
    (schema-field 'map 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.map" #f)
    (schema-field 'comment 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.comment" #f)
             ) #f #f))
(register-element! "ElementDefinition.mapping.identity" (fhir-spec (string->symbol "ElementDefinition.mapping.identity") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.identity" 'element))
(register-element! "ElementDefinition.mapping.language" (fhir-spec (string->symbol "ElementDefinition.mapping.language") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.language" 'element))
(register-element! "ElementDefinition.mapping.map" (fhir-spec (string->symbol "ElementDefinition.mapping.map") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.map" 'element))
(register-element! "ElementDefinition.mapping.comment" (fhir-spec (string->symbol "ElementDefinition.mapping.comment") "https://hl7.org/fhir/R4/datatypes.html#ElementDefinition.mapping.comment" 'element))

