#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Encounter (fhir-spec 'Encounter "https://hl7.org/fhir/R4/encounter.html#Encounter" 'type)
  #:schema (type-schema 'Encounter #f 'DomainResource "https://hl7.org/fhir/R4/encounter.html#Encounter"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/encounter.html#Encounter.status" #f)
    (schema-field 'statusHistory 0 '* (vector 'type 'EncounterStatusHistory) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory" #f)
    (schema-field 'class 1 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.class" #f)
    (schema-field 'classHistory 0 '* (vector 'type 'EncounterClassHistory) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.type" #f)
    (schema-field 'serviceType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.serviceType" #f)
    (schema-field 'priority 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.priority" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.subject" #f)
    (schema-field 'episodeOfCare 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.episodeOfCare" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.basedOn" #f)
    (schema-field 'participant 0 '* (vector 'type 'EncounterParticipant) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.participant" #f)
    (schema-field 'appointment 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.appointment" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.period" #f)
    (schema-field 'length 0 1 (vector 'type 'Duration) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.length" #f)
    (schema-field 'reasonCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.reasonCode" #f)
    (schema-field 'reasonReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.reasonReference" #f)
    (schema-field 'diagnosis 0 '* (vector 'type 'EncounterDiagnosis) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis" #f)
    (schema-field 'account 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.account" #f)
    (schema-field 'hospitalization 0 1 (vector 'type 'EncounterHospitalization) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization" #f)
    (schema-field 'location 0 '* (vector 'type 'EncounterLocation) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.location" #f)
    (schema-field 'serviceProvider 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.serviceProvider" #f)
    (schema-field 'partOf 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.partOf" #f)
             ) #f #f))
(register-element! "Encounter.identifier" (fhir-spec (string->symbol "Encounter.identifier") "https://hl7.org/fhir/R4/encounter.html#Encounter.identifier" 'element))
(register-element! "Encounter.status" (fhir-spec (string->symbol "Encounter.status") "https://hl7.org/fhir/R4/encounter.html#Encounter.status" 'element))
(register-element! "Encounter.statusHistory" (fhir-spec (string->symbol "Encounter.statusHistory") "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory" 'element))
(register-element! "Encounter.class" (fhir-spec (string->symbol "Encounter.class") "https://hl7.org/fhir/R4/encounter.html#Encounter.class" 'element))
(register-element! "Encounter.classHistory" (fhir-spec (string->symbol "Encounter.classHistory") "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory" 'element))
(register-element! "Encounter.type" (fhir-spec (string->symbol "Encounter.type") "https://hl7.org/fhir/R4/encounter.html#Encounter.type" 'element))
(register-element! "Encounter.serviceType" (fhir-spec (string->symbol "Encounter.serviceType") "https://hl7.org/fhir/R4/encounter.html#Encounter.serviceType" 'element))
(register-element! "Encounter.priority" (fhir-spec (string->symbol "Encounter.priority") "https://hl7.org/fhir/R4/encounter.html#Encounter.priority" 'element))
(register-element! "Encounter.subject" (fhir-spec (string->symbol "Encounter.subject") "https://hl7.org/fhir/R4/encounter.html#Encounter.subject" 'element))
(register-element! "Encounter.episodeOfCare" (fhir-spec (string->symbol "Encounter.episodeOfCare") "https://hl7.org/fhir/R4/encounter.html#Encounter.episodeOfCare" 'element))
(register-element! "Encounter.basedOn" (fhir-spec (string->symbol "Encounter.basedOn") "https://hl7.org/fhir/R4/encounter.html#Encounter.basedOn" 'element))
(register-element! "Encounter.participant" (fhir-spec (string->symbol "Encounter.participant") "https://hl7.org/fhir/R4/encounter.html#Encounter.participant" 'element))
(register-element! "Encounter.appointment" (fhir-spec (string->symbol "Encounter.appointment") "https://hl7.org/fhir/R4/encounter.html#Encounter.appointment" 'element))
(register-element! "Encounter.period" (fhir-spec (string->symbol "Encounter.period") "https://hl7.org/fhir/R4/encounter.html#Encounter.period" 'element))
(register-element! "Encounter.length" (fhir-spec (string->symbol "Encounter.length") "https://hl7.org/fhir/R4/encounter.html#Encounter.length" 'element))
(register-element! "Encounter.reasonCode" (fhir-spec (string->symbol "Encounter.reasonCode") "https://hl7.org/fhir/R4/encounter.html#Encounter.reasonCode" 'element))
(register-element! "Encounter.reasonReference" (fhir-spec (string->symbol "Encounter.reasonReference") "https://hl7.org/fhir/R4/encounter.html#Encounter.reasonReference" 'element))
(register-element! "Encounter.diagnosis" (fhir-spec (string->symbol "Encounter.diagnosis") "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis" 'element))
(register-element! "Encounter.account" (fhir-spec (string->symbol "Encounter.account") "https://hl7.org/fhir/R4/encounter.html#Encounter.account" 'element))
(register-element! "Encounter.hospitalization" (fhir-spec (string->symbol "Encounter.hospitalization") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization" 'element))
(register-element! "Encounter.location" (fhir-spec (string->symbol "Encounter.location") "https://hl7.org/fhir/R4/encounter.html#Encounter.location" 'element))
(register-element! "Encounter.serviceProvider" (fhir-spec (string->symbol "Encounter.serviceProvider") "https://hl7.org/fhir/R4/encounter.html#Encounter.serviceProvider" 'element))
(register-element! "Encounter.partOf" (fhir-spec (string->symbol "Encounter.partOf") "https://hl7.org/fhir/R4/encounter.html#Encounter.partOf" 'element))

(register-type! 'EncounterStatusHistory (fhir-spec 'EncounterStatusHistory "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory" 'type)
  #:schema (type-schema 'EncounterStatusHistory #f 'BackboneElement "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory"
             (list
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory.status" #f)
    (schema-field 'period 1 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory.period" #f)
             ) #f #f))
(register-element! "Encounter.statusHistory.status" (fhir-spec (string->symbol "Encounter.statusHistory.status") "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory.status" 'element))
(register-element! "Encounter.statusHistory.period" (fhir-spec (string->symbol "Encounter.statusHistory.period") "https://hl7.org/fhir/R4/encounter.html#Encounter.statusHistory.period" 'element))

(register-type! 'EncounterClassHistory (fhir-spec 'EncounterClassHistory "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory" 'type)
  #:schema (type-schema 'EncounterClassHistory #f 'BackboneElement "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory"
             (list
    (schema-field 'class 1 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory.class" #f)
    (schema-field 'period 1 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory.period" #f)
             ) #f #f))
(register-element! "Encounter.classHistory.class" (fhir-spec (string->symbol "Encounter.classHistory.class") "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory.class" 'element))
(register-element! "Encounter.classHistory.period" (fhir-spec (string->symbol "Encounter.classHistory.period") "https://hl7.org/fhir/R4/encounter.html#Encounter.classHistory.period" 'element))

(register-type! 'EncounterParticipant (fhir-spec 'EncounterParticipant "https://hl7.org/fhir/R4/encounter.html#Encounter.participant" 'type)
  #:schema (type-schema 'EncounterParticipant #f 'BackboneElement "https://hl7.org/fhir/R4/encounter.html#Encounter.participant"
             (list
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.participant.type" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.participant.period" #f)
    (schema-field 'individual 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.participant.individual" #f)
             ) #f #f))
(register-element! "Encounter.participant.type" (fhir-spec (string->symbol "Encounter.participant.type") "https://hl7.org/fhir/R4/encounter.html#Encounter.participant.type" 'element))
(register-element! "Encounter.participant.period" (fhir-spec (string->symbol "Encounter.participant.period") "https://hl7.org/fhir/R4/encounter.html#Encounter.participant.period" 'element))
(register-element! "Encounter.participant.individual" (fhir-spec (string->symbol "Encounter.participant.individual") "https://hl7.org/fhir/R4/encounter.html#Encounter.participant.individual" 'element))

(register-type! 'EncounterDiagnosis (fhir-spec 'EncounterDiagnosis "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis" 'type)
  #:schema (type-schema 'EncounterDiagnosis #f 'BackboneElement "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis"
             (list
    (schema-field 'condition 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis.condition" #f)
    (schema-field 'use 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis.use" #f)
    (schema-field 'rank 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis.rank" #f)
             ) #f #f))
(register-element! "Encounter.diagnosis.condition" (fhir-spec (string->symbol "Encounter.diagnosis.condition") "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis.condition" 'element))
(register-element! "Encounter.diagnosis.use" (fhir-spec (string->symbol "Encounter.diagnosis.use") "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis.use" 'element))
(register-element! "Encounter.diagnosis.rank" (fhir-spec (string->symbol "Encounter.diagnosis.rank") "https://hl7.org/fhir/R4/encounter.html#Encounter.diagnosis.rank" 'element))

(register-type! 'EncounterHospitalization (fhir-spec 'EncounterHospitalization "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization" 'type)
  #:schema (type-schema 'EncounterHospitalization #f 'BackboneElement "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization"
             (list
    (schema-field 'preAdmissionIdentifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.preAdmissionIdentifier" #f)
    (schema-field 'origin 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.origin" #f)
    (schema-field 'admitSource 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.admitSource" #f)
    (schema-field 'reAdmission 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.reAdmission" #f)
    (schema-field 'dietPreference 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.dietPreference" #f)
    (schema-field 'specialCourtesy 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.specialCourtesy" #f)
    (schema-field 'specialArrangement 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.specialArrangement" #f)
    (schema-field 'destination 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.destination" #f)
    (schema-field 'dischargeDisposition 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.dischargeDisposition" #f)
             ) #f #f))
(register-element! "Encounter.hospitalization.preAdmissionIdentifier" (fhir-spec (string->symbol "Encounter.hospitalization.preAdmissionIdentifier") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.preAdmissionIdentifier" 'element))
(register-element! "Encounter.hospitalization.origin" (fhir-spec (string->symbol "Encounter.hospitalization.origin") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.origin" 'element))
(register-element! "Encounter.hospitalization.admitSource" (fhir-spec (string->symbol "Encounter.hospitalization.admitSource") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.admitSource" 'element))
(register-element! "Encounter.hospitalization.reAdmission" (fhir-spec (string->symbol "Encounter.hospitalization.reAdmission") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.reAdmission" 'element))
(register-element! "Encounter.hospitalization.dietPreference" (fhir-spec (string->symbol "Encounter.hospitalization.dietPreference") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.dietPreference" 'element))
(register-element! "Encounter.hospitalization.specialCourtesy" (fhir-spec (string->symbol "Encounter.hospitalization.specialCourtesy") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.specialCourtesy" 'element))
(register-element! "Encounter.hospitalization.specialArrangement" (fhir-spec (string->symbol "Encounter.hospitalization.specialArrangement") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.specialArrangement" 'element))
(register-element! "Encounter.hospitalization.destination" (fhir-spec (string->symbol "Encounter.hospitalization.destination") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.destination" 'element))
(register-element! "Encounter.hospitalization.dischargeDisposition" (fhir-spec (string->symbol "Encounter.hospitalization.dischargeDisposition") "https://hl7.org/fhir/R4/encounter.html#Encounter.hospitalization.dischargeDisposition" 'element))

(register-type! 'EncounterLocation (fhir-spec 'EncounterLocation "https://hl7.org/fhir/R4/encounter.html#Encounter.location" 'type)
  #:schema (type-schema 'EncounterLocation #f 'BackboneElement "https://hl7.org/fhir/R4/encounter.html#Encounter.location"
             (list
    (schema-field 'location 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.location.location" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/encounter.html#Encounter.location.status" #f)
    (schema-field 'physicalType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.location.physicalType" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/encounter.html#Encounter.location.period" #f)
             ) #f #f))
(register-element! "Encounter.location.location" (fhir-spec (string->symbol "Encounter.location.location") "https://hl7.org/fhir/R4/encounter.html#Encounter.location.location" 'element))
(register-element! "Encounter.location.status" (fhir-spec (string->symbol "Encounter.location.status") "https://hl7.org/fhir/R4/encounter.html#Encounter.location.status" 'element))
(register-element! "Encounter.location.physicalType" (fhir-spec (string->symbol "Encounter.location.physicalType") "https://hl7.org/fhir/R4/encounter.html#Encounter.location.physicalType" 'element))
(register-element! "Encounter.location.period" (fhir-spec (string->symbol "Encounter.location.period") "https://hl7.org/fhir/R4/encounter.html#Encounter.location.period" 'element))

