#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ExplanationOfBenefit (fhir-spec 'ExplanationOfBenefit "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit" 'type)
  #:schema (type-schema 'ExplanationOfBenefit #f 'DomainResource "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.status" #f)
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.type" #f)
    (schema-field 'subType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.subType" #f)
    (schema-field 'use 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.use" #f)
    (schema-field 'patient 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.patient" #f)
    (schema-field 'billablePeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.billablePeriod" #f)
    (schema-field 'created 1 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.created" #f)
    (schema-field 'enterer 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.enterer" #f)
    (schema-field 'insurer 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurer" #f)
    (schema-field 'provider 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.provider" #f)
    (schema-field 'priority 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.priority" #f)
    (schema-field 'fundsReserveRequested 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.fundsReserveRequested" #f)
    (schema-field 'fundsReserve 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.fundsReserve" #f)
    (schema-field 'related 0 '* (vector 'type 'ExplanationOfBenefitRelated) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related" #f)
    (schema-field 'prescription 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.prescription" #f)
    (schema-field 'originalPrescription 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.originalPrescription" #f)
    (schema-field 'payee 0 1 (vector 'type 'ExplanationOfBenefitPayee) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee" #f)
    (schema-field 'referral 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.referral" #f)
    (schema-field 'facility 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.facility" #f)
    (schema-field 'claim 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.claim" #f)
    (schema-field 'claimResponse 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.claimResponse" #f)
    (schema-field 'outcome 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.outcome" #f)
    (schema-field 'disposition 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.disposition" #f)
    (schema-field 'preAuthRef 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.preAuthRef" #f)
    (schema-field 'preAuthRefPeriod 0 '* (vector 'type 'Period) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.preAuthRefPeriod" #f)
    (schema-field 'careTeam 0 '* (vector 'type 'ExplanationOfBenefitCareTeam) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'ExplanationOfBenefitSupportingInfo) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo" #f)
    (schema-field 'diagnosis 0 '* (vector 'type 'ExplanationOfBenefitDiagnosis) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis" #f)
    (schema-field 'procedure 0 '* (vector 'type 'ExplanationOfBenefitProcedure) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure" #f)
    (schema-field 'precedence 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.precedence" #f)
    (schema-field 'insurance 1 '* (vector 'type 'ExplanationOfBenefitInsurance) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance" #f)
    (schema-field 'accident 0 1 (vector 'type 'ExplanationOfBenefitAccident) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident" #f)
    (schema-field 'item 0 '* (vector 'type 'ExplanationOfBenefitItem) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item" #f)
    (schema-field 'addItem 0 '* (vector 'type 'ExplanationOfBenefitAddItem) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ExplanationOfBenefitItemAdjudication) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.adjudication" #f)
    (schema-field 'total 0 '* (vector 'type 'ExplanationOfBenefitTotal) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total" #f)
    (schema-field 'payment 0 1 (vector 'type 'ExplanationOfBenefitPayment) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment" #f)
    (schema-field 'formCode 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.formCode" #f)
    (schema-field 'form 0 1 (vector 'type 'Attachment) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.form" #f)
    (schema-field 'processNote 0 '* (vector 'type 'ExplanationOfBenefitProcessNote) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote" #f)
    (schema-field 'benefitPeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitPeriod" #f)
    (schema-field 'benefitBalance 0 '* (vector 'type 'ExplanationOfBenefitBenefitBalance) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.identifier" (fhir-spec (string->symbol "ExplanationOfBenefit.identifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.identifier" 'element))
(register-element! "ExplanationOfBenefit.status" (fhir-spec (string->symbol "ExplanationOfBenefit.status") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.status" 'element))
(register-element! "ExplanationOfBenefit.type" (fhir-spec (string->symbol "ExplanationOfBenefit.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.type" 'element))
(register-element! "ExplanationOfBenefit.subType" (fhir-spec (string->symbol "ExplanationOfBenefit.subType") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.subType" 'element))
(register-element! "ExplanationOfBenefit.use" (fhir-spec (string->symbol "ExplanationOfBenefit.use") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.use" 'element))
(register-element! "ExplanationOfBenefit.patient" (fhir-spec (string->symbol "ExplanationOfBenefit.patient") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.patient" 'element))
(register-element! "ExplanationOfBenefit.billablePeriod" (fhir-spec (string->symbol "ExplanationOfBenefit.billablePeriod") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.billablePeriod" 'element))
(register-element! "ExplanationOfBenefit.created" (fhir-spec (string->symbol "ExplanationOfBenefit.created") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.created" 'element))
(register-element! "ExplanationOfBenefit.enterer" (fhir-spec (string->symbol "ExplanationOfBenefit.enterer") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.enterer" 'element))
(register-element! "ExplanationOfBenefit.insurer" (fhir-spec (string->symbol "ExplanationOfBenefit.insurer") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurer" 'element))
(register-element! "ExplanationOfBenefit.provider" (fhir-spec (string->symbol "ExplanationOfBenefit.provider") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.provider" 'element))
(register-element! "ExplanationOfBenefit.priority" (fhir-spec (string->symbol "ExplanationOfBenefit.priority") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.priority" 'element))
(register-element! "ExplanationOfBenefit.fundsReserveRequested" (fhir-spec (string->symbol "ExplanationOfBenefit.fundsReserveRequested") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.fundsReserveRequested" 'element))
(register-element! "ExplanationOfBenefit.fundsReserve" (fhir-spec (string->symbol "ExplanationOfBenefit.fundsReserve") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.fundsReserve" 'element))
(register-element! "ExplanationOfBenefit.related" (fhir-spec (string->symbol "ExplanationOfBenefit.related") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related" 'element))
(register-element! "ExplanationOfBenefit.prescription" (fhir-spec (string->symbol "ExplanationOfBenefit.prescription") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.prescription" 'element))
(register-element! "ExplanationOfBenefit.originalPrescription" (fhir-spec (string->symbol "ExplanationOfBenefit.originalPrescription") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.originalPrescription" 'element))
(register-element! "ExplanationOfBenefit.payee" (fhir-spec (string->symbol "ExplanationOfBenefit.payee") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee" 'element))
(register-element! "ExplanationOfBenefit.referral" (fhir-spec (string->symbol "ExplanationOfBenefit.referral") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.referral" 'element))
(register-element! "ExplanationOfBenefit.facility" (fhir-spec (string->symbol "ExplanationOfBenefit.facility") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.facility" 'element))
(register-element! "ExplanationOfBenefit.claim" (fhir-spec (string->symbol "ExplanationOfBenefit.claim") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.claim" 'element))
(register-element! "ExplanationOfBenefit.claimResponse" (fhir-spec (string->symbol "ExplanationOfBenefit.claimResponse") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.claimResponse" 'element))
(register-element! "ExplanationOfBenefit.outcome" (fhir-spec (string->symbol "ExplanationOfBenefit.outcome") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.outcome" 'element))
(register-element! "ExplanationOfBenefit.disposition" (fhir-spec (string->symbol "ExplanationOfBenefit.disposition") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.disposition" 'element))
(register-element! "ExplanationOfBenefit.preAuthRef" (fhir-spec (string->symbol "ExplanationOfBenefit.preAuthRef") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.preAuthRef" 'element))
(register-element! "ExplanationOfBenefit.preAuthRefPeriod" (fhir-spec (string->symbol "ExplanationOfBenefit.preAuthRefPeriod") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.preAuthRefPeriod" 'element))
(register-element! "ExplanationOfBenefit.careTeam" (fhir-spec (string->symbol "ExplanationOfBenefit.careTeam") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo" 'element))
(register-element! "ExplanationOfBenefit.diagnosis" (fhir-spec (string->symbol "ExplanationOfBenefit.diagnosis") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis" 'element))
(register-element! "ExplanationOfBenefit.procedure" (fhir-spec (string->symbol "ExplanationOfBenefit.procedure") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure" 'element))
(register-element! "ExplanationOfBenefit.precedence" (fhir-spec (string->symbol "ExplanationOfBenefit.precedence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.precedence" 'element))
(register-element! "ExplanationOfBenefit.insurance" (fhir-spec (string->symbol "ExplanationOfBenefit.insurance") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance" 'element))
(register-element! "ExplanationOfBenefit.accident" (fhir-spec (string->symbol "ExplanationOfBenefit.accident") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident" 'element))
(register-element! "ExplanationOfBenefit.item" (fhir-spec (string->symbol "ExplanationOfBenefit.item") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item" 'element))
(register-element! "ExplanationOfBenefit.addItem" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem" 'element))
(register-element! "ExplanationOfBenefit.adjudication" (fhir-spec (string->symbol "ExplanationOfBenefit.adjudication") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.adjudication" 'element))
(register-element! "ExplanationOfBenefit.total" (fhir-spec (string->symbol "ExplanationOfBenefit.total") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total" 'element))
(register-element! "ExplanationOfBenefit.payment" (fhir-spec (string->symbol "ExplanationOfBenefit.payment") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment" 'element))
(register-element! "ExplanationOfBenefit.formCode" (fhir-spec (string->symbol "ExplanationOfBenefit.formCode") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.formCode" 'element))
(register-element! "ExplanationOfBenefit.form" (fhir-spec (string->symbol "ExplanationOfBenefit.form") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.form" 'element))
(register-element! "ExplanationOfBenefit.processNote" (fhir-spec (string->symbol "ExplanationOfBenefit.processNote") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote" 'element))
(register-element! "ExplanationOfBenefit.benefitPeriod" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitPeriod") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitPeriod" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance" 'element))

(register-type! 'ExplanationOfBenefitRelated (fhir-spec 'ExplanationOfBenefitRelated "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related" 'type)
  #:schema (type-schema 'ExplanationOfBenefitRelated #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related"
             (list
    (schema-field 'claim 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related.claim" #f)
    (schema-field 'relationship 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related.relationship" #f)
    (schema-field 'reference 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related.reference" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.related.claim" (fhir-spec (string->symbol "ExplanationOfBenefit.related.claim") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related.claim" 'element))
(register-element! "ExplanationOfBenefit.related.relationship" (fhir-spec (string->symbol "ExplanationOfBenefit.related.relationship") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related.relationship" 'element))
(register-element! "ExplanationOfBenefit.related.reference" (fhir-spec (string->symbol "ExplanationOfBenefit.related.reference") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.related.reference" 'element))

(register-type! 'ExplanationOfBenefitPayee (fhir-spec 'ExplanationOfBenefitPayee "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee" 'type)
  #:schema (type-schema 'ExplanationOfBenefitPayee #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee.type" #f)
    (schema-field 'party 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee.party" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.payee.type" (fhir-spec (string->symbol "ExplanationOfBenefit.payee.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee.type" 'element))
(register-element! "ExplanationOfBenefit.payee.party" (fhir-spec (string->symbol "ExplanationOfBenefit.payee.party") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payee.party" 'element))

(register-type! 'ExplanationOfBenefitCareTeam (fhir-spec 'ExplanationOfBenefitCareTeam "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam" 'type)
  #:schema (type-schema 'ExplanationOfBenefitCareTeam #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.sequence" #f)
    (schema-field 'provider 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.provider" #f)
    (schema-field 'responsible 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.responsible" #f)
    (schema-field 'role 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.role" #f)
    (schema-field 'qualification 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.qualification" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.careTeam.sequence" (fhir-spec (string->symbol "ExplanationOfBenefit.careTeam.sequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.sequence" 'element))
(register-element! "ExplanationOfBenefit.careTeam.provider" (fhir-spec (string->symbol "ExplanationOfBenefit.careTeam.provider") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.provider" 'element))
(register-element! "ExplanationOfBenefit.careTeam.responsible" (fhir-spec (string->symbol "ExplanationOfBenefit.careTeam.responsible") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.responsible" 'element))
(register-element! "ExplanationOfBenefit.careTeam.role" (fhir-spec (string->symbol "ExplanationOfBenefit.careTeam.role") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.role" 'element))
(register-element! "ExplanationOfBenefit.careTeam.qualification" (fhir-spec (string->symbol "ExplanationOfBenefit.careTeam.qualification") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.careTeam.qualification" 'element))

(register-type! 'ExplanationOfBenefitSupportingInfo (fhir-spec 'ExplanationOfBenefitSupportingInfo "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo" 'type)
  #:schema (type-schema 'ExplanationOfBenefitSupportingInfo #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.sequence" #f)
    (schema-field 'category 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.category" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.code" #f)
    (schema-field 'reason 0 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.reason" #f)
    (schema-field 'timingDate 0 1 (vector 'prim "date") 'timing "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.timing[x]" #f)
    (schema-field 'timingPeriod 0 1 (vector 'type 'Period) 'timing "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.timing[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.supportingInfo.sequence" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.sequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.sequence" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.category" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.category") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.category" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.code" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.code") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.code" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.reason" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.reason") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.reason" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.timing[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.timing[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.timing[x]" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.timing[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.timing[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.timing[x]" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.value[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.value[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.value[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.value[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.value[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.value[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.value[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.value[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" 'element))
(register-element! "ExplanationOfBenefit.supportingInfo.value[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.supportingInfo.value[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.supportingInfo.value[x]" 'element))

(register-type! 'ExplanationOfBenefitDiagnosis (fhir-spec 'ExplanationOfBenefitDiagnosis "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis" 'type)
  #:schema (type-schema 'ExplanationOfBenefitDiagnosis #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.sequence" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.type" #f)
    (schema-field 'onAdmission 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.onAdmission" #f)
    (schema-field 'packageCode 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.packageCode" #f)
    (schema-field 'diagnosisCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'diagnosis "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.diagnosis[x]" #f)
    (schema-field 'diagnosisReference 0 1 (vector 'type 'Reference) 'diagnosis "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.diagnosis[x]" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.diagnosis.sequence" (fhir-spec (string->symbol "ExplanationOfBenefit.diagnosis.sequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.sequence" 'element))
(register-element! "ExplanationOfBenefit.diagnosis.type" (fhir-spec (string->symbol "ExplanationOfBenefit.diagnosis.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.type" 'element))
(register-element! "ExplanationOfBenefit.diagnosis.onAdmission" (fhir-spec (string->symbol "ExplanationOfBenefit.diagnosis.onAdmission") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.onAdmission" 'element))
(register-element! "ExplanationOfBenefit.diagnosis.packageCode" (fhir-spec (string->symbol "ExplanationOfBenefit.diagnosis.packageCode") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.packageCode" 'element))
(register-element! "ExplanationOfBenefit.diagnosis.diagnosis[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.diagnosis.diagnosis[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.diagnosis[x]" 'element))
(register-element! "ExplanationOfBenefit.diagnosis.diagnosis[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.diagnosis.diagnosis[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.diagnosis.diagnosis[x]" 'element))

(register-type! 'ExplanationOfBenefitProcedure (fhir-spec 'ExplanationOfBenefitProcedure "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure" 'type)
  #:schema (type-schema 'ExplanationOfBenefitProcedure #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.sequence" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.type" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.date" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.udi" #f)
    (schema-field 'procedureCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'procedure "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.procedure[x]" #f)
    (schema-field 'procedureReference 0 1 (vector 'type 'Reference) 'procedure "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.procedure[x]" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.procedure.sequence" (fhir-spec (string->symbol "ExplanationOfBenefit.procedure.sequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.sequence" 'element))
(register-element! "ExplanationOfBenefit.procedure.type" (fhir-spec (string->symbol "ExplanationOfBenefit.procedure.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.type" 'element))
(register-element! "ExplanationOfBenefit.procedure.date" (fhir-spec (string->symbol "ExplanationOfBenefit.procedure.date") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.date" 'element))
(register-element! "ExplanationOfBenefit.procedure.udi" (fhir-spec (string->symbol "ExplanationOfBenefit.procedure.udi") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.udi" 'element))
(register-element! "ExplanationOfBenefit.procedure.procedure[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.procedure.procedure[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.procedure[x]" 'element))
(register-element! "ExplanationOfBenefit.procedure.procedure[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.procedure.procedure[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.procedure.procedure[x]" 'element))

(register-type! 'ExplanationOfBenefitInsurance (fhir-spec 'ExplanationOfBenefitInsurance "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance" 'type)
  #:schema (type-schema 'ExplanationOfBenefitInsurance #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance"
             (list
    (schema-field 'focal 1 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance.focal" #f)
    (schema-field 'coverage 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance.coverage" #f)
    (schema-field 'preAuthRef 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance.preAuthRef" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.insurance.focal" (fhir-spec (string->symbol "ExplanationOfBenefit.insurance.focal") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance.focal" 'element))
(register-element! "ExplanationOfBenefit.insurance.coverage" (fhir-spec (string->symbol "ExplanationOfBenefit.insurance.coverage") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance.coverage" 'element))
(register-element! "ExplanationOfBenefit.insurance.preAuthRef" (fhir-spec (string->symbol "ExplanationOfBenefit.insurance.preAuthRef") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.insurance.preAuthRef" 'element))

(register-type! 'ExplanationOfBenefitAccident (fhir-spec 'ExplanationOfBenefitAccident "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident" 'type)
  #:schema (type-schema 'ExplanationOfBenefitAccident #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident"
             (list
    (schema-field 'date 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.date" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.type" #f)
    (schema-field 'locationAddress 0 1 (vector 'type 'Address) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.location[x]" #f)
    (schema-field 'locationReference 0 1 (vector 'type 'Reference) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.location[x]" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.accident.date" (fhir-spec (string->symbol "ExplanationOfBenefit.accident.date") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.date" 'element))
(register-element! "ExplanationOfBenefit.accident.type" (fhir-spec (string->symbol "ExplanationOfBenefit.accident.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.type" 'element))
(register-element! "ExplanationOfBenefit.accident.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.accident.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.location[x]" 'element))
(register-element! "ExplanationOfBenefit.accident.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.accident.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.accident.location[x]" 'element))

(register-type! 'ExplanationOfBenefitItem (fhir-spec 'ExplanationOfBenefitItem "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item" 'type)
  #:schema (type-schema 'ExplanationOfBenefitItem #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.sequence" #f)
    (schema-field 'careTeamSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.careTeamSequence" #f)
    (schema-field 'diagnosisSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.diagnosisSequence" #f)
    (schema-field 'procedureSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.procedureSequence" #f)
    (schema-field 'informationSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.informationSequence" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.revenue" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.category" #f)
    (schema-field 'productOrService 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.productOrService" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.programCode" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.factor" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.net" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.udi" #f)
    (schema-field 'bodySite 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.bodySite" #f)
    (schema-field 'subSite 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.subSite" #f)
    (schema-field 'encounter 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.encounter" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.noteNumber" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ExplanationOfBenefitItemAdjudication) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication" #f)
    (schema-field 'detail 0 '* (vector 'type 'ExplanationOfBenefitItemDetail) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail" #f)
    (schema-field 'servicedDate 0 1 (vector 'prim "date") 'serviced "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.serviced[x]" #f)
    (schema-field 'servicedPeriod 0 1 (vector 'type 'Period) 'serviced "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.serviced[x]" #f)
    (schema-field 'locationCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.location[x]" #f)
    (schema-field 'locationAddress 0 1 (vector 'type 'Address) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.location[x]" #f)
    (schema-field 'locationReference 0 1 (vector 'type 'Reference) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.location[x]" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.item.sequence" (fhir-spec (string->symbol "ExplanationOfBenefit.item.sequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.sequence" 'element))
(register-element! "ExplanationOfBenefit.item.careTeamSequence" (fhir-spec (string->symbol "ExplanationOfBenefit.item.careTeamSequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.careTeamSequence" 'element))
(register-element! "ExplanationOfBenefit.item.diagnosisSequence" (fhir-spec (string->symbol "ExplanationOfBenefit.item.diagnosisSequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.diagnosisSequence" 'element))
(register-element! "ExplanationOfBenefit.item.procedureSequence" (fhir-spec (string->symbol "ExplanationOfBenefit.item.procedureSequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.procedureSequence" 'element))
(register-element! "ExplanationOfBenefit.item.informationSequence" (fhir-spec (string->symbol "ExplanationOfBenefit.item.informationSequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.informationSequence" 'element))
(register-element! "ExplanationOfBenefit.item.revenue" (fhir-spec (string->symbol "ExplanationOfBenefit.item.revenue") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.revenue" 'element))
(register-element! "ExplanationOfBenefit.item.category" (fhir-spec (string->symbol "ExplanationOfBenefit.item.category") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.category" 'element))
(register-element! "ExplanationOfBenefit.item.productOrService" (fhir-spec (string->symbol "ExplanationOfBenefit.item.productOrService") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.productOrService" 'element))
(register-element! "ExplanationOfBenefit.item.modifier" (fhir-spec (string->symbol "ExplanationOfBenefit.item.modifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.modifier" 'element))
(register-element! "ExplanationOfBenefit.item.programCode" (fhir-spec (string->symbol "ExplanationOfBenefit.item.programCode") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.programCode" 'element))
(register-element! "ExplanationOfBenefit.item.quantity" (fhir-spec (string->symbol "ExplanationOfBenefit.item.quantity") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.quantity" 'element))
(register-element! "ExplanationOfBenefit.item.unitPrice" (fhir-spec (string->symbol "ExplanationOfBenefit.item.unitPrice") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.unitPrice" 'element))
(register-element! "ExplanationOfBenefit.item.factor" (fhir-spec (string->symbol "ExplanationOfBenefit.item.factor") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.factor" 'element))
(register-element! "ExplanationOfBenefit.item.net" (fhir-spec (string->symbol "ExplanationOfBenefit.item.net") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.net" 'element))
(register-element! "ExplanationOfBenefit.item.udi" (fhir-spec (string->symbol "ExplanationOfBenefit.item.udi") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.udi" 'element))
(register-element! "ExplanationOfBenefit.item.bodySite" (fhir-spec (string->symbol "ExplanationOfBenefit.item.bodySite") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.bodySite" 'element))
(register-element! "ExplanationOfBenefit.item.subSite" (fhir-spec (string->symbol "ExplanationOfBenefit.item.subSite") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.subSite" 'element))
(register-element! "ExplanationOfBenefit.item.encounter" (fhir-spec (string->symbol "ExplanationOfBenefit.item.encounter") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.encounter" 'element))
(register-element! "ExplanationOfBenefit.item.noteNumber" (fhir-spec (string->symbol "ExplanationOfBenefit.item.noteNumber") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.noteNumber" 'element))
(register-element! "ExplanationOfBenefit.item.adjudication" (fhir-spec (string->symbol "ExplanationOfBenefit.item.adjudication") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication" 'element))
(register-element! "ExplanationOfBenefit.item.detail" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail" 'element))
(register-element! "ExplanationOfBenefit.item.serviced[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.item.serviced[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.serviced[x]" 'element))
(register-element! "ExplanationOfBenefit.item.serviced[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.item.serviced[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.serviced[x]" 'element))
(register-element! "ExplanationOfBenefit.item.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.item.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.location[x]" 'element))
(register-element! "ExplanationOfBenefit.item.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.item.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.location[x]" 'element))
(register-element! "ExplanationOfBenefit.item.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.item.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.location[x]" 'element))

(register-type! 'ExplanationOfBenefitItemAdjudication (fhir-spec 'ExplanationOfBenefitItemAdjudication "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication" 'type)
  #:schema (type-schema 'ExplanationOfBenefitItemAdjudication #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication"
             (list
    (schema-field 'category 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.category" #f)
    (schema-field 'reason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.reason" #f)
    (schema-field 'amount 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.amount" #f)
    (schema-field 'value 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.value" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.item.adjudication.category" (fhir-spec (string->symbol "ExplanationOfBenefit.item.adjudication.category") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.category" 'element))
(register-element! "ExplanationOfBenefit.item.adjudication.reason" (fhir-spec (string->symbol "ExplanationOfBenefit.item.adjudication.reason") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.reason" 'element))
(register-element! "ExplanationOfBenefit.item.adjudication.amount" (fhir-spec (string->symbol "ExplanationOfBenefit.item.adjudication.amount") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.amount" 'element))
(register-element! "ExplanationOfBenefit.item.adjudication.value" (fhir-spec (string->symbol "ExplanationOfBenefit.item.adjudication.value") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.adjudication.value" 'element))

(register-type! 'ExplanationOfBenefitItemDetail (fhir-spec 'ExplanationOfBenefitItemDetail "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail" 'type)
  #:schema (type-schema 'ExplanationOfBenefitItemDetail #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.sequence" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.revenue" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.category" #f)
    (schema-field 'productOrService 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.productOrService" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.programCode" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.factor" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.net" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.udi" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.noteNumber" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ExplanationOfBenefitItemAdjudication) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.adjudication" #f)
    (schema-field 'subDetail 0 '* (vector 'type 'ExplanationOfBenefitItemDetailSubDetail) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.item.detail.sequence" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.sequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.sequence" 'element))
(register-element! "ExplanationOfBenefit.item.detail.revenue" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.revenue") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.revenue" 'element))
(register-element! "ExplanationOfBenefit.item.detail.category" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.category") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.category" 'element))
(register-element! "ExplanationOfBenefit.item.detail.productOrService" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.productOrService") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.productOrService" 'element))
(register-element! "ExplanationOfBenefit.item.detail.modifier" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.modifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.modifier" 'element))
(register-element! "ExplanationOfBenefit.item.detail.programCode" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.programCode") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.programCode" 'element))
(register-element! "ExplanationOfBenefit.item.detail.quantity" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.quantity") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.quantity" 'element))
(register-element! "ExplanationOfBenefit.item.detail.unitPrice" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.unitPrice") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.unitPrice" 'element))
(register-element! "ExplanationOfBenefit.item.detail.factor" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.factor") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.factor" 'element))
(register-element! "ExplanationOfBenefit.item.detail.net" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.net") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.net" 'element))
(register-element! "ExplanationOfBenefit.item.detail.udi" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.udi") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.udi" 'element))
(register-element! "ExplanationOfBenefit.item.detail.noteNumber" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.noteNumber") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.noteNumber" 'element))
(register-element! "ExplanationOfBenefit.item.detail.adjudication" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.adjudication") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.adjudication" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail" 'element))

(register-type! 'ExplanationOfBenefitItemDetailSubDetail (fhir-spec 'ExplanationOfBenefitItemDetailSubDetail "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail" 'type)
  #:schema (type-schema 'ExplanationOfBenefitItemDetailSubDetail #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.sequence" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.revenue" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.category" #f)
    (schema-field 'productOrService 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.productOrService" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.programCode" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.factor" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.net" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.udi" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.noteNumber" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ExplanationOfBenefitItemAdjudication) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.adjudication" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.sequence" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.sequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.sequence" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.revenue" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.revenue") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.revenue" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.category" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.category") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.category" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.productOrService" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.productOrService") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.productOrService" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.modifier" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.modifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.modifier" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.programCode" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.programCode") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.programCode" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.quantity" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.quantity") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.quantity" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.unitPrice" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.unitPrice") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.unitPrice" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.factor" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.factor") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.factor" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.net" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.net") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.net" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.udi" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.udi") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.udi" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.noteNumber" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.noteNumber") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.noteNumber" 'element))
(register-element! "ExplanationOfBenefit.item.detail.subDetail.adjudication" (fhir-spec (string->symbol "ExplanationOfBenefit.item.detail.subDetail.adjudication") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.item.detail.subDetail.adjudication" 'element))

(register-type! 'ExplanationOfBenefitAddItem (fhir-spec 'ExplanationOfBenefitAddItem "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem" 'type)
  #:schema (type-schema 'ExplanationOfBenefitAddItem #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem"
             (list
    (schema-field 'itemSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.itemSequence" #f)
    (schema-field 'detailSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detailSequence" #f)
    (schema-field 'subDetailSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.subDetailSequence" #f)
    (schema-field 'provider 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.provider" #f)
    (schema-field 'productOrService 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.productOrService" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.programCode" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.factor" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.net" #f)
    (schema-field 'bodySite 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.bodySite" #f)
    (schema-field 'subSite 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.subSite" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.noteNumber" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ExplanationOfBenefitItemAdjudication) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.adjudication" #f)
    (schema-field 'detail 0 '* (vector 'type 'ExplanationOfBenefitAddItemDetail) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail" #f)
    (schema-field 'servicedDate 0 1 (vector 'prim "date") 'serviced "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.serviced[x]" #f)
    (schema-field 'servicedPeriod 0 1 (vector 'type 'Period) 'serviced "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.serviced[x]" #f)
    (schema-field 'locationCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.location[x]" #f)
    (schema-field 'locationAddress 0 1 (vector 'type 'Address) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.location[x]" #f)
    (schema-field 'locationReference 0 1 (vector 'type 'Reference) 'location "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.location[x]" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.addItem.itemSequence" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.itemSequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.itemSequence" 'element))
(register-element! "ExplanationOfBenefit.addItem.detailSequence" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detailSequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detailSequence" 'element))
(register-element! "ExplanationOfBenefit.addItem.subDetailSequence" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.subDetailSequence") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.subDetailSequence" 'element))
(register-element! "ExplanationOfBenefit.addItem.provider" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.provider") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.provider" 'element))
(register-element! "ExplanationOfBenefit.addItem.productOrService" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.productOrService") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.productOrService" 'element))
(register-element! "ExplanationOfBenefit.addItem.modifier" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.modifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.modifier" 'element))
(register-element! "ExplanationOfBenefit.addItem.programCode" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.programCode") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.programCode" 'element))
(register-element! "ExplanationOfBenefit.addItem.quantity" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.quantity") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.quantity" 'element))
(register-element! "ExplanationOfBenefit.addItem.unitPrice" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.unitPrice") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.unitPrice" 'element))
(register-element! "ExplanationOfBenefit.addItem.factor" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.factor") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.factor" 'element))
(register-element! "ExplanationOfBenefit.addItem.net" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.net") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.net" 'element))
(register-element! "ExplanationOfBenefit.addItem.bodySite" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.bodySite") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.bodySite" 'element))
(register-element! "ExplanationOfBenefit.addItem.subSite" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.subSite") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.subSite" 'element))
(register-element! "ExplanationOfBenefit.addItem.noteNumber" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.noteNumber") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.noteNumber" 'element))
(register-element! "ExplanationOfBenefit.addItem.adjudication" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.adjudication") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.adjudication" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail" 'element))
(register-element! "ExplanationOfBenefit.addItem.serviced[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.serviced[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.serviced[x]" 'element))
(register-element! "ExplanationOfBenefit.addItem.serviced[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.serviced[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.serviced[x]" 'element))
(register-element! "ExplanationOfBenefit.addItem.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.location[x]" 'element))
(register-element! "ExplanationOfBenefit.addItem.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.location[x]" 'element))
(register-element! "ExplanationOfBenefit.addItem.location[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.location[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.location[x]" 'element))

(register-type! 'ExplanationOfBenefitAddItemDetail (fhir-spec 'ExplanationOfBenefitAddItemDetail "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail" 'type)
  #:schema (type-schema 'ExplanationOfBenefitAddItemDetail #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail"
             (list
    (schema-field 'productOrService 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.productOrService" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.modifier" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.factor" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.net" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.noteNumber" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ExplanationOfBenefitItemAdjudication) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.adjudication" #f)
    (schema-field 'subDetail 0 '* (vector 'type 'ExplanationOfBenefitAddItemDetailSubDetail) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.addItem.detail.productOrService" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.productOrService") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.productOrService" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.modifier" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.modifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.modifier" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.quantity" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.quantity") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.quantity" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.unitPrice" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.unitPrice") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.unitPrice" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.factor" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.factor") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.factor" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.net" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.net") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.net" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.noteNumber" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.noteNumber") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.noteNumber" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.adjudication" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.adjudication") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.adjudication" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail" 'element))

(register-type! 'ExplanationOfBenefitAddItemDetailSubDetail (fhir-spec 'ExplanationOfBenefitAddItemDetailSubDetail "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail" 'type)
  #:schema (type-schema 'ExplanationOfBenefitAddItemDetailSubDetail #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail"
             (list
    (schema-field 'productOrService 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.productOrService" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.modifier" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.factor" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.net" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.noteNumber" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ExplanationOfBenefitItemAdjudication) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.adjudication" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.productOrService" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.productOrService") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.productOrService" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.modifier" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.modifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.modifier" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.quantity" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.quantity") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.quantity" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.unitPrice" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.unitPrice") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.unitPrice" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.factor" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.factor") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.factor" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.net" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.net") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.net" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.noteNumber" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.noteNumber") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.noteNumber" 'element))
(register-element! "ExplanationOfBenefit.addItem.detail.subDetail.adjudication" (fhir-spec (string->symbol "ExplanationOfBenefit.addItem.detail.subDetail.adjudication") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.addItem.detail.subDetail.adjudication" 'element))

(register-type! 'ExplanationOfBenefitTotal (fhir-spec 'ExplanationOfBenefitTotal "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total" 'type)
  #:schema (type-schema 'ExplanationOfBenefitTotal #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total"
             (list
    (schema-field 'category 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total.category" #f)
    (schema-field 'amount 1 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total.amount" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.total.category" (fhir-spec (string->symbol "ExplanationOfBenefit.total.category") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total.category" 'element))
(register-element! "ExplanationOfBenefit.total.amount" (fhir-spec (string->symbol "ExplanationOfBenefit.total.amount") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.total.amount" 'element))

(register-type! 'ExplanationOfBenefitPayment (fhir-spec 'ExplanationOfBenefitPayment "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment" 'type)
  #:schema (type-schema 'ExplanationOfBenefitPayment #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.type" #f)
    (schema-field 'adjustment 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.adjustment" #f)
    (schema-field 'adjustmentReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.adjustmentReason" #f)
    (schema-field 'date 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.date" #f)
    (schema-field 'amount 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.amount" #f)
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.identifier" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.payment.type" (fhir-spec (string->symbol "ExplanationOfBenefit.payment.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.type" 'element))
(register-element! "ExplanationOfBenefit.payment.adjustment" (fhir-spec (string->symbol "ExplanationOfBenefit.payment.adjustment") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.adjustment" 'element))
(register-element! "ExplanationOfBenefit.payment.adjustmentReason" (fhir-spec (string->symbol "ExplanationOfBenefit.payment.adjustmentReason") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.adjustmentReason" 'element))
(register-element! "ExplanationOfBenefit.payment.date" (fhir-spec (string->symbol "ExplanationOfBenefit.payment.date") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.date" 'element))
(register-element! "ExplanationOfBenefit.payment.amount" (fhir-spec (string->symbol "ExplanationOfBenefit.payment.amount") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.amount" 'element))
(register-element! "ExplanationOfBenefit.payment.identifier" (fhir-spec (string->symbol "ExplanationOfBenefit.payment.identifier") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.payment.identifier" 'element))

(register-type! 'ExplanationOfBenefitProcessNote (fhir-spec 'ExplanationOfBenefitProcessNote "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote" 'type)
  #:schema (type-schema 'ExplanationOfBenefitProcessNote #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote"
             (list
    (schema-field 'number 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.number" #f)
    (schema-field 'type 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.type" #f)
    (schema-field 'text 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.text" #f)
    (schema-field 'language 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.language" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.processNote.number" (fhir-spec (string->symbol "ExplanationOfBenefit.processNote.number") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.number" 'element))
(register-element! "ExplanationOfBenefit.processNote.type" (fhir-spec (string->symbol "ExplanationOfBenefit.processNote.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.type" 'element))
(register-element! "ExplanationOfBenefit.processNote.text" (fhir-spec (string->symbol "ExplanationOfBenefit.processNote.text") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.text" 'element))
(register-element! "ExplanationOfBenefit.processNote.language" (fhir-spec (string->symbol "ExplanationOfBenefit.processNote.language") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.processNote.language" 'element))

(register-type! 'ExplanationOfBenefitBenefitBalance (fhir-spec 'ExplanationOfBenefitBenefitBalance "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance" 'type)
  #:schema (type-schema 'ExplanationOfBenefitBenefitBalance #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance"
             (list
    (schema-field 'category 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.category" #f)
    (schema-field 'excluded 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.excluded" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.name" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.description" #f)
    (schema-field 'network 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.network" #f)
    (schema-field 'unit 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.unit" #f)
    (schema-field 'term 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.term" #f)
    (schema-field 'financial 0 '* (vector 'type 'ExplanationOfBenefitBenefitBalanceFinancial) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.benefitBalance.category" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.category") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.category" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.excluded" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.excluded") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.excluded" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.name" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.name") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.name" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.description" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.description") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.description" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.network" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.network") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.network" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.unit" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.unit") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.unit" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.term" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.term") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.term" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.financial" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.financial") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial" 'element))

(register-type! 'ExplanationOfBenefitBenefitBalanceFinancial (fhir-spec 'ExplanationOfBenefitBenefitBalanceFinancial "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial" 'type)
  #:schema (type-schema 'ExplanationOfBenefitBenefitBalanceFinancial #f 'BackboneElement "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.type" #f)
    (schema-field 'allowedUnsignedInt 0 1 (vector 'prim "unsignedInt") 'allowed "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.allowed[x]" #f)
    (schema-field 'allowedString 0 1 (vector 'prim "string") 'allowed "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.allowed[x]" #f)
    (schema-field 'allowedMoney 0 1 (vector 'type 'Money) 'allowed "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.allowed[x]" #f)
    (schema-field 'usedUnsignedInt 0 1 (vector 'prim "unsignedInt") 'used "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.used[x]" #f)
    (schema-field 'usedMoney 0 1 (vector 'type 'Money) 'used "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.used[x]" #f)
             ) #f #f))
(register-element! "ExplanationOfBenefit.benefitBalance.financial.type" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.financial.type") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.type" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.financial.allowed[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.financial.allowed[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.allowed[x]" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.financial.allowed[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.financial.allowed[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.allowed[x]" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.financial.allowed[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.financial.allowed[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.allowed[x]" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.financial.used[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.financial.used[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.used[x]" 'element))
(register-element! "ExplanationOfBenefit.benefitBalance.financial.used[x]" (fhir-spec (string->symbol "ExplanationOfBenefit.benefitBalance.financial.used[x]") "https://hl7.org/fhir/R4/explanationofbenefit.html#ExplanationOfBenefit.benefitBalance.financial.used[x]" 'element))

