#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Extension (fhir-spec 'Extension "https://hl7.org/fhir/R4/datatypes.html#Extension" 'type)
  #:schema (type-schema 'Extension #f 'Element "https://hl7.org/fhir/R4/datatypes.html#Extension"
             (list
    (schema-field 'url 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/datatypes.html#Extension.url" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueContributor 0 1 (vector 'type 'Contributor) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" #f)
             ) #f #f))
(register-element! "Extension.url" (fhir-spec (string->symbol "Extension.url") "https://hl7.org/fhir/R4/datatypes.html#Extension.url" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))
(register-element! "Extension.value[x]" (fhir-spec (string->symbol "Extension.value[x]") "https://hl7.org/fhir/R4/datatypes.html#Extension.value[x]" 'element))

