#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Media (fhir-spec 'Media "https://hl7.org/fhir/R4/media.html#Media" 'type)
  #:schema (type-schema 'Media #f 'DomainResource "https://hl7.org/fhir/R4/media.html#Media"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/media.html#Media.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/media.html#Media.basedOn" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/media.html#Media.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/media.html#Media.status" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/media.html#Media.type" #f)
    (schema-field 'modality 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/media.html#Media.modality" #f)
    (schema-field 'view 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/media.html#Media.view" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/media.html#Media.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/media.html#Media.encounter" #f)
    (schema-field 'issued 0 1 (vector 'prim "instant") #f "https://hl7.org/fhir/R4/media.html#Media.issued" #f)
    (schema-field 'operator 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/media.html#Media.operator" #f)
    (schema-field 'reasonCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/media.html#Media.reasonCode" #f)
    (schema-field 'bodySite 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/media.html#Media.bodySite" #f)
    (schema-field 'deviceName 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/media.html#Media.deviceName" #f)
    (schema-field 'device 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/media.html#Media.device" #f)
    (schema-field 'height 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/media.html#Media.height" #f)
    (schema-field 'width 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/media.html#Media.width" #f)
    (schema-field 'frames 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/media.html#Media.frames" #f)
    (schema-field 'duration 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/media.html#Media.duration" #f)
    (schema-field 'content 1 1 (vector 'type 'Attachment) #f "https://hl7.org/fhir/R4/media.html#Media.content" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/media.html#Media.note" #f)
    (schema-field 'createdDateTime 0 1 (vector 'prim "dateTime") 'created "https://hl7.org/fhir/R4/media.html#Media.created[x]" #f)
    (schema-field 'createdPeriod 0 1 (vector 'type 'Period) 'created "https://hl7.org/fhir/R4/media.html#Media.created[x]" #f)
             ) #f #f))
(register-element! "Media.identifier" (fhir-spec (string->symbol "Media.identifier") "https://hl7.org/fhir/R4/media.html#Media.identifier" 'element))
(register-element! "Media.basedOn" (fhir-spec (string->symbol "Media.basedOn") "https://hl7.org/fhir/R4/media.html#Media.basedOn" 'element))
(register-element! "Media.partOf" (fhir-spec (string->symbol "Media.partOf") "https://hl7.org/fhir/R4/media.html#Media.partOf" 'element))
(register-element! "Media.status" (fhir-spec (string->symbol "Media.status") "https://hl7.org/fhir/R4/media.html#Media.status" 'element))
(register-element! "Media.type" (fhir-spec (string->symbol "Media.type") "https://hl7.org/fhir/R4/media.html#Media.type" 'element))
(register-element! "Media.modality" (fhir-spec (string->symbol "Media.modality") "https://hl7.org/fhir/R4/media.html#Media.modality" 'element))
(register-element! "Media.view" (fhir-spec (string->symbol "Media.view") "https://hl7.org/fhir/R4/media.html#Media.view" 'element))
(register-element! "Media.subject" (fhir-spec (string->symbol "Media.subject") "https://hl7.org/fhir/R4/media.html#Media.subject" 'element))
(register-element! "Media.encounter" (fhir-spec (string->symbol "Media.encounter") "https://hl7.org/fhir/R4/media.html#Media.encounter" 'element))
(register-element! "Media.issued" (fhir-spec (string->symbol "Media.issued") "https://hl7.org/fhir/R4/media.html#Media.issued" 'element))
(register-element! "Media.operator" (fhir-spec (string->symbol "Media.operator") "https://hl7.org/fhir/R4/media.html#Media.operator" 'element))
(register-element! "Media.reasonCode" (fhir-spec (string->symbol "Media.reasonCode") "https://hl7.org/fhir/R4/media.html#Media.reasonCode" 'element))
(register-element! "Media.bodySite" (fhir-spec (string->symbol "Media.bodySite") "https://hl7.org/fhir/R4/media.html#Media.bodySite" 'element))
(register-element! "Media.deviceName" (fhir-spec (string->symbol "Media.deviceName") "https://hl7.org/fhir/R4/media.html#Media.deviceName" 'element))
(register-element! "Media.device" (fhir-spec (string->symbol "Media.device") "https://hl7.org/fhir/R4/media.html#Media.device" 'element))
(register-element! "Media.height" (fhir-spec (string->symbol "Media.height") "https://hl7.org/fhir/R4/media.html#Media.height" 'element))
(register-element! "Media.width" (fhir-spec (string->symbol "Media.width") "https://hl7.org/fhir/R4/media.html#Media.width" 'element))
(register-element! "Media.frames" (fhir-spec (string->symbol "Media.frames") "https://hl7.org/fhir/R4/media.html#Media.frames" 'element))
(register-element! "Media.duration" (fhir-spec (string->symbol "Media.duration") "https://hl7.org/fhir/R4/media.html#Media.duration" 'element))
(register-element! "Media.content" (fhir-spec (string->symbol "Media.content") "https://hl7.org/fhir/R4/media.html#Media.content" 'element))
(register-element! "Media.note" (fhir-spec (string->symbol "Media.note") "https://hl7.org/fhir/R4/media.html#Media.note" 'element))
(register-element! "Media.created[x]" (fhir-spec (string->symbol "Media.created[x]") "https://hl7.org/fhir/R4/media.html#Media.created[x]" 'element))
(register-element! "Media.created[x]" (fhir-spec (string->symbol "Media.created[x]") "https://hl7.org/fhir/R4/media.html#Media.created[x]" 'element))

