#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'MedicationDispense (fhir-spec 'MedicationDispense "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense" 'type)
  #:schema (type-schema 'MedicationDispense #f 'DomainResource "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.identifier" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.status" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.category" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.subject" #f)
    (schema-field 'context 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.context" #f)
    (schema-field 'supportingInformation 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.supportingInformation" #f)
    (schema-field 'performer 0 '* (vector 'type 'MedicationDispensePerformer) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.location" #f)
    (schema-field 'authorizingPrescription 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.authorizingPrescription" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.type" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.quantity" #f)
    (schema-field 'daysSupply 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.daysSupply" #f)
    (schema-field 'whenPrepared 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.whenPrepared" #f)
    (schema-field 'whenHandedOver 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.whenHandedOver" #f)
    (schema-field 'destination 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.destination" #f)
    (schema-field 'receiver 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.receiver" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.note" #f)
    (schema-field 'dosageInstruction 0 '* (vector 'type 'Dosage) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.dosageInstruction" #f)
    (schema-field 'substitution 0 1 (vector 'type 'MedicationDispenseSubstitution) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution" #f)
    (schema-field 'detectedIssue 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.detectedIssue" #f)
    (schema-field 'eventHistory 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.eventHistory" #f)
    (schema-field 'statusReasonCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'statusReason "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.statusReason[x]" #f)
    (schema-field 'statusReasonReference 0 1 (vector 'type 'Reference) 'statusReason "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.statusReason[x]" #f)
    (schema-field 'medicationCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'medication "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.medication[x]" #f)
    (schema-field 'medicationReference 0 1 (vector 'type 'Reference) 'medication "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.medication[x]" #f)
             ) #f #f))
(register-element! "MedicationDispense.identifier" (fhir-spec (string->symbol "MedicationDispense.identifier") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.identifier" 'element))
(register-element! "MedicationDispense.partOf" (fhir-spec (string->symbol "MedicationDispense.partOf") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.partOf" 'element))
(register-element! "MedicationDispense.status" (fhir-spec (string->symbol "MedicationDispense.status") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.status" 'element))
(register-element! "MedicationDispense.category" (fhir-spec (string->symbol "MedicationDispense.category") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.category" 'element))
(register-element! "MedicationDispense.subject" (fhir-spec (string->symbol "MedicationDispense.subject") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.subject" 'element))
(register-element! "MedicationDispense.context" (fhir-spec (string->symbol "MedicationDispense.context") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.context" 'element))
(register-element! "MedicationDispense.supportingInformation" (fhir-spec (string->symbol "MedicationDispense.supportingInformation") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.supportingInformation" 'element))
(register-element! "MedicationDispense.performer" (fhir-spec (string->symbol "MedicationDispense.performer") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer" 'element))
(register-element! "MedicationDispense.location" (fhir-spec (string->symbol "MedicationDispense.location") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.location" 'element))
(register-element! "MedicationDispense.authorizingPrescription" (fhir-spec (string->symbol "MedicationDispense.authorizingPrescription") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.authorizingPrescription" 'element))
(register-element! "MedicationDispense.type" (fhir-spec (string->symbol "MedicationDispense.type") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.type" 'element))
(register-element! "MedicationDispense.quantity" (fhir-spec (string->symbol "MedicationDispense.quantity") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.quantity" 'element))
(register-element! "MedicationDispense.daysSupply" (fhir-spec (string->symbol "MedicationDispense.daysSupply") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.daysSupply" 'element))
(register-element! "MedicationDispense.whenPrepared" (fhir-spec (string->symbol "MedicationDispense.whenPrepared") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.whenPrepared" 'element))
(register-element! "MedicationDispense.whenHandedOver" (fhir-spec (string->symbol "MedicationDispense.whenHandedOver") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.whenHandedOver" 'element))
(register-element! "MedicationDispense.destination" (fhir-spec (string->symbol "MedicationDispense.destination") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.destination" 'element))
(register-element! "MedicationDispense.receiver" (fhir-spec (string->symbol "MedicationDispense.receiver") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.receiver" 'element))
(register-element! "MedicationDispense.note" (fhir-spec (string->symbol "MedicationDispense.note") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.note" 'element))
(register-element! "MedicationDispense.dosageInstruction" (fhir-spec (string->symbol "MedicationDispense.dosageInstruction") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.dosageInstruction" 'element))
(register-element! "MedicationDispense.substitution" (fhir-spec (string->symbol "MedicationDispense.substitution") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution" 'element))
(register-element! "MedicationDispense.detectedIssue" (fhir-spec (string->symbol "MedicationDispense.detectedIssue") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.detectedIssue" 'element))
(register-element! "MedicationDispense.eventHistory" (fhir-spec (string->symbol "MedicationDispense.eventHistory") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.eventHistory" 'element))
(register-element! "MedicationDispense.statusReason[x]" (fhir-spec (string->symbol "MedicationDispense.statusReason[x]") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.statusReason[x]" 'element))
(register-element! "MedicationDispense.statusReason[x]" (fhir-spec (string->symbol "MedicationDispense.statusReason[x]") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.statusReason[x]" 'element))
(register-element! "MedicationDispense.medication[x]" (fhir-spec (string->symbol "MedicationDispense.medication[x]") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.medication[x]" 'element))
(register-element! "MedicationDispense.medication[x]" (fhir-spec (string->symbol "MedicationDispense.medication[x]") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.medication[x]" 'element))

(register-type! 'MedicationDispensePerformer (fhir-spec 'MedicationDispensePerformer "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer" 'type)
  #:schema (type-schema 'MedicationDispensePerformer #f 'BackboneElement "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer.actor" #f)
             ) #f #f))
(register-element! "MedicationDispense.performer.function" (fhir-spec (string->symbol "MedicationDispense.performer.function") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer.function" 'element))
(register-element! "MedicationDispense.performer.actor" (fhir-spec (string->symbol "MedicationDispense.performer.actor") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.performer.actor" 'element))

(register-type! 'MedicationDispenseSubstitution (fhir-spec 'MedicationDispenseSubstitution "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution" 'type)
  #:schema (type-schema 'MedicationDispenseSubstitution #f 'BackboneElement "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution"
             (list
    (schema-field 'wasSubstituted 1 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.wasSubstituted" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.type" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.reason" #f)
    (schema-field 'responsibleParty 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.responsibleParty" #f)
             ) #f #f))
(register-element! "MedicationDispense.substitution.wasSubstituted" (fhir-spec (string->symbol "MedicationDispense.substitution.wasSubstituted") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.wasSubstituted" 'element))
(register-element! "MedicationDispense.substitution.type" (fhir-spec (string->symbol "MedicationDispense.substitution.type") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.type" 'element))
(register-element! "MedicationDispense.substitution.reason" (fhir-spec (string->symbol "MedicationDispense.substitution.reason") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.reason" 'element))
(register-element! "MedicationDispense.substitution.responsibleParty" (fhir-spec (string->symbol "MedicationDispense.substitution.responsibleParty") "https://hl7.org/fhir/R4/medicationdispense.html#MedicationDispense.substitution.responsibleParty" 'element))

