#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'MedicinalProduct (fhir-spec 'MedicinalProduct "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct" 'type)
  #:schema (type-schema 'MedicinalProduct #f 'DomainResource "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.identifier" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.type" #f)
    (schema-field 'domain 0 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.domain" #f)
    (schema-field 'combinedPharmaceuticalDoseForm 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.combinedPharmaceuticalDoseForm" #f)
    (schema-field 'legalStatusOfSupply 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.legalStatusOfSupply" #f)
    (schema-field 'additionalMonitoringIndicator 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.additionalMonitoringIndicator" #f)
    (schema-field 'specialMeasures 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialMeasures" #f)
    (schema-field 'paediatricUseIndicator 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.paediatricUseIndicator" #f)
    (schema-field 'productClassification 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.productClassification" #f)
    (schema-field 'marketingStatus 0 '* (vector 'type 'MarketingStatus) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.marketingStatus" #f)
    (schema-field 'pharmaceuticalProduct 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.pharmaceuticalProduct" #f)
    (schema-field 'packagedMedicinalProduct 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.packagedMedicinalProduct" #f)
    (schema-field 'attachedDocument 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.attachedDocument" #f)
    (schema-field 'masterFile 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.masterFile" #f)
    (schema-field 'contact 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.contact" #f)
    (schema-field 'clinicalTrial 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.clinicalTrial" #f)
    (schema-field 'name 1 '* (vector 'type 'MedicinalProductName) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name" #f)
    (schema-field 'crossReference 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.crossReference" #f)
    (schema-field 'manufacturingBusinessOperation 0 '* (vector 'type 'MedicinalProductManufacturingBusinessOperation) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation" #f)
    (schema-field 'specialDesignation 0 '* (vector 'type 'MedicinalProductSpecialDesignation) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation" #f)
             ) #f #f))
(register-element! "MedicinalProduct.identifier" (fhir-spec (string->symbol "MedicinalProduct.identifier") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.identifier" 'element))
(register-element! "MedicinalProduct.type" (fhir-spec (string->symbol "MedicinalProduct.type") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.type" 'element))
(register-element! "MedicinalProduct.domain" (fhir-spec (string->symbol "MedicinalProduct.domain") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.domain" 'element))
(register-element! "MedicinalProduct.combinedPharmaceuticalDoseForm" (fhir-spec (string->symbol "MedicinalProduct.combinedPharmaceuticalDoseForm") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.combinedPharmaceuticalDoseForm" 'element))
(register-element! "MedicinalProduct.legalStatusOfSupply" (fhir-spec (string->symbol "MedicinalProduct.legalStatusOfSupply") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.legalStatusOfSupply" 'element))
(register-element! "MedicinalProduct.additionalMonitoringIndicator" (fhir-spec (string->symbol "MedicinalProduct.additionalMonitoringIndicator") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.additionalMonitoringIndicator" 'element))
(register-element! "MedicinalProduct.specialMeasures" (fhir-spec (string->symbol "MedicinalProduct.specialMeasures") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialMeasures" 'element))
(register-element! "MedicinalProduct.paediatricUseIndicator" (fhir-spec (string->symbol "MedicinalProduct.paediatricUseIndicator") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.paediatricUseIndicator" 'element))
(register-element! "MedicinalProduct.productClassification" (fhir-spec (string->symbol "MedicinalProduct.productClassification") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.productClassification" 'element))
(register-element! "MedicinalProduct.marketingStatus" (fhir-spec (string->symbol "MedicinalProduct.marketingStatus") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.marketingStatus" 'element))
(register-element! "MedicinalProduct.pharmaceuticalProduct" (fhir-spec (string->symbol "MedicinalProduct.pharmaceuticalProduct") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.pharmaceuticalProduct" 'element))
(register-element! "MedicinalProduct.packagedMedicinalProduct" (fhir-spec (string->symbol "MedicinalProduct.packagedMedicinalProduct") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.packagedMedicinalProduct" 'element))
(register-element! "MedicinalProduct.attachedDocument" (fhir-spec (string->symbol "MedicinalProduct.attachedDocument") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.attachedDocument" 'element))
(register-element! "MedicinalProduct.masterFile" (fhir-spec (string->symbol "MedicinalProduct.masterFile") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.masterFile" 'element))
(register-element! "MedicinalProduct.contact" (fhir-spec (string->symbol "MedicinalProduct.contact") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.contact" 'element))
(register-element! "MedicinalProduct.clinicalTrial" (fhir-spec (string->symbol "MedicinalProduct.clinicalTrial") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.clinicalTrial" 'element))
(register-element! "MedicinalProduct.name" (fhir-spec (string->symbol "MedicinalProduct.name") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name" 'element))
(register-element! "MedicinalProduct.crossReference" (fhir-spec (string->symbol "MedicinalProduct.crossReference") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.crossReference" 'element))
(register-element! "MedicinalProduct.manufacturingBusinessOperation" (fhir-spec (string->symbol "MedicinalProduct.manufacturingBusinessOperation") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation" 'element))
(register-element! "MedicinalProduct.specialDesignation" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation" 'element))

(register-type! 'MedicinalProductName (fhir-spec 'MedicinalProductName "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name" 'type)
  #:schema (type-schema 'MedicinalProductName #f 'BackboneElement "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name"
             (list
    (schema-field 'productName 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.productName" #f)
    (schema-field 'namePart 0 '* (vector 'type 'MedicinalProductNameNamePart) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart" #f)
    (schema-field 'countryLanguage 0 '* (vector 'type 'MedicinalProductNameCountryLanguage) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage" #f)
             ) #f #f))
(register-element! "MedicinalProduct.name.productName" (fhir-spec (string->symbol "MedicinalProduct.name.productName") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.productName" 'element))
(register-element! "MedicinalProduct.name.namePart" (fhir-spec (string->symbol "MedicinalProduct.name.namePart") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart" 'element))
(register-element! "MedicinalProduct.name.countryLanguage" (fhir-spec (string->symbol "MedicinalProduct.name.countryLanguage") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage" 'element))

(register-type! 'MedicinalProductNameNamePart (fhir-spec 'MedicinalProductNameNamePart "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart" 'type)
  #:schema (type-schema 'MedicinalProductNameNamePart #f 'BackboneElement "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart"
             (list
    (schema-field 'part 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart.part" #f)
    (schema-field 'type 1 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart.type" #f)
             ) #f #f))
(register-element! "MedicinalProduct.name.namePart.part" (fhir-spec (string->symbol "MedicinalProduct.name.namePart.part") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart.part" 'element))
(register-element! "MedicinalProduct.name.namePart.type" (fhir-spec (string->symbol "MedicinalProduct.name.namePart.type") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.namePart.type" 'element))

(register-type! 'MedicinalProductNameCountryLanguage (fhir-spec 'MedicinalProductNameCountryLanguage "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage" 'type)
  #:schema (type-schema 'MedicinalProductNameCountryLanguage #f 'BackboneElement "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage"
             (list
    (schema-field 'country 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage.country" #f)
    (schema-field 'jurisdiction 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage.jurisdiction" #f)
    (schema-field 'language 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage.language" #f)
             ) #f #f))
(register-element! "MedicinalProduct.name.countryLanguage.country" (fhir-spec (string->symbol "MedicinalProduct.name.countryLanguage.country") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage.country" 'element))
(register-element! "MedicinalProduct.name.countryLanguage.jurisdiction" (fhir-spec (string->symbol "MedicinalProduct.name.countryLanguage.jurisdiction") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage.jurisdiction" 'element))
(register-element! "MedicinalProduct.name.countryLanguage.language" (fhir-spec (string->symbol "MedicinalProduct.name.countryLanguage.language") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.name.countryLanguage.language" 'element))

(register-type! 'MedicinalProductManufacturingBusinessOperation (fhir-spec 'MedicinalProductManufacturingBusinessOperation "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation" 'type)
  #:schema (type-schema 'MedicinalProductManufacturingBusinessOperation #f 'BackboneElement "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation"
             (list
    (schema-field 'operationType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.operationType" #f)
    (schema-field 'authorisationReferenceNumber 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.authorisationReferenceNumber" #f)
    (schema-field 'effectiveDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.effectiveDate" #f)
    (schema-field 'confidentialityIndicator 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.confidentialityIndicator" #f)
    (schema-field 'manufacturer 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.manufacturer" #f)
    (schema-field 'regulator 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.regulator" #f)
             ) #f #f))
(register-element! "MedicinalProduct.manufacturingBusinessOperation.operationType" (fhir-spec (string->symbol "MedicinalProduct.manufacturingBusinessOperation.operationType") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.operationType" 'element))
(register-element! "MedicinalProduct.manufacturingBusinessOperation.authorisationReferenceNumber" (fhir-spec (string->symbol "MedicinalProduct.manufacturingBusinessOperation.authorisationReferenceNumber") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.authorisationReferenceNumber" 'element))
(register-element! "MedicinalProduct.manufacturingBusinessOperation.effectiveDate" (fhir-spec (string->symbol "MedicinalProduct.manufacturingBusinessOperation.effectiveDate") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.effectiveDate" 'element))
(register-element! "MedicinalProduct.manufacturingBusinessOperation.confidentialityIndicator" (fhir-spec (string->symbol "MedicinalProduct.manufacturingBusinessOperation.confidentialityIndicator") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.confidentialityIndicator" 'element))
(register-element! "MedicinalProduct.manufacturingBusinessOperation.manufacturer" (fhir-spec (string->symbol "MedicinalProduct.manufacturingBusinessOperation.manufacturer") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.manufacturer" 'element))
(register-element! "MedicinalProduct.manufacturingBusinessOperation.regulator" (fhir-spec (string->symbol "MedicinalProduct.manufacturingBusinessOperation.regulator") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.manufacturingBusinessOperation.regulator" 'element))

(register-type! 'MedicinalProductSpecialDesignation (fhir-spec 'MedicinalProductSpecialDesignation "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation" 'type)
  #:schema (type-schema 'MedicinalProductSpecialDesignation #f 'BackboneElement "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.identifier" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.type" #f)
    (schema-field 'intendedUse 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.intendedUse" #f)
    (schema-field 'status 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.status" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.date" #f)
    (schema-field 'species 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.species" #f)
    (schema-field 'indicationCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'indication "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.indication[x]" #f)
    (schema-field 'indicationReference 0 1 (vector 'type 'Reference) 'indication "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.indication[x]" #f)
             ) #f #f))
(register-element! "MedicinalProduct.specialDesignation.identifier" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.identifier") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.identifier" 'element))
(register-element! "MedicinalProduct.specialDesignation.type" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.type") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.type" 'element))
(register-element! "MedicinalProduct.specialDesignation.intendedUse" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.intendedUse") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.intendedUse" 'element))
(register-element! "MedicinalProduct.specialDesignation.status" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.status") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.status" 'element))
(register-element! "MedicinalProduct.specialDesignation.date" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.date") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.date" 'element))
(register-element! "MedicinalProduct.specialDesignation.species" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.species") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.species" 'element))
(register-element! "MedicinalProduct.specialDesignation.indication[x]" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.indication[x]") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.indication[x]" 'element))
(register-element! "MedicinalProduct.specialDesignation.indication[x]" (fhir-spec (string->symbol "MedicinalProduct.specialDesignation.indication[x]") "https://hl7.org/fhir/R4/medicinalproduct.html#MedicinalProduct.specialDesignation.indication[x]" 'element))

