#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ObservationDefinition (fhir-spec 'ObservationDefinition "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition" 'type)
  #:schema (type-schema 'ObservationDefinition #f 'DomainResource "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition"
             (list
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.category" #f)
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.code" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.identifier" #f)
    (schema-field 'permittedDataType 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.permittedDataType" #f)
    (schema-field 'multipleResultsAllowed 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.multipleResultsAllowed" #f)
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.method" #f)
    (schema-field 'preferredReportName 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.preferredReportName" #f)
    (schema-field 'quantitativeDetails 0 1 (vector 'type 'ObservationDefinitionQuantitativeDetails) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails" #f)
    (schema-field 'qualifiedInterval 0 '* (vector 'type 'ObservationDefinitionQualifiedInterval) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval" #f)
    (schema-field 'validCodedValueSet 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.validCodedValueSet" #f)
    (schema-field 'normalCodedValueSet 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.normalCodedValueSet" #f)
    (schema-field 'abnormalCodedValueSet 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.abnormalCodedValueSet" #f)
    (schema-field 'criticalCodedValueSet 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.criticalCodedValueSet" #f)
             ) #f #f))
(register-element! "ObservationDefinition.category" (fhir-spec (string->symbol "ObservationDefinition.category") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.category" 'element))
(register-element! "ObservationDefinition.code" (fhir-spec (string->symbol "ObservationDefinition.code") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.code" 'element))
(register-element! "ObservationDefinition.identifier" (fhir-spec (string->symbol "ObservationDefinition.identifier") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.identifier" 'element))
(register-element! "ObservationDefinition.permittedDataType" (fhir-spec (string->symbol "ObservationDefinition.permittedDataType") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.permittedDataType" 'element))
(register-element! "ObservationDefinition.multipleResultsAllowed" (fhir-spec (string->symbol "ObservationDefinition.multipleResultsAllowed") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.multipleResultsAllowed" 'element))
(register-element! "ObservationDefinition.method" (fhir-spec (string->symbol "ObservationDefinition.method") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.method" 'element))
(register-element! "ObservationDefinition.preferredReportName" (fhir-spec (string->symbol "ObservationDefinition.preferredReportName") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.preferredReportName" 'element))
(register-element! "ObservationDefinition.quantitativeDetails" (fhir-spec (string->symbol "ObservationDefinition.quantitativeDetails") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails" 'element))
(register-element! "ObservationDefinition.qualifiedInterval" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval" 'element))
(register-element! "ObservationDefinition.validCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.validCodedValueSet") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.validCodedValueSet" 'element))
(register-element! "ObservationDefinition.normalCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.normalCodedValueSet") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.normalCodedValueSet" 'element))
(register-element! "ObservationDefinition.abnormalCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.abnormalCodedValueSet") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.abnormalCodedValueSet" 'element))
(register-element! "ObservationDefinition.criticalCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.criticalCodedValueSet") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.criticalCodedValueSet" 'element))

(register-type! 'ObservationDefinitionQuantitativeDetails (fhir-spec 'ObservationDefinitionQuantitativeDetails "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails" 'type)
  #:schema (type-schema 'ObservationDefinitionQuantitativeDetails #f 'BackboneElement "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails"
             (list
    (schema-field 'customaryUnit 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.customaryUnit" #f)
    (schema-field 'unit 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.unit" #f)
    (schema-field 'conversionFactor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.conversionFactor" #f)
    (schema-field 'decimalPrecision 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.decimalPrecision" #f)
             ) #f #f))
(register-element! "ObservationDefinition.quantitativeDetails.customaryUnit" (fhir-spec (string->symbol "ObservationDefinition.quantitativeDetails.customaryUnit") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.customaryUnit" 'element))
(register-element! "ObservationDefinition.quantitativeDetails.unit" (fhir-spec (string->symbol "ObservationDefinition.quantitativeDetails.unit") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.unit" 'element))
(register-element! "ObservationDefinition.quantitativeDetails.conversionFactor" (fhir-spec (string->symbol "ObservationDefinition.quantitativeDetails.conversionFactor") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.conversionFactor" 'element))
(register-element! "ObservationDefinition.quantitativeDetails.decimalPrecision" (fhir-spec (string->symbol "ObservationDefinition.quantitativeDetails.decimalPrecision") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.quantitativeDetails.decimalPrecision" 'element))

(register-type! 'ObservationDefinitionQualifiedInterval (fhir-spec 'ObservationDefinitionQualifiedInterval "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval" 'type)
  #:schema (type-schema 'ObservationDefinitionQualifiedInterval #f 'BackboneElement "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval"
             (list
    (schema-field 'category 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.category" #f)
    (schema-field 'range 0 1 (vector 'type 'Range) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.range" #f)
    (schema-field 'context 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.context" #f)
    (schema-field 'appliesTo 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.appliesTo" #f)
    (schema-field 'gender 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.gender" #f)
    (schema-field 'age 0 1 (vector 'type 'Range) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.age" #f)
    (schema-field 'gestationalAge 0 1 (vector 'type 'Range) #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.gestationalAge" #f)
    (schema-field 'condition 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.condition" #f)
             ) #f #f))
(register-element! "ObservationDefinition.qualifiedInterval.category" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.category") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.category" 'element))
(register-element! "ObservationDefinition.qualifiedInterval.range" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.range") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.range" 'element))
(register-element! "ObservationDefinition.qualifiedInterval.context" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.context") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.context" 'element))
(register-element! "ObservationDefinition.qualifiedInterval.appliesTo" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.appliesTo") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.appliesTo" 'element))
(register-element! "ObservationDefinition.qualifiedInterval.gender" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.gender") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.gender" 'element))
(register-element! "ObservationDefinition.qualifiedInterval.age" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.age") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.age" 'element))
(register-element! "ObservationDefinition.qualifiedInterval.gestationalAge" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.gestationalAge") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.gestationalAge" 'element))
(register-element! "ObservationDefinition.qualifiedInterval.condition" (fhir-spec (string->symbol "ObservationDefinition.qualifiedInterval.condition") "https://hl7.org/fhir/R4/observationdefinition.html#ObservationDefinition.qualifiedInterval.condition" 'element))

