#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Procedure (fhir-spec 'Procedure "https://hl7.org/fhir/R4/procedure.html#Procedure" 'type)
  #:schema (type-schema 'Procedure #f 'DomainResource "https://hl7.org/fhir/R4/procedure.html#Procedure"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.identifier" #f)
    (schema-field 'instantiatesCanonical 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/procedure.html#Procedure.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 '* (vector 'prim "uri") #f "https://hl7.org/fhir/R4/procedure.html#Procedure.instantiatesUri" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.basedOn" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/procedure.html#Procedure.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.statusReason" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.category" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.code" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.encounter" #f)
    (schema-field 'recorder 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.recorder" #f)
    (schema-field 'asserter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.asserter" #f)
    (schema-field 'performer 0 '* (vector 'type 'ProcedurePerformer) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.performer" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.location" #f)
    (schema-field 'reasonCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.reasonCode" #f)
    (schema-field 'reasonReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.reasonReference" #f)
    (schema-field 'bodySite 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.bodySite" #f)
    (schema-field 'outcome 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.outcome" #f)
    (schema-field 'report 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.report" #f)
    (schema-field 'complication 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.complication" #f)
    (schema-field 'complicationDetail 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.complicationDetail" #f)
    (schema-field 'followUp 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.followUp" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.note" #f)
    (schema-field 'focalDevice 0 '* (vector 'type 'ProcedureFocalDevice) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice" #f)
    (schema-field 'usedReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.usedReference" #f)
    (schema-field 'usedCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.usedCode" #f)
    (schema-field 'performedDateTime 0 1 (vector 'prim "dateTime") 'performed "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" #f)
    (schema-field 'performedPeriod 0 1 (vector 'type 'Period) 'performed "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" #f)
    (schema-field 'performedString 0 1 (vector 'prim "string") 'performed "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" #f)
    (schema-field 'performedAge 0 1 (vector 'type 'Age) 'performed "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" #f)
    (schema-field 'performedRange 0 1 (vector 'type 'Range) 'performed "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" #f)
             ) #f #f))
(register-element! "Procedure.identifier" (fhir-spec (string->symbol "Procedure.identifier") "https://hl7.org/fhir/R4/procedure.html#Procedure.identifier" 'element))
(register-element! "Procedure.instantiatesCanonical" (fhir-spec (string->symbol "Procedure.instantiatesCanonical") "https://hl7.org/fhir/R4/procedure.html#Procedure.instantiatesCanonical" 'element))
(register-element! "Procedure.instantiatesUri" (fhir-spec (string->symbol "Procedure.instantiatesUri") "https://hl7.org/fhir/R4/procedure.html#Procedure.instantiatesUri" 'element))
(register-element! "Procedure.basedOn" (fhir-spec (string->symbol "Procedure.basedOn") "https://hl7.org/fhir/R4/procedure.html#Procedure.basedOn" 'element))
(register-element! "Procedure.partOf" (fhir-spec (string->symbol "Procedure.partOf") "https://hl7.org/fhir/R4/procedure.html#Procedure.partOf" 'element))
(register-element! "Procedure.status" (fhir-spec (string->symbol "Procedure.status") "https://hl7.org/fhir/R4/procedure.html#Procedure.status" 'element))
(register-element! "Procedure.statusReason" (fhir-spec (string->symbol "Procedure.statusReason") "https://hl7.org/fhir/R4/procedure.html#Procedure.statusReason" 'element))
(register-element! "Procedure.category" (fhir-spec (string->symbol "Procedure.category") "https://hl7.org/fhir/R4/procedure.html#Procedure.category" 'element))
(register-element! "Procedure.code" (fhir-spec (string->symbol "Procedure.code") "https://hl7.org/fhir/R4/procedure.html#Procedure.code" 'element))
(register-element! "Procedure.subject" (fhir-spec (string->symbol "Procedure.subject") "https://hl7.org/fhir/R4/procedure.html#Procedure.subject" 'element))
(register-element! "Procedure.encounter" (fhir-spec (string->symbol "Procedure.encounter") "https://hl7.org/fhir/R4/procedure.html#Procedure.encounter" 'element))
(register-element! "Procedure.recorder" (fhir-spec (string->symbol "Procedure.recorder") "https://hl7.org/fhir/R4/procedure.html#Procedure.recorder" 'element))
(register-element! "Procedure.asserter" (fhir-spec (string->symbol "Procedure.asserter") "https://hl7.org/fhir/R4/procedure.html#Procedure.asserter" 'element))
(register-element! "Procedure.performer" (fhir-spec (string->symbol "Procedure.performer") "https://hl7.org/fhir/R4/procedure.html#Procedure.performer" 'element))
(register-element! "Procedure.location" (fhir-spec (string->symbol "Procedure.location") "https://hl7.org/fhir/R4/procedure.html#Procedure.location" 'element))
(register-element! "Procedure.reasonCode" (fhir-spec (string->symbol "Procedure.reasonCode") "https://hl7.org/fhir/R4/procedure.html#Procedure.reasonCode" 'element))
(register-element! "Procedure.reasonReference" (fhir-spec (string->symbol "Procedure.reasonReference") "https://hl7.org/fhir/R4/procedure.html#Procedure.reasonReference" 'element))
(register-element! "Procedure.bodySite" (fhir-spec (string->symbol "Procedure.bodySite") "https://hl7.org/fhir/R4/procedure.html#Procedure.bodySite" 'element))
(register-element! "Procedure.outcome" (fhir-spec (string->symbol "Procedure.outcome") "https://hl7.org/fhir/R4/procedure.html#Procedure.outcome" 'element))
(register-element! "Procedure.report" (fhir-spec (string->symbol "Procedure.report") "https://hl7.org/fhir/R4/procedure.html#Procedure.report" 'element))
(register-element! "Procedure.complication" (fhir-spec (string->symbol "Procedure.complication") "https://hl7.org/fhir/R4/procedure.html#Procedure.complication" 'element))
(register-element! "Procedure.complicationDetail" (fhir-spec (string->symbol "Procedure.complicationDetail") "https://hl7.org/fhir/R4/procedure.html#Procedure.complicationDetail" 'element))
(register-element! "Procedure.followUp" (fhir-spec (string->symbol "Procedure.followUp") "https://hl7.org/fhir/R4/procedure.html#Procedure.followUp" 'element))
(register-element! "Procedure.note" (fhir-spec (string->symbol "Procedure.note") "https://hl7.org/fhir/R4/procedure.html#Procedure.note" 'element))
(register-element! "Procedure.focalDevice" (fhir-spec (string->symbol "Procedure.focalDevice") "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice" 'element))
(register-element! "Procedure.usedReference" (fhir-spec (string->symbol "Procedure.usedReference") "https://hl7.org/fhir/R4/procedure.html#Procedure.usedReference" 'element))
(register-element! "Procedure.usedCode" (fhir-spec (string->symbol "Procedure.usedCode") "https://hl7.org/fhir/R4/procedure.html#Procedure.usedCode" 'element))
(register-element! "Procedure.performed[x]" (fhir-spec (string->symbol "Procedure.performed[x]") "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" 'element))
(register-element! "Procedure.performed[x]" (fhir-spec (string->symbol "Procedure.performed[x]") "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" 'element))
(register-element! "Procedure.performed[x]" (fhir-spec (string->symbol "Procedure.performed[x]") "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" 'element))
(register-element! "Procedure.performed[x]" (fhir-spec (string->symbol "Procedure.performed[x]") "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" 'element))
(register-element! "Procedure.performed[x]" (fhir-spec (string->symbol "Procedure.performed[x]") "https://hl7.org/fhir/R4/procedure.html#Procedure.performed[x]" 'element))

(register-type! 'ProcedurePerformer (fhir-spec 'ProcedurePerformer "https://hl7.org/fhir/R4/procedure.html#Procedure.performer" 'type)
  #:schema (type-schema 'ProcedurePerformer #f 'BackboneElement "https://hl7.org/fhir/R4/procedure.html#Procedure.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.performer.actor" #f)
    (schema-field 'onBehalfOf 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.performer.onBehalfOf" #f)
             ) #f #f))
(register-element! "Procedure.performer.function" (fhir-spec (string->symbol "Procedure.performer.function") "https://hl7.org/fhir/R4/procedure.html#Procedure.performer.function" 'element))
(register-element! "Procedure.performer.actor" (fhir-spec (string->symbol "Procedure.performer.actor") "https://hl7.org/fhir/R4/procedure.html#Procedure.performer.actor" 'element))
(register-element! "Procedure.performer.onBehalfOf" (fhir-spec (string->symbol "Procedure.performer.onBehalfOf") "https://hl7.org/fhir/R4/procedure.html#Procedure.performer.onBehalfOf" 'element))

(register-type! 'ProcedureFocalDevice (fhir-spec 'ProcedureFocalDevice "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice" 'type)
  #:schema (type-schema 'ProcedureFocalDevice #f 'BackboneElement "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice"
             (list
    (schema-field 'action 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice.action" #f)
    (schema-field 'manipulated 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice.manipulated" #f)
             ) #f #f))
(register-element! "Procedure.focalDevice.action" (fhir-spec (string->symbol "Procedure.focalDevice.action") "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice.action" 'element))
(register-element! "Procedure.focalDevice.manipulated" (fhir-spec (string->symbol "Procedure.focalDevice.manipulated") "https://hl7.org/fhir/R4/procedure.html#Procedure.focalDevice.manipulated" 'element))

