#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'RiskEvidenceSynthesis (fhir-spec 'RiskEvidenceSynthesis "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis" 'type)
  #:schema (type-schema 'RiskEvidenceSynthesis #f 'DomainResource "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.status" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.note" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.jurisdiction" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.copyright" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.effectivePeriod" #f)
    (schema-field 'topic 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.topic" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.endorser" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.relatedArtifact" #f)
    (schema-field 'synthesisType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.synthesisType" #f)
    (schema-field 'studyType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.studyType" #f)
    (schema-field 'population 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.population" #f)
    (schema-field 'exposure 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.exposure" #f)
    (schema-field 'outcome 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.outcome" #f)
    (schema-field 'sampleSize 0 1 (vector 'type 'RiskEvidenceSynthesisSampleSize) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize" #f)
    (schema-field 'riskEstimate 0 1 (vector 'type 'RiskEvidenceSynthesisRiskEstimate) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate" #f)
    (schema-field 'certainty 0 '* (vector 'type 'RiskEvidenceSynthesisCertainty) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty" #f)
             ) #f #f))
(register-element! "RiskEvidenceSynthesis.url" (fhir-spec (string->symbol "RiskEvidenceSynthesis.url") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.url" 'element))
(register-element! "RiskEvidenceSynthesis.identifier" (fhir-spec (string->symbol "RiskEvidenceSynthesis.identifier") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.identifier" 'element))
(register-element! "RiskEvidenceSynthesis.version" (fhir-spec (string->symbol "RiskEvidenceSynthesis.version") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.version" 'element))
(register-element! "RiskEvidenceSynthesis.name" (fhir-spec (string->symbol "RiskEvidenceSynthesis.name") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.name" 'element))
(register-element! "RiskEvidenceSynthesis.title" (fhir-spec (string->symbol "RiskEvidenceSynthesis.title") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.title" 'element))
(register-element! "RiskEvidenceSynthesis.status" (fhir-spec (string->symbol "RiskEvidenceSynthesis.status") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.status" 'element))
(register-element! "RiskEvidenceSynthesis.date" (fhir-spec (string->symbol "RiskEvidenceSynthesis.date") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.date" 'element))
(register-element! "RiskEvidenceSynthesis.publisher" (fhir-spec (string->symbol "RiskEvidenceSynthesis.publisher") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.publisher" 'element))
(register-element! "RiskEvidenceSynthesis.contact" (fhir-spec (string->symbol "RiskEvidenceSynthesis.contact") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.contact" 'element))
(register-element! "RiskEvidenceSynthesis.description" (fhir-spec (string->symbol "RiskEvidenceSynthesis.description") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.description" 'element))
(register-element! "RiskEvidenceSynthesis.note" (fhir-spec (string->symbol "RiskEvidenceSynthesis.note") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.note" 'element))
(register-element! "RiskEvidenceSynthesis.useContext" (fhir-spec (string->symbol "RiskEvidenceSynthesis.useContext") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.useContext" 'element))
(register-element! "RiskEvidenceSynthesis.jurisdiction" (fhir-spec (string->symbol "RiskEvidenceSynthesis.jurisdiction") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.jurisdiction" 'element))
(register-element! "RiskEvidenceSynthesis.copyright" (fhir-spec (string->symbol "RiskEvidenceSynthesis.copyright") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.copyright" 'element))
(register-element! "RiskEvidenceSynthesis.approvalDate" (fhir-spec (string->symbol "RiskEvidenceSynthesis.approvalDate") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.approvalDate" 'element))
(register-element! "RiskEvidenceSynthesis.lastReviewDate" (fhir-spec (string->symbol "RiskEvidenceSynthesis.lastReviewDate") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.lastReviewDate" 'element))
(register-element! "RiskEvidenceSynthesis.effectivePeriod" (fhir-spec (string->symbol "RiskEvidenceSynthesis.effectivePeriod") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.effectivePeriod" 'element))
(register-element! "RiskEvidenceSynthesis.topic" (fhir-spec (string->symbol "RiskEvidenceSynthesis.topic") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.topic" 'element))
(register-element! "RiskEvidenceSynthesis.author" (fhir-spec (string->symbol "RiskEvidenceSynthesis.author") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.author" 'element))
(register-element! "RiskEvidenceSynthesis.editor" (fhir-spec (string->symbol "RiskEvidenceSynthesis.editor") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.editor" 'element))
(register-element! "RiskEvidenceSynthesis.reviewer" (fhir-spec (string->symbol "RiskEvidenceSynthesis.reviewer") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.reviewer" 'element))
(register-element! "RiskEvidenceSynthesis.endorser" (fhir-spec (string->symbol "RiskEvidenceSynthesis.endorser") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.endorser" 'element))
(register-element! "RiskEvidenceSynthesis.relatedArtifact" (fhir-spec (string->symbol "RiskEvidenceSynthesis.relatedArtifact") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.relatedArtifact" 'element))
(register-element! "RiskEvidenceSynthesis.synthesisType" (fhir-spec (string->symbol "RiskEvidenceSynthesis.synthesisType") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.synthesisType" 'element))
(register-element! "RiskEvidenceSynthesis.studyType" (fhir-spec (string->symbol "RiskEvidenceSynthesis.studyType") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.studyType" 'element))
(register-element! "RiskEvidenceSynthesis.population" (fhir-spec (string->symbol "RiskEvidenceSynthesis.population") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.population" 'element))
(register-element! "RiskEvidenceSynthesis.exposure" (fhir-spec (string->symbol "RiskEvidenceSynthesis.exposure") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.exposure" 'element))
(register-element! "RiskEvidenceSynthesis.outcome" (fhir-spec (string->symbol "RiskEvidenceSynthesis.outcome") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.outcome" 'element))
(register-element! "RiskEvidenceSynthesis.sampleSize" (fhir-spec (string->symbol "RiskEvidenceSynthesis.sampleSize") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate" 'element))
(register-element! "RiskEvidenceSynthesis.certainty" (fhir-spec (string->symbol "RiskEvidenceSynthesis.certainty") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty" 'element))

(register-type! 'RiskEvidenceSynthesisSampleSize (fhir-spec 'RiskEvidenceSynthesisSampleSize "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize" 'type)
  #:schema (type-schema 'RiskEvidenceSynthesisSampleSize #f 'BackboneElement "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize"
             (list
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize.description" #f)
    (schema-field 'numberOfStudies 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize.numberOfStudies" #f)
    (schema-field 'numberOfParticipants 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize.numberOfParticipants" #f)
             ) #f #f))
(register-element! "RiskEvidenceSynthesis.sampleSize.description" (fhir-spec (string->symbol "RiskEvidenceSynthesis.sampleSize.description") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize.description" 'element))
(register-element! "RiskEvidenceSynthesis.sampleSize.numberOfStudies" (fhir-spec (string->symbol "RiskEvidenceSynthesis.sampleSize.numberOfStudies") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize.numberOfStudies" 'element))
(register-element! "RiskEvidenceSynthesis.sampleSize.numberOfParticipants" (fhir-spec (string->symbol "RiskEvidenceSynthesis.sampleSize.numberOfParticipants") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.sampleSize.numberOfParticipants" 'element))

(register-type! 'RiskEvidenceSynthesisRiskEstimate (fhir-spec 'RiskEvidenceSynthesisRiskEstimate "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate" 'type)
  #:schema (type-schema 'RiskEvidenceSynthesisRiskEstimate #f 'BackboneElement "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate"
             (list
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.description" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.type" #f)
    (schema-field 'value 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.value" #f)
    (schema-field 'unitOfMeasure 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.unitOfMeasure" #f)
    (schema-field 'denominatorCount 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.denominatorCount" #f)
    (schema-field 'numeratorCount 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.numeratorCount" #f)
    (schema-field 'precisionEstimate 0 '* (vector 'type 'RiskEvidenceSynthesisRiskEstimatePrecisionEstimate) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate" #f)
             ) #f #f))
(register-element! "RiskEvidenceSynthesis.riskEstimate.description" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.description") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.description" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.type" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.type") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.type" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.value" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.value") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.value" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.unitOfMeasure" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.unitOfMeasure") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.unitOfMeasure" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.denominatorCount" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.denominatorCount") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.denominatorCount" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.numeratorCount" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.numeratorCount") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.numeratorCount" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.precisionEstimate" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.precisionEstimate") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate" 'element))

(register-type! 'RiskEvidenceSynthesisRiskEstimatePrecisionEstimate (fhir-spec 'RiskEvidenceSynthesisRiskEstimatePrecisionEstimate "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate" 'type)
  #:schema (type-schema 'RiskEvidenceSynthesisRiskEstimatePrecisionEstimate #f 'BackboneElement "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.type" #f)
    (schema-field 'level 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.level" #f)
    (schema-field 'from 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.from" #f)
    (schema-field 'to 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.to" #f)
             ) #f #f))
(register-element! "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.type" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.type") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.type" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.level" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.level") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.level" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.from" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.from") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.from" 'element))
(register-element! "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.to" (fhir-spec (string->symbol "RiskEvidenceSynthesis.riskEstimate.precisionEstimate.to") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.riskEstimate.precisionEstimate.to" 'element))

(register-type! 'RiskEvidenceSynthesisCertainty (fhir-spec 'RiskEvidenceSynthesisCertainty "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty" 'type)
  #:schema (type-schema 'RiskEvidenceSynthesisCertainty #f 'BackboneElement "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty"
             (list
    (schema-field 'rating 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.rating" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.note" #f)
    (schema-field 'certaintySubcomponent 0 '* (vector 'type 'RiskEvidenceSynthesisCertaintyCertaintySubcomponent) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent" #f)
             ) #f #f))
(register-element! "RiskEvidenceSynthesis.certainty.rating" (fhir-spec (string->symbol "RiskEvidenceSynthesis.certainty.rating") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.rating" 'element))
(register-element! "RiskEvidenceSynthesis.certainty.note" (fhir-spec (string->symbol "RiskEvidenceSynthesis.certainty.note") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.note" 'element))
(register-element! "RiskEvidenceSynthesis.certainty.certaintySubcomponent" (fhir-spec (string->symbol "RiskEvidenceSynthesis.certainty.certaintySubcomponent") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent" 'element))

(register-type! 'RiskEvidenceSynthesisCertaintyCertaintySubcomponent (fhir-spec 'RiskEvidenceSynthesisCertaintyCertaintySubcomponent "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent" 'type)
  #:schema (type-schema 'RiskEvidenceSynthesisCertaintyCertaintySubcomponent #f 'BackboneElement "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent.type" #f)
    (schema-field 'rating 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent.rating" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent.note" #f)
             ) #f #f))
(register-element! "RiskEvidenceSynthesis.certainty.certaintySubcomponent.type" (fhir-spec (string->symbol "RiskEvidenceSynthesis.certainty.certaintySubcomponent.type") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent.type" 'element))
(register-element! "RiskEvidenceSynthesis.certainty.certaintySubcomponent.rating" (fhir-spec (string->symbol "RiskEvidenceSynthesis.certainty.certaintySubcomponent.rating") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent.rating" 'element))
(register-element! "RiskEvidenceSynthesis.certainty.certaintySubcomponent.note" (fhir-spec (string->symbol "RiskEvidenceSynthesis.certainty.certaintySubcomponent.note") "https://hl7.org/fhir/R4/riskevidencesynthesis.html#RiskEvidenceSynthesis.certainty.certaintySubcomponent.note" 'element))

