#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'RiskAssessment (fhir-spec 'RiskAssessment "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment" 'type)
  #:schema (type-schema 'RiskAssessment #f 'DomainResource "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.identifier" #f)
    (schema-field 'basedOn 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.basedOn" #f)
    (schema-field 'parent 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.parent" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.status" #f)
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.method" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.code" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.encounter" #f)
    (schema-field 'condition 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.condition" #f)
    (schema-field 'performer 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.performer" #f)
    (schema-field 'reasonCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.reasonCode" #f)
    (schema-field 'reasonReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.reasonReference" #f)
    (schema-field 'basis 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.basis" #f)
    (schema-field 'prediction 0 '* (vector 'type 'RiskAssessmentPrediction) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction" #f)
    (schema-field 'mitigation 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.mitigation" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.note" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.occurrence[x]" #f)
             ) #f #f))
(register-element! "RiskAssessment.identifier" (fhir-spec (string->symbol "RiskAssessment.identifier") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.identifier" 'element))
(register-element! "RiskAssessment.basedOn" (fhir-spec (string->symbol "RiskAssessment.basedOn") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.basedOn" 'element))
(register-element! "RiskAssessment.parent" (fhir-spec (string->symbol "RiskAssessment.parent") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.parent" 'element))
(register-element! "RiskAssessment.status" (fhir-spec (string->symbol "RiskAssessment.status") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.status" 'element))
(register-element! "RiskAssessment.method" (fhir-spec (string->symbol "RiskAssessment.method") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.method" 'element))
(register-element! "RiskAssessment.code" (fhir-spec (string->symbol "RiskAssessment.code") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.code" 'element))
(register-element! "RiskAssessment.subject" (fhir-spec (string->symbol "RiskAssessment.subject") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.subject" 'element))
(register-element! "RiskAssessment.encounter" (fhir-spec (string->symbol "RiskAssessment.encounter") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.encounter" 'element))
(register-element! "RiskAssessment.condition" (fhir-spec (string->symbol "RiskAssessment.condition") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.condition" 'element))
(register-element! "RiskAssessment.performer" (fhir-spec (string->symbol "RiskAssessment.performer") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.performer" 'element))
(register-element! "RiskAssessment.reasonCode" (fhir-spec (string->symbol "RiskAssessment.reasonCode") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.reasonCode" 'element))
(register-element! "RiskAssessment.reasonReference" (fhir-spec (string->symbol "RiskAssessment.reasonReference") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.reasonReference" 'element))
(register-element! "RiskAssessment.basis" (fhir-spec (string->symbol "RiskAssessment.basis") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.basis" 'element))
(register-element! "RiskAssessment.prediction" (fhir-spec (string->symbol "RiskAssessment.prediction") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction" 'element))
(register-element! "RiskAssessment.mitigation" (fhir-spec (string->symbol "RiskAssessment.mitigation") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.mitigation" 'element))
(register-element! "RiskAssessment.note" (fhir-spec (string->symbol "RiskAssessment.note") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.note" 'element))
(register-element! "RiskAssessment.occurrence[x]" (fhir-spec (string->symbol "RiskAssessment.occurrence[x]") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.occurrence[x]" 'element))
(register-element! "RiskAssessment.occurrence[x]" (fhir-spec (string->symbol "RiskAssessment.occurrence[x]") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.occurrence[x]" 'element))

(register-type! 'RiskAssessmentPrediction (fhir-spec 'RiskAssessmentPrediction "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction" 'type)
  #:schema (type-schema 'RiskAssessmentPrediction #f 'BackboneElement "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction"
             (list
    (schema-field 'outcome 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.outcome" #f)
    (schema-field 'qualitativeRisk 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.qualitativeRisk" #f)
    (schema-field 'relativeRisk 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.relativeRisk" #f)
    (schema-field 'rationale 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.rationale" #f)
    (schema-field 'probabilityDecimal 0 1 (vector 'prim "decimal") 'probability "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.probability[x]" #f)
    (schema-field 'probabilityRange 0 1 (vector 'type 'Range) 'probability "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.probability[x]" #f)
    (schema-field 'whenPeriod 0 1 (vector 'type 'Period) 'when "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.when[x]" #f)
    (schema-field 'whenRange 0 1 (vector 'type 'Range) 'when "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.when[x]" #f)
             ) #f #f))
(register-element! "RiskAssessment.prediction.outcome" (fhir-spec (string->symbol "RiskAssessment.prediction.outcome") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.outcome" 'element))
(register-element! "RiskAssessment.prediction.qualitativeRisk" (fhir-spec (string->symbol "RiskAssessment.prediction.qualitativeRisk") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.qualitativeRisk" 'element))
(register-element! "RiskAssessment.prediction.relativeRisk" (fhir-spec (string->symbol "RiskAssessment.prediction.relativeRisk") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.relativeRisk" 'element))
(register-element! "RiskAssessment.prediction.rationale" (fhir-spec (string->symbol "RiskAssessment.prediction.rationale") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.rationale" 'element))
(register-element! "RiskAssessment.prediction.probability[x]" (fhir-spec (string->symbol "RiskAssessment.prediction.probability[x]") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.probability[x]" 'element))
(register-element! "RiskAssessment.prediction.probability[x]" (fhir-spec (string->symbol "RiskAssessment.prediction.probability[x]") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.probability[x]" 'element))
(register-element! "RiskAssessment.prediction.when[x]" (fhir-spec (string->symbol "RiskAssessment.prediction.when[x]") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.when[x]" 'element))
(register-element! "RiskAssessment.prediction.when[x]" (fhir-spec (string->symbol "RiskAssessment.prediction.when[x]") "https://hl7.org/fhir/R4/riskassessment.html#RiskAssessment.prediction.when[x]" 'element))

