#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'StructureMap (fhir-spec 'StructureMap "https://hl7.org/fhir/R4/structuremap.html#StructureMap" 'type)
  #:schema (type-schema 'StructureMap #f 'DomainResource "https://hl7.org/fhir/R4/structuremap.html#StructureMap"
             (list
    (schema-field 'url 1 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.version" #f)
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.copyright" #f)
    (schema-field 'structure 0 '* (vector 'type 'StructureMapStructure) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure" #f)
    (schema-field 'import 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.import" #f)
    (schema-field 'group 1 '* (vector 'type 'StructureMapGroup) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group" #f)
             ) #f #f))
(register-element! "StructureMap.url" (fhir-spec (string->symbol "StructureMap.url") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.url" 'element))
(register-element! "StructureMap.identifier" (fhir-spec (string->symbol "StructureMap.identifier") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.identifier" 'element))
(register-element! "StructureMap.version" (fhir-spec (string->symbol "StructureMap.version") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.version" 'element))
(register-element! "StructureMap.name" (fhir-spec (string->symbol "StructureMap.name") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.name" 'element))
(register-element! "StructureMap.title" (fhir-spec (string->symbol "StructureMap.title") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.title" 'element))
(register-element! "StructureMap.status" (fhir-spec (string->symbol "StructureMap.status") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.status" 'element))
(register-element! "StructureMap.experimental" (fhir-spec (string->symbol "StructureMap.experimental") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.experimental" 'element))
(register-element! "StructureMap.date" (fhir-spec (string->symbol "StructureMap.date") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.date" 'element))
(register-element! "StructureMap.publisher" (fhir-spec (string->symbol "StructureMap.publisher") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.publisher" 'element))
(register-element! "StructureMap.contact" (fhir-spec (string->symbol "StructureMap.contact") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.contact" 'element))
(register-element! "StructureMap.description" (fhir-spec (string->symbol "StructureMap.description") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.description" 'element))
(register-element! "StructureMap.useContext" (fhir-spec (string->symbol "StructureMap.useContext") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.useContext" 'element))
(register-element! "StructureMap.jurisdiction" (fhir-spec (string->symbol "StructureMap.jurisdiction") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.jurisdiction" 'element))
(register-element! "StructureMap.purpose" (fhir-spec (string->symbol "StructureMap.purpose") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.purpose" 'element))
(register-element! "StructureMap.copyright" (fhir-spec (string->symbol "StructureMap.copyright") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.copyright" 'element))
(register-element! "StructureMap.structure" (fhir-spec (string->symbol "StructureMap.structure") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure" 'element))
(register-element! "StructureMap.import" (fhir-spec (string->symbol "StructureMap.import") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.import" 'element))
(register-element! "StructureMap.group" (fhir-spec (string->symbol "StructureMap.group") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group" 'element))

(register-type! 'StructureMapStructure (fhir-spec 'StructureMapStructure "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure" 'type)
  #:schema (type-schema 'StructureMapStructure #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure"
             (list
    (schema-field 'url 1 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.url" #f)
    (schema-field 'mode 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.mode" #f)
    (schema-field 'alias 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.alias" #f)
    (schema-field 'documentation 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.documentation" #f)
             ) #f #f))
(register-element! "StructureMap.structure.url" (fhir-spec (string->symbol "StructureMap.structure.url") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.url" 'element))
(register-element! "StructureMap.structure.mode" (fhir-spec (string->symbol "StructureMap.structure.mode") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.mode" 'element))
(register-element! "StructureMap.structure.alias" (fhir-spec (string->symbol "StructureMap.structure.alias") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.alias" 'element))
(register-element! "StructureMap.structure.documentation" (fhir-spec (string->symbol "StructureMap.structure.documentation") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.structure.documentation" 'element))

(register-type! 'StructureMapGroup (fhir-spec 'StructureMapGroup "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group" 'type)
  #:schema (type-schema 'StructureMapGroup #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group"
             (list
    (schema-field 'name 1 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.name" #f)
    (schema-field 'extends 0 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.extends" #f)
    (schema-field 'typeMode 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.typeMode" #f)
    (schema-field 'documentation 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.documentation" #f)
    (schema-field 'input 1 '* (vector 'type 'StructureMapGroupInput) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input" #f)
    (schema-field 'rule 1 '* (vector 'type 'StructureMapGroupRule) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule" #f)
             ) #f #f))
(register-element! "StructureMap.group.name" (fhir-spec (string->symbol "StructureMap.group.name") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.name" 'element))
(register-element! "StructureMap.group.extends" (fhir-spec (string->symbol "StructureMap.group.extends") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.extends" 'element))
(register-element! "StructureMap.group.typeMode" (fhir-spec (string->symbol "StructureMap.group.typeMode") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.typeMode" 'element))
(register-element! "StructureMap.group.documentation" (fhir-spec (string->symbol "StructureMap.group.documentation") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.documentation" 'element))
(register-element! "StructureMap.group.input" (fhir-spec (string->symbol "StructureMap.group.input") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input" 'element))
(register-element! "StructureMap.group.rule" (fhir-spec (string->symbol "StructureMap.group.rule") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule" 'element))

(register-type! 'StructureMapGroupInput (fhir-spec 'StructureMapGroupInput "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input" 'type)
  #:schema (type-schema 'StructureMapGroupInput #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input"
             (list
    (schema-field 'name 1 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.name" #f)
    (schema-field 'type 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.type" #f)
    (schema-field 'mode 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.mode" #f)
    (schema-field 'documentation 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.documentation" #f)
             ) #f #f))
(register-element! "StructureMap.group.input.name" (fhir-spec (string->symbol "StructureMap.group.input.name") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.name" 'element))
(register-element! "StructureMap.group.input.type" (fhir-spec (string->symbol "StructureMap.group.input.type") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.type" 'element))
(register-element! "StructureMap.group.input.mode" (fhir-spec (string->symbol "StructureMap.group.input.mode") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.mode" 'element))
(register-element! "StructureMap.group.input.documentation" (fhir-spec (string->symbol "StructureMap.group.input.documentation") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.input.documentation" 'element))

(register-type! 'StructureMapGroupRule (fhir-spec 'StructureMapGroupRule "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule" 'type)
  #:schema (type-schema 'StructureMapGroupRule #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule"
             (list
    (schema-field 'name 1 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.name" #f)
    (schema-field 'source 1 '* (vector 'type 'StructureMapGroupRuleSource) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source" #f)
    (schema-field 'target 0 '* (vector 'type 'StructureMapGroupRuleTarget) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target" #f)
    (schema-field 'rule 0 '* (vector 'type 'StructureMapGroupRule) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.rule" #f)
    (schema-field 'dependent 0 '* (vector 'type 'StructureMapGroupRuleDependent) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent" #f)
    (schema-field 'documentation 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.documentation" #f)
             ) #f #f))
(register-element! "StructureMap.group.rule.name" (fhir-spec (string->symbol "StructureMap.group.rule.name") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.name" 'element))
(register-element! "StructureMap.group.rule.source" (fhir-spec (string->symbol "StructureMap.group.rule.source") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source" 'element))
(register-element! "StructureMap.group.rule.target" (fhir-spec (string->symbol "StructureMap.group.rule.target") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target" 'element))
(register-element! "StructureMap.group.rule.rule" (fhir-spec (string->symbol "StructureMap.group.rule.rule") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.rule" 'element))
(register-element! "StructureMap.group.rule.dependent" (fhir-spec (string->symbol "StructureMap.group.rule.dependent") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent" 'element))
(register-element! "StructureMap.group.rule.documentation" (fhir-spec (string->symbol "StructureMap.group.rule.documentation") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.documentation" 'element))

(register-type! 'StructureMapGroupRuleSource (fhir-spec 'StructureMapGroupRuleSource "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source" 'type)
  #:schema (type-schema 'StructureMapGroupRuleSource #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source"
             (list
    (schema-field 'context 1 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.context" #f)
    (schema-field 'min 0 1 (vector 'prim "integer") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.min" #f)
    (schema-field 'max 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.max" #f)
    (schema-field 'type 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.type" #f)
    (schema-field 'element 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.element" #f)
    (schema-field 'listMode 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.listMode" #f)
    (schema-field 'variable 0 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.variable" #f)
    (schema-field 'condition 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.condition" #f)
    (schema-field 'check 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.check" #f)
    (schema-field 'logMessage 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.logMessage" #f)
    (schema-field 'defaultValueBase64Binary 0 1 (vector 'prim "base64Binary") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueBoolean 0 1 (vector 'prim "boolean") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueCanonical 0 1 (vector 'prim "canonical") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueCode 0 1 (vector 'prim "code") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueDate 0 1 (vector 'prim "date") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueDateTime 0 1 (vector 'prim "dateTime") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueDecimal 0 1 (vector 'prim "decimal") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueId 0 1 (vector 'prim "id") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueInstant 0 1 (vector 'prim "instant") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueInteger 0 1 (vector 'prim "integer") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueMarkdown 0 1 (vector 'prim "markdown") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueOid 0 1 (vector 'prim "oid") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValuePositiveInt 0 1 (vector 'prim "positiveInt") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueString 0 1 (vector 'prim "string") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueTime 0 1 (vector 'prim "time") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueUri 0 1 (vector 'prim "uri") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueUrl 0 1 (vector 'prim "url") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueUuid 0 1 (vector 'prim "uuid") 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueAddress 0 1 (vector 'type 'Address) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueAge 0 1 (vector 'type 'Age) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueAnnotation 0 1 (vector 'type 'Annotation) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueAttachment 0 1 (vector 'type 'Attachment) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueCoding 0 1 (vector 'type 'Coding) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueContactPoint 0 1 (vector 'type 'ContactPoint) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueCount 0 1 (vector 'type 'Count) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueDistance 0 1 (vector 'type 'Distance) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueDuration 0 1 (vector 'type 'Duration) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueHumanName 0 1 (vector 'type 'HumanName) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueIdentifier 0 1 (vector 'type 'Identifier) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueMoney 0 1 (vector 'type 'Money) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValuePeriod 0 1 (vector 'type 'Period) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueQuantity 0 1 (vector 'type 'Quantity) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueRange 0 1 (vector 'type 'Range) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueRatio 0 1 (vector 'type 'Ratio) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueReference 0 1 (vector 'type 'Reference) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueSampledData 0 1 (vector 'type 'SampledData) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueSignature 0 1 (vector 'type 'Signature) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueTiming 0 1 (vector 'type 'Timing) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueContactDetail 0 1 (vector 'type 'ContactDetail) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueContributor 0 1 (vector 'type 'Contributor) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueDataRequirement 0 1 (vector 'type 'DataRequirement) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueExpression 0 1 (vector 'type 'Expression) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueUsageContext 0 1 (vector 'type 'UsageContext) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueDosage 0 1 (vector 'type 'Dosage) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
    (schema-field 'defaultValueMeta 0 1 (vector 'type 'Meta) 'defaultValue "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" #f)
             ) #f #f))
(register-element! "StructureMap.group.rule.source.context" (fhir-spec (string->symbol "StructureMap.group.rule.source.context") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.context" 'element))
(register-element! "StructureMap.group.rule.source.min" (fhir-spec (string->symbol "StructureMap.group.rule.source.min") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.min" 'element))
(register-element! "StructureMap.group.rule.source.max" (fhir-spec (string->symbol "StructureMap.group.rule.source.max") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.max" 'element))
(register-element! "StructureMap.group.rule.source.type" (fhir-spec (string->symbol "StructureMap.group.rule.source.type") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.type" 'element))
(register-element! "StructureMap.group.rule.source.element" (fhir-spec (string->symbol "StructureMap.group.rule.source.element") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.element" 'element))
(register-element! "StructureMap.group.rule.source.listMode" (fhir-spec (string->symbol "StructureMap.group.rule.source.listMode") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.listMode" 'element))
(register-element! "StructureMap.group.rule.source.variable" (fhir-spec (string->symbol "StructureMap.group.rule.source.variable") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.variable" 'element))
(register-element! "StructureMap.group.rule.source.condition" (fhir-spec (string->symbol "StructureMap.group.rule.source.condition") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.condition" 'element))
(register-element! "StructureMap.group.rule.source.check" (fhir-spec (string->symbol "StructureMap.group.rule.source.check") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.check" 'element))
(register-element! "StructureMap.group.rule.source.logMessage" (fhir-spec (string->symbol "StructureMap.group.rule.source.logMessage") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.logMessage" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))
(register-element! "StructureMap.group.rule.source.defaultValue[x]" (fhir-spec (string->symbol "StructureMap.group.rule.source.defaultValue[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.source.defaultValue[x]" 'element))

(register-type! 'StructureMapGroupRuleTarget (fhir-spec 'StructureMapGroupRuleTarget "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target" 'type)
  #:schema (type-schema 'StructureMapGroupRuleTarget #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target"
             (list
    (schema-field 'context 0 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.context" #f)
    (schema-field 'contextType 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.contextType" #f)
    (schema-field 'element 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.element" #f)
    (schema-field 'variable 0 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.variable" #f)
    (schema-field 'listMode 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.listMode" #f)
    (schema-field 'listRuleId 0 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.listRuleId" #f)
    (schema-field 'transform 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.transform" #f)
    (schema-field 'parameter 0 '* (vector 'type 'StructureMapGroupRuleTargetParameter) #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter" #f)
             ) #f #f))
(register-element! "StructureMap.group.rule.target.context" (fhir-spec (string->symbol "StructureMap.group.rule.target.context") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.context" 'element))
(register-element! "StructureMap.group.rule.target.contextType" (fhir-spec (string->symbol "StructureMap.group.rule.target.contextType") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.contextType" 'element))
(register-element! "StructureMap.group.rule.target.element" (fhir-spec (string->symbol "StructureMap.group.rule.target.element") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.element" 'element))
(register-element! "StructureMap.group.rule.target.variable" (fhir-spec (string->symbol "StructureMap.group.rule.target.variable") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.variable" 'element))
(register-element! "StructureMap.group.rule.target.listMode" (fhir-spec (string->symbol "StructureMap.group.rule.target.listMode") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.listMode" 'element))
(register-element! "StructureMap.group.rule.target.listRuleId" (fhir-spec (string->symbol "StructureMap.group.rule.target.listRuleId") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.listRuleId" 'element))
(register-element! "StructureMap.group.rule.target.transform" (fhir-spec (string->symbol "StructureMap.group.rule.target.transform") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.transform" 'element))
(register-element! "StructureMap.group.rule.target.parameter" (fhir-spec (string->symbol "StructureMap.group.rule.target.parameter") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter" 'element))

(register-type! 'StructureMapGroupRuleTargetParameter (fhir-spec 'StructureMapGroupRuleTargetParameter "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter" 'type)
  #:schema (type-schema 'StructureMapGroupRuleTargetParameter #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter"
             (list
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" #f)
             ) #f #f))
(register-element! "StructureMap.group.rule.target.parameter.value[x]" (fhir-spec (string->symbol "StructureMap.group.rule.target.parameter.value[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" 'element))
(register-element! "StructureMap.group.rule.target.parameter.value[x]" (fhir-spec (string->symbol "StructureMap.group.rule.target.parameter.value[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" 'element))
(register-element! "StructureMap.group.rule.target.parameter.value[x]" (fhir-spec (string->symbol "StructureMap.group.rule.target.parameter.value[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" 'element))
(register-element! "StructureMap.group.rule.target.parameter.value[x]" (fhir-spec (string->symbol "StructureMap.group.rule.target.parameter.value[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" 'element))
(register-element! "StructureMap.group.rule.target.parameter.value[x]" (fhir-spec (string->symbol "StructureMap.group.rule.target.parameter.value[x]") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.target.parameter.value[x]" 'element))

(register-type! 'StructureMapGroupRuleDependent (fhir-spec 'StructureMapGroupRuleDependent "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent" 'type)
  #:schema (type-schema 'StructureMapGroupRuleDependent #f 'BackboneElement "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent"
             (list
    (schema-field 'name 1 1 (vector 'prim "id") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent.name" #f)
    (schema-field 'variable 1 '* (vector 'prim "string") #f "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent.variable" #f)
             ) #f #f))
(register-element! "StructureMap.group.rule.dependent.name" (fhir-spec (string->symbol "StructureMap.group.rule.dependent.name") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent.name" 'element))
(register-element! "StructureMap.group.rule.dependent.variable" (fhir-spec (string->symbol "StructureMap.group.rule.dependent.variable") "https://hl7.org/fhir/R4/structuremap.html#StructureMap.group.rule.dependent.variable" 'element))

