#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Task (fhir-spec 'Task "https://hl7.org/fhir/R4/task.html#Task" 'type)
  #:schema (type-schema 'Task #f 'DomainResource "https://hl7.org/fhir/R4/task.html#Task"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/task.html#Task.identifier" #f)
    (schema-field 'instantiatesCanonical 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R4/task.html#Task.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R4/task.html#Task.instantiatesUri" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.basedOn" #f)
    (schema-field 'groupIdentifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R4/task.html#Task.groupIdentifier" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/task.html#Task.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/task.html#Task.statusReason" #f)
    (schema-field 'businessStatus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/task.html#Task.businessStatus" #f)
    (schema-field 'intent 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/task.html#Task.intent" #f)
    (schema-field 'priority 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/task.html#Task.priority" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/task.html#Task.code" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/task.html#Task.description" #f)
    (schema-field 'focus 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.focus" #f)
    (schema-field 'for 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.for" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.encounter" #f)
    (schema-field 'executionPeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/task.html#Task.executionPeriod" #f)
    (schema-field 'authoredOn 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/task.html#Task.authoredOn" #f)
    (schema-field 'lastModified 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/task.html#Task.lastModified" #f)
    (schema-field 'requester 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.requester" #f)
    (schema-field 'performerType 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/task.html#Task.performerType" #f)
    (schema-field 'owner 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.owner" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.location" #f)
    (schema-field 'reasonCode 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/task.html#Task.reasonCode" #f)
    (schema-field 'reasonReference 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.reasonReference" #f)
    (schema-field 'insurance 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.insurance" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R4/task.html#Task.note" #f)
    (schema-field 'relevantHistory 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.relevantHistory" #f)
    (schema-field 'restriction 0 1 (vector 'type 'TaskRestriction) #f "https://hl7.org/fhir/R4/task.html#Task.restriction" #f)
    (schema-field 'input 0 '* (vector 'type 'TaskInput) #f "https://hl7.org/fhir/R4/task.html#Task.input" #f)
    (schema-field 'output 0 '* (vector 'type 'TaskOutput) #f "https://hl7.org/fhir/R4/task.html#Task.output" #f)
             ) #f #f))
(register-element! "Task.identifier" (fhir-spec (string->symbol "Task.identifier") "https://hl7.org/fhir/R4/task.html#Task.identifier" 'element))
(register-element! "Task.instantiatesCanonical" (fhir-spec (string->symbol "Task.instantiatesCanonical") "https://hl7.org/fhir/R4/task.html#Task.instantiatesCanonical" 'element))
(register-element! "Task.instantiatesUri" (fhir-spec (string->symbol "Task.instantiatesUri") "https://hl7.org/fhir/R4/task.html#Task.instantiatesUri" 'element))
(register-element! "Task.basedOn" (fhir-spec (string->symbol "Task.basedOn") "https://hl7.org/fhir/R4/task.html#Task.basedOn" 'element))
(register-element! "Task.groupIdentifier" (fhir-spec (string->symbol "Task.groupIdentifier") "https://hl7.org/fhir/R4/task.html#Task.groupIdentifier" 'element))
(register-element! "Task.partOf" (fhir-spec (string->symbol "Task.partOf") "https://hl7.org/fhir/R4/task.html#Task.partOf" 'element))
(register-element! "Task.status" (fhir-spec (string->symbol "Task.status") "https://hl7.org/fhir/R4/task.html#Task.status" 'element))
(register-element! "Task.statusReason" (fhir-spec (string->symbol "Task.statusReason") "https://hl7.org/fhir/R4/task.html#Task.statusReason" 'element))
(register-element! "Task.businessStatus" (fhir-spec (string->symbol "Task.businessStatus") "https://hl7.org/fhir/R4/task.html#Task.businessStatus" 'element))
(register-element! "Task.intent" (fhir-spec (string->symbol "Task.intent") "https://hl7.org/fhir/R4/task.html#Task.intent" 'element))
(register-element! "Task.priority" (fhir-spec (string->symbol "Task.priority") "https://hl7.org/fhir/R4/task.html#Task.priority" 'element))
(register-element! "Task.code" (fhir-spec (string->symbol "Task.code") "https://hl7.org/fhir/R4/task.html#Task.code" 'element))
(register-element! "Task.description" (fhir-spec (string->symbol "Task.description") "https://hl7.org/fhir/R4/task.html#Task.description" 'element))
(register-element! "Task.focus" (fhir-spec (string->symbol "Task.focus") "https://hl7.org/fhir/R4/task.html#Task.focus" 'element))
(register-element! "Task.for" (fhir-spec (string->symbol "Task.for") "https://hl7.org/fhir/R4/task.html#Task.for" 'element))
(register-element! "Task.encounter" (fhir-spec (string->symbol "Task.encounter") "https://hl7.org/fhir/R4/task.html#Task.encounter" 'element))
(register-element! "Task.executionPeriod" (fhir-spec (string->symbol "Task.executionPeriod") "https://hl7.org/fhir/R4/task.html#Task.executionPeriod" 'element))
(register-element! "Task.authoredOn" (fhir-spec (string->symbol "Task.authoredOn") "https://hl7.org/fhir/R4/task.html#Task.authoredOn" 'element))
(register-element! "Task.lastModified" (fhir-spec (string->symbol "Task.lastModified") "https://hl7.org/fhir/R4/task.html#Task.lastModified" 'element))
(register-element! "Task.requester" (fhir-spec (string->symbol "Task.requester") "https://hl7.org/fhir/R4/task.html#Task.requester" 'element))
(register-element! "Task.performerType" (fhir-spec (string->symbol "Task.performerType") "https://hl7.org/fhir/R4/task.html#Task.performerType" 'element))
(register-element! "Task.owner" (fhir-spec (string->symbol "Task.owner") "https://hl7.org/fhir/R4/task.html#Task.owner" 'element))
(register-element! "Task.location" (fhir-spec (string->symbol "Task.location") "https://hl7.org/fhir/R4/task.html#Task.location" 'element))
(register-element! "Task.reasonCode" (fhir-spec (string->symbol "Task.reasonCode") "https://hl7.org/fhir/R4/task.html#Task.reasonCode" 'element))
(register-element! "Task.reasonReference" (fhir-spec (string->symbol "Task.reasonReference") "https://hl7.org/fhir/R4/task.html#Task.reasonReference" 'element))
(register-element! "Task.insurance" (fhir-spec (string->symbol "Task.insurance") "https://hl7.org/fhir/R4/task.html#Task.insurance" 'element))
(register-element! "Task.note" (fhir-spec (string->symbol "Task.note") "https://hl7.org/fhir/R4/task.html#Task.note" 'element))
(register-element! "Task.relevantHistory" (fhir-spec (string->symbol "Task.relevantHistory") "https://hl7.org/fhir/R4/task.html#Task.relevantHistory" 'element))
(register-element! "Task.restriction" (fhir-spec (string->symbol "Task.restriction") "https://hl7.org/fhir/R4/task.html#Task.restriction" 'element))
(register-element! "Task.input" (fhir-spec (string->symbol "Task.input") "https://hl7.org/fhir/R4/task.html#Task.input" 'element))
(register-element! "Task.output" (fhir-spec (string->symbol "Task.output") "https://hl7.org/fhir/R4/task.html#Task.output" 'element))

(register-type! 'TaskRestriction (fhir-spec 'TaskRestriction "https://hl7.org/fhir/R4/task.html#Task.restriction" 'type)
  #:schema (type-schema 'TaskRestriction #f 'BackboneElement "https://hl7.org/fhir/R4/task.html#Task.restriction"
             (list
    (schema-field 'repetitions 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R4/task.html#Task.restriction.repetitions" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R4/task.html#Task.restriction.period" #f)
    (schema-field 'recipient 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/task.html#Task.restriction.recipient" #f)
             ) #f #f))
(register-element! "Task.restriction.repetitions" (fhir-spec (string->symbol "Task.restriction.repetitions") "https://hl7.org/fhir/R4/task.html#Task.restriction.repetitions" 'element))
(register-element! "Task.restriction.period" (fhir-spec (string->symbol "Task.restriction.period") "https://hl7.org/fhir/R4/task.html#Task.restriction.period" 'element))
(register-element! "Task.restriction.recipient" (fhir-spec (string->symbol "Task.restriction.recipient") "https://hl7.org/fhir/R4/task.html#Task.restriction.recipient" 'element))

(register-type! 'TaskInput (fhir-spec 'TaskInput "https://hl7.org/fhir/R4/task.html#Task.input" 'type)
  #:schema (type-schema 'TaskInput #f 'BackboneElement "https://hl7.org/fhir/R4/task.html#Task.input"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/task.html#Task.input.type" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueContributor 0 1 (vector 'type 'Contributor) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" #f)
             ) #f #f))
(register-element! "Task.input.type" (fhir-spec (string->symbol "Task.input.type") "https://hl7.org/fhir/R4/task.html#Task.input.type" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://hl7.org/fhir/R4/task.html#Task.input.value[x]" 'element))

(register-type! 'TaskOutput (fhir-spec 'TaskOutput "https://hl7.org/fhir/R4/task.html#Task.output" 'type)
  #:schema (type-schema 'TaskOutput #f 'BackboneElement "https://hl7.org/fhir/R4/task.html#Task.output"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/task.html#Task.output.type" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueContributor 0 1 (vector 'type 'Contributor) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" #f)
             ) #f #f))
(register-element! "Task.output.type" (fhir-spec (string->symbol "Task.output.type") "https://hl7.org/fhir/R4/task.html#Task.output.type" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://hl7.org/fhir/R4/task.html#Task.output.value[x]" 'element))

