#lang racket/base
;;; GENERATED from hl7.fhir.r4.core#4.0.1 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'VerificationResult (fhir-spec 'VerificationResult "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult" 'type)
  #:schema (type-schema 'VerificationResult #f 'DomainResource "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult"
             (list
    (schema-field 'target 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.target" #f)
    (schema-field 'targetLocation 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.targetLocation" #f)
    (schema-field 'need 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.need" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.status" #f)
    (schema-field 'statusDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.statusDate" #f)
    (schema-field 'validationType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validationType" #f)
    (schema-field 'validationProcess 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validationProcess" #f)
    (schema-field 'frequency 0 1 (vector 'type 'Timing) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.frequency" #f)
    (schema-field 'lastPerformed 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.lastPerformed" #f)
    (schema-field 'nextScheduled 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.nextScheduled" #f)
    (schema-field 'failureAction 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.failureAction" #f)
    (schema-field 'primarySource 0 '* (vector 'type 'VerificationResultPrimarySource) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource" #f)
    (schema-field 'attestation 0 1 (vector 'type 'VerificationResultAttestation) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation" #f)
    (schema-field 'validator 0 '* (vector 'type 'VerificationResultValidator) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator" #f)
             ) #f #f))
(register-element! "VerificationResult.target" (fhir-spec (string->symbol "VerificationResult.target") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.target" 'element))
(register-element! "VerificationResult.targetLocation" (fhir-spec (string->symbol "VerificationResult.targetLocation") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.targetLocation" 'element))
(register-element! "VerificationResult.need" (fhir-spec (string->symbol "VerificationResult.need") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.need" 'element))
(register-element! "VerificationResult.status" (fhir-spec (string->symbol "VerificationResult.status") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.status" 'element))
(register-element! "VerificationResult.statusDate" (fhir-spec (string->symbol "VerificationResult.statusDate") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.statusDate" 'element))
(register-element! "VerificationResult.validationType" (fhir-spec (string->symbol "VerificationResult.validationType") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validationType" 'element))
(register-element! "VerificationResult.validationProcess" (fhir-spec (string->symbol "VerificationResult.validationProcess") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validationProcess" 'element))
(register-element! "VerificationResult.frequency" (fhir-spec (string->symbol "VerificationResult.frequency") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.frequency" 'element))
(register-element! "VerificationResult.lastPerformed" (fhir-spec (string->symbol "VerificationResult.lastPerformed") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.lastPerformed" 'element))
(register-element! "VerificationResult.nextScheduled" (fhir-spec (string->symbol "VerificationResult.nextScheduled") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.nextScheduled" 'element))
(register-element! "VerificationResult.failureAction" (fhir-spec (string->symbol "VerificationResult.failureAction") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.failureAction" 'element))
(register-element! "VerificationResult.primarySource" (fhir-spec (string->symbol "VerificationResult.primarySource") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource" 'element))
(register-element! "VerificationResult.attestation" (fhir-spec (string->symbol "VerificationResult.attestation") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation" 'element))
(register-element! "VerificationResult.validator" (fhir-spec (string->symbol "VerificationResult.validator") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator" 'element))

(register-type! 'VerificationResultPrimarySource (fhir-spec 'VerificationResultPrimarySource "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource" 'type)
  #:schema (type-schema 'VerificationResultPrimarySource #f 'BackboneElement "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource"
             (list
    (schema-field 'who 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.who" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.type" #f)
    (schema-field 'communicationMethod 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.communicationMethod" #f)
    (schema-field 'validationStatus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.validationStatus" #f)
    (schema-field 'validationDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.validationDate" #f)
    (schema-field 'canPushUpdates 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.canPushUpdates" #f)
    (schema-field 'pushTypeAvailable 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.pushTypeAvailable" #f)
             ) #f #f))
(register-element! "VerificationResult.primarySource.who" (fhir-spec (string->symbol "VerificationResult.primarySource.who") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.who" 'element))
(register-element! "VerificationResult.primarySource.type" (fhir-spec (string->symbol "VerificationResult.primarySource.type") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.type" 'element))
(register-element! "VerificationResult.primarySource.communicationMethod" (fhir-spec (string->symbol "VerificationResult.primarySource.communicationMethod") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.communicationMethod" 'element))
(register-element! "VerificationResult.primarySource.validationStatus" (fhir-spec (string->symbol "VerificationResult.primarySource.validationStatus") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.validationStatus" 'element))
(register-element! "VerificationResult.primarySource.validationDate" (fhir-spec (string->symbol "VerificationResult.primarySource.validationDate") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.validationDate" 'element))
(register-element! "VerificationResult.primarySource.canPushUpdates" (fhir-spec (string->symbol "VerificationResult.primarySource.canPushUpdates") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.canPushUpdates" 'element))
(register-element! "VerificationResult.primarySource.pushTypeAvailable" (fhir-spec (string->symbol "VerificationResult.primarySource.pushTypeAvailable") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.primarySource.pushTypeAvailable" 'element))

(register-type! 'VerificationResultAttestation (fhir-spec 'VerificationResultAttestation "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation" 'type)
  #:schema (type-schema 'VerificationResultAttestation #f 'BackboneElement "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation"
             (list
    (schema-field 'who 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.who" #f)
    (schema-field 'onBehalfOf 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.onBehalfOf" #f)
    (schema-field 'communicationMethod 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.communicationMethod" #f)
    (schema-field 'date 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.date" #f)
    (schema-field 'sourceIdentityCertificate 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.sourceIdentityCertificate" #f)
    (schema-field 'proxyIdentityCertificate 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.proxyIdentityCertificate" #f)
    (schema-field 'proxySignature 0 1 (vector 'type 'Signature) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.proxySignature" #f)
    (schema-field 'sourceSignature 0 1 (vector 'type 'Signature) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.sourceSignature" #f)
             ) #f #f))
(register-element! "VerificationResult.attestation.who" (fhir-spec (string->symbol "VerificationResult.attestation.who") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.who" 'element))
(register-element! "VerificationResult.attestation.onBehalfOf" (fhir-spec (string->symbol "VerificationResult.attestation.onBehalfOf") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.onBehalfOf" 'element))
(register-element! "VerificationResult.attestation.communicationMethod" (fhir-spec (string->symbol "VerificationResult.attestation.communicationMethod") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.communicationMethod" 'element))
(register-element! "VerificationResult.attestation.date" (fhir-spec (string->symbol "VerificationResult.attestation.date") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.date" 'element))
(register-element! "VerificationResult.attestation.sourceIdentityCertificate" (fhir-spec (string->symbol "VerificationResult.attestation.sourceIdentityCertificate") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.sourceIdentityCertificate" 'element))
(register-element! "VerificationResult.attestation.proxyIdentityCertificate" (fhir-spec (string->symbol "VerificationResult.attestation.proxyIdentityCertificate") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.proxyIdentityCertificate" 'element))
(register-element! "VerificationResult.attestation.proxySignature" (fhir-spec (string->symbol "VerificationResult.attestation.proxySignature") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.proxySignature" 'element))
(register-element! "VerificationResult.attestation.sourceSignature" (fhir-spec (string->symbol "VerificationResult.attestation.sourceSignature") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.attestation.sourceSignature" 'element))

(register-type! 'VerificationResultValidator (fhir-spec 'VerificationResultValidator "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator" 'type)
  #:schema (type-schema 'VerificationResultValidator #f 'BackboneElement "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator"
             (list
    (schema-field 'organization 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator.organization" #f)
    (schema-field 'identityCertificate 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator.identityCertificate" #f)
    (schema-field 'attestationSignature 0 1 (vector 'type 'Signature) #f "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator.attestationSignature" #f)
             ) #f #f))
(register-element! "VerificationResult.validator.organization" (fhir-spec (string->symbol "VerificationResult.validator.organization") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator.organization" 'element))
(register-element! "VerificationResult.validator.identityCertificate" (fhir-spec (string->symbol "VerificationResult.validator.identityCertificate") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator.identityCertificate" 'element))
(register-element! "VerificationResult.validator.attestationSignature" (fhir-spec (string->symbol "VerificationResult.validator.attestationSignature") "https://hl7.org/fhir/R4/verificationresult.html#VerificationResult.validator.attestationSignature" 'element))

