#lang racket/base
;;; GENERATED from hl7.fhir.uv.sql-on-fhir#3.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide ViewDefinition ViewDefinitionConstant ViewDefinitionSelect ViewDefinitionSelectColumn ViewDefinitionSelectColumnTag ViewDefinitionWhere)
(define-syntax (ViewDefinition stx)
  (build-fhir-form stx 'ViewDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec approvalDate 0 1 #(prim "date") #f)
      #s(field-spec lastReviewDate 0 1 #(prim "date") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(field-spec topic 0 * #(type CodeableConcept) #f)
      #s(field-spec author 0 * #(type ContactDetail) #f)
      #s(field-spec editor 0 * #(type ContactDetail) #f)
      #s(field-spec reviewer 0 * #(type ContactDetail) #f)
      #s(field-spec endorser 0 * #(type ContactDetail) #f)
      #s(field-spec relatedArtifact 0 * #(type RelatedArtifact) #f)
      #s(field-spec resource 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/resource-types"))
      #s(field-spec profile 0 * #(prim "canonical") #f)
      #s(field-spec fhirVersion 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/FHIR-version"))
      #s(field-spec constant 0 * #(type ViewDefinitionConstant) #f)
      #s(field-spec select 1 * #(type ViewDefinitionSelect) #f)
      #s(field-spec where 0 * #(type ViewDefinitionWhere) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      )
    #:parent 'DomainResource))
(define-syntax (ViewDefinitionConstant stx)
  (build-fhir-form stx 'ViewDefinitionConstant
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec valueBase64Binary 0 1 #(prim "base64Binary") #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec valueCode 0 1 #(prim "code") #f)
      #s(field-spec valueDate 0 1 #(prim "date") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec valueDecimal 0 1 #(prim "decimal") #f)
      #s(field-spec valueId 0 1 #(prim "id") #f)
      #s(field-spec valueInstant 0 1 #(prim "instant") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueInteger64 0 1 #(prim "integer64") #f)
      #s(field-spec valueOid 0 1 #(prim "oid") #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valuePositiveInt 0 1 #(prim "positiveInt") #f)
      #s(field-spec valueTime 0 1 #(prim "time") #f)
      #s(field-spec valueUnsignedInt 0 1 #(prim "unsignedInt") #f)
      #s(field-spec valueUri 0 1 #(prim "uri") #f)
      #s(field-spec valueUrl 0 1 #(prim "url") #f)
      #s(field-spec valueUuid 0 1 #(prim "uuid") #f)
      #s(choice-group 1 1 (valueBase64Binary valueBoolean valueCanonical valueCode valueDate valueDateTime valueDecimal valueId valueInstant valueInteger valueInteger64 valueOid valueString valuePositiveInt valueTime valueUnsignedInt valueUri valueUrl valueUuid))
      )
    #:parent 'BackboneElement))
(define-syntax (ViewDefinitionSelect stx)
  (build-fhir-form stx 'ViewDefinitionSelect
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec column 0 * #(type ViewDefinitionSelectColumn) #f)
      #s(field-spec select 0 * #(type ViewDefinitionSelect) #f)
      #s(field-spec forEach 0 1 #(prim "string") #f)
      #s(field-spec forEachOrNull 0 1 #(prim "string") #f)
      #s(field-spec repeat 0 * #(prim "string") #f)
      #s(field-spec unionAll 0 * #(type ViewDefinitionSelect) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ViewDefinitionSelectColumn stx)
  (build-fhir-form stx 'ViewDefinitionSelectColumn
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 1 1 #(prim "string") #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec collection 0 1 #(prim "boolean") #f)
      #s(field-spec type 0 1 #(prim "uri") #f)
      #s(field-spec tag 0 * #(type ViewDefinitionSelectColumnTag) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ViewDefinitionSelectColumnTag stx)
  (build-fhir-form stx 'ViewDefinitionSelectColumnTag
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec value 1 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ViewDefinitionWhere stx)
  (build-fhir-form stx 'ViewDefinitionWhere
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 1 1 #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
