#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide DataRequirement DataRequirementCodeFilter DataRequirementDateFilter DataRequirementValueFilter DataRequirementSort)
(define-syntax (DataRequirement stx)
  (build-fhir-form stx 'DataRequirement
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/fhir-types"))
      #s(field-spec profile 0 * #(prim "canonical") #f)
      #s(field-spec mustSupport 0 * #(prim "string") #f)
      #s(field-spec codeFilter 0 * #(type DataRequirementCodeFilter) #f)
      #s(field-spec dateFilter 0 * #(type DataRequirementDateFilter) #f)
      #s(field-spec valueFilter 0 * #(type DataRequirementValueFilter) #f)
      #s(field-spec limit 0 1 #(prim "positiveInt") #f)
      #s(field-spec sort 0 * #(type DataRequirementSort) #f)
      #s(field-spec subjectCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec subjectReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (subjectCodeableConcept subjectReference))
      )
    #:parent 'DataType))
(define-syntax (DataRequirementCodeFilter stx)
  (build-fhir-form stx 'DataRequirementCodeFilter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 0 1 #(prim "string") #f)
      #s(field-spec searchParam 0 1 #(prim "string") #f)
      #s(field-spec valueSet 0 1 #(prim "canonical") #f)
      #s(field-spec code 0 * #(type Coding) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (DataRequirementDateFilter stx)
  (build-fhir-form stx 'DataRequirementDateFilter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 0 1 #(prim "string") #f)
      #s(field-spec searchParam 0 1 #(prim "string") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec valuePeriod 0 1 #(type Period) #f)
      #s(field-spec valueDuration 0 1 #(type Duration) #f)
      #s(choice-group 0 1 (valueDateTime valuePeriod valueDuration))
      )
    #:parent 'BackboneElement))
(define-syntax (DataRequirementValueFilter stx)
  (build-fhir-form stx 'DataRequirementValueFilter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 0 1 #(prim "string") #f)
      #s(field-spec searchParam 0 1 #(prim "string") #f)
      #s(field-spec comparator 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/value-filter-comparator"))
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec valuePeriod 0 1 #(type Period) #f)
      #s(field-spec valueDuration 0 1 #(type Duration) #f)
      #s(choice-group 0 1 (valueDateTime valuePeriod valueDuration))
      )
    #:parent 'BackboneElement))
(define-syntax (DataRequirementSort stx)
  (build-fhir-form stx 'DataRequirementSort
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 1 1 #(prim "string") #f)
      #s(field-spec direction 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/sort-direction"))
      )
    #:parent 'BackboneElement))
