#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Dosage DosageDoseAndRate)
(define-syntax (Dosage stx)
  (build-fhir-form stx 'Dosage
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec condition 0 * #(type DosageCondition) #f)
      #s(field-spec text 0 1 #(prim "string") #f)
      #s(field-spec additionalInstruction 0 * #(type CodeableConcept) #f)
      #s(field-spec patientInstruction 0 1 #(prim "string") #f)
      #s(field-spec timing 0 1 #(type Timing) #f)
      #s(field-spec asNeeded 0 1 #(prim "boolean") #f)
      #s(field-spec asNeededFor 0 * #(type CodeableConcept) #f)
      #s(field-spec site 0 1 #(type CodeableReference) #f)
      #s(field-spec route 0 1 #(type CodeableConcept) #f)
      #s(field-spec method 0 1 #(type CodeableConcept) #f)
      #s(field-spec doseAndRate 0 * #(type DosageDoseAndRate) #f)
      #s(field-spec safety 0 1 #(type DosageSafety) #f)
      )
    #:parent 'BackboneType))
(define-syntax (DosageDoseAndRate stx)
  (build-fhir-form stx 'DosageDoseAndRate
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec doseRange 0 1 #(type Range) #f)
      #s(field-spec doseQuantity 0 1 #(type Quantity) #f)
      #s(field-spec doseExpression 0 1 #(type Expression) #f)
      #s(field-spec rateRatio 0 1 #(type Ratio) #f)
      #s(field-spec rateRange 0 1 #(type Range) #f)
      #s(field-spec rateQuantity 0 1 #(type Quantity) #f)
      #s(field-spec rateExpression 0 1 #(type Expression) #f)
      #s(choice-group 0 1 (doseRange doseQuantity doseExpression))
      #s(choice-group 0 1 (rateRatio rateRange rateQuantity rateExpression))
      )
    #:parent 'BackboneElement))
