#lang racket/base
;;; GENERATED from hl7.fhir.uv.sql-on-fhir#3.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ViewDefinition (fhir-spec 'ViewDefinition "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition" 'type)
  #:schema (type-schema 'ViewDefinition #f 'DomainResource "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.effectivePeriod" #f)
    (schema-field 'topic 0 '* (vector 'type 'CodeableConcept) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.topic" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.endorser" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.relatedArtifact" #f)
    (schema-field 'resource 1 1 (vector 'prim "code") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.resource" #f)
    (schema-field 'profile 0 '* (vector 'prim "canonical") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.profile" #f)
    (schema-field 'fhirVersion 0 '* (vector 'prim "code") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.fhirVersion" #f)
    (schema-field 'constant 0 '* (vector 'type 'ViewDefinitionConstant) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant" #f)
    (schema-field 'select 1 '* (vector 'type 'ViewDefinitionSelect) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select" #f)
    (schema-field 'where 0 '* (vector 'type 'ViewDefinitionWhere) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "ViewDefinition.url" (fhir-spec (string->symbol "ViewDefinition.url") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.url" 'element))
(register-element! "ViewDefinition.identifier" (fhir-spec (string->symbol "ViewDefinition.identifier") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.identifier" 'element))
(register-element! "ViewDefinition.version" (fhir-spec (string->symbol "ViewDefinition.version") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.version" 'element))
(register-element! "ViewDefinition.name" (fhir-spec (string->symbol "ViewDefinition.name") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.name" 'element))
(register-element! "ViewDefinition.title" (fhir-spec (string->symbol "ViewDefinition.title") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.title" 'element))
(register-element! "ViewDefinition.status" (fhir-spec (string->symbol "ViewDefinition.status") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.status" 'element))
(register-element! "ViewDefinition.experimental" (fhir-spec (string->symbol "ViewDefinition.experimental") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.experimental" 'element))
(register-element! "ViewDefinition.date" (fhir-spec (string->symbol "ViewDefinition.date") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.date" 'element))
(register-element! "ViewDefinition.publisher" (fhir-spec (string->symbol "ViewDefinition.publisher") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.publisher" 'element))
(register-element! "ViewDefinition.contact" (fhir-spec (string->symbol "ViewDefinition.contact") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.contact" 'element))
(register-element! "ViewDefinition.description" (fhir-spec (string->symbol "ViewDefinition.description") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.description" 'element))
(register-element! "ViewDefinition.useContext" (fhir-spec (string->symbol "ViewDefinition.useContext") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.useContext" 'element))
(register-element! "ViewDefinition.jurisdiction" (fhir-spec (string->symbol "ViewDefinition.jurisdiction") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.jurisdiction" 'element))
(register-element! "ViewDefinition.purpose" (fhir-spec (string->symbol "ViewDefinition.purpose") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.purpose" 'element))
(register-element! "ViewDefinition.copyright" (fhir-spec (string->symbol "ViewDefinition.copyright") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.copyright" 'element))
(register-element! "ViewDefinition.copyrightLabel" (fhir-spec (string->symbol "ViewDefinition.copyrightLabel") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.copyrightLabel" 'element))
(register-element! "ViewDefinition.approvalDate" (fhir-spec (string->symbol "ViewDefinition.approvalDate") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.approvalDate" 'element))
(register-element! "ViewDefinition.lastReviewDate" (fhir-spec (string->symbol "ViewDefinition.lastReviewDate") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.lastReviewDate" 'element))
(register-element! "ViewDefinition.effectivePeriod" (fhir-spec (string->symbol "ViewDefinition.effectivePeriod") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.effectivePeriod" 'element))
(register-element! "ViewDefinition.topic" (fhir-spec (string->symbol "ViewDefinition.topic") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.topic" 'element))
(register-element! "ViewDefinition.author" (fhir-spec (string->symbol "ViewDefinition.author") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.author" 'element))
(register-element! "ViewDefinition.editor" (fhir-spec (string->symbol "ViewDefinition.editor") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.editor" 'element))
(register-element! "ViewDefinition.reviewer" (fhir-spec (string->symbol "ViewDefinition.reviewer") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.reviewer" 'element))
(register-element! "ViewDefinition.endorser" (fhir-spec (string->symbol "ViewDefinition.endorser") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.endorser" 'element))
(register-element! "ViewDefinition.relatedArtifact" (fhir-spec (string->symbol "ViewDefinition.relatedArtifact") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.relatedArtifact" 'element))
(register-element! "ViewDefinition.resource" (fhir-spec (string->symbol "ViewDefinition.resource") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.resource" 'element))
(register-element! "ViewDefinition.profile" (fhir-spec (string->symbol "ViewDefinition.profile") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.profile" 'element))
(register-element! "ViewDefinition.fhirVersion" (fhir-spec (string->symbol "ViewDefinition.fhirVersion") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.fhirVersion" 'element))
(register-element! "ViewDefinition.constant" (fhir-spec (string->symbol "ViewDefinition.constant") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant" 'element))
(register-element! "ViewDefinition.select" (fhir-spec (string->symbol "ViewDefinition.select") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select" 'element))
(register-element! "ViewDefinition.where" (fhir-spec (string->symbol "ViewDefinition.where") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where" 'element))
(register-element! "ViewDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "ViewDefinition.versionAlgorithm[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.versionAlgorithm[x]" 'element))
(register-element! "ViewDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "ViewDefinition.versionAlgorithm[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.versionAlgorithm[x]" 'element))

(register-type! 'ViewDefinitionConstant (fhir-spec 'ViewDefinitionConstant "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant" 'type)
  #:schema (type-schema 'ViewDefinitionConstant #f 'BackboneElement "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant"
             (list
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.name" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueInteger64 0 1 (vector 'prim "integer64") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" #f)
             ) #f #f))
(register-element! "ViewDefinition.constant.name" (fhir-spec (string->symbol "ViewDefinition.constant.name") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.name" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))
(register-element! "ViewDefinition.constant.value[x]" (fhir-spec (string->symbol "ViewDefinition.constant.value[x]") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.constant.value[x]" 'element))

(register-type! 'ViewDefinitionSelect (fhir-spec 'ViewDefinitionSelect "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select" 'type)
  #:schema (type-schema 'ViewDefinitionSelect #f 'BackboneElement "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select"
             (list
    (schema-field 'column 0 '* (vector 'type 'ViewDefinitionSelectColumn) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column" #f)
    (schema-field 'select 0 '* (vector 'type 'ViewDefinitionSelect) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.select" #f)
    (schema-field 'forEach 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.forEach" #f)
    (schema-field 'forEachOrNull 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.forEachOrNull" #f)
    (schema-field 'repeat 0 '* (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.repeat" #f)
    (schema-field 'unionAll 0 '* (vector 'type 'ViewDefinitionSelect) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.unionAll" #f)
             ) #f #f))
(register-element! "ViewDefinition.select.column" (fhir-spec (string->symbol "ViewDefinition.select.column") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column" 'element))
(register-element! "ViewDefinition.select.select" (fhir-spec (string->symbol "ViewDefinition.select.select") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.select" 'element))
(register-element! "ViewDefinition.select.forEach" (fhir-spec (string->symbol "ViewDefinition.select.forEach") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.forEach" 'element))
(register-element! "ViewDefinition.select.forEachOrNull" (fhir-spec (string->symbol "ViewDefinition.select.forEachOrNull") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.forEachOrNull" 'element))
(register-element! "ViewDefinition.select.repeat" (fhir-spec (string->symbol "ViewDefinition.select.repeat") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.repeat" 'element))
(register-element! "ViewDefinition.select.unionAll" (fhir-spec (string->symbol "ViewDefinition.select.unionAll") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.unionAll" 'element))

(register-type! 'ViewDefinitionSelectColumn (fhir-spec 'ViewDefinitionSelectColumn "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column" 'type)
  #:schema (type-schema 'ViewDefinitionSelectColumn #f 'BackboneElement "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column"
             (list
    (schema-field 'path 1 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.path" #f)
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.name" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.description" #f)
    (schema-field 'collection 0 1 (vector 'prim "boolean") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.collection" #f)
    (schema-field 'type 0 1 (vector 'prim "uri") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.type" #f)
    (schema-field 'tag 0 '* (vector 'type 'ViewDefinitionSelectColumnTag) #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag" #f)
             ) #f #f))
(register-element! "ViewDefinition.select.column.path" (fhir-spec (string->symbol "ViewDefinition.select.column.path") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.path" 'element))
(register-element! "ViewDefinition.select.column.name" (fhir-spec (string->symbol "ViewDefinition.select.column.name") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.name" 'element))
(register-element! "ViewDefinition.select.column.description" (fhir-spec (string->symbol "ViewDefinition.select.column.description") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.description" 'element))
(register-element! "ViewDefinition.select.column.collection" (fhir-spec (string->symbol "ViewDefinition.select.column.collection") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.collection" 'element))
(register-element! "ViewDefinition.select.column.type" (fhir-spec (string->symbol "ViewDefinition.select.column.type") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.type" 'element))
(register-element! "ViewDefinition.select.column.tag" (fhir-spec (string->symbol "ViewDefinition.select.column.tag") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag" 'element))

(register-type! 'ViewDefinitionSelectColumnTag (fhir-spec 'ViewDefinitionSelectColumnTag "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag" 'type)
  #:schema (type-schema 'ViewDefinitionSelectColumnTag #f 'BackboneElement "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag"
             (list
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag.name" #f)
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag.value" #f)
             ) #f #f))
(register-element! "ViewDefinition.select.column.tag.name" (fhir-spec (string->symbol "ViewDefinition.select.column.tag.name") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag.name" 'element))
(register-element! "ViewDefinition.select.column.tag.value" (fhir-spec (string->symbol "ViewDefinition.select.column.tag.value") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.select.column.tag.value" 'element))

(register-type! 'ViewDefinitionWhere (fhir-spec 'ViewDefinitionWhere "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where" 'type)
  #:schema (type-schema 'ViewDefinitionWhere #f 'BackboneElement "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where"
             (list
    (schema-field 'path 1 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where.path" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where.description" #f)
             ) #f #f))
(register-element! "ViewDefinition.where.path" (fhir-spec (string->symbol "ViewDefinition.where.path") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where.path" 'element))
(register-element! "ViewDefinition.where.description" (fhir-spec (string->symbol "ViewDefinition.where.description") "https://sql-on-fhir.org/ig/viewdefinition.html#ViewDefinition.where.description" 'element))

