#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ActorDefinition (fhir-spec 'ActorDefinition "https://build.fhir.org/actordefinition.html#ActorDefinition" 'type)
  #:schema (type-schema 'ActorDefinition #f 'DomainResource "https://build.fhir.org/actordefinition.html#ActorDefinition"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/actordefinition.html#ActorDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/actordefinition.html#ActorDefinition.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/actordefinition.html#ActorDefinition.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/actordefinition.html#ActorDefinition.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.copyrightLabel" #f)
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.type" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/actordefinition.html#ActorDefinition.category" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.documentation" #f)
    (schema-field 'reference 0 '* (vector 'prim "url") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.reference" #f)
    (schema-field 'baseDefinition 0 '* (vector 'prim "canonical") #f "https://build.fhir.org/actordefinition.html#ActorDefinition.baseDefinition" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/actordefinition.html#ActorDefinition.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/actordefinition.html#ActorDefinition.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "ActorDefinition.url" (fhir-spec (string->symbol "ActorDefinition.url") "https://build.fhir.org/actordefinition.html#ActorDefinition.url" 'element))
(register-element! "ActorDefinition.identifier" (fhir-spec (string->symbol "ActorDefinition.identifier") "https://build.fhir.org/actordefinition.html#ActorDefinition.identifier" 'element))
(register-element! "ActorDefinition.version" (fhir-spec (string->symbol "ActorDefinition.version") "https://build.fhir.org/actordefinition.html#ActorDefinition.version" 'element))
(register-element! "ActorDefinition.name" (fhir-spec (string->symbol "ActorDefinition.name") "https://build.fhir.org/actordefinition.html#ActorDefinition.name" 'element))
(register-element! "ActorDefinition.title" (fhir-spec (string->symbol "ActorDefinition.title") "https://build.fhir.org/actordefinition.html#ActorDefinition.title" 'element))
(register-element! "ActorDefinition.status" (fhir-spec (string->symbol "ActorDefinition.status") "https://build.fhir.org/actordefinition.html#ActorDefinition.status" 'element))
(register-element! "ActorDefinition.experimental" (fhir-spec (string->symbol "ActorDefinition.experimental") "https://build.fhir.org/actordefinition.html#ActorDefinition.experimental" 'element))
(register-element! "ActorDefinition.date" (fhir-spec (string->symbol "ActorDefinition.date") "https://build.fhir.org/actordefinition.html#ActorDefinition.date" 'element))
(register-element! "ActorDefinition.publisher" (fhir-spec (string->symbol "ActorDefinition.publisher") "https://build.fhir.org/actordefinition.html#ActorDefinition.publisher" 'element))
(register-element! "ActorDefinition.contact" (fhir-spec (string->symbol "ActorDefinition.contact") "https://build.fhir.org/actordefinition.html#ActorDefinition.contact" 'element))
(register-element! "ActorDefinition.description" (fhir-spec (string->symbol "ActorDefinition.description") "https://build.fhir.org/actordefinition.html#ActorDefinition.description" 'element))
(register-element! "ActorDefinition.useContext" (fhir-spec (string->symbol "ActorDefinition.useContext") "https://build.fhir.org/actordefinition.html#ActorDefinition.useContext" 'element))
(register-element! "ActorDefinition.jurisdiction" (fhir-spec (string->symbol "ActorDefinition.jurisdiction") "https://build.fhir.org/actordefinition.html#ActorDefinition.jurisdiction" 'element))
(register-element! "ActorDefinition.purpose" (fhir-spec (string->symbol "ActorDefinition.purpose") "https://build.fhir.org/actordefinition.html#ActorDefinition.purpose" 'element))
(register-element! "ActorDefinition.copyright" (fhir-spec (string->symbol "ActorDefinition.copyright") "https://build.fhir.org/actordefinition.html#ActorDefinition.copyright" 'element))
(register-element! "ActorDefinition.copyrightLabel" (fhir-spec (string->symbol "ActorDefinition.copyrightLabel") "https://build.fhir.org/actordefinition.html#ActorDefinition.copyrightLabel" 'element))
(register-element! "ActorDefinition.type" (fhir-spec (string->symbol "ActorDefinition.type") "https://build.fhir.org/actordefinition.html#ActorDefinition.type" 'element))
(register-element! "ActorDefinition.category" (fhir-spec (string->symbol "ActorDefinition.category") "https://build.fhir.org/actordefinition.html#ActorDefinition.category" 'element))
(register-element! "ActorDefinition.documentation" (fhir-spec (string->symbol "ActorDefinition.documentation") "https://build.fhir.org/actordefinition.html#ActorDefinition.documentation" 'element))
(register-element! "ActorDefinition.reference" (fhir-spec (string->symbol "ActorDefinition.reference") "https://build.fhir.org/actordefinition.html#ActorDefinition.reference" 'element))
(register-element! "ActorDefinition.baseDefinition" (fhir-spec (string->symbol "ActorDefinition.baseDefinition") "https://build.fhir.org/actordefinition.html#ActorDefinition.baseDefinition" 'element))
(register-element! "ActorDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "ActorDefinition.versionAlgorithm[x]") "https://build.fhir.org/actordefinition.html#ActorDefinition.versionAlgorithm[x]" 'element))
(register-element! "ActorDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "ActorDefinition.versionAlgorithm[x]") "https://build.fhir.org/actordefinition.html#ActorDefinition.versionAlgorithm[x]" 'element))

