#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'AdverseEvent (fhir-spec 'AdverseEvent "https://build.fhir.org/adverseevent.html#AdverseEvent" 'type)
  #:schema (type-schema 'AdverseEvent #f 'DomainResource "https://build.fhir.org/adverseevent.html#AdverseEvent"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/adverseevent.html#AdverseEvent.status" #f)
    (schema-field 'actuality 1 1 (vector 'prim "code") #f "https://build.fhir.org/adverseevent.html#AdverseEvent.actuality" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.category" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.code" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.encounter" #f)
    (schema-field 'detected 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/adverseevent.html#AdverseEvent.detected" #f)
    (schema-field 'recordedDate 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/adverseevent.html#AdverseEvent.recordedDate" #f)
    (schema-field 'resultingEffect 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.resultingEffect" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.location" #f)
    (schema-field 'seriousness 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.seriousness" #f)
    (schema-field 'outcome 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.outcome" #f)
    (schema-field 'recorder 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.recorder" #f)
    (schema-field 'participant 0 '* (vector 'type 'AdverseEventParticipant) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.participant" #f)
    (schema-field 'study 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.study" #f)
    (schema-field 'expectedInResearchStudy 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/adverseevent.html#AdverseEvent.expectedInResearchStudy" #f)
    (schema-field 'suspectEntity 0 '* (vector 'type 'AdverseEventSuspectEntity) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity" #f)
    (schema-field 'contributingFactor 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.contributingFactor" #f)
    (schema-field 'preventiveAction 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.preventiveAction" #f)
    (schema-field 'mitigatingAction 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.mitigatingAction" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.supportingInfo" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.note" #f)
    (schema-field 'effectDateTime 0 1 (vector 'prim "dateTime") 'effect "https://build.fhir.org/adverseevent.html#AdverseEvent.effect[x]" #f)
    (schema-field 'effectPeriod 0 1 (vector 'type 'Period) 'effect "https://build.fhir.org/adverseevent.html#AdverseEvent.effect[x]" #f)
             ) #f #f))
(register-element! "AdverseEvent.identifier" (fhir-spec (string->symbol "AdverseEvent.identifier") "https://build.fhir.org/adverseevent.html#AdverseEvent.identifier" 'element))
(register-element! "AdverseEvent.status" (fhir-spec (string->symbol "AdverseEvent.status") "https://build.fhir.org/adverseevent.html#AdverseEvent.status" 'element))
(register-element! "AdverseEvent.actuality" (fhir-spec (string->symbol "AdverseEvent.actuality") "https://build.fhir.org/adverseevent.html#AdverseEvent.actuality" 'element))
(register-element! "AdverseEvent.category" (fhir-spec (string->symbol "AdverseEvent.category") "https://build.fhir.org/adverseevent.html#AdverseEvent.category" 'element))
(register-element! "AdverseEvent.code" (fhir-spec (string->symbol "AdverseEvent.code") "https://build.fhir.org/adverseevent.html#AdverseEvent.code" 'element))
(register-element! "AdverseEvent.subject" (fhir-spec (string->symbol "AdverseEvent.subject") "https://build.fhir.org/adverseevent.html#AdverseEvent.subject" 'element))
(register-element! "AdverseEvent.encounter" (fhir-spec (string->symbol "AdverseEvent.encounter") "https://build.fhir.org/adverseevent.html#AdverseEvent.encounter" 'element))
(register-element! "AdverseEvent.detected" (fhir-spec (string->symbol "AdverseEvent.detected") "https://build.fhir.org/adverseevent.html#AdverseEvent.detected" 'element))
(register-element! "AdverseEvent.recordedDate" (fhir-spec (string->symbol "AdverseEvent.recordedDate") "https://build.fhir.org/adverseevent.html#AdverseEvent.recordedDate" 'element))
(register-element! "AdverseEvent.resultingEffect" (fhir-spec (string->symbol "AdverseEvent.resultingEffect") "https://build.fhir.org/adverseevent.html#AdverseEvent.resultingEffect" 'element))
(register-element! "AdverseEvent.location" (fhir-spec (string->symbol "AdverseEvent.location") "https://build.fhir.org/adverseevent.html#AdverseEvent.location" 'element))
(register-element! "AdverseEvent.seriousness" (fhir-spec (string->symbol "AdverseEvent.seriousness") "https://build.fhir.org/adverseevent.html#AdverseEvent.seriousness" 'element))
(register-element! "AdverseEvent.outcome" (fhir-spec (string->symbol "AdverseEvent.outcome") "https://build.fhir.org/adverseevent.html#AdverseEvent.outcome" 'element))
(register-element! "AdverseEvent.recorder" (fhir-spec (string->symbol "AdverseEvent.recorder") "https://build.fhir.org/adverseevent.html#AdverseEvent.recorder" 'element))
(register-element! "AdverseEvent.participant" (fhir-spec (string->symbol "AdverseEvent.participant") "https://build.fhir.org/adverseevent.html#AdverseEvent.participant" 'element))
(register-element! "AdverseEvent.study" (fhir-spec (string->symbol "AdverseEvent.study") "https://build.fhir.org/adverseevent.html#AdverseEvent.study" 'element))
(register-element! "AdverseEvent.expectedInResearchStudy" (fhir-spec (string->symbol "AdverseEvent.expectedInResearchStudy") "https://build.fhir.org/adverseevent.html#AdverseEvent.expectedInResearchStudy" 'element))
(register-element! "AdverseEvent.suspectEntity" (fhir-spec (string->symbol "AdverseEvent.suspectEntity") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity" 'element))
(register-element! "AdverseEvent.contributingFactor" (fhir-spec (string->symbol "AdverseEvent.contributingFactor") "https://build.fhir.org/adverseevent.html#AdverseEvent.contributingFactor" 'element))
(register-element! "AdverseEvent.preventiveAction" (fhir-spec (string->symbol "AdverseEvent.preventiveAction") "https://build.fhir.org/adverseevent.html#AdverseEvent.preventiveAction" 'element))
(register-element! "AdverseEvent.mitigatingAction" (fhir-spec (string->symbol "AdverseEvent.mitigatingAction") "https://build.fhir.org/adverseevent.html#AdverseEvent.mitigatingAction" 'element))
(register-element! "AdverseEvent.supportingInfo" (fhir-spec (string->symbol "AdverseEvent.supportingInfo") "https://build.fhir.org/adverseevent.html#AdverseEvent.supportingInfo" 'element))
(register-element! "AdverseEvent.note" (fhir-spec (string->symbol "AdverseEvent.note") "https://build.fhir.org/adverseevent.html#AdverseEvent.note" 'element))
(register-element! "AdverseEvent.effect[x]" (fhir-spec (string->symbol "AdverseEvent.effect[x]") "https://build.fhir.org/adverseevent.html#AdverseEvent.effect[x]" 'element))
(register-element! "AdverseEvent.effect[x]" (fhir-spec (string->symbol "AdverseEvent.effect[x]") "https://build.fhir.org/adverseevent.html#AdverseEvent.effect[x]" 'element))

(register-type! 'AdverseEventParticipant (fhir-spec 'AdverseEventParticipant "https://build.fhir.org/adverseevent.html#AdverseEvent.participant" 'type)
  #:schema (type-schema 'AdverseEventParticipant #f 'BackboneElement "https://build.fhir.org/adverseevent.html#AdverseEvent.participant"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.participant.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.participant.actor" #f)
             ) #f #f))
(register-element! "AdverseEvent.participant.function" (fhir-spec (string->symbol "AdverseEvent.participant.function") "https://build.fhir.org/adverseevent.html#AdverseEvent.participant.function" 'element))
(register-element! "AdverseEvent.participant.actor" (fhir-spec (string->symbol "AdverseEvent.participant.actor") "https://build.fhir.org/adverseevent.html#AdverseEvent.participant.actor" 'element))

(register-type! 'AdverseEventSuspectEntity (fhir-spec 'AdverseEventSuspectEntity "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity" 'type)
  #:schema (type-schema 'AdverseEventSuspectEntity #f 'BackboneElement "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity"
             (list
    (schema-field 'instance 1 1 (vector 'type 'CodeableReference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.instance" #f)
    (schema-field 'causality 0 1 (vector 'type 'AdverseEventSuspectEntityCausality) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.occurrence[x]" #f)
             ) #f #f))
(register-element! "AdverseEvent.suspectEntity.instance" (fhir-spec (string->symbol "AdverseEvent.suspectEntity.instance") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.instance" 'element))
(register-element! "AdverseEvent.suspectEntity.causality" (fhir-spec (string->symbol "AdverseEvent.suspectEntity.causality") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality" 'element))
(register-element! "AdverseEvent.suspectEntity.occurrence[x]" (fhir-spec (string->symbol "AdverseEvent.suspectEntity.occurrence[x]") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.occurrence[x]" 'element))
(register-element! "AdverseEvent.suspectEntity.occurrence[x]" (fhir-spec (string->symbol "AdverseEvent.suspectEntity.occurrence[x]") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.occurrence[x]" 'element))

(register-type! 'AdverseEventSuspectEntityCausality (fhir-spec 'AdverseEventSuspectEntityCausality "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality" 'type)
  #:schema (type-schema 'AdverseEventSuspectEntityCausality #f 'BackboneElement "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality"
             (list
    (schema-field 'assessmentMethod 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality.assessmentMethod" #f)
    (schema-field 'entityRelatedness 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality.entityRelatedness" #f)
    (schema-field 'author 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality.author" #f)
             ) #f #f))
(register-element! "AdverseEvent.suspectEntity.causality.assessmentMethod" (fhir-spec (string->symbol "AdverseEvent.suspectEntity.causality.assessmentMethod") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality.assessmentMethod" 'element))
(register-element! "AdverseEvent.suspectEntity.causality.entityRelatedness" (fhir-spec (string->symbol "AdverseEvent.suspectEntity.causality.entityRelatedness") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality.entityRelatedness" 'element))
(register-element! "AdverseEvent.suspectEntity.causality.author" (fhir-spec (string->symbol "AdverseEvent.suspectEntity.causality.author") "https://build.fhir.org/adverseevent.html#AdverseEvent.suspectEntity.causality.author" 'element))

