#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'CarePlan (fhir-spec 'CarePlan "https://build.fhir.org/careplan.html#CarePlan" 'type)
  #:schema (type-schema 'CarePlan #f 'DomainResource "https://build.fhir.org/careplan.html#CarePlan"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/careplan.html#CarePlan.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.basedOn" #f)
    (schema-field 'replaces 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.replaces" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/careplan.html#CarePlan.status" #f)
    (schema-field 'intent 1 1 (vector 'prim "code") #f "https://build.fhir.org/careplan.html#CarePlan.intent" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/careplan.html#CarePlan.category" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/careplan.html#CarePlan.title" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://build.fhir.org/careplan.html#CarePlan.description" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.encounter" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/careplan.html#CarePlan.period" #f)
    (schema-field 'created 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/careplan.html#CarePlan.created" #f)
    (schema-field 'custodian 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.custodian" #f)
    (schema-field 'contributor 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.contributor" #f)
    (schema-field 'careTeam 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.careTeam" #f)
    (schema-field 'addresses 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/careplan.html#CarePlan.addresses" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.supportingInfo" #f)
    (schema-field 'goal 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.goal" #f)
    (schema-field 'activity 0 '* (vector 'type 'CarePlanActivity) #f "https://build.fhir.org/careplan.html#CarePlan.activity" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/careplan.html#CarePlan.note" #f)
             ) #f #f))
(register-element! "CarePlan.identifier" (fhir-spec (string->symbol "CarePlan.identifier") "https://build.fhir.org/careplan.html#CarePlan.identifier" 'element))
(register-element! "CarePlan.basedOn" (fhir-spec (string->symbol "CarePlan.basedOn") "https://build.fhir.org/careplan.html#CarePlan.basedOn" 'element))
(register-element! "CarePlan.replaces" (fhir-spec (string->symbol "CarePlan.replaces") "https://build.fhir.org/careplan.html#CarePlan.replaces" 'element))
(register-element! "CarePlan.partOf" (fhir-spec (string->symbol "CarePlan.partOf") "https://build.fhir.org/careplan.html#CarePlan.partOf" 'element))
(register-element! "CarePlan.status" (fhir-spec (string->symbol "CarePlan.status") "https://build.fhir.org/careplan.html#CarePlan.status" 'element))
(register-element! "CarePlan.intent" (fhir-spec (string->symbol "CarePlan.intent") "https://build.fhir.org/careplan.html#CarePlan.intent" 'element))
(register-element! "CarePlan.category" (fhir-spec (string->symbol "CarePlan.category") "https://build.fhir.org/careplan.html#CarePlan.category" 'element))
(register-element! "CarePlan.title" (fhir-spec (string->symbol "CarePlan.title") "https://build.fhir.org/careplan.html#CarePlan.title" 'element))
(register-element! "CarePlan.description" (fhir-spec (string->symbol "CarePlan.description") "https://build.fhir.org/careplan.html#CarePlan.description" 'element))
(register-element! "CarePlan.subject" (fhir-spec (string->symbol "CarePlan.subject") "https://build.fhir.org/careplan.html#CarePlan.subject" 'element))
(register-element! "CarePlan.encounter" (fhir-spec (string->symbol "CarePlan.encounter") "https://build.fhir.org/careplan.html#CarePlan.encounter" 'element))
(register-element! "CarePlan.period" (fhir-spec (string->symbol "CarePlan.period") "https://build.fhir.org/careplan.html#CarePlan.period" 'element))
(register-element! "CarePlan.created" (fhir-spec (string->symbol "CarePlan.created") "https://build.fhir.org/careplan.html#CarePlan.created" 'element))
(register-element! "CarePlan.custodian" (fhir-spec (string->symbol "CarePlan.custodian") "https://build.fhir.org/careplan.html#CarePlan.custodian" 'element))
(register-element! "CarePlan.contributor" (fhir-spec (string->symbol "CarePlan.contributor") "https://build.fhir.org/careplan.html#CarePlan.contributor" 'element))
(register-element! "CarePlan.careTeam" (fhir-spec (string->symbol "CarePlan.careTeam") "https://build.fhir.org/careplan.html#CarePlan.careTeam" 'element))
(register-element! "CarePlan.addresses" (fhir-spec (string->symbol "CarePlan.addresses") "https://build.fhir.org/careplan.html#CarePlan.addresses" 'element))
(register-element! "CarePlan.supportingInfo" (fhir-spec (string->symbol "CarePlan.supportingInfo") "https://build.fhir.org/careplan.html#CarePlan.supportingInfo" 'element))
(register-element! "CarePlan.goal" (fhir-spec (string->symbol "CarePlan.goal") "https://build.fhir.org/careplan.html#CarePlan.goal" 'element))
(register-element! "CarePlan.activity" (fhir-spec (string->symbol "CarePlan.activity") "https://build.fhir.org/careplan.html#CarePlan.activity" 'element))
(register-element! "CarePlan.note" (fhir-spec (string->symbol "CarePlan.note") "https://build.fhir.org/careplan.html#CarePlan.note" 'element))

(register-type! 'CarePlanActivity (fhir-spec 'CarePlanActivity "https://build.fhir.org/careplan.html#CarePlan.activity" 'type)
  #:schema (type-schema 'CarePlanActivity #f 'BackboneElement "https://build.fhir.org/careplan.html#CarePlan.activity"
             (list
    (schema-field 'performedActivity 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/careplan.html#CarePlan.activity.performedActivity" #f)
    (schema-field 'progress 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/careplan.html#CarePlan.activity.progress" #f)
    (schema-field 'plannedActivityReference 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/careplan.html#CarePlan.activity.plannedActivityReference" #f)
             ) #f #f))
(register-element! "CarePlan.activity.performedActivity" (fhir-spec (string->symbol "CarePlan.activity.performedActivity") "https://build.fhir.org/careplan.html#CarePlan.activity.performedActivity" 'element))
(register-element! "CarePlan.activity.progress" (fhir-spec (string->symbol "CarePlan.activity.progress") "https://build.fhir.org/careplan.html#CarePlan.activity.progress" 'element))
(register-element! "CarePlan.activity.plannedActivityReference" (fhir-spec (string->symbol "CarePlan.activity.plannedActivityReference") "https://build.fhir.org/careplan.html#CarePlan.activity.plannedActivityReference" 'element))

