#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Claim (fhir-spec 'Claim "https://build.fhir.org/claim.html#Claim" 'type)
  #:schema (type-schema 'Claim #f 'DomainResource "https://build.fhir.org/claim.html#Claim"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/claim.html#Claim.identifier" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/claim.html#Claim.traceNumber" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/claim.html#Claim.status" #f)
    (schema-field 'statusReason 0 1 (vector 'prim "string") #f "https://build.fhir.org/claim.html#Claim.statusReason" #f)
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.type" #f)
    (schema-field 'subType 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.subType" #f)
    (schema-field 'use 1 1 (vector 'prim "code") #f "https://build.fhir.org/claim.html#Claim.use" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.subject" #f)
    (schema-field 'billablePeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/claim.html#Claim.billablePeriod" #f)
    (schema-field 'created 1 1 (vector 'prim "dateTime") #f "https://build.fhir.org/claim.html#Claim.created" #f)
    (schema-field 'enterer 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.enterer" #f)
    (schema-field 'insurer 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.insurer" #f)
    (schema-field 'provider 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.provider" #f)
    (schema-field 'priority 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.priority" #f)
    (schema-field 'fundsReserve 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.fundsReserve" #f)
    (schema-field 'related 0 '* (vector 'type 'ClaimRelated) #f "https://build.fhir.org/claim.html#Claim.related" #f)
    (schema-field 'prescription 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.prescription" #f)
    (schema-field 'originalPrescription 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.originalPrescription" #f)
    (schema-field 'payee 0 1 (vector 'type 'ClaimPayee) #f "https://build.fhir.org/claim.html#Claim.payee" #f)
    (schema-field 'referral 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.referral" #f)
    (schema-field 'encounter 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.encounter" #f)
    (schema-field 'facility 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.facility" #f)
    (schema-field 'diagnosisRelatedGroup 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.diagnosisRelatedGroup" #f)
    (schema-field 'event 0 '* (vector 'type 'ClaimEvent) #f "https://build.fhir.org/claim.html#Claim.event" #f)
    (schema-field 'careTeam 0 '* (vector 'type 'ClaimCareTeam) #f "https://build.fhir.org/claim.html#Claim.careTeam" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'ClaimSupportingInfo) #f "https://build.fhir.org/claim.html#Claim.supportingInfo" #f)
    (schema-field 'diagnosis 0 '* (vector 'type 'ClaimDiagnosis) #f "https://build.fhir.org/claim.html#Claim.diagnosis" #f)
    (schema-field 'procedure 0 '* (vector 'type 'ClaimProcedure) #f "https://build.fhir.org/claim.html#Claim.procedure" #f)
    (schema-field 'insurance 0 '* (vector 'type 'ClaimInsurance) #f "https://build.fhir.org/claim.html#Claim.insurance" #f)
    (schema-field 'accident 0 1 (vector 'type 'ClaimAccident) #f "https://build.fhir.org/claim.html#Claim.accident" #f)
    (schema-field 'patientPaid 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.patientPaid" #f)
    (schema-field 'item 0 '* (vector 'type 'ClaimItem) #f "https://build.fhir.org/claim.html#Claim.item" #f)
    (schema-field 'total 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.total" #f)
             ) #f #f))
(register-element! "Claim.identifier" (fhir-spec (string->symbol "Claim.identifier") "https://build.fhir.org/claim.html#Claim.identifier" 'element))
(register-element! "Claim.traceNumber" (fhir-spec (string->symbol "Claim.traceNumber") "https://build.fhir.org/claim.html#Claim.traceNumber" 'element))
(register-element! "Claim.status" (fhir-spec (string->symbol "Claim.status") "https://build.fhir.org/claim.html#Claim.status" 'element))
(register-element! "Claim.statusReason" (fhir-spec (string->symbol "Claim.statusReason") "https://build.fhir.org/claim.html#Claim.statusReason" 'element))
(register-element! "Claim.type" (fhir-spec (string->symbol "Claim.type") "https://build.fhir.org/claim.html#Claim.type" 'element))
(register-element! "Claim.subType" (fhir-spec (string->symbol "Claim.subType") "https://build.fhir.org/claim.html#Claim.subType" 'element))
(register-element! "Claim.use" (fhir-spec (string->symbol "Claim.use") "https://build.fhir.org/claim.html#Claim.use" 'element))
(register-element! "Claim.subject" (fhir-spec (string->symbol "Claim.subject") "https://build.fhir.org/claim.html#Claim.subject" 'element))
(register-element! "Claim.billablePeriod" (fhir-spec (string->symbol "Claim.billablePeriod") "https://build.fhir.org/claim.html#Claim.billablePeriod" 'element))
(register-element! "Claim.created" (fhir-spec (string->symbol "Claim.created") "https://build.fhir.org/claim.html#Claim.created" 'element))
(register-element! "Claim.enterer" (fhir-spec (string->symbol "Claim.enterer") "https://build.fhir.org/claim.html#Claim.enterer" 'element))
(register-element! "Claim.insurer" (fhir-spec (string->symbol "Claim.insurer") "https://build.fhir.org/claim.html#Claim.insurer" 'element))
(register-element! "Claim.provider" (fhir-spec (string->symbol "Claim.provider") "https://build.fhir.org/claim.html#Claim.provider" 'element))
(register-element! "Claim.priority" (fhir-spec (string->symbol "Claim.priority") "https://build.fhir.org/claim.html#Claim.priority" 'element))
(register-element! "Claim.fundsReserve" (fhir-spec (string->symbol "Claim.fundsReserve") "https://build.fhir.org/claim.html#Claim.fundsReserve" 'element))
(register-element! "Claim.related" (fhir-spec (string->symbol "Claim.related") "https://build.fhir.org/claim.html#Claim.related" 'element))
(register-element! "Claim.prescription" (fhir-spec (string->symbol "Claim.prescription") "https://build.fhir.org/claim.html#Claim.prescription" 'element))
(register-element! "Claim.originalPrescription" (fhir-spec (string->symbol "Claim.originalPrescription") "https://build.fhir.org/claim.html#Claim.originalPrescription" 'element))
(register-element! "Claim.payee" (fhir-spec (string->symbol "Claim.payee") "https://build.fhir.org/claim.html#Claim.payee" 'element))
(register-element! "Claim.referral" (fhir-spec (string->symbol "Claim.referral") "https://build.fhir.org/claim.html#Claim.referral" 'element))
(register-element! "Claim.encounter" (fhir-spec (string->symbol "Claim.encounter") "https://build.fhir.org/claim.html#Claim.encounter" 'element))
(register-element! "Claim.facility" (fhir-spec (string->symbol "Claim.facility") "https://build.fhir.org/claim.html#Claim.facility" 'element))
(register-element! "Claim.diagnosisRelatedGroup" (fhir-spec (string->symbol "Claim.diagnosisRelatedGroup") "https://build.fhir.org/claim.html#Claim.diagnosisRelatedGroup" 'element))
(register-element! "Claim.event" (fhir-spec (string->symbol "Claim.event") "https://build.fhir.org/claim.html#Claim.event" 'element))
(register-element! "Claim.careTeam" (fhir-spec (string->symbol "Claim.careTeam") "https://build.fhir.org/claim.html#Claim.careTeam" 'element))
(register-element! "Claim.supportingInfo" (fhir-spec (string->symbol "Claim.supportingInfo") "https://build.fhir.org/claim.html#Claim.supportingInfo" 'element))
(register-element! "Claim.diagnosis" (fhir-spec (string->symbol "Claim.diagnosis") "https://build.fhir.org/claim.html#Claim.diagnosis" 'element))
(register-element! "Claim.procedure" (fhir-spec (string->symbol "Claim.procedure") "https://build.fhir.org/claim.html#Claim.procedure" 'element))
(register-element! "Claim.insurance" (fhir-spec (string->symbol "Claim.insurance") "https://build.fhir.org/claim.html#Claim.insurance" 'element))
(register-element! "Claim.accident" (fhir-spec (string->symbol "Claim.accident") "https://build.fhir.org/claim.html#Claim.accident" 'element))
(register-element! "Claim.patientPaid" (fhir-spec (string->symbol "Claim.patientPaid") "https://build.fhir.org/claim.html#Claim.patientPaid" 'element))
(register-element! "Claim.item" (fhir-spec (string->symbol "Claim.item") "https://build.fhir.org/claim.html#Claim.item" 'element))
(register-element! "Claim.total" (fhir-spec (string->symbol "Claim.total") "https://build.fhir.org/claim.html#Claim.total" 'element))

(register-type! 'ClaimRelated (fhir-spec 'ClaimRelated "https://build.fhir.org/claim.html#Claim.related" 'type)
  #:schema (type-schema 'ClaimRelated #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.related"
             (list
    (schema-field 'claim 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.related.claim" #f)
    (schema-field 'relationship 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.related.relationship" #f)
    (schema-field 'reference 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/claim.html#Claim.related.reference" #f)
             ) #f #f))
(register-element! "Claim.related.claim" (fhir-spec (string->symbol "Claim.related.claim") "https://build.fhir.org/claim.html#Claim.related.claim" 'element))
(register-element! "Claim.related.relationship" (fhir-spec (string->symbol "Claim.related.relationship") "https://build.fhir.org/claim.html#Claim.related.relationship" 'element))
(register-element! "Claim.related.reference" (fhir-spec (string->symbol "Claim.related.reference") "https://build.fhir.org/claim.html#Claim.related.reference" 'element))

(register-type! 'ClaimPayee (fhir-spec 'ClaimPayee "https://build.fhir.org/claim.html#Claim.payee" 'type)
  #:schema (type-schema 'ClaimPayee #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.payee"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.payee.type" #f)
    (schema-field 'party 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.payee.party" #f)
             ) #f #f))
(register-element! "Claim.payee.type" (fhir-spec (string->symbol "Claim.payee.type") "https://build.fhir.org/claim.html#Claim.payee.type" 'element))
(register-element! "Claim.payee.party" (fhir-spec (string->symbol "Claim.payee.party") "https://build.fhir.org/claim.html#Claim.payee.party" 'element))

(register-type! 'ClaimEvent (fhir-spec 'ClaimEvent "https://build.fhir.org/claim.html#Claim.event" 'type)
  #:schema (type-schema 'ClaimEvent #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.event"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.event.type" #f)
    (schema-field 'whenDateTime 0 1 (vector 'prim "dateTime") 'when "https://build.fhir.org/claim.html#Claim.event.when[x]" #f)
    (schema-field 'whenPeriod 0 1 (vector 'type 'Period) 'when "https://build.fhir.org/claim.html#Claim.event.when[x]" #f)
             ) #f #f))
(register-element! "Claim.event.type" (fhir-spec (string->symbol "Claim.event.type") "https://build.fhir.org/claim.html#Claim.event.type" 'element))
(register-element! "Claim.event.when[x]" (fhir-spec (string->symbol "Claim.event.when[x]") "https://build.fhir.org/claim.html#Claim.event.when[x]" 'element))
(register-element! "Claim.event.when[x]" (fhir-spec (string->symbol "Claim.event.when[x]") "https://build.fhir.org/claim.html#Claim.event.when[x]" 'element))

(register-type! 'ClaimCareTeam (fhir-spec 'ClaimCareTeam "https://build.fhir.org/claim.html#Claim.careTeam" 'type)
  #:schema (type-schema 'ClaimCareTeam #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.careTeam"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.careTeam.sequence" #f)
    (schema-field 'provider 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.careTeam.provider" #f)
    (schema-field 'role 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.careTeam.role" #f)
    (schema-field 'specialty 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.careTeam.specialty" #f)
             ) #f #f))
(register-element! "Claim.careTeam.sequence" (fhir-spec (string->symbol "Claim.careTeam.sequence") "https://build.fhir.org/claim.html#Claim.careTeam.sequence" 'element))
(register-element! "Claim.careTeam.provider" (fhir-spec (string->symbol "Claim.careTeam.provider") "https://build.fhir.org/claim.html#Claim.careTeam.provider" 'element))
(register-element! "Claim.careTeam.role" (fhir-spec (string->symbol "Claim.careTeam.role") "https://build.fhir.org/claim.html#Claim.careTeam.role" 'element))
(register-element! "Claim.careTeam.specialty" (fhir-spec (string->symbol "Claim.careTeam.specialty") "https://build.fhir.org/claim.html#Claim.careTeam.specialty" 'element))

(register-type! 'ClaimSupportingInfo (fhir-spec 'ClaimSupportingInfo "https://build.fhir.org/claim.html#Claim.supportingInfo" 'type)
  #:schema (type-schema 'ClaimSupportingInfo #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.supportingInfo"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.supportingInfo.sequence" #f)
    (schema-field 'category 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.supportingInfo.category" #f)
    (schema-field 'subCategory 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.supportingInfo.subCategory" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.supportingInfo.code" #f)
    (schema-field 'reason 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.supportingInfo.reason" #f)
    (schema-field 'timingDateTime 0 1 (vector 'prim "dateTime") 'timing "https://build.fhir.org/claim.html#Claim.supportingInfo.timing[x]" #f)
    (schema-field 'timingPeriod 0 1 (vector 'type 'Period) 'timing "https://build.fhir.org/claim.html#Claim.supportingInfo.timing[x]" #f)
    (schema-field 'timingTiming 0 1 (vector 'type 'Timing) 'timing "https://build.fhir.org/claim.html#Claim.supportingInfo.timing[x]" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueInteger64 0 1 (vector 'prim "integer64") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueCodeableReference 0 1 (vector 'type 'CodeableReference) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueRatioRange 0 1 (vector 'type 'RatioRange) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueAvailability 0 1 (vector 'type 'Availability) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueExtendedContactDetail 0 1 (vector 'type 'ExtendedContactDetail) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueVirtualServiceDetail 0 1 (vector 'type 'VirtualServiceDetail) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" #f)
             ) #f #f))
(register-element! "Claim.supportingInfo.sequence" (fhir-spec (string->symbol "Claim.supportingInfo.sequence") "https://build.fhir.org/claim.html#Claim.supportingInfo.sequence" 'element))
(register-element! "Claim.supportingInfo.category" (fhir-spec (string->symbol "Claim.supportingInfo.category") "https://build.fhir.org/claim.html#Claim.supportingInfo.category" 'element))
(register-element! "Claim.supportingInfo.subCategory" (fhir-spec (string->symbol "Claim.supportingInfo.subCategory") "https://build.fhir.org/claim.html#Claim.supportingInfo.subCategory" 'element))
(register-element! "Claim.supportingInfo.code" (fhir-spec (string->symbol "Claim.supportingInfo.code") "https://build.fhir.org/claim.html#Claim.supportingInfo.code" 'element))
(register-element! "Claim.supportingInfo.reason" (fhir-spec (string->symbol "Claim.supportingInfo.reason") "https://build.fhir.org/claim.html#Claim.supportingInfo.reason" 'element))
(register-element! "Claim.supportingInfo.timing[x]" (fhir-spec (string->symbol "Claim.supportingInfo.timing[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.timing[x]" 'element))
(register-element! "Claim.supportingInfo.timing[x]" (fhir-spec (string->symbol "Claim.supportingInfo.timing[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.timing[x]" 'element))
(register-element! "Claim.supportingInfo.timing[x]" (fhir-spec (string->symbol "Claim.supportingInfo.timing[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.timing[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))
(register-element! "Claim.supportingInfo.value[x]" (fhir-spec (string->symbol "Claim.supportingInfo.value[x]") "https://build.fhir.org/claim.html#Claim.supportingInfo.value[x]" 'element))

(register-type! 'ClaimDiagnosis (fhir-spec 'ClaimDiagnosis "https://build.fhir.org/claim.html#Claim.diagnosis" 'type)
  #:schema (type-schema 'ClaimDiagnosis #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.diagnosis"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.diagnosis.sequence" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.diagnosis.type" #f)
    (schema-field 'onAdmission 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.diagnosis.onAdmission" #f)
    (schema-field 'diagnosisCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'diagnosis "https://build.fhir.org/claim.html#Claim.diagnosis.diagnosis[x]" #f)
    (schema-field 'diagnosisReference 0 1 (vector 'type 'Reference) 'diagnosis "https://build.fhir.org/claim.html#Claim.diagnosis.diagnosis[x]" #f)
             ) #f #f))
(register-element! "Claim.diagnosis.sequence" (fhir-spec (string->symbol "Claim.diagnosis.sequence") "https://build.fhir.org/claim.html#Claim.diagnosis.sequence" 'element))
(register-element! "Claim.diagnosis.type" (fhir-spec (string->symbol "Claim.diagnosis.type") "https://build.fhir.org/claim.html#Claim.diagnosis.type" 'element))
(register-element! "Claim.diagnosis.onAdmission" (fhir-spec (string->symbol "Claim.diagnosis.onAdmission") "https://build.fhir.org/claim.html#Claim.diagnosis.onAdmission" 'element))
(register-element! "Claim.diagnosis.diagnosis[x]" (fhir-spec (string->symbol "Claim.diagnosis.diagnosis[x]") "https://build.fhir.org/claim.html#Claim.diagnosis.diagnosis[x]" 'element))
(register-element! "Claim.diagnosis.diagnosis[x]" (fhir-spec (string->symbol "Claim.diagnosis.diagnosis[x]") "https://build.fhir.org/claim.html#Claim.diagnosis.diagnosis[x]" 'element))

(register-type! 'ClaimProcedure (fhir-spec 'ClaimProcedure "https://build.fhir.org/claim.html#Claim.procedure" 'type)
  #:schema (type-schema 'ClaimProcedure #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.procedure"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.procedure.sequence" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.procedure.type" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/claim.html#Claim.procedure.date" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.procedure.udi" #f)
    (schema-field 'procedureCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'procedure "https://build.fhir.org/claim.html#Claim.procedure.procedure[x]" #f)
    (schema-field 'procedureReference 0 1 (vector 'type 'Reference) 'procedure "https://build.fhir.org/claim.html#Claim.procedure.procedure[x]" #f)
             ) #f #f))
(register-element! "Claim.procedure.sequence" (fhir-spec (string->symbol "Claim.procedure.sequence") "https://build.fhir.org/claim.html#Claim.procedure.sequence" 'element))
(register-element! "Claim.procedure.type" (fhir-spec (string->symbol "Claim.procedure.type") "https://build.fhir.org/claim.html#Claim.procedure.type" 'element))
(register-element! "Claim.procedure.date" (fhir-spec (string->symbol "Claim.procedure.date") "https://build.fhir.org/claim.html#Claim.procedure.date" 'element))
(register-element! "Claim.procedure.udi" (fhir-spec (string->symbol "Claim.procedure.udi") "https://build.fhir.org/claim.html#Claim.procedure.udi" 'element))
(register-element! "Claim.procedure.procedure[x]" (fhir-spec (string->symbol "Claim.procedure.procedure[x]") "https://build.fhir.org/claim.html#Claim.procedure.procedure[x]" 'element))
(register-element! "Claim.procedure.procedure[x]" (fhir-spec (string->symbol "Claim.procedure.procedure[x]") "https://build.fhir.org/claim.html#Claim.procedure.procedure[x]" 'element))

(register-type! 'ClaimInsurance (fhir-spec 'ClaimInsurance "https://build.fhir.org/claim.html#Claim.insurance" 'type)
  #:schema (type-schema 'ClaimInsurance #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.insurance"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.insurance.sequence" #f)
    (schema-field 'focal 1 1 (vector 'prim "boolean") #f "https://build.fhir.org/claim.html#Claim.insurance.focal" #f)
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/claim.html#Claim.insurance.identifier" #f)
    (schema-field 'coverage 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.insurance.coverage" #f)
    (schema-field 'businessArrangement 0 1 (vector 'prim "string") #f "https://build.fhir.org/claim.html#Claim.insurance.businessArrangement" #f)
    (schema-field 'preAuthRef 0 '* (vector 'prim "string") #f "https://build.fhir.org/claim.html#Claim.insurance.preAuthRef" #f)
    (schema-field 'claimResponse 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.insurance.claimResponse" #f)
             ) #f #f))
(register-element! "Claim.insurance.sequence" (fhir-spec (string->symbol "Claim.insurance.sequence") "https://build.fhir.org/claim.html#Claim.insurance.sequence" 'element))
(register-element! "Claim.insurance.focal" (fhir-spec (string->symbol "Claim.insurance.focal") "https://build.fhir.org/claim.html#Claim.insurance.focal" 'element))
(register-element! "Claim.insurance.identifier" (fhir-spec (string->symbol "Claim.insurance.identifier") "https://build.fhir.org/claim.html#Claim.insurance.identifier" 'element))
(register-element! "Claim.insurance.coverage" (fhir-spec (string->symbol "Claim.insurance.coverage") "https://build.fhir.org/claim.html#Claim.insurance.coverage" 'element))
(register-element! "Claim.insurance.businessArrangement" (fhir-spec (string->symbol "Claim.insurance.businessArrangement") "https://build.fhir.org/claim.html#Claim.insurance.businessArrangement" 'element))
(register-element! "Claim.insurance.preAuthRef" (fhir-spec (string->symbol "Claim.insurance.preAuthRef") "https://build.fhir.org/claim.html#Claim.insurance.preAuthRef" 'element))
(register-element! "Claim.insurance.claimResponse" (fhir-spec (string->symbol "Claim.insurance.claimResponse") "https://build.fhir.org/claim.html#Claim.insurance.claimResponse" 'element))

(register-type! 'ClaimAccident (fhir-spec 'ClaimAccident "https://build.fhir.org/claim.html#Claim.accident" 'type)
  #:schema (type-schema 'ClaimAccident #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.accident"
             (list
    (schema-field 'date 1 1 (vector 'prim "date") #f "https://build.fhir.org/claim.html#Claim.accident.date" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.accident.type" #f)
    (schema-field 'locationAddress 0 1 (vector 'type 'Address) 'location "https://build.fhir.org/claim.html#Claim.accident.location[x]" #f)
    (schema-field 'locationReference 0 1 (vector 'type 'Reference) 'location "https://build.fhir.org/claim.html#Claim.accident.location[x]" #f)
             ) #f #f))
(register-element! "Claim.accident.date" (fhir-spec (string->symbol "Claim.accident.date") "https://build.fhir.org/claim.html#Claim.accident.date" 'element))
(register-element! "Claim.accident.type" (fhir-spec (string->symbol "Claim.accident.type") "https://build.fhir.org/claim.html#Claim.accident.type" 'element))
(register-element! "Claim.accident.location[x]" (fhir-spec (string->symbol "Claim.accident.location[x]") "https://build.fhir.org/claim.html#Claim.accident.location[x]" 'element))
(register-element! "Claim.accident.location[x]" (fhir-spec (string->symbol "Claim.accident.location[x]") "https://build.fhir.org/claim.html#Claim.accident.location[x]" 'element))

(register-type! 'ClaimItem (fhir-spec 'ClaimItem "https://build.fhir.org/claim.html#Claim.item" 'type)
  #:schema (type-schema 'ClaimItem #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.item"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.item.sequence" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/claim.html#Claim.item.traceNumber" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.item.subject" #f)
    (schema-field 'careTeamSequence 0 '* (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.item.careTeamSequence" #f)
    (schema-field 'diagnosisSequence 0 '* (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.item.diagnosisSequence" #f)
    (schema-field 'procedureSequence 0 '* (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.item.procedureSequence" #f)
    (schema-field 'informationSequence 0 '* (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.item.informationSequence" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.revenue" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.category" #f)
    (schema-field 'productOrService 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.productOrService" #f)
    (schema-field 'productOrServiceEnd 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.productOrServiceEnd" #f)
    (schema-field 'request 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.item.request" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.programCode" #f)
    (schema-field 'patientPaid 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.patientPaid" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/claim.html#Claim.item.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/claim.html#Claim.item.factor" #f)
    (schema-field 'tax 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.tax" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.net" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.item.udi" #f)
    (schema-field 'bodySite 0 '* (vector 'type 'ClaimItemBodySite) #f "https://build.fhir.org/claim.html#Claim.item.bodySite" #f)
    (schema-field 'encounter 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.item.encounter" #f)
    (schema-field 'detail 0 '* (vector 'type 'ClaimItemDetail) #f "https://build.fhir.org/claim.html#Claim.item.detail" #f)
    (schema-field 'servicedDate 0 1 (vector 'prim "date") 'serviced "https://build.fhir.org/claim.html#Claim.item.serviced[x]" #f)
    (schema-field 'servicedPeriod 0 1 (vector 'type 'Period) 'serviced "https://build.fhir.org/claim.html#Claim.item.serviced[x]" #f)
    (schema-field 'locationCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'location "https://build.fhir.org/claim.html#Claim.item.location[x]" #f)
    (schema-field 'locationAddress 0 1 (vector 'type 'Address) 'location "https://build.fhir.org/claim.html#Claim.item.location[x]" #f)
    (schema-field 'locationReference 0 1 (vector 'type 'Reference) 'location "https://build.fhir.org/claim.html#Claim.item.location[x]" #f)
             ) #f #f))
(register-element! "Claim.item.sequence" (fhir-spec (string->symbol "Claim.item.sequence") "https://build.fhir.org/claim.html#Claim.item.sequence" 'element))
(register-element! "Claim.item.traceNumber" (fhir-spec (string->symbol "Claim.item.traceNumber") "https://build.fhir.org/claim.html#Claim.item.traceNumber" 'element))
(register-element! "Claim.item.subject" (fhir-spec (string->symbol "Claim.item.subject") "https://build.fhir.org/claim.html#Claim.item.subject" 'element))
(register-element! "Claim.item.careTeamSequence" (fhir-spec (string->symbol "Claim.item.careTeamSequence") "https://build.fhir.org/claim.html#Claim.item.careTeamSequence" 'element))
(register-element! "Claim.item.diagnosisSequence" (fhir-spec (string->symbol "Claim.item.diagnosisSequence") "https://build.fhir.org/claim.html#Claim.item.diagnosisSequence" 'element))
(register-element! "Claim.item.procedureSequence" (fhir-spec (string->symbol "Claim.item.procedureSequence") "https://build.fhir.org/claim.html#Claim.item.procedureSequence" 'element))
(register-element! "Claim.item.informationSequence" (fhir-spec (string->symbol "Claim.item.informationSequence") "https://build.fhir.org/claim.html#Claim.item.informationSequence" 'element))
(register-element! "Claim.item.revenue" (fhir-spec (string->symbol "Claim.item.revenue") "https://build.fhir.org/claim.html#Claim.item.revenue" 'element))
(register-element! "Claim.item.category" (fhir-spec (string->symbol "Claim.item.category") "https://build.fhir.org/claim.html#Claim.item.category" 'element))
(register-element! "Claim.item.productOrService" (fhir-spec (string->symbol "Claim.item.productOrService") "https://build.fhir.org/claim.html#Claim.item.productOrService" 'element))
(register-element! "Claim.item.productOrServiceEnd" (fhir-spec (string->symbol "Claim.item.productOrServiceEnd") "https://build.fhir.org/claim.html#Claim.item.productOrServiceEnd" 'element))
(register-element! "Claim.item.request" (fhir-spec (string->symbol "Claim.item.request") "https://build.fhir.org/claim.html#Claim.item.request" 'element))
(register-element! "Claim.item.modifier" (fhir-spec (string->symbol "Claim.item.modifier") "https://build.fhir.org/claim.html#Claim.item.modifier" 'element))
(register-element! "Claim.item.programCode" (fhir-spec (string->symbol "Claim.item.programCode") "https://build.fhir.org/claim.html#Claim.item.programCode" 'element))
(register-element! "Claim.item.patientPaid" (fhir-spec (string->symbol "Claim.item.patientPaid") "https://build.fhir.org/claim.html#Claim.item.patientPaid" 'element))
(register-element! "Claim.item.quantity" (fhir-spec (string->symbol "Claim.item.quantity") "https://build.fhir.org/claim.html#Claim.item.quantity" 'element))
(register-element! "Claim.item.unitPrice" (fhir-spec (string->symbol "Claim.item.unitPrice") "https://build.fhir.org/claim.html#Claim.item.unitPrice" 'element))
(register-element! "Claim.item.factor" (fhir-spec (string->symbol "Claim.item.factor") "https://build.fhir.org/claim.html#Claim.item.factor" 'element))
(register-element! "Claim.item.tax" (fhir-spec (string->symbol "Claim.item.tax") "https://build.fhir.org/claim.html#Claim.item.tax" 'element))
(register-element! "Claim.item.net" (fhir-spec (string->symbol "Claim.item.net") "https://build.fhir.org/claim.html#Claim.item.net" 'element))
(register-element! "Claim.item.udi" (fhir-spec (string->symbol "Claim.item.udi") "https://build.fhir.org/claim.html#Claim.item.udi" 'element))
(register-element! "Claim.item.bodySite" (fhir-spec (string->symbol "Claim.item.bodySite") "https://build.fhir.org/claim.html#Claim.item.bodySite" 'element))
(register-element! "Claim.item.encounter" (fhir-spec (string->symbol "Claim.item.encounter") "https://build.fhir.org/claim.html#Claim.item.encounter" 'element))
(register-element! "Claim.item.detail" (fhir-spec (string->symbol "Claim.item.detail") "https://build.fhir.org/claim.html#Claim.item.detail" 'element))
(register-element! "Claim.item.serviced[x]" (fhir-spec (string->symbol "Claim.item.serviced[x]") "https://build.fhir.org/claim.html#Claim.item.serviced[x]" 'element))
(register-element! "Claim.item.serviced[x]" (fhir-spec (string->symbol "Claim.item.serviced[x]") "https://build.fhir.org/claim.html#Claim.item.serviced[x]" 'element))
(register-element! "Claim.item.location[x]" (fhir-spec (string->symbol "Claim.item.location[x]") "https://build.fhir.org/claim.html#Claim.item.location[x]" 'element))
(register-element! "Claim.item.location[x]" (fhir-spec (string->symbol "Claim.item.location[x]") "https://build.fhir.org/claim.html#Claim.item.location[x]" 'element))
(register-element! "Claim.item.location[x]" (fhir-spec (string->symbol "Claim.item.location[x]") "https://build.fhir.org/claim.html#Claim.item.location[x]" 'element))

(register-type! 'ClaimItemBodySite (fhir-spec 'ClaimItemBodySite "https://build.fhir.org/claim.html#Claim.item.bodySite" 'type)
  #:schema (type-schema 'ClaimItemBodySite #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.item.bodySite"
             (list
    (schema-field 'site 1 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/claim.html#Claim.item.bodySite.site" #f)
    (schema-field 'subSite 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.bodySite.subSite" #f)
             ) #f #f))
(register-element! "Claim.item.bodySite.site" (fhir-spec (string->symbol "Claim.item.bodySite.site") "https://build.fhir.org/claim.html#Claim.item.bodySite.site" 'element))
(register-element! "Claim.item.bodySite.subSite" (fhir-spec (string->symbol "Claim.item.bodySite.subSite") "https://build.fhir.org/claim.html#Claim.item.bodySite.subSite" 'element))

(register-type! 'ClaimItemDetail (fhir-spec 'ClaimItemDetail "https://build.fhir.org/claim.html#Claim.item.detail" 'type)
  #:schema (type-schema 'ClaimItemDetail #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.item.detail"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.item.detail.sequence" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/claim.html#Claim.item.detail.traceNumber" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.revenue" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.category" #f)
    (schema-field 'productOrService 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.productOrService" #f)
    (schema-field 'productOrServiceEnd 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.productOrServiceEnd" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.programCode" #f)
    (schema-field 'patientPaid 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.patientPaid" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/claim.html#Claim.item.detail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/claim.html#Claim.item.detail.factor" #f)
    (schema-field 'tax 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.tax" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.net" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.item.detail.udi" #f)
    (schema-field 'subDetail 0 '* (vector 'type 'ClaimItemDetailSubDetail) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail" #f)
             ) #f #f))
(register-element! "Claim.item.detail.sequence" (fhir-spec (string->symbol "Claim.item.detail.sequence") "https://build.fhir.org/claim.html#Claim.item.detail.sequence" 'element))
(register-element! "Claim.item.detail.traceNumber" (fhir-spec (string->symbol "Claim.item.detail.traceNumber") "https://build.fhir.org/claim.html#Claim.item.detail.traceNumber" 'element))
(register-element! "Claim.item.detail.revenue" (fhir-spec (string->symbol "Claim.item.detail.revenue") "https://build.fhir.org/claim.html#Claim.item.detail.revenue" 'element))
(register-element! "Claim.item.detail.category" (fhir-spec (string->symbol "Claim.item.detail.category") "https://build.fhir.org/claim.html#Claim.item.detail.category" 'element))
(register-element! "Claim.item.detail.productOrService" (fhir-spec (string->symbol "Claim.item.detail.productOrService") "https://build.fhir.org/claim.html#Claim.item.detail.productOrService" 'element))
(register-element! "Claim.item.detail.productOrServiceEnd" (fhir-spec (string->symbol "Claim.item.detail.productOrServiceEnd") "https://build.fhir.org/claim.html#Claim.item.detail.productOrServiceEnd" 'element))
(register-element! "Claim.item.detail.modifier" (fhir-spec (string->symbol "Claim.item.detail.modifier") "https://build.fhir.org/claim.html#Claim.item.detail.modifier" 'element))
(register-element! "Claim.item.detail.programCode" (fhir-spec (string->symbol "Claim.item.detail.programCode") "https://build.fhir.org/claim.html#Claim.item.detail.programCode" 'element))
(register-element! "Claim.item.detail.patientPaid" (fhir-spec (string->symbol "Claim.item.detail.patientPaid") "https://build.fhir.org/claim.html#Claim.item.detail.patientPaid" 'element))
(register-element! "Claim.item.detail.quantity" (fhir-spec (string->symbol "Claim.item.detail.quantity") "https://build.fhir.org/claim.html#Claim.item.detail.quantity" 'element))
(register-element! "Claim.item.detail.unitPrice" (fhir-spec (string->symbol "Claim.item.detail.unitPrice") "https://build.fhir.org/claim.html#Claim.item.detail.unitPrice" 'element))
(register-element! "Claim.item.detail.factor" (fhir-spec (string->symbol "Claim.item.detail.factor") "https://build.fhir.org/claim.html#Claim.item.detail.factor" 'element))
(register-element! "Claim.item.detail.tax" (fhir-spec (string->symbol "Claim.item.detail.tax") "https://build.fhir.org/claim.html#Claim.item.detail.tax" 'element))
(register-element! "Claim.item.detail.net" (fhir-spec (string->symbol "Claim.item.detail.net") "https://build.fhir.org/claim.html#Claim.item.detail.net" 'element))
(register-element! "Claim.item.detail.udi" (fhir-spec (string->symbol "Claim.item.detail.udi") "https://build.fhir.org/claim.html#Claim.item.detail.udi" 'element))
(register-element! "Claim.item.detail.subDetail" (fhir-spec (string->symbol "Claim.item.detail.subDetail") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail" 'element))

(register-type! 'ClaimItemDetailSubDetail (fhir-spec 'ClaimItemDetailSubDetail "https://build.fhir.org/claim.html#Claim.item.detail.subDetail" 'type)
  #:schema (type-schema 'ClaimItemDetailSubDetail #f 'BackboneElement "https://build.fhir.org/claim.html#Claim.item.detail.subDetail"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.sequence" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.traceNumber" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.revenue" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.category" #f)
    (schema-field 'productOrService 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.productOrService" #f)
    (schema-field 'productOrServiceEnd 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.productOrServiceEnd" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.programCode" #f)
    (schema-field 'patientPaid 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.patientPaid" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.factor" #f)
    (schema-field 'tax 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.tax" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.net" #f)
    (schema-field 'udi 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.udi" #f)
             ) #f #f))
(register-element! "Claim.item.detail.subDetail.sequence" (fhir-spec (string->symbol "Claim.item.detail.subDetail.sequence") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.sequence" 'element))
(register-element! "Claim.item.detail.subDetail.traceNumber" (fhir-spec (string->symbol "Claim.item.detail.subDetail.traceNumber") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.traceNumber" 'element))
(register-element! "Claim.item.detail.subDetail.revenue" (fhir-spec (string->symbol "Claim.item.detail.subDetail.revenue") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.revenue" 'element))
(register-element! "Claim.item.detail.subDetail.category" (fhir-spec (string->symbol "Claim.item.detail.subDetail.category") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.category" 'element))
(register-element! "Claim.item.detail.subDetail.productOrService" (fhir-spec (string->symbol "Claim.item.detail.subDetail.productOrService") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.productOrService" 'element))
(register-element! "Claim.item.detail.subDetail.productOrServiceEnd" (fhir-spec (string->symbol "Claim.item.detail.subDetail.productOrServiceEnd") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.productOrServiceEnd" 'element))
(register-element! "Claim.item.detail.subDetail.modifier" (fhir-spec (string->symbol "Claim.item.detail.subDetail.modifier") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.modifier" 'element))
(register-element! "Claim.item.detail.subDetail.programCode" (fhir-spec (string->symbol "Claim.item.detail.subDetail.programCode") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.programCode" 'element))
(register-element! "Claim.item.detail.subDetail.patientPaid" (fhir-spec (string->symbol "Claim.item.detail.subDetail.patientPaid") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.patientPaid" 'element))
(register-element! "Claim.item.detail.subDetail.quantity" (fhir-spec (string->symbol "Claim.item.detail.subDetail.quantity") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.quantity" 'element))
(register-element! "Claim.item.detail.subDetail.unitPrice" (fhir-spec (string->symbol "Claim.item.detail.subDetail.unitPrice") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.unitPrice" 'element))
(register-element! "Claim.item.detail.subDetail.factor" (fhir-spec (string->symbol "Claim.item.detail.subDetail.factor") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.factor" 'element))
(register-element! "Claim.item.detail.subDetail.tax" (fhir-spec (string->symbol "Claim.item.detail.subDetail.tax") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.tax" 'element))
(register-element! "Claim.item.detail.subDetail.net" (fhir-spec (string->symbol "Claim.item.detail.subDetail.net") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.net" 'element))
(register-element! "Claim.item.detail.subDetail.udi" (fhir-spec (string->symbol "Claim.item.detail.subDetail.udi") "https://build.fhir.org/claim.html#Claim.item.detail.subDetail.udi" 'element))

