#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Consent (fhir-spec 'Consent "https://build.fhir.org/consent.html#Consent" 'type)
  #:schema (type-schema 'Consent #f 'DomainResource "https://build.fhir.org/consent.html#Consent"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/consent.html#Consent.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/consent.html#Consent.status" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/consent.html#Consent.category" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.subject" #f)
    (schema-field 'date 0 1 (vector 'prim "date") #f "https://build.fhir.org/consent.html#Consent.date" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/consent.html#Consent.period" #f)
    (schema-field 'grantor 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.grantor" #f)
    (schema-field 'grantee 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.grantee" #f)
    (schema-field 'manager 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.manager" #f)
    (schema-field 'controller 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.controller" #f)
    (schema-field 'sourceAttachment 0 '* (vector 'type 'Attachment) #f "https://build.fhir.org/consent.html#Consent.sourceAttachment" #f)
    (schema-field 'sourceReference 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.sourceReference" #f)
    (schema-field 'regulatoryBasis 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/consent.html#Consent.regulatoryBasis" #f)
    (schema-field 'policyBasis 0 1 (vector 'type 'ConsentPolicyBasis) #f "https://build.fhir.org/consent.html#Consent.policyBasis" #f)
    (schema-field 'policyText 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.policyText" #f)
    (schema-field 'verification 0 '* (vector 'type 'ConsentVerification) #f "https://build.fhir.org/consent.html#Consent.verification" #f)
    (schema-field 'decision 0 1 (vector 'prim "code") #f "https://build.fhir.org/consent.html#Consent.decision" #f)
    (schema-field 'provision 0 '* (vector 'type 'ConsentProvision) #f "https://build.fhir.org/consent.html#Consent.provision" #f)
             ) #f #f))
(register-element! "Consent.identifier" (fhir-spec (string->symbol "Consent.identifier") "https://build.fhir.org/consent.html#Consent.identifier" 'element))
(register-element! "Consent.status" (fhir-spec (string->symbol "Consent.status") "https://build.fhir.org/consent.html#Consent.status" 'element))
(register-element! "Consent.category" (fhir-spec (string->symbol "Consent.category") "https://build.fhir.org/consent.html#Consent.category" 'element))
(register-element! "Consent.subject" (fhir-spec (string->symbol "Consent.subject") "https://build.fhir.org/consent.html#Consent.subject" 'element))
(register-element! "Consent.date" (fhir-spec (string->symbol "Consent.date") "https://build.fhir.org/consent.html#Consent.date" 'element))
(register-element! "Consent.period" (fhir-spec (string->symbol "Consent.period") "https://build.fhir.org/consent.html#Consent.period" 'element))
(register-element! "Consent.grantor" (fhir-spec (string->symbol "Consent.grantor") "https://build.fhir.org/consent.html#Consent.grantor" 'element))
(register-element! "Consent.grantee" (fhir-spec (string->symbol "Consent.grantee") "https://build.fhir.org/consent.html#Consent.grantee" 'element))
(register-element! "Consent.manager" (fhir-spec (string->symbol "Consent.manager") "https://build.fhir.org/consent.html#Consent.manager" 'element))
(register-element! "Consent.controller" (fhir-spec (string->symbol "Consent.controller") "https://build.fhir.org/consent.html#Consent.controller" 'element))
(register-element! "Consent.sourceAttachment" (fhir-spec (string->symbol "Consent.sourceAttachment") "https://build.fhir.org/consent.html#Consent.sourceAttachment" 'element))
(register-element! "Consent.sourceReference" (fhir-spec (string->symbol "Consent.sourceReference") "https://build.fhir.org/consent.html#Consent.sourceReference" 'element))
(register-element! "Consent.regulatoryBasis" (fhir-spec (string->symbol "Consent.regulatoryBasis") "https://build.fhir.org/consent.html#Consent.regulatoryBasis" 'element))
(register-element! "Consent.policyBasis" (fhir-spec (string->symbol "Consent.policyBasis") "https://build.fhir.org/consent.html#Consent.policyBasis" 'element))
(register-element! "Consent.policyText" (fhir-spec (string->symbol "Consent.policyText") "https://build.fhir.org/consent.html#Consent.policyText" 'element))
(register-element! "Consent.verification" (fhir-spec (string->symbol "Consent.verification") "https://build.fhir.org/consent.html#Consent.verification" 'element))
(register-element! "Consent.decision" (fhir-spec (string->symbol "Consent.decision") "https://build.fhir.org/consent.html#Consent.decision" 'element))
(register-element! "Consent.provision" (fhir-spec (string->symbol "Consent.provision") "https://build.fhir.org/consent.html#Consent.provision" 'element))

(register-type! 'ConsentPolicyBasis (fhir-spec 'ConsentPolicyBasis "https://build.fhir.org/consent.html#Consent.policyBasis" 'type)
  #:schema (type-schema 'ConsentPolicyBasis #f 'BackboneElement "https://build.fhir.org/consent.html#Consent.policyBasis"
             (list
    (schema-field 'reference 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.policyBasis.reference" #f)
    (schema-field 'uri 0 1 (vector 'prim "uri") #f "https://build.fhir.org/consent.html#Consent.policyBasis.uri" #f)
             ) #f #f))
(register-element! "Consent.policyBasis.reference" (fhir-spec (string->symbol "Consent.policyBasis.reference") "https://build.fhir.org/consent.html#Consent.policyBasis.reference" 'element))
(register-element! "Consent.policyBasis.uri" (fhir-spec (string->symbol "Consent.policyBasis.uri") "https://build.fhir.org/consent.html#Consent.policyBasis.uri" 'element))

(register-type! 'ConsentVerification (fhir-spec 'ConsentVerification "https://build.fhir.org/consent.html#Consent.verification" 'type)
  #:schema (type-schema 'ConsentVerification #f 'BackboneElement "https://build.fhir.org/consent.html#Consent.verification"
             (list
    (schema-field 'verified 1 1 (vector 'prim "boolean") #f "https://build.fhir.org/consent.html#Consent.verification.verified" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/consent.html#Consent.verification.type" #f)
    (schema-field 'verifiedBy 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.verification.verifiedBy" #f)
    (schema-field 'verifiedWith 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.verification.verifiedWith" #f)
    (schema-field 'date 0 '* (vector 'prim "dateTime") #f "https://build.fhir.org/consent.html#Consent.verification.date" #f)
             ) #f #f))
(register-element! "Consent.verification.verified" (fhir-spec (string->symbol "Consent.verification.verified") "https://build.fhir.org/consent.html#Consent.verification.verified" 'element))
(register-element! "Consent.verification.type" (fhir-spec (string->symbol "Consent.verification.type") "https://build.fhir.org/consent.html#Consent.verification.type" 'element))
(register-element! "Consent.verification.verifiedBy" (fhir-spec (string->symbol "Consent.verification.verifiedBy") "https://build.fhir.org/consent.html#Consent.verification.verifiedBy" 'element))
(register-element! "Consent.verification.verifiedWith" (fhir-spec (string->symbol "Consent.verification.verifiedWith") "https://build.fhir.org/consent.html#Consent.verification.verifiedWith" 'element))
(register-element! "Consent.verification.date" (fhir-spec (string->symbol "Consent.verification.date") "https://build.fhir.org/consent.html#Consent.verification.date" 'element))

(register-type! 'ConsentProvision (fhir-spec 'ConsentProvision "https://build.fhir.org/consent.html#Consent.provision" 'type)
  #:schema (type-schema 'ConsentProvision #f 'BackboneElement "https://build.fhir.org/consent.html#Consent.provision"
             (list
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/consent.html#Consent.provision.period" #f)
    (schema-field 'actor 0 '* (vector 'type 'ConsentProvisionActor) #f "https://build.fhir.org/consent.html#Consent.provision.actor" #f)
    (schema-field 'action 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/consent.html#Consent.provision.action" #f)
    (schema-field 'securityLabel 0 '* (vector 'type 'Coding) #f "https://build.fhir.org/consent.html#Consent.provision.securityLabel" #f)
    (schema-field 'purpose 0 '* (vector 'type 'Coding) #f "https://build.fhir.org/consent.html#Consent.provision.purpose" #f)
    (schema-field 'documentType 0 '* (vector 'type 'Coding) #f "https://build.fhir.org/consent.html#Consent.provision.documentType" #f)
    (schema-field 'resourceType 0 '* (vector 'type 'Coding) #f "https://build.fhir.org/consent.html#Consent.provision.resourceType" #f)
    (schema-field 'code 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/consent.html#Consent.provision.code" #f)
    (schema-field 'dataPeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/consent.html#Consent.provision.dataPeriod" #f)
    (schema-field 'data 0 '* (vector 'type 'ConsentProvisionData) #f "https://build.fhir.org/consent.html#Consent.provision.data" #f)
    (schema-field 'expression 0 1 (vector 'type 'Expression) #f "https://build.fhir.org/consent.html#Consent.provision.expression" #f)
    (schema-field 'provision 0 '* (vector 'type 'ConsentProvision) #f "https://build.fhir.org/consent.html#Consent.provision.provision" #f)
             ) #f #f))
(register-element! "Consent.provision.period" (fhir-spec (string->symbol "Consent.provision.period") "https://build.fhir.org/consent.html#Consent.provision.period" 'element))
(register-element! "Consent.provision.actor" (fhir-spec (string->symbol "Consent.provision.actor") "https://build.fhir.org/consent.html#Consent.provision.actor" 'element))
(register-element! "Consent.provision.action" (fhir-spec (string->symbol "Consent.provision.action") "https://build.fhir.org/consent.html#Consent.provision.action" 'element))
(register-element! "Consent.provision.securityLabel" (fhir-spec (string->symbol "Consent.provision.securityLabel") "https://build.fhir.org/consent.html#Consent.provision.securityLabel" 'element))
(register-element! "Consent.provision.purpose" (fhir-spec (string->symbol "Consent.provision.purpose") "https://build.fhir.org/consent.html#Consent.provision.purpose" 'element))
(register-element! "Consent.provision.documentType" (fhir-spec (string->symbol "Consent.provision.documentType") "https://build.fhir.org/consent.html#Consent.provision.documentType" 'element))
(register-element! "Consent.provision.resourceType" (fhir-spec (string->symbol "Consent.provision.resourceType") "https://build.fhir.org/consent.html#Consent.provision.resourceType" 'element))
(register-element! "Consent.provision.code" (fhir-spec (string->symbol "Consent.provision.code") "https://build.fhir.org/consent.html#Consent.provision.code" 'element))
(register-element! "Consent.provision.dataPeriod" (fhir-spec (string->symbol "Consent.provision.dataPeriod") "https://build.fhir.org/consent.html#Consent.provision.dataPeriod" 'element))
(register-element! "Consent.provision.data" (fhir-spec (string->symbol "Consent.provision.data") "https://build.fhir.org/consent.html#Consent.provision.data" 'element))
(register-element! "Consent.provision.expression" (fhir-spec (string->symbol "Consent.provision.expression") "https://build.fhir.org/consent.html#Consent.provision.expression" 'element))
(register-element! "Consent.provision.provision" (fhir-spec (string->symbol "Consent.provision.provision") "https://build.fhir.org/consent.html#Consent.provision.provision" 'element))

(register-type! 'ConsentProvisionActor (fhir-spec 'ConsentProvisionActor "https://build.fhir.org/consent.html#Consent.provision.actor" 'type)
  #:schema (type-schema 'ConsentProvisionActor #f 'BackboneElement "https://build.fhir.org/consent.html#Consent.provision.actor"
             (list
    (schema-field 'role 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/consent.html#Consent.provision.actor.role" #f)
    (schema-field 'reference 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.provision.actor.reference" #f)
             ) #f #f))
(register-element! "Consent.provision.actor.role" (fhir-spec (string->symbol "Consent.provision.actor.role") "https://build.fhir.org/consent.html#Consent.provision.actor.role" 'element))
(register-element! "Consent.provision.actor.reference" (fhir-spec (string->symbol "Consent.provision.actor.reference") "https://build.fhir.org/consent.html#Consent.provision.actor.reference" 'element))

(register-type! 'ConsentProvisionData (fhir-spec 'ConsentProvisionData "https://build.fhir.org/consent.html#Consent.provision.data" 'type)
  #:schema (type-schema 'ConsentProvisionData #f 'BackboneElement "https://build.fhir.org/consent.html#Consent.provision.data"
             (list
    (schema-field 'meaning 1 1 (vector 'prim "code") #f "https://build.fhir.org/consent.html#Consent.provision.data.meaning" #f)
    (schema-field 'reference 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/consent.html#Consent.provision.data.reference" #f)
             ) #f #f))
(register-element! "Consent.provision.data.meaning" (fhir-spec (string->symbol "Consent.provision.data.meaning") "https://build.fhir.org/consent.html#Consent.provision.data.meaning" 'element))
(register-element! "Consent.provision.data.reference" (fhir-spec (string->symbol "Consent.provision.data.reference") "https://build.fhir.org/consent.html#Consent.provision.data.reference" 'element))

