#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Contract (fhir-spec 'Contract "https://build.fhir.org/contract.html#Contract" 'type)
  #:schema (type-schema 'Contract #f 'DomainResource "https://build.fhir.org/contract.html#Contract"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/contract.html#Contract.identifier" #f)
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/contract.html#Contract.url" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.version" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://build.fhir.org/contract.html#Contract.status" #f)
    (schema-field 'legalState 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.legalState" #f)
    (schema-field 'instantiatesCanonical 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 1 (vector 'prim "uri") #f "https://build.fhir.org/contract.html#Contract.instantiatesUri" #f)
    (schema-field 'contentDerivative 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.contentDerivative" #f)
    (schema-field 'issued 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/contract.html#Contract.issued" #f)
    (schema-field 'applies 0 1 (vector 'type 'Period) #f "https://build.fhir.org/contract.html#Contract.applies" #f)
    (schema-field 'expirationType 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.expirationType" #f)
    (schema-field 'subject 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.subject" #f)
    (schema-field 'authority 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.authority" #f)
    (schema-field 'domain 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.domain" #f)
    (schema-field 'site 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.site" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.title" #f)
    (schema-field 'subtitle 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.subtitle" #f)
    (schema-field 'alias 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.alias" #f)
    (schema-field 'author 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.author" #f)
    (schema-field 'scope 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.scope" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.type" #f)
    (schema-field 'subType 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.subType" #f)
    (schema-field 'contentDefinition 0 1 (vector 'type 'ContractContentDefinition) #f "https://build.fhir.org/contract.html#Contract.contentDefinition" #f)
    (schema-field 'term 0 '* (vector 'type 'ContractTerm) #f "https://build.fhir.org/contract.html#Contract.term" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.supportingInfo" #f)
    (schema-field 'relevantHistory 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.relevantHistory" #f)
    (schema-field 'signer 0 '* (vector 'type 'ContractSigner) #f "https://build.fhir.org/contract.html#Contract.signer" #f)
    (schema-field 'friendly 0 '* (vector 'type 'ContractFriendly) #f "https://build.fhir.org/contract.html#Contract.friendly" #f)
    (schema-field 'legal 0 '* (vector 'type 'ContractLegal) #f "https://build.fhir.org/contract.html#Contract.legal" #f)
    (schema-field 'rule 0 '* (vector 'type 'ContractRule) #f "https://build.fhir.org/contract.html#Contract.rule" #f)
    (schema-field 'topicCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'topic "https://build.fhir.org/contract.html#Contract.topic[x]" #f)
    (schema-field 'topicReference 0 1 (vector 'type 'Reference) 'topic "https://build.fhir.org/contract.html#Contract.topic[x]" #f)
    (schema-field 'legallyBindingAttachment 0 1 (vector 'type 'Attachment) 'legallyBinding "https://build.fhir.org/contract.html#Contract.legallyBinding[x]" #f)
    (schema-field 'legallyBindingReference 0 1 (vector 'type 'Reference) 'legallyBinding "https://build.fhir.org/contract.html#Contract.legallyBinding[x]" #f)
             ) #f #f))
(register-element! "Contract.identifier" (fhir-spec (string->symbol "Contract.identifier") "https://build.fhir.org/contract.html#Contract.identifier" 'element))
(register-element! "Contract.url" (fhir-spec (string->symbol "Contract.url") "https://build.fhir.org/contract.html#Contract.url" 'element))
(register-element! "Contract.version" (fhir-spec (string->symbol "Contract.version") "https://build.fhir.org/contract.html#Contract.version" 'element))
(register-element! "Contract.status" (fhir-spec (string->symbol "Contract.status") "https://build.fhir.org/contract.html#Contract.status" 'element))
(register-element! "Contract.legalState" (fhir-spec (string->symbol "Contract.legalState") "https://build.fhir.org/contract.html#Contract.legalState" 'element))
(register-element! "Contract.instantiatesCanonical" (fhir-spec (string->symbol "Contract.instantiatesCanonical") "https://build.fhir.org/contract.html#Contract.instantiatesCanonical" 'element))
(register-element! "Contract.instantiatesUri" (fhir-spec (string->symbol "Contract.instantiatesUri") "https://build.fhir.org/contract.html#Contract.instantiatesUri" 'element))
(register-element! "Contract.contentDerivative" (fhir-spec (string->symbol "Contract.contentDerivative") "https://build.fhir.org/contract.html#Contract.contentDerivative" 'element))
(register-element! "Contract.issued" (fhir-spec (string->symbol "Contract.issued") "https://build.fhir.org/contract.html#Contract.issued" 'element))
(register-element! "Contract.applies" (fhir-spec (string->symbol "Contract.applies") "https://build.fhir.org/contract.html#Contract.applies" 'element))
(register-element! "Contract.expirationType" (fhir-spec (string->symbol "Contract.expirationType") "https://build.fhir.org/contract.html#Contract.expirationType" 'element))
(register-element! "Contract.subject" (fhir-spec (string->symbol "Contract.subject") "https://build.fhir.org/contract.html#Contract.subject" 'element))
(register-element! "Contract.authority" (fhir-spec (string->symbol "Contract.authority") "https://build.fhir.org/contract.html#Contract.authority" 'element))
(register-element! "Contract.domain" (fhir-spec (string->symbol "Contract.domain") "https://build.fhir.org/contract.html#Contract.domain" 'element))
(register-element! "Contract.site" (fhir-spec (string->symbol "Contract.site") "https://build.fhir.org/contract.html#Contract.site" 'element))
(register-element! "Contract.name" (fhir-spec (string->symbol "Contract.name") "https://build.fhir.org/contract.html#Contract.name" 'element))
(register-element! "Contract.title" (fhir-spec (string->symbol "Contract.title") "https://build.fhir.org/contract.html#Contract.title" 'element))
(register-element! "Contract.subtitle" (fhir-spec (string->symbol "Contract.subtitle") "https://build.fhir.org/contract.html#Contract.subtitle" 'element))
(register-element! "Contract.alias" (fhir-spec (string->symbol "Contract.alias") "https://build.fhir.org/contract.html#Contract.alias" 'element))
(register-element! "Contract.author" (fhir-spec (string->symbol "Contract.author") "https://build.fhir.org/contract.html#Contract.author" 'element))
(register-element! "Contract.scope" (fhir-spec (string->symbol "Contract.scope") "https://build.fhir.org/contract.html#Contract.scope" 'element))
(register-element! "Contract.type" (fhir-spec (string->symbol "Contract.type") "https://build.fhir.org/contract.html#Contract.type" 'element))
(register-element! "Contract.subType" (fhir-spec (string->symbol "Contract.subType") "https://build.fhir.org/contract.html#Contract.subType" 'element))
(register-element! "Contract.contentDefinition" (fhir-spec (string->symbol "Contract.contentDefinition") "https://build.fhir.org/contract.html#Contract.contentDefinition" 'element))
(register-element! "Contract.term" (fhir-spec (string->symbol "Contract.term") "https://build.fhir.org/contract.html#Contract.term" 'element))
(register-element! "Contract.supportingInfo" (fhir-spec (string->symbol "Contract.supportingInfo") "https://build.fhir.org/contract.html#Contract.supportingInfo" 'element))
(register-element! "Contract.relevantHistory" (fhir-spec (string->symbol "Contract.relevantHistory") "https://build.fhir.org/contract.html#Contract.relevantHistory" 'element))
(register-element! "Contract.signer" (fhir-spec (string->symbol "Contract.signer") "https://build.fhir.org/contract.html#Contract.signer" 'element))
(register-element! "Contract.friendly" (fhir-spec (string->symbol "Contract.friendly") "https://build.fhir.org/contract.html#Contract.friendly" 'element))
(register-element! "Contract.legal" (fhir-spec (string->symbol "Contract.legal") "https://build.fhir.org/contract.html#Contract.legal" 'element))
(register-element! "Contract.rule" (fhir-spec (string->symbol "Contract.rule") "https://build.fhir.org/contract.html#Contract.rule" 'element))
(register-element! "Contract.topic[x]" (fhir-spec (string->symbol "Contract.topic[x]") "https://build.fhir.org/contract.html#Contract.topic[x]" 'element))
(register-element! "Contract.topic[x]" (fhir-spec (string->symbol "Contract.topic[x]") "https://build.fhir.org/contract.html#Contract.topic[x]" 'element))
(register-element! "Contract.legallyBinding[x]" (fhir-spec (string->symbol "Contract.legallyBinding[x]") "https://build.fhir.org/contract.html#Contract.legallyBinding[x]" 'element))
(register-element! "Contract.legallyBinding[x]" (fhir-spec (string->symbol "Contract.legallyBinding[x]") "https://build.fhir.org/contract.html#Contract.legallyBinding[x]" 'element))

(register-type! 'ContractContentDefinition (fhir-spec 'ContractContentDefinition "https://build.fhir.org/contract.html#Contract.contentDefinition" 'type)
  #:schema (type-schema 'ContractContentDefinition #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.contentDefinition"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.contentDefinition.type" #f)
    (schema-field 'subType 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.contentDefinition.subType" #f)
    (schema-field 'publisher 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.contentDefinition.publisher" #f)
    (schema-field 'publicationDate 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/contract.html#Contract.contentDefinition.publicationDate" #f)
    (schema-field 'publicationStatus 1 1 (vector 'prim "code") #f "https://build.fhir.org/contract.html#Contract.contentDefinition.publicationStatus" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/contract.html#Contract.contentDefinition.copyright" #f)
             ) #f #f))
(register-element! "Contract.contentDefinition.type" (fhir-spec (string->symbol "Contract.contentDefinition.type") "https://build.fhir.org/contract.html#Contract.contentDefinition.type" 'element))
(register-element! "Contract.contentDefinition.subType" (fhir-spec (string->symbol "Contract.contentDefinition.subType") "https://build.fhir.org/contract.html#Contract.contentDefinition.subType" 'element))
(register-element! "Contract.contentDefinition.publisher" (fhir-spec (string->symbol "Contract.contentDefinition.publisher") "https://build.fhir.org/contract.html#Contract.contentDefinition.publisher" 'element))
(register-element! "Contract.contentDefinition.publicationDate" (fhir-spec (string->symbol "Contract.contentDefinition.publicationDate") "https://build.fhir.org/contract.html#Contract.contentDefinition.publicationDate" 'element))
(register-element! "Contract.contentDefinition.publicationStatus" (fhir-spec (string->symbol "Contract.contentDefinition.publicationStatus") "https://build.fhir.org/contract.html#Contract.contentDefinition.publicationStatus" 'element))
(register-element! "Contract.contentDefinition.copyright" (fhir-spec (string->symbol "Contract.contentDefinition.copyright") "https://build.fhir.org/contract.html#Contract.contentDefinition.copyright" 'element))

(register-type! 'ContractTerm (fhir-spec 'ContractTerm "https://build.fhir.org/contract.html#Contract.term" 'type)
  #:schema (type-schema 'ContractTerm #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term"
             (list
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/contract.html#Contract.term.identifier" #f)
    (schema-field 'issued 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/contract.html#Contract.term.issued" #f)
    (schema-field 'applies 0 1 (vector 'type 'Period) #f "https://build.fhir.org/contract.html#Contract.term.applies" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.type" #f)
    (schema-field 'subType 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.subType" #f)
    (schema-field 'text 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/contract.html#Contract.term.text" #f)
    (schema-field 'securityLabel 0 '* (vector 'type 'ContractTermSecurityLabel) #f "https://build.fhir.org/contract.html#Contract.term.securityLabel" #f)
    (schema-field 'offer 1 1 (vector 'type 'ContractTermOffer) #f "https://build.fhir.org/contract.html#Contract.term.offer" #f)
    (schema-field 'asset 0 '* (vector 'type 'ContractTermAsset) #f "https://build.fhir.org/contract.html#Contract.term.asset" #f)
    (schema-field 'action 0 '* (vector 'type 'ContractTermAction) #f "https://build.fhir.org/contract.html#Contract.term.action" #f)
    (schema-field 'group 0 '* (vector 'type 'ContractTerm) #f "https://build.fhir.org/contract.html#Contract.term.group" #f)
    (schema-field 'topicCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'topic "https://build.fhir.org/contract.html#Contract.term.topic[x]" #f)
    (schema-field 'topicReference 0 1 (vector 'type 'Reference) 'topic "https://build.fhir.org/contract.html#Contract.term.topic[x]" #f)
             ) #f #f))
(register-element! "Contract.term.identifier" (fhir-spec (string->symbol "Contract.term.identifier") "https://build.fhir.org/contract.html#Contract.term.identifier" 'element))
(register-element! "Contract.term.issued" (fhir-spec (string->symbol "Contract.term.issued") "https://build.fhir.org/contract.html#Contract.term.issued" 'element))
(register-element! "Contract.term.applies" (fhir-spec (string->symbol "Contract.term.applies") "https://build.fhir.org/contract.html#Contract.term.applies" 'element))
(register-element! "Contract.term.type" (fhir-spec (string->symbol "Contract.term.type") "https://build.fhir.org/contract.html#Contract.term.type" 'element))
(register-element! "Contract.term.subType" (fhir-spec (string->symbol "Contract.term.subType") "https://build.fhir.org/contract.html#Contract.term.subType" 'element))
(register-element! "Contract.term.text" (fhir-spec (string->symbol "Contract.term.text") "https://build.fhir.org/contract.html#Contract.term.text" 'element))
(register-element! "Contract.term.securityLabel" (fhir-spec (string->symbol "Contract.term.securityLabel") "https://build.fhir.org/contract.html#Contract.term.securityLabel" 'element))
(register-element! "Contract.term.offer" (fhir-spec (string->symbol "Contract.term.offer") "https://build.fhir.org/contract.html#Contract.term.offer" 'element))
(register-element! "Contract.term.asset" (fhir-spec (string->symbol "Contract.term.asset") "https://build.fhir.org/contract.html#Contract.term.asset" 'element))
(register-element! "Contract.term.action" (fhir-spec (string->symbol "Contract.term.action") "https://build.fhir.org/contract.html#Contract.term.action" 'element))
(register-element! "Contract.term.group" (fhir-spec (string->symbol "Contract.term.group") "https://build.fhir.org/contract.html#Contract.term.group" 'element))
(register-element! "Contract.term.topic[x]" (fhir-spec (string->symbol "Contract.term.topic[x]") "https://build.fhir.org/contract.html#Contract.term.topic[x]" 'element))
(register-element! "Contract.term.topic[x]" (fhir-spec (string->symbol "Contract.term.topic[x]") "https://build.fhir.org/contract.html#Contract.term.topic[x]" 'element))

(register-type! 'ContractTermSecurityLabel (fhir-spec 'ContractTermSecurityLabel "https://build.fhir.org/contract.html#Contract.term.securityLabel" 'type)
  #:schema (type-schema 'ContractTermSecurityLabel #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.securityLabel"
             (list
    (schema-field 'number 0 '* (vector 'prim "unsignedInt") #f "https://build.fhir.org/contract.html#Contract.term.securityLabel.number" #f)
    (schema-field 'classification 1 1 (vector 'type 'Coding) #f "https://build.fhir.org/contract.html#Contract.term.securityLabel.classification" #f)
    (schema-field 'category 0 '* (vector 'type 'Coding) #f "https://build.fhir.org/contract.html#Contract.term.securityLabel.category" #f)
    (schema-field 'control 0 '* (vector 'type 'Coding) #f "https://build.fhir.org/contract.html#Contract.term.securityLabel.control" #f)
             ) #f #f))
(register-element! "Contract.term.securityLabel.number" (fhir-spec (string->symbol "Contract.term.securityLabel.number") "https://build.fhir.org/contract.html#Contract.term.securityLabel.number" 'element))
(register-element! "Contract.term.securityLabel.classification" (fhir-spec (string->symbol "Contract.term.securityLabel.classification") "https://build.fhir.org/contract.html#Contract.term.securityLabel.classification" 'element))
(register-element! "Contract.term.securityLabel.category" (fhir-spec (string->symbol "Contract.term.securityLabel.category") "https://build.fhir.org/contract.html#Contract.term.securityLabel.category" 'element))
(register-element! "Contract.term.securityLabel.control" (fhir-spec (string->symbol "Contract.term.securityLabel.control") "https://build.fhir.org/contract.html#Contract.term.securityLabel.control" 'element))

(register-type! 'ContractTermOffer (fhir-spec 'ContractTermOffer "https://build.fhir.org/contract.html#Contract.term.offer" 'type)
  #:schema (type-schema 'ContractTermOffer #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.offer"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/contract.html#Contract.term.offer.identifier" #f)
    (schema-field 'party 0 '* (vector 'type 'ContractTermOfferParty) #f "https://build.fhir.org/contract.html#Contract.term.offer.party" #f)
    (schema-field 'topic 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.offer.topic" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.offer.type" #f)
    (schema-field 'decision 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.offer.decision" #f)
    (schema-field 'decisionMode 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.offer.decisionMode" #f)
    (schema-field 'answer 0 '* (vector 'type 'ContractTermOfferAnswer) #f "https://build.fhir.org/contract.html#Contract.term.offer.answer" #f)
    (schema-field 'text 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.offer.text" #f)
    (schema-field 'linkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.offer.linkId" #f)
    (schema-field 'securityLabelNumber 0 '* (vector 'prim "unsignedInt") #f "https://build.fhir.org/contract.html#Contract.term.offer.securityLabelNumber" #f)
             ) #f #f))
(register-element! "Contract.term.offer.identifier" (fhir-spec (string->symbol "Contract.term.offer.identifier") "https://build.fhir.org/contract.html#Contract.term.offer.identifier" 'element))
(register-element! "Contract.term.offer.party" (fhir-spec (string->symbol "Contract.term.offer.party") "https://build.fhir.org/contract.html#Contract.term.offer.party" 'element))
(register-element! "Contract.term.offer.topic" (fhir-spec (string->symbol "Contract.term.offer.topic") "https://build.fhir.org/contract.html#Contract.term.offer.topic" 'element))
(register-element! "Contract.term.offer.type" (fhir-spec (string->symbol "Contract.term.offer.type") "https://build.fhir.org/contract.html#Contract.term.offer.type" 'element))
(register-element! "Contract.term.offer.decision" (fhir-spec (string->symbol "Contract.term.offer.decision") "https://build.fhir.org/contract.html#Contract.term.offer.decision" 'element))
(register-element! "Contract.term.offer.decisionMode" (fhir-spec (string->symbol "Contract.term.offer.decisionMode") "https://build.fhir.org/contract.html#Contract.term.offer.decisionMode" 'element))
(register-element! "Contract.term.offer.answer" (fhir-spec (string->symbol "Contract.term.offer.answer") "https://build.fhir.org/contract.html#Contract.term.offer.answer" 'element))
(register-element! "Contract.term.offer.text" (fhir-spec (string->symbol "Contract.term.offer.text") "https://build.fhir.org/contract.html#Contract.term.offer.text" 'element))
(register-element! "Contract.term.offer.linkId" (fhir-spec (string->symbol "Contract.term.offer.linkId") "https://build.fhir.org/contract.html#Contract.term.offer.linkId" 'element))
(register-element! "Contract.term.offer.securityLabelNumber" (fhir-spec (string->symbol "Contract.term.offer.securityLabelNumber") "https://build.fhir.org/contract.html#Contract.term.offer.securityLabelNumber" 'element))

(register-type! 'ContractTermOfferParty (fhir-spec 'ContractTermOfferParty "https://build.fhir.org/contract.html#Contract.term.offer.party" 'type)
  #:schema (type-schema 'ContractTermOfferParty #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.offer.party"
             (list
    (schema-field 'reference 1 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.offer.party.reference" #f)
    (schema-field 'role 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.offer.party.role" #f)
             ) #f #f))
(register-element! "Contract.term.offer.party.reference" (fhir-spec (string->symbol "Contract.term.offer.party.reference") "https://build.fhir.org/contract.html#Contract.term.offer.party.reference" 'element))
(register-element! "Contract.term.offer.party.role" (fhir-spec (string->symbol "Contract.term.offer.party.role") "https://build.fhir.org/contract.html#Contract.term.offer.party.role" 'element))

(register-type! 'ContractTermOfferAnswer (fhir-spec 'ContractTermOfferAnswer "https://build.fhir.org/contract.html#Contract.term.offer.answer" 'type)
  #:schema (type-schema 'ContractTermOfferAnswer #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.offer.answer"
             (list
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" #f)
             ) #f #f))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))
(register-element! "Contract.term.offer.answer.value[x]" (fhir-spec (string->symbol "Contract.term.offer.answer.value[x]") "https://build.fhir.org/contract.html#Contract.term.offer.answer.value[x]" 'element))

(register-type! 'ContractTermAsset (fhir-spec 'ContractTermAsset "https://build.fhir.org/contract.html#Contract.term.asset" 'type)
  #:schema (type-schema 'ContractTermAsset #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.asset"
             (list
    (schema-field 'scope 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.asset.scope" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.asset.type" #f)
    (schema-field 'typeReference 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.asset.typeReference" #f)
    (schema-field 'subtype 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.asset.subtype" #f)
    (schema-field 'relationship 0 1 (vector 'type 'Coding) #f "https://build.fhir.org/contract.html#Contract.term.asset.relationship" #f)
    (schema-field 'context 0 '* (vector 'type 'ContractTermAssetContext) #f "https://build.fhir.org/contract.html#Contract.term.asset.context" #f)
    (schema-field 'condition 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.asset.condition" #f)
    (schema-field 'periodType 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.asset.periodType" #f)
    (schema-field 'period 0 '* (vector 'type 'Period) #f "https://build.fhir.org/contract.html#Contract.term.asset.period" #f)
    (schema-field 'usePeriod 0 '* (vector 'type 'Period) #f "https://build.fhir.org/contract.html#Contract.term.asset.usePeriod" #f)
    (schema-field 'text 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.asset.text" #f)
    (schema-field 'linkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.asset.linkId" #f)
    (schema-field 'answer 0 '* (vector 'type 'ContractTermOfferAnswer) #f "https://build.fhir.org/contract.html#Contract.term.asset.answer" #f)
    (schema-field 'securityLabelNumber 0 '* (vector 'prim "unsignedInt") #f "https://build.fhir.org/contract.html#Contract.term.asset.securityLabelNumber" #f)
    (schema-field 'valuedItem 0 '* (vector 'type 'ContractTermAssetValuedItem) #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem" #f)
             ) #f #f))
(register-element! "Contract.term.asset.scope" (fhir-spec (string->symbol "Contract.term.asset.scope") "https://build.fhir.org/contract.html#Contract.term.asset.scope" 'element))
(register-element! "Contract.term.asset.type" (fhir-spec (string->symbol "Contract.term.asset.type") "https://build.fhir.org/contract.html#Contract.term.asset.type" 'element))
(register-element! "Contract.term.asset.typeReference" (fhir-spec (string->symbol "Contract.term.asset.typeReference") "https://build.fhir.org/contract.html#Contract.term.asset.typeReference" 'element))
(register-element! "Contract.term.asset.subtype" (fhir-spec (string->symbol "Contract.term.asset.subtype") "https://build.fhir.org/contract.html#Contract.term.asset.subtype" 'element))
(register-element! "Contract.term.asset.relationship" (fhir-spec (string->symbol "Contract.term.asset.relationship") "https://build.fhir.org/contract.html#Contract.term.asset.relationship" 'element))
(register-element! "Contract.term.asset.context" (fhir-spec (string->symbol "Contract.term.asset.context") "https://build.fhir.org/contract.html#Contract.term.asset.context" 'element))
(register-element! "Contract.term.asset.condition" (fhir-spec (string->symbol "Contract.term.asset.condition") "https://build.fhir.org/contract.html#Contract.term.asset.condition" 'element))
(register-element! "Contract.term.asset.periodType" (fhir-spec (string->symbol "Contract.term.asset.periodType") "https://build.fhir.org/contract.html#Contract.term.asset.periodType" 'element))
(register-element! "Contract.term.asset.period" (fhir-spec (string->symbol "Contract.term.asset.period") "https://build.fhir.org/contract.html#Contract.term.asset.period" 'element))
(register-element! "Contract.term.asset.usePeriod" (fhir-spec (string->symbol "Contract.term.asset.usePeriod") "https://build.fhir.org/contract.html#Contract.term.asset.usePeriod" 'element))
(register-element! "Contract.term.asset.text" (fhir-spec (string->symbol "Contract.term.asset.text") "https://build.fhir.org/contract.html#Contract.term.asset.text" 'element))
(register-element! "Contract.term.asset.linkId" (fhir-spec (string->symbol "Contract.term.asset.linkId") "https://build.fhir.org/contract.html#Contract.term.asset.linkId" 'element))
(register-element! "Contract.term.asset.answer" (fhir-spec (string->symbol "Contract.term.asset.answer") "https://build.fhir.org/contract.html#Contract.term.asset.answer" 'element))
(register-element! "Contract.term.asset.securityLabelNumber" (fhir-spec (string->symbol "Contract.term.asset.securityLabelNumber") "https://build.fhir.org/contract.html#Contract.term.asset.securityLabelNumber" 'element))
(register-element! "Contract.term.asset.valuedItem" (fhir-spec (string->symbol "Contract.term.asset.valuedItem") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem" 'element))

(register-type! 'ContractTermAssetContext (fhir-spec 'ContractTermAssetContext "https://build.fhir.org/contract.html#Contract.term.asset.context" 'type)
  #:schema (type-schema 'ContractTermAssetContext #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.asset.context"
             (list
    (schema-field 'reference 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.asset.context.reference" #f)
    (schema-field 'code 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.asset.context.code" #f)
    (schema-field 'text 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.asset.context.text" #f)
             ) #f #f))
(register-element! "Contract.term.asset.context.reference" (fhir-spec (string->symbol "Contract.term.asset.context.reference") "https://build.fhir.org/contract.html#Contract.term.asset.context.reference" 'element))
(register-element! "Contract.term.asset.context.code" (fhir-spec (string->symbol "Contract.term.asset.context.code") "https://build.fhir.org/contract.html#Contract.term.asset.context.code" 'element))
(register-element! "Contract.term.asset.context.text" (fhir-spec (string->symbol "Contract.term.asset.context.text") "https://build.fhir.org/contract.html#Contract.term.asset.context.text" 'element))

(register-type! 'ContractTermAssetValuedItem (fhir-spec 'ContractTermAssetValuedItem "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem" 'type)
  #:schema (type-schema 'ContractTermAssetValuedItem #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem"
             (list
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.identifier" #f)
    (schema-field 'effectiveTime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.effectiveTime" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.factor" #f)
    (schema-field 'points 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.points" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.net" #f)
    (schema-field 'payment 0 1 (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.payment" #f)
    (schema-field 'paymentDate 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.paymentDate" #f)
    (schema-field 'responsible 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.responsible" #f)
    (schema-field 'recipient 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.recipient" #f)
    (schema-field 'linkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.linkId" #f)
    (schema-field 'securityLabelNumber 0 '* (vector 'prim "unsignedInt") #f "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.securityLabelNumber" #f)
    (schema-field 'entityCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'entity "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.entity[x]" #f)
    (schema-field 'entityReference 0 1 (vector 'type 'Reference) 'entity "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.entity[x]" #f)
             ) #f #f))
(register-element! "Contract.term.asset.valuedItem.identifier" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.identifier") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.identifier" 'element))
(register-element! "Contract.term.asset.valuedItem.effectiveTime" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.effectiveTime") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.effectiveTime" 'element))
(register-element! "Contract.term.asset.valuedItem.quantity" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.quantity") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.quantity" 'element))
(register-element! "Contract.term.asset.valuedItem.unitPrice" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.unitPrice") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.unitPrice" 'element))
(register-element! "Contract.term.asset.valuedItem.factor" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.factor") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.factor" 'element))
(register-element! "Contract.term.asset.valuedItem.points" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.points") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.points" 'element))
(register-element! "Contract.term.asset.valuedItem.net" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.net") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.net" 'element))
(register-element! "Contract.term.asset.valuedItem.payment" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.payment") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.payment" 'element))
(register-element! "Contract.term.asset.valuedItem.paymentDate" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.paymentDate") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.paymentDate" 'element))
(register-element! "Contract.term.asset.valuedItem.responsible" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.responsible") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.responsible" 'element))
(register-element! "Contract.term.asset.valuedItem.recipient" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.recipient") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.recipient" 'element))
(register-element! "Contract.term.asset.valuedItem.linkId" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.linkId") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.linkId" 'element))
(register-element! "Contract.term.asset.valuedItem.securityLabelNumber" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.securityLabelNumber") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.securityLabelNumber" 'element))
(register-element! "Contract.term.asset.valuedItem.entity[x]" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.entity[x]") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.entity[x]" 'element))
(register-element! "Contract.term.asset.valuedItem.entity[x]" (fhir-spec (string->symbol "Contract.term.asset.valuedItem.entity[x]") "https://build.fhir.org/contract.html#Contract.term.asset.valuedItem.entity[x]" 'element))

(register-type! 'ContractTermAction (fhir-spec 'ContractTermAction "https://build.fhir.org/contract.html#Contract.term.action" 'type)
  #:schema (type-schema 'ContractTermAction #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.action"
             (list
    (schema-field 'doNotPerform 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/contract.html#Contract.term.action.doNotPerform" #f)
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.action.type" #f)
    (schema-field 'subject 0 '* (vector 'type 'ContractTermActionSubject) #f "https://build.fhir.org/contract.html#Contract.term.action.subject" #f)
    (schema-field 'intent 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.action.intent" #f)
    (schema-field 'linkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.action.linkId" #f)
    (schema-field 'status 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.action.status" #f)
    (schema-field 'context 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.action.context" #f)
    (schema-field 'contextLinkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.action.contextLinkId" #f)
    (schema-field 'requester 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.action.requester" #f)
    (schema-field 'requesterLinkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.action.requesterLinkId" #f)
    (schema-field 'performerType 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.action.performerType" #f)
    (schema-field 'performerRole 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.action.performerRole" #f)
    (schema-field 'performer 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.action.performer" #f)
    (schema-field 'performerLinkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.action.performerLinkId" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/contract.html#Contract.term.action.reason" #f)
    (schema-field 'reasonLinkId 0 '* (vector 'prim "string") #f "https://build.fhir.org/contract.html#Contract.term.action.reasonLinkId" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/contract.html#Contract.term.action.note" #f)
    (schema-field 'securityLabelNumber 0 '* (vector 'prim "unsignedInt") #f "https://build.fhir.org/contract.html#Contract.term.action.securityLabelNumber" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://build.fhir.org/contract.html#Contract.term.action.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://build.fhir.org/contract.html#Contract.term.action.occurrence[x]" #f)
    (schema-field 'occurrenceTiming 0 1 (vector 'type 'Timing) 'occurrence "https://build.fhir.org/contract.html#Contract.term.action.occurrence[x]" #f)
             ) #f #f))
(register-element! "Contract.term.action.doNotPerform" (fhir-spec (string->symbol "Contract.term.action.doNotPerform") "https://build.fhir.org/contract.html#Contract.term.action.doNotPerform" 'element))
(register-element! "Contract.term.action.type" (fhir-spec (string->symbol "Contract.term.action.type") "https://build.fhir.org/contract.html#Contract.term.action.type" 'element))
(register-element! "Contract.term.action.subject" (fhir-spec (string->symbol "Contract.term.action.subject") "https://build.fhir.org/contract.html#Contract.term.action.subject" 'element))
(register-element! "Contract.term.action.intent" (fhir-spec (string->symbol "Contract.term.action.intent") "https://build.fhir.org/contract.html#Contract.term.action.intent" 'element))
(register-element! "Contract.term.action.linkId" (fhir-spec (string->symbol "Contract.term.action.linkId") "https://build.fhir.org/contract.html#Contract.term.action.linkId" 'element))
(register-element! "Contract.term.action.status" (fhir-spec (string->symbol "Contract.term.action.status") "https://build.fhir.org/contract.html#Contract.term.action.status" 'element))
(register-element! "Contract.term.action.context" (fhir-spec (string->symbol "Contract.term.action.context") "https://build.fhir.org/contract.html#Contract.term.action.context" 'element))
(register-element! "Contract.term.action.contextLinkId" (fhir-spec (string->symbol "Contract.term.action.contextLinkId") "https://build.fhir.org/contract.html#Contract.term.action.contextLinkId" 'element))
(register-element! "Contract.term.action.requester" (fhir-spec (string->symbol "Contract.term.action.requester") "https://build.fhir.org/contract.html#Contract.term.action.requester" 'element))
(register-element! "Contract.term.action.requesterLinkId" (fhir-spec (string->symbol "Contract.term.action.requesterLinkId") "https://build.fhir.org/contract.html#Contract.term.action.requesterLinkId" 'element))
(register-element! "Contract.term.action.performerType" (fhir-spec (string->symbol "Contract.term.action.performerType") "https://build.fhir.org/contract.html#Contract.term.action.performerType" 'element))
(register-element! "Contract.term.action.performerRole" (fhir-spec (string->symbol "Contract.term.action.performerRole") "https://build.fhir.org/contract.html#Contract.term.action.performerRole" 'element))
(register-element! "Contract.term.action.performer" (fhir-spec (string->symbol "Contract.term.action.performer") "https://build.fhir.org/contract.html#Contract.term.action.performer" 'element))
(register-element! "Contract.term.action.performerLinkId" (fhir-spec (string->symbol "Contract.term.action.performerLinkId") "https://build.fhir.org/contract.html#Contract.term.action.performerLinkId" 'element))
(register-element! "Contract.term.action.reason" (fhir-spec (string->symbol "Contract.term.action.reason") "https://build.fhir.org/contract.html#Contract.term.action.reason" 'element))
(register-element! "Contract.term.action.reasonLinkId" (fhir-spec (string->symbol "Contract.term.action.reasonLinkId") "https://build.fhir.org/contract.html#Contract.term.action.reasonLinkId" 'element))
(register-element! "Contract.term.action.note" (fhir-spec (string->symbol "Contract.term.action.note") "https://build.fhir.org/contract.html#Contract.term.action.note" 'element))
(register-element! "Contract.term.action.securityLabelNumber" (fhir-spec (string->symbol "Contract.term.action.securityLabelNumber") "https://build.fhir.org/contract.html#Contract.term.action.securityLabelNumber" 'element))
(register-element! "Contract.term.action.occurrence[x]" (fhir-spec (string->symbol "Contract.term.action.occurrence[x]") "https://build.fhir.org/contract.html#Contract.term.action.occurrence[x]" 'element))
(register-element! "Contract.term.action.occurrence[x]" (fhir-spec (string->symbol "Contract.term.action.occurrence[x]") "https://build.fhir.org/contract.html#Contract.term.action.occurrence[x]" 'element))
(register-element! "Contract.term.action.occurrence[x]" (fhir-spec (string->symbol "Contract.term.action.occurrence[x]") "https://build.fhir.org/contract.html#Contract.term.action.occurrence[x]" 'element))

(register-type! 'ContractTermActionSubject (fhir-spec 'ContractTermActionSubject "https://build.fhir.org/contract.html#Contract.term.action.subject" 'type)
  #:schema (type-schema 'ContractTermActionSubject #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.term.action.subject"
             (list
    (schema-field 'reference 1 '* (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.term.action.subject.reference" #f)
    (schema-field 'role 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/contract.html#Contract.term.action.subject.role" #f)
             ) #f #f))
(register-element! "Contract.term.action.subject.reference" (fhir-spec (string->symbol "Contract.term.action.subject.reference") "https://build.fhir.org/contract.html#Contract.term.action.subject.reference" 'element))
(register-element! "Contract.term.action.subject.role" (fhir-spec (string->symbol "Contract.term.action.subject.role") "https://build.fhir.org/contract.html#Contract.term.action.subject.role" 'element))

(register-type! 'ContractSigner (fhir-spec 'ContractSigner "https://build.fhir.org/contract.html#Contract.signer" 'type)
  #:schema (type-schema 'ContractSigner #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.signer"
             (list
    (schema-field 'type 1 1 (vector 'type 'Coding) #f "https://build.fhir.org/contract.html#Contract.signer.type" #f)
    (schema-field 'party 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/contract.html#Contract.signer.party" #f)
    (schema-field 'signature 1 '* (vector 'type 'Signature) #f "https://build.fhir.org/contract.html#Contract.signer.signature" #f)
             ) #f #f))
(register-element! "Contract.signer.type" (fhir-spec (string->symbol "Contract.signer.type") "https://build.fhir.org/contract.html#Contract.signer.type" 'element))
(register-element! "Contract.signer.party" (fhir-spec (string->symbol "Contract.signer.party") "https://build.fhir.org/contract.html#Contract.signer.party" 'element))
(register-element! "Contract.signer.signature" (fhir-spec (string->symbol "Contract.signer.signature") "https://build.fhir.org/contract.html#Contract.signer.signature" 'element))

(register-type! 'ContractFriendly (fhir-spec 'ContractFriendly "https://build.fhir.org/contract.html#Contract.friendly" 'type)
  #:schema (type-schema 'ContractFriendly #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.friendly"
             (list
    (schema-field 'contentAttachment 0 1 (vector 'type 'Attachment) 'content "https://build.fhir.org/contract.html#Contract.friendly.content[x]" #f)
    (schema-field 'contentReference 0 1 (vector 'type 'Reference) 'content "https://build.fhir.org/contract.html#Contract.friendly.content[x]" #f)
             ) #f #f))
(register-element! "Contract.friendly.content[x]" (fhir-spec (string->symbol "Contract.friendly.content[x]") "https://build.fhir.org/contract.html#Contract.friendly.content[x]" 'element))
(register-element! "Contract.friendly.content[x]" (fhir-spec (string->symbol "Contract.friendly.content[x]") "https://build.fhir.org/contract.html#Contract.friendly.content[x]" 'element))

(register-type! 'ContractLegal (fhir-spec 'ContractLegal "https://build.fhir.org/contract.html#Contract.legal" 'type)
  #:schema (type-schema 'ContractLegal #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.legal"
             (list
    (schema-field 'contentAttachment 0 1 (vector 'type 'Attachment) 'content "https://build.fhir.org/contract.html#Contract.legal.content[x]" #f)
    (schema-field 'contentReference 0 1 (vector 'type 'Reference) 'content "https://build.fhir.org/contract.html#Contract.legal.content[x]" #f)
             ) #f #f))
(register-element! "Contract.legal.content[x]" (fhir-spec (string->symbol "Contract.legal.content[x]") "https://build.fhir.org/contract.html#Contract.legal.content[x]" 'element))
(register-element! "Contract.legal.content[x]" (fhir-spec (string->symbol "Contract.legal.content[x]") "https://build.fhir.org/contract.html#Contract.legal.content[x]" 'element))

(register-type! 'ContractRule (fhir-spec 'ContractRule "https://build.fhir.org/contract.html#Contract.rule" 'type)
  #:schema (type-schema 'ContractRule #f 'BackboneElement "https://build.fhir.org/contract.html#Contract.rule"
             (list
    (schema-field 'contentAttachment 0 1 (vector 'type 'Attachment) 'content "https://build.fhir.org/contract.html#Contract.rule.content[x]" #f)
    (schema-field 'contentReference 0 1 (vector 'type 'Reference) 'content "https://build.fhir.org/contract.html#Contract.rule.content[x]" #f)
             ) #f #f))
(register-element! "Contract.rule.content[x]" (fhir-spec (string->symbol "Contract.rule.content[x]") "https://build.fhir.org/contract.html#Contract.rule.content[x]" 'element))
(register-element! "Contract.rule.content[x]" (fhir-spec (string->symbol "Contract.rule.content[x]") "https://build.fhir.org/contract.html#Contract.rule.content[x]" 'element))

