#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Coverage (fhir-spec 'Coverage "https://build.fhir.org/coverage.html#Coverage" 'type)
  #:schema (type-schema 'Coverage #f 'DomainResource "https://build.fhir.org/coverage.html#Coverage"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/coverage.html#Coverage.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/coverage.html#Coverage.status" #f)
    (schema-field 'statusReason 0 1 (vector 'prim "string") #f "https://build.fhir.org/coverage.html#Coverage.statusReason" #f)
    (schema-field 'kind 1 1 (vector 'prim "code") #f "https://build.fhir.org/coverage.html#Coverage.kind" #f)
    (schema-field 'paymentBy 0 '* (vector 'type 'CoveragePaymentBy) #f "https://build.fhir.org/coverage.html#Coverage.paymentBy" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.type" #f)
    (schema-field 'policyHolder 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/coverage.html#Coverage.policyHolder" #f)
    (schema-field 'subscriber 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/coverage.html#Coverage.subscriber" #f)
    (schema-field 'subscriberId 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/coverage.html#Coverage.subscriberId" #f)
    (schema-field 'beneficiary 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/coverage.html#Coverage.beneficiary" #f)
    (schema-field 'dependent 0 1 (vector 'prim "string") #f "https://build.fhir.org/coverage.html#Coverage.dependent" #f)
    (schema-field 'relationship 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.relationship" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/coverage.html#Coverage.period" #f)
    (schema-field 'insurer 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/coverage.html#Coverage.insurer" #f)
    (schema-field 'class 0 '* (vector 'type 'CoverageClass) #f "https://build.fhir.org/coverage.html#Coverage.class" #f)
    (schema-field 'order 0 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/coverage.html#Coverage.order" #f)
    (schema-field 'network 0 1 (vector 'prim "string") #f "https://build.fhir.org/coverage.html#Coverage.network" #f)
    (schema-field 'costToBeneficiary 0 '* (vector 'type 'CoverageCostToBeneficiary) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary" #f)
    (schema-field 'subrogation 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/coverage.html#Coverage.subrogation" #f)
    (schema-field 'contract 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/coverage.html#Coverage.contract" #f)
    (schema-field 'insurancePlan 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/coverage.html#Coverage.insurancePlan" #f)
             ) #f #f))
(register-element! "Coverage.identifier" (fhir-spec (string->symbol "Coverage.identifier") "https://build.fhir.org/coverage.html#Coverage.identifier" 'element))
(register-element! "Coverage.status" (fhir-spec (string->symbol "Coverage.status") "https://build.fhir.org/coverage.html#Coverage.status" 'element))
(register-element! "Coverage.statusReason" (fhir-spec (string->symbol "Coverage.statusReason") "https://build.fhir.org/coverage.html#Coverage.statusReason" 'element))
(register-element! "Coverage.kind" (fhir-spec (string->symbol "Coverage.kind") "https://build.fhir.org/coverage.html#Coverage.kind" 'element))
(register-element! "Coverage.paymentBy" (fhir-spec (string->symbol "Coverage.paymentBy") "https://build.fhir.org/coverage.html#Coverage.paymentBy" 'element))
(register-element! "Coverage.type" (fhir-spec (string->symbol "Coverage.type") "https://build.fhir.org/coverage.html#Coverage.type" 'element))
(register-element! "Coverage.policyHolder" (fhir-spec (string->symbol "Coverage.policyHolder") "https://build.fhir.org/coverage.html#Coverage.policyHolder" 'element))
(register-element! "Coverage.subscriber" (fhir-spec (string->symbol "Coverage.subscriber") "https://build.fhir.org/coverage.html#Coverage.subscriber" 'element))
(register-element! "Coverage.subscriberId" (fhir-spec (string->symbol "Coverage.subscriberId") "https://build.fhir.org/coverage.html#Coverage.subscriberId" 'element))
(register-element! "Coverage.beneficiary" (fhir-spec (string->symbol "Coverage.beneficiary") "https://build.fhir.org/coverage.html#Coverage.beneficiary" 'element))
(register-element! "Coverage.dependent" (fhir-spec (string->symbol "Coverage.dependent") "https://build.fhir.org/coverage.html#Coverage.dependent" 'element))
(register-element! "Coverage.relationship" (fhir-spec (string->symbol "Coverage.relationship") "https://build.fhir.org/coverage.html#Coverage.relationship" 'element))
(register-element! "Coverage.period" (fhir-spec (string->symbol "Coverage.period") "https://build.fhir.org/coverage.html#Coverage.period" 'element))
(register-element! "Coverage.insurer" (fhir-spec (string->symbol "Coverage.insurer") "https://build.fhir.org/coverage.html#Coverage.insurer" 'element))
(register-element! "Coverage.class" (fhir-spec (string->symbol "Coverage.class") "https://build.fhir.org/coverage.html#Coverage.class" 'element))
(register-element! "Coverage.order" (fhir-spec (string->symbol "Coverage.order") "https://build.fhir.org/coverage.html#Coverage.order" 'element))
(register-element! "Coverage.network" (fhir-spec (string->symbol "Coverage.network") "https://build.fhir.org/coverage.html#Coverage.network" 'element))
(register-element! "Coverage.costToBeneficiary" (fhir-spec (string->symbol "Coverage.costToBeneficiary") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary" 'element))
(register-element! "Coverage.subrogation" (fhir-spec (string->symbol "Coverage.subrogation") "https://build.fhir.org/coverage.html#Coverage.subrogation" 'element))
(register-element! "Coverage.contract" (fhir-spec (string->symbol "Coverage.contract") "https://build.fhir.org/coverage.html#Coverage.contract" 'element))
(register-element! "Coverage.insurancePlan" (fhir-spec (string->symbol "Coverage.insurancePlan") "https://build.fhir.org/coverage.html#Coverage.insurancePlan" 'element))

(register-type! 'CoveragePaymentBy (fhir-spec 'CoveragePaymentBy "https://build.fhir.org/coverage.html#Coverage.paymentBy" 'type)
  #:schema (type-schema 'CoveragePaymentBy #f 'BackboneElement "https://build.fhir.org/coverage.html#Coverage.paymentBy"
             (list
    (schema-field 'party 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/coverage.html#Coverage.paymentBy.party" #f)
    (schema-field 'responsibility 0 1 (vector 'prim "string") #f "https://build.fhir.org/coverage.html#Coverage.paymentBy.responsibility" #f)
             ) #f #f))
(register-element! "Coverage.paymentBy.party" (fhir-spec (string->symbol "Coverage.paymentBy.party") "https://build.fhir.org/coverage.html#Coverage.paymentBy.party" 'element))
(register-element! "Coverage.paymentBy.responsibility" (fhir-spec (string->symbol "Coverage.paymentBy.responsibility") "https://build.fhir.org/coverage.html#Coverage.paymentBy.responsibility" 'element))

(register-type! 'CoverageClass (fhir-spec 'CoverageClass "https://build.fhir.org/coverage.html#Coverage.class" 'type)
  #:schema (type-schema 'CoverageClass #f 'BackboneElement "https://build.fhir.org/coverage.html#Coverage.class"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.class.type" #f)
    (schema-field 'value 1 1 (vector 'type 'Identifier) #f "https://build.fhir.org/coverage.html#Coverage.class.value" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/coverage.html#Coverage.class.name" #f)
             ) #f #f))
(register-element! "Coverage.class.type" (fhir-spec (string->symbol "Coverage.class.type") "https://build.fhir.org/coverage.html#Coverage.class.type" 'element))
(register-element! "Coverage.class.value" (fhir-spec (string->symbol "Coverage.class.value") "https://build.fhir.org/coverage.html#Coverage.class.value" 'element))
(register-element! "Coverage.class.name" (fhir-spec (string->symbol "Coverage.class.name") "https://build.fhir.org/coverage.html#Coverage.class.name" 'element))

(register-type! 'CoverageCostToBeneficiary (fhir-spec 'CoverageCostToBeneficiary "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary" 'type)
  #:schema (type-schema 'CoverageCostToBeneficiary #f 'BackboneElement "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.type" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.category" #f)
    (schema-field 'network 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.network" #f)
    (schema-field 'unit 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.unit" #f)
    (schema-field 'term 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.term" #f)
    (schema-field 'exception 0 '* (vector 'type 'CoverageCostToBeneficiaryException) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.value[x]" #f)
             ) #f #f))
(register-element! "Coverage.costToBeneficiary.type" (fhir-spec (string->symbol "Coverage.costToBeneficiary.type") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.type" 'element))
(register-element! "Coverage.costToBeneficiary.category" (fhir-spec (string->symbol "Coverage.costToBeneficiary.category") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.category" 'element))
(register-element! "Coverage.costToBeneficiary.network" (fhir-spec (string->symbol "Coverage.costToBeneficiary.network") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.network" 'element))
(register-element! "Coverage.costToBeneficiary.unit" (fhir-spec (string->symbol "Coverage.costToBeneficiary.unit") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.unit" 'element))
(register-element! "Coverage.costToBeneficiary.term" (fhir-spec (string->symbol "Coverage.costToBeneficiary.term") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.term" 'element))
(register-element! "Coverage.costToBeneficiary.exception" (fhir-spec (string->symbol "Coverage.costToBeneficiary.exception") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception" 'element))
(register-element! "Coverage.costToBeneficiary.value[x]" (fhir-spec (string->symbol "Coverage.costToBeneficiary.value[x]") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.value[x]" 'element))
(register-element! "Coverage.costToBeneficiary.value[x]" (fhir-spec (string->symbol "Coverage.costToBeneficiary.value[x]") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.value[x]" 'element))

(register-type! 'CoverageCostToBeneficiaryException (fhir-spec 'CoverageCostToBeneficiaryException "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception" 'type)
  #:schema (type-schema 'CoverageCostToBeneficiaryException #f 'BackboneElement "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception.type" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception.period" #f)
             ) #f #f))
(register-element! "Coverage.costToBeneficiary.exception.type" (fhir-spec (string->symbol "Coverage.costToBeneficiary.exception.type") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception.type" 'element))
(register-element! "Coverage.costToBeneficiary.exception.period" (fhir-spec (string->symbol "Coverage.costToBeneficiary.exception.period") "https://build.fhir.org/coverage.html#Coverage.costToBeneficiary.exception.period" 'element))

