#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'DeviceRequest (fhir-spec 'DeviceRequest "https://build.fhir.org/devicerequest.html#DeviceRequest" 'type)
  #:schema (type-schema 'DeviceRequest #f 'DomainResource "https://build.fhir.org/devicerequest.html#DeviceRequest"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.basedOn" #f)
    (schema-field 'replaces 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.replaces" #f)
    (schema-field 'groupIdentifier 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.groupIdentifier" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://build.fhir.org/devicerequest.html#DeviceRequest.status" #f)
    (schema-field 'intent 1 1 (vector 'prim "code") #f "https://build.fhir.org/devicerequest.html#DeviceRequest.intent" #f)
    (schema-field 'priority 0 1 (vector 'prim "code") #f "https://build.fhir.org/devicerequest.html#DeviceRequest.priority" #f)
    (schema-field 'doNotPerform 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/devicerequest.html#DeviceRequest.doNotPerform" #f)
    (schema-field 'quantity 0 1 (vector 'prim "integer") #f "https://build.fhir.org/devicerequest.html#DeviceRequest.quantity" #f)
    (schema-field 'parameter 0 '* (vector 'type 'DeviceRequestParameter) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.encounter" #f)
    (schema-field 'authoredOn 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/devicerequest.html#DeviceRequest.authoredOn" #f)
    (schema-field 'requester 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.requester" #f)
    (schema-field 'performer 0 1 (vector 'type 'CodeableReference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.performer" #f)
    (schema-field 'location 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.location" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.reason" #f)
    (schema-field 'asNeeded 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/devicerequest.html#DeviceRequest.asNeeded" #f)
    (schema-field 'asNeededFor 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.asNeededFor" #f)
    (schema-field 'insurance 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.insurance" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.supportingInfo" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.note" #f)
    (schema-field 'relevantHistory 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.relevantHistory" #f)
    (schema-field 'productCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'product "https://build.fhir.org/devicerequest.html#DeviceRequest.product[x]" #f)
    (schema-field 'productReference 0 1 (vector 'type 'Reference) 'product "https://build.fhir.org/devicerequest.html#DeviceRequest.product[x]" #f)
    (schema-field 'productCanonical 0 1 (vector 'prim "canonical") 'product "https://build.fhir.org/devicerequest.html#DeviceRequest.product[x]" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://build.fhir.org/devicerequest.html#DeviceRequest.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://build.fhir.org/devicerequest.html#DeviceRequest.occurrence[x]" #f)
    (schema-field 'occurrenceTiming 0 1 (vector 'type 'Timing) 'occurrence "https://build.fhir.org/devicerequest.html#DeviceRequest.occurrence[x]" #f)
             ) #f #f))
(register-element! "DeviceRequest.identifier" (fhir-spec (string->symbol "DeviceRequest.identifier") "https://build.fhir.org/devicerequest.html#DeviceRequest.identifier" 'element))
(register-element! "DeviceRequest.basedOn" (fhir-spec (string->symbol "DeviceRequest.basedOn") "https://build.fhir.org/devicerequest.html#DeviceRequest.basedOn" 'element))
(register-element! "DeviceRequest.replaces" (fhir-spec (string->symbol "DeviceRequest.replaces") "https://build.fhir.org/devicerequest.html#DeviceRequest.replaces" 'element))
(register-element! "DeviceRequest.groupIdentifier" (fhir-spec (string->symbol "DeviceRequest.groupIdentifier") "https://build.fhir.org/devicerequest.html#DeviceRequest.groupIdentifier" 'element))
(register-element! "DeviceRequest.status" (fhir-spec (string->symbol "DeviceRequest.status") "https://build.fhir.org/devicerequest.html#DeviceRequest.status" 'element))
(register-element! "DeviceRequest.intent" (fhir-spec (string->symbol "DeviceRequest.intent") "https://build.fhir.org/devicerequest.html#DeviceRequest.intent" 'element))
(register-element! "DeviceRequest.priority" (fhir-spec (string->symbol "DeviceRequest.priority") "https://build.fhir.org/devicerequest.html#DeviceRequest.priority" 'element))
(register-element! "DeviceRequest.doNotPerform" (fhir-spec (string->symbol "DeviceRequest.doNotPerform") "https://build.fhir.org/devicerequest.html#DeviceRequest.doNotPerform" 'element))
(register-element! "DeviceRequest.quantity" (fhir-spec (string->symbol "DeviceRequest.quantity") "https://build.fhir.org/devicerequest.html#DeviceRequest.quantity" 'element))
(register-element! "DeviceRequest.parameter" (fhir-spec (string->symbol "DeviceRequest.parameter") "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter" 'element))
(register-element! "DeviceRequest.subject" (fhir-spec (string->symbol "DeviceRequest.subject") "https://build.fhir.org/devicerequest.html#DeviceRequest.subject" 'element))
(register-element! "DeviceRequest.encounter" (fhir-spec (string->symbol "DeviceRequest.encounter") "https://build.fhir.org/devicerequest.html#DeviceRequest.encounter" 'element))
(register-element! "DeviceRequest.authoredOn" (fhir-spec (string->symbol "DeviceRequest.authoredOn") "https://build.fhir.org/devicerequest.html#DeviceRequest.authoredOn" 'element))
(register-element! "DeviceRequest.requester" (fhir-spec (string->symbol "DeviceRequest.requester") "https://build.fhir.org/devicerequest.html#DeviceRequest.requester" 'element))
(register-element! "DeviceRequest.performer" (fhir-spec (string->symbol "DeviceRequest.performer") "https://build.fhir.org/devicerequest.html#DeviceRequest.performer" 'element))
(register-element! "DeviceRequest.location" (fhir-spec (string->symbol "DeviceRequest.location") "https://build.fhir.org/devicerequest.html#DeviceRequest.location" 'element))
(register-element! "DeviceRequest.reason" (fhir-spec (string->symbol "DeviceRequest.reason") "https://build.fhir.org/devicerequest.html#DeviceRequest.reason" 'element))
(register-element! "DeviceRequest.asNeeded" (fhir-spec (string->symbol "DeviceRequest.asNeeded") "https://build.fhir.org/devicerequest.html#DeviceRequest.asNeeded" 'element))
(register-element! "DeviceRequest.asNeededFor" (fhir-spec (string->symbol "DeviceRequest.asNeededFor") "https://build.fhir.org/devicerequest.html#DeviceRequest.asNeededFor" 'element))
(register-element! "DeviceRequest.insurance" (fhir-spec (string->symbol "DeviceRequest.insurance") "https://build.fhir.org/devicerequest.html#DeviceRequest.insurance" 'element))
(register-element! "DeviceRequest.supportingInfo" (fhir-spec (string->symbol "DeviceRequest.supportingInfo") "https://build.fhir.org/devicerequest.html#DeviceRequest.supportingInfo" 'element))
(register-element! "DeviceRequest.note" (fhir-spec (string->symbol "DeviceRequest.note") "https://build.fhir.org/devicerequest.html#DeviceRequest.note" 'element))
(register-element! "DeviceRequest.relevantHistory" (fhir-spec (string->symbol "DeviceRequest.relevantHistory") "https://build.fhir.org/devicerequest.html#DeviceRequest.relevantHistory" 'element))
(register-element! "DeviceRequest.product[x]" (fhir-spec (string->symbol "DeviceRequest.product[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.product[x]" 'element))
(register-element! "DeviceRequest.product[x]" (fhir-spec (string->symbol "DeviceRequest.product[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.product[x]" 'element))
(register-element! "DeviceRequest.product[x]" (fhir-spec (string->symbol "DeviceRequest.product[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.product[x]" 'element))
(register-element! "DeviceRequest.occurrence[x]" (fhir-spec (string->symbol "DeviceRequest.occurrence[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.occurrence[x]" 'element))
(register-element! "DeviceRequest.occurrence[x]" (fhir-spec (string->symbol "DeviceRequest.occurrence[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.occurrence[x]" 'element))
(register-element! "DeviceRequest.occurrence[x]" (fhir-spec (string->symbol "DeviceRequest.occurrence[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.occurrence[x]" 'element))

(register-type! 'DeviceRequestParameter (fhir-spec 'DeviceRequestParameter "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter" 'type)
  #:schema (type-schema 'DeviceRequestParameter #f 'BackboneElement "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter"
             (list
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.code" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" #f)
             ) #f #f))
(register-element! "DeviceRequest.parameter.code" (fhir-spec (string->symbol "DeviceRequest.parameter.code") "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.code" 'element))
(register-element! "DeviceRequest.parameter.value[x]" (fhir-spec (string->symbol "DeviceRequest.parameter.value[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" 'element))
(register-element! "DeviceRequest.parameter.value[x]" (fhir-spec (string->symbol "DeviceRequest.parameter.value[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" 'element))
(register-element! "DeviceRequest.parameter.value[x]" (fhir-spec (string->symbol "DeviceRequest.parameter.value[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" 'element))
(register-element! "DeviceRequest.parameter.value[x]" (fhir-spec (string->symbol "DeviceRequest.parameter.value[x]") "https://build.fhir.org/devicerequest.html#DeviceRequest.parameter.value[x]" 'element))

