#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'DosageCondition (fhir-spec 'DosageCondition "https://build.fhir.org/datatypes.html#DosageCondition" 'type)
  #:schema (type-schema 'DosageCondition #f 'BackboneType "https://build.fhir.org/datatypes.html#DosageCondition"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/datatypes.html#DosageCondition.code" #f)
    (schema-field 'details 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/datatypes.html#DosageCondition.details" #f)
    (schema-field 'operation 0 1 (vector 'prim "code") #f "https://build.fhir.org/datatypes.html#DosageCondition.operation" #f)
    (schema-field 'text 0 1 (vector 'prim "string") #f "https://build.fhir.org/datatypes.html#DosageCondition.text" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueInteger64 0 1 (vector 'prim "integer64") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueCodeableReference 0 1 (vector 'type 'CodeableReference) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueRatioRange 0 1 (vector 'type 'RatioRange) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueAvailability 0 1 (vector 'type 'Availability) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueExtendedContactDetail 0 1 (vector 'type 'ExtendedContactDetail) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueVirtualServiceDetail 0 1 (vector 'type 'VirtualServiceDetail) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" #f)
             ) #f #f))
(register-element! "DosageCondition.code" (fhir-spec (string->symbol "DosageCondition.code") "https://build.fhir.org/datatypes.html#DosageCondition.code" 'element))
(register-element! "DosageCondition.details" (fhir-spec (string->symbol "DosageCondition.details") "https://build.fhir.org/datatypes.html#DosageCondition.details" 'element))
(register-element! "DosageCondition.operation" (fhir-spec (string->symbol "DosageCondition.operation") "https://build.fhir.org/datatypes.html#DosageCondition.operation" 'element))
(register-element! "DosageCondition.text" (fhir-spec (string->symbol "DosageCondition.text") "https://build.fhir.org/datatypes.html#DosageCondition.text" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))
(register-element! "DosageCondition.value[x]" (fhir-spec (string->symbol "DosageCondition.value[x]") "https://build.fhir.org/datatypes.html#DosageCondition.value[x]" 'element))

