#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Encounter (fhir-spec 'Encounter "https://build.fhir.org/encounter.html#Encounter" 'type)
  #:schema (type-schema 'Encounter #f 'DomainResource "https://build.fhir.org/encounter.html#Encounter"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/encounter.html#Encounter.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/encounter.html#Encounter.status" #f)
    (schema-field 'businessStatus 0 '* (vector 'type 'EncounterBusinessStatus) #f "https://build.fhir.org/encounter.html#Encounter.businessStatus" #f)
    (schema-field 'class 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.class" #f)
    (schema-field 'priority 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.priority" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.type" #f)
    (schema-field 'serviceType 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/encounter.html#Encounter.serviceType" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.subject" #f)
    (schema-field 'subjectStatus 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.subjectStatus" #f)
    (schema-field 'episodeOfCare 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.episodeOfCare" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.basedOn" #f)
    (schema-field 'careTeam 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.careTeam" #f)
    (schema-field 'partOf 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.partOf" #f)
    (schema-field 'serviceProvider 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.serviceProvider" #f)
    (schema-field 'participant 0 '* (vector 'type 'EncounterParticipant) #f "https://build.fhir.org/encounter.html#Encounter.participant" #f)
    (schema-field 'appointment 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.appointment" #f)
    (schema-field 'virtualService 0 '* (vector 'type 'VirtualServiceDetail) #f "https://build.fhir.org/encounter.html#Encounter.virtualService" #f)
    (schema-field 'actualPeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/encounter.html#Encounter.actualPeriod" #f)
    (schema-field 'plannedStartDate 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/encounter.html#Encounter.plannedStartDate" #f)
    (schema-field 'plannedEndDate 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/encounter.html#Encounter.plannedEndDate" #f)
    (schema-field 'length 0 1 (vector 'type 'Duration) #f "https://build.fhir.org/encounter.html#Encounter.length" #f)
    (schema-field 'reason 0 '* (vector 'type 'EncounterReason) #f "https://build.fhir.org/encounter.html#Encounter.reason" #f)
    (schema-field 'diagnosis 0 '* (vector 'type 'EncounterDiagnosis) #f "https://build.fhir.org/encounter.html#Encounter.diagnosis" #f)
    (schema-field 'account 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.account" #f)
    (schema-field 'dietPreference 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.dietPreference" #f)
    (schema-field 'specialArrangement 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.specialArrangement" #f)
    (schema-field 'specialCourtesy 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.specialCourtesy" #f)
    (schema-field 'admission 0 1 (vector 'type 'EncounterAdmission) #f "https://build.fhir.org/encounter.html#Encounter.admission" #f)
    (schema-field 'location 0 '* (vector 'type 'EncounterLocation) #f "https://build.fhir.org/encounter.html#Encounter.location" #f)
             ) #f #f))
(register-element! "Encounter.identifier" (fhir-spec (string->symbol "Encounter.identifier") "https://build.fhir.org/encounter.html#Encounter.identifier" 'element))
(register-element! "Encounter.status" (fhir-spec (string->symbol "Encounter.status") "https://build.fhir.org/encounter.html#Encounter.status" 'element))
(register-element! "Encounter.businessStatus" (fhir-spec (string->symbol "Encounter.businessStatus") "https://build.fhir.org/encounter.html#Encounter.businessStatus" 'element))
(register-element! "Encounter.class" (fhir-spec (string->symbol "Encounter.class") "https://build.fhir.org/encounter.html#Encounter.class" 'element))
(register-element! "Encounter.priority" (fhir-spec (string->symbol "Encounter.priority") "https://build.fhir.org/encounter.html#Encounter.priority" 'element))
(register-element! "Encounter.type" (fhir-spec (string->symbol "Encounter.type") "https://build.fhir.org/encounter.html#Encounter.type" 'element))
(register-element! "Encounter.serviceType" (fhir-spec (string->symbol "Encounter.serviceType") "https://build.fhir.org/encounter.html#Encounter.serviceType" 'element))
(register-element! "Encounter.subject" (fhir-spec (string->symbol "Encounter.subject") "https://build.fhir.org/encounter.html#Encounter.subject" 'element))
(register-element! "Encounter.subjectStatus" (fhir-spec (string->symbol "Encounter.subjectStatus") "https://build.fhir.org/encounter.html#Encounter.subjectStatus" 'element))
(register-element! "Encounter.episodeOfCare" (fhir-spec (string->symbol "Encounter.episodeOfCare") "https://build.fhir.org/encounter.html#Encounter.episodeOfCare" 'element))
(register-element! "Encounter.basedOn" (fhir-spec (string->symbol "Encounter.basedOn") "https://build.fhir.org/encounter.html#Encounter.basedOn" 'element))
(register-element! "Encounter.careTeam" (fhir-spec (string->symbol "Encounter.careTeam") "https://build.fhir.org/encounter.html#Encounter.careTeam" 'element))
(register-element! "Encounter.partOf" (fhir-spec (string->symbol "Encounter.partOf") "https://build.fhir.org/encounter.html#Encounter.partOf" 'element))
(register-element! "Encounter.serviceProvider" (fhir-spec (string->symbol "Encounter.serviceProvider") "https://build.fhir.org/encounter.html#Encounter.serviceProvider" 'element))
(register-element! "Encounter.participant" (fhir-spec (string->symbol "Encounter.participant") "https://build.fhir.org/encounter.html#Encounter.participant" 'element))
(register-element! "Encounter.appointment" (fhir-spec (string->symbol "Encounter.appointment") "https://build.fhir.org/encounter.html#Encounter.appointment" 'element))
(register-element! "Encounter.virtualService" (fhir-spec (string->symbol "Encounter.virtualService") "https://build.fhir.org/encounter.html#Encounter.virtualService" 'element))
(register-element! "Encounter.actualPeriod" (fhir-spec (string->symbol "Encounter.actualPeriod") "https://build.fhir.org/encounter.html#Encounter.actualPeriod" 'element))
(register-element! "Encounter.plannedStartDate" (fhir-spec (string->symbol "Encounter.plannedStartDate") "https://build.fhir.org/encounter.html#Encounter.plannedStartDate" 'element))
(register-element! "Encounter.plannedEndDate" (fhir-spec (string->symbol "Encounter.plannedEndDate") "https://build.fhir.org/encounter.html#Encounter.plannedEndDate" 'element))
(register-element! "Encounter.length" (fhir-spec (string->symbol "Encounter.length") "https://build.fhir.org/encounter.html#Encounter.length" 'element))
(register-element! "Encounter.reason" (fhir-spec (string->symbol "Encounter.reason") "https://build.fhir.org/encounter.html#Encounter.reason" 'element))
(register-element! "Encounter.diagnosis" (fhir-spec (string->symbol "Encounter.diagnosis") "https://build.fhir.org/encounter.html#Encounter.diagnosis" 'element))
(register-element! "Encounter.account" (fhir-spec (string->symbol "Encounter.account") "https://build.fhir.org/encounter.html#Encounter.account" 'element))
(register-element! "Encounter.dietPreference" (fhir-spec (string->symbol "Encounter.dietPreference") "https://build.fhir.org/encounter.html#Encounter.dietPreference" 'element))
(register-element! "Encounter.specialArrangement" (fhir-spec (string->symbol "Encounter.specialArrangement") "https://build.fhir.org/encounter.html#Encounter.specialArrangement" 'element))
(register-element! "Encounter.specialCourtesy" (fhir-spec (string->symbol "Encounter.specialCourtesy") "https://build.fhir.org/encounter.html#Encounter.specialCourtesy" 'element))
(register-element! "Encounter.admission" (fhir-spec (string->symbol "Encounter.admission") "https://build.fhir.org/encounter.html#Encounter.admission" 'element))
(register-element! "Encounter.location" (fhir-spec (string->symbol "Encounter.location") "https://build.fhir.org/encounter.html#Encounter.location" 'element))

(register-type! 'EncounterBusinessStatus (fhir-spec 'EncounterBusinessStatus "https://build.fhir.org/encounter.html#Encounter.businessStatus" 'type)
  #:schema (type-schema 'EncounterBusinessStatus #f 'BackboneElement "https://build.fhir.org/encounter.html#Encounter.businessStatus"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.businessStatus.code" #f)
    (schema-field 'type 0 1 (vector 'type 'Coding) #f "https://build.fhir.org/encounter.html#Encounter.businessStatus.type" #f)
    (schema-field 'effectiveDate 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/encounter.html#Encounter.businessStatus.effectiveDate" #f)
             ) #f #f))
(register-element! "Encounter.businessStatus.code" (fhir-spec (string->symbol "Encounter.businessStatus.code") "https://build.fhir.org/encounter.html#Encounter.businessStatus.code" 'element))
(register-element! "Encounter.businessStatus.type" (fhir-spec (string->symbol "Encounter.businessStatus.type") "https://build.fhir.org/encounter.html#Encounter.businessStatus.type" 'element))
(register-element! "Encounter.businessStatus.effectiveDate" (fhir-spec (string->symbol "Encounter.businessStatus.effectiveDate") "https://build.fhir.org/encounter.html#Encounter.businessStatus.effectiveDate" 'element))

(register-type! 'EncounterParticipant (fhir-spec 'EncounterParticipant "https://build.fhir.org/encounter.html#Encounter.participant" 'type)
  #:schema (type-schema 'EncounterParticipant #f 'BackboneElement "https://build.fhir.org/encounter.html#Encounter.participant"
             (list
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.participant.type" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/encounter.html#Encounter.participant.period" #f)
    (schema-field 'actor 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.participant.actor" #f)
             ) #f #f))
(register-element! "Encounter.participant.type" (fhir-spec (string->symbol "Encounter.participant.type") "https://build.fhir.org/encounter.html#Encounter.participant.type" 'element))
(register-element! "Encounter.participant.period" (fhir-spec (string->symbol "Encounter.participant.period") "https://build.fhir.org/encounter.html#Encounter.participant.period" 'element))
(register-element! "Encounter.participant.actor" (fhir-spec (string->symbol "Encounter.participant.actor") "https://build.fhir.org/encounter.html#Encounter.participant.actor" 'element))

(register-type! 'EncounterReason (fhir-spec 'EncounterReason "https://build.fhir.org/encounter.html#Encounter.reason" 'type)
  #:schema (type-schema 'EncounterReason #f 'BackboneElement "https://build.fhir.org/encounter.html#Encounter.reason"
             (list
    (schema-field 'use 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.reason.use" #f)
    (schema-field 'value 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/encounter.html#Encounter.reason.value" #f)
             ) #f #f))
(register-element! "Encounter.reason.use" (fhir-spec (string->symbol "Encounter.reason.use") "https://build.fhir.org/encounter.html#Encounter.reason.use" 'element))
(register-element! "Encounter.reason.value" (fhir-spec (string->symbol "Encounter.reason.value") "https://build.fhir.org/encounter.html#Encounter.reason.value" 'element))

(register-type! 'EncounterDiagnosis (fhir-spec 'EncounterDiagnosis "https://build.fhir.org/encounter.html#Encounter.diagnosis" 'type)
  #:schema (type-schema 'EncounterDiagnosis #f 'BackboneElement "https://build.fhir.org/encounter.html#Encounter.diagnosis"
             (list
    (schema-field 'condition 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/encounter.html#Encounter.diagnosis.condition" #f)
    (schema-field 'use 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.diagnosis.use" #f)
             ) #f #f))
(register-element! "Encounter.diagnosis.condition" (fhir-spec (string->symbol "Encounter.diagnosis.condition") "https://build.fhir.org/encounter.html#Encounter.diagnosis.condition" 'element))
(register-element! "Encounter.diagnosis.use" (fhir-spec (string->symbol "Encounter.diagnosis.use") "https://build.fhir.org/encounter.html#Encounter.diagnosis.use" 'element))

(register-type! 'EncounterAdmission (fhir-spec 'EncounterAdmission "https://build.fhir.org/encounter.html#Encounter.admission" 'type)
  #:schema (type-schema 'EncounterAdmission #f 'BackboneElement "https://build.fhir.org/encounter.html#Encounter.admission"
             (list
    (schema-field 'preAdmissionIdentifier 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/encounter.html#Encounter.admission.preAdmissionIdentifier" #f)
    (schema-field 'origin 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.admission.origin" #f)
    (schema-field 'admitSource 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.admission.admitSource" #f)
    (schema-field 'reAdmission 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.admission.reAdmission" #f)
    (schema-field 'destination 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.admission.destination" #f)
    (schema-field 'dischargeDisposition 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.admission.dischargeDisposition" #f)
             ) #f #f))
(register-element! "Encounter.admission.preAdmissionIdentifier" (fhir-spec (string->symbol "Encounter.admission.preAdmissionIdentifier") "https://build.fhir.org/encounter.html#Encounter.admission.preAdmissionIdentifier" 'element))
(register-element! "Encounter.admission.origin" (fhir-spec (string->symbol "Encounter.admission.origin") "https://build.fhir.org/encounter.html#Encounter.admission.origin" 'element))
(register-element! "Encounter.admission.admitSource" (fhir-spec (string->symbol "Encounter.admission.admitSource") "https://build.fhir.org/encounter.html#Encounter.admission.admitSource" 'element))
(register-element! "Encounter.admission.reAdmission" (fhir-spec (string->symbol "Encounter.admission.reAdmission") "https://build.fhir.org/encounter.html#Encounter.admission.reAdmission" 'element))
(register-element! "Encounter.admission.destination" (fhir-spec (string->symbol "Encounter.admission.destination") "https://build.fhir.org/encounter.html#Encounter.admission.destination" 'element))
(register-element! "Encounter.admission.dischargeDisposition" (fhir-spec (string->symbol "Encounter.admission.dischargeDisposition") "https://build.fhir.org/encounter.html#Encounter.admission.dischargeDisposition" 'element))

(register-type! 'EncounterLocation (fhir-spec 'EncounterLocation "https://build.fhir.org/encounter.html#Encounter.location" 'type)
  #:schema (type-schema 'EncounterLocation #f 'BackboneElement "https://build.fhir.org/encounter.html#Encounter.location"
             (list
    (schema-field 'location 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/encounter.html#Encounter.location.location" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://build.fhir.org/encounter.html#Encounter.location.status" #f)
    (schema-field 'form 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/encounter.html#Encounter.location.form" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/encounter.html#Encounter.location.period" #f)
             ) #f #f))
(register-element! "Encounter.location.location" (fhir-spec (string->symbol "Encounter.location.location") "https://build.fhir.org/encounter.html#Encounter.location.location" 'element))
(register-element! "Encounter.location.status" (fhir-spec (string->symbol "Encounter.location.status") "https://build.fhir.org/encounter.html#Encounter.location.status" 'element))
(register-element! "Encounter.location.form" (fhir-spec (string->symbol "Encounter.location.form") "https://build.fhir.org/encounter.html#Encounter.location.form" 'element))
(register-element! "Encounter.location.period" (fhir-spec (string->symbol "Encounter.location.period") "https://build.fhir.org/encounter.html#Encounter.location.period" 'element))

