#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'EventDefinition (fhir-spec 'EventDefinition "https://build.fhir.org/eventdefinition.html#EventDefinition" 'type)
  #:schema (type-schema 'EventDefinition #f 'DomainResource "https://build.fhir.org/eventdefinition.html#EventDefinition"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.title" #f)
    (schema-field 'subtitle 0 1 (vector 'prim "string") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.subtitle" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.purpose" #f)
    (schema-field 'usage 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.usage" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/eventdefinition.html#EventDefinition.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.effectivePeriod" #f)
    (schema-field 'topic 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.topic" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.endorser" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.relatedArtifact" #f)
    (schema-field 'trigger 1 '* (vector 'type 'TriggerDefinition) #f "https://build.fhir.org/eventdefinition.html#EventDefinition.trigger" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/eventdefinition.html#EventDefinition.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/eventdefinition.html#EventDefinition.versionAlgorithm[x]" #f)
    (schema-field 'subjectCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'subject "https://build.fhir.org/eventdefinition.html#EventDefinition.subject[x]" #f)
    (schema-field 'subjectReference 0 1 (vector 'type 'Reference) 'subject "https://build.fhir.org/eventdefinition.html#EventDefinition.subject[x]" #f)
             ) #f #f))
(register-element! "EventDefinition.url" (fhir-spec (string->symbol "EventDefinition.url") "https://build.fhir.org/eventdefinition.html#EventDefinition.url" 'element))
(register-element! "EventDefinition.identifier" (fhir-spec (string->symbol "EventDefinition.identifier") "https://build.fhir.org/eventdefinition.html#EventDefinition.identifier" 'element))
(register-element! "EventDefinition.version" (fhir-spec (string->symbol "EventDefinition.version") "https://build.fhir.org/eventdefinition.html#EventDefinition.version" 'element))
(register-element! "EventDefinition.name" (fhir-spec (string->symbol "EventDefinition.name") "https://build.fhir.org/eventdefinition.html#EventDefinition.name" 'element))
(register-element! "EventDefinition.title" (fhir-spec (string->symbol "EventDefinition.title") "https://build.fhir.org/eventdefinition.html#EventDefinition.title" 'element))
(register-element! "EventDefinition.subtitle" (fhir-spec (string->symbol "EventDefinition.subtitle") "https://build.fhir.org/eventdefinition.html#EventDefinition.subtitle" 'element))
(register-element! "EventDefinition.status" (fhir-spec (string->symbol "EventDefinition.status") "https://build.fhir.org/eventdefinition.html#EventDefinition.status" 'element))
(register-element! "EventDefinition.experimental" (fhir-spec (string->symbol "EventDefinition.experimental") "https://build.fhir.org/eventdefinition.html#EventDefinition.experimental" 'element))
(register-element! "EventDefinition.date" (fhir-spec (string->symbol "EventDefinition.date") "https://build.fhir.org/eventdefinition.html#EventDefinition.date" 'element))
(register-element! "EventDefinition.publisher" (fhir-spec (string->symbol "EventDefinition.publisher") "https://build.fhir.org/eventdefinition.html#EventDefinition.publisher" 'element))
(register-element! "EventDefinition.contact" (fhir-spec (string->symbol "EventDefinition.contact") "https://build.fhir.org/eventdefinition.html#EventDefinition.contact" 'element))
(register-element! "EventDefinition.description" (fhir-spec (string->symbol "EventDefinition.description") "https://build.fhir.org/eventdefinition.html#EventDefinition.description" 'element))
(register-element! "EventDefinition.useContext" (fhir-spec (string->symbol "EventDefinition.useContext") "https://build.fhir.org/eventdefinition.html#EventDefinition.useContext" 'element))
(register-element! "EventDefinition.jurisdiction" (fhir-spec (string->symbol "EventDefinition.jurisdiction") "https://build.fhir.org/eventdefinition.html#EventDefinition.jurisdiction" 'element))
(register-element! "EventDefinition.purpose" (fhir-spec (string->symbol "EventDefinition.purpose") "https://build.fhir.org/eventdefinition.html#EventDefinition.purpose" 'element))
(register-element! "EventDefinition.usage" (fhir-spec (string->symbol "EventDefinition.usage") "https://build.fhir.org/eventdefinition.html#EventDefinition.usage" 'element))
(register-element! "EventDefinition.copyright" (fhir-spec (string->symbol "EventDefinition.copyright") "https://build.fhir.org/eventdefinition.html#EventDefinition.copyright" 'element))
(register-element! "EventDefinition.copyrightLabel" (fhir-spec (string->symbol "EventDefinition.copyrightLabel") "https://build.fhir.org/eventdefinition.html#EventDefinition.copyrightLabel" 'element))
(register-element! "EventDefinition.approvalDate" (fhir-spec (string->symbol "EventDefinition.approvalDate") "https://build.fhir.org/eventdefinition.html#EventDefinition.approvalDate" 'element))
(register-element! "EventDefinition.lastReviewDate" (fhir-spec (string->symbol "EventDefinition.lastReviewDate") "https://build.fhir.org/eventdefinition.html#EventDefinition.lastReviewDate" 'element))
(register-element! "EventDefinition.effectivePeriod" (fhir-spec (string->symbol "EventDefinition.effectivePeriod") "https://build.fhir.org/eventdefinition.html#EventDefinition.effectivePeriod" 'element))
(register-element! "EventDefinition.topic" (fhir-spec (string->symbol "EventDefinition.topic") "https://build.fhir.org/eventdefinition.html#EventDefinition.topic" 'element))
(register-element! "EventDefinition.author" (fhir-spec (string->symbol "EventDefinition.author") "https://build.fhir.org/eventdefinition.html#EventDefinition.author" 'element))
(register-element! "EventDefinition.editor" (fhir-spec (string->symbol "EventDefinition.editor") "https://build.fhir.org/eventdefinition.html#EventDefinition.editor" 'element))
(register-element! "EventDefinition.reviewer" (fhir-spec (string->symbol "EventDefinition.reviewer") "https://build.fhir.org/eventdefinition.html#EventDefinition.reviewer" 'element))
(register-element! "EventDefinition.endorser" (fhir-spec (string->symbol "EventDefinition.endorser") "https://build.fhir.org/eventdefinition.html#EventDefinition.endorser" 'element))
(register-element! "EventDefinition.relatedArtifact" (fhir-spec (string->symbol "EventDefinition.relatedArtifact") "https://build.fhir.org/eventdefinition.html#EventDefinition.relatedArtifact" 'element))
(register-element! "EventDefinition.trigger" (fhir-spec (string->symbol "EventDefinition.trigger") "https://build.fhir.org/eventdefinition.html#EventDefinition.trigger" 'element))
(register-element! "EventDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "EventDefinition.versionAlgorithm[x]") "https://build.fhir.org/eventdefinition.html#EventDefinition.versionAlgorithm[x]" 'element))
(register-element! "EventDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "EventDefinition.versionAlgorithm[x]") "https://build.fhir.org/eventdefinition.html#EventDefinition.versionAlgorithm[x]" 'element))
(register-element! "EventDefinition.subject[x]" (fhir-spec (string->symbol "EventDefinition.subject[x]") "https://build.fhir.org/eventdefinition.html#EventDefinition.subject[x]" 'element))
(register-element! "EventDefinition.subject[x]" (fhir-spec (string->symbol "EventDefinition.subject[x]") "https://build.fhir.org/eventdefinition.html#EventDefinition.subject[x]" 'element))

