#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Evidence (fhir-spec 'Evidence "https://build.fhir.org/evidence.html#Evidence" 'type)
  #:schema (type-schema 'Evidence #f 'DomainResource "https://build.fhir.org/evidence.html#Evidence"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/evidence.html#Evidence.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/evidence.html#Evidence.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/evidence.html#Evidence.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/evidence.html#Evidence.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/evidence.html#Evidence.title" #f)
    (schema-field 'citeAs 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.citeAs" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://build.fhir.org/evidence.html#Evidence.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/evidence.html#Evidence.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/evidence.html#Evidence.date" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/evidence.html#Evidence.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/evidence.html#Evidence.lastReviewDate" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/evidence.html#Evidence.author" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/evidence.html#Evidence.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/evidence.html#Evidence.contact" #f)
    (schema-field 'recorder 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/evidence.html#Evidence.recorder" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/evidence.html#Evidence.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/evidence.html#Evidence.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/evidence.html#Evidence.endorser" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/evidence.html#Evidence.useContext" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/evidence.html#Evidence.copyrightLabel" #f)
    (schema-field 'relatesTo 0 '* (vector 'type 'EvidenceRelatesTo) #f "https://build.fhir.org/evidence.html#Evidence.relatesTo" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.description" #f)
    (schema-field 'assertion 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.assertion" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/evidence.html#Evidence.note" #f)
    (schema-field 'classification 0 '* (vector 'type 'EvidenceClassification) #f "https://build.fhir.org/evidence.html#Evidence.classification" #f)
    (schema-field 'variableDefinition 0 '* (vector 'type 'EvidenceVariableDefinition) #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition" #f)
    (schema-field 'synthesisType 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.synthesisType" #f)
    (schema-field 'studyDesign 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.studyDesign" #f)
    (schema-field 'statistic 0 '* (vector 'type 'EvidenceStatistic) #f "https://build.fhir.org/evidence.html#Evidence.statistic" #f)
    (schema-field 'certainty 0 '* (vector 'type 'EvidenceCertainty) #f "https://build.fhir.org/evidence.html#Evidence.certainty" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/evidence.html#Evidence.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/evidence.html#Evidence.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "Evidence.url" (fhir-spec (string->symbol "Evidence.url") "https://build.fhir.org/evidence.html#Evidence.url" 'element))
(register-element! "Evidence.identifier" (fhir-spec (string->symbol "Evidence.identifier") "https://build.fhir.org/evidence.html#Evidence.identifier" 'element))
(register-element! "Evidence.version" (fhir-spec (string->symbol "Evidence.version") "https://build.fhir.org/evidence.html#Evidence.version" 'element))
(register-element! "Evidence.name" (fhir-spec (string->symbol "Evidence.name") "https://build.fhir.org/evidence.html#Evidence.name" 'element))
(register-element! "Evidence.title" (fhir-spec (string->symbol "Evidence.title") "https://build.fhir.org/evidence.html#Evidence.title" 'element))
(register-element! "Evidence.citeAs" (fhir-spec (string->symbol "Evidence.citeAs") "https://build.fhir.org/evidence.html#Evidence.citeAs" 'element))
(register-element! "Evidence.status" (fhir-spec (string->symbol "Evidence.status") "https://build.fhir.org/evidence.html#Evidence.status" 'element))
(register-element! "Evidence.experimental" (fhir-spec (string->symbol "Evidence.experimental") "https://build.fhir.org/evidence.html#Evidence.experimental" 'element))
(register-element! "Evidence.date" (fhir-spec (string->symbol "Evidence.date") "https://build.fhir.org/evidence.html#Evidence.date" 'element))
(register-element! "Evidence.approvalDate" (fhir-spec (string->symbol "Evidence.approvalDate") "https://build.fhir.org/evidence.html#Evidence.approvalDate" 'element))
(register-element! "Evidence.lastReviewDate" (fhir-spec (string->symbol "Evidence.lastReviewDate") "https://build.fhir.org/evidence.html#Evidence.lastReviewDate" 'element))
(register-element! "Evidence.author" (fhir-spec (string->symbol "Evidence.author") "https://build.fhir.org/evidence.html#Evidence.author" 'element))
(register-element! "Evidence.publisher" (fhir-spec (string->symbol "Evidence.publisher") "https://build.fhir.org/evidence.html#Evidence.publisher" 'element))
(register-element! "Evidence.contact" (fhir-spec (string->symbol "Evidence.contact") "https://build.fhir.org/evidence.html#Evidence.contact" 'element))
(register-element! "Evidence.recorder" (fhir-spec (string->symbol "Evidence.recorder") "https://build.fhir.org/evidence.html#Evidence.recorder" 'element))
(register-element! "Evidence.editor" (fhir-spec (string->symbol "Evidence.editor") "https://build.fhir.org/evidence.html#Evidence.editor" 'element))
(register-element! "Evidence.reviewer" (fhir-spec (string->symbol "Evidence.reviewer") "https://build.fhir.org/evidence.html#Evidence.reviewer" 'element))
(register-element! "Evidence.endorser" (fhir-spec (string->symbol "Evidence.endorser") "https://build.fhir.org/evidence.html#Evidence.endorser" 'element))
(register-element! "Evidence.useContext" (fhir-spec (string->symbol "Evidence.useContext") "https://build.fhir.org/evidence.html#Evidence.useContext" 'element))
(register-element! "Evidence.purpose" (fhir-spec (string->symbol "Evidence.purpose") "https://build.fhir.org/evidence.html#Evidence.purpose" 'element))
(register-element! "Evidence.copyright" (fhir-spec (string->symbol "Evidence.copyright") "https://build.fhir.org/evidence.html#Evidence.copyright" 'element))
(register-element! "Evidence.copyrightLabel" (fhir-spec (string->symbol "Evidence.copyrightLabel") "https://build.fhir.org/evidence.html#Evidence.copyrightLabel" 'element))
(register-element! "Evidence.relatesTo" (fhir-spec (string->symbol "Evidence.relatesTo") "https://build.fhir.org/evidence.html#Evidence.relatesTo" 'element))
(register-element! "Evidence.description" (fhir-spec (string->symbol "Evidence.description") "https://build.fhir.org/evidence.html#Evidence.description" 'element))
(register-element! "Evidence.assertion" (fhir-spec (string->symbol "Evidence.assertion") "https://build.fhir.org/evidence.html#Evidence.assertion" 'element))
(register-element! "Evidence.note" (fhir-spec (string->symbol "Evidence.note") "https://build.fhir.org/evidence.html#Evidence.note" 'element))
(register-element! "Evidence.classification" (fhir-spec (string->symbol "Evidence.classification") "https://build.fhir.org/evidence.html#Evidence.classification" 'element))
(register-element! "Evidence.variableDefinition" (fhir-spec (string->symbol "Evidence.variableDefinition") "https://build.fhir.org/evidence.html#Evidence.variableDefinition" 'element))
(register-element! "Evidence.synthesisType" (fhir-spec (string->symbol "Evidence.synthesisType") "https://build.fhir.org/evidence.html#Evidence.synthesisType" 'element))
(register-element! "Evidence.studyDesign" (fhir-spec (string->symbol "Evidence.studyDesign") "https://build.fhir.org/evidence.html#Evidence.studyDesign" 'element))
(register-element! "Evidence.statistic" (fhir-spec (string->symbol "Evidence.statistic") "https://build.fhir.org/evidence.html#Evidence.statistic" 'element))
(register-element! "Evidence.certainty" (fhir-spec (string->symbol "Evidence.certainty") "https://build.fhir.org/evidence.html#Evidence.certainty" 'element))
(register-element! "Evidence.versionAlgorithm[x]" (fhir-spec (string->symbol "Evidence.versionAlgorithm[x]") "https://build.fhir.org/evidence.html#Evidence.versionAlgorithm[x]" 'element))
(register-element! "Evidence.versionAlgorithm[x]" (fhir-spec (string->symbol "Evidence.versionAlgorithm[x]") "https://build.fhir.org/evidence.html#Evidence.versionAlgorithm[x]" 'element))

(register-type! 'EvidenceRelatesTo (fhir-spec 'EvidenceRelatesTo "https://build.fhir.org/evidence.html#Evidence.relatesTo" 'type)
  #:schema (type-schema 'EvidenceRelatesTo #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.relatesTo"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.relatesTo.type" #f)
    (schema-field 'targetUri 0 1 (vector 'prim "uri") 'target "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" #f)
    (schema-field 'targetAttachment 0 1 (vector 'type 'Attachment) 'target "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" #f)
    (schema-field 'targetCanonical 0 1 (vector 'prim "canonical") 'target "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" #f)
    (schema-field 'targetReference 0 1 (vector 'type 'Reference) 'target "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" #f)
    (schema-field 'targetMarkdown 0 1 (vector 'prim "markdown") 'target "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" #f)
             ) #f #f))
(register-element! "Evidence.relatesTo.type" (fhir-spec (string->symbol "Evidence.relatesTo.type") "https://build.fhir.org/evidence.html#Evidence.relatesTo.type" 'element))
(register-element! "Evidence.relatesTo.target[x]" (fhir-spec (string->symbol "Evidence.relatesTo.target[x]") "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" 'element))
(register-element! "Evidence.relatesTo.target[x]" (fhir-spec (string->symbol "Evidence.relatesTo.target[x]") "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" 'element))
(register-element! "Evidence.relatesTo.target[x]" (fhir-spec (string->symbol "Evidence.relatesTo.target[x]") "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" 'element))
(register-element! "Evidence.relatesTo.target[x]" (fhir-spec (string->symbol "Evidence.relatesTo.target[x]") "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" 'element))
(register-element! "Evidence.relatesTo.target[x]" (fhir-spec (string->symbol "Evidence.relatesTo.target[x]") "https://build.fhir.org/evidence.html#Evidence.relatesTo.target[x]" 'element))

(register-type! 'EvidenceClassification (fhir-spec 'EvidenceClassification "https://build.fhir.org/evidence.html#Evidence.classification" 'type)
  #:schema (type-schema 'EvidenceClassification #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.classification"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.classification.type" #f)
    (schema-field 'classifier 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/evidence.html#Evidence.classification.classifier" #f)
             ) #f #f))
(register-element! "Evidence.classification.type" (fhir-spec (string->symbol "Evidence.classification.type") "https://build.fhir.org/evidence.html#Evidence.classification.type" 'element))
(register-element! "Evidence.classification.classifier" (fhir-spec (string->symbol "Evidence.classification.classifier") "https://build.fhir.org/evidence.html#Evidence.classification.classifier" 'element))

(register-type! 'EvidenceVariableDefinition (fhir-spec 'EvidenceVariableDefinition "https://build.fhir.org/evidence.html#Evidence.variableDefinition" 'type)
  #:schema (type-schema 'EvidenceVariableDefinition #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.variableDefinition"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.note" #f)
    (schema-field 'variableRole 1 1 (vector 'prim "code") #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.variableRole" #f)
    (schema-field 'roleSubtype 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.roleSubtype" #f)
    (schema-field 'comparatorCategory 0 1 (vector 'prim "string") #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.comparatorCategory" #f)
    (schema-field 'observed 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.observed" #f)
    (schema-field 'intended 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.intended" #f)
    (schema-field 'directnessMatch 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.variableDefinition.directnessMatch" #f)
             ) #f #f))
(register-element! "Evidence.variableDefinition.description" (fhir-spec (string->symbol "Evidence.variableDefinition.description") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.description" 'element))
(register-element! "Evidence.variableDefinition.note" (fhir-spec (string->symbol "Evidence.variableDefinition.note") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.note" 'element))
(register-element! "Evidence.variableDefinition.variableRole" (fhir-spec (string->symbol "Evidence.variableDefinition.variableRole") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.variableRole" 'element))
(register-element! "Evidence.variableDefinition.roleSubtype" (fhir-spec (string->symbol "Evidence.variableDefinition.roleSubtype") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.roleSubtype" 'element))
(register-element! "Evidence.variableDefinition.comparatorCategory" (fhir-spec (string->symbol "Evidence.variableDefinition.comparatorCategory") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.comparatorCategory" 'element))
(register-element! "Evidence.variableDefinition.observed" (fhir-spec (string->symbol "Evidence.variableDefinition.observed") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.observed" 'element))
(register-element! "Evidence.variableDefinition.intended" (fhir-spec (string->symbol "Evidence.variableDefinition.intended") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.intended" 'element))
(register-element! "Evidence.variableDefinition.directnessMatch" (fhir-spec (string->symbol "Evidence.variableDefinition.directnessMatch") "https://build.fhir.org/evidence.html#Evidence.variableDefinition.directnessMatch" 'element))

(register-type! 'EvidenceStatistic (fhir-spec 'EvidenceStatistic "https://build.fhir.org/evidence.html#Evidence.statistic" 'type)
  #:schema (type-schema 'EvidenceStatistic #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.statistic"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.statistic.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/evidence.html#Evidence.statistic.note" #f)
    (schema-field 'statisticType 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.statistic.statisticType" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.statistic.category" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/evidence.html#Evidence.statistic.quantity" #f)
    (schema-field 'numberOfEvents 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/evidence.html#Evidence.statistic.numberOfEvents" #f)
    (schema-field 'numberAffected 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/evidence.html#Evidence.statistic.numberAffected" #f)
    (schema-field 'sampleSize 0 1 (vector 'type 'EvidenceStatisticSampleSize) #f "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize" #f)
    (schema-field 'attributeEstimate 0 '* (vector 'type 'EvidenceStatisticAttributeEstimate) #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate" #f)
    (schema-field 'modelCharacteristic 0 '* (vector 'type 'EvidenceStatisticModelCharacteristic) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic" #f)
             ) #f #f))
(register-element! "Evidence.statistic.description" (fhir-spec (string->symbol "Evidence.statistic.description") "https://build.fhir.org/evidence.html#Evidence.statistic.description" 'element))
(register-element! "Evidence.statistic.note" (fhir-spec (string->symbol "Evidence.statistic.note") "https://build.fhir.org/evidence.html#Evidence.statistic.note" 'element))
(register-element! "Evidence.statistic.statisticType" (fhir-spec (string->symbol "Evidence.statistic.statisticType") "https://build.fhir.org/evidence.html#Evidence.statistic.statisticType" 'element))
(register-element! "Evidence.statistic.category" (fhir-spec (string->symbol "Evidence.statistic.category") "https://build.fhir.org/evidence.html#Evidence.statistic.category" 'element))
(register-element! "Evidence.statistic.quantity" (fhir-spec (string->symbol "Evidence.statistic.quantity") "https://build.fhir.org/evidence.html#Evidence.statistic.quantity" 'element))
(register-element! "Evidence.statistic.numberOfEvents" (fhir-spec (string->symbol "Evidence.statistic.numberOfEvents") "https://build.fhir.org/evidence.html#Evidence.statistic.numberOfEvents" 'element))
(register-element! "Evidence.statistic.numberAffected" (fhir-spec (string->symbol "Evidence.statistic.numberAffected") "https://build.fhir.org/evidence.html#Evidence.statistic.numberAffected" 'element))
(register-element! "Evidence.statistic.sampleSize" (fhir-spec (string->symbol "Evidence.statistic.sampleSize") "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize" 'element))
(register-element! "Evidence.statistic.attributeEstimate" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate" 'element))
(register-element! "Evidence.statistic.modelCharacteristic" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic" 'element))

(register-type! 'EvidenceStatisticSampleSize (fhir-spec 'EvidenceStatisticSampleSize "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize" 'type)
  #:schema (type-schema 'EvidenceStatisticSampleSize #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.note" #f)
    (schema-field 'numberOfStudies 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.numberOfStudies" #f)
    (schema-field 'numberOfParticipants 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.numberOfParticipants" #f)
    (schema-field 'knownDataCount 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.knownDataCount" #f)
    (schema-field 'numberAnalyzed 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.numberAnalyzed" #f)
             ) #f #f))
(register-element! "Evidence.statistic.sampleSize.description" (fhir-spec (string->symbol "Evidence.statistic.sampleSize.description") "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.description" 'element))
(register-element! "Evidence.statistic.sampleSize.note" (fhir-spec (string->symbol "Evidence.statistic.sampleSize.note") "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.note" 'element))
(register-element! "Evidence.statistic.sampleSize.numberOfStudies" (fhir-spec (string->symbol "Evidence.statistic.sampleSize.numberOfStudies") "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.numberOfStudies" 'element))
(register-element! "Evidence.statistic.sampleSize.numberOfParticipants" (fhir-spec (string->symbol "Evidence.statistic.sampleSize.numberOfParticipants") "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.numberOfParticipants" 'element))
(register-element! "Evidence.statistic.sampleSize.knownDataCount" (fhir-spec (string->symbol "Evidence.statistic.sampleSize.knownDataCount") "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.knownDataCount" 'element))
(register-element! "Evidence.statistic.sampleSize.numberAnalyzed" (fhir-spec (string->symbol "Evidence.statistic.sampleSize.numberAnalyzed") "https://build.fhir.org/evidence.html#Evidence.statistic.sampleSize.numberAnalyzed" 'element))

(register-type! 'EvidenceStatisticAttributeEstimate (fhir-spec 'EvidenceStatisticAttributeEstimate "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate" 'type)
  #:schema (type-schema 'EvidenceStatisticAttributeEstimate #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.note" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.type" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.quantity" #f)
    (schema-field 'level 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.level" #f)
    (schema-field 'range 0 1 (vector 'type 'Range) #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.range" #f)
    (schema-field 'attributeEstimate 0 '* (vector 'type 'EvidenceStatisticAttributeEstimate) #f "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.attributeEstimate" #f)
             ) #f #f))
(register-element! "Evidence.statistic.attributeEstimate.description" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate.description") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.description" 'element))
(register-element! "Evidence.statistic.attributeEstimate.note" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate.note") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.note" 'element))
(register-element! "Evidence.statistic.attributeEstimate.type" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate.type") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.type" 'element))
(register-element! "Evidence.statistic.attributeEstimate.quantity" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate.quantity") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.quantity" 'element))
(register-element! "Evidence.statistic.attributeEstimate.level" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate.level") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.level" 'element))
(register-element! "Evidence.statistic.attributeEstimate.range" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate.range") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.range" 'element))
(register-element! "Evidence.statistic.attributeEstimate.attributeEstimate" (fhir-spec (string->symbol "Evidence.statistic.attributeEstimate.attributeEstimate") "https://build.fhir.org/evidence.html#Evidence.statistic.attributeEstimate.attributeEstimate" 'element))

(register-type! 'EvidenceStatisticModelCharacteristic (fhir-spec 'EvidenceStatisticModelCharacteristic "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic" 'type)
  #:schema (type-schema 'EvidenceStatisticModelCharacteristic #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.code" #f)
    (schema-field 'intended 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.intended" #f)
    (schema-field 'applied 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.applied" #f)
    (schema-field 'variable 0 '* (vector 'type 'EvidenceStatisticModelCharacteristicVariable) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable" #f)
    (schema-field 'attribute 0 '* (vector 'type 'EvidenceStatisticAttributeEstimate) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.attribute" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.value[x]" #f)
             ) #f #f))
(register-element! "Evidence.statistic.modelCharacteristic.code" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.code") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.code" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.intended" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.intended") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.intended" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.applied" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.applied") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.applied" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.variable" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.variable") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.attribute" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.attribute") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.attribute" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.value[x]" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.value[x]") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.value[x]" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.value[x]" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.value[x]") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.value[x]" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.value[x]" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.value[x]") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.value[x]" 'element))

(register-type! 'EvidenceStatisticModelCharacteristicVariable (fhir-spec 'EvidenceStatisticModelCharacteristicVariable "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable" 'type)
  #:schema (type-schema 'EvidenceStatisticModelCharacteristicVariable #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable"
             (list
    (schema-field 'variableDefinition 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.variableDefinition" #f)
    (schema-field 'handling 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.handling" #f)
    (schema-field 'valueCategory 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.valueCategory" #f)
    (schema-field 'valueQuantity 0 '* (vector 'type 'Quantity) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.valueQuantity" #f)
    (schema-field 'valueRange 0 '* (vector 'type 'Range) #f "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.valueRange" #f)
             ) #f #f))
(register-element! "Evidence.statistic.modelCharacteristic.variable.variableDefinition" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.variable.variableDefinition") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.variableDefinition" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.variable.handling" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.variable.handling") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.handling" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.variable.valueCategory" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.variable.valueCategory") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.valueCategory" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.variable.valueQuantity" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.variable.valueQuantity") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.valueQuantity" 'element))
(register-element! "Evidence.statistic.modelCharacteristic.variable.valueRange" (fhir-spec (string->symbol "Evidence.statistic.modelCharacteristic.variable.valueRange") "https://build.fhir.org/evidence.html#Evidence.statistic.modelCharacteristic.variable.valueRange" 'element))

(register-type! 'EvidenceCertainty (fhir-spec 'EvidenceCertainty "https://build.fhir.org/evidence.html#Evidence.certainty" 'type)
  #:schema (type-schema 'EvidenceCertainty #f 'BackboneElement "https://build.fhir.org/evidence.html#Evidence.certainty"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/evidence.html#Evidence.certainty.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/evidence.html#Evidence.certainty.note" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.certainty.type" #f)
    (schema-field 'rating 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/evidence.html#Evidence.certainty.rating" #f)
    (schema-field 'rater 0 '* (vector 'prim "string") #f "https://build.fhir.org/evidence.html#Evidence.certainty.rater" #f)
    (schema-field 'subcomponent 0 '* (vector 'type 'EvidenceCertainty) #f "https://build.fhir.org/evidence.html#Evidence.certainty.subcomponent" #f)
             ) #f #f))
(register-element! "Evidence.certainty.description" (fhir-spec (string->symbol "Evidence.certainty.description") "https://build.fhir.org/evidence.html#Evidence.certainty.description" 'element))
(register-element! "Evidence.certainty.note" (fhir-spec (string->symbol "Evidence.certainty.note") "https://build.fhir.org/evidence.html#Evidence.certainty.note" 'element))
(register-element! "Evidence.certainty.type" (fhir-spec (string->symbol "Evidence.certainty.type") "https://build.fhir.org/evidence.html#Evidence.certainty.type" 'element))
(register-element! "Evidence.certainty.rating" (fhir-spec (string->symbol "Evidence.certainty.rating") "https://build.fhir.org/evidence.html#Evidence.certainty.rating" 'element))
(register-element! "Evidence.certainty.rater" (fhir-spec (string->symbol "Evidence.certainty.rater") "https://build.fhir.org/evidence.html#Evidence.certainty.rater" 'element))
(register-element! "Evidence.certainty.subcomponent" (fhir-spec (string->symbol "Evidence.certainty.subcomponent") "https://build.fhir.org/evidence.html#Evidence.certainty.subcomponent" 'element))

