#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ExampleScenario (fhir-spec 'ExampleScenario "https://build.fhir.org/examplescenario.html#ExampleScenario" 'type)
  #:schema (type-schema 'ExampleScenario #f 'DomainResource "https://build.fhir.org/examplescenario.html#ExampleScenario"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.copyrightLabel" #f)
    (schema-field 'actor 0 '* (vector 'type 'ExampleScenarioActor) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.actor" #f)
    (schema-field 'instance 0 '* (vector 'type 'ExampleScenarioInstance) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance" #f)
    (schema-field 'process 0 '* (vector 'type 'ExampleScenarioProcess) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/examplescenario.html#ExampleScenario.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/examplescenario.html#ExampleScenario.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "ExampleScenario.url" (fhir-spec (string->symbol "ExampleScenario.url") "https://build.fhir.org/examplescenario.html#ExampleScenario.url" 'element))
(register-element! "ExampleScenario.identifier" (fhir-spec (string->symbol "ExampleScenario.identifier") "https://build.fhir.org/examplescenario.html#ExampleScenario.identifier" 'element))
(register-element! "ExampleScenario.version" (fhir-spec (string->symbol "ExampleScenario.version") "https://build.fhir.org/examplescenario.html#ExampleScenario.version" 'element))
(register-element! "ExampleScenario.name" (fhir-spec (string->symbol "ExampleScenario.name") "https://build.fhir.org/examplescenario.html#ExampleScenario.name" 'element))
(register-element! "ExampleScenario.title" (fhir-spec (string->symbol "ExampleScenario.title") "https://build.fhir.org/examplescenario.html#ExampleScenario.title" 'element))
(register-element! "ExampleScenario.status" (fhir-spec (string->symbol "ExampleScenario.status") "https://build.fhir.org/examplescenario.html#ExampleScenario.status" 'element))
(register-element! "ExampleScenario.experimental" (fhir-spec (string->symbol "ExampleScenario.experimental") "https://build.fhir.org/examplescenario.html#ExampleScenario.experimental" 'element))
(register-element! "ExampleScenario.date" (fhir-spec (string->symbol "ExampleScenario.date") "https://build.fhir.org/examplescenario.html#ExampleScenario.date" 'element))
(register-element! "ExampleScenario.publisher" (fhir-spec (string->symbol "ExampleScenario.publisher") "https://build.fhir.org/examplescenario.html#ExampleScenario.publisher" 'element))
(register-element! "ExampleScenario.contact" (fhir-spec (string->symbol "ExampleScenario.contact") "https://build.fhir.org/examplescenario.html#ExampleScenario.contact" 'element))
(register-element! "ExampleScenario.description" (fhir-spec (string->symbol "ExampleScenario.description") "https://build.fhir.org/examplescenario.html#ExampleScenario.description" 'element))
(register-element! "ExampleScenario.useContext" (fhir-spec (string->symbol "ExampleScenario.useContext") "https://build.fhir.org/examplescenario.html#ExampleScenario.useContext" 'element))
(register-element! "ExampleScenario.jurisdiction" (fhir-spec (string->symbol "ExampleScenario.jurisdiction") "https://build.fhir.org/examplescenario.html#ExampleScenario.jurisdiction" 'element))
(register-element! "ExampleScenario.purpose" (fhir-spec (string->symbol "ExampleScenario.purpose") "https://build.fhir.org/examplescenario.html#ExampleScenario.purpose" 'element))
(register-element! "ExampleScenario.copyright" (fhir-spec (string->symbol "ExampleScenario.copyright") "https://build.fhir.org/examplescenario.html#ExampleScenario.copyright" 'element))
(register-element! "ExampleScenario.copyrightLabel" (fhir-spec (string->symbol "ExampleScenario.copyrightLabel") "https://build.fhir.org/examplescenario.html#ExampleScenario.copyrightLabel" 'element))
(register-element! "ExampleScenario.actor" (fhir-spec (string->symbol "ExampleScenario.actor") "https://build.fhir.org/examplescenario.html#ExampleScenario.actor" 'element))
(register-element! "ExampleScenario.instance" (fhir-spec (string->symbol "ExampleScenario.instance") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance" 'element))
(register-element! "ExampleScenario.process" (fhir-spec (string->symbol "ExampleScenario.process") "https://build.fhir.org/examplescenario.html#ExampleScenario.process" 'element))
(register-element! "ExampleScenario.versionAlgorithm[x]" (fhir-spec (string->symbol "ExampleScenario.versionAlgorithm[x]") "https://build.fhir.org/examplescenario.html#ExampleScenario.versionAlgorithm[x]" 'element))
(register-element! "ExampleScenario.versionAlgorithm[x]" (fhir-spec (string->symbol "ExampleScenario.versionAlgorithm[x]") "https://build.fhir.org/examplescenario.html#ExampleScenario.versionAlgorithm[x]" 'element))

(register-type! 'ExampleScenarioActor (fhir-spec 'ExampleScenarioActor "https://build.fhir.org/examplescenario.html#ExampleScenario.actor" 'type)
  #:schema (type-schema 'ExampleScenarioActor #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.actor"
             (list
    (schema-field 'key 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.key" #f)
    (schema-field 'type 0 1 (vector 'prim "code") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.type" #f)
    (schema-field 'title 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.title" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.description" #f)
    (schema-field 'definition 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.definition" #f)
             ) #f #f))
(register-element! "ExampleScenario.actor.key" (fhir-spec (string->symbol "ExampleScenario.actor.key") "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.key" 'element))
(register-element! "ExampleScenario.actor.type" (fhir-spec (string->symbol "ExampleScenario.actor.type") "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.type" 'element))
(register-element! "ExampleScenario.actor.title" (fhir-spec (string->symbol "ExampleScenario.actor.title") "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.title" 'element))
(register-element! "ExampleScenario.actor.description" (fhir-spec (string->symbol "ExampleScenario.actor.description") "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.description" 'element))
(register-element! "ExampleScenario.actor.definition" (fhir-spec (string->symbol "ExampleScenario.actor.definition") "https://build.fhir.org/examplescenario.html#ExampleScenario.actor.definition" 'element))

(register-type! 'ExampleScenarioInstance (fhir-spec 'ExampleScenarioInstance "https://build.fhir.org/examplescenario.html#ExampleScenario.instance" 'type)
  #:schema (type-schema 'ExampleScenarioInstance #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.instance"
             (list
    (schema-field 'key 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.key" #f)
    (schema-field 'structureType 1 1 (vector 'type 'Coding) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureType" #f)
    (schema-field 'structureVersion 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureVersion" #f)
    (schema-field 'title 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.title" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.description" #f)
    (schema-field 'content 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.content" #f)
    (schema-field 'version 0 '* (vector 'type 'ExampleScenarioInstanceVersion) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version" #f)
    (schema-field 'containedInstance 0 '* (vector 'type 'ExampleScenarioInstanceContainedInstance) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance" #f)
    (schema-field 'structureProfileCanonical 0 1 (vector 'prim "canonical") 'structureProfile "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureProfile[x]" #f)
    (schema-field 'structureProfileUri 0 1 (vector 'prim "uri") 'structureProfile "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureProfile[x]" #f)
             ) #f #f))
(register-element! "ExampleScenario.instance.key" (fhir-spec (string->symbol "ExampleScenario.instance.key") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.key" 'element))
(register-element! "ExampleScenario.instance.structureType" (fhir-spec (string->symbol "ExampleScenario.instance.structureType") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureType" 'element))
(register-element! "ExampleScenario.instance.structureVersion" (fhir-spec (string->symbol "ExampleScenario.instance.structureVersion") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureVersion" 'element))
(register-element! "ExampleScenario.instance.title" (fhir-spec (string->symbol "ExampleScenario.instance.title") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.title" 'element))
(register-element! "ExampleScenario.instance.description" (fhir-spec (string->symbol "ExampleScenario.instance.description") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.description" 'element))
(register-element! "ExampleScenario.instance.content" (fhir-spec (string->symbol "ExampleScenario.instance.content") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.content" 'element))
(register-element! "ExampleScenario.instance.version" (fhir-spec (string->symbol "ExampleScenario.instance.version") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version" 'element))
(register-element! "ExampleScenario.instance.containedInstance" (fhir-spec (string->symbol "ExampleScenario.instance.containedInstance") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance" 'element))
(register-element! "ExampleScenario.instance.structureProfile[x]" (fhir-spec (string->symbol "ExampleScenario.instance.structureProfile[x]") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureProfile[x]" 'element))
(register-element! "ExampleScenario.instance.structureProfile[x]" (fhir-spec (string->symbol "ExampleScenario.instance.structureProfile[x]") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.structureProfile[x]" 'element))

(register-type! 'ExampleScenarioInstanceVersion (fhir-spec 'ExampleScenarioInstanceVersion "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version" 'type)
  #:schema (type-schema 'ExampleScenarioInstanceVersion #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version"
             (list
    (schema-field 'key 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.key" #f)
    (schema-field 'title 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.title" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.description" #f)
    (schema-field 'content 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.content" #f)
             ) #f #f))
(register-element! "ExampleScenario.instance.version.key" (fhir-spec (string->symbol "ExampleScenario.instance.version.key") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.key" 'element))
(register-element! "ExampleScenario.instance.version.title" (fhir-spec (string->symbol "ExampleScenario.instance.version.title") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.title" 'element))
(register-element! "ExampleScenario.instance.version.description" (fhir-spec (string->symbol "ExampleScenario.instance.version.description") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.description" 'element))
(register-element! "ExampleScenario.instance.version.content" (fhir-spec (string->symbol "ExampleScenario.instance.version.content") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.version.content" 'element))

(register-type! 'ExampleScenarioInstanceContainedInstance (fhir-spec 'ExampleScenarioInstanceContainedInstance "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance" 'type)
  #:schema (type-schema 'ExampleScenarioInstanceContainedInstance #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance"
             (list
    (schema-field 'instanceReference 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance.instanceReference" #f)
    (schema-field 'versionReference 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance.versionReference" #f)
             ) #f #f))
(register-element! "ExampleScenario.instance.containedInstance.instanceReference" (fhir-spec (string->symbol "ExampleScenario.instance.containedInstance.instanceReference") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance.instanceReference" 'element))
(register-element! "ExampleScenario.instance.containedInstance.versionReference" (fhir-spec (string->symbol "ExampleScenario.instance.containedInstance.versionReference") "https://build.fhir.org/examplescenario.html#ExampleScenario.instance.containedInstance.versionReference" 'element))

(register-type! 'ExampleScenarioProcess (fhir-spec 'ExampleScenarioProcess "https://build.fhir.org/examplescenario.html#ExampleScenario.process" 'type)
  #:schema (type-schema 'ExampleScenarioProcess #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.process"
             (list
    (schema-field 'title 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.title" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.description" #f)
    (schema-field 'preConditions 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.preConditions" #f)
    (schema-field 'postConditions 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.postConditions" #f)
    (schema-field 'step 0 '* (vector 'type 'ExampleScenarioProcessStep) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step" #f)
             ) #f #f))
(register-element! "ExampleScenario.process.title" (fhir-spec (string->symbol "ExampleScenario.process.title") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.title" 'element))
(register-element! "ExampleScenario.process.description" (fhir-spec (string->symbol "ExampleScenario.process.description") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.description" 'element))
(register-element! "ExampleScenario.process.preConditions" (fhir-spec (string->symbol "ExampleScenario.process.preConditions") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.preConditions" 'element))
(register-element! "ExampleScenario.process.postConditions" (fhir-spec (string->symbol "ExampleScenario.process.postConditions") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.postConditions" 'element))
(register-element! "ExampleScenario.process.step" (fhir-spec (string->symbol "ExampleScenario.process.step") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step" 'element))

(register-type! 'ExampleScenarioProcessStep (fhir-spec 'ExampleScenarioProcessStep "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step" 'type)
  #:schema (type-schema 'ExampleScenarioProcessStep #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step"
             (list
    (schema-field 'number 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.number" #f)
    (schema-field 'process 0 1 (vector 'type 'ExampleScenarioProcess) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.process" #f)
    (schema-field 'workflow 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.workflow" #f)
    (schema-field 'operation 0 1 (vector 'type 'ExampleScenarioProcessStepOperation) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation" #f)
    (schema-field 'alternative 0 '* (vector 'type 'ExampleScenarioProcessStepAlternative) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative" #f)
    (schema-field 'pause 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.pause" #f)
             ) #f #f))
(register-element! "ExampleScenario.process.step.number" (fhir-spec (string->symbol "ExampleScenario.process.step.number") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.number" 'element))
(register-element! "ExampleScenario.process.step.process" (fhir-spec (string->symbol "ExampleScenario.process.step.process") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.process" 'element))
(register-element! "ExampleScenario.process.step.workflow" (fhir-spec (string->symbol "ExampleScenario.process.step.workflow") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.workflow" 'element))
(register-element! "ExampleScenario.process.step.operation" (fhir-spec (string->symbol "ExampleScenario.process.step.operation") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation" 'element))
(register-element! "ExampleScenario.process.step.alternative" (fhir-spec (string->symbol "ExampleScenario.process.step.alternative") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative" 'element))
(register-element! "ExampleScenario.process.step.pause" (fhir-spec (string->symbol "ExampleScenario.process.step.pause") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.pause" 'element))

(register-type! 'ExampleScenarioProcessStepOperation (fhir-spec 'ExampleScenarioProcessStepOperation "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation" 'type)
  #:schema (type-schema 'ExampleScenarioProcessStepOperation #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation"
             (list
    (schema-field 'type 0 1 (vector 'type 'Coding) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.type" #f)
    (schema-field 'title 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.title" #f)
    (schema-field 'initiator 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.initiator" #f)
    (schema-field 'receiver 0 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.receiver" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.description" #f)
    (schema-field 'initiatorActive 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.initiatorActive" #f)
    (schema-field 'receiverActive 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.receiverActive" #f)
    (schema-field 'request 0 1 (vector 'type 'ExampleScenarioInstanceContainedInstance) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.request" #f)
    (schema-field 'response 0 1 (vector 'type 'ExampleScenarioInstanceContainedInstance) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.response" #f)
             ) #f #f))
(register-element! "ExampleScenario.process.step.operation.type" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.type") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.type" 'element))
(register-element! "ExampleScenario.process.step.operation.title" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.title") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.title" 'element))
(register-element! "ExampleScenario.process.step.operation.initiator" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.initiator") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.initiator" 'element))
(register-element! "ExampleScenario.process.step.operation.receiver" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.receiver") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.receiver" 'element))
(register-element! "ExampleScenario.process.step.operation.description" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.description") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.description" 'element))
(register-element! "ExampleScenario.process.step.operation.initiatorActive" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.initiatorActive") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.initiatorActive" 'element))
(register-element! "ExampleScenario.process.step.operation.receiverActive" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.receiverActive") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.receiverActive" 'element))
(register-element! "ExampleScenario.process.step.operation.request" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.request") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.request" 'element))
(register-element! "ExampleScenario.process.step.operation.response" (fhir-spec (string->symbol "ExampleScenario.process.step.operation.response") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.operation.response" 'element))

(register-type! 'ExampleScenarioProcessStepAlternative (fhir-spec 'ExampleScenarioProcessStepAlternative "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative" 'type)
  #:schema (type-schema 'ExampleScenarioProcessStepAlternative #f 'BackboneElement "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative"
             (list
    (schema-field 'title 1 1 (vector 'prim "string") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative.title" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative.description" #f)
    (schema-field 'step 0 '* (vector 'type 'ExampleScenarioProcessStep) #f "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative.step" #f)
             ) #f #f))
(register-element! "ExampleScenario.process.step.alternative.title" (fhir-spec (string->symbol "ExampleScenario.process.step.alternative.title") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative.title" 'element))
(register-element! "ExampleScenario.process.step.alternative.description" (fhir-spec (string->symbol "ExampleScenario.process.step.alternative.description") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative.description" 'element))
(register-element! "ExampleScenario.process.step.alternative.step" (fhir-spec (string->symbol "ExampleScenario.process.step.alternative.step") "https://build.fhir.org/examplescenario.html#ExampleScenario.process.step.alternative.step" 'element))

