#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Goal (fhir-spec 'Goal "https://build.fhir.org/goal.html#Goal" 'type)
  #:schema (type-schema 'Goal #f 'DomainResource "https://build.fhir.org/goal.html#Goal"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/goal.html#Goal.identifier" #f)
    (schema-field 'lifecycleStatus 1 1 (vector 'prim "code") #f "https://build.fhir.org/goal.html#Goal.lifecycleStatus" #f)
    (schema-field 'lifecycleStatusReason 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/goal.html#Goal.lifecycleStatusReason" #f)
    (schema-field 'achievementStatus 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/goal.html#Goal.achievementStatus" #f)
    (schema-field 'achievementStatusDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/goal.html#Goal.achievementStatusDate" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/goal.html#Goal.category" #f)
    (schema-field 'continuous 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/goal.html#Goal.continuous" #f)
    (schema-field 'priority 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/goal.html#Goal.priority" #f)
    (schema-field 'description 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/goal.html#Goal.description" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/goal.html#Goal.subject" #f)
    (schema-field 'acceptance 0 '* (vector 'type 'GoalAcceptance) #f "https://build.fhir.org/goal.html#Goal.acceptance" #f)
    (schema-field 'target 0 '* (vector 'type 'GoalTarget) #f "https://build.fhir.org/goal.html#Goal.target" #f)
    (schema-field 'recorder 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/goal.html#Goal.recorder" #f)
    (schema-field 'source 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/goal.html#Goal.source" #f)
    (schema-field 'addresses 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/goal.html#Goal.addresses" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/goal.html#Goal.note" #f)
    (schema-field 'startDate 0 1 (vector 'prim "date") 'start "https://build.fhir.org/goal.html#Goal.start[x]" #f)
    (schema-field 'startCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'start "https://build.fhir.org/goal.html#Goal.start[x]" #f)
             ) #f #f))
(register-element! "Goal.identifier" (fhir-spec (string->symbol "Goal.identifier") "https://build.fhir.org/goal.html#Goal.identifier" 'element))
(register-element! "Goal.lifecycleStatus" (fhir-spec (string->symbol "Goal.lifecycleStatus") "https://build.fhir.org/goal.html#Goal.lifecycleStatus" 'element))
(register-element! "Goal.lifecycleStatusReason" (fhir-spec (string->symbol "Goal.lifecycleStatusReason") "https://build.fhir.org/goal.html#Goal.lifecycleStatusReason" 'element))
(register-element! "Goal.achievementStatus" (fhir-spec (string->symbol "Goal.achievementStatus") "https://build.fhir.org/goal.html#Goal.achievementStatus" 'element))
(register-element! "Goal.achievementStatusDate" (fhir-spec (string->symbol "Goal.achievementStatusDate") "https://build.fhir.org/goal.html#Goal.achievementStatusDate" 'element))
(register-element! "Goal.category" (fhir-spec (string->symbol "Goal.category") "https://build.fhir.org/goal.html#Goal.category" 'element))
(register-element! "Goal.continuous" (fhir-spec (string->symbol "Goal.continuous") "https://build.fhir.org/goal.html#Goal.continuous" 'element))
(register-element! "Goal.priority" (fhir-spec (string->symbol "Goal.priority") "https://build.fhir.org/goal.html#Goal.priority" 'element))
(register-element! "Goal.description" (fhir-spec (string->symbol "Goal.description") "https://build.fhir.org/goal.html#Goal.description" 'element))
(register-element! "Goal.subject" (fhir-spec (string->symbol "Goal.subject") "https://build.fhir.org/goal.html#Goal.subject" 'element))
(register-element! "Goal.acceptance" (fhir-spec (string->symbol "Goal.acceptance") "https://build.fhir.org/goal.html#Goal.acceptance" 'element))
(register-element! "Goal.target" (fhir-spec (string->symbol "Goal.target") "https://build.fhir.org/goal.html#Goal.target" 'element))
(register-element! "Goal.recorder" (fhir-spec (string->symbol "Goal.recorder") "https://build.fhir.org/goal.html#Goal.recorder" 'element))
(register-element! "Goal.source" (fhir-spec (string->symbol "Goal.source") "https://build.fhir.org/goal.html#Goal.source" 'element))
(register-element! "Goal.addresses" (fhir-spec (string->symbol "Goal.addresses") "https://build.fhir.org/goal.html#Goal.addresses" 'element))
(register-element! "Goal.note" (fhir-spec (string->symbol "Goal.note") "https://build.fhir.org/goal.html#Goal.note" 'element))
(register-element! "Goal.start[x]" (fhir-spec (string->symbol "Goal.start[x]") "https://build.fhir.org/goal.html#Goal.start[x]" 'element))
(register-element! "Goal.start[x]" (fhir-spec (string->symbol "Goal.start[x]") "https://build.fhir.org/goal.html#Goal.start[x]" 'element))

(register-type! 'GoalAcceptance (fhir-spec 'GoalAcceptance "https://build.fhir.org/goal.html#Goal.acceptance" 'type)
  #:schema (type-schema 'GoalAcceptance #f 'BackboneElement "https://build.fhir.org/goal.html#Goal.acceptance"
             (list
    (schema-field 'participant 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/goal.html#Goal.acceptance.participant" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://build.fhir.org/goal.html#Goal.acceptance.status" #f)
    (schema-field 'priority 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/goal.html#Goal.acceptance.priority" #f)
             ) #f #f))
(register-element! "Goal.acceptance.participant" (fhir-spec (string->symbol "Goal.acceptance.participant") "https://build.fhir.org/goal.html#Goal.acceptance.participant" 'element))
(register-element! "Goal.acceptance.status" (fhir-spec (string->symbol "Goal.acceptance.status") "https://build.fhir.org/goal.html#Goal.acceptance.status" 'element))
(register-element! "Goal.acceptance.priority" (fhir-spec (string->symbol "Goal.acceptance.priority") "https://build.fhir.org/goal.html#Goal.acceptance.priority" 'element))

(register-type! 'GoalTarget (fhir-spec 'GoalTarget "https://build.fhir.org/goal.html#Goal.target" 'type)
  #:schema (type-schema 'GoalTarget #f 'BackboneElement "https://build.fhir.org/goal.html#Goal.target"
             (list
    (schema-field 'measure 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/goal.html#Goal.target.measure" #f)
    (schema-field 'detailQuantity 0 1 (vector 'type 'Quantity) 'detail "https://build.fhir.org/goal.html#Goal.target.detail[x]" #f)
    (schema-field 'detailRange 0 1 (vector 'type 'Range) 'detail "https://build.fhir.org/goal.html#Goal.target.detail[x]" #f)
    (schema-field 'detailCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'detail "https://build.fhir.org/goal.html#Goal.target.detail[x]" #f)
    (schema-field 'detailString 0 1 (vector 'prim "string") 'detail "https://build.fhir.org/goal.html#Goal.target.detail[x]" #f)
    (schema-field 'detailBoolean 0 1 (vector 'prim "boolean") 'detail "https://build.fhir.org/goal.html#Goal.target.detail[x]" #f)
    (schema-field 'detailInteger 0 1 (vector 'prim "integer") 'detail "https://build.fhir.org/goal.html#Goal.target.detail[x]" #f)
    (schema-field 'detailRatio 0 1 (vector 'type 'Ratio) 'detail "https://build.fhir.org/goal.html#Goal.target.detail[x]" #f)
    (schema-field 'dueDate 0 1 (vector 'prim "date") 'due "https://build.fhir.org/goal.html#Goal.target.due[x]" #f)
    (schema-field 'dueDuration 0 1 (vector 'type 'Duration) 'due "https://build.fhir.org/goal.html#Goal.target.due[x]" #f)
             ) #f #f))
(register-element! "Goal.target.measure" (fhir-spec (string->symbol "Goal.target.measure") "https://build.fhir.org/goal.html#Goal.target.measure" 'element))
(register-element! "Goal.target.detail[x]" (fhir-spec (string->symbol "Goal.target.detail[x]") "https://build.fhir.org/goal.html#Goal.target.detail[x]" 'element))
(register-element! "Goal.target.detail[x]" (fhir-spec (string->symbol "Goal.target.detail[x]") "https://build.fhir.org/goal.html#Goal.target.detail[x]" 'element))
(register-element! "Goal.target.detail[x]" (fhir-spec (string->symbol "Goal.target.detail[x]") "https://build.fhir.org/goal.html#Goal.target.detail[x]" 'element))
(register-element! "Goal.target.detail[x]" (fhir-spec (string->symbol "Goal.target.detail[x]") "https://build.fhir.org/goal.html#Goal.target.detail[x]" 'element))
(register-element! "Goal.target.detail[x]" (fhir-spec (string->symbol "Goal.target.detail[x]") "https://build.fhir.org/goal.html#Goal.target.detail[x]" 'element))
(register-element! "Goal.target.detail[x]" (fhir-spec (string->symbol "Goal.target.detail[x]") "https://build.fhir.org/goal.html#Goal.target.detail[x]" 'element))
(register-element! "Goal.target.detail[x]" (fhir-spec (string->symbol "Goal.target.detail[x]") "https://build.fhir.org/goal.html#Goal.target.detail[x]" 'element))
(register-element! "Goal.target.due[x]" (fhir-spec (string->symbol "Goal.target.due[x]") "https://build.fhir.org/goal.html#Goal.target.due[x]" 'element))
(register-element! "Goal.target.due[x]" (fhir-spec (string->symbol "Goal.target.due[x]") "https://build.fhir.org/goal.html#Goal.target.due[x]" 'element))

