#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'GuidanceResponse (fhir-spec 'GuidanceResponse "https://build.fhir.org/guidanceresponse.html#GuidanceResponse" 'type)
  #:schema (type-schema 'GuidanceResponse #f 'DomainResource "https://build.fhir.org/guidanceresponse.html#GuidanceResponse"
             (list
    (schema-field 'requestIdentifier 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.requestIdentifier" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.status" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.encounter" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.occurrenceDateTime" #f)
    (schema-field 'performer 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.performer" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.location" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.reason" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.note" #f)
    (schema-field 'evaluationMessage 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.evaluationMessage" #f)
    (schema-field 'outputParameters 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.outputParameters" #f)
    (schema-field 'result 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.result" #f)
    (schema-field 'dataRequirement 0 '* (vector 'type 'DataRequirement) #f "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.dataRequirement" #f)
    (schema-field 'moduleUri 0 1 (vector 'prim "uri") 'module "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.module[x]" #f)
    (schema-field 'moduleCanonical 0 1 (vector 'prim "canonical") 'module "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.module[x]" #f)
    (schema-field 'moduleCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'module "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.module[x]" #f)
             ) #f #f))
(register-element! "GuidanceResponse.requestIdentifier" (fhir-spec (string->symbol "GuidanceResponse.requestIdentifier") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.requestIdentifier" 'element))
(register-element! "GuidanceResponse.identifier" (fhir-spec (string->symbol "GuidanceResponse.identifier") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.identifier" 'element))
(register-element! "GuidanceResponse.status" (fhir-spec (string->symbol "GuidanceResponse.status") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.status" 'element))
(register-element! "GuidanceResponse.subject" (fhir-spec (string->symbol "GuidanceResponse.subject") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.subject" 'element))
(register-element! "GuidanceResponse.encounter" (fhir-spec (string->symbol "GuidanceResponse.encounter") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.encounter" 'element))
(register-element! "GuidanceResponse.occurrenceDateTime" (fhir-spec (string->symbol "GuidanceResponse.occurrenceDateTime") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.occurrenceDateTime" 'element))
(register-element! "GuidanceResponse.performer" (fhir-spec (string->symbol "GuidanceResponse.performer") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.performer" 'element))
(register-element! "GuidanceResponse.location" (fhir-spec (string->symbol "GuidanceResponse.location") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.location" 'element))
(register-element! "GuidanceResponse.reason" (fhir-spec (string->symbol "GuidanceResponse.reason") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.reason" 'element))
(register-element! "GuidanceResponse.note" (fhir-spec (string->symbol "GuidanceResponse.note") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.note" 'element))
(register-element! "GuidanceResponse.evaluationMessage" (fhir-spec (string->symbol "GuidanceResponse.evaluationMessage") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.evaluationMessage" 'element))
(register-element! "GuidanceResponse.outputParameters" (fhir-spec (string->symbol "GuidanceResponse.outputParameters") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.outputParameters" 'element))
(register-element! "GuidanceResponse.result" (fhir-spec (string->symbol "GuidanceResponse.result") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.result" 'element))
(register-element! "GuidanceResponse.dataRequirement" (fhir-spec (string->symbol "GuidanceResponse.dataRequirement") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.dataRequirement" 'element))
(register-element! "GuidanceResponse.module[x]" (fhir-spec (string->symbol "GuidanceResponse.module[x]") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.module[x]" 'element))
(register-element! "GuidanceResponse.module[x]" (fhir-spec (string->symbol "GuidanceResponse.module[x]") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.module[x]" 'element))
(register-element! "GuidanceResponse.module[x]" (fhir-spec (string->symbol "GuidanceResponse.module[x]") "https://build.fhir.org/guidanceresponse.html#GuidanceResponse.module[x]" 'element))

