#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'MeasureReport (fhir-spec 'MeasureReport "https://build.fhir.org/measurereport.html#MeasureReport" 'type)
  #:schema (type-schema 'MeasureReport #f 'DomainResource "https://build.fhir.org/measurereport.html#MeasureReport"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/measurereport.html#MeasureReport.identifier" #f)
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.category" #f)
    (schema-field 'messages 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.messages" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/measurereport.html#MeasureReport.status" #f)
    (schema-field 'type 0 1 (vector 'prim "code") #f "https://build.fhir.org/measurereport.html#MeasureReport.type" #f)
    (schema-field 'dataUpdateType 0 1 (vector 'prim "code") #f "https://build.fhir.org/measurereport.html#MeasureReport.dataUpdateType" #f)
    (schema-field 'measure 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/measurereport.html#MeasureReport.measure" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.subject" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/measurereport.html#MeasureReport.date" #f)
    (schema-field 'reporter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.reporter" #f)
    (schema-field 'reportingVendor 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.reportingVendor" #f)
    (schema-field 'location 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.location" #f)
    (schema-field 'period 1 1 (vector 'type 'Period) #f "https://build.fhir.org/measurereport.html#MeasureReport.period" #f)
    (schema-field 'inputParameters 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.inputParameters" #f)
    (schema-field 'group 0 '* (vector 'type 'MeasureReportGroup) #f "https://build.fhir.org/measurereport.html#MeasureReport.group" #f)
    (schema-field 'supplementalData 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.supplementalData" #f)
    (schema-field 'evaluatedResource 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.evaluatedResource" #f)
             ) #f #f))
(register-element! "MeasureReport.identifier" (fhir-spec (string->symbol "MeasureReport.identifier") "https://build.fhir.org/measurereport.html#MeasureReport.identifier" 'element))
(register-element! "MeasureReport.category" (fhir-spec (string->symbol "MeasureReport.category") "https://build.fhir.org/measurereport.html#MeasureReport.category" 'element))
(register-element! "MeasureReport.messages" (fhir-spec (string->symbol "MeasureReport.messages") "https://build.fhir.org/measurereport.html#MeasureReport.messages" 'element))
(register-element! "MeasureReport.status" (fhir-spec (string->symbol "MeasureReport.status") "https://build.fhir.org/measurereport.html#MeasureReport.status" 'element))
(register-element! "MeasureReport.type" (fhir-spec (string->symbol "MeasureReport.type") "https://build.fhir.org/measurereport.html#MeasureReport.type" 'element))
(register-element! "MeasureReport.dataUpdateType" (fhir-spec (string->symbol "MeasureReport.dataUpdateType") "https://build.fhir.org/measurereport.html#MeasureReport.dataUpdateType" 'element))
(register-element! "MeasureReport.measure" (fhir-spec (string->symbol "MeasureReport.measure") "https://build.fhir.org/measurereport.html#MeasureReport.measure" 'element))
(register-element! "MeasureReport.subject" (fhir-spec (string->symbol "MeasureReport.subject") "https://build.fhir.org/measurereport.html#MeasureReport.subject" 'element))
(register-element! "MeasureReport.date" (fhir-spec (string->symbol "MeasureReport.date") "https://build.fhir.org/measurereport.html#MeasureReport.date" 'element))
(register-element! "MeasureReport.reporter" (fhir-spec (string->symbol "MeasureReport.reporter") "https://build.fhir.org/measurereport.html#MeasureReport.reporter" 'element))
(register-element! "MeasureReport.reportingVendor" (fhir-spec (string->symbol "MeasureReport.reportingVendor") "https://build.fhir.org/measurereport.html#MeasureReport.reportingVendor" 'element))
(register-element! "MeasureReport.location" (fhir-spec (string->symbol "MeasureReport.location") "https://build.fhir.org/measurereport.html#MeasureReport.location" 'element))
(register-element! "MeasureReport.period" (fhir-spec (string->symbol "MeasureReport.period") "https://build.fhir.org/measurereport.html#MeasureReport.period" 'element))
(register-element! "MeasureReport.inputParameters" (fhir-spec (string->symbol "MeasureReport.inputParameters") "https://build.fhir.org/measurereport.html#MeasureReport.inputParameters" 'element))
(register-element! "MeasureReport.group" (fhir-spec (string->symbol "MeasureReport.group") "https://build.fhir.org/measurereport.html#MeasureReport.group" 'element))
(register-element! "MeasureReport.supplementalData" (fhir-spec (string->symbol "MeasureReport.supplementalData") "https://build.fhir.org/measurereport.html#MeasureReport.supplementalData" 'element))
(register-element! "MeasureReport.evaluatedResource" (fhir-spec (string->symbol "MeasureReport.evaluatedResource") "https://build.fhir.org/measurereport.html#MeasureReport.evaluatedResource" 'element))

(register-type! 'MeasureReportGroup (fhir-spec 'MeasureReportGroup "https://build.fhir.org/measurereport.html#MeasureReport.group" 'type)
  #:schema (type-schema 'MeasureReportGroup #f 'BackboneElement "https://build.fhir.org/measurereport.html#MeasureReport.group"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.linkId" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.title" #f)
    (schema-field 'calculatedDate 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.calculatedDate" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.description" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.type" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.subject" #f)
    (schema-field 'scoring 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.scoring" #f)
    (schema-field 'compositeScoring 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.compositeScoring" #f)
    (schema-field 'improvementNotation 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.improvementNotation" #f)
    (schema-field 'improvementNotationGuidance 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.improvementNotationGuidance" #f)
    (schema-field 'population 0 '* (vector 'type 'MeasureReportGroupPopulation) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population" #f)
    (schema-field 'stratifier 0 '* (vector 'type 'MeasureReportGroupStratifier) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier" #f)
    (schema-field 'measureScoreQuantity 0 1 (vector 'type 'Quantity) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
    (schema-field 'measureScoreDateTime 0 1 (vector 'prim "dateTime") 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
    (schema-field 'measureScoreCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
    (schema-field 'measureScorePeriod 0 1 (vector 'type 'Period) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
    (schema-field 'measureScoreRange 0 1 (vector 'type 'Range) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
    (schema-field 'measureScoreDuration 0 1 (vector 'type 'Duration) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
    (schema-field 'measureScoreBoolean 0 1 (vector 'prim "boolean") 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
    (schema-field 'measureScoreRatio 0 1 (vector 'type 'Ratio) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" #f)
             ) #f #f))
(register-element! "MeasureReport.group.linkId" (fhir-spec (string->symbol "MeasureReport.group.linkId") "https://build.fhir.org/measurereport.html#MeasureReport.group.linkId" 'element))
(register-element! "MeasureReport.group.title" (fhir-spec (string->symbol "MeasureReport.group.title") "https://build.fhir.org/measurereport.html#MeasureReport.group.title" 'element))
(register-element! "MeasureReport.group.calculatedDate" (fhir-spec (string->symbol "MeasureReport.group.calculatedDate") "https://build.fhir.org/measurereport.html#MeasureReport.group.calculatedDate" 'element))
(register-element! "MeasureReport.group.code" (fhir-spec (string->symbol "MeasureReport.group.code") "https://build.fhir.org/measurereport.html#MeasureReport.group.code" 'element))
(register-element! "MeasureReport.group.description" (fhir-spec (string->symbol "MeasureReport.group.description") "https://build.fhir.org/measurereport.html#MeasureReport.group.description" 'element))
(register-element! "MeasureReport.group.type" (fhir-spec (string->symbol "MeasureReport.group.type") "https://build.fhir.org/measurereport.html#MeasureReport.group.type" 'element))
(register-element! "MeasureReport.group.subject" (fhir-spec (string->symbol "MeasureReport.group.subject") "https://build.fhir.org/measurereport.html#MeasureReport.group.subject" 'element))
(register-element! "MeasureReport.group.scoring" (fhir-spec (string->symbol "MeasureReport.group.scoring") "https://build.fhir.org/measurereport.html#MeasureReport.group.scoring" 'element))
(register-element! "MeasureReport.group.compositeScoring" (fhir-spec (string->symbol "MeasureReport.group.compositeScoring") "https://build.fhir.org/measurereport.html#MeasureReport.group.compositeScoring" 'element))
(register-element! "MeasureReport.group.improvementNotation" (fhir-spec (string->symbol "MeasureReport.group.improvementNotation") "https://build.fhir.org/measurereport.html#MeasureReport.group.improvementNotation" 'element))
(register-element! "MeasureReport.group.improvementNotationGuidance" (fhir-spec (string->symbol "MeasureReport.group.improvementNotationGuidance") "https://build.fhir.org/measurereport.html#MeasureReport.group.improvementNotationGuidance" 'element))
(register-element! "MeasureReport.group.population" (fhir-spec (string->symbol "MeasureReport.group.population") "https://build.fhir.org/measurereport.html#MeasureReport.group.population" 'element))
(register-element! "MeasureReport.group.stratifier" (fhir-spec (string->symbol "MeasureReport.group.stratifier") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))
(register-element! "MeasureReport.group.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.measureScore[x]" 'element))

(register-type! 'MeasureReportGroupPopulation (fhir-spec 'MeasureReportGroupPopulation "https://build.fhir.org/measurereport.html#MeasureReport.group.population" 'type)
  #:schema (type-schema 'MeasureReportGroupPopulation #f 'BackboneElement "https://build.fhir.org/measurereport.html#MeasureReport.group.population"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.linkId" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.title" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.description" #f)
    (schema-field 'count 0 1 (vector 'prim "integer") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.count" #f)
    (schema-field 'countQuantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.countQuantity" #f)
    (schema-field 'subjectResults 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.subjectResults" #f)
    (schema-field 'subjectReport 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.subjectReport" #f)
    (schema-field 'subjects 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.population.subjects" #f)
             ) #f #f))
(register-element! "MeasureReport.group.population.linkId" (fhir-spec (string->symbol "MeasureReport.group.population.linkId") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.linkId" 'element))
(register-element! "MeasureReport.group.population.title" (fhir-spec (string->symbol "MeasureReport.group.population.title") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.title" 'element))
(register-element! "MeasureReport.group.population.code" (fhir-spec (string->symbol "MeasureReport.group.population.code") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.code" 'element))
(register-element! "MeasureReport.group.population.description" (fhir-spec (string->symbol "MeasureReport.group.population.description") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.description" 'element))
(register-element! "MeasureReport.group.population.count" (fhir-spec (string->symbol "MeasureReport.group.population.count") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.count" 'element))
(register-element! "MeasureReport.group.population.countQuantity" (fhir-spec (string->symbol "MeasureReport.group.population.countQuantity") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.countQuantity" 'element))
(register-element! "MeasureReport.group.population.subjectResults" (fhir-spec (string->symbol "MeasureReport.group.population.subjectResults") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.subjectResults" 'element))
(register-element! "MeasureReport.group.population.subjectReport" (fhir-spec (string->symbol "MeasureReport.group.population.subjectReport") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.subjectReport" 'element))
(register-element! "MeasureReport.group.population.subjects" (fhir-spec (string->symbol "MeasureReport.group.population.subjects") "https://build.fhir.org/measurereport.html#MeasureReport.group.population.subjects" 'element))

(register-type! 'MeasureReportGroupStratifier (fhir-spec 'MeasureReportGroupStratifier "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier" 'type)
  #:schema (type-schema 'MeasureReportGroupStratifier #f 'BackboneElement "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.linkId" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.title" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.description" #f)
    (schema-field 'stratum 0 '* (vector 'type 'MeasureReportGroupStratifierStratum) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum" #f)
             ) #f #f))
(register-element! "MeasureReport.group.stratifier.linkId" (fhir-spec (string->symbol "MeasureReport.group.stratifier.linkId") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.linkId" 'element))
(register-element! "MeasureReport.group.stratifier.title" (fhir-spec (string->symbol "MeasureReport.group.stratifier.title") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.title" 'element))
(register-element! "MeasureReport.group.stratifier.code" (fhir-spec (string->symbol "MeasureReport.group.stratifier.code") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.code" 'element))
(register-element! "MeasureReport.group.stratifier.description" (fhir-spec (string->symbol "MeasureReport.group.stratifier.description") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.description" 'element))
(register-element! "MeasureReport.group.stratifier.stratum" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum" 'element))

(register-type! 'MeasureReportGroupStratifierStratum (fhir-spec 'MeasureReportGroupStratifierStratum "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum" 'type)
  #:schema (type-schema 'MeasureReportGroupStratifierStratum #f 'BackboneElement "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum"
             (list
    (schema-field 'component 0 '* (vector 'type 'MeasureReportGroupStratifierStratumComponent) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component" #f)
    (schema-field 'population 0 '* (vector 'type 'MeasureReportGroupStratifierStratumPopulation) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" #f)
    (schema-field 'measureScoreQuantity 0 1 (vector 'type 'Quantity) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
    (schema-field 'measureScoreDateTime 0 1 (vector 'prim "dateTime") 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
    (schema-field 'measureScoreCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
    (schema-field 'measureScorePeriod 0 1 (vector 'type 'Period) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
    (schema-field 'measureScoreRange 0 1 (vector 'type 'Range) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
    (schema-field 'measureScoreDuration 0 1 (vector 'type 'Duration) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
    (schema-field 'measureScoreBoolean 0 1 (vector 'prim "boolean") 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
    (schema-field 'measureScoreRatio 0 1 (vector 'type 'Ratio) 'measureScore "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" #f)
             ) #f #f))
(register-element! "MeasureReport.group.stratifier.stratum.component" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.population" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.measureScore[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.measureScore[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.measureScore[x]" 'element))

(register-type! 'MeasureReportGroupStratifierStratumComponent (fhir-spec 'MeasureReportGroupStratifierStratumComponent "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component" 'type)
  #:schema (type-schema 'MeasureReportGroupStratifierStratumComponent #f 'BackboneElement "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.linkId" #f)
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.description" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" #f)
             ) #f #f))
(register-element! "MeasureReport.group.stratifier.stratum.component.linkId" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.linkId") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.linkId" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.component.code" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.code") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.code" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.component.description" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.description") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.description" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.component.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.component.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.component.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.component.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.component.value[x]" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.component.value[x]") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.component.value[x]" 'element))

(register-type! 'MeasureReportGroupStratifierStratumPopulation (fhir-spec 'MeasureReportGroupStratifierStratumPopulation "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population" 'type)
  #:schema (type-schema 'MeasureReportGroupStratifierStratumPopulation #f 'BackboneElement "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.linkId" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.code" #f)
    (schema-field 'count 0 1 (vector 'prim "integer") #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.count" #f)
    (schema-field 'countQuantity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.countQuantity" #f)
    (schema-field 'subjectResults 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.subjectResults" #f)
    (schema-field 'subjectReport 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.subjectReport" #f)
    (schema-field 'subjects 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.subjects" #f)
             ) #f #f))
(register-element! "MeasureReport.group.stratifier.stratum.population.linkId" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population.linkId") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.linkId" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.population.code" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population.code") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.code" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.population.count" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population.count") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.count" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.population.countQuantity" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population.countQuantity") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.countQuantity" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.population.subjectResults" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population.subjectResults") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.subjectResults" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.population.subjectReport" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population.subjectReport") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.subjectReport" 'element))
(register-element! "MeasureReport.group.stratifier.stratum.population.subjects" (fhir-spec (string->symbol "MeasureReport.group.stratifier.stratum.population.subjects") "https://build.fhir.org/measurereport.html#MeasureReport.group.stratifier.stratum.population.subjects" 'element))

