#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Measure (fhir-spec 'Measure "https://build.fhir.org/measure.html#Measure" 'type)
  #:schema (type-schema 'Measure #f 'DomainResource "https://build.fhir.org/measure.html#Measure"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/measure.html#Measure.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/measure.html#Measure.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.title" #f)
    (schema-field 'subtitle 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.subtitle" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/measure.html#Measure.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/measure.html#Measure.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/measure.html#Measure.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/measure.html#Measure.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/measure.html#Measure.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.purpose" #f)
    (schema-field 'usage 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.usage" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/measure.html#Measure.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/measure.html#Measure.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/measure.html#Measure.effectivePeriod" #f)
    (schema-field 'reportingFrequency 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/measure.html#Measure.reportingFrequency" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/measure.html#Measure.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/measure.html#Measure.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/measure.html#Measure.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/measure.html#Measure.endorser" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://build.fhir.org/measure.html#Measure.relatedArtifact" #f)
    (schema-field 'library 0 '* (vector 'prim "canonical") #f "https://build.fhir.org/measure.html#Measure.library" #f)
    (schema-field 'disclaimer 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.disclaimer" #f)
    (schema-field 'riskAdjustment 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.riskAdjustment" #f)
    (schema-field 'rateAggregation 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.rateAggregation" #f)
    (schema-field 'rationale 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.rationale" #f)
    (schema-field 'clinicalRecommendationStatement 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.clinicalRecommendationStatement" #f)
    (schema-field 'term 0 '* (vector 'type 'MeasureTerm) #f "https://build.fhir.org/measure.html#Measure.term" #f)
    (schema-field 'group 0 '* (vector 'type 'MeasureGroup) #f "https://build.fhir.org/measure.html#Measure.group" #f)
    (schema-field 'supplementalData 0 '* (vector 'type 'MeasureSupplementalData) #f "https://build.fhir.org/measure.html#Measure.supplementalData" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/measure.html#Measure.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/measure.html#Measure.versionAlgorithm[x]" #f)
    (schema-field 'subjectCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'subject "https://build.fhir.org/measure.html#Measure.subject[x]" #f)
    (schema-field 'subjectReference 0 1 (vector 'type 'Reference) 'subject "https://build.fhir.org/measure.html#Measure.subject[x]" #f)
             ) #f #f))
(register-element! "Measure.url" (fhir-spec (string->symbol "Measure.url") "https://build.fhir.org/measure.html#Measure.url" 'element))
(register-element! "Measure.identifier" (fhir-spec (string->symbol "Measure.identifier") "https://build.fhir.org/measure.html#Measure.identifier" 'element))
(register-element! "Measure.version" (fhir-spec (string->symbol "Measure.version") "https://build.fhir.org/measure.html#Measure.version" 'element))
(register-element! "Measure.name" (fhir-spec (string->symbol "Measure.name") "https://build.fhir.org/measure.html#Measure.name" 'element))
(register-element! "Measure.title" (fhir-spec (string->symbol "Measure.title") "https://build.fhir.org/measure.html#Measure.title" 'element))
(register-element! "Measure.subtitle" (fhir-spec (string->symbol "Measure.subtitle") "https://build.fhir.org/measure.html#Measure.subtitle" 'element))
(register-element! "Measure.status" (fhir-spec (string->symbol "Measure.status") "https://build.fhir.org/measure.html#Measure.status" 'element))
(register-element! "Measure.experimental" (fhir-spec (string->symbol "Measure.experimental") "https://build.fhir.org/measure.html#Measure.experimental" 'element))
(register-element! "Measure.date" (fhir-spec (string->symbol "Measure.date") "https://build.fhir.org/measure.html#Measure.date" 'element))
(register-element! "Measure.publisher" (fhir-spec (string->symbol "Measure.publisher") "https://build.fhir.org/measure.html#Measure.publisher" 'element))
(register-element! "Measure.contact" (fhir-spec (string->symbol "Measure.contact") "https://build.fhir.org/measure.html#Measure.contact" 'element))
(register-element! "Measure.description" (fhir-spec (string->symbol "Measure.description") "https://build.fhir.org/measure.html#Measure.description" 'element))
(register-element! "Measure.useContext" (fhir-spec (string->symbol "Measure.useContext") "https://build.fhir.org/measure.html#Measure.useContext" 'element))
(register-element! "Measure.jurisdiction" (fhir-spec (string->symbol "Measure.jurisdiction") "https://build.fhir.org/measure.html#Measure.jurisdiction" 'element))
(register-element! "Measure.purpose" (fhir-spec (string->symbol "Measure.purpose") "https://build.fhir.org/measure.html#Measure.purpose" 'element))
(register-element! "Measure.usage" (fhir-spec (string->symbol "Measure.usage") "https://build.fhir.org/measure.html#Measure.usage" 'element))
(register-element! "Measure.copyright" (fhir-spec (string->symbol "Measure.copyright") "https://build.fhir.org/measure.html#Measure.copyright" 'element))
(register-element! "Measure.copyrightLabel" (fhir-spec (string->symbol "Measure.copyrightLabel") "https://build.fhir.org/measure.html#Measure.copyrightLabel" 'element))
(register-element! "Measure.approvalDate" (fhir-spec (string->symbol "Measure.approvalDate") "https://build.fhir.org/measure.html#Measure.approvalDate" 'element))
(register-element! "Measure.lastReviewDate" (fhir-spec (string->symbol "Measure.lastReviewDate") "https://build.fhir.org/measure.html#Measure.lastReviewDate" 'element))
(register-element! "Measure.effectivePeriod" (fhir-spec (string->symbol "Measure.effectivePeriod") "https://build.fhir.org/measure.html#Measure.effectivePeriod" 'element))
(register-element! "Measure.reportingFrequency" (fhir-spec (string->symbol "Measure.reportingFrequency") "https://build.fhir.org/measure.html#Measure.reportingFrequency" 'element))
(register-element! "Measure.author" (fhir-spec (string->symbol "Measure.author") "https://build.fhir.org/measure.html#Measure.author" 'element))
(register-element! "Measure.editor" (fhir-spec (string->symbol "Measure.editor") "https://build.fhir.org/measure.html#Measure.editor" 'element))
(register-element! "Measure.reviewer" (fhir-spec (string->symbol "Measure.reviewer") "https://build.fhir.org/measure.html#Measure.reviewer" 'element))
(register-element! "Measure.endorser" (fhir-spec (string->symbol "Measure.endorser") "https://build.fhir.org/measure.html#Measure.endorser" 'element))
(register-element! "Measure.relatedArtifact" (fhir-spec (string->symbol "Measure.relatedArtifact") "https://build.fhir.org/measure.html#Measure.relatedArtifact" 'element))
(register-element! "Measure.library" (fhir-spec (string->symbol "Measure.library") "https://build.fhir.org/measure.html#Measure.library" 'element))
(register-element! "Measure.disclaimer" (fhir-spec (string->symbol "Measure.disclaimer") "https://build.fhir.org/measure.html#Measure.disclaimer" 'element))
(register-element! "Measure.riskAdjustment" (fhir-spec (string->symbol "Measure.riskAdjustment") "https://build.fhir.org/measure.html#Measure.riskAdjustment" 'element))
(register-element! "Measure.rateAggregation" (fhir-spec (string->symbol "Measure.rateAggregation") "https://build.fhir.org/measure.html#Measure.rateAggregation" 'element))
(register-element! "Measure.rationale" (fhir-spec (string->symbol "Measure.rationale") "https://build.fhir.org/measure.html#Measure.rationale" 'element))
(register-element! "Measure.clinicalRecommendationStatement" (fhir-spec (string->symbol "Measure.clinicalRecommendationStatement") "https://build.fhir.org/measure.html#Measure.clinicalRecommendationStatement" 'element))
(register-element! "Measure.term" (fhir-spec (string->symbol "Measure.term") "https://build.fhir.org/measure.html#Measure.term" 'element))
(register-element! "Measure.group" (fhir-spec (string->symbol "Measure.group") "https://build.fhir.org/measure.html#Measure.group" 'element))
(register-element! "Measure.supplementalData" (fhir-spec (string->symbol "Measure.supplementalData") "https://build.fhir.org/measure.html#Measure.supplementalData" 'element))
(register-element! "Measure.versionAlgorithm[x]" (fhir-spec (string->symbol "Measure.versionAlgorithm[x]") "https://build.fhir.org/measure.html#Measure.versionAlgorithm[x]" 'element))
(register-element! "Measure.versionAlgorithm[x]" (fhir-spec (string->symbol "Measure.versionAlgorithm[x]") "https://build.fhir.org/measure.html#Measure.versionAlgorithm[x]" 'element))
(register-element! "Measure.subject[x]" (fhir-spec (string->symbol "Measure.subject[x]") "https://build.fhir.org/measure.html#Measure.subject[x]" 'element))
(register-element! "Measure.subject[x]" (fhir-spec (string->symbol "Measure.subject[x]") "https://build.fhir.org/measure.html#Measure.subject[x]" 'element))

(register-type! 'MeasureTerm (fhir-spec 'MeasureTerm "https://build.fhir.org/measure.html#Measure.term" 'type)
  #:schema (type-schema 'MeasureTerm #f 'BackboneElement "https://build.fhir.org/measure.html#Measure.term"
             (list
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.term.code" #f)
    (schema-field 'definition 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.term.definition" #f)
             ) #f #f))
(register-element! "Measure.term.code" (fhir-spec (string->symbol "Measure.term.code") "https://build.fhir.org/measure.html#Measure.term.code" 'element))
(register-element! "Measure.term.definition" (fhir-spec (string->symbol "Measure.term.definition") "https://build.fhir.org/measure.html#Measure.term.definition" 'element))

(register-type! 'MeasureGroup (fhir-spec 'MeasureGroup "https://build.fhir.org/measure.html#Measure.group" 'type)
  #:schema (type-schema 'MeasureGroup #f 'BackboneElement "https://build.fhir.org/measure.html#Measure.group"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.linkId" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.title" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.group.description" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.type" #f)
    (schema-field 'basis 0 1 (vector 'prim "code") #f "https://build.fhir.org/measure.html#Measure.group.basis" #f)
    (schema-field 'basisRequirement 0 '* (vector 'type 'DataRequirement) #f "https://build.fhir.org/measure.html#Measure.group.basisRequirement" #f)
    (schema-field 'scoring 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.scoring" #f)
    (schema-field 'scoringUnit 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.scoringUnit" #f)
    (schema-field 'scoringPrecision 0 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/measure.html#Measure.group.scoringPrecision" #f)
    (schema-field 'compositeScoring 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.compositeScoring" #f)
    (schema-field 'component 0 '* (vector 'type 'MeasureGroupComponent) #f "https://build.fhir.org/measure.html#Measure.group.component" #f)
    (schema-field 'rateAggregation 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.group.rateAggregation" #f)
    (schema-field 'improvementNotation 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.improvementNotation" #f)
    (schema-field 'improvementNotationGuidance 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.group.improvementNotationGuidance" #f)
    (schema-field 'library 0 '* (vector 'prim "canonical") #f "https://build.fhir.org/measure.html#Measure.group.library" #f)
    (schema-field 'population 0 '* (vector 'type 'MeasureGroupPopulation) #f "https://build.fhir.org/measure.html#Measure.group.population" #f)
    (schema-field 'stratifier 0 '* (vector 'type 'MeasureGroupStratifier) #f "https://build.fhir.org/measure.html#Measure.group.stratifier" #f)
    (schema-field 'subjectCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'subject "https://build.fhir.org/measure.html#Measure.group.subject[x]" #f)
    (schema-field 'subjectReference 0 1 (vector 'type 'Reference) 'subject "https://build.fhir.org/measure.html#Measure.group.subject[x]" #f)
             ) #f #f))
(register-element! "Measure.group.linkId" (fhir-spec (string->symbol "Measure.group.linkId") "https://build.fhir.org/measure.html#Measure.group.linkId" 'element))
(register-element! "Measure.group.title" (fhir-spec (string->symbol "Measure.group.title") "https://build.fhir.org/measure.html#Measure.group.title" 'element))
(register-element! "Measure.group.code" (fhir-spec (string->symbol "Measure.group.code") "https://build.fhir.org/measure.html#Measure.group.code" 'element))
(register-element! "Measure.group.description" (fhir-spec (string->symbol "Measure.group.description") "https://build.fhir.org/measure.html#Measure.group.description" 'element))
(register-element! "Measure.group.type" (fhir-spec (string->symbol "Measure.group.type") "https://build.fhir.org/measure.html#Measure.group.type" 'element))
(register-element! "Measure.group.basis" (fhir-spec (string->symbol "Measure.group.basis") "https://build.fhir.org/measure.html#Measure.group.basis" 'element))
(register-element! "Measure.group.basisRequirement" (fhir-spec (string->symbol "Measure.group.basisRequirement") "https://build.fhir.org/measure.html#Measure.group.basisRequirement" 'element))
(register-element! "Measure.group.scoring" (fhir-spec (string->symbol "Measure.group.scoring") "https://build.fhir.org/measure.html#Measure.group.scoring" 'element))
(register-element! "Measure.group.scoringUnit" (fhir-spec (string->symbol "Measure.group.scoringUnit") "https://build.fhir.org/measure.html#Measure.group.scoringUnit" 'element))
(register-element! "Measure.group.scoringPrecision" (fhir-spec (string->symbol "Measure.group.scoringPrecision") "https://build.fhir.org/measure.html#Measure.group.scoringPrecision" 'element))
(register-element! "Measure.group.compositeScoring" (fhir-spec (string->symbol "Measure.group.compositeScoring") "https://build.fhir.org/measure.html#Measure.group.compositeScoring" 'element))
(register-element! "Measure.group.component" (fhir-spec (string->symbol "Measure.group.component") "https://build.fhir.org/measure.html#Measure.group.component" 'element))
(register-element! "Measure.group.rateAggregation" (fhir-spec (string->symbol "Measure.group.rateAggregation") "https://build.fhir.org/measure.html#Measure.group.rateAggregation" 'element))
(register-element! "Measure.group.improvementNotation" (fhir-spec (string->symbol "Measure.group.improvementNotation") "https://build.fhir.org/measure.html#Measure.group.improvementNotation" 'element))
(register-element! "Measure.group.improvementNotationGuidance" (fhir-spec (string->symbol "Measure.group.improvementNotationGuidance") "https://build.fhir.org/measure.html#Measure.group.improvementNotationGuidance" 'element))
(register-element! "Measure.group.library" (fhir-spec (string->symbol "Measure.group.library") "https://build.fhir.org/measure.html#Measure.group.library" 'element))
(register-element! "Measure.group.population" (fhir-spec (string->symbol "Measure.group.population") "https://build.fhir.org/measure.html#Measure.group.population" 'element))
(register-element! "Measure.group.stratifier" (fhir-spec (string->symbol "Measure.group.stratifier") "https://build.fhir.org/measure.html#Measure.group.stratifier" 'element))
(register-element! "Measure.group.subject[x]" (fhir-spec (string->symbol "Measure.group.subject[x]") "https://build.fhir.org/measure.html#Measure.group.subject[x]" 'element))
(register-element! "Measure.group.subject[x]" (fhir-spec (string->symbol "Measure.group.subject[x]") "https://build.fhir.org/measure.html#Measure.group.subject[x]" 'element))

(register-type! 'MeasureGroupComponent (fhir-spec 'MeasureGroupComponent "https://build.fhir.org/measure.html#Measure.group.component" 'type)
  #:schema (type-schema 'MeasureGroupComponent #f 'BackboneElement "https://build.fhir.org/measure.html#Measure.group.component"
             (list
    (schema-field 'measure 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/measure.html#Measure.group.component.measure" #f)
    (schema-field 'groupId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.component.groupId" #f)
    (schema-field 'weight 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/measure.html#Measure.group.component.weight" #f)
             ) #f #f))
(register-element! "Measure.group.component.measure" (fhir-spec (string->symbol "Measure.group.component.measure") "https://build.fhir.org/measure.html#Measure.group.component.measure" 'element))
(register-element! "Measure.group.component.groupId" (fhir-spec (string->symbol "Measure.group.component.groupId") "https://build.fhir.org/measure.html#Measure.group.component.groupId" 'element))
(register-element! "Measure.group.component.weight" (fhir-spec (string->symbol "Measure.group.component.weight") "https://build.fhir.org/measure.html#Measure.group.component.weight" 'element))

(register-type! 'MeasureGroupPopulation (fhir-spec 'MeasureGroupPopulation "https://build.fhir.org/measure.html#Measure.group.population" 'type)
  #:schema (type-schema 'MeasureGroupPopulation #f 'BackboneElement "https://build.fhir.org/measure.html#Measure.group.population"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.population.linkId" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.population.title" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.population.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.group.population.description" #f)
    (schema-field 'criteria 0 1 (vector 'type 'Expression) #f "https://build.fhir.org/measure.html#Measure.group.population.criteria" #f)
    (schema-field 'groupDefinition 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measure.html#Measure.group.population.groupDefinition" #f)
    (schema-field 'inputPopulationId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.population.inputPopulationId" #f)
    (schema-field 'aggregateMethod 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.population.aggregateMethod" #f)
             ) #f #f))
(register-element! "Measure.group.population.linkId" (fhir-spec (string->symbol "Measure.group.population.linkId") "https://build.fhir.org/measure.html#Measure.group.population.linkId" 'element))
(register-element! "Measure.group.population.title" (fhir-spec (string->symbol "Measure.group.population.title") "https://build.fhir.org/measure.html#Measure.group.population.title" 'element))
(register-element! "Measure.group.population.code" (fhir-spec (string->symbol "Measure.group.population.code") "https://build.fhir.org/measure.html#Measure.group.population.code" 'element))
(register-element! "Measure.group.population.description" (fhir-spec (string->symbol "Measure.group.population.description") "https://build.fhir.org/measure.html#Measure.group.population.description" 'element))
(register-element! "Measure.group.population.criteria" (fhir-spec (string->symbol "Measure.group.population.criteria") "https://build.fhir.org/measure.html#Measure.group.population.criteria" 'element))
(register-element! "Measure.group.population.groupDefinition" (fhir-spec (string->symbol "Measure.group.population.groupDefinition") "https://build.fhir.org/measure.html#Measure.group.population.groupDefinition" 'element))
(register-element! "Measure.group.population.inputPopulationId" (fhir-spec (string->symbol "Measure.group.population.inputPopulationId") "https://build.fhir.org/measure.html#Measure.group.population.inputPopulationId" 'element))
(register-element! "Measure.group.population.aggregateMethod" (fhir-spec (string->symbol "Measure.group.population.aggregateMethod") "https://build.fhir.org/measure.html#Measure.group.population.aggregateMethod" 'element))

(register-type! 'MeasureGroupStratifier (fhir-spec 'MeasureGroupStratifier "https://build.fhir.org/measure.html#Measure.group.stratifier" 'type)
  #:schema (type-schema 'MeasureGroupStratifier #f 'BackboneElement "https://build.fhir.org/measure.html#Measure.group.stratifier"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.stratifier.linkId" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.stratifier.title" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.stratifier.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.group.stratifier.description" #f)
    (schema-field 'criteria 0 1 (vector 'type 'Expression) #f "https://build.fhir.org/measure.html#Measure.group.stratifier.criteria" #f)
    (schema-field 'groupDefinition 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measure.html#Measure.group.stratifier.groupDefinition" #f)
    (schema-field 'component 0 '* (vector 'type 'MeasureGroupStratifierComponent) #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component" #f)
             ) #f #f))
(register-element! "Measure.group.stratifier.linkId" (fhir-spec (string->symbol "Measure.group.stratifier.linkId") "https://build.fhir.org/measure.html#Measure.group.stratifier.linkId" 'element))
(register-element! "Measure.group.stratifier.title" (fhir-spec (string->symbol "Measure.group.stratifier.title") "https://build.fhir.org/measure.html#Measure.group.stratifier.title" 'element))
(register-element! "Measure.group.stratifier.code" (fhir-spec (string->symbol "Measure.group.stratifier.code") "https://build.fhir.org/measure.html#Measure.group.stratifier.code" 'element))
(register-element! "Measure.group.stratifier.description" (fhir-spec (string->symbol "Measure.group.stratifier.description") "https://build.fhir.org/measure.html#Measure.group.stratifier.description" 'element))
(register-element! "Measure.group.stratifier.criteria" (fhir-spec (string->symbol "Measure.group.stratifier.criteria") "https://build.fhir.org/measure.html#Measure.group.stratifier.criteria" 'element))
(register-element! "Measure.group.stratifier.groupDefinition" (fhir-spec (string->symbol "Measure.group.stratifier.groupDefinition") "https://build.fhir.org/measure.html#Measure.group.stratifier.groupDefinition" 'element))
(register-element! "Measure.group.stratifier.component" (fhir-spec (string->symbol "Measure.group.stratifier.component") "https://build.fhir.org/measure.html#Measure.group.stratifier.component" 'element))

(register-type! 'MeasureGroupStratifierComponent (fhir-spec 'MeasureGroupStratifierComponent "https://build.fhir.org/measure.html#Measure.group.stratifier.component" 'type)
  #:schema (type-schema 'MeasureGroupStratifierComponent #f 'BackboneElement "https://build.fhir.org/measure.html#Measure.group.stratifier.component"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component.linkId" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component.description" #f)
    (schema-field 'criteria 0 1 (vector 'type 'Expression) #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component.criteria" #f)
    (schema-field 'groupDefinition 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component.groupDefinition" #f)
    (schema-field 'valueSet 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component.valueSet" #f)
    (schema-field 'unit 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.group.stratifier.component.unit" #f)
             ) #f #f))
(register-element! "Measure.group.stratifier.component.linkId" (fhir-spec (string->symbol "Measure.group.stratifier.component.linkId") "https://build.fhir.org/measure.html#Measure.group.stratifier.component.linkId" 'element))
(register-element! "Measure.group.stratifier.component.code" (fhir-spec (string->symbol "Measure.group.stratifier.component.code") "https://build.fhir.org/measure.html#Measure.group.stratifier.component.code" 'element))
(register-element! "Measure.group.stratifier.component.description" (fhir-spec (string->symbol "Measure.group.stratifier.component.description") "https://build.fhir.org/measure.html#Measure.group.stratifier.component.description" 'element))
(register-element! "Measure.group.stratifier.component.criteria" (fhir-spec (string->symbol "Measure.group.stratifier.component.criteria") "https://build.fhir.org/measure.html#Measure.group.stratifier.component.criteria" 'element))
(register-element! "Measure.group.stratifier.component.groupDefinition" (fhir-spec (string->symbol "Measure.group.stratifier.component.groupDefinition") "https://build.fhir.org/measure.html#Measure.group.stratifier.component.groupDefinition" 'element))
(register-element! "Measure.group.stratifier.component.valueSet" (fhir-spec (string->symbol "Measure.group.stratifier.component.valueSet") "https://build.fhir.org/measure.html#Measure.group.stratifier.component.valueSet" 'element))
(register-element! "Measure.group.stratifier.component.unit" (fhir-spec (string->symbol "Measure.group.stratifier.component.unit") "https://build.fhir.org/measure.html#Measure.group.stratifier.component.unit" 'element))

(register-type! 'MeasureSupplementalData (fhir-spec 'MeasureSupplementalData "https://build.fhir.org/measure.html#Measure.supplementalData" 'type)
  #:schema (type-schema 'MeasureSupplementalData #f 'BackboneElement "https://build.fhir.org/measure.html#Measure.supplementalData"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.supplementalData.linkId" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.supplementalData.code" #f)
    (schema-field 'usage 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/measure.html#Measure.supplementalData.usage" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/measure.html#Measure.supplementalData.description" #f)
    (schema-field 'criteria 1 1 (vector 'type 'Expression) #f "https://build.fhir.org/measure.html#Measure.supplementalData.criteria" #f)
    (schema-field 'valueSet 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/measure.html#Measure.supplementalData.valueSet" #f)
    (schema-field 'unit 0 1 (vector 'prim "string") #f "https://build.fhir.org/measure.html#Measure.supplementalData.unit" #f)
             ) #f #f))
(register-element! "Measure.supplementalData.linkId" (fhir-spec (string->symbol "Measure.supplementalData.linkId") "https://build.fhir.org/measure.html#Measure.supplementalData.linkId" 'element))
(register-element! "Measure.supplementalData.code" (fhir-spec (string->symbol "Measure.supplementalData.code") "https://build.fhir.org/measure.html#Measure.supplementalData.code" 'element))
(register-element! "Measure.supplementalData.usage" (fhir-spec (string->symbol "Measure.supplementalData.usage") "https://build.fhir.org/measure.html#Measure.supplementalData.usage" 'element))
(register-element! "Measure.supplementalData.description" (fhir-spec (string->symbol "Measure.supplementalData.description") "https://build.fhir.org/measure.html#Measure.supplementalData.description" 'element))
(register-element! "Measure.supplementalData.criteria" (fhir-spec (string->symbol "Measure.supplementalData.criteria") "https://build.fhir.org/measure.html#Measure.supplementalData.criteria" 'element))
(register-element! "Measure.supplementalData.valueSet" (fhir-spec (string->symbol "Measure.supplementalData.valueSet") "https://build.fhir.org/measure.html#Measure.supplementalData.valueSet" 'element))
(register-element! "Measure.supplementalData.unit" (fhir-spec (string->symbol "Measure.supplementalData.unit") "https://build.fhir.org/measure.html#Measure.supplementalData.unit" 'element))

