#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'MedicationAdministration (fhir-spec 'MedicationAdministration "https://build.fhir.org/medicationadministration.html#MedicationAdministration" 'type)
  #:schema (type-schema 'MedicationAdministration #f 'DomainResource "https://build.fhir.org/medicationadministration.html#MedicationAdministration"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.basedOn" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.status" #f)
    (schema-field 'statusReason 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.statusReason" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.category" #f)
    (schema-field 'medication 1 1 (vector 'type 'CodeableReference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.medication" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.encounter" #f)
    (schema-field 'supportingInformation 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.supportingInformation" #f)
    (schema-field 'recorded 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.recorded" #f)
    (schema-field 'isSubPotent 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.isSubPotent" #f)
    (schema-field 'subPotentReason 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.subPotentReason" #f)
    (schema-field 'performer 0 '* (vector 'type 'MedicationAdministrationPerformer) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.reason" #f)
    (schema-field 'request 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.request" #f)
    (schema-field 'device 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.device" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.note" #f)
    (schema-field 'dosage 0 1 (vector 'type 'MedicationAdministrationDosage) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage" #f)
    (schema-field 'eventHistory 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.eventHistory" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://build.fhir.org/medicationadministration.html#MedicationAdministration.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://build.fhir.org/medicationadministration.html#MedicationAdministration.occurrence[x]" #f)
    (schema-field 'occurrenceTiming 0 1 (vector 'type 'Timing) 'occurrence "https://build.fhir.org/medicationadministration.html#MedicationAdministration.occurrence[x]" #f)
             ) #f #f))
(register-element! "MedicationAdministration.identifier" (fhir-spec (string->symbol "MedicationAdministration.identifier") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.identifier" 'element))
(register-element! "MedicationAdministration.basedOn" (fhir-spec (string->symbol "MedicationAdministration.basedOn") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.basedOn" 'element))
(register-element! "MedicationAdministration.partOf" (fhir-spec (string->symbol "MedicationAdministration.partOf") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.partOf" 'element))
(register-element! "MedicationAdministration.status" (fhir-spec (string->symbol "MedicationAdministration.status") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.status" 'element))
(register-element! "MedicationAdministration.statusReason" (fhir-spec (string->symbol "MedicationAdministration.statusReason") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.statusReason" 'element))
(register-element! "MedicationAdministration.category" (fhir-spec (string->symbol "MedicationAdministration.category") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.category" 'element))
(register-element! "MedicationAdministration.medication" (fhir-spec (string->symbol "MedicationAdministration.medication") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.medication" 'element))
(register-element! "MedicationAdministration.subject" (fhir-spec (string->symbol "MedicationAdministration.subject") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.subject" 'element))
(register-element! "MedicationAdministration.encounter" (fhir-spec (string->symbol "MedicationAdministration.encounter") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.encounter" 'element))
(register-element! "MedicationAdministration.supportingInformation" (fhir-spec (string->symbol "MedicationAdministration.supportingInformation") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.supportingInformation" 'element))
(register-element! "MedicationAdministration.recorded" (fhir-spec (string->symbol "MedicationAdministration.recorded") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.recorded" 'element))
(register-element! "MedicationAdministration.isSubPotent" (fhir-spec (string->symbol "MedicationAdministration.isSubPotent") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.isSubPotent" 'element))
(register-element! "MedicationAdministration.subPotentReason" (fhir-spec (string->symbol "MedicationAdministration.subPotentReason") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.subPotentReason" 'element))
(register-element! "MedicationAdministration.performer" (fhir-spec (string->symbol "MedicationAdministration.performer") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer" 'element))
(register-element! "MedicationAdministration.reason" (fhir-spec (string->symbol "MedicationAdministration.reason") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.reason" 'element))
(register-element! "MedicationAdministration.request" (fhir-spec (string->symbol "MedicationAdministration.request") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.request" 'element))
(register-element! "MedicationAdministration.device" (fhir-spec (string->symbol "MedicationAdministration.device") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.device" 'element))
(register-element! "MedicationAdministration.note" (fhir-spec (string->symbol "MedicationAdministration.note") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.note" 'element))
(register-element! "MedicationAdministration.dosage" (fhir-spec (string->symbol "MedicationAdministration.dosage") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage" 'element))
(register-element! "MedicationAdministration.eventHistory" (fhir-spec (string->symbol "MedicationAdministration.eventHistory") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.eventHistory" 'element))
(register-element! "MedicationAdministration.occurrence[x]" (fhir-spec (string->symbol "MedicationAdministration.occurrence[x]") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.occurrence[x]" 'element))
(register-element! "MedicationAdministration.occurrence[x]" (fhir-spec (string->symbol "MedicationAdministration.occurrence[x]") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.occurrence[x]" 'element))
(register-element! "MedicationAdministration.occurrence[x]" (fhir-spec (string->symbol "MedicationAdministration.occurrence[x]") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.occurrence[x]" 'element))

(register-type! 'MedicationAdministrationPerformer (fhir-spec 'MedicationAdministrationPerformer "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer" 'type)
  #:schema (type-schema 'MedicationAdministrationPerformer #f 'BackboneElement "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'CodeableReference) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer.actor" #f)
             ) #f #f))
(register-element! "MedicationAdministration.performer.function" (fhir-spec (string->symbol "MedicationAdministration.performer.function") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer.function" 'element))
(register-element! "MedicationAdministration.performer.actor" (fhir-spec (string->symbol "MedicationAdministration.performer.actor") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.performer.actor" 'element))

(register-type! 'MedicationAdministrationDosage (fhir-spec 'MedicationAdministrationDosage "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage" 'type)
  #:schema (type-schema 'MedicationAdministrationDosage #f 'BackboneElement "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage"
             (list
    (schema-field 'text 0 1 (vector 'prim "string") #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.text" #f)
    (schema-field 'site 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.site" #f)
    (schema-field 'route 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.route" #f)
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.method" #f)
    (schema-field 'dose 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.dose" #f)
    (schema-field 'rateRatio 0 1 (vector 'type 'Ratio) 'rate "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.rate[x]" #f)
    (schema-field 'rateQuantity 0 1 (vector 'type 'Quantity) 'rate "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.rate[x]" #f)
             ) #f #f))
(register-element! "MedicationAdministration.dosage.text" (fhir-spec (string->symbol "MedicationAdministration.dosage.text") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.text" 'element))
(register-element! "MedicationAdministration.dosage.site" (fhir-spec (string->symbol "MedicationAdministration.dosage.site") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.site" 'element))
(register-element! "MedicationAdministration.dosage.route" (fhir-spec (string->symbol "MedicationAdministration.dosage.route") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.route" 'element))
(register-element! "MedicationAdministration.dosage.method" (fhir-spec (string->symbol "MedicationAdministration.dosage.method") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.method" 'element))
(register-element! "MedicationAdministration.dosage.dose" (fhir-spec (string->symbol "MedicationAdministration.dosage.dose") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.dose" 'element))
(register-element! "MedicationAdministration.dosage.rate[x]" (fhir-spec (string->symbol "MedicationAdministration.dosage.rate[x]") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.rate[x]" 'element))
(register-element! "MedicationAdministration.dosage.rate[x]" (fhir-spec (string->symbol "MedicationAdministration.dosage.rate[x]") "https://build.fhir.org/medicationadministration.html#MedicationAdministration.dosage.rate[x]" 'element))

