#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'MessageDefinition (fhir-spec 'MessageDefinition "https://build.fhir.org/messagedefinition.html#MessageDefinition" 'type)
  #:schema (type-schema 'MessageDefinition #f 'DomainResource "https://build.fhir.org/messagedefinition.html#MessageDefinition"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.title" #f)
    (schema-field 'replaces 0 '* (vector 'prim "canonical") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.replaces" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.experimental" #f)
    (schema-field 'date 1 1 (vector 'prim "dateTime") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.copyrightLabel" #f)
    (schema-field 'base 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.base" #f)
    (schema-field 'parent 0 '* (vector 'prim "canonical") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.parent" #f)
    (schema-field 'category 0 1 (vector 'prim "code") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.category" #f)
    (schema-field 'focus 0 '* (vector 'type 'MessageDefinitionFocus) #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus" #f)
    (schema-field 'responseRequired 0 1 (vector 'prim "code") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.responseRequired" #f)
    (schema-field 'allowedResponse 0 '* (vector 'type 'MessageDefinitionAllowedResponse) #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/messagedefinition.html#MessageDefinition.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/messagedefinition.html#MessageDefinition.versionAlgorithm[x]" #f)
    (schema-field 'eventCoding 0 1 (vector 'type 'Coding) 'event "https://build.fhir.org/messagedefinition.html#MessageDefinition.event[x]" #f)
    (schema-field 'eventUri 0 1 (vector 'prim "uri") 'event "https://build.fhir.org/messagedefinition.html#MessageDefinition.event[x]" #f)
             ) #f #f))
(register-element! "MessageDefinition.url" (fhir-spec (string->symbol "MessageDefinition.url") "https://build.fhir.org/messagedefinition.html#MessageDefinition.url" 'element))
(register-element! "MessageDefinition.identifier" (fhir-spec (string->symbol "MessageDefinition.identifier") "https://build.fhir.org/messagedefinition.html#MessageDefinition.identifier" 'element))
(register-element! "MessageDefinition.version" (fhir-spec (string->symbol "MessageDefinition.version") "https://build.fhir.org/messagedefinition.html#MessageDefinition.version" 'element))
(register-element! "MessageDefinition.name" (fhir-spec (string->symbol "MessageDefinition.name") "https://build.fhir.org/messagedefinition.html#MessageDefinition.name" 'element))
(register-element! "MessageDefinition.title" (fhir-spec (string->symbol "MessageDefinition.title") "https://build.fhir.org/messagedefinition.html#MessageDefinition.title" 'element))
(register-element! "MessageDefinition.replaces" (fhir-spec (string->symbol "MessageDefinition.replaces") "https://build.fhir.org/messagedefinition.html#MessageDefinition.replaces" 'element))
(register-element! "MessageDefinition.status" (fhir-spec (string->symbol "MessageDefinition.status") "https://build.fhir.org/messagedefinition.html#MessageDefinition.status" 'element))
(register-element! "MessageDefinition.experimental" (fhir-spec (string->symbol "MessageDefinition.experimental") "https://build.fhir.org/messagedefinition.html#MessageDefinition.experimental" 'element))
(register-element! "MessageDefinition.date" (fhir-spec (string->symbol "MessageDefinition.date") "https://build.fhir.org/messagedefinition.html#MessageDefinition.date" 'element))
(register-element! "MessageDefinition.publisher" (fhir-spec (string->symbol "MessageDefinition.publisher") "https://build.fhir.org/messagedefinition.html#MessageDefinition.publisher" 'element))
(register-element! "MessageDefinition.contact" (fhir-spec (string->symbol "MessageDefinition.contact") "https://build.fhir.org/messagedefinition.html#MessageDefinition.contact" 'element))
(register-element! "MessageDefinition.description" (fhir-spec (string->symbol "MessageDefinition.description") "https://build.fhir.org/messagedefinition.html#MessageDefinition.description" 'element))
(register-element! "MessageDefinition.useContext" (fhir-spec (string->symbol "MessageDefinition.useContext") "https://build.fhir.org/messagedefinition.html#MessageDefinition.useContext" 'element))
(register-element! "MessageDefinition.jurisdiction" (fhir-spec (string->symbol "MessageDefinition.jurisdiction") "https://build.fhir.org/messagedefinition.html#MessageDefinition.jurisdiction" 'element))
(register-element! "MessageDefinition.purpose" (fhir-spec (string->symbol "MessageDefinition.purpose") "https://build.fhir.org/messagedefinition.html#MessageDefinition.purpose" 'element))
(register-element! "MessageDefinition.copyright" (fhir-spec (string->symbol "MessageDefinition.copyright") "https://build.fhir.org/messagedefinition.html#MessageDefinition.copyright" 'element))
(register-element! "MessageDefinition.copyrightLabel" (fhir-spec (string->symbol "MessageDefinition.copyrightLabel") "https://build.fhir.org/messagedefinition.html#MessageDefinition.copyrightLabel" 'element))
(register-element! "MessageDefinition.base" (fhir-spec (string->symbol "MessageDefinition.base") "https://build.fhir.org/messagedefinition.html#MessageDefinition.base" 'element))
(register-element! "MessageDefinition.parent" (fhir-spec (string->symbol "MessageDefinition.parent") "https://build.fhir.org/messagedefinition.html#MessageDefinition.parent" 'element))
(register-element! "MessageDefinition.category" (fhir-spec (string->symbol "MessageDefinition.category") "https://build.fhir.org/messagedefinition.html#MessageDefinition.category" 'element))
(register-element! "MessageDefinition.focus" (fhir-spec (string->symbol "MessageDefinition.focus") "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus" 'element))
(register-element! "MessageDefinition.responseRequired" (fhir-spec (string->symbol "MessageDefinition.responseRequired") "https://build.fhir.org/messagedefinition.html#MessageDefinition.responseRequired" 'element))
(register-element! "MessageDefinition.allowedResponse" (fhir-spec (string->symbol "MessageDefinition.allowedResponse") "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse" 'element))
(register-element! "MessageDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "MessageDefinition.versionAlgorithm[x]") "https://build.fhir.org/messagedefinition.html#MessageDefinition.versionAlgorithm[x]" 'element))
(register-element! "MessageDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "MessageDefinition.versionAlgorithm[x]") "https://build.fhir.org/messagedefinition.html#MessageDefinition.versionAlgorithm[x]" 'element))
(register-element! "MessageDefinition.event[x]" (fhir-spec (string->symbol "MessageDefinition.event[x]") "https://build.fhir.org/messagedefinition.html#MessageDefinition.event[x]" 'element))
(register-element! "MessageDefinition.event[x]" (fhir-spec (string->symbol "MessageDefinition.event[x]") "https://build.fhir.org/messagedefinition.html#MessageDefinition.event[x]" 'element))

(register-type! 'MessageDefinitionFocus (fhir-spec 'MessageDefinitionFocus "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus" 'type)
  #:schema (type-schema 'MessageDefinitionFocus #f 'BackboneElement "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.code" #f)
    (schema-field 'profile 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.profile" #f)
    (schema-field 'min 1 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.min" #f)
    (schema-field 'max 0 1 (vector 'prim "string") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.max" #f)
             ) #f #f))
(register-element! "MessageDefinition.focus.code" (fhir-spec (string->symbol "MessageDefinition.focus.code") "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.code" 'element))
(register-element! "MessageDefinition.focus.profile" (fhir-spec (string->symbol "MessageDefinition.focus.profile") "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.profile" 'element))
(register-element! "MessageDefinition.focus.min" (fhir-spec (string->symbol "MessageDefinition.focus.min") "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.min" 'element))
(register-element! "MessageDefinition.focus.max" (fhir-spec (string->symbol "MessageDefinition.focus.max") "https://build.fhir.org/messagedefinition.html#MessageDefinition.focus.max" 'element))

(register-type! 'MessageDefinitionAllowedResponse (fhir-spec 'MessageDefinitionAllowedResponse "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse" 'type)
  #:schema (type-schema 'MessageDefinitionAllowedResponse #f 'BackboneElement "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse"
             (list
    (schema-field 'message 1 1 (vector 'prim "canonical") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse.message" #f)
    (schema-field 'situation 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse.situation" #f)
             ) #f #f))
(register-element! "MessageDefinition.allowedResponse.message" (fhir-spec (string->symbol "MessageDefinition.allowedResponse.message") "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse.message" 'element))
(register-element! "MessageDefinition.allowedResponse.situation" (fhir-spec (string->symbol "MessageDefinition.allowedResponse.situation") "https://build.fhir.org/messagedefinition.html#MessageDefinition.allowedResponse.situation" 'element))

