#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'NamingSystem (fhir-spec 'NamingSystem "https://build.fhir.org/namingsystem.html#NamingSystem" 'type)
  #:schema (type-schema 'NamingSystem #f 'DomainResource "https://build.fhir.org/namingsystem.html#NamingSystem"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/namingsystem.html#NamingSystem.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/namingsystem.html#NamingSystem.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.version" #f)
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/namingsystem.html#NamingSystem.status" #f)
    (schema-field 'kind 1 1 (vector 'prim "code") #f "https://build.fhir.org/namingsystem.html#NamingSystem.kind" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/namingsystem.html#NamingSystem.experimental" #f)
    (schema-field 'date 1 1 (vector 'prim "dateTime") #f "https://build.fhir.org/namingsystem.html#NamingSystem.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/namingsystem.html#NamingSystem.contact" #f)
    (schema-field 'responsible 0 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.responsible" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/namingsystem.html#NamingSystem.type" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/namingsystem.html#NamingSystem.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/namingsystem.html#NamingSystem.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/namingsystem.html#NamingSystem.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/namingsystem.html#NamingSystem.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/namingsystem.html#NamingSystem.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/namingsystem.html#NamingSystem.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/namingsystem.html#NamingSystem.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/namingsystem.html#NamingSystem.effectivePeriod" #f)
    (schema-field 'topic 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/namingsystem.html#NamingSystem.topic" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/namingsystem.html#NamingSystem.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/namingsystem.html#NamingSystem.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/namingsystem.html#NamingSystem.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/namingsystem.html#NamingSystem.endorser" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://build.fhir.org/namingsystem.html#NamingSystem.relatedArtifact" #f)
    (schema-field 'usage 0 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.usage" #f)
    (schema-field 'uniqueId 1 '* (vector 'type 'NamingSystemUniqueId) #f "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/namingsystem.html#NamingSystem.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/namingsystem.html#NamingSystem.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "NamingSystem.url" (fhir-spec (string->symbol "NamingSystem.url") "https://build.fhir.org/namingsystem.html#NamingSystem.url" 'element))
(register-element! "NamingSystem.identifier" (fhir-spec (string->symbol "NamingSystem.identifier") "https://build.fhir.org/namingsystem.html#NamingSystem.identifier" 'element))
(register-element! "NamingSystem.version" (fhir-spec (string->symbol "NamingSystem.version") "https://build.fhir.org/namingsystem.html#NamingSystem.version" 'element))
(register-element! "NamingSystem.name" (fhir-spec (string->symbol "NamingSystem.name") "https://build.fhir.org/namingsystem.html#NamingSystem.name" 'element))
(register-element! "NamingSystem.title" (fhir-spec (string->symbol "NamingSystem.title") "https://build.fhir.org/namingsystem.html#NamingSystem.title" 'element))
(register-element! "NamingSystem.status" (fhir-spec (string->symbol "NamingSystem.status") "https://build.fhir.org/namingsystem.html#NamingSystem.status" 'element))
(register-element! "NamingSystem.kind" (fhir-spec (string->symbol "NamingSystem.kind") "https://build.fhir.org/namingsystem.html#NamingSystem.kind" 'element))
(register-element! "NamingSystem.experimental" (fhir-spec (string->symbol "NamingSystem.experimental") "https://build.fhir.org/namingsystem.html#NamingSystem.experimental" 'element))
(register-element! "NamingSystem.date" (fhir-spec (string->symbol "NamingSystem.date") "https://build.fhir.org/namingsystem.html#NamingSystem.date" 'element))
(register-element! "NamingSystem.publisher" (fhir-spec (string->symbol "NamingSystem.publisher") "https://build.fhir.org/namingsystem.html#NamingSystem.publisher" 'element))
(register-element! "NamingSystem.contact" (fhir-spec (string->symbol "NamingSystem.contact") "https://build.fhir.org/namingsystem.html#NamingSystem.contact" 'element))
(register-element! "NamingSystem.responsible" (fhir-spec (string->symbol "NamingSystem.responsible") "https://build.fhir.org/namingsystem.html#NamingSystem.responsible" 'element))
(register-element! "NamingSystem.type" (fhir-spec (string->symbol "NamingSystem.type") "https://build.fhir.org/namingsystem.html#NamingSystem.type" 'element))
(register-element! "NamingSystem.description" (fhir-spec (string->symbol "NamingSystem.description") "https://build.fhir.org/namingsystem.html#NamingSystem.description" 'element))
(register-element! "NamingSystem.useContext" (fhir-spec (string->symbol "NamingSystem.useContext") "https://build.fhir.org/namingsystem.html#NamingSystem.useContext" 'element))
(register-element! "NamingSystem.jurisdiction" (fhir-spec (string->symbol "NamingSystem.jurisdiction") "https://build.fhir.org/namingsystem.html#NamingSystem.jurisdiction" 'element))
(register-element! "NamingSystem.purpose" (fhir-spec (string->symbol "NamingSystem.purpose") "https://build.fhir.org/namingsystem.html#NamingSystem.purpose" 'element))
(register-element! "NamingSystem.copyright" (fhir-spec (string->symbol "NamingSystem.copyright") "https://build.fhir.org/namingsystem.html#NamingSystem.copyright" 'element))
(register-element! "NamingSystem.copyrightLabel" (fhir-spec (string->symbol "NamingSystem.copyrightLabel") "https://build.fhir.org/namingsystem.html#NamingSystem.copyrightLabel" 'element))
(register-element! "NamingSystem.approvalDate" (fhir-spec (string->symbol "NamingSystem.approvalDate") "https://build.fhir.org/namingsystem.html#NamingSystem.approvalDate" 'element))
(register-element! "NamingSystem.lastReviewDate" (fhir-spec (string->symbol "NamingSystem.lastReviewDate") "https://build.fhir.org/namingsystem.html#NamingSystem.lastReviewDate" 'element))
(register-element! "NamingSystem.effectivePeriod" (fhir-spec (string->symbol "NamingSystem.effectivePeriod") "https://build.fhir.org/namingsystem.html#NamingSystem.effectivePeriod" 'element))
(register-element! "NamingSystem.topic" (fhir-spec (string->symbol "NamingSystem.topic") "https://build.fhir.org/namingsystem.html#NamingSystem.topic" 'element))
(register-element! "NamingSystem.author" (fhir-spec (string->symbol "NamingSystem.author") "https://build.fhir.org/namingsystem.html#NamingSystem.author" 'element))
(register-element! "NamingSystem.editor" (fhir-spec (string->symbol "NamingSystem.editor") "https://build.fhir.org/namingsystem.html#NamingSystem.editor" 'element))
(register-element! "NamingSystem.reviewer" (fhir-spec (string->symbol "NamingSystem.reviewer") "https://build.fhir.org/namingsystem.html#NamingSystem.reviewer" 'element))
(register-element! "NamingSystem.endorser" (fhir-spec (string->symbol "NamingSystem.endorser") "https://build.fhir.org/namingsystem.html#NamingSystem.endorser" 'element))
(register-element! "NamingSystem.relatedArtifact" (fhir-spec (string->symbol "NamingSystem.relatedArtifact") "https://build.fhir.org/namingsystem.html#NamingSystem.relatedArtifact" 'element))
(register-element! "NamingSystem.usage" (fhir-spec (string->symbol "NamingSystem.usage") "https://build.fhir.org/namingsystem.html#NamingSystem.usage" 'element))
(register-element! "NamingSystem.uniqueId" (fhir-spec (string->symbol "NamingSystem.uniqueId") "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId" 'element))
(register-element! "NamingSystem.versionAlgorithm[x]" (fhir-spec (string->symbol "NamingSystem.versionAlgorithm[x]") "https://build.fhir.org/namingsystem.html#NamingSystem.versionAlgorithm[x]" 'element))
(register-element! "NamingSystem.versionAlgorithm[x]" (fhir-spec (string->symbol "NamingSystem.versionAlgorithm[x]") "https://build.fhir.org/namingsystem.html#NamingSystem.versionAlgorithm[x]" 'element))

(register-type! 'NamingSystemUniqueId (fhir-spec 'NamingSystemUniqueId "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId" 'type)
  #:schema (type-schema 'NamingSystemUniqueId #f 'BackboneElement "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId"
             (list
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.type" #f)
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.value" #f)
    (schema-field 'preferred 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.preferred" #f)
    (schema-field 'comment 0 1 (vector 'prim "string") #f "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.comment" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.period" #f)
    (schema-field 'authoritative 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.authoritative" #f)
             ) #f #f))
(register-element! "NamingSystem.uniqueId.type" (fhir-spec (string->symbol "NamingSystem.uniqueId.type") "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.type" 'element))
(register-element! "NamingSystem.uniqueId.value" (fhir-spec (string->symbol "NamingSystem.uniqueId.value") "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.value" 'element))
(register-element! "NamingSystem.uniqueId.preferred" (fhir-spec (string->symbol "NamingSystem.uniqueId.preferred") "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.preferred" 'element))
(register-element! "NamingSystem.uniqueId.comment" (fhir-spec (string->symbol "NamingSystem.uniqueId.comment") "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.comment" 'element))
(register-element! "NamingSystem.uniqueId.period" (fhir-spec (string->symbol "NamingSystem.uniqueId.period") "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.period" 'element))
(register-element! "NamingSystem.uniqueId.authoritative" (fhir-spec (string->symbol "NamingSystem.uniqueId.authoritative") "https://build.fhir.org/namingsystem.html#NamingSystem.uniqueId.authoritative" 'element))

