#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'PractitionerRole (fhir-spec 'PractitionerRole "https://build.fhir.org/practitionerrole.html#PractitionerRole" 'type)
  #:schema (type-schema 'PractitionerRole #f 'DomainResource "https://build.fhir.org/practitionerrole.html#PractitionerRole"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.identifier" #f)
    (schema-field 'active 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.active" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.period" #f)
    (schema-field 'practitioner 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.practitioner" #f)
    (schema-field 'organization 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.organization" #f)
    (schema-field 'network 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.network" #f)
    (schema-field 'code 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.code" #f)
    (schema-field 'display 0 1 (vector 'prim "string") #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.display" #f)
    (schema-field 'specialty 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.specialty" #f)
    (schema-field 'location 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.location" #f)
    (schema-field 'healthcareService 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.healthcareService" #f)
    (schema-field 'contact 0 '* (vector 'type 'ExtendedContactDetail) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.contact" #f)
    (schema-field 'characteristic 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.characteristic" #f)
    (schema-field 'communication 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.communication" #f)
    (schema-field 'availability 0 1 (vector 'type 'Availability) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.availability" #f)
    (schema-field 'endpoint 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/practitionerrole.html#PractitionerRole.endpoint" #f)
             ) #f #f))
(register-element! "PractitionerRole.identifier" (fhir-spec (string->symbol "PractitionerRole.identifier") "https://build.fhir.org/practitionerrole.html#PractitionerRole.identifier" 'element))
(register-element! "PractitionerRole.active" (fhir-spec (string->symbol "PractitionerRole.active") "https://build.fhir.org/practitionerrole.html#PractitionerRole.active" 'element))
(register-element! "PractitionerRole.period" (fhir-spec (string->symbol "PractitionerRole.period") "https://build.fhir.org/practitionerrole.html#PractitionerRole.period" 'element))
(register-element! "PractitionerRole.practitioner" (fhir-spec (string->symbol "PractitionerRole.practitioner") "https://build.fhir.org/practitionerrole.html#PractitionerRole.practitioner" 'element))
(register-element! "PractitionerRole.organization" (fhir-spec (string->symbol "PractitionerRole.organization") "https://build.fhir.org/practitionerrole.html#PractitionerRole.organization" 'element))
(register-element! "PractitionerRole.network" (fhir-spec (string->symbol "PractitionerRole.network") "https://build.fhir.org/practitionerrole.html#PractitionerRole.network" 'element))
(register-element! "PractitionerRole.code" (fhir-spec (string->symbol "PractitionerRole.code") "https://build.fhir.org/practitionerrole.html#PractitionerRole.code" 'element))
(register-element! "PractitionerRole.display" (fhir-spec (string->symbol "PractitionerRole.display") "https://build.fhir.org/practitionerrole.html#PractitionerRole.display" 'element))
(register-element! "PractitionerRole.specialty" (fhir-spec (string->symbol "PractitionerRole.specialty") "https://build.fhir.org/practitionerrole.html#PractitionerRole.specialty" 'element))
(register-element! "PractitionerRole.location" (fhir-spec (string->symbol "PractitionerRole.location") "https://build.fhir.org/practitionerrole.html#PractitionerRole.location" 'element))
(register-element! "PractitionerRole.healthcareService" (fhir-spec (string->symbol "PractitionerRole.healthcareService") "https://build.fhir.org/practitionerrole.html#PractitionerRole.healthcareService" 'element))
(register-element! "PractitionerRole.contact" (fhir-spec (string->symbol "PractitionerRole.contact") "https://build.fhir.org/practitionerrole.html#PractitionerRole.contact" 'element))
(register-element! "PractitionerRole.characteristic" (fhir-spec (string->symbol "PractitionerRole.characteristic") "https://build.fhir.org/practitionerrole.html#PractitionerRole.characteristic" 'element))
(register-element! "PractitionerRole.communication" (fhir-spec (string->symbol "PractitionerRole.communication") "https://build.fhir.org/practitionerrole.html#PractitionerRole.communication" 'element))
(register-element! "PractitionerRole.availability" (fhir-spec (string->symbol "PractitionerRole.availability") "https://build.fhir.org/practitionerrole.html#PractitionerRole.availability" 'element))
(register-element! "PractitionerRole.endpoint" (fhir-spec (string->symbol "PractitionerRole.endpoint") "https://build.fhir.org/practitionerrole.html#PractitionerRole.endpoint" 'element))

