#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Procedure (fhir-spec 'Procedure "https://build.fhir.org/procedure.html#Procedure" 'type)
  #:schema (type-schema 'Procedure #f 'DomainResource "https://build.fhir.org/procedure.html#Procedure"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/procedure.html#Procedure.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.basedOn" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/procedure.html#Procedure.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/procedure.html#Procedure.statusReason" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/procedure.html#Procedure.category" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/procedure.html#Procedure.code" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.subject" #f)
    (schema-field 'focus 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.focus" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.encounter" #f)
    (schema-field 'recorded 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/procedure.html#Procedure.recorded" #f)
    (schema-field 'recorder 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.recorder" #f)
    (schema-field 'performer 0 '* (vector 'type 'ProcedurePerformer) #f "https://build.fhir.org/procedure.html#Procedure.performer" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.location" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/procedure.html#Procedure.reason" #f)
    (schema-field 'bodySite 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/procedure.html#Procedure.bodySite" #f)
    (schema-field 'bodyStructure 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.bodyStructure" #f)
    (schema-field 'outcome 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/procedure.html#Procedure.outcome" #f)
    (schema-field 'report 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.report" #f)
    (schema-field 'complication 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/procedure.html#Procedure.complication" #f)
    (schema-field 'followUp 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/procedure.html#Procedure.followUp" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/procedure.html#Procedure.note" #f)
    (schema-field 'focalDevice 0 '* (vector 'type 'ProcedureFocalDevice) #f "https://build.fhir.org/procedure.html#Procedure.focalDevice" #f)
    (schema-field 'used 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/procedure.html#Procedure.used" #f)
    (schema-field 'supportingInfo 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.supportingInfo" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" #f)
    (schema-field 'occurrenceString 0 1 (vector 'prim "string") 'occurrence "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" #f)
    (schema-field 'occurrenceAge 0 1 (vector 'type 'Age) 'occurrence "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" #f)
    (schema-field 'occurrenceRange 0 1 (vector 'type 'Range) 'occurrence "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" #f)
    (schema-field 'occurrenceTiming 0 1 (vector 'type 'Timing) 'occurrence "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" #f)
    (schema-field 'reportedBoolean 0 1 (vector 'prim "boolean") 'reported "https://build.fhir.org/procedure.html#Procedure.reported[x]" #f)
    (schema-field 'reportedReference 0 1 (vector 'type 'Reference) 'reported "https://build.fhir.org/procedure.html#Procedure.reported[x]" #f)
             ) #f #f))
(register-element! "Procedure.identifier" (fhir-spec (string->symbol "Procedure.identifier") "https://build.fhir.org/procedure.html#Procedure.identifier" 'element))
(register-element! "Procedure.basedOn" (fhir-spec (string->symbol "Procedure.basedOn") "https://build.fhir.org/procedure.html#Procedure.basedOn" 'element))
(register-element! "Procedure.partOf" (fhir-spec (string->symbol "Procedure.partOf") "https://build.fhir.org/procedure.html#Procedure.partOf" 'element))
(register-element! "Procedure.status" (fhir-spec (string->symbol "Procedure.status") "https://build.fhir.org/procedure.html#Procedure.status" 'element))
(register-element! "Procedure.statusReason" (fhir-spec (string->symbol "Procedure.statusReason") "https://build.fhir.org/procedure.html#Procedure.statusReason" 'element))
(register-element! "Procedure.category" (fhir-spec (string->symbol "Procedure.category") "https://build.fhir.org/procedure.html#Procedure.category" 'element))
(register-element! "Procedure.code" (fhir-spec (string->symbol "Procedure.code") "https://build.fhir.org/procedure.html#Procedure.code" 'element))
(register-element! "Procedure.subject" (fhir-spec (string->symbol "Procedure.subject") "https://build.fhir.org/procedure.html#Procedure.subject" 'element))
(register-element! "Procedure.focus" (fhir-spec (string->symbol "Procedure.focus") "https://build.fhir.org/procedure.html#Procedure.focus" 'element))
(register-element! "Procedure.encounter" (fhir-spec (string->symbol "Procedure.encounter") "https://build.fhir.org/procedure.html#Procedure.encounter" 'element))
(register-element! "Procedure.recorded" (fhir-spec (string->symbol "Procedure.recorded") "https://build.fhir.org/procedure.html#Procedure.recorded" 'element))
(register-element! "Procedure.recorder" (fhir-spec (string->symbol "Procedure.recorder") "https://build.fhir.org/procedure.html#Procedure.recorder" 'element))
(register-element! "Procedure.performer" (fhir-spec (string->symbol "Procedure.performer") "https://build.fhir.org/procedure.html#Procedure.performer" 'element))
(register-element! "Procedure.location" (fhir-spec (string->symbol "Procedure.location") "https://build.fhir.org/procedure.html#Procedure.location" 'element))
(register-element! "Procedure.reason" (fhir-spec (string->symbol "Procedure.reason") "https://build.fhir.org/procedure.html#Procedure.reason" 'element))
(register-element! "Procedure.bodySite" (fhir-spec (string->symbol "Procedure.bodySite") "https://build.fhir.org/procedure.html#Procedure.bodySite" 'element))
(register-element! "Procedure.bodyStructure" (fhir-spec (string->symbol "Procedure.bodyStructure") "https://build.fhir.org/procedure.html#Procedure.bodyStructure" 'element))
(register-element! "Procedure.outcome" (fhir-spec (string->symbol "Procedure.outcome") "https://build.fhir.org/procedure.html#Procedure.outcome" 'element))
(register-element! "Procedure.report" (fhir-spec (string->symbol "Procedure.report") "https://build.fhir.org/procedure.html#Procedure.report" 'element))
(register-element! "Procedure.complication" (fhir-spec (string->symbol "Procedure.complication") "https://build.fhir.org/procedure.html#Procedure.complication" 'element))
(register-element! "Procedure.followUp" (fhir-spec (string->symbol "Procedure.followUp") "https://build.fhir.org/procedure.html#Procedure.followUp" 'element))
(register-element! "Procedure.note" (fhir-spec (string->symbol "Procedure.note") "https://build.fhir.org/procedure.html#Procedure.note" 'element))
(register-element! "Procedure.focalDevice" (fhir-spec (string->symbol "Procedure.focalDevice") "https://build.fhir.org/procedure.html#Procedure.focalDevice" 'element))
(register-element! "Procedure.used" (fhir-spec (string->symbol "Procedure.used") "https://build.fhir.org/procedure.html#Procedure.used" 'element))
(register-element! "Procedure.supportingInfo" (fhir-spec (string->symbol "Procedure.supportingInfo") "https://build.fhir.org/procedure.html#Procedure.supportingInfo" 'element))
(register-element! "Procedure.occurrence[x]" (fhir-spec (string->symbol "Procedure.occurrence[x]") "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" 'element))
(register-element! "Procedure.occurrence[x]" (fhir-spec (string->symbol "Procedure.occurrence[x]") "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" 'element))
(register-element! "Procedure.occurrence[x]" (fhir-spec (string->symbol "Procedure.occurrence[x]") "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" 'element))
(register-element! "Procedure.occurrence[x]" (fhir-spec (string->symbol "Procedure.occurrence[x]") "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" 'element))
(register-element! "Procedure.occurrence[x]" (fhir-spec (string->symbol "Procedure.occurrence[x]") "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" 'element))
(register-element! "Procedure.occurrence[x]" (fhir-spec (string->symbol "Procedure.occurrence[x]") "https://build.fhir.org/procedure.html#Procedure.occurrence[x]" 'element))
(register-element! "Procedure.reported[x]" (fhir-spec (string->symbol "Procedure.reported[x]") "https://build.fhir.org/procedure.html#Procedure.reported[x]" 'element))
(register-element! "Procedure.reported[x]" (fhir-spec (string->symbol "Procedure.reported[x]") "https://build.fhir.org/procedure.html#Procedure.reported[x]" 'element))

(register-type! 'ProcedurePerformer (fhir-spec 'ProcedurePerformer "https://build.fhir.org/procedure.html#Procedure.performer" 'type)
  #:schema (type-schema 'ProcedurePerformer #f 'BackboneElement "https://build.fhir.org/procedure.html#Procedure.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/procedure.html#Procedure.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.performer.actor" #f)
    (schema-field 'onBehalfOf 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.performer.onBehalfOf" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/procedure.html#Procedure.performer.period" #f)
             ) #f #f))
(register-element! "Procedure.performer.function" (fhir-spec (string->symbol "Procedure.performer.function") "https://build.fhir.org/procedure.html#Procedure.performer.function" 'element))
(register-element! "Procedure.performer.actor" (fhir-spec (string->symbol "Procedure.performer.actor") "https://build.fhir.org/procedure.html#Procedure.performer.actor" 'element))
(register-element! "Procedure.performer.onBehalfOf" (fhir-spec (string->symbol "Procedure.performer.onBehalfOf") "https://build.fhir.org/procedure.html#Procedure.performer.onBehalfOf" 'element))
(register-element! "Procedure.performer.period" (fhir-spec (string->symbol "Procedure.performer.period") "https://build.fhir.org/procedure.html#Procedure.performer.period" 'element))

(register-type! 'ProcedureFocalDevice (fhir-spec 'ProcedureFocalDevice "https://build.fhir.org/procedure.html#Procedure.focalDevice" 'type)
  #:schema (type-schema 'ProcedureFocalDevice #f 'BackboneElement "https://build.fhir.org/procedure.html#Procedure.focalDevice"
             (list
    (schema-field 'action 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/procedure.html#Procedure.focalDevice.action" #f)
    (schema-field 'manipulated 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/procedure.html#Procedure.focalDevice.manipulated" #f)
             ) #f #f))
(register-element! "Procedure.focalDevice.action" (fhir-spec (string->symbol "Procedure.focalDevice.action") "https://build.fhir.org/procedure.html#Procedure.focalDevice.action" 'element))
(register-element! "Procedure.focalDevice.manipulated" (fhir-spec (string->symbol "Procedure.focalDevice.manipulated") "https://build.fhir.org/procedure.html#Procedure.focalDevice.manipulated" 'element))

