#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ResearchStudy (fhir-spec 'ResearchStudy "https://build.fhir.org/researchstudy.html#ResearchStudy" 'type)
  #:schema (type-schema 'ResearchStudy #f 'DomainResource "https://build.fhir.org/researchstudy.html#ResearchStudy"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.title" #f)
    (schema-field 'label 0 '* (vector 'type 'ResearchStudyLabel) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.label" #f)
    (schema-field 'protocol 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.protocol" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.partOf" #f)
    (schema-field 'citeAs 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.citeAs" #f)
    (schema-field 'relatesTo 0 '* (vector 'type 'ResearchStudyRelatesTo) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.date" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.status" #f)
    (schema-field 'purposeType 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.purposeType" #f)
    (schema-field 'phase 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.phase" #f)
    (schema-field 'studyDesign 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.studyDesign" #f)
    (schema-field 'focus 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.focus" #f)
    (schema-field 'condition 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.condition" #f)
    (schema-field 'keyword 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.keyword" #f)
    (schema-field 'region 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.region" #f)
    (schema-field 'descriptionSummary 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.descriptionSummary" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.description" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.period" #f)
    (schema-field 'site 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.site" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.note" #f)
    (schema-field 'classifier 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.classifier" #f)
    (schema-field 'associatedParty 0 '* (vector 'type 'ResearchStudyAssociatedParty) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty" #f)
    (schema-field 'progressStatus 0 '* (vector 'type 'ResearchStudyProgressStatus) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus" #f)
    (schema-field 'whyStopped 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.whyStopped" #f)
    (schema-field 'recruitment 0 1 (vector 'type 'ResearchStudyRecruitment) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment" #f)
    (schema-field 'comparisonGroup 0 '* (vector 'type 'ResearchStudyComparisonGroup) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup" #f)
    (schema-field 'objective 0 '* (vector 'type 'ResearchStudyObjective) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective" #f)
    (schema-field 'result 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.result" #f)
             ) #f #f))
(register-element! "ResearchStudy.url" (fhir-spec (string->symbol "ResearchStudy.url") "https://build.fhir.org/researchstudy.html#ResearchStudy.url" 'element))
(register-element! "ResearchStudy.identifier" (fhir-spec (string->symbol "ResearchStudy.identifier") "https://build.fhir.org/researchstudy.html#ResearchStudy.identifier" 'element))
(register-element! "ResearchStudy.version" (fhir-spec (string->symbol "ResearchStudy.version") "https://build.fhir.org/researchstudy.html#ResearchStudy.version" 'element))
(register-element! "ResearchStudy.name" (fhir-spec (string->symbol "ResearchStudy.name") "https://build.fhir.org/researchstudy.html#ResearchStudy.name" 'element))
(register-element! "ResearchStudy.title" (fhir-spec (string->symbol "ResearchStudy.title") "https://build.fhir.org/researchstudy.html#ResearchStudy.title" 'element))
(register-element! "ResearchStudy.label" (fhir-spec (string->symbol "ResearchStudy.label") "https://build.fhir.org/researchstudy.html#ResearchStudy.label" 'element))
(register-element! "ResearchStudy.protocol" (fhir-spec (string->symbol "ResearchStudy.protocol") "https://build.fhir.org/researchstudy.html#ResearchStudy.protocol" 'element))
(register-element! "ResearchStudy.partOf" (fhir-spec (string->symbol "ResearchStudy.partOf") "https://build.fhir.org/researchstudy.html#ResearchStudy.partOf" 'element))
(register-element! "ResearchStudy.citeAs" (fhir-spec (string->symbol "ResearchStudy.citeAs") "https://build.fhir.org/researchstudy.html#ResearchStudy.citeAs" 'element))
(register-element! "ResearchStudy.relatesTo" (fhir-spec (string->symbol "ResearchStudy.relatesTo") "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo" 'element))
(register-element! "ResearchStudy.date" (fhir-spec (string->symbol "ResearchStudy.date") "https://build.fhir.org/researchstudy.html#ResearchStudy.date" 'element))
(register-element! "ResearchStudy.status" (fhir-spec (string->symbol "ResearchStudy.status") "https://build.fhir.org/researchstudy.html#ResearchStudy.status" 'element))
(register-element! "ResearchStudy.purposeType" (fhir-spec (string->symbol "ResearchStudy.purposeType") "https://build.fhir.org/researchstudy.html#ResearchStudy.purposeType" 'element))
(register-element! "ResearchStudy.phase" (fhir-spec (string->symbol "ResearchStudy.phase") "https://build.fhir.org/researchstudy.html#ResearchStudy.phase" 'element))
(register-element! "ResearchStudy.studyDesign" (fhir-spec (string->symbol "ResearchStudy.studyDesign") "https://build.fhir.org/researchstudy.html#ResearchStudy.studyDesign" 'element))
(register-element! "ResearchStudy.focus" (fhir-spec (string->symbol "ResearchStudy.focus") "https://build.fhir.org/researchstudy.html#ResearchStudy.focus" 'element))
(register-element! "ResearchStudy.condition" (fhir-spec (string->symbol "ResearchStudy.condition") "https://build.fhir.org/researchstudy.html#ResearchStudy.condition" 'element))
(register-element! "ResearchStudy.keyword" (fhir-spec (string->symbol "ResearchStudy.keyword") "https://build.fhir.org/researchstudy.html#ResearchStudy.keyword" 'element))
(register-element! "ResearchStudy.region" (fhir-spec (string->symbol "ResearchStudy.region") "https://build.fhir.org/researchstudy.html#ResearchStudy.region" 'element))
(register-element! "ResearchStudy.descriptionSummary" (fhir-spec (string->symbol "ResearchStudy.descriptionSummary") "https://build.fhir.org/researchstudy.html#ResearchStudy.descriptionSummary" 'element))
(register-element! "ResearchStudy.description" (fhir-spec (string->symbol "ResearchStudy.description") "https://build.fhir.org/researchstudy.html#ResearchStudy.description" 'element))
(register-element! "ResearchStudy.period" (fhir-spec (string->symbol "ResearchStudy.period") "https://build.fhir.org/researchstudy.html#ResearchStudy.period" 'element))
(register-element! "ResearchStudy.site" (fhir-spec (string->symbol "ResearchStudy.site") "https://build.fhir.org/researchstudy.html#ResearchStudy.site" 'element))
(register-element! "ResearchStudy.note" (fhir-spec (string->symbol "ResearchStudy.note") "https://build.fhir.org/researchstudy.html#ResearchStudy.note" 'element))
(register-element! "ResearchStudy.classifier" (fhir-spec (string->symbol "ResearchStudy.classifier") "https://build.fhir.org/researchstudy.html#ResearchStudy.classifier" 'element))
(register-element! "ResearchStudy.associatedParty" (fhir-spec (string->symbol "ResearchStudy.associatedParty") "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty" 'element))
(register-element! "ResearchStudy.progressStatus" (fhir-spec (string->symbol "ResearchStudy.progressStatus") "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus" 'element))
(register-element! "ResearchStudy.whyStopped" (fhir-spec (string->symbol "ResearchStudy.whyStopped") "https://build.fhir.org/researchstudy.html#ResearchStudy.whyStopped" 'element))
(register-element! "ResearchStudy.recruitment" (fhir-spec (string->symbol "ResearchStudy.recruitment") "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment" 'element))
(register-element! "ResearchStudy.comparisonGroup" (fhir-spec (string->symbol "ResearchStudy.comparisonGroup") "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup" 'element))
(register-element! "ResearchStudy.objective" (fhir-spec (string->symbol "ResearchStudy.objective") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective" 'element))
(register-element! "ResearchStudy.result" (fhir-spec (string->symbol "ResearchStudy.result") "https://build.fhir.org/researchstudy.html#ResearchStudy.result" 'element))

(register-type! 'ResearchStudyLabel (fhir-spec 'ResearchStudyLabel "https://build.fhir.org/researchstudy.html#ResearchStudy.label" 'type)
  #:schema (type-schema 'ResearchStudyLabel #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.label"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.label.type" #f)
    (schema-field 'value 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.label.value" #f)
    (schema-field 'language 0 1 (vector 'prim "code") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.label.language" #f)
             ) #f #f))
(register-element! "ResearchStudy.label.type" (fhir-spec (string->symbol "ResearchStudy.label.type") "https://build.fhir.org/researchstudy.html#ResearchStudy.label.type" 'element))
(register-element! "ResearchStudy.label.value" (fhir-spec (string->symbol "ResearchStudy.label.value") "https://build.fhir.org/researchstudy.html#ResearchStudy.label.value" 'element))
(register-element! "ResearchStudy.label.language" (fhir-spec (string->symbol "ResearchStudy.label.language") "https://build.fhir.org/researchstudy.html#ResearchStudy.label.language" 'element))

(register-type! 'ResearchStudyRelatesTo (fhir-spec 'ResearchStudyRelatesTo "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo" 'type)
  #:schema (type-schema 'ResearchStudyRelatesTo #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.type" #f)
    (schema-field 'targetUri 0 1 (vector 'prim "uri") 'target "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" #f)
    (schema-field 'targetAttachment 0 1 (vector 'type 'Attachment) 'target "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" #f)
    (schema-field 'targetCanonical 0 1 (vector 'prim "canonical") 'target "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" #f)
    (schema-field 'targetReference 0 1 (vector 'type 'Reference) 'target "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" #f)
    (schema-field 'targetMarkdown 0 1 (vector 'prim "markdown") 'target "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" #f)
             ) #f #f))
(register-element! "ResearchStudy.relatesTo.type" (fhir-spec (string->symbol "ResearchStudy.relatesTo.type") "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.type" 'element))
(register-element! "ResearchStudy.relatesTo.target[x]" (fhir-spec (string->symbol "ResearchStudy.relatesTo.target[x]") "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" 'element))
(register-element! "ResearchStudy.relatesTo.target[x]" (fhir-spec (string->symbol "ResearchStudy.relatesTo.target[x]") "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" 'element))
(register-element! "ResearchStudy.relatesTo.target[x]" (fhir-spec (string->symbol "ResearchStudy.relatesTo.target[x]") "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" 'element))
(register-element! "ResearchStudy.relatesTo.target[x]" (fhir-spec (string->symbol "ResearchStudy.relatesTo.target[x]") "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" 'element))
(register-element! "ResearchStudy.relatesTo.target[x]" (fhir-spec (string->symbol "ResearchStudy.relatesTo.target[x]") "https://build.fhir.org/researchstudy.html#ResearchStudy.relatesTo.target[x]" 'element))

(register-type! 'ResearchStudyAssociatedParty (fhir-spec 'ResearchStudyAssociatedParty "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty" 'type)
  #:schema (type-schema 'ResearchStudyAssociatedParty #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty"
             (list
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.name" #f)
    (schema-field 'role 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.role" #f)
    (schema-field 'period 0 '* (vector 'type 'Period) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.period" #f)
    (schema-field 'classifier 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.classifier" #f)
    (schema-field 'party 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.party" #f)
             ) #f #f))
(register-element! "ResearchStudy.associatedParty.name" (fhir-spec (string->symbol "ResearchStudy.associatedParty.name") "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.name" 'element))
(register-element! "ResearchStudy.associatedParty.role" (fhir-spec (string->symbol "ResearchStudy.associatedParty.role") "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.role" 'element))
(register-element! "ResearchStudy.associatedParty.period" (fhir-spec (string->symbol "ResearchStudy.associatedParty.period") "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.period" 'element))
(register-element! "ResearchStudy.associatedParty.classifier" (fhir-spec (string->symbol "ResearchStudy.associatedParty.classifier") "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.classifier" 'element))
(register-element! "ResearchStudy.associatedParty.party" (fhir-spec (string->symbol "ResearchStudy.associatedParty.party") "https://build.fhir.org/researchstudy.html#ResearchStudy.associatedParty.party" 'element))

(register-type! 'ResearchStudyProgressStatus (fhir-spec 'ResearchStudyProgressStatus "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus" 'type)
  #:schema (type-schema 'ResearchStudyProgressStatus #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus"
             (list
    (schema-field 'state 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus.state" #f)
    (schema-field 'actual 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus.actual" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus.period" #f)
             ) #f #f))
(register-element! "ResearchStudy.progressStatus.state" (fhir-spec (string->symbol "ResearchStudy.progressStatus.state") "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus.state" 'element))
(register-element! "ResearchStudy.progressStatus.actual" (fhir-spec (string->symbol "ResearchStudy.progressStatus.actual") "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus.actual" 'element))
(register-element! "ResearchStudy.progressStatus.period" (fhir-spec (string->symbol "ResearchStudy.progressStatus.period") "https://build.fhir.org/researchstudy.html#ResearchStudy.progressStatus.period" 'element))

(register-type! 'ResearchStudyRecruitment (fhir-spec 'ResearchStudyRecruitment "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment" 'type)
  #:schema (type-schema 'ResearchStudyRecruitment #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment"
             (list
    (schema-field 'targetNumber 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.targetNumber" #f)
    (schema-field 'actualNumber 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.actualNumber" #f)
    (schema-field 'eligibility 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.eligibility" #f)
    (schema-field 'actualGroup 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.actualGroup" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.description" #f)
             ) #f #f))
(register-element! "ResearchStudy.recruitment.targetNumber" (fhir-spec (string->symbol "ResearchStudy.recruitment.targetNumber") "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.targetNumber" 'element))
(register-element! "ResearchStudy.recruitment.actualNumber" (fhir-spec (string->symbol "ResearchStudy.recruitment.actualNumber") "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.actualNumber" 'element))
(register-element! "ResearchStudy.recruitment.eligibility" (fhir-spec (string->symbol "ResearchStudy.recruitment.eligibility") "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.eligibility" 'element))
(register-element! "ResearchStudy.recruitment.actualGroup" (fhir-spec (string->symbol "ResearchStudy.recruitment.actualGroup") "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.actualGroup" 'element))
(register-element! "ResearchStudy.recruitment.description" (fhir-spec (string->symbol "ResearchStudy.recruitment.description") "https://build.fhir.org/researchstudy.html#ResearchStudy.recruitment.description" 'element))

(register-type! 'ResearchStudyComparisonGroup (fhir-spec 'ResearchStudyComparisonGroup "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup" 'type)
  #:schema (type-schema 'ResearchStudyComparisonGroup #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup"
             (list
    (schema-field 'targetNumber 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.targetNumber" #f)
    (schema-field 'actualNumber 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.actualNumber" #f)
    (schema-field 'eligibility 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.eligibility" #f)
    (schema-field 'observedGroup 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.observedGroup" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.name" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.description" #f)
             ) #f #f))
(register-element! "ResearchStudy.comparisonGroup.targetNumber" (fhir-spec (string->symbol "ResearchStudy.comparisonGroup.targetNumber") "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.targetNumber" 'element))
(register-element! "ResearchStudy.comparisonGroup.actualNumber" (fhir-spec (string->symbol "ResearchStudy.comparisonGroup.actualNumber") "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.actualNumber" 'element))
(register-element! "ResearchStudy.comparisonGroup.eligibility" (fhir-spec (string->symbol "ResearchStudy.comparisonGroup.eligibility") "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.eligibility" 'element))
(register-element! "ResearchStudy.comparisonGroup.observedGroup" (fhir-spec (string->symbol "ResearchStudy.comparisonGroup.observedGroup") "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.observedGroup" 'element))
(register-element! "ResearchStudy.comparisonGroup.name" (fhir-spec (string->symbol "ResearchStudy.comparisonGroup.name") "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.name" 'element))
(register-element! "ResearchStudy.comparisonGroup.description" (fhir-spec (string->symbol "ResearchStudy.comparisonGroup.description") "https://build.fhir.org/researchstudy.html#ResearchStudy.comparisonGroup.description" 'element))

(register-type! 'ResearchStudyObjective (fhir-spec 'ResearchStudyObjective "https://build.fhir.org/researchstudy.html#ResearchStudy.objective" 'type)
  #:schema (type-schema 'ResearchStudyObjective #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.objective"
             (list
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.name" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.type" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.description" #f)
    (schema-field 'outcomeMeasure 0 '* (vector 'type 'ResearchStudyObjectiveOutcomeMeasure) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure" #f)
             ) #f #f))
(register-element! "ResearchStudy.objective.name" (fhir-spec (string->symbol "ResearchStudy.objective.name") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.name" 'element))
(register-element! "ResearchStudy.objective.type" (fhir-spec (string->symbol "ResearchStudy.objective.type") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.type" 'element))
(register-element! "ResearchStudy.objective.description" (fhir-spec (string->symbol "ResearchStudy.objective.description") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.description" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure" 'element))

(register-type! 'ResearchStudyObjectiveOutcomeMeasure (fhir-spec 'ResearchStudyObjectiveOutcomeMeasure "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure" 'type)
  #:schema (type-schema 'ResearchStudyObjectiveOutcomeMeasure #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure"
             (list
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.name" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.type" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.description" #f)
    (schema-field 'endpoint 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.endpoint" #f)
    (schema-field 'population 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.population" #f)
    (schema-field 'intervention 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.intervention" #f)
    (schema-field 'comparator 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.comparator" #f)
    (schema-field 'summaryMeasure 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.summaryMeasure" #f)
    (schema-field 'endpointAnalysisPlan 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.endpointAnalysisPlan" #f)
    (schema-field 'eventHandling 0 '* (vector 'type 'ResearchStudyObjectiveOutcomeMeasureEventHandling) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling" #f)
             ) #f #f))
(register-element! "ResearchStudy.objective.outcomeMeasure.name" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.name") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.name" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.type" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.type") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.type" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.description" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.description") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.description" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.endpoint" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.endpoint") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.endpoint" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.population" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.population") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.population" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.intervention" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.intervention") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.intervention" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.comparator" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.comparator") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.comparator" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.summaryMeasure" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.summaryMeasure") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.summaryMeasure" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.endpointAnalysisPlan" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.endpointAnalysisPlan") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.endpointAnalysisPlan" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.eventHandling" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.eventHandling") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling" 'element))

(register-type! 'ResearchStudyObjectiveOutcomeMeasureEventHandling (fhir-spec 'ResearchStudyObjectiveOutcomeMeasureEventHandling "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling" 'type)
  #:schema (type-schema 'ResearchStudyObjectiveOutcomeMeasureEventHandling #f 'BackboneElement "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling"
             (list
    (schema-field 'event 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.event" #f)
    (schema-field 'group 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.group" #f)
    (schema-field 'handling 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.handling" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.description" #f)
             ) #f #f))
(register-element! "ResearchStudy.objective.outcomeMeasure.eventHandling.event" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.eventHandling.event") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.event" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.eventHandling.group" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.eventHandling.group") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.group" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.eventHandling.handling" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.eventHandling.handling") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.handling" 'element))
(register-element! "ResearchStudy.objective.outcomeMeasure.eventHandling.description" (fhir-spec (string->symbol "ResearchStudy.objective.outcomeMeasure.eventHandling.description") "https://build.fhir.org/researchstudy.html#ResearchStudy.objective.outcomeMeasure.eventHandling.description" 'element))

