#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'SpecimenDefinition (fhir-spec 'SpecimenDefinition "https://build.fhir.org/specimendefinition.html#SpecimenDefinition" 'type)
  #:schema (type-schema 'SpecimenDefinition #f 'DomainResource "https://build.fhir.org/specimendefinition.html#SpecimenDefinition"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.title" #f)
    (schema-field 'derivedFromCanonical 0 '* (vector 'prim "canonical") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.derivedFromCanonical" #f)
    (schema-field 'derivedFromUri 0 '* (vector 'prim "uri") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.derivedFromUri" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.effectivePeriod" #f)
    (schema-field 'typeCollected 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeCollected" #f)
    (schema-field 'patientPreparation 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.patientPreparation" #f)
    (schema-field 'timeAspect 0 1 (vector 'prim "string") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.timeAspect" #f)
    (schema-field 'collection 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.collection" #f)
    (schema-field 'typeTested 0 '* (vector 'type 'SpecimenDefinitionTypeTested) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.versionAlgorithm[x]" #f)
    (schema-field 'subjectCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'subject "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.subject[x]" #f)
    (schema-field 'subjectReference 0 1 (vector 'type 'Reference) 'subject "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.subject[x]" #f)
             ) #f #f))
(register-element! "SpecimenDefinition.url" (fhir-spec (string->symbol "SpecimenDefinition.url") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.url" 'element))
(register-element! "SpecimenDefinition.identifier" (fhir-spec (string->symbol "SpecimenDefinition.identifier") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.identifier" 'element))
(register-element! "SpecimenDefinition.version" (fhir-spec (string->symbol "SpecimenDefinition.version") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.version" 'element))
(register-element! "SpecimenDefinition.name" (fhir-spec (string->symbol "SpecimenDefinition.name") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.name" 'element))
(register-element! "SpecimenDefinition.title" (fhir-spec (string->symbol "SpecimenDefinition.title") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.title" 'element))
(register-element! "SpecimenDefinition.derivedFromCanonical" (fhir-spec (string->symbol "SpecimenDefinition.derivedFromCanonical") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.derivedFromCanonical" 'element))
(register-element! "SpecimenDefinition.derivedFromUri" (fhir-spec (string->symbol "SpecimenDefinition.derivedFromUri") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.derivedFromUri" 'element))
(register-element! "SpecimenDefinition.status" (fhir-spec (string->symbol "SpecimenDefinition.status") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.status" 'element))
(register-element! "SpecimenDefinition.experimental" (fhir-spec (string->symbol "SpecimenDefinition.experimental") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.experimental" 'element))
(register-element! "SpecimenDefinition.date" (fhir-spec (string->symbol "SpecimenDefinition.date") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.date" 'element))
(register-element! "SpecimenDefinition.publisher" (fhir-spec (string->symbol "SpecimenDefinition.publisher") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.publisher" 'element))
(register-element! "SpecimenDefinition.contact" (fhir-spec (string->symbol "SpecimenDefinition.contact") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.contact" 'element))
(register-element! "SpecimenDefinition.description" (fhir-spec (string->symbol "SpecimenDefinition.description") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.description" 'element))
(register-element! "SpecimenDefinition.useContext" (fhir-spec (string->symbol "SpecimenDefinition.useContext") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.useContext" 'element))
(register-element! "SpecimenDefinition.jurisdiction" (fhir-spec (string->symbol "SpecimenDefinition.jurisdiction") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.jurisdiction" 'element))
(register-element! "SpecimenDefinition.purpose" (fhir-spec (string->symbol "SpecimenDefinition.purpose") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.purpose" 'element))
(register-element! "SpecimenDefinition.copyright" (fhir-spec (string->symbol "SpecimenDefinition.copyright") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.copyright" 'element))
(register-element! "SpecimenDefinition.copyrightLabel" (fhir-spec (string->symbol "SpecimenDefinition.copyrightLabel") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.copyrightLabel" 'element))
(register-element! "SpecimenDefinition.approvalDate" (fhir-spec (string->symbol "SpecimenDefinition.approvalDate") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.approvalDate" 'element))
(register-element! "SpecimenDefinition.lastReviewDate" (fhir-spec (string->symbol "SpecimenDefinition.lastReviewDate") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.lastReviewDate" 'element))
(register-element! "SpecimenDefinition.effectivePeriod" (fhir-spec (string->symbol "SpecimenDefinition.effectivePeriod") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.effectivePeriod" 'element))
(register-element! "SpecimenDefinition.typeCollected" (fhir-spec (string->symbol "SpecimenDefinition.typeCollected") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeCollected" 'element))
(register-element! "SpecimenDefinition.patientPreparation" (fhir-spec (string->symbol "SpecimenDefinition.patientPreparation") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.patientPreparation" 'element))
(register-element! "SpecimenDefinition.timeAspect" (fhir-spec (string->symbol "SpecimenDefinition.timeAspect") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.timeAspect" 'element))
(register-element! "SpecimenDefinition.collection" (fhir-spec (string->symbol "SpecimenDefinition.collection") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.collection" 'element))
(register-element! "SpecimenDefinition.typeTested" (fhir-spec (string->symbol "SpecimenDefinition.typeTested") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested" 'element))
(register-element! "SpecimenDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "SpecimenDefinition.versionAlgorithm[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.versionAlgorithm[x]" 'element))
(register-element! "SpecimenDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "SpecimenDefinition.versionAlgorithm[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.versionAlgorithm[x]" 'element))
(register-element! "SpecimenDefinition.subject[x]" (fhir-spec (string->symbol "SpecimenDefinition.subject[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.subject[x]" 'element))
(register-element! "SpecimenDefinition.subject[x]" (fhir-spec (string->symbol "SpecimenDefinition.subject[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.subject[x]" 'element))

(register-type! 'SpecimenDefinitionTypeTested (fhir-spec 'SpecimenDefinitionTypeTested "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested" 'type)
  #:schema (type-schema 'SpecimenDefinitionTypeTested #f 'BackboneElement "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested"
             (list
    (schema-field 'isDerived 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.isDerived" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.type" #f)
    (schema-field 'preference 1 1 (vector 'prim "code") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.preference" #f)
    (schema-field 'container 0 1 (vector 'type 'SpecimenDefinitionTypeTestedContainer) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container" #f)
    (schema-field 'requirement 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.requirement" #f)
    (schema-field 'retentionTime 0 1 (vector 'type 'Duration) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.retentionTime" #f)
    (schema-field 'singleUse 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.singleUse" #f)
    (schema-field 'rejectionCriterion 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.rejectionCriterion" #f)
    (schema-field 'handling 0 '* (vector 'type 'SpecimenDefinitionTypeTestedHandling) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling" #f)
    (schema-field 'testingDestination 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.testingDestination" #f)
             ) #f #f))
(register-element! "SpecimenDefinition.typeTested.isDerived" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.isDerived") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.isDerived" 'element))
(register-element! "SpecimenDefinition.typeTested.type" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.type") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.type" 'element))
(register-element! "SpecimenDefinition.typeTested.preference" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.preference") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.preference" 'element))
(register-element! "SpecimenDefinition.typeTested.container" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container" 'element))
(register-element! "SpecimenDefinition.typeTested.requirement" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.requirement") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.requirement" 'element))
(register-element! "SpecimenDefinition.typeTested.retentionTime" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.retentionTime") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.retentionTime" 'element))
(register-element! "SpecimenDefinition.typeTested.singleUse" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.singleUse") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.singleUse" 'element))
(register-element! "SpecimenDefinition.typeTested.rejectionCriterion" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.rejectionCriterion") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.rejectionCriterion" 'element))
(register-element! "SpecimenDefinition.typeTested.handling" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.handling") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling" 'element))
(register-element! "SpecimenDefinition.typeTested.testingDestination" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.testingDestination") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.testingDestination" 'element))

(register-type! 'SpecimenDefinitionTypeTestedContainer (fhir-spec 'SpecimenDefinitionTypeTestedContainer "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container" 'type)
  #:schema (type-schema 'SpecimenDefinitionTypeTestedContainer #f 'BackboneElement "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container"
             (list
    (schema-field 'material 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.material" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.type" #f)
    (schema-field 'cap 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.cap" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.description" #f)
    (schema-field 'capacity 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.capacity" #f)
    (schema-field 'additive 0 '* (vector 'type 'SpecimenDefinitionTypeTestedContainerAdditive) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive" #f)
    (schema-field 'preparation 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.preparation" #f)
    (schema-field 'minimumVolumeQuantity 0 1 (vector 'type 'Quantity) 'minimumVolume "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.minimumVolume[x]" #f)
    (schema-field 'minimumVolumeString 0 1 (vector 'prim "string") 'minimumVolume "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.minimumVolume[x]" #f)
             ) #f #f))
(register-element! "SpecimenDefinition.typeTested.container.material" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.material") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.material" 'element))
(register-element! "SpecimenDefinition.typeTested.container.type" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.type") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.type" 'element))
(register-element! "SpecimenDefinition.typeTested.container.cap" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.cap") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.cap" 'element))
(register-element! "SpecimenDefinition.typeTested.container.description" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.description") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.description" 'element))
(register-element! "SpecimenDefinition.typeTested.container.capacity" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.capacity") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.capacity" 'element))
(register-element! "SpecimenDefinition.typeTested.container.additive" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.additive") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive" 'element))
(register-element! "SpecimenDefinition.typeTested.container.preparation" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.preparation") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.preparation" 'element))
(register-element! "SpecimenDefinition.typeTested.container.minimumVolume[x]" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.minimumVolume[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.minimumVolume[x]" 'element))
(register-element! "SpecimenDefinition.typeTested.container.minimumVolume[x]" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.minimumVolume[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.minimumVolume[x]" 'element))

(register-type! 'SpecimenDefinitionTypeTestedContainerAdditive (fhir-spec 'SpecimenDefinitionTypeTestedContainerAdditive "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive" 'type)
  #:schema (type-schema 'SpecimenDefinitionTypeTestedContainerAdditive #f 'BackboneElement "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive"
             (list
    (schema-field 'additiveCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'additive "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive.additive[x]" #f)
    (schema-field 'additiveReference 0 1 (vector 'type 'Reference) 'additive "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive.additive[x]" #f)
             ) #f #f))
(register-element! "SpecimenDefinition.typeTested.container.additive.additive[x]" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.additive.additive[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive.additive[x]" 'element))
(register-element! "SpecimenDefinition.typeTested.container.additive.additive[x]" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.container.additive.additive[x]") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.container.additive.additive[x]" 'element))

(register-type! 'SpecimenDefinitionTypeTestedHandling (fhir-spec 'SpecimenDefinitionTypeTestedHandling "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling" 'type)
  #:schema (type-schema 'SpecimenDefinitionTypeTestedHandling #f 'BackboneElement "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling"
             (list
    (schema-field 'temperatureQualifier 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.temperatureQualifier" #f)
    (schema-field 'temperatureRange 0 1 (vector 'type 'Range) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.temperatureRange" #f)
    (schema-field 'maxDuration 0 1 (vector 'type 'Duration) #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.maxDuration" #f)
    (schema-field 'instruction 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.instruction" #f)
             ) #f #f))
(register-element! "SpecimenDefinition.typeTested.handling.temperatureQualifier" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.handling.temperatureQualifier") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.temperatureQualifier" 'element))
(register-element! "SpecimenDefinition.typeTested.handling.temperatureRange" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.handling.temperatureRange") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.temperatureRange" 'element))
(register-element! "SpecimenDefinition.typeTested.handling.maxDuration" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.handling.maxDuration") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.maxDuration" 'element))
(register-element! "SpecimenDefinition.typeTested.handling.instruction" (fhir-spec (string->symbol "SpecimenDefinition.typeTested.handling.instruction") "https://build.fhir.org/specimendefinition.html#SpecimenDefinition.typeTested.handling.instruction" 'element))

