#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'StructureDefinition (fhir-spec 'StructureDefinition "https://build.fhir.org/structuredefinition.html#StructureDefinition" 'type)
  #:schema (type-schema 'StructureDefinition #f 'DomainResource "https://build.fhir.org/structuredefinition.html#StructureDefinition"
             (list
    (schema-field 'url 1 1 (vector 'prim "uri") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.version" #f)
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.copyrightLabel" #f)
    (schema-field 'keyword 0 '* (vector 'type 'Coding) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.keyword" #f)
    (schema-field 'fhirVersion 0 1 (vector 'prim "code") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.fhirVersion" #f)
    (schema-field 'mapping 0 '* (vector 'type 'StructureDefinitionMapping) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping" #f)
    (schema-field 'kind 1 1 (vector 'prim "code") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.kind" #f)
    (schema-field 'abstract 1 1 (vector 'prim "boolean") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.abstract" #f)
    (schema-field 'context 0 '* (vector 'type 'StructureDefinitionContext) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.context" #f)
    (schema-field 'contextInvariant 0 '* (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.contextInvariant" #f)
    (schema-field 'type 1 1 (vector 'prim "uri") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.type" #f)
    (schema-field 'baseDefinition 0 1 (vector 'prim "canonical") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.baseDefinition" #f)
    (schema-field 'derivation 0 1 (vector 'prim "code") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.derivation" #f)
    (schema-field 'snapshot 0 1 (vector 'type 'StructureDefinitionSnapshot) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.snapshot" #f)
    (schema-field 'differential 0 1 (vector 'type 'StructureDefinitionDifferential) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.differential" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/structuredefinition.html#StructureDefinition.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/structuredefinition.html#StructureDefinition.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "StructureDefinition.url" (fhir-spec (string->symbol "StructureDefinition.url") "https://build.fhir.org/structuredefinition.html#StructureDefinition.url" 'element))
(register-element! "StructureDefinition.identifier" (fhir-spec (string->symbol "StructureDefinition.identifier") "https://build.fhir.org/structuredefinition.html#StructureDefinition.identifier" 'element))
(register-element! "StructureDefinition.version" (fhir-spec (string->symbol "StructureDefinition.version") "https://build.fhir.org/structuredefinition.html#StructureDefinition.version" 'element))
(register-element! "StructureDefinition.name" (fhir-spec (string->symbol "StructureDefinition.name") "https://build.fhir.org/structuredefinition.html#StructureDefinition.name" 'element))
(register-element! "StructureDefinition.title" (fhir-spec (string->symbol "StructureDefinition.title") "https://build.fhir.org/structuredefinition.html#StructureDefinition.title" 'element))
(register-element! "StructureDefinition.status" (fhir-spec (string->symbol "StructureDefinition.status") "https://build.fhir.org/structuredefinition.html#StructureDefinition.status" 'element))
(register-element! "StructureDefinition.experimental" (fhir-spec (string->symbol "StructureDefinition.experimental") "https://build.fhir.org/structuredefinition.html#StructureDefinition.experimental" 'element))
(register-element! "StructureDefinition.date" (fhir-spec (string->symbol "StructureDefinition.date") "https://build.fhir.org/structuredefinition.html#StructureDefinition.date" 'element))
(register-element! "StructureDefinition.publisher" (fhir-spec (string->symbol "StructureDefinition.publisher") "https://build.fhir.org/structuredefinition.html#StructureDefinition.publisher" 'element))
(register-element! "StructureDefinition.contact" (fhir-spec (string->symbol "StructureDefinition.contact") "https://build.fhir.org/structuredefinition.html#StructureDefinition.contact" 'element))
(register-element! "StructureDefinition.description" (fhir-spec (string->symbol "StructureDefinition.description") "https://build.fhir.org/structuredefinition.html#StructureDefinition.description" 'element))
(register-element! "StructureDefinition.useContext" (fhir-spec (string->symbol "StructureDefinition.useContext") "https://build.fhir.org/structuredefinition.html#StructureDefinition.useContext" 'element))
(register-element! "StructureDefinition.jurisdiction" (fhir-spec (string->symbol "StructureDefinition.jurisdiction") "https://build.fhir.org/structuredefinition.html#StructureDefinition.jurisdiction" 'element))
(register-element! "StructureDefinition.purpose" (fhir-spec (string->symbol "StructureDefinition.purpose") "https://build.fhir.org/structuredefinition.html#StructureDefinition.purpose" 'element))
(register-element! "StructureDefinition.copyright" (fhir-spec (string->symbol "StructureDefinition.copyright") "https://build.fhir.org/structuredefinition.html#StructureDefinition.copyright" 'element))
(register-element! "StructureDefinition.copyrightLabel" (fhir-spec (string->symbol "StructureDefinition.copyrightLabel") "https://build.fhir.org/structuredefinition.html#StructureDefinition.copyrightLabel" 'element))
(register-element! "StructureDefinition.keyword" (fhir-spec (string->symbol "StructureDefinition.keyword") "https://build.fhir.org/structuredefinition.html#StructureDefinition.keyword" 'element))
(register-element! "StructureDefinition.fhirVersion" (fhir-spec (string->symbol "StructureDefinition.fhirVersion") "https://build.fhir.org/structuredefinition.html#StructureDefinition.fhirVersion" 'element))
(register-element! "StructureDefinition.mapping" (fhir-spec (string->symbol "StructureDefinition.mapping") "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping" 'element))
(register-element! "StructureDefinition.kind" (fhir-spec (string->symbol "StructureDefinition.kind") "https://build.fhir.org/structuredefinition.html#StructureDefinition.kind" 'element))
(register-element! "StructureDefinition.abstract" (fhir-spec (string->symbol "StructureDefinition.abstract") "https://build.fhir.org/structuredefinition.html#StructureDefinition.abstract" 'element))
(register-element! "StructureDefinition.context" (fhir-spec (string->symbol "StructureDefinition.context") "https://build.fhir.org/structuredefinition.html#StructureDefinition.context" 'element))
(register-element! "StructureDefinition.contextInvariant" (fhir-spec (string->symbol "StructureDefinition.contextInvariant") "https://build.fhir.org/structuredefinition.html#StructureDefinition.contextInvariant" 'element))
(register-element! "StructureDefinition.type" (fhir-spec (string->symbol "StructureDefinition.type") "https://build.fhir.org/structuredefinition.html#StructureDefinition.type" 'element))
(register-element! "StructureDefinition.baseDefinition" (fhir-spec (string->symbol "StructureDefinition.baseDefinition") "https://build.fhir.org/structuredefinition.html#StructureDefinition.baseDefinition" 'element))
(register-element! "StructureDefinition.derivation" (fhir-spec (string->symbol "StructureDefinition.derivation") "https://build.fhir.org/structuredefinition.html#StructureDefinition.derivation" 'element))
(register-element! "StructureDefinition.snapshot" (fhir-spec (string->symbol "StructureDefinition.snapshot") "https://build.fhir.org/structuredefinition.html#StructureDefinition.snapshot" 'element))
(register-element! "StructureDefinition.differential" (fhir-spec (string->symbol "StructureDefinition.differential") "https://build.fhir.org/structuredefinition.html#StructureDefinition.differential" 'element))
(register-element! "StructureDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "StructureDefinition.versionAlgorithm[x]") "https://build.fhir.org/structuredefinition.html#StructureDefinition.versionAlgorithm[x]" 'element))
(register-element! "StructureDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "StructureDefinition.versionAlgorithm[x]") "https://build.fhir.org/structuredefinition.html#StructureDefinition.versionAlgorithm[x]" 'element))

(register-type! 'StructureDefinitionMapping (fhir-spec 'StructureDefinitionMapping "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping" 'type)
  #:schema (type-schema 'StructureDefinitionMapping #f 'BackboneElement "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping"
             (list
    (schema-field 'identity 1 1 (vector 'prim "id") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.identity" #f)
    (schema-field 'uri 0 1 (vector 'prim "uri") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.uri" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.name" #f)
    (schema-field 'comment 0 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.comment" #f)
             ) #f #f))
(register-element! "StructureDefinition.mapping.identity" (fhir-spec (string->symbol "StructureDefinition.mapping.identity") "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.identity" 'element))
(register-element! "StructureDefinition.mapping.uri" (fhir-spec (string->symbol "StructureDefinition.mapping.uri") "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.uri" 'element))
(register-element! "StructureDefinition.mapping.name" (fhir-spec (string->symbol "StructureDefinition.mapping.name") "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.name" 'element))
(register-element! "StructureDefinition.mapping.comment" (fhir-spec (string->symbol "StructureDefinition.mapping.comment") "https://build.fhir.org/structuredefinition.html#StructureDefinition.mapping.comment" 'element))

(register-type! 'StructureDefinitionContext (fhir-spec 'StructureDefinitionContext "https://build.fhir.org/structuredefinition.html#StructureDefinition.context" 'type)
  #:schema (type-schema 'StructureDefinitionContext #f 'BackboneElement "https://build.fhir.org/structuredefinition.html#StructureDefinition.context"
             (list
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.context.type" #f)
    (schema-field 'expression 1 1 (vector 'prim "string") #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.context.expression" #f)
             ) #f #f))
(register-element! "StructureDefinition.context.type" (fhir-spec (string->symbol "StructureDefinition.context.type") "https://build.fhir.org/structuredefinition.html#StructureDefinition.context.type" 'element))
(register-element! "StructureDefinition.context.expression" (fhir-spec (string->symbol "StructureDefinition.context.expression") "https://build.fhir.org/structuredefinition.html#StructureDefinition.context.expression" 'element))

(register-type! 'StructureDefinitionSnapshot (fhir-spec 'StructureDefinitionSnapshot "https://build.fhir.org/structuredefinition.html#StructureDefinition.snapshot" 'type)
  #:schema (type-schema 'StructureDefinitionSnapshot #f 'BackboneElement "https://build.fhir.org/structuredefinition.html#StructureDefinition.snapshot"
             (list
    (schema-field 'element 1 '* (vector 'type 'ElementDefinition) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.snapshot.element" #f)
             ) #f #f))
(register-element! "StructureDefinition.snapshot.element" (fhir-spec (string->symbol "StructureDefinition.snapshot.element") "https://build.fhir.org/structuredefinition.html#StructureDefinition.snapshot.element" 'element))

(register-type! 'StructureDefinitionDifferential (fhir-spec 'StructureDefinitionDifferential "https://build.fhir.org/structuredefinition.html#StructureDefinition.differential" 'type)
  #:schema (type-schema 'StructureDefinitionDifferential #f 'BackboneElement "https://build.fhir.org/structuredefinition.html#StructureDefinition.differential"
             (list
    (schema-field 'element 1 '* (vector 'type 'ElementDefinition) #f "https://build.fhir.org/structuredefinition.html#StructureDefinition.differential.element" #f)
             ) #f #f))
(register-element! "StructureDefinition.differential.element" (fhir-spec (string->symbol "StructureDefinition.differential.element") "https://build.fhir.org/structuredefinition.html#StructureDefinition.differential.element" 'element))

