#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'SubscriptionTopic (fhir-spec 'SubscriptionTopic "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic" 'type)
  #:schema (type-schema 'SubscriptionTopic #f 'DomainResource "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic"
             (list
    (schema-field 'url 1 1 (vector 'prim "uri") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.title" #f)
    (schema-field 'derivedFrom 0 '* (vector 'prim "canonical") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.derivedFrom" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.effectivePeriod" #f)
    (schema-field 'trigger 0 '* (vector 'type 'SubscriptionTopicTrigger) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "SubscriptionTopic.url" (fhir-spec (string->symbol "SubscriptionTopic.url") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.url" 'element))
(register-element! "SubscriptionTopic.identifier" (fhir-spec (string->symbol "SubscriptionTopic.identifier") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.identifier" 'element))
(register-element! "SubscriptionTopic.version" (fhir-spec (string->symbol "SubscriptionTopic.version") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.version" 'element))
(register-element! "SubscriptionTopic.name" (fhir-spec (string->symbol "SubscriptionTopic.name") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.name" 'element))
(register-element! "SubscriptionTopic.title" (fhir-spec (string->symbol "SubscriptionTopic.title") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.title" 'element))
(register-element! "SubscriptionTopic.derivedFrom" (fhir-spec (string->symbol "SubscriptionTopic.derivedFrom") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.derivedFrom" 'element))
(register-element! "SubscriptionTopic.status" (fhir-spec (string->symbol "SubscriptionTopic.status") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.status" 'element))
(register-element! "SubscriptionTopic.experimental" (fhir-spec (string->symbol "SubscriptionTopic.experimental") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.experimental" 'element))
(register-element! "SubscriptionTopic.date" (fhir-spec (string->symbol "SubscriptionTopic.date") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.date" 'element))
(register-element! "SubscriptionTopic.publisher" (fhir-spec (string->symbol "SubscriptionTopic.publisher") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.publisher" 'element))
(register-element! "SubscriptionTopic.contact" (fhir-spec (string->symbol "SubscriptionTopic.contact") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.contact" 'element))
(register-element! "SubscriptionTopic.description" (fhir-spec (string->symbol "SubscriptionTopic.description") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.description" 'element))
(register-element! "SubscriptionTopic.useContext" (fhir-spec (string->symbol "SubscriptionTopic.useContext") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.useContext" 'element))
(register-element! "SubscriptionTopic.jurisdiction" (fhir-spec (string->symbol "SubscriptionTopic.jurisdiction") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.jurisdiction" 'element))
(register-element! "SubscriptionTopic.purpose" (fhir-spec (string->symbol "SubscriptionTopic.purpose") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.purpose" 'element))
(register-element! "SubscriptionTopic.copyright" (fhir-spec (string->symbol "SubscriptionTopic.copyright") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.copyright" 'element))
(register-element! "SubscriptionTopic.copyrightLabel" (fhir-spec (string->symbol "SubscriptionTopic.copyrightLabel") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.copyrightLabel" 'element))
(register-element! "SubscriptionTopic.approvalDate" (fhir-spec (string->symbol "SubscriptionTopic.approvalDate") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.approvalDate" 'element))
(register-element! "SubscriptionTopic.lastReviewDate" (fhir-spec (string->symbol "SubscriptionTopic.lastReviewDate") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.lastReviewDate" 'element))
(register-element! "SubscriptionTopic.effectivePeriod" (fhir-spec (string->symbol "SubscriptionTopic.effectivePeriod") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.effectivePeriod" 'element))
(register-element! "SubscriptionTopic.trigger" (fhir-spec (string->symbol "SubscriptionTopic.trigger") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger" 'element))
(register-element! "SubscriptionTopic.versionAlgorithm[x]" (fhir-spec (string->symbol "SubscriptionTopic.versionAlgorithm[x]") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.versionAlgorithm[x]" 'element))
(register-element! "SubscriptionTopic.versionAlgorithm[x]" (fhir-spec (string->symbol "SubscriptionTopic.versionAlgorithm[x]") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.versionAlgorithm[x]" 'element))

(register-type! 'SubscriptionTopicTrigger (fhir-spec 'SubscriptionTopicTrigger "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger" 'type)
  #:schema (type-schema 'SubscriptionTopicTrigger #f 'BackboneElement "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.description" #f)
    (schema-field 'resource 1 1 (vector 'prim "uri") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.resource" #f)
    (schema-field 'supportedInteraction 0 '* (vector 'prim "code") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.supportedInteraction" #f)
    (schema-field 'queryCriteria 0 1 (vector 'type 'SubscriptionTopicTriggerQueryCriteria) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria" #f)
    (schema-field 'fhirPathCriteria 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.fhirPathCriteria" #f)
    (schema-field 'event 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.event" #f)
    (schema-field 'canFilterBy 0 '* (vector 'type 'SubscriptionTopicTriggerCanFilterBy) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy" #f)
    (schema-field 'notificationShape 0 '* (vector 'type 'SubscriptionTopicTriggerNotificationShape) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape" #f)
             ) #f #f))
(register-element! "SubscriptionTopic.trigger.description" (fhir-spec (string->symbol "SubscriptionTopic.trigger.description") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.description" 'element))
(register-element! "SubscriptionTopic.trigger.resource" (fhir-spec (string->symbol "SubscriptionTopic.trigger.resource") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.resource" 'element))
(register-element! "SubscriptionTopic.trigger.supportedInteraction" (fhir-spec (string->symbol "SubscriptionTopic.trigger.supportedInteraction") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.supportedInteraction" 'element))
(register-element! "SubscriptionTopic.trigger.queryCriteria" (fhir-spec (string->symbol "SubscriptionTopic.trigger.queryCriteria") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria" 'element))
(register-element! "SubscriptionTopic.trigger.fhirPathCriteria" (fhir-spec (string->symbol "SubscriptionTopic.trigger.fhirPathCriteria") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.fhirPathCriteria" 'element))
(register-element! "SubscriptionTopic.trigger.event" (fhir-spec (string->symbol "SubscriptionTopic.trigger.event") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.event" 'element))
(register-element! "SubscriptionTopic.trigger.canFilterBy" (fhir-spec (string->symbol "SubscriptionTopic.trigger.canFilterBy") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy" 'element))
(register-element! "SubscriptionTopic.trigger.notificationShape" (fhir-spec (string->symbol "SubscriptionTopic.trigger.notificationShape") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape" 'element))

(register-type! 'SubscriptionTopicTriggerQueryCriteria (fhir-spec 'SubscriptionTopicTriggerQueryCriteria "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria" 'type)
  #:schema (type-schema 'SubscriptionTopicTriggerQueryCriteria #f 'BackboneElement "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria"
             (list
    (schema-field 'previous 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.previous" #f)
    (schema-field 'resultForCreate 0 1 (vector 'prim "code") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.resultForCreate" #f)
    (schema-field 'current 0 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.current" #f)
    (schema-field 'resultForDelete 0 1 (vector 'prim "code") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.resultForDelete" #f)
    (schema-field 'requireBoth 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.requireBoth" #f)
             ) #f #f))
(register-element! "SubscriptionTopic.trigger.queryCriteria.previous" (fhir-spec (string->symbol "SubscriptionTopic.trigger.queryCriteria.previous") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.previous" 'element))
(register-element! "SubscriptionTopic.trigger.queryCriteria.resultForCreate" (fhir-spec (string->symbol "SubscriptionTopic.trigger.queryCriteria.resultForCreate") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.resultForCreate" 'element))
(register-element! "SubscriptionTopic.trigger.queryCriteria.current" (fhir-spec (string->symbol "SubscriptionTopic.trigger.queryCriteria.current") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.current" 'element))
(register-element! "SubscriptionTopic.trigger.queryCriteria.resultForDelete" (fhir-spec (string->symbol "SubscriptionTopic.trigger.queryCriteria.resultForDelete") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.resultForDelete" 'element))
(register-element! "SubscriptionTopic.trigger.queryCriteria.requireBoth" (fhir-spec (string->symbol "SubscriptionTopic.trigger.queryCriteria.requireBoth") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.queryCriteria.requireBoth" 'element))

(register-type! 'SubscriptionTopicTriggerCanFilterBy (fhir-spec 'SubscriptionTopicTriggerCanFilterBy "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy" 'type)
  #:schema (type-schema 'SubscriptionTopicTriggerCanFilterBy #f 'BackboneElement "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.description" #f)
    (schema-field 'resource 0 1 (vector 'prim "uri") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.resource" #f)
    (schema-field 'filterParameter 1 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.filterParameter" #f)
    (schema-field 'filterDefinition 0 1 (vector 'prim "uri") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.filterDefinition" #f)
    (schema-field 'comparator 0 '* (vector 'prim "code") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.comparator" #f)
    (schema-field 'modifier 0 '* (vector 'prim "code") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.modifier" #f)
             ) #f #f))
(register-element! "SubscriptionTopic.trigger.canFilterBy.description" (fhir-spec (string->symbol "SubscriptionTopic.trigger.canFilterBy.description") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.description" 'element))
(register-element! "SubscriptionTopic.trigger.canFilterBy.resource" (fhir-spec (string->symbol "SubscriptionTopic.trigger.canFilterBy.resource") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.resource" 'element))
(register-element! "SubscriptionTopic.trigger.canFilterBy.filterParameter" (fhir-spec (string->symbol "SubscriptionTopic.trigger.canFilterBy.filterParameter") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.filterParameter" 'element))
(register-element! "SubscriptionTopic.trigger.canFilterBy.filterDefinition" (fhir-spec (string->symbol "SubscriptionTopic.trigger.canFilterBy.filterDefinition") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.filterDefinition" 'element))
(register-element! "SubscriptionTopic.trigger.canFilterBy.comparator" (fhir-spec (string->symbol "SubscriptionTopic.trigger.canFilterBy.comparator") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.comparator" 'element))
(register-element! "SubscriptionTopic.trigger.canFilterBy.modifier" (fhir-spec (string->symbol "SubscriptionTopic.trigger.canFilterBy.modifier") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.canFilterBy.modifier" 'element))

(register-type! 'SubscriptionTopicTriggerNotificationShape (fhir-spec 'SubscriptionTopicTriggerNotificationShape "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape" 'type)
  #:schema (type-schema 'SubscriptionTopicTriggerNotificationShape #f 'BackboneElement "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape"
             (list
    (schema-field 'resource 1 1 (vector 'prim "uri") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.resource" #f)
    (schema-field 'include 0 '* (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.include" #f)
    (schema-field 'revInclude 0 '* (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.revInclude" #f)
    (schema-field 'relatedQuery 0 '* (vector 'type 'SubscriptionTopicTriggerNotificationShapeRelatedQuery) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery" #f)
             ) #f #f))
(register-element! "SubscriptionTopic.trigger.notificationShape.resource" (fhir-spec (string->symbol "SubscriptionTopic.trigger.notificationShape.resource") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.resource" 'element))
(register-element! "SubscriptionTopic.trigger.notificationShape.include" (fhir-spec (string->symbol "SubscriptionTopic.trigger.notificationShape.include") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.include" 'element))
(register-element! "SubscriptionTopic.trigger.notificationShape.revInclude" (fhir-spec (string->symbol "SubscriptionTopic.trigger.notificationShape.revInclude") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.revInclude" 'element))
(register-element! "SubscriptionTopic.trigger.notificationShape.relatedQuery" (fhir-spec (string->symbol "SubscriptionTopic.trigger.notificationShape.relatedQuery") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery" 'element))

(register-type! 'SubscriptionTopicTriggerNotificationShapeRelatedQuery (fhir-spec 'SubscriptionTopicTriggerNotificationShapeRelatedQuery "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery" 'type)
  #:schema (type-schema 'SubscriptionTopicTriggerNotificationShapeRelatedQuery #f 'BackboneElement "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery"
             (list
    (schema-field 'queryType 0 1 (vector 'type 'Coding) #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery.queryType" #f)
    (schema-field 'query 1 1 (vector 'prim "string") #f "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery.query" #f)
             ) #f #f))
(register-element! "SubscriptionTopic.trigger.notificationShape.relatedQuery.queryType" (fhir-spec (string->symbol "SubscriptionTopic.trigger.notificationShape.relatedQuery.queryType") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery.queryType" 'element))
(register-element! "SubscriptionTopic.trigger.notificationShape.relatedQuery.query" (fhir-spec (string->symbol "SubscriptionTopic.trigger.notificationShape.relatedQuery.query") "https://build.fhir.org/subscriptiontopic.html#SubscriptionTopic.trigger.notificationShape.relatedQuery.query" 'element))

