#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Task (fhir-spec 'Task "https://build.fhir.org/task.html#Task" 'type)
  #:schema (type-schema 'Task #f 'DomainResource "https://build.fhir.org/task.html#Task"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://build.fhir.org/task.html#Task.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.basedOn" #f)
    (schema-field 'groupIdentifier 0 1 (vector 'type 'Identifier) #f "https://build.fhir.org/task.html#Task.groupIdentifier" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://build.fhir.org/task.html#Task.status" #f)
    (schema-field 'statusReason 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/task.html#Task.statusReason" #f)
    (schema-field 'businessStatus 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/task.html#Task.businessStatus" #f)
    (schema-field 'intent 1 1 (vector 'prim "code") #f "https://build.fhir.org/task.html#Task.intent" #f)
    (schema-field 'priority 0 1 (vector 'prim "code") #f "https://build.fhir.org/task.html#Task.priority" #f)
    (schema-field 'doNotPerform 0 1 (vector 'prim "boolean") #f "https://build.fhir.org/task.html#Task.doNotPerform" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/task.html#Task.code" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://build.fhir.org/task.html#Task.description" #f)
    (schema-field 'focus 0 '* (vector 'type 'TaskFocus) #f "https://build.fhir.org/task.html#Task.focus" #f)
    (schema-field 'for 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.for" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.encounter" #f)
    (schema-field 'requestedPeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/task.html#Task.requestedPeriod" #f)
    (schema-field 'executionPeriod 0 1 (vector 'type 'Period) #f "https://build.fhir.org/task.html#Task.executionPeriod" #f)
    (schema-field 'authoredOn 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/task.html#Task.authoredOn" #f)
    (schema-field 'lastModified 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/task.html#Task.lastModified" #f)
    (schema-field 'requester 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.requester" #f)
    (schema-field 'requestedPerformer 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/task.html#Task.requestedPerformer" #f)
    (schema-field 'owner 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.owner" #f)
    (schema-field 'performer 0 '* (vector 'type 'TaskPerformer) #f "https://build.fhir.org/task.html#Task.performer" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.location" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://build.fhir.org/task.html#Task.reason" #f)
    (schema-field 'insurance 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.insurance" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://build.fhir.org/task.html#Task.note" #f)
    (schema-field 'relevantHistory 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.relevantHistory" #f)
    (schema-field 'restriction 0 1 (vector 'type 'TaskRestriction) #f "https://build.fhir.org/task.html#Task.restriction" #f)
    (schema-field 'input 0 '* (vector 'type 'TaskInput) #f "https://build.fhir.org/task.html#Task.input" #f)
    (schema-field 'output 0 '* (vector 'type 'TaskOutput) #f "https://build.fhir.org/task.html#Task.output" #f)
             ) #f #f))
(register-element! "Task.identifier" (fhir-spec (string->symbol "Task.identifier") "https://build.fhir.org/task.html#Task.identifier" 'element))
(register-element! "Task.basedOn" (fhir-spec (string->symbol "Task.basedOn") "https://build.fhir.org/task.html#Task.basedOn" 'element))
(register-element! "Task.groupIdentifier" (fhir-spec (string->symbol "Task.groupIdentifier") "https://build.fhir.org/task.html#Task.groupIdentifier" 'element))
(register-element! "Task.partOf" (fhir-spec (string->symbol "Task.partOf") "https://build.fhir.org/task.html#Task.partOf" 'element))
(register-element! "Task.status" (fhir-spec (string->symbol "Task.status") "https://build.fhir.org/task.html#Task.status" 'element))
(register-element! "Task.statusReason" (fhir-spec (string->symbol "Task.statusReason") "https://build.fhir.org/task.html#Task.statusReason" 'element))
(register-element! "Task.businessStatus" (fhir-spec (string->symbol "Task.businessStatus") "https://build.fhir.org/task.html#Task.businessStatus" 'element))
(register-element! "Task.intent" (fhir-spec (string->symbol "Task.intent") "https://build.fhir.org/task.html#Task.intent" 'element))
(register-element! "Task.priority" (fhir-spec (string->symbol "Task.priority") "https://build.fhir.org/task.html#Task.priority" 'element))
(register-element! "Task.doNotPerform" (fhir-spec (string->symbol "Task.doNotPerform") "https://build.fhir.org/task.html#Task.doNotPerform" 'element))
(register-element! "Task.code" (fhir-spec (string->symbol "Task.code") "https://build.fhir.org/task.html#Task.code" 'element))
(register-element! "Task.description" (fhir-spec (string->symbol "Task.description") "https://build.fhir.org/task.html#Task.description" 'element))
(register-element! "Task.focus" (fhir-spec (string->symbol "Task.focus") "https://build.fhir.org/task.html#Task.focus" 'element))
(register-element! "Task.for" (fhir-spec (string->symbol "Task.for") "https://build.fhir.org/task.html#Task.for" 'element))
(register-element! "Task.encounter" (fhir-spec (string->symbol "Task.encounter") "https://build.fhir.org/task.html#Task.encounter" 'element))
(register-element! "Task.requestedPeriod" (fhir-spec (string->symbol "Task.requestedPeriod") "https://build.fhir.org/task.html#Task.requestedPeriod" 'element))
(register-element! "Task.executionPeriod" (fhir-spec (string->symbol "Task.executionPeriod") "https://build.fhir.org/task.html#Task.executionPeriod" 'element))
(register-element! "Task.authoredOn" (fhir-spec (string->symbol "Task.authoredOn") "https://build.fhir.org/task.html#Task.authoredOn" 'element))
(register-element! "Task.lastModified" (fhir-spec (string->symbol "Task.lastModified") "https://build.fhir.org/task.html#Task.lastModified" 'element))
(register-element! "Task.requester" (fhir-spec (string->symbol "Task.requester") "https://build.fhir.org/task.html#Task.requester" 'element))
(register-element! "Task.requestedPerformer" (fhir-spec (string->symbol "Task.requestedPerformer") "https://build.fhir.org/task.html#Task.requestedPerformer" 'element))
(register-element! "Task.owner" (fhir-spec (string->symbol "Task.owner") "https://build.fhir.org/task.html#Task.owner" 'element))
(register-element! "Task.performer" (fhir-spec (string->symbol "Task.performer") "https://build.fhir.org/task.html#Task.performer" 'element))
(register-element! "Task.location" (fhir-spec (string->symbol "Task.location") "https://build.fhir.org/task.html#Task.location" 'element))
(register-element! "Task.reason" (fhir-spec (string->symbol "Task.reason") "https://build.fhir.org/task.html#Task.reason" 'element))
(register-element! "Task.insurance" (fhir-spec (string->symbol "Task.insurance") "https://build.fhir.org/task.html#Task.insurance" 'element))
(register-element! "Task.note" (fhir-spec (string->symbol "Task.note") "https://build.fhir.org/task.html#Task.note" 'element))
(register-element! "Task.relevantHistory" (fhir-spec (string->symbol "Task.relevantHistory") "https://build.fhir.org/task.html#Task.relevantHistory" 'element))
(register-element! "Task.restriction" (fhir-spec (string->symbol "Task.restriction") "https://build.fhir.org/task.html#Task.restriction" 'element))
(register-element! "Task.input" (fhir-spec (string->symbol "Task.input") "https://build.fhir.org/task.html#Task.input" 'element))
(register-element! "Task.output" (fhir-spec (string->symbol "Task.output") "https://build.fhir.org/task.html#Task.output" 'element))

(register-type! 'TaskFocus (fhir-spec 'TaskFocus "https://build.fhir.org/task.html#Task.focus" 'type)
  #:schema (type-schema 'TaskFocus #f 'BackboneElement "https://build.fhir.org/task.html#Task.focus"
             (list
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/task.html#Task.focus.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://build.fhir.org/task.html#Task.focus.value[x]" #f)
             ) #f #f))
(register-element! "Task.focus.value[x]" (fhir-spec (string->symbol "Task.focus.value[x]") "https://build.fhir.org/task.html#Task.focus.value[x]" 'element))
(register-element! "Task.focus.value[x]" (fhir-spec (string->symbol "Task.focus.value[x]") "https://build.fhir.org/task.html#Task.focus.value[x]" 'element))

(register-type! 'TaskPerformer (fhir-spec 'TaskPerformer "https://build.fhir.org/task.html#Task.performer" 'type)
  #:schema (type-schema 'TaskPerformer #f 'BackboneElement "https://build.fhir.org/task.html#Task.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/task.html#Task.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.performer.actor" #f)
             ) #f #f))
(register-element! "Task.performer.function" (fhir-spec (string->symbol "Task.performer.function") "https://build.fhir.org/task.html#Task.performer.function" 'element))
(register-element! "Task.performer.actor" (fhir-spec (string->symbol "Task.performer.actor") "https://build.fhir.org/task.html#Task.performer.actor" 'element))

(register-type! 'TaskRestriction (fhir-spec 'TaskRestriction "https://build.fhir.org/task.html#Task.restriction" 'type)
  #:schema (type-schema 'TaskRestriction #f 'BackboneElement "https://build.fhir.org/task.html#Task.restriction"
             (list
    (schema-field 'repetitions 0 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/task.html#Task.restriction.repetitions" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://build.fhir.org/task.html#Task.restriction.period" #f)
    (schema-field 'recipient 0 '* (vector 'type 'Reference) #f "https://build.fhir.org/task.html#Task.restriction.recipient" #f)
             ) #f #f))
(register-element! "Task.restriction.repetitions" (fhir-spec (string->symbol "Task.restriction.repetitions") "https://build.fhir.org/task.html#Task.restriction.repetitions" 'element))
(register-element! "Task.restriction.period" (fhir-spec (string->symbol "Task.restriction.period") "https://build.fhir.org/task.html#Task.restriction.period" 'element))
(register-element! "Task.restriction.recipient" (fhir-spec (string->symbol "Task.restriction.recipient") "https://build.fhir.org/task.html#Task.restriction.recipient" 'element))

(register-type! 'TaskInput (fhir-spec 'TaskInput "https://build.fhir.org/task.html#Task.input" 'type)
  #:schema (type-schema 'TaskInput #f 'BackboneElement "https://build.fhir.org/task.html#Task.input"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/task.html#Task.input.type" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueInteger64 0 1 (vector 'prim "integer64") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCodeableReference 0 1 (vector 'type 'CodeableReference) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueRatioRange 0 1 (vector 'type 'RatioRange) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueAvailability 0 1 (vector 'type 'Availability) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueExtendedContactDetail 0 1 (vector 'type 'ExtendedContactDetail) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueVirtualServiceDetail 0 1 (vector 'type 'VirtualServiceDetail) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://build.fhir.org/task.html#Task.input.value[x]" #f)
             ) #f #f))
(register-element! "Task.input.type" (fhir-spec (string->symbol "Task.input.type") "https://build.fhir.org/task.html#Task.input.type" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))
(register-element! "Task.input.value[x]" (fhir-spec (string->symbol "Task.input.value[x]") "https://build.fhir.org/task.html#Task.input.value[x]" 'element))

(register-type! 'TaskOutput (fhir-spec 'TaskOutput "https://build.fhir.org/task.html#Task.output" 'type)
  #:schema (type-schema 'TaskOutput #f 'BackboneElement "https://build.fhir.org/task.html#Task.output"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/task.html#Task.output.type" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueInteger64 0 1 (vector 'prim "integer64") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCodeableReference 0 1 (vector 'type 'CodeableReference) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueRatioRange 0 1 (vector 'type 'RatioRange) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueAvailability 0 1 (vector 'type 'Availability) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueExtendedContactDetail 0 1 (vector 'type 'ExtendedContactDetail) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueVirtualServiceDetail 0 1 (vector 'type 'VirtualServiceDetail) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://build.fhir.org/task.html#Task.output.value[x]" #f)
             ) #f #f))
(register-element! "Task.output.type" (fhir-spec (string->symbol "Task.output.type") "https://build.fhir.org/task.html#Task.output.type" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))
(register-element! "Task.output.value[x]" (fhir-spec (string->symbol "Task.output.value[x]") "https://build.fhir.org/task.html#Task.output.value[x]" 'element))

