#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Timing (fhir-spec 'Timing "https://build.fhir.org/datatypes.html#Timing" 'type)
  #:schema (type-schema 'Timing #f 'BackboneType "https://build.fhir.org/datatypes.html#Timing"
             (list
    (schema-field 'event 0 '* (vector 'prim "dateTime") #f "https://build.fhir.org/datatypes.html#Timing.event" #f)
    (schema-field 'repeat 0 1 (vector 'type 'TimingRepeat) #f "https://build.fhir.org/datatypes.html#Timing.repeat" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://build.fhir.org/datatypes.html#Timing.code" #f)
             ) #f #f))
(register-element! "Timing.event" (fhir-spec (string->symbol "Timing.event") "https://build.fhir.org/datatypes.html#Timing.event" 'element))
(register-element! "Timing.repeat" (fhir-spec (string->symbol "Timing.repeat") "https://build.fhir.org/datatypes.html#Timing.repeat" 'element))
(register-element! "Timing.code" (fhir-spec (string->symbol "Timing.code") "https://build.fhir.org/datatypes.html#Timing.code" 'element))

(register-type! 'TimingRepeat (fhir-spec 'TimingRepeat "https://build.fhir.org/datatypes.html#Timing.repeat" 'type)
  #:schema (type-schema 'TimingRepeat #f 'BackboneElement "https://build.fhir.org/datatypes.html#Timing.repeat"
             (list
    (schema-field 'count 0 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/datatypes.html#Timing.repeat.count" #f)
    (schema-field 'countMax 0 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/datatypes.html#Timing.repeat.countMax" #f)
    (schema-field 'duration 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/datatypes.html#Timing.repeat.duration" #f)
    (schema-field 'durationMax 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/datatypes.html#Timing.repeat.durationMax" #f)
    (schema-field 'durationUnit 0 1 (vector 'prim "code") #f "https://build.fhir.org/datatypes.html#Timing.repeat.durationUnit" #f)
    (schema-field 'frequency 0 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/datatypes.html#Timing.repeat.frequency" #f)
    (schema-field 'frequencyMax 0 1 (vector 'prim "positiveInt") #f "https://build.fhir.org/datatypes.html#Timing.repeat.frequencyMax" #f)
    (schema-field 'period 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/datatypes.html#Timing.repeat.period" #f)
    (schema-field 'periodMax 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/datatypes.html#Timing.repeat.periodMax" #f)
    (schema-field 'periodUnit 0 1 (vector 'prim "code") #f "https://build.fhir.org/datatypes.html#Timing.repeat.periodUnit" #f)
    (schema-field 'startOffset 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/datatypes.html#Timing.repeat.startOffset" #f)
    (schema-field 'endOffset 0 1 (vector 'type 'Quantity) #f "https://build.fhir.org/datatypes.html#Timing.repeat.endOffset" #f)
    (schema-field 'dayOfWeek 0 '* (vector 'prim "code") #f "https://build.fhir.org/datatypes.html#Timing.repeat.dayOfWeek" #f)
    (schema-field 'timeOfDay 0 '* (vector 'prim "time") #f "https://build.fhir.org/datatypes.html#Timing.repeat.timeOfDay" #f)
    (schema-field 'when 0 '* (vector 'prim "code") #f "https://build.fhir.org/datatypes.html#Timing.repeat.when" #f)
    (schema-field 'offset 0 1 (vector 'prim "unsignedInt") #f "https://build.fhir.org/datatypes.html#Timing.repeat.offset" #f)
    (schema-field 'boundsDuration 0 1 (vector 'type 'Duration) 'bounds "https://build.fhir.org/datatypes.html#Timing.repeat.bounds[x]" #f)
    (schema-field 'boundsRange 0 1 (vector 'type 'Range) 'bounds "https://build.fhir.org/datatypes.html#Timing.repeat.bounds[x]" #f)
    (schema-field 'boundsPeriod 0 1 (vector 'type 'Period) 'bounds "https://build.fhir.org/datatypes.html#Timing.repeat.bounds[x]" #f)
             ) #f #f))
(register-element! "Timing.repeat.count" (fhir-spec (string->symbol "Timing.repeat.count") "https://build.fhir.org/datatypes.html#Timing.repeat.count" 'element))
(register-element! "Timing.repeat.countMax" (fhir-spec (string->symbol "Timing.repeat.countMax") "https://build.fhir.org/datatypes.html#Timing.repeat.countMax" 'element))
(register-element! "Timing.repeat.duration" (fhir-spec (string->symbol "Timing.repeat.duration") "https://build.fhir.org/datatypes.html#Timing.repeat.duration" 'element))
(register-element! "Timing.repeat.durationMax" (fhir-spec (string->symbol "Timing.repeat.durationMax") "https://build.fhir.org/datatypes.html#Timing.repeat.durationMax" 'element))
(register-element! "Timing.repeat.durationUnit" (fhir-spec (string->symbol "Timing.repeat.durationUnit") "https://build.fhir.org/datatypes.html#Timing.repeat.durationUnit" 'element))
(register-element! "Timing.repeat.frequency" (fhir-spec (string->symbol "Timing.repeat.frequency") "https://build.fhir.org/datatypes.html#Timing.repeat.frequency" 'element))
(register-element! "Timing.repeat.frequencyMax" (fhir-spec (string->symbol "Timing.repeat.frequencyMax") "https://build.fhir.org/datatypes.html#Timing.repeat.frequencyMax" 'element))
(register-element! "Timing.repeat.period" (fhir-spec (string->symbol "Timing.repeat.period") "https://build.fhir.org/datatypes.html#Timing.repeat.period" 'element))
(register-element! "Timing.repeat.periodMax" (fhir-spec (string->symbol "Timing.repeat.periodMax") "https://build.fhir.org/datatypes.html#Timing.repeat.periodMax" 'element))
(register-element! "Timing.repeat.periodUnit" (fhir-spec (string->symbol "Timing.repeat.periodUnit") "https://build.fhir.org/datatypes.html#Timing.repeat.periodUnit" 'element))
(register-element! "Timing.repeat.startOffset" (fhir-spec (string->symbol "Timing.repeat.startOffset") "https://build.fhir.org/datatypes.html#Timing.repeat.startOffset" 'element))
(register-element! "Timing.repeat.endOffset" (fhir-spec (string->symbol "Timing.repeat.endOffset") "https://build.fhir.org/datatypes.html#Timing.repeat.endOffset" 'element))
(register-element! "Timing.repeat.dayOfWeek" (fhir-spec (string->symbol "Timing.repeat.dayOfWeek") "https://build.fhir.org/datatypes.html#Timing.repeat.dayOfWeek" 'element))
(register-element! "Timing.repeat.timeOfDay" (fhir-spec (string->symbol "Timing.repeat.timeOfDay") "https://build.fhir.org/datatypes.html#Timing.repeat.timeOfDay" 'element))
(register-element! "Timing.repeat.when" (fhir-spec (string->symbol "Timing.repeat.when") "https://build.fhir.org/datatypes.html#Timing.repeat.when" 'element))
(register-element! "Timing.repeat.offset" (fhir-spec (string->symbol "Timing.repeat.offset") "https://build.fhir.org/datatypes.html#Timing.repeat.offset" 'element))
(register-element! "Timing.repeat.bounds[x]" (fhir-spec (string->symbol "Timing.repeat.bounds[x]") "https://build.fhir.org/datatypes.html#Timing.repeat.bounds[x]" 'element))
(register-element! "Timing.repeat.bounds[x]" (fhir-spec (string->symbol "Timing.repeat.bounds[x]") "https://build.fhir.org/datatypes.html#Timing.repeat.bounds[x]" 'element))
(register-element! "Timing.repeat.bounds[x]" (fhir-spec (string->symbol "Timing.repeat.bounds[x]") "https://build.fhir.org/datatypes.html#Timing.repeat.bounds[x]" 'element))

