#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'condition_occurrence (fhir-spec 'condition_occurrence "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence" 'type)
  #:schema (type-schema 'condition_occurrence #f 'Base "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence"
             (list
    (schema-field 'condition_occurrence_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_occurrence_id" #f)
    (schema-field 'person_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.person_id" #f)
    (schema-field 'condition_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_concept_id" #f)
    (schema-field 'condition_start_date 1 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_start_date" #f)
    (schema-field 'condition_start_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_start_datetime" #f)
    (schema-field 'condition_end_date 0 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_end_date" #f)
    (schema-field 'condition_end_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_end_datetime" #f)
    (schema-field 'condition_type_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_type_concept_id" #f)
    (schema-field 'condition_status_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_status_concept_id" #f)
    (schema-field 'stop_reason 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.stop_reason" #f)
    (schema-field 'provider_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.provider_id" #f)
    (schema-field 'visit_occurrence_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.visit_occurrence_id" #f)
    (schema-field 'visit_detail_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.visit_detail_id" #f)
    (schema-field 'condition_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_source_value" #f)
    (schema-field 'condition_source_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_source_concept_id" #f)
    (schema-field 'condition_status_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_status_source_value" #f)
             ) #f #f))
(register-element! "condition_occurrence.condition_occurrence_id" (fhir-spec (string->symbol "condition_occurrence.condition_occurrence_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_occurrence_id" 'element))
(register-element! "condition_occurrence.person_id" (fhir-spec (string->symbol "condition_occurrence.person_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.person_id" 'element))
(register-element! "condition_occurrence.condition_concept_id" (fhir-spec (string->symbol "condition_occurrence.condition_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_concept_id" 'element))
(register-element! "condition_occurrence.condition_start_date" (fhir-spec (string->symbol "condition_occurrence.condition_start_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_start_date" 'element))
(register-element! "condition_occurrence.condition_start_datetime" (fhir-spec (string->symbol "condition_occurrence.condition_start_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_start_datetime" 'element))
(register-element! "condition_occurrence.condition_end_date" (fhir-spec (string->symbol "condition_occurrence.condition_end_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_end_date" 'element))
(register-element! "condition_occurrence.condition_end_datetime" (fhir-spec (string->symbol "condition_occurrence.condition_end_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_end_datetime" 'element))
(register-element! "condition_occurrence.condition_type_concept_id" (fhir-spec (string->symbol "condition_occurrence.condition_type_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_type_concept_id" 'element))
(register-element! "condition_occurrence.condition_status_concept_id" (fhir-spec (string->symbol "condition_occurrence.condition_status_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_status_concept_id" 'element))
(register-element! "condition_occurrence.stop_reason" (fhir-spec (string->symbol "condition_occurrence.stop_reason") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.stop_reason" 'element))
(register-element! "condition_occurrence.provider_id" (fhir-spec (string->symbol "condition_occurrence.provider_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.provider_id" 'element))
(register-element! "condition_occurrence.visit_occurrence_id" (fhir-spec (string->symbol "condition_occurrence.visit_occurrence_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.visit_occurrence_id" 'element))
(register-element! "condition_occurrence.visit_detail_id" (fhir-spec (string->symbol "condition_occurrence.visit_detail_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.visit_detail_id" 'element))
(register-element! "condition_occurrence.condition_source_value" (fhir-spec (string->symbol "condition_occurrence.condition_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_source_value" 'element))
(register-element! "condition_occurrence.condition_source_concept_id" (fhir-spec (string->symbol "condition_occurrence.condition_source_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_source_concept_id" 'element))
(register-element! "condition_occurrence.condition_status_source_value" (fhir-spec (string->symbol "condition_occurrence.condition_status_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#condition_occurrence.condition_status_source_value" 'element))

