#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'cost (fhir-spec 'cost "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost" 'type)
  #:schema (type-schema 'cost #f 'Base "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost"
             (list
    (schema-field 'cost_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_id" #f)
    (schema-field 'cost_event_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_event_id" #f)
    (schema-field 'cost_domain_id 1 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_domain_id" #f)
    (schema-field 'cost_type_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_type_concept_id" #f)
    (schema-field 'currency_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.currency_concept_id" #f)
    (schema-field 'total_charge 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.total_charge" #f)
    (schema-field 'total_cost 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.total_cost" #f)
    (schema-field 'total_paid 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.total_paid" #f)
    (schema-field 'paid_by_payer 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_by_payer" #f)
    (schema-field 'paid_by_patient 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_by_patient" #f)
    (schema-field 'paid_patient_copay 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_patient_copay" #f)
    (schema-field 'paid_patient_coinsurance 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_patient_coinsurance" #f)
    (schema-field 'paid_patient_deductible 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_patient_deductible" #f)
    (schema-field 'paid_by_primary 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_by_primary" #f)
    (schema-field 'paid_ingredient_cost 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_ingredient_cost" #f)
    (schema-field 'paid_dispensing_fee 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_dispensing_fee" #f)
    (schema-field 'payer_plan_period_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.payer_plan_period_id" #f)
    (schema-field 'amount_allowed 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.amount_allowed" #f)
    (schema-field 'revenue_code_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.revenue_code_concept_id" #f)
    (schema-field 'revenue_code_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.revenue_code_source_value" #f)
    (schema-field 'drg_concept_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.drg_concept_id" #f)
    (schema-field 'drg_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.drg_source_value" #f)
             ) #f #f))
(register-element! "cost.cost_id" (fhir-spec (string->symbol "cost.cost_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_id" 'element))
(register-element! "cost.cost_event_id" (fhir-spec (string->symbol "cost.cost_event_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_event_id" 'element))
(register-element! "cost.cost_domain_id" (fhir-spec (string->symbol "cost.cost_domain_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_domain_id" 'element))
(register-element! "cost.cost_type_concept_id" (fhir-spec (string->symbol "cost.cost_type_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.cost_type_concept_id" 'element))
(register-element! "cost.currency_concept_id" (fhir-spec (string->symbol "cost.currency_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.currency_concept_id" 'element))
(register-element! "cost.total_charge" (fhir-spec (string->symbol "cost.total_charge") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.total_charge" 'element))
(register-element! "cost.total_cost" (fhir-spec (string->symbol "cost.total_cost") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.total_cost" 'element))
(register-element! "cost.total_paid" (fhir-spec (string->symbol "cost.total_paid") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.total_paid" 'element))
(register-element! "cost.paid_by_payer" (fhir-spec (string->symbol "cost.paid_by_payer") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_by_payer" 'element))
(register-element! "cost.paid_by_patient" (fhir-spec (string->symbol "cost.paid_by_patient") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_by_patient" 'element))
(register-element! "cost.paid_patient_copay" (fhir-spec (string->symbol "cost.paid_patient_copay") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_patient_copay" 'element))
(register-element! "cost.paid_patient_coinsurance" (fhir-spec (string->symbol "cost.paid_patient_coinsurance") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_patient_coinsurance" 'element))
(register-element! "cost.paid_patient_deductible" (fhir-spec (string->symbol "cost.paid_patient_deductible") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_patient_deductible" 'element))
(register-element! "cost.paid_by_primary" (fhir-spec (string->symbol "cost.paid_by_primary") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_by_primary" 'element))
(register-element! "cost.paid_ingredient_cost" (fhir-spec (string->symbol "cost.paid_ingredient_cost") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_ingredient_cost" 'element))
(register-element! "cost.paid_dispensing_fee" (fhir-spec (string->symbol "cost.paid_dispensing_fee") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.paid_dispensing_fee" 'element))
(register-element! "cost.payer_plan_period_id" (fhir-spec (string->symbol "cost.payer_plan_period_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.payer_plan_period_id" 'element))
(register-element! "cost.amount_allowed" (fhir-spec (string->symbol "cost.amount_allowed") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.amount_allowed" 'element))
(register-element! "cost.revenue_code_concept_id" (fhir-spec (string->symbol "cost.revenue_code_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.revenue_code_concept_id" 'element))
(register-element! "cost.revenue_code_source_value" (fhir-spec (string->symbol "cost.revenue_code_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.revenue_code_source_value" 'element))
(register-element! "cost.drg_concept_id" (fhir-spec (string->symbol "cost.drg_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.drg_concept_id" 'element))
(register-element! "cost.drg_source_value" (fhir-spec (string->symbol "cost.drg_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#cost.drg_source_value" 'element))

