#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'drug_exposure (fhir-spec 'drug_exposure "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure" 'type)
  #:schema (type-schema 'drug_exposure #f 'Base "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure"
             (list
    (schema-field 'drug_exposure_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_id" #f)
    (schema-field 'person_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.person_id" #f)
    (schema-field 'drug_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_concept_id" #f)
    (schema-field 'drug_exposure_start_date 1 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_start_date" #f)
    (schema-field 'drug_exposure_start_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_start_datetime" #f)
    (schema-field 'drug_exposure_end_date 1 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_end_date" #f)
    (schema-field 'drug_exposure_end_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_end_datetime" #f)
    (schema-field 'verbatim_end_date 0 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.verbatim_end_date" #f)
    (schema-field 'drug_type_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_type_concept_id" #f)
    (schema-field 'stop_reason 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.stop_reason" #f)
    (schema-field 'refills 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.refills" #f)
    (schema-field 'quantity 0 1 (vector 'prim "decimal") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.quantity" #f)
    (schema-field 'days_supply 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.days_supply" #f)
    (schema-field 'sig 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.sig" #f)
    (schema-field 'route_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.route_concept_id" #f)
    (schema-field 'lot_number 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.lot_number" #f)
    (schema-field 'provider_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.provider_id" #f)
    (schema-field 'visit_occurrence_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.visit_occurrence_id" #f)
    (schema-field 'visit_detail_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.visit_detail_id" #f)
    (schema-field 'drug_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_source_value" #f)
    (schema-field 'drug_source_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_source_concept_id" #f)
    (schema-field 'route_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.route_source_value" #f)
    (schema-field 'dose_unit_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.dose_unit_source_value" #f)
             ) #f #f))
(register-element! "drug_exposure.drug_exposure_id" (fhir-spec (string->symbol "drug_exposure.drug_exposure_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_id" 'element))
(register-element! "drug_exposure.person_id" (fhir-spec (string->symbol "drug_exposure.person_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.person_id" 'element))
(register-element! "drug_exposure.drug_concept_id" (fhir-spec (string->symbol "drug_exposure.drug_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_concept_id" 'element))
(register-element! "drug_exposure.drug_exposure_start_date" (fhir-spec (string->symbol "drug_exposure.drug_exposure_start_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_start_date" 'element))
(register-element! "drug_exposure.drug_exposure_start_datetime" (fhir-spec (string->symbol "drug_exposure.drug_exposure_start_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_start_datetime" 'element))
(register-element! "drug_exposure.drug_exposure_end_date" (fhir-spec (string->symbol "drug_exposure.drug_exposure_end_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_end_date" 'element))
(register-element! "drug_exposure.drug_exposure_end_datetime" (fhir-spec (string->symbol "drug_exposure.drug_exposure_end_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_exposure_end_datetime" 'element))
(register-element! "drug_exposure.verbatim_end_date" (fhir-spec (string->symbol "drug_exposure.verbatim_end_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.verbatim_end_date" 'element))
(register-element! "drug_exposure.drug_type_concept_id" (fhir-spec (string->symbol "drug_exposure.drug_type_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_type_concept_id" 'element))
(register-element! "drug_exposure.stop_reason" (fhir-spec (string->symbol "drug_exposure.stop_reason") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.stop_reason" 'element))
(register-element! "drug_exposure.refills" (fhir-spec (string->symbol "drug_exposure.refills") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.refills" 'element))
(register-element! "drug_exposure.quantity" (fhir-spec (string->symbol "drug_exposure.quantity") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.quantity" 'element))
(register-element! "drug_exposure.days_supply" (fhir-spec (string->symbol "drug_exposure.days_supply") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.days_supply" 'element))
(register-element! "drug_exposure.sig" (fhir-spec (string->symbol "drug_exposure.sig") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.sig" 'element))
(register-element! "drug_exposure.route_concept_id" (fhir-spec (string->symbol "drug_exposure.route_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.route_concept_id" 'element))
(register-element! "drug_exposure.lot_number" (fhir-spec (string->symbol "drug_exposure.lot_number") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.lot_number" 'element))
(register-element! "drug_exposure.provider_id" (fhir-spec (string->symbol "drug_exposure.provider_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.provider_id" 'element))
(register-element! "drug_exposure.visit_occurrence_id" (fhir-spec (string->symbol "drug_exposure.visit_occurrence_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.visit_occurrence_id" 'element))
(register-element! "drug_exposure.visit_detail_id" (fhir-spec (string->symbol "drug_exposure.visit_detail_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.visit_detail_id" 'element))
(register-element! "drug_exposure.drug_source_value" (fhir-spec (string->symbol "drug_exposure.drug_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_source_value" 'element))
(register-element! "drug_exposure.drug_source_concept_id" (fhir-spec (string->symbol "drug_exposure.drug_source_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.drug_source_concept_id" 'element))
(register-element! "drug_exposure.route_source_value" (fhir-spec (string->symbol "drug_exposure.route_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.route_source_value" 'element))
(register-element! "drug_exposure.dose_unit_source_value" (fhir-spec (string->symbol "drug_exposure.dose_unit_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#drug_exposure.dose_unit_source_value" 'element))

