#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'person (fhir-spec 'person "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person" 'type)
  #:schema (type-schema 'person #f 'Base "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person"
             (list
    (schema-field 'person_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.person_id" #f)
    (schema-field 'gender_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.gender_concept_id" #f)
    (schema-field 'year_of_birth 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.year_of_birth" #f)
    (schema-field 'month_of_birth 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.month_of_birth" #f)
    (schema-field 'day_of_birth 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.day_of_birth" #f)
    (schema-field 'birth_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.birth_datetime" #f)
    (schema-field 'race_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.race_concept_id" #f)
    (schema-field 'ethnicity_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.ethnicity_concept_id" #f)
    (schema-field 'location_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.location_id" #f)
    (schema-field 'provider_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.provider_id" #f)
    (schema-field 'care_site_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.care_site_id" #f)
    (schema-field 'person_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.person_source_value" #f)
    (schema-field 'gender_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.gender_source_value" #f)
    (schema-field 'gender_source_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.gender_source_concept_id" #f)
    (schema-field 'race_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.race_source_value" #f)
    (schema-field 'race_source_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.race_source_concept_id" #f)
    (schema-field 'ethnicity_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.ethnicity_source_value" #f)
    (schema-field 'ethnicity_source_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.ethnicity_source_concept_id" #f)
             ) #f #f))
(register-element! "person.person_id" (fhir-spec (string->symbol "person.person_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.person_id" 'element))
(register-element! "person.gender_concept_id" (fhir-spec (string->symbol "person.gender_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.gender_concept_id" 'element))
(register-element! "person.year_of_birth" (fhir-spec (string->symbol "person.year_of_birth") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.year_of_birth" 'element))
(register-element! "person.month_of_birth" (fhir-spec (string->symbol "person.month_of_birth") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.month_of_birth" 'element))
(register-element! "person.day_of_birth" (fhir-spec (string->symbol "person.day_of_birth") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.day_of_birth" 'element))
(register-element! "person.birth_datetime" (fhir-spec (string->symbol "person.birth_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.birth_datetime" 'element))
(register-element! "person.race_concept_id" (fhir-spec (string->symbol "person.race_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.race_concept_id" 'element))
(register-element! "person.ethnicity_concept_id" (fhir-spec (string->symbol "person.ethnicity_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.ethnicity_concept_id" 'element))
(register-element! "person.location_id" (fhir-spec (string->symbol "person.location_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.location_id" 'element))
(register-element! "person.provider_id" (fhir-spec (string->symbol "person.provider_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.provider_id" 'element))
(register-element! "person.care_site_id" (fhir-spec (string->symbol "person.care_site_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.care_site_id" 'element))
(register-element! "person.person_source_value" (fhir-spec (string->symbol "person.person_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.person_source_value" 'element))
(register-element! "person.gender_source_value" (fhir-spec (string->symbol "person.gender_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.gender_source_value" 'element))
(register-element! "person.gender_source_concept_id" (fhir-spec (string->symbol "person.gender_source_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.gender_source_concept_id" 'element))
(register-element! "person.race_source_value" (fhir-spec (string->symbol "person.race_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.race_source_value" 'element))
(register-element! "person.race_source_concept_id" (fhir-spec (string->symbol "person.race_source_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.race_source_concept_id" 'element))
(register-element! "person.ethnicity_source_value" (fhir-spec (string->symbol "person.ethnicity_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.ethnicity_source_value" 'element))
(register-element! "person.ethnicity_source_concept_id" (fhir-spec (string->symbol "person.ethnicity_source_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#person.ethnicity_source_concept_id" 'element))

