#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'specimen (fhir-spec 'specimen "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen" 'type)
  #:schema (type-schema 'specimen #f 'Base "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen"
             (list
    (schema-field 'specimen_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_id" #f)
    (schema-field 'person_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.person_id" #f)
    (schema-field 'specimen_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_concept_id" #f)
    (schema-field 'specimen_type_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_type_concept_id" #f)
    (schema-field 'specimen_date 1 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_date" #f)
    (schema-field 'specimen_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_datetime" #f)
    (schema-field 'quantity 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.quantity" #f)
    (schema-field 'unit_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.unit_concept_id" #f)
    (schema-field 'anatomic_site_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.anatomic_site_concept_id" #f)
    (schema-field 'disease_status_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.disease_status_concept_id" #f)
    (schema-field 'specimen_source_id 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_source_id" #f)
    (schema-field 'specimen_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_source_value" #f)
    (schema-field 'unit_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.unit_source_value" #f)
    (schema-field 'anatomic_site_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.anatomic_site_source_value" #f)
    (schema-field 'disease_status_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.disease_status_source_value" #f)
             ) #f #f))
(register-element! "specimen.specimen_id" (fhir-spec (string->symbol "specimen.specimen_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_id" 'element))
(register-element! "specimen.person_id" (fhir-spec (string->symbol "specimen.person_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.person_id" 'element))
(register-element! "specimen.specimen_concept_id" (fhir-spec (string->symbol "specimen.specimen_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_concept_id" 'element))
(register-element! "specimen.specimen_type_concept_id" (fhir-spec (string->symbol "specimen.specimen_type_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_type_concept_id" 'element))
(register-element! "specimen.specimen_date" (fhir-spec (string->symbol "specimen.specimen_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_date" 'element))
(register-element! "specimen.specimen_datetime" (fhir-spec (string->symbol "specimen.specimen_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_datetime" 'element))
(register-element! "specimen.quantity" (fhir-spec (string->symbol "specimen.quantity") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.quantity" 'element))
(register-element! "specimen.unit_concept_id" (fhir-spec (string->symbol "specimen.unit_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.unit_concept_id" 'element))
(register-element! "specimen.anatomic_site_concept_id" (fhir-spec (string->symbol "specimen.anatomic_site_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.anatomic_site_concept_id" 'element))
(register-element! "specimen.disease_status_concept_id" (fhir-spec (string->symbol "specimen.disease_status_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.disease_status_concept_id" 'element))
(register-element! "specimen.specimen_source_id" (fhir-spec (string->symbol "specimen.specimen_source_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_source_id" 'element))
(register-element! "specimen.specimen_source_value" (fhir-spec (string->symbol "specimen.specimen_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.specimen_source_value" 'element))
(register-element! "specimen.unit_source_value" (fhir-spec (string->symbol "specimen.unit_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.unit_source_value" 'element))
(register-element! "specimen.anatomic_site_source_value" (fhir-spec (string->symbol "specimen.anatomic_site_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.anatomic_site_source_value" 'element))
(register-element! "specimen.disease_status_source_value" (fhir-spec (string->symbol "specimen.disease_status_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#specimen.disease_status_source_value" 'element))

