#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'visit_detail (fhir-spec 'visit_detail "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail" 'type)
  #:schema (type-schema 'visit_detail #f 'Base "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail"
             (list
    (schema-field 'visit_detail_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_id" #f)
    (schema-field 'person_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.person_id" #f)
    (schema-field 'visit_detail_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_concept_id" #f)
    (schema-field 'visit_detail_start_date 1 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_start_date" #f)
    (schema-field 'visit_detail_start_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_start_datetime" #f)
    (schema-field 'visit_detail_end_date 1 1 (vector 'prim "date") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_end_date" #f)
    (schema-field 'visit_detail_end_datetime 0 1 (vector 'prim "dateTime") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_end_datetime" #f)
    (schema-field 'visit_detail_type_concept_id 1 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_type_concept_id" #f)
    (schema-field 'provider_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.provider_id" #f)
    (schema-field 'care_site_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.care_site_id" #f)
    (schema-field 'visit_detail_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_source_value" #f)
    (schema-field 'visit_detail_source_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_source_concept_id" #f)
    (schema-field 'admitted_from_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.admitted_from_concept_id" #f)
    (schema-field 'admitted_from_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.admitted_from_source_value" #f)
    (schema-field 'discharged_to_source_value 0 1 (vector 'prim "string") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.discharged_to_source_value" #f)
    (schema-field 'discharged_to_concept_id 0 1 (vector 'prim "code") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.discharged_to_concept_id" #f)
    (schema-field 'preceding_visit_detail_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.preceding_visit_detail_id" #f)
    (schema-field 'parent_visit_detail_id 0 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.parent_visit_detail_id" #f)
    (schema-field 'visit_occurrence_id 1 1 (vector 'prim "integer") #f "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_occurrence_id" #f)
             ) #f #f))
(register-element! "visit_detail.visit_detail_id" (fhir-spec (string->symbol "visit_detail.visit_detail_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_id" 'element))
(register-element! "visit_detail.person_id" (fhir-spec (string->symbol "visit_detail.person_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.person_id" 'element))
(register-element! "visit_detail.visit_detail_concept_id" (fhir-spec (string->symbol "visit_detail.visit_detail_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_concept_id" 'element))
(register-element! "visit_detail.visit_detail_start_date" (fhir-spec (string->symbol "visit_detail.visit_detail_start_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_start_date" 'element))
(register-element! "visit_detail.visit_detail_start_datetime" (fhir-spec (string->symbol "visit_detail.visit_detail_start_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_start_datetime" 'element))
(register-element! "visit_detail.visit_detail_end_date" (fhir-spec (string->symbol "visit_detail.visit_detail_end_date") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_end_date" 'element))
(register-element! "visit_detail.visit_detail_end_datetime" (fhir-spec (string->symbol "visit_detail.visit_detail_end_datetime") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_end_datetime" 'element))
(register-element! "visit_detail.visit_detail_type_concept_id" (fhir-spec (string->symbol "visit_detail.visit_detail_type_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_type_concept_id" 'element))
(register-element! "visit_detail.provider_id" (fhir-spec (string->symbol "visit_detail.provider_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.provider_id" 'element))
(register-element! "visit_detail.care_site_id" (fhir-spec (string->symbol "visit_detail.care_site_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.care_site_id" 'element))
(register-element! "visit_detail.visit_detail_source_value" (fhir-spec (string->symbol "visit_detail.visit_detail_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_source_value" 'element))
(register-element! "visit_detail.visit_detail_source_concept_id" (fhir-spec (string->symbol "visit_detail.visit_detail_source_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_detail_source_concept_id" 'element))
(register-element! "visit_detail.admitted_from_concept_id" (fhir-spec (string->symbol "visit_detail.admitted_from_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.admitted_from_concept_id" 'element))
(register-element! "visit_detail.admitted_from_source_value" (fhir-spec (string->symbol "visit_detail.admitted_from_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.admitted_from_source_value" 'element))
(register-element! "visit_detail.discharged_to_source_value" (fhir-spec (string->symbol "visit_detail.discharged_to_source_value") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.discharged_to_source_value" 'element))
(register-element! "visit_detail.discharged_to_concept_id" (fhir-spec (string->symbol "visit_detail.discharged_to_concept_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.discharged_to_concept_id" 'element))
(register-element! "visit_detail.preceding_visit_detail_id" (fhir-spec (string->symbol "visit_detail.preceding_visit_detail_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.preceding_visit_detail_id" 'element))
(register-element! "visit_detail.parent_visit_detail_id" (fhir-spec (string->symbol "visit_detail.parent_visit_detail_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.parent_visit_detail_id" 'element))
(register-element! "visit_detail.visit_occurrence_id" (fhir-spec (string->symbol "visit_detail.visit_occurrence_id") "https://build.fhir.org/ig/HL7/fhir-omop-ig/datatypes.html#visit_detail.visit_occurrence_id" 'element))

