#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'AuditEvent (fhir-spec 'AuditEvent "https://hl7.org/fhir/R5/auditevent.html#AuditEvent" 'type)
  #:schema (type-schema 'AuditEvent #f 'DomainResource "https://hl7.org/fhir/R5/auditevent.html#AuditEvent"
             (list
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.category" #f)
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.code" #f)
    (schema-field 'action 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.action" #f)
    (schema-field 'severity 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.severity" #f)
    (schema-field 'recorded 1 1 (vector 'prim "instant") #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.recorded" #f)
    (schema-field 'outcome 0 1 (vector 'type 'AuditEventOutcome) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome" #f)
    (schema-field 'authorization 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.authorization" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.basedOn" #f)
    (schema-field 'patient 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.patient" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.encounter" #f)
    (schema-field 'agent 1 '* (vector 'type 'AuditEventAgent) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent" #f)
    (schema-field 'source 1 1 (vector 'type 'AuditEventSource) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source" #f)
    (schema-field 'entity 0 '* (vector 'type 'AuditEventEntity) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity" #f)
    (schema-field 'occurredPeriod 0 1 (vector 'type 'Period) 'occurred "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.occurred[x]" #f)
    (schema-field 'occurredDateTime 0 1 (vector 'prim "dateTime") 'occurred "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.occurred[x]" #f)
             ) #f #f))
(register-element! "AuditEvent.category" (fhir-spec (string->symbol "AuditEvent.category") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.category" 'element))
(register-element! "AuditEvent.code" (fhir-spec (string->symbol "AuditEvent.code") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.code" 'element))
(register-element! "AuditEvent.action" (fhir-spec (string->symbol "AuditEvent.action") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.action" 'element))
(register-element! "AuditEvent.severity" (fhir-spec (string->symbol "AuditEvent.severity") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.severity" 'element))
(register-element! "AuditEvent.recorded" (fhir-spec (string->symbol "AuditEvent.recorded") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.recorded" 'element))
(register-element! "AuditEvent.outcome" (fhir-spec (string->symbol "AuditEvent.outcome") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome" 'element))
(register-element! "AuditEvent.authorization" (fhir-spec (string->symbol "AuditEvent.authorization") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.authorization" 'element))
(register-element! "AuditEvent.basedOn" (fhir-spec (string->symbol "AuditEvent.basedOn") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.basedOn" 'element))
(register-element! "AuditEvent.patient" (fhir-spec (string->symbol "AuditEvent.patient") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.patient" 'element))
(register-element! "AuditEvent.encounter" (fhir-spec (string->symbol "AuditEvent.encounter") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.encounter" 'element))
(register-element! "AuditEvent.agent" (fhir-spec (string->symbol "AuditEvent.agent") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent" 'element))
(register-element! "AuditEvent.source" (fhir-spec (string->symbol "AuditEvent.source") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source" 'element))
(register-element! "AuditEvent.entity" (fhir-spec (string->symbol "AuditEvent.entity") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity" 'element))
(register-element! "AuditEvent.occurred[x]" (fhir-spec (string->symbol "AuditEvent.occurred[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.occurred[x]" 'element))
(register-element! "AuditEvent.occurred[x]" (fhir-spec (string->symbol "AuditEvent.occurred[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.occurred[x]" 'element))

(register-type! 'AuditEventOutcome (fhir-spec 'AuditEventOutcome "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome" 'type)
  #:schema (type-schema 'AuditEventOutcome #f 'BackboneElement "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome"
             (list
    (schema-field 'code 1 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome.code" #f)
    (schema-field 'detail 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome.detail" #f)
             ) #f #f))
(register-element! "AuditEvent.outcome.code" (fhir-spec (string->symbol "AuditEvent.outcome.code") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome.code" 'element))
(register-element! "AuditEvent.outcome.detail" (fhir-spec (string->symbol "AuditEvent.outcome.detail") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.outcome.detail" 'element))

(register-type! 'AuditEventAgent (fhir-spec 'AuditEventAgent "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent" 'type)
  #:schema (type-schema 'AuditEventAgent #f 'BackboneElement "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.type" #f)
    (schema-field 'role 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.role" #f)
    (schema-field 'who 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.who" #f)
    (schema-field 'requestor 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.requestor" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.location" #f)
    (schema-field 'policy 0 '* (vector 'prim "uri") #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.policy" #f)
    (schema-field 'authorization 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.authorization" #f)
    (schema-field 'networkReference 0 1 (vector 'type 'Reference) 'network "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.network[x]" #f)
    (schema-field 'networkUri 0 1 (vector 'prim "uri") 'network "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.network[x]" #f)
    (schema-field 'networkString 0 1 (vector 'prim "string") 'network "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.network[x]" #f)
             ) #f #f))
(register-element! "AuditEvent.agent.type" (fhir-spec (string->symbol "AuditEvent.agent.type") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.type" 'element))
(register-element! "AuditEvent.agent.role" (fhir-spec (string->symbol "AuditEvent.agent.role") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.role" 'element))
(register-element! "AuditEvent.agent.who" (fhir-spec (string->symbol "AuditEvent.agent.who") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.who" 'element))
(register-element! "AuditEvent.agent.requestor" (fhir-spec (string->symbol "AuditEvent.agent.requestor") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.requestor" 'element))
(register-element! "AuditEvent.agent.location" (fhir-spec (string->symbol "AuditEvent.agent.location") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.location" 'element))
(register-element! "AuditEvent.agent.policy" (fhir-spec (string->symbol "AuditEvent.agent.policy") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.policy" 'element))
(register-element! "AuditEvent.agent.authorization" (fhir-spec (string->symbol "AuditEvent.agent.authorization") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.authorization" 'element))
(register-element! "AuditEvent.agent.network[x]" (fhir-spec (string->symbol "AuditEvent.agent.network[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.network[x]" 'element))
(register-element! "AuditEvent.agent.network[x]" (fhir-spec (string->symbol "AuditEvent.agent.network[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.network[x]" 'element))
(register-element! "AuditEvent.agent.network[x]" (fhir-spec (string->symbol "AuditEvent.agent.network[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.agent.network[x]" 'element))

(register-type! 'AuditEventSource (fhir-spec 'AuditEventSource "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source" 'type)
  #:schema (type-schema 'AuditEventSource #f 'BackboneElement "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source"
             (list
    (schema-field 'site 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source.site" #f)
    (schema-field 'observer 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source.observer" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source.type" #f)
             ) #f #f))
(register-element! "AuditEvent.source.site" (fhir-spec (string->symbol "AuditEvent.source.site") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source.site" 'element))
(register-element! "AuditEvent.source.observer" (fhir-spec (string->symbol "AuditEvent.source.observer") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source.observer" 'element))
(register-element! "AuditEvent.source.type" (fhir-spec (string->symbol "AuditEvent.source.type") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.source.type" 'element))

(register-type! 'AuditEventEntity (fhir-spec 'AuditEventEntity "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity" 'type)
  #:schema (type-schema 'AuditEventEntity #f 'BackboneElement "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity"
             (list
    (schema-field 'what 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.what" #f)
    (schema-field 'role 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.role" #f)
    (schema-field 'securityLabel 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.securityLabel" #f)
    (schema-field 'query 0 1 (vector 'prim "base64Binary") #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.query" #f)
    (schema-field 'detail 0 '* (vector 'type 'AuditEventEntityDetail) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail" #f)
    (schema-field 'agent 0 '* (vector 'type 'AuditEventAgent) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.agent" #f)
             ) #f #f))
(register-element! "AuditEvent.entity.what" (fhir-spec (string->symbol "AuditEvent.entity.what") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.what" 'element))
(register-element! "AuditEvent.entity.role" (fhir-spec (string->symbol "AuditEvent.entity.role") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.role" 'element))
(register-element! "AuditEvent.entity.securityLabel" (fhir-spec (string->symbol "AuditEvent.entity.securityLabel") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.securityLabel" 'element))
(register-element! "AuditEvent.entity.query" (fhir-spec (string->symbol "AuditEvent.entity.query") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.query" 'element))
(register-element! "AuditEvent.entity.detail" (fhir-spec (string->symbol "AuditEvent.entity.detail") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail" 'element))
(register-element! "AuditEvent.entity.agent" (fhir-spec (string->symbol "AuditEvent.entity.agent") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.agent" 'element))

(register-type! 'AuditEventEntityDetail (fhir-spec 'AuditEventEntityDetail "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail" 'type)
  #:schema (type-schema 'AuditEventEntityDetail #f 'BackboneElement "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.type" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" #f)
             ) #f #f))
(register-element! "AuditEvent.entity.detail.type" (fhir-spec (string->symbol "AuditEvent.entity.detail.type") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.type" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))
(register-element! "AuditEvent.entity.detail.value[x]" (fhir-spec (string->symbol "AuditEvent.entity.detail.value[x]") "https://hl7.org/fhir/R5/auditevent.html#AuditEvent.entity.detail.value[x]" 'element))

