#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'CapabilityStatement (fhir-spec 'CapabilityStatement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement" 'type)
  #:schema (type-schema 'CapabilityStatement #f 'DomainResource "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.experimental" #f)
    (schema-field 'date 1 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.copyrightLabel" #f)
    (schema-field 'kind 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.kind" #f)
    (schema-field 'instantiates 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.instantiates" #f)
    (schema-field 'imports 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.imports" #f)
    (schema-field 'software 0 1 (vector 'type 'CapabilityStatementSoftware) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software" #f)
    (schema-field 'implementation 0 1 (vector 'type 'CapabilityStatementImplementation) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation" #f)
    (schema-field 'fhirVersion 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.fhirVersion" #f)
    (schema-field 'format 1 '* (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.format" #f)
    (schema-field 'patchFormat 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.patchFormat" #f)
    (schema-field 'acceptLanguage 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.acceptLanguage" #f)
    (schema-field 'implementationGuide 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementationGuide" #f)
    (schema-field 'rest 0 '* (vector 'type 'CapabilityStatementRest) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest" #f)
    (schema-field 'messaging 0 '* (vector 'type 'CapabilityStatementMessaging) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging" #f)
    (schema-field 'document 0 '* (vector 'type 'CapabilityStatementDocument) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "CapabilityStatement.url" (fhir-spec (string->symbol "CapabilityStatement.url") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.url" 'element))
(register-element! "CapabilityStatement.identifier" (fhir-spec (string->symbol "CapabilityStatement.identifier") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.identifier" 'element))
(register-element! "CapabilityStatement.version" (fhir-spec (string->symbol "CapabilityStatement.version") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.version" 'element))
(register-element! "CapabilityStatement.name" (fhir-spec (string->symbol "CapabilityStatement.name") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.name" 'element))
(register-element! "CapabilityStatement.title" (fhir-spec (string->symbol "CapabilityStatement.title") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.title" 'element))
(register-element! "CapabilityStatement.status" (fhir-spec (string->symbol "CapabilityStatement.status") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.status" 'element))
(register-element! "CapabilityStatement.experimental" (fhir-spec (string->symbol "CapabilityStatement.experimental") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.experimental" 'element))
(register-element! "CapabilityStatement.date" (fhir-spec (string->symbol "CapabilityStatement.date") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.date" 'element))
(register-element! "CapabilityStatement.publisher" (fhir-spec (string->symbol "CapabilityStatement.publisher") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.publisher" 'element))
(register-element! "CapabilityStatement.contact" (fhir-spec (string->symbol "CapabilityStatement.contact") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.contact" 'element))
(register-element! "CapabilityStatement.description" (fhir-spec (string->symbol "CapabilityStatement.description") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.description" 'element))
(register-element! "CapabilityStatement.useContext" (fhir-spec (string->symbol "CapabilityStatement.useContext") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.useContext" 'element))
(register-element! "CapabilityStatement.jurisdiction" (fhir-spec (string->symbol "CapabilityStatement.jurisdiction") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.jurisdiction" 'element))
(register-element! "CapabilityStatement.purpose" (fhir-spec (string->symbol "CapabilityStatement.purpose") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.purpose" 'element))
(register-element! "CapabilityStatement.copyright" (fhir-spec (string->symbol "CapabilityStatement.copyright") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.copyright" 'element))
(register-element! "CapabilityStatement.copyrightLabel" (fhir-spec (string->symbol "CapabilityStatement.copyrightLabel") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.copyrightLabel" 'element))
(register-element! "CapabilityStatement.kind" (fhir-spec (string->symbol "CapabilityStatement.kind") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.kind" 'element))
(register-element! "CapabilityStatement.instantiates" (fhir-spec (string->symbol "CapabilityStatement.instantiates") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.instantiates" 'element))
(register-element! "CapabilityStatement.imports" (fhir-spec (string->symbol "CapabilityStatement.imports") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.imports" 'element))
(register-element! "CapabilityStatement.software" (fhir-spec (string->symbol "CapabilityStatement.software") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software" 'element))
(register-element! "CapabilityStatement.implementation" (fhir-spec (string->symbol "CapabilityStatement.implementation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation" 'element))
(register-element! "CapabilityStatement.fhirVersion" (fhir-spec (string->symbol "CapabilityStatement.fhirVersion") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.fhirVersion" 'element))
(register-element! "CapabilityStatement.format" (fhir-spec (string->symbol "CapabilityStatement.format") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.format" 'element))
(register-element! "CapabilityStatement.patchFormat" (fhir-spec (string->symbol "CapabilityStatement.patchFormat") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.patchFormat" 'element))
(register-element! "CapabilityStatement.acceptLanguage" (fhir-spec (string->symbol "CapabilityStatement.acceptLanguage") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.acceptLanguage" 'element))
(register-element! "CapabilityStatement.implementationGuide" (fhir-spec (string->symbol "CapabilityStatement.implementationGuide") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementationGuide" 'element))
(register-element! "CapabilityStatement.rest" (fhir-spec (string->symbol "CapabilityStatement.rest") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest" 'element))
(register-element! "CapabilityStatement.messaging" (fhir-spec (string->symbol "CapabilityStatement.messaging") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging" 'element))
(register-element! "CapabilityStatement.document" (fhir-spec (string->symbol "CapabilityStatement.document") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document" 'element))
(register-element! "CapabilityStatement.versionAlgorithm[x]" (fhir-spec (string->symbol "CapabilityStatement.versionAlgorithm[x]") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.versionAlgorithm[x]" 'element))
(register-element! "CapabilityStatement.versionAlgorithm[x]" (fhir-spec (string->symbol "CapabilityStatement.versionAlgorithm[x]") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.versionAlgorithm[x]" 'element))

(register-type! 'CapabilityStatementSoftware (fhir-spec 'CapabilityStatementSoftware "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software" 'type)
  #:schema (type-schema 'CapabilityStatementSoftware #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software"
             (list
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software.name" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software.version" #f)
    (schema-field 'releaseDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software.releaseDate" #f)
             ) #f #f))
(register-element! "CapabilityStatement.software.name" (fhir-spec (string->symbol "CapabilityStatement.software.name") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software.name" 'element))
(register-element! "CapabilityStatement.software.version" (fhir-spec (string->symbol "CapabilityStatement.software.version") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software.version" 'element))
(register-element! "CapabilityStatement.software.releaseDate" (fhir-spec (string->symbol "CapabilityStatement.software.releaseDate") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.software.releaseDate" 'element))

(register-type! 'CapabilityStatementImplementation (fhir-spec 'CapabilityStatementImplementation "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation" 'type)
  #:schema (type-schema 'CapabilityStatementImplementation #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation"
             (list
    (schema-field 'description 1 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation.description" #f)
    (schema-field 'url 0 1 (vector 'prim "url") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation.url" #f)
    (schema-field 'custodian 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation.custodian" #f)
             ) #f #f))
(register-element! "CapabilityStatement.implementation.description" (fhir-spec (string->symbol "CapabilityStatement.implementation.description") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation.description" 'element))
(register-element! "CapabilityStatement.implementation.url" (fhir-spec (string->symbol "CapabilityStatement.implementation.url") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation.url" 'element))
(register-element! "CapabilityStatement.implementation.custodian" (fhir-spec (string->symbol "CapabilityStatement.implementation.custodian") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.implementation.custodian" 'element))

(register-type! 'CapabilityStatementRest (fhir-spec 'CapabilityStatementRest "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest" 'type)
  #:schema (type-schema 'CapabilityStatementRest #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest"
             (list
    (schema-field 'mode 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.mode" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.documentation" #f)
    (schema-field 'security 0 1 (vector 'type 'CapabilityStatementRestSecurity) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security" #f)
    (schema-field 'resource 0 '* (vector 'type 'CapabilityStatementRestResource) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource" #f)
    (schema-field 'interaction 0 '* (vector 'type 'CapabilityStatementRestInteraction) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction" #f)
    (schema-field 'searchParam 0 '* (vector 'type 'CapabilityStatementRestResourceSearchParam) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.searchParam" #f)
    (schema-field 'operation 0 '* (vector 'type 'CapabilityStatementRestResourceOperation) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.operation" #f)
    (schema-field 'compartment 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.compartment" #f)
             ) #f #f))
(register-element! "CapabilityStatement.rest.mode" (fhir-spec (string->symbol "CapabilityStatement.rest.mode") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.mode" 'element))
(register-element! "CapabilityStatement.rest.documentation" (fhir-spec (string->symbol "CapabilityStatement.rest.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.documentation" 'element))
(register-element! "CapabilityStatement.rest.security" (fhir-spec (string->symbol "CapabilityStatement.rest.security") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security" 'element))
(register-element! "CapabilityStatement.rest.resource" (fhir-spec (string->symbol "CapabilityStatement.rest.resource") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource" 'element))
(register-element! "CapabilityStatement.rest.interaction" (fhir-spec (string->symbol "CapabilityStatement.rest.interaction") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction" 'element))
(register-element! "CapabilityStatement.rest.searchParam" (fhir-spec (string->symbol "CapabilityStatement.rest.searchParam") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.searchParam" 'element))
(register-element! "CapabilityStatement.rest.operation" (fhir-spec (string->symbol "CapabilityStatement.rest.operation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.operation" 'element))
(register-element! "CapabilityStatement.rest.compartment" (fhir-spec (string->symbol "CapabilityStatement.rest.compartment") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.compartment" 'element))

(register-type! 'CapabilityStatementRestSecurity (fhir-spec 'CapabilityStatementRestSecurity "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security" 'type)
  #:schema (type-schema 'CapabilityStatementRestSecurity #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security"
             (list
    (schema-field 'cors 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security.cors" #f)
    (schema-field 'service 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security.service" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security.description" #f)
             ) #f #f))
(register-element! "CapabilityStatement.rest.security.cors" (fhir-spec (string->symbol "CapabilityStatement.rest.security.cors") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security.cors" 'element))
(register-element! "CapabilityStatement.rest.security.service" (fhir-spec (string->symbol "CapabilityStatement.rest.security.service") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security.service" 'element))
(register-element! "CapabilityStatement.rest.security.description" (fhir-spec (string->symbol "CapabilityStatement.rest.security.description") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.security.description" 'element))

(register-type! 'CapabilityStatementRestResource (fhir-spec 'CapabilityStatementRestResource "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource" 'type)
  #:schema (type-schema 'CapabilityStatementRestResource #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource"
             (list
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.type" #f)
    (schema-field 'profile 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.profile" #f)
    (schema-field 'supportedProfile 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.supportedProfile" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.documentation" #f)
    (schema-field 'interaction 0 '* (vector 'type 'CapabilityStatementRestResourceInteraction) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction" #f)
    (schema-field 'versioning 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.versioning" #f)
    (schema-field 'readHistory 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.readHistory" #f)
    (schema-field 'updateCreate 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.updateCreate" #f)
    (schema-field 'conditionalCreate 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalCreate" #f)
    (schema-field 'conditionalRead 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalRead" #f)
    (schema-field 'conditionalUpdate 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalUpdate" #f)
    (schema-field 'conditionalPatch 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalPatch" #f)
    (schema-field 'conditionalDelete 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalDelete" #f)
    (schema-field 'referencePolicy 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.referencePolicy" #f)
    (schema-field 'searchInclude 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchInclude" #f)
    (schema-field 'searchRevInclude 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchRevInclude" #f)
    (schema-field 'searchParam 0 '* (vector 'type 'CapabilityStatementRestResourceSearchParam) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam" #f)
    (schema-field 'operation 0 '* (vector 'type 'CapabilityStatementRestResourceOperation) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation" #f)
             ) #f #f))
(register-element! "CapabilityStatement.rest.resource.type" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.type") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.type" 'element))
(register-element! "CapabilityStatement.rest.resource.profile" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.profile") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.profile" 'element))
(register-element! "CapabilityStatement.rest.resource.supportedProfile" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.supportedProfile") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.supportedProfile" 'element))
(register-element! "CapabilityStatement.rest.resource.documentation" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.documentation" 'element))
(register-element! "CapabilityStatement.rest.resource.interaction" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.interaction") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction" 'element))
(register-element! "CapabilityStatement.rest.resource.versioning" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.versioning") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.versioning" 'element))
(register-element! "CapabilityStatement.rest.resource.readHistory" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.readHistory") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.readHistory" 'element))
(register-element! "CapabilityStatement.rest.resource.updateCreate" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.updateCreate") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.updateCreate" 'element))
(register-element! "CapabilityStatement.rest.resource.conditionalCreate" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.conditionalCreate") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalCreate" 'element))
(register-element! "CapabilityStatement.rest.resource.conditionalRead" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.conditionalRead") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalRead" 'element))
(register-element! "CapabilityStatement.rest.resource.conditionalUpdate" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.conditionalUpdate") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalUpdate" 'element))
(register-element! "CapabilityStatement.rest.resource.conditionalPatch" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.conditionalPatch") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalPatch" 'element))
(register-element! "CapabilityStatement.rest.resource.conditionalDelete" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.conditionalDelete") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.conditionalDelete" 'element))
(register-element! "CapabilityStatement.rest.resource.referencePolicy" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.referencePolicy") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.referencePolicy" 'element))
(register-element! "CapabilityStatement.rest.resource.searchInclude" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.searchInclude") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchInclude" 'element))
(register-element! "CapabilityStatement.rest.resource.searchRevInclude" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.searchRevInclude") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchRevInclude" 'element))
(register-element! "CapabilityStatement.rest.resource.searchParam" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.searchParam") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam" 'element))
(register-element! "CapabilityStatement.rest.resource.operation" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.operation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation" 'element))

(register-type! 'CapabilityStatementRestResourceInteraction (fhir-spec 'CapabilityStatementRestResourceInteraction "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction" 'type)
  #:schema (type-schema 'CapabilityStatementRestResourceInteraction #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction.code" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction.documentation" #f)
             ) #f #f))
(register-element! "CapabilityStatement.rest.resource.interaction.code" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.interaction.code") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction.code" 'element))
(register-element! "CapabilityStatement.rest.resource.interaction.documentation" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.interaction.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.interaction.documentation" 'element))

(register-type! 'CapabilityStatementRestResourceSearchParam (fhir-spec 'CapabilityStatementRestResourceSearchParam "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam" 'type)
  #:schema (type-schema 'CapabilityStatementRestResourceSearchParam #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam"
             (list
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.name" #f)
    (schema-field 'definition 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.definition" #f)
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.type" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.documentation" #f)
             ) #f #f))
(register-element! "CapabilityStatement.rest.resource.searchParam.name" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.searchParam.name") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.name" 'element))
(register-element! "CapabilityStatement.rest.resource.searchParam.definition" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.searchParam.definition") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.definition" 'element))
(register-element! "CapabilityStatement.rest.resource.searchParam.type" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.searchParam.type") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.type" 'element))
(register-element! "CapabilityStatement.rest.resource.searchParam.documentation" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.searchParam.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.searchParam.documentation" 'element))

(register-type! 'CapabilityStatementRestResourceOperation (fhir-spec 'CapabilityStatementRestResourceOperation "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation" 'type)
  #:schema (type-schema 'CapabilityStatementRestResourceOperation #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation"
             (list
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation.name" #f)
    (schema-field 'definition 1 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation.definition" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation.documentation" #f)
             ) #f #f))
(register-element! "CapabilityStatement.rest.resource.operation.name" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.operation.name") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation.name" 'element))
(register-element! "CapabilityStatement.rest.resource.operation.definition" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.operation.definition") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation.definition" 'element))
(register-element! "CapabilityStatement.rest.resource.operation.documentation" (fhir-spec (string->symbol "CapabilityStatement.rest.resource.operation.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.resource.operation.documentation" 'element))

(register-type! 'CapabilityStatementRestInteraction (fhir-spec 'CapabilityStatementRestInteraction "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction" 'type)
  #:schema (type-schema 'CapabilityStatementRestInteraction #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction.code" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction.documentation" #f)
             ) #f #f))
(register-element! "CapabilityStatement.rest.interaction.code" (fhir-spec (string->symbol "CapabilityStatement.rest.interaction.code") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction.code" 'element))
(register-element! "CapabilityStatement.rest.interaction.documentation" (fhir-spec (string->symbol "CapabilityStatement.rest.interaction.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.rest.interaction.documentation" 'element))

(register-type! 'CapabilityStatementMessaging (fhir-spec 'CapabilityStatementMessaging "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging" 'type)
  #:schema (type-schema 'CapabilityStatementMessaging #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging"
             (list
    (schema-field 'endpoint 0 '* (vector 'type 'CapabilityStatementMessagingEndpoint) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint" #f)
    (schema-field 'reliableCache 0 1 (vector 'prim "unsignedInt") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.reliableCache" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.documentation" #f)
    (schema-field 'supportedMessage 0 '* (vector 'type 'CapabilityStatementMessagingSupportedMessage) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage" #f)
             ) #f #f))
(register-element! "CapabilityStatement.messaging.endpoint" (fhir-spec (string->symbol "CapabilityStatement.messaging.endpoint") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint" 'element))
(register-element! "CapabilityStatement.messaging.reliableCache" (fhir-spec (string->symbol "CapabilityStatement.messaging.reliableCache") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.reliableCache" 'element))
(register-element! "CapabilityStatement.messaging.documentation" (fhir-spec (string->symbol "CapabilityStatement.messaging.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.documentation" 'element))
(register-element! "CapabilityStatement.messaging.supportedMessage" (fhir-spec (string->symbol "CapabilityStatement.messaging.supportedMessage") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage" 'element))

(register-type! 'CapabilityStatementMessagingEndpoint (fhir-spec 'CapabilityStatementMessagingEndpoint "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint" 'type)
  #:schema (type-schema 'CapabilityStatementMessagingEndpoint #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint"
             (list
    (schema-field 'protocol 1 1 (vector 'type 'Coding) #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint.protocol" #f)
    (schema-field 'address 1 1 (vector 'prim "url") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint.address" #f)
             ) #f #f))
(register-element! "CapabilityStatement.messaging.endpoint.protocol" (fhir-spec (string->symbol "CapabilityStatement.messaging.endpoint.protocol") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint.protocol" 'element))
(register-element! "CapabilityStatement.messaging.endpoint.address" (fhir-spec (string->symbol "CapabilityStatement.messaging.endpoint.address") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.endpoint.address" 'element))

(register-type! 'CapabilityStatementMessagingSupportedMessage (fhir-spec 'CapabilityStatementMessagingSupportedMessage "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage" 'type)
  #:schema (type-schema 'CapabilityStatementMessagingSupportedMessage #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage"
             (list
    (schema-field 'mode 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage.mode" #f)
    (schema-field 'definition 1 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage.definition" #f)
             ) #f #f))
(register-element! "CapabilityStatement.messaging.supportedMessage.mode" (fhir-spec (string->symbol "CapabilityStatement.messaging.supportedMessage.mode") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage.mode" 'element))
(register-element! "CapabilityStatement.messaging.supportedMessage.definition" (fhir-spec (string->symbol "CapabilityStatement.messaging.supportedMessage.definition") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.messaging.supportedMessage.definition" 'element))

(register-type! 'CapabilityStatementDocument (fhir-spec 'CapabilityStatementDocument "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document" 'type)
  #:schema (type-schema 'CapabilityStatementDocument #f 'BackboneElement "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document"
             (list
    (schema-field 'mode 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document.mode" #f)
    (schema-field 'documentation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document.documentation" #f)
    (schema-field 'profile 1 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document.profile" #f)
             ) #f #f))
(register-element! "CapabilityStatement.document.mode" (fhir-spec (string->symbol "CapabilityStatement.document.mode") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document.mode" 'element))
(register-element! "CapabilityStatement.document.documentation" (fhir-spec (string->symbol "CapabilityStatement.document.documentation") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document.documentation" 'element))
(register-element! "CapabilityStatement.document.profile" (fhir-spec (string->symbol "CapabilityStatement.document.profile") "https://hl7.org/fhir/R5/capabilitystatement.html#CapabilityStatement.document.profile" 'element))

