#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Citation (fhir-spec 'Citation "https://hl7.org/fhir/R5/citation.html#Citation" 'type)
  #:schema (type-schema 'Citation #f 'DomainResource "https://hl7.org/fhir/R5/citation.html#Citation"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/citation.html#Citation.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/citation.html#Citation.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/citation.html#Citation.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/citation.html#Citation.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/citation.html#Citation.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/citation.html#Citation.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R5/citation.html#Citation.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/citation.html#Citation.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/citation.html#Citation.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/citation.html#Citation.effectivePeriod" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/citation.html#Citation.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/citation.html#Citation.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/citation.html#Citation.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/citation.html#Citation.endorser" #f)
    (schema-field 'summary 0 '* (vector 'type 'CitationSummary) #f "https://hl7.org/fhir/R5/citation.html#Citation.summary" #f)
    (schema-field 'classification 0 '* (vector 'type 'CitationClassification) #f "https://hl7.org/fhir/R5/citation.html#Citation.classification" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/citation.html#Citation.note" #f)
    (schema-field 'currentState 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.currentState" #f)
    (schema-field 'statusDate 0 '* (vector 'type 'CitationStatusDate) #f "https://hl7.org/fhir/R5/citation.html#Citation.statusDate" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://hl7.org/fhir/R5/citation.html#Citation.relatedArtifact" #f)
    (schema-field 'citedArtifact 0 1 (vector 'type 'CitationCitedArtifact) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://hl7.org/fhir/R5/citation.html#Citation.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://hl7.org/fhir/R5/citation.html#Citation.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "Citation.url" (fhir-spec (string->symbol "Citation.url") "https://hl7.org/fhir/R5/citation.html#Citation.url" 'element))
(register-element! "Citation.identifier" (fhir-spec (string->symbol "Citation.identifier") "https://hl7.org/fhir/R5/citation.html#Citation.identifier" 'element))
(register-element! "Citation.version" (fhir-spec (string->symbol "Citation.version") "https://hl7.org/fhir/R5/citation.html#Citation.version" 'element))
(register-element! "Citation.name" (fhir-spec (string->symbol "Citation.name") "https://hl7.org/fhir/R5/citation.html#Citation.name" 'element))
(register-element! "Citation.title" (fhir-spec (string->symbol "Citation.title") "https://hl7.org/fhir/R5/citation.html#Citation.title" 'element))
(register-element! "Citation.status" (fhir-spec (string->symbol "Citation.status") "https://hl7.org/fhir/R5/citation.html#Citation.status" 'element))
(register-element! "Citation.experimental" (fhir-spec (string->symbol "Citation.experimental") "https://hl7.org/fhir/R5/citation.html#Citation.experimental" 'element))
(register-element! "Citation.date" (fhir-spec (string->symbol "Citation.date") "https://hl7.org/fhir/R5/citation.html#Citation.date" 'element))
(register-element! "Citation.publisher" (fhir-spec (string->symbol "Citation.publisher") "https://hl7.org/fhir/R5/citation.html#Citation.publisher" 'element))
(register-element! "Citation.contact" (fhir-spec (string->symbol "Citation.contact") "https://hl7.org/fhir/R5/citation.html#Citation.contact" 'element))
(register-element! "Citation.description" (fhir-spec (string->symbol "Citation.description") "https://hl7.org/fhir/R5/citation.html#Citation.description" 'element))
(register-element! "Citation.useContext" (fhir-spec (string->symbol "Citation.useContext") "https://hl7.org/fhir/R5/citation.html#Citation.useContext" 'element))
(register-element! "Citation.jurisdiction" (fhir-spec (string->symbol "Citation.jurisdiction") "https://hl7.org/fhir/R5/citation.html#Citation.jurisdiction" 'element))
(register-element! "Citation.purpose" (fhir-spec (string->symbol "Citation.purpose") "https://hl7.org/fhir/R5/citation.html#Citation.purpose" 'element))
(register-element! "Citation.copyright" (fhir-spec (string->symbol "Citation.copyright") "https://hl7.org/fhir/R5/citation.html#Citation.copyright" 'element))
(register-element! "Citation.copyrightLabel" (fhir-spec (string->symbol "Citation.copyrightLabel") "https://hl7.org/fhir/R5/citation.html#Citation.copyrightLabel" 'element))
(register-element! "Citation.approvalDate" (fhir-spec (string->symbol "Citation.approvalDate") "https://hl7.org/fhir/R5/citation.html#Citation.approvalDate" 'element))
(register-element! "Citation.lastReviewDate" (fhir-spec (string->symbol "Citation.lastReviewDate") "https://hl7.org/fhir/R5/citation.html#Citation.lastReviewDate" 'element))
(register-element! "Citation.effectivePeriod" (fhir-spec (string->symbol "Citation.effectivePeriod") "https://hl7.org/fhir/R5/citation.html#Citation.effectivePeriod" 'element))
(register-element! "Citation.author" (fhir-spec (string->symbol "Citation.author") "https://hl7.org/fhir/R5/citation.html#Citation.author" 'element))
(register-element! "Citation.editor" (fhir-spec (string->symbol "Citation.editor") "https://hl7.org/fhir/R5/citation.html#Citation.editor" 'element))
(register-element! "Citation.reviewer" (fhir-spec (string->symbol "Citation.reviewer") "https://hl7.org/fhir/R5/citation.html#Citation.reviewer" 'element))
(register-element! "Citation.endorser" (fhir-spec (string->symbol "Citation.endorser") "https://hl7.org/fhir/R5/citation.html#Citation.endorser" 'element))
(register-element! "Citation.summary" (fhir-spec (string->symbol "Citation.summary") "https://hl7.org/fhir/R5/citation.html#Citation.summary" 'element))
(register-element! "Citation.classification" (fhir-spec (string->symbol "Citation.classification") "https://hl7.org/fhir/R5/citation.html#Citation.classification" 'element))
(register-element! "Citation.note" (fhir-spec (string->symbol "Citation.note") "https://hl7.org/fhir/R5/citation.html#Citation.note" 'element))
(register-element! "Citation.currentState" (fhir-spec (string->symbol "Citation.currentState") "https://hl7.org/fhir/R5/citation.html#Citation.currentState" 'element))
(register-element! "Citation.statusDate" (fhir-spec (string->symbol "Citation.statusDate") "https://hl7.org/fhir/R5/citation.html#Citation.statusDate" 'element))
(register-element! "Citation.relatedArtifact" (fhir-spec (string->symbol "Citation.relatedArtifact") "https://hl7.org/fhir/R5/citation.html#Citation.relatedArtifact" 'element))
(register-element! "Citation.citedArtifact" (fhir-spec (string->symbol "Citation.citedArtifact") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact" 'element))
(register-element! "Citation.versionAlgorithm[x]" (fhir-spec (string->symbol "Citation.versionAlgorithm[x]") "https://hl7.org/fhir/R5/citation.html#Citation.versionAlgorithm[x]" 'element))
(register-element! "Citation.versionAlgorithm[x]" (fhir-spec (string->symbol "Citation.versionAlgorithm[x]") "https://hl7.org/fhir/R5/citation.html#Citation.versionAlgorithm[x]" 'element))

(register-type! 'CitationSummary (fhir-spec 'CitationSummary "https://hl7.org/fhir/R5/citation.html#Citation.summary" 'type)
  #:schema (type-schema 'CitationSummary #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.summary"
             (list
    (schema-field 'style 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.summary.style" #f)
    (schema-field 'text 1 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.summary.text" #f)
             ) #f #f))
(register-element! "Citation.summary.style" (fhir-spec (string->symbol "Citation.summary.style") "https://hl7.org/fhir/R5/citation.html#Citation.summary.style" 'element))
(register-element! "Citation.summary.text" (fhir-spec (string->symbol "Citation.summary.text") "https://hl7.org/fhir/R5/citation.html#Citation.summary.text" 'element))

(register-type! 'CitationClassification (fhir-spec 'CitationClassification "https://hl7.org/fhir/R5/citation.html#Citation.classification" 'type)
  #:schema (type-schema 'CitationClassification #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.classification"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.classification.type" #f)
    (schema-field 'classifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.classification.classifier" #f)
             ) #f #f))
(register-element! "Citation.classification.type" (fhir-spec (string->symbol "Citation.classification.type") "https://hl7.org/fhir/R5/citation.html#Citation.classification.type" 'element))
(register-element! "Citation.classification.classifier" (fhir-spec (string->symbol "Citation.classification.classifier") "https://hl7.org/fhir/R5/citation.html#Citation.classification.classifier" 'element))

(register-type! 'CitationStatusDate (fhir-spec 'CitationStatusDate "https://hl7.org/fhir/R5/citation.html#Citation.statusDate" 'type)
  #:schema (type-schema 'CitationStatusDate #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.statusDate"
             (list
    (schema-field 'activity 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.statusDate.activity" #f)
    (schema-field 'actual 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/citation.html#Citation.statusDate.actual" #f)
    (schema-field 'period 1 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/citation.html#Citation.statusDate.period" #f)
             ) #f #f))
(register-element! "Citation.statusDate.activity" (fhir-spec (string->symbol "Citation.statusDate.activity") "https://hl7.org/fhir/R5/citation.html#Citation.statusDate.activity" 'element))
(register-element! "Citation.statusDate.actual" (fhir-spec (string->symbol "Citation.statusDate.actual") "https://hl7.org/fhir/R5/citation.html#Citation.statusDate.actual" 'element))
(register-element! "Citation.statusDate.period" (fhir-spec (string->symbol "Citation.statusDate.period") "https://hl7.org/fhir/R5/citation.html#Citation.statusDate.period" 'element))

(register-type! 'CitationCitedArtifact (fhir-spec 'CitationCitedArtifact "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact" 'type)
  #:schema (type-schema 'CitationCitedArtifact #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.identifier" #f)
    (schema-field 'relatedIdentifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatedIdentifier" #f)
    (schema-field 'dateAccessed 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.dateAccessed" #f)
    (schema-field 'version 0 1 (vector 'type 'CitationCitedArtifactVersion) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version" #f)
    (schema-field 'currentState 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.currentState" #f)
    (schema-field 'statusDate 0 '* (vector 'type 'CitationCitedArtifactStatusDate) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate" #f)
    (schema-field 'title 0 '* (vector 'type 'CitationCitedArtifactTitle) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title" #f)
    (schema-field 'abstract 0 '* (vector 'type 'CitationCitedArtifactAbstract) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract" #f)
    (schema-field 'part 0 1 (vector 'type 'CitationCitedArtifactPart) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part" #f)
    (schema-field 'relatesTo 0 '* (vector 'type 'CitationCitedArtifactRelatesTo) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo" #f)
    (schema-field 'publicationForm 0 '* (vector 'type 'CitationCitedArtifactPublicationForm) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm" #f)
    (schema-field 'webLocation 0 '* (vector 'type 'CitationCitedArtifactWebLocation) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation" #f)
    (schema-field 'classification 0 '* (vector 'type 'CitationCitedArtifactClassification) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification" #f)
    (schema-field 'contributorship 0 1 (vector 'type 'CitationCitedArtifactContributorship) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.note" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.identifier" (fhir-spec (string->symbol "Citation.citedArtifact.identifier") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.identifier" 'element))
(register-element! "Citation.citedArtifact.relatedIdentifier" (fhir-spec (string->symbol "Citation.citedArtifact.relatedIdentifier") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatedIdentifier" 'element))
(register-element! "Citation.citedArtifact.dateAccessed" (fhir-spec (string->symbol "Citation.citedArtifact.dateAccessed") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.dateAccessed" 'element))
(register-element! "Citation.citedArtifact.version" (fhir-spec (string->symbol "Citation.citedArtifact.version") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version" 'element))
(register-element! "Citation.citedArtifact.currentState" (fhir-spec (string->symbol "Citation.citedArtifact.currentState") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.currentState" 'element))
(register-element! "Citation.citedArtifact.statusDate" (fhir-spec (string->symbol "Citation.citedArtifact.statusDate") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate" 'element))
(register-element! "Citation.citedArtifact.title" (fhir-spec (string->symbol "Citation.citedArtifact.title") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title" 'element))
(register-element! "Citation.citedArtifact.abstract" (fhir-spec (string->symbol "Citation.citedArtifact.abstract") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract" 'element))
(register-element! "Citation.citedArtifact.part" (fhir-spec (string->symbol "Citation.citedArtifact.part") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part" 'element))
(register-element! "Citation.citedArtifact.relatesTo" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo" 'element))
(register-element! "Citation.citedArtifact.publicationForm" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm" 'element))
(register-element! "Citation.citedArtifact.webLocation" (fhir-spec (string->symbol "Citation.citedArtifact.webLocation") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation" 'element))
(register-element! "Citation.citedArtifact.classification" (fhir-spec (string->symbol "Citation.citedArtifact.classification") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification" 'element))
(register-element! "Citation.citedArtifact.contributorship" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship" 'element))
(register-element! "Citation.citedArtifact.note" (fhir-spec (string->symbol "Citation.citedArtifact.note") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.note" 'element))

(register-type! 'CitationCitedArtifactVersion (fhir-spec 'CitationCitedArtifactVersion "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version" 'type)
  #:schema (type-schema 'CitationCitedArtifactVersion #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version"
             (list
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version.value" #f)
    (schema-field 'baseCitation 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version.baseCitation" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.version.value" (fhir-spec (string->symbol "Citation.citedArtifact.version.value") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version.value" 'element))
(register-element! "Citation.citedArtifact.version.baseCitation" (fhir-spec (string->symbol "Citation.citedArtifact.version.baseCitation") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.version.baseCitation" 'element))

(register-type! 'CitationCitedArtifactStatusDate (fhir-spec 'CitationCitedArtifactStatusDate "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate" 'type)
  #:schema (type-schema 'CitationCitedArtifactStatusDate #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate"
             (list
    (schema-field 'activity 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate.activity" #f)
    (schema-field 'actual 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate.actual" #f)
    (schema-field 'period 1 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate.period" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.statusDate.activity" (fhir-spec (string->symbol "Citation.citedArtifact.statusDate.activity") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate.activity" 'element))
(register-element! "Citation.citedArtifact.statusDate.actual" (fhir-spec (string->symbol "Citation.citedArtifact.statusDate.actual") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate.actual" 'element))
(register-element! "Citation.citedArtifact.statusDate.period" (fhir-spec (string->symbol "Citation.citedArtifact.statusDate.period") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.statusDate.period" 'element))

(register-type! 'CitationCitedArtifactTitle (fhir-spec 'CitationCitedArtifactTitle "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title" 'type)
  #:schema (type-schema 'CitationCitedArtifactTitle #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title"
             (list
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title.type" #f)
    (schema-field 'language 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title.language" #f)
    (schema-field 'text 1 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title.text" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.title.type" (fhir-spec (string->symbol "Citation.citedArtifact.title.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title.type" 'element))
(register-element! "Citation.citedArtifact.title.language" (fhir-spec (string->symbol "Citation.citedArtifact.title.language") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title.language" 'element))
(register-element! "Citation.citedArtifact.title.text" (fhir-spec (string->symbol "Citation.citedArtifact.title.text") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.title.text" 'element))

(register-type! 'CitationCitedArtifactAbstract (fhir-spec 'CitationCitedArtifactAbstract "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract" 'type)
  #:schema (type-schema 'CitationCitedArtifactAbstract #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.type" #f)
    (schema-field 'language 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.language" #f)
    (schema-field 'text 1 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.text" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.copyright" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.abstract.type" (fhir-spec (string->symbol "Citation.citedArtifact.abstract.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.type" 'element))
(register-element! "Citation.citedArtifact.abstract.language" (fhir-spec (string->symbol "Citation.citedArtifact.abstract.language") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.language" 'element))
(register-element! "Citation.citedArtifact.abstract.text" (fhir-spec (string->symbol "Citation.citedArtifact.abstract.text") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.text" 'element))
(register-element! "Citation.citedArtifact.abstract.copyright" (fhir-spec (string->symbol "Citation.citedArtifact.abstract.copyright") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.abstract.copyright" 'element))

(register-type! 'CitationCitedArtifactPart (fhir-spec 'CitationCitedArtifactPart "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part" 'type)
  #:schema (type-schema 'CitationCitedArtifactPart #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part.type" #f)
    (schema-field 'value 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part.value" #f)
    (schema-field 'baseCitation 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part.baseCitation" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.part.type" (fhir-spec (string->symbol "Citation.citedArtifact.part.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part.type" 'element))
(register-element! "Citation.citedArtifact.part.value" (fhir-spec (string->symbol "Citation.citedArtifact.part.value") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part.value" 'element))
(register-element! "Citation.citedArtifact.part.baseCitation" (fhir-spec (string->symbol "Citation.citedArtifact.part.baseCitation") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.part.baseCitation" 'element))

(register-type! 'CitationCitedArtifactRelatesTo (fhir-spec 'CitationCitedArtifactRelatesTo "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo" 'type)
  #:schema (type-schema 'CitationCitedArtifactRelatesTo #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo"
             (list
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.type" #f)
    (schema-field 'classifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.classifier" #f)
    (schema-field 'label 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.label" #f)
    (schema-field 'display 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.display" #f)
    (schema-field 'citation 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.citation" #f)
    (schema-field 'document 0 1 (vector 'type 'Attachment) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.document" #f)
    (schema-field 'resource 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.resource" #f)
    (schema-field 'resourceReference 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.resourceReference" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.relatesTo.type" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.type" 'element))
(register-element! "Citation.citedArtifact.relatesTo.classifier" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.classifier") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.classifier" 'element))
(register-element! "Citation.citedArtifact.relatesTo.label" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.label") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.label" 'element))
(register-element! "Citation.citedArtifact.relatesTo.display" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.display") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.display" 'element))
(register-element! "Citation.citedArtifact.relatesTo.citation" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.citation") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.citation" 'element))
(register-element! "Citation.citedArtifact.relatesTo.document" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.document") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.document" 'element))
(register-element! "Citation.citedArtifact.relatesTo.resource" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.resource") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.resource" 'element))
(register-element! "Citation.citedArtifact.relatesTo.resourceReference" (fhir-spec (string->symbol "Citation.citedArtifact.relatesTo.resourceReference") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.relatesTo.resourceReference" 'element))

(register-type! 'CitationCitedArtifactPublicationForm (fhir-spec 'CitationCitedArtifactPublicationForm "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm" 'type)
  #:schema (type-schema 'CitationCitedArtifactPublicationForm #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm"
             (list
    (schema-field 'publishedIn 0 1 (vector 'type 'CitationCitedArtifactPublicationFormPublishedIn) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn" #f)
    (schema-field 'citedMedium 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.citedMedium" #f)
    (schema-field 'volume 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.volume" #f)
    (schema-field 'issue 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.issue" #f)
    (schema-field 'articleDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.articleDate" #f)
    (schema-field 'publicationDateText 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publicationDateText" #f)
    (schema-field 'publicationDateSeason 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publicationDateSeason" #f)
    (schema-field 'lastRevisionDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.lastRevisionDate" #f)
    (schema-field 'language 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.language" #f)
    (schema-field 'accessionNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.accessionNumber" #f)
    (schema-field 'pageString 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.pageString" #f)
    (schema-field 'firstPage 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.firstPage" #f)
    (schema-field 'lastPage 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.lastPage" #f)
    (schema-field 'pageCount 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.pageCount" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.copyright" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.publicationForm.publishedIn" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publishedIn") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn" 'element))
(register-element! "Citation.citedArtifact.publicationForm.citedMedium" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.citedMedium") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.citedMedium" 'element))
(register-element! "Citation.citedArtifact.publicationForm.volume" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.volume") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.volume" 'element))
(register-element! "Citation.citedArtifact.publicationForm.issue" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.issue") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.issue" 'element))
(register-element! "Citation.citedArtifact.publicationForm.articleDate" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.articleDate") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.articleDate" 'element))
(register-element! "Citation.citedArtifact.publicationForm.publicationDateText" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publicationDateText") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publicationDateText" 'element))
(register-element! "Citation.citedArtifact.publicationForm.publicationDateSeason" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publicationDateSeason") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publicationDateSeason" 'element))
(register-element! "Citation.citedArtifact.publicationForm.lastRevisionDate" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.lastRevisionDate") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.lastRevisionDate" 'element))
(register-element! "Citation.citedArtifact.publicationForm.language" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.language") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.language" 'element))
(register-element! "Citation.citedArtifact.publicationForm.accessionNumber" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.accessionNumber") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.accessionNumber" 'element))
(register-element! "Citation.citedArtifact.publicationForm.pageString" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.pageString") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.pageString" 'element))
(register-element! "Citation.citedArtifact.publicationForm.firstPage" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.firstPage") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.firstPage" 'element))
(register-element! "Citation.citedArtifact.publicationForm.lastPage" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.lastPage") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.lastPage" 'element))
(register-element! "Citation.citedArtifact.publicationForm.pageCount" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.pageCount") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.pageCount" 'element))
(register-element! "Citation.citedArtifact.publicationForm.copyright" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.copyright") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.copyright" 'element))

(register-type! 'CitationCitedArtifactPublicationFormPublishedIn (fhir-spec 'CitationCitedArtifactPublicationFormPublishedIn "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn" 'type)
  #:schema (type-schema 'CitationCitedArtifactPublicationFormPublishedIn #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.type" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.identifier" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.title" #f)
    (schema-field 'publisher 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.publisher" #f)
    (schema-field 'publisherLocation 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.publisherLocation" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.publicationForm.publishedIn.type" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publishedIn.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.type" 'element))
(register-element! "Citation.citedArtifact.publicationForm.publishedIn.identifier" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publishedIn.identifier") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.identifier" 'element))
(register-element! "Citation.citedArtifact.publicationForm.publishedIn.title" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publishedIn.title") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.title" 'element))
(register-element! "Citation.citedArtifact.publicationForm.publishedIn.publisher" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publishedIn.publisher") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.publisher" 'element))
(register-element! "Citation.citedArtifact.publicationForm.publishedIn.publisherLocation" (fhir-spec (string->symbol "Citation.citedArtifact.publicationForm.publishedIn.publisherLocation") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.publicationForm.publishedIn.publisherLocation" 'element))

(register-type! 'CitationCitedArtifactWebLocation (fhir-spec 'CitationCitedArtifactWebLocation "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation" 'type)
  #:schema (type-schema 'CitationCitedArtifactWebLocation #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation"
             (list
    (schema-field 'classifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation.classifier" #f)
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation.url" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.webLocation.classifier" (fhir-spec (string->symbol "Citation.citedArtifact.webLocation.classifier") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation.classifier" 'element))
(register-element! "Citation.citedArtifact.webLocation.url" (fhir-spec (string->symbol "Citation.citedArtifact.webLocation.url") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.webLocation.url" 'element))

(register-type! 'CitationCitedArtifactClassification (fhir-spec 'CitationCitedArtifactClassification "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification" 'type)
  #:schema (type-schema 'CitationCitedArtifactClassification #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification.type" #f)
    (schema-field 'classifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification.classifier" #f)
    (schema-field 'artifactAssessment 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification.artifactAssessment" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.classification.type" (fhir-spec (string->symbol "Citation.citedArtifact.classification.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification.type" 'element))
(register-element! "Citation.citedArtifact.classification.classifier" (fhir-spec (string->symbol "Citation.citedArtifact.classification.classifier") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification.classifier" 'element))
(register-element! "Citation.citedArtifact.classification.artifactAssessment" (fhir-spec (string->symbol "Citation.citedArtifact.classification.artifactAssessment") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.classification.artifactAssessment" 'element))

(register-type! 'CitationCitedArtifactContributorship (fhir-spec 'CitationCitedArtifactContributorship "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship" 'type)
  #:schema (type-schema 'CitationCitedArtifactContributorship #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship"
             (list
    (schema-field 'complete 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.complete" #f)
    (schema-field 'entry 0 '* (vector 'type 'CitationCitedArtifactContributorshipEntry) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry" #f)
    (schema-field 'summary 0 '* (vector 'type 'CitationCitedArtifactContributorshipSummary) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.contributorship.complete" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.complete") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.complete" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry" 'element))
(register-element! "Citation.citedArtifact.contributorship.summary" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.summary") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary" 'element))

(register-type! 'CitationCitedArtifactContributorshipEntry (fhir-spec 'CitationCitedArtifactContributorshipEntry "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry" 'type)
  #:schema (type-schema 'CitationCitedArtifactContributorshipEntry #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry"
             (list
    (schema-field 'contributor 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributor" #f)
    (schema-field 'forenameInitials 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.forenameInitials" #f)
    (schema-field 'affiliation 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.affiliation" #f)
    (schema-field 'contributionType 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionType" #f)
    (schema-field 'role 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.role" #f)
    (schema-field 'contributionInstance 0 '* (vector 'type 'CitationCitedArtifactContributorshipEntryContributionInstance) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance" #f)
    (schema-field 'correspondingContact 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.correspondingContact" #f)
    (schema-field 'rankingOrder 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.rankingOrder" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.contributorship.entry.contributor" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.contributor") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributor" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.forenameInitials" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.forenameInitials") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.forenameInitials" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.affiliation" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.affiliation") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.affiliation" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.contributionType" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.contributionType") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionType" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.role" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.role") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.role" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.contributionInstance" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.contributionInstance") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.correspondingContact" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.correspondingContact") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.correspondingContact" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.rankingOrder" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.rankingOrder") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.rankingOrder" 'element))

(register-type! 'CitationCitedArtifactContributorshipEntryContributionInstance (fhir-spec 'CitationCitedArtifactContributorshipEntryContributionInstance "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance" 'type)
  #:schema (type-schema 'CitationCitedArtifactContributorshipEntryContributionInstance #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance.type" #f)
    (schema-field 'time 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance.time" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.contributorship.entry.contributionInstance.type" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.contributionInstance.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance.type" 'element))
(register-element! "Citation.citedArtifact.contributorship.entry.contributionInstance.time" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.entry.contributionInstance.time") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.entry.contributionInstance.time" 'element))

(register-type! 'CitationCitedArtifactContributorshipSummary (fhir-spec 'CitationCitedArtifactContributorshipSummary "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary" 'type)
  #:schema (type-schema 'CitationCitedArtifactContributorshipSummary #f 'BackboneElement "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.type" #f)
    (schema-field 'style 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.style" #f)
    (schema-field 'source 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.source" #f)
    (schema-field 'value 1 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.value" #f)
             ) #f #f))
(register-element! "Citation.citedArtifact.contributorship.summary.type" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.summary.type") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.type" 'element))
(register-element! "Citation.citedArtifact.contributorship.summary.style" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.summary.style") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.style" 'element))
(register-element! "Citation.citedArtifact.contributorship.summary.source" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.summary.source") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.source" 'element))
(register-element! "Citation.citedArtifact.contributorship.summary.value" (fhir-spec (string->symbol "Citation.citedArtifact.contributorship.summary.value") "https://hl7.org/fhir/R5/citation.html#Citation.citedArtifact.contributorship.summary.value" 'element))

