#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ClaimResponse (fhir-spec 'ClaimResponse "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse" 'type)
  #:schema (type-schema 'ClaimResponse #f 'DomainResource "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.identifier" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.traceNumber" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.status" #f)
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.type" #f)
    (schema-field 'subType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.subType" #f)
    (schema-field 'use 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.use" #f)
    (schema-field 'patient 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.patient" #f)
    (schema-field 'created 1 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.created" #f)
    (schema-field 'insurer 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurer" #f)
    (schema-field 'requestor 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.requestor" #f)
    (schema-field 'request 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.request" #f)
    (schema-field 'outcome 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.outcome" #f)
    (schema-field 'decision 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.decision" #f)
    (schema-field 'disposition 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.disposition" #f)
    (schema-field 'preAuthRef 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.preAuthRef" #f)
    (schema-field 'preAuthPeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.preAuthPeriod" #f)
    (schema-field 'event 0 '* (vector 'type 'ClaimResponseEvent) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event" #f)
    (schema-field 'payeeType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payeeType" #f)
    (schema-field 'encounter 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.encounter" #f)
    (schema-field 'diagnosisRelatedGroup 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.diagnosisRelatedGroup" #f)
    (schema-field 'item 0 '* (vector 'type 'ClaimResponseItem) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item" #f)
    (schema-field 'addItem 0 '* (vector 'type 'ClaimResponseAddItem) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ClaimResponseItemAdjudication) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.adjudication" #f)
    (schema-field 'total 0 '* (vector 'type 'ClaimResponseTotal) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total" #f)
    (schema-field 'payment 0 1 (vector 'type 'ClaimResponsePayment) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment" #f)
    (schema-field 'fundsReserve 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.fundsReserve" #f)
    (schema-field 'formCode 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.formCode" #f)
    (schema-field 'form 0 1 (vector 'type 'Attachment) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.form" #f)
    (schema-field 'processNote 0 '* (vector 'type 'ClaimResponseProcessNote) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote" #f)
    (schema-field 'communicationRequest 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.communicationRequest" #f)
    (schema-field 'insurance 0 '* (vector 'type 'ClaimResponseInsurance) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance" #f)
    (schema-field 'error 0 '* (vector 'type 'ClaimResponseError) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error" #f)
             ) #f #f))
(register-element! "ClaimResponse.identifier" (fhir-spec (string->symbol "ClaimResponse.identifier") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.identifier" 'element))
(register-element! "ClaimResponse.traceNumber" (fhir-spec (string->symbol "ClaimResponse.traceNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.traceNumber" 'element))
(register-element! "ClaimResponse.status" (fhir-spec (string->symbol "ClaimResponse.status") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.status" 'element))
(register-element! "ClaimResponse.type" (fhir-spec (string->symbol "ClaimResponse.type") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.type" 'element))
(register-element! "ClaimResponse.subType" (fhir-spec (string->symbol "ClaimResponse.subType") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.subType" 'element))
(register-element! "ClaimResponse.use" (fhir-spec (string->symbol "ClaimResponse.use") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.use" 'element))
(register-element! "ClaimResponse.patient" (fhir-spec (string->symbol "ClaimResponse.patient") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.patient" 'element))
(register-element! "ClaimResponse.created" (fhir-spec (string->symbol "ClaimResponse.created") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.created" 'element))
(register-element! "ClaimResponse.insurer" (fhir-spec (string->symbol "ClaimResponse.insurer") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurer" 'element))
(register-element! "ClaimResponse.requestor" (fhir-spec (string->symbol "ClaimResponse.requestor") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.requestor" 'element))
(register-element! "ClaimResponse.request" (fhir-spec (string->symbol "ClaimResponse.request") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.request" 'element))
(register-element! "ClaimResponse.outcome" (fhir-spec (string->symbol "ClaimResponse.outcome") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.outcome" 'element))
(register-element! "ClaimResponse.decision" (fhir-spec (string->symbol "ClaimResponse.decision") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.decision" 'element))
(register-element! "ClaimResponse.disposition" (fhir-spec (string->symbol "ClaimResponse.disposition") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.disposition" 'element))
(register-element! "ClaimResponse.preAuthRef" (fhir-spec (string->symbol "ClaimResponse.preAuthRef") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.preAuthRef" 'element))
(register-element! "ClaimResponse.preAuthPeriod" (fhir-spec (string->symbol "ClaimResponse.preAuthPeriod") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.preAuthPeriod" 'element))
(register-element! "ClaimResponse.event" (fhir-spec (string->symbol "ClaimResponse.event") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event" 'element))
(register-element! "ClaimResponse.payeeType" (fhir-spec (string->symbol "ClaimResponse.payeeType") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payeeType" 'element))
(register-element! "ClaimResponse.encounter" (fhir-spec (string->symbol "ClaimResponse.encounter") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.encounter" 'element))
(register-element! "ClaimResponse.diagnosisRelatedGroup" (fhir-spec (string->symbol "ClaimResponse.diagnosisRelatedGroup") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.diagnosisRelatedGroup" 'element))
(register-element! "ClaimResponse.item" (fhir-spec (string->symbol "ClaimResponse.item") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item" 'element))
(register-element! "ClaimResponse.addItem" (fhir-spec (string->symbol "ClaimResponse.addItem") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem" 'element))
(register-element! "ClaimResponse.adjudication" (fhir-spec (string->symbol "ClaimResponse.adjudication") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.adjudication" 'element))
(register-element! "ClaimResponse.total" (fhir-spec (string->symbol "ClaimResponse.total") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total" 'element))
(register-element! "ClaimResponse.payment" (fhir-spec (string->symbol "ClaimResponse.payment") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment" 'element))
(register-element! "ClaimResponse.fundsReserve" (fhir-spec (string->symbol "ClaimResponse.fundsReserve") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.fundsReserve" 'element))
(register-element! "ClaimResponse.formCode" (fhir-spec (string->symbol "ClaimResponse.formCode") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.formCode" 'element))
(register-element! "ClaimResponse.form" (fhir-spec (string->symbol "ClaimResponse.form") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.form" 'element))
(register-element! "ClaimResponse.processNote" (fhir-spec (string->symbol "ClaimResponse.processNote") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote" 'element))
(register-element! "ClaimResponse.communicationRequest" (fhir-spec (string->symbol "ClaimResponse.communicationRequest") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.communicationRequest" 'element))
(register-element! "ClaimResponse.insurance" (fhir-spec (string->symbol "ClaimResponse.insurance") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance" 'element))
(register-element! "ClaimResponse.error" (fhir-spec (string->symbol "ClaimResponse.error") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error" 'element))

(register-type! 'ClaimResponseEvent (fhir-spec 'ClaimResponseEvent "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event" 'type)
  #:schema (type-schema 'ClaimResponseEvent #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event.type" #f)
    (schema-field 'whenDateTime 0 1 (vector 'prim "dateTime") 'when "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event.when[x]" #f)
    (schema-field 'whenPeriod 0 1 (vector 'type 'Period) 'when "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event.when[x]" #f)
             ) #f #f))
(register-element! "ClaimResponse.event.type" (fhir-spec (string->symbol "ClaimResponse.event.type") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event.type" 'element))
(register-element! "ClaimResponse.event.when[x]" (fhir-spec (string->symbol "ClaimResponse.event.when[x]") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event.when[x]" 'element))
(register-element! "ClaimResponse.event.when[x]" (fhir-spec (string->symbol "ClaimResponse.event.when[x]") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.event.when[x]" 'element))

(register-type! 'ClaimResponseItem (fhir-spec 'ClaimResponseItem "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item" 'type)
  #:schema (type-schema 'ClaimResponseItem #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item"
             (list
    (schema-field 'itemSequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.itemSequence" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.traceNumber" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.noteNumber" #f)
    (schema-field 'reviewOutcome 0 1 (vector 'type 'ClaimResponseItemReviewOutcome) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ClaimResponseItemAdjudication) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication" #f)
    (schema-field 'detail 0 '* (vector 'type 'ClaimResponseItemDetail) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail" #f)
             ) #f #f))
(register-element! "ClaimResponse.item.itemSequence" (fhir-spec (string->symbol "ClaimResponse.item.itemSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.itemSequence" 'element))
(register-element! "ClaimResponse.item.traceNumber" (fhir-spec (string->symbol "ClaimResponse.item.traceNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.traceNumber" 'element))
(register-element! "ClaimResponse.item.noteNumber" (fhir-spec (string->symbol "ClaimResponse.item.noteNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.noteNumber" 'element))
(register-element! "ClaimResponse.item.reviewOutcome" (fhir-spec (string->symbol "ClaimResponse.item.reviewOutcome") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome" 'element))
(register-element! "ClaimResponse.item.adjudication" (fhir-spec (string->symbol "ClaimResponse.item.adjudication") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication" 'element))
(register-element! "ClaimResponse.item.detail" (fhir-spec (string->symbol "ClaimResponse.item.detail") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail" 'element))

(register-type! 'ClaimResponseItemReviewOutcome (fhir-spec 'ClaimResponseItemReviewOutcome "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome" 'type)
  #:schema (type-schema 'ClaimResponseItemReviewOutcome #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome"
             (list
    (schema-field 'decision 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.decision" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.reason" #f)
    (schema-field 'preAuthRef 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.preAuthRef" #f)
    (schema-field 'preAuthPeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.preAuthPeriod" #f)
             ) #f #f))
(register-element! "ClaimResponse.item.reviewOutcome.decision" (fhir-spec (string->symbol "ClaimResponse.item.reviewOutcome.decision") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.decision" 'element))
(register-element! "ClaimResponse.item.reviewOutcome.reason" (fhir-spec (string->symbol "ClaimResponse.item.reviewOutcome.reason") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.reason" 'element))
(register-element! "ClaimResponse.item.reviewOutcome.preAuthRef" (fhir-spec (string->symbol "ClaimResponse.item.reviewOutcome.preAuthRef") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.preAuthRef" 'element))
(register-element! "ClaimResponse.item.reviewOutcome.preAuthPeriod" (fhir-spec (string->symbol "ClaimResponse.item.reviewOutcome.preAuthPeriod") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.reviewOutcome.preAuthPeriod" 'element))

(register-type! 'ClaimResponseItemAdjudication (fhir-spec 'ClaimResponseItemAdjudication "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication" 'type)
  #:schema (type-schema 'ClaimResponseItemAdjudication #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication"
             (list
    (schema-field 'category 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.category" #f)
    (schema-field 'reason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.reason" #f)
    (schema-field 'amount 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.amount" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.quantity" #f)
             ) #f #f))
(register-element! "ClaimResponse.item.adjudication.category" (fhir-spec (string->symbol "ClaimResponse.item.adjudication.category") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.category" 'element))
(register-element! "ClaimResponse.item.adjudication.reason" (fhir-spec (string->symbol "ClaimResponse.item.adjudication.reason") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.reason" 'element))
(register-element! "ClaimResponse.item.adjudication.amount" (fhir-spec (string->symbol "ClaimResponse.item.adjudication.amount") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.amount" 'element))
(register-element! "ClaimResponse.item.adjudication.quantity" (fhir-spec (string->symbol "ClaimResponse.item.adjudication.quantity") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.adjudication.quantity" 'element))

(register-type! 'ClaimResponseItemDetail (fhir-spec 'ClaimResponseItemDetail "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail" 'type)
  #:schema (type-schema 'ClaimResponseItemDetail #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail"
             (list
    (schema-field 'detailSequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.detailSequence" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.traceNumber" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.noteNumber" #f)
    (schema-field 'reviewOutcome 0 1 (vector 'type 'ClaimResponseItemReviewOutcome) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.reviewOutcome" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ClaimResponseItemAdjudication) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.adjudication" #f)
    (schema-field 'subDetail 0 '* (vector 'type 'ClaimResponseItemDetailSubDetail) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail" #f)
             ) #f #f))
(register-element! "ClaimResponse.item.detail.detailSequence" (fhir-spec (string->symbol "ClaimResponse.item.detail.detailSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.detailSequence" 'element))
(register-element! "ClaimResponse.item.detail.traceNumber" (fhir-spec (string->symbol "ClaimResponse.item.detail.traceNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.traceNumber" 'element))
(register-element! "ClaimResponse.item.detail.noteNumber" (fhir-spec (string->symbol "ClaimResponse.item.detail.noteNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.noteNumber" 'element))
(register-element! "ClaimResponse.item.detail.reviewOutcome" (fhir-spec (string->symbol "ClaimResponse.item.detail.reviewOutcome") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.reviewOutcome" 'element))
(register-element! "ClaimResponse.item.detail.adjudication" (fhir-spec (string->symbol "ClaimResponse.item.detail.adjudication") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.adjudication" 'element))
(register-element! "ClaimResponse.item.detail.subDetail" (fhir-spec (string->symbol "ClaimResponse.item.detail.subDetail") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail" 'element))

(register-type! 'ClaimResponseItemDetailSubDetail (fhir-spec 'ClaimResponseItemDetailSubDetail "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail" 'type)
  #:schema (type-schema 'ClaimResponseItemDetailSubDetail #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail"
             (list
    (schema-field 'subDetailSequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.subDetailSequence" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.traceNumber" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.noteNumber" #f)
    (schema-field 'reviewOutcome 0 1 (vector 'type 'ClaimResponseItemReviewOutcome) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.reviewOutcome" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ClaimResponseItemAdjudication) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.adjudication" #f)
             ) #f #f))
(register-element! "ClaimResponse.item.detail.subDetail.subDetailSequence" (fhir-spec (string->symbol "ClaimResponse.item.detail.subDetail.subDetailSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.subDetailSequence" 'element))
(register-element! "ClaimResponse.item.detail.subDetail.traceNumber" (fhir-spec (string->symbol "ClaimResponse.item.detail.subDetail.traceNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.traceNumber" 'element))
(register-element! "ClaimResponse.item.detail.subDetail.noteNumber" (fhir-spec (string->symbol "ClaimResponse.item.detail.subDetail.noteNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.noteNumber" 'element))
(register-element! "ClaimResponse.item.detail.subDetail.reviewOutcome" (fhir-spec (string->symbol "ClaimResponse.item.detail.subDetail.reviewOutcome") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.reviewOutcome" 'element))
(register-element! "ClaimResponse.item.detail.subDetail.adjudication" (fhir-spec (string->symbol "ClaimResponse.item.detail.subDetail.adjudication") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.item.detail.subDetail.adjudication" 'element))

(register-type! 'ClaimResponseAddItem (fhir-spec 'ClaimResponseAddItem "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem" 'type)
  #:schema (type-schema 'ClaimResponseAddItem #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem"
             (list
    (schema-field 'itemSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.itemSequence" #f)
    (schema-field 'detailSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detailSequence" #f)
    (schema-field 'subdetailSequence 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.subdetailSequence" #f)
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.traceNumber" #f)
    (schema-field 'provider 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.provider" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.revenue" #f)
    (schema-field 'productOrService 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.productOrService" #f)
    (schema-field 'productOrServiceEnd 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.productOrServiceEnd" #f)
    (schema-field 'request 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.request" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.modifier" #f)
    (schema-field 'programCode 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.programCode" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.factor" #f)
    (schema-field 'tax 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.tax" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.net" #f)
    (schema-field 'bodySite 0 '* (vector 'type 'ClaimResponseAddItemBodySite) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.noteNumber" #f)
    (schema-field 'reviewOutcome 0 1 (vector 'type 'ClaimResponseItemReviewOutcome) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.reviewOutcome" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ClaimResponseItemAdjudication) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.adjudication" #f)
    (schema-field 'detail 0 '* (vector 'type 'ClaimResponseAddItemDetail) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail" #f)
    (schema-field 'servicedDate 0 1 (vector 'prim "date") 'serviced "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.serviced[x]" #f)
    (schema-field 'servicedPeriod 0 1 (vector 'type 'Period) 'serviced "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.serviced[x]" #f)
    (schema-field 'locationCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'location "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.location[x]" #f)
    (schema-field 'locationAddress 0 1 (vector 'type 'Address) 'location "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.location[x]" #f)
    (schema-field 'locationReference 0 1 (vector 'type 'Reference) 'location "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.location[x]" #f)
             ) #f #f))
(register-element! "ClaimResponse.addItem.itemSequence" (fhir-spec (string->symbol "ClaimResponse.addItem.itemSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.itemSequence" 'element))
(register-element! "ClaimResponse.addItem.detailSequence" (fhir-spec (string->symbol "ClaimResponse.addItem.detailSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detailSequence" 'element))
(register-element! "ClaimResponse.addItem.subdetailSequence" (fhir-spec (string->symbol "ClaimResponse.addItem.subdetailSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.subdetailSequence" 'element))
(register-element! "ClaimResponse.addItem.traceNumber" (fhir-spec (string->symbol "ClaimResponse.addItem.traceNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.traceNumber" 'element))
(register-element! "ClaimResponse.addItem.provider" (fhir-spec (string->symbol "ClaimResponse.addItem.provider") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.provider" 'element))
(register-element! "ClaimResponse.addItem.revenue" (fhir-spec (string->symbol "ClaimResponse.addItem.revenue") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.revenue" 'element))
(register-element! "ClaimResponse.addItem.productOrService" (fhir-spec (string->symbol "ClaimResponse.addItem.productOrService") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.productOrService" 'element))
(register-element! "ClaimResponse.addItem.productOrServiceEnd" (fhir-spec (string->symbol "ClaimResponse.addItem.productOrServiceEnd") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.productOrServiceEnd" 'element))
(register-element! "ClaimResponse.addItem.request" (fhir-spec (string->symbol "ClaimResponse.addItem.request") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.request" 'element))
(register-element! "ClaimResponse.addItem.modifier" (fhir-spec (string->symbol "ClaimResponse.addItem.modifier") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.modifier" 'element))
(register-element! "ClaimResponse.addItem.programCode" (fhir-spec (string->symbol "ClaimResponse.addItem.programCode") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.programCode" 'element))
(register-element! "ClaimResponse.addItem.quantity" (fhir-spec (string->symbol "ClaimResponse.addItem.quantity") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.quantity" 'element))
(register-element! "ClaimResponse.addItem.unitPrice" (fhir-spec (string->symbol "ClaimResponse.addItem.unitPrice") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.unitPrice" 'element))
(register-element! "ClaimResponse.addItem.factor" (fhir-spec (string->symbol "ClaimResponse.addItem.factor") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.factor" 'element))
(register-element! "ClaimResponse.addItem.tax" (fhir-spec (string->symbol "ClaimResponse.addItem.tax") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.tax" 'element))
(register-element! "ClaimResponse.addItem.net" (fhir-spec (string->symbol "ClaimResponse.addItem.net") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.net" 'element))
(register-element! "ClaimResponse.addItem.bodySite" (fhir-spec (string->symbol "ClaimResponse.addItem.bodySite") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite" 'element))
(register-element! "ClaimResponse.addItem.noteNumber" (fhir-spec (string->symbol "ClaimResponse.addItem.noteNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.noteNumber" 'element))
(register-element! "ClaimResponse.addItem.reviewOutcome" (fhir-spec (string->symbol "ClaimResponse.addItem.reviewOutcome") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.reviewOutcome" 'element))
(register-element! "ClaimResponse.addItem.adjudication" (fhir-spec (string->symbol "ClaimResponse.addItem.adjudication") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.adjudication" 'element))
(register-element! "ClaimResponse.addItem.detail" (fhir-spec (string->symbol "ClaimResponse.addItem.detail") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail" 'element))
(register-element! "ClaimResponse.addItem.serviced[x]" (fhir-spec (string->symbol "ClaimResponse.addItem.serviced[x]") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.serviced[x]" 'element))
(register-element! "ClaimResponse.addItem.serviced[x]" (fhir-spec (string->symbol "ClaimResponse.addItem.serviced[x]") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.serviced[x]" 'element))
(register-element! "ClaimResponse.addItem.location[x]" (fhir-spec (string->symbol "ClaimResponse.addItem.location[x]") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.location[x]" 'element))
(register-element! "ClaimResponse.addItem.location[x]" (fhir-spec (string->symbol "ClaimResponse.addItem.location[x]") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.location[x]" 'element))
(register-element! "ClaimResponse.addItem.location[x]" (fhir-spec (string->symbol "ClaimResponse.addItem.location[x]") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.location[x]" 'element))

(register-type! 'ClaimResponseAddItemBodySite (fhir-spec 'ClaimResponseAddItemBodySite "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite" 'type)
  #:schema (type-schema 'ClaimResponseAddItemBodySite #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite"
             (list
    (schema-field 'site 1 '* (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite.site" #f)
    (schema-field 'subSite 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite.subSite" #f)
             ) #f #f))
(register-element! "ClaimResponse.addItem.bodySite.site" (fhir-spec (string->symbol "ClaimResponse.addItem.bodySite.site") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite.site" 'element))
(register-element! "ClaimResponse.addItem.bodySite.subSite" (fhir-spec (string->symbol "ClaimResponse.addItem.bodySite.subSite") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.bodySite.subSite" 'element))

(register-type! 'ClaimResponseAddItemDetail (fhir-spec 'ClaimResponseAddItemDetail "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail" 'type)
  #:schema (type-schema 'ClaimResponseAddItemDetail #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail"
             (list
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.traceNumber" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.revenue" #f)
    (schema-field 'productOrService 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.productOrService" #f)
    (schema-field 'productOrServiceEnd 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.productOrServiceEnd" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.modifier" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.factor" #f)
    (schema-field 'tax 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.tax" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.net" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.noteNumber" #f)
    (schema-field 'reviewOutcome 0 1 (vector 'type 'ClaimResponseItemReviewOutcome) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.reviewOutcome" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ClaimResponseItemAdjudication) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.adjudication" #f)
    (schema-field 'subDetail 0 '* (vector 'type 'ClaimResponseAddItemDetailSubDetail) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail" #f)
             ) #f #f))
(register-element! "ClaimResponse.addItem.detail.traceNumber" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.traceNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.traceNumber" 'element))
(register-element! "ClaimResponse.addItem.detail.revenue" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.revenue") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.revenue" 'element))
(register-element! "ClaimResponse.addItem.detail.productOrService" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.productOrService") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.productOrService" 'element))
(register-element! "ClaimResponse.addItem.detail.productOrServiceEnd" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.productOrServiceEnd") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.productOrServiceEnd" 'element))
(register-element! "ClaimResponse.addItem.detail.modifier" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.modifier") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.modifier" 'element))
(register-element! "ClaimResponse.addItem.detail.quantity" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.quantity") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.quantity" 'element))
(register-element! "ClaimResponse.addItem.detail.unitPrice" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.unitPrice") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.unitPrice" 'element))
(register-element! "ClaimResponse.addItem.detail.factor" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.factor") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.factor" 'element))
(register-element! "ClaimResponse.addItem.detail.tax" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.tax") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.tax" 'element))
(register-element! "ClaimResponse.addItem.detail.net" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.net") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.net" 'element))
(register-element! "ClaimResponse.addItem.detail.noteNumber" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.noteNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.noteNumber" 'element))
(register-element! "ClaimResponse.addItem.detail.reviewOutcome" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.reviewOutcome") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.reviewOutcome" 'element))
(register-element! "ClaimResponse.addItem.detail.adjudication" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.adjudication") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.adjudication" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail" 'element))

(register-type! 'ClaimResponseAddItemDetailSubDetail (fhir-spec 'ClaimResponseAddItemDetailSubDetail "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail" 'type)
  #:schema (type-schema 'ClaimResponseAddItemDetailSubDetail #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail"
             (list
    (schema-field 'traceNumber 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.traceNumber" #f)
    (schema-field 'revenue 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.revenue" #f)
    (schema-field 'productOrService 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.productOrService" #f)
    (schema-field 'productOrServiceEnd 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.productOrServiceEnd" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.modifier" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.quantity" #f)
    (schema-field 'unitPrice 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.unitPrice" #f)
    (schema-field 'factor 0 1 (vector 'prim "decimal") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.factor" #f)
    (schema-field 'tax 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.tax" #f)
    (schema-field 'net 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.net" #f)
    (schema-field 'noteNumber 0 '* (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.noteNumber" #f)
    (schema-field 'reviewOutcome 0 1 (vector 'type 'ClaimResponseItemReviewOutcome) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.reviewOutcome" #f)
    (schema-field 'adjudication 0 '* (vector 'type 'ClaimResponseItemAdjudication) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.adjudication" #f)
             ) #f #f))
(register-element! "ClaimResponse.addItem.detail.subDetail.traceNumber" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.traceNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.traceNumber" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.revenue" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.revenue") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.revenue" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.productOrService" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.productOrService") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.productOrService" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.productOrServiceEnd" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.productOrServiceEnd") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.productOrServiceEnd" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.modifier" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.modifier") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.modifier" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.quantity" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.quantity") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.quantity" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.unitPrice" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.unitPrice") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.unitPrice" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.factor" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.factor") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.factor" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.tax" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.tax") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.tax" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.net" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.net") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.net" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.noteNumber" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.noteNumber") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.noteNumber" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.reviewOutcome" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.reviewOutcome") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.reviewOutcome" 'element))
(register-element! "ClaimResponse.addItem.detail.subDetail.adjudication" (fhir-spec (string->symbol "ClaimResponse.addItem.detail.subDetail.adjudication") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.addItem.detail.subDetail.adjudication" 'element))

(register-type! 'ClaimResponseTotal (fhir-spec 'ClaimResponseTotal "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total" 'type)
  #:schema (type-schema 'ClaimResponseTotal #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total"
             (list
    (schema-field 'category 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total.category" #f)
    (schema-field 'amount 1 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total.amount" #f)
             ) #f #f))
(register-element! "ClaimResponse.total.category" (fhir-spec (string->symbol "ClaimResponse.total.category") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total.category" 'element))
(register-element! "ClaimResponse.total.amount" (fhir-spec (string->symbol "ClaimResponse.total.amount") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.total.amount" 'element))

(register-type! 'ClaimResponsePayment (fhir-spec 'ClaimResponsePayment "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment" 'type)
  #:schema (type-schema 'ClaimResponsePayment #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.type" #f)
    (schema-field 'adjustment 0 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.adjustment" #f)
    (schema-field 'adjustmentReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.adjustmentReason" #f)
    (schema-field 'date 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.date" #f)
    (schema-field 'amount 1 1 (vector 'type 'Money) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.amount" #f)
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.identifier" #f)
             ) #f #f))
(register-element! "ClaimResponse.payment.type" (fhir-spec (string->symbol "ClaimResponse.payment.type") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.type" 'element))
(register-element! "ClaimResponse.payment.adjustment" (fhir-spec (string->symbol "ClaimResponse.payment.adjustment") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.adjustment" 'element))
(register-element! "ClaimResponse.payment.adjustmentReason" (fhir-spec (string->symbol "ClaimResponse.payment.adjustmentReason") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.adjustmentReason" 'element))
(register-element! "ClaimResponse.payment.date" (fhir-spec (string->symbol "ClaimResponse.payment.date") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.date" 'element))
(register-element! "ClaimResponse.payment.amount" (fhir-spec (string->symbol "ClaimResponse.payment.amount") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.amount" 'element))
(register-element! "ClaimResponse.payment.identifier" (fhir-spec (string->symbol "ClaimResponse.payment.identifier") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.payment.identifier" 'element))

(register-type! 'ClaimResponseProcessNote (fhir-spec 'ClaimResponseProcessNote "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote" 'type)
  #:schema (type-schema 'ClaimResponseProcessNote #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote"
             (list
    (schema-field 'number 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.number" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.type" #f)
    (schema-field 'text 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.text" #f)
    (schema-field 'language 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.language" #f)
             ) #f #f))
(register-element! "ClaimResponse.processNote.number" (fhir-spec (string->symbol "ClaimResponse.processNote.number") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.number" 'element))
(register-element! "ClaimResponse.processNote.type" (fhir-spec (string->symbol "ClaimResponse.processNote.type") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.type" 'element))
(register-element! "ClaimResponse.processNote.text" (fhir-spec (string->symbol "ClaimResponse.processNote.text") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.text" 'element))
(register-element! "ClaimResponse.processNote.language" (fhir-spec (string->symbol "ClaimResponse.processNote.language") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.processNote.language" 'element))

(register-type! 'ClaimResponseInsurance (fhir-spec 'ClaimResponseInsurance "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance" 'type)
  #:schema (type-schema 'ClaimResponseInsurance #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance"
             (list
    (schema-field 'sequence 1 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.sequence" #f)
    (schema-field 'focal 1 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.focal" #f)
    (schema-field 'coverage 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.coverage" #f)
    (schema-field 'businessArrangement 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.businessArrangement" #f)
    (schema-field 'claimResponse 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.claimResponse" #f)
             ) #f #f))
(register-element! "ClaimResponse.insurance.sequence" (fhir-spec (string->symbol "ClaimResponse.insurance.sequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.sequence" 'element))
(register-element! "ClaimResponse.insurance.focal" (fhir-spec (string->symbol "ClaimResponse.insurance.focal") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.focal" 'element))
(register-element! "ClaimResponse.insurance.coverage" (fhir-spec (string->symbol "ClaimResponse.insurance.coverage") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.coverage" 'element))
(register-element! "ClaimResponse.insurance.businessArrangement" (fhir-spec (string->symbol "ClaimResponse.insurance.businessArrangement") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.businessArrangement" 'element))
(register-element! "ClaimResponse.insurance.claimResponse" (fhir-spec (string->symbol "ClaimResponse.insurance.claimResponse") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.insurance.claimResponse" 'element))

(register-type! 'ClaimResponseError (fhir-spec 'ClaimResponseError "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error" 'type)
  #:schema (type-schema 'ClaimResponseError #f 'BackboneElement "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error"
             (list
    (schema-field 'itemSequence 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.itemSequence" #f)
    (schema-field 'detailSequence 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.detailSequence" #f)
    (schema-field 'subDetailSequence 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.subDetailSequence" #f)
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.code" #f)
    (schema-field 'expression 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.expression" #f)
             ) #f #f))
(register-element! "ClaimResponse.error.itemSequence" (fhir-spec (string->symbol "ClaimResponse.error.itemSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.itemSequence" 'element))
(register-element! "ClaimResponse.error.detailSequence" (fhir-spec (string->symbol "ClaimResponse.error.detailSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.detailSequence" 'element))
(register-element! "ClaimResponse.error.subDetailSequence" (fhir-spec (string->symbol "ClaimResponse.error.subDetailSequence") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.subDetailSequence" 'element))
(register-element! "ClaimResponse.error.code" (fhir-spec (string->symbol "ClaimResponse.error.code") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.code" 'element))
(register-element! "ClaimResponse.error.expression" (fhir-spec (string->symbol "ClaimResponse.error.expression") "https://hl7.org/fhir/R5/claimresponse.html#ClaimResponse.error.expression" 'element))

