#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'CommunicationRequest (fhir-spec 'CommunicationRequest "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest" 'type)
  #:schema (type-schema 'CommunicationRequest #f 'DomainResource "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.basedOn" #f)
    (schema-field 'replaces 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.replaces" #f)
    (schema-field 'groupIdentifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.groupIdentifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.statusReason" #f)
    (schema-field 'intent 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.intent" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.category" #f)
    (schema-field 'priority 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.priority" #f)
    (schema-field 'doNotPerform 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.doNotPerform" #f)
    (schema-field 'medium 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.medium" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.subject" #f)
    (schema-field 'about 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.about" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.encounter" #f)
    (schema-field 'payload 0 '* (vector 'type 'CommunicationRequestPayload) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload" #f)
    (schema-field 'authoredOn 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.authoredOn" #f)
    (schema-field 'requester 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.requester" #f)
    (schema-field 'recipient 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.recipient" #f)
    (schema-field 'informationProvider 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.informationProvider" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.reason" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.note" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.occurrence[x]" #f)
             ) #f #f))
(register-element! "CommunicationRequest.identifier" (fhir-spec (string->symbol "CommunicationRequest.identifier") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.identifier" 'element))
(register-element! "CommunicationRequest.basedOn" (fhir-spec (string->symbol "CommunicationRequest.basedOn") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.basedOn" 'element))
(register-element! "CommunicationRequest.replaces" (fhir-spec (string->symbol "CommunicationRequest.replaces") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.replaces" 'element))
(register-element! "CommunicationRequest.groupIdentifier" (fhir-spec (string->symbol "CommunicationRequest.groupIdentifier") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.groupIdentifier" 'element))
(register-element! "CommunicationRequest.status" (fhir-spec (string->symbol "CommunicationRequest.status") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.status" 'element))
(register-element! "CommunicationRequest.statusReason" (fhir-spec (string->symbol "CommunicationRequest.statusReason") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.statusReason" 'element))
(register-element! "CommunicationRequest.intent" (fhir-spec (string->symbol "CommunicationRequest.intent") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.intent" 'element))
(register-element! "CommunicationRequest.category" (fhir-spec (string->symbol "CommunicationRequest.category") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.category" 'element))
(register-element! "CommunicationRequest.priority" (fhir-spec (string->symbol "CommunicationRequest.priority") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.priority" 'element))
(register-element! "CommunicationRequest.doNotPerform" (fhir-spec (string->symbol "CommunicationRequest.doNotPerform") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.doNotPerform" 'element))
(register-element! "CommunicationRequest.medium" (fhir-spec (string->symbol "CommunicationRequest.medium") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.medium" 'element))
(register-element! "CommunicationRequest.subject" (fhir-spec (string->symbol "CommunicationRequest.subject") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.subject" 'element))
(register-element! "CommunicationRequest.about" (fhir-spec (string->symbol "CommunicationRequest.about") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.about" 'element))
(register-element! "CommunicationRequest.encounter" (fhir-spec (string->symbol "CommunicationRequest.encounter") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.encounter" 'element))
(register-element! "CommunicationRequest.payload" (fhir-spec (string->symbol "CommunicationRequest.payload") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload" 'element))
(register-element! "CommunicationRequest.authoredOn" (fhir-spec (string->symbol "CommunicationRequest.authoredOn") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.authoredOn" 'element))
(register-element! "CommunicationRequest.requester" (fhir-spec (string->symbol "CommunicationRequest.requester") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.requester" 'element))
(register-element! "CommunicationRequest.recipient" (fhir-spec (string->symbol "CommunicationRequest.recipient") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.recipient" 'element))
(register-element! "CommunicationRequest.informationProvider" (fhir-spec (string->symbol "CommunicationRequest.informationProvider") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.informationProvider" 'element))
(register-element! "CommunicationRequest.reason" (fhir-spec (string->symbol "CommunicationRequest.reason") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.reason" 'element))
(register-element! "CommunicationRequest.note" (fhir-spec (string->symbol "CommunicationRequest.note") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.note" 'element))
(register-element! "CommunicationRequest.occurrence[x]" (fhir-spec (string->symbol "CommunicationRequest.occurrence[x]") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.occurrence[x]" 'element))
(register-element! "CommunicationRequest.occurrence[x]" (fhir-spec (string->symbol "CommunicationRequest.occurrence[x]") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.occurrence[x]" 'element))

(register-type! 'CommunicationRequestPayload (fhir-spec 'CommunicationRequestPayload "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload" 'type)
  #:schema (type-schema 'CommunicationRequestPayload #f 'BackboneElement "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload"
             (list
    (schema-field 'contentAttachment 0 1 (vector 'type 'Attachment) 'content "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload.content[x]" #f)
    (schema-field 'contentReference 0 1 (vector 'type 'Reference) 'content "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload.content[x]" #f)
    (schema-field 'contentCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'content "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload.content[x]" #f)
             ) #f #f))
(register-element! "CommunicationRequest.payload.content[x]" (fhir-spec (string->symbol "CommunicationRequest.payload.content[x]") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload.content[x]" 'element))
(register-element! "CommunicationRequest.payload.content[x]" (fhir-spec (string->symbol "CommunicationRequest.payload.content[x]") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload.content[x]" 'element))
(register-element! "CommunicationRequest.payload.content[x]" (fhir-spec (string->symbol "CommunicationRequest.payload.content[x]") "https://hl7.org/fhir/R5/communicationrequest.html#CommunicationRequest.payload.content[x]" 'element))

