#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'CoverageEligibilityResponse (fhir-spec 'CoverageEligibilityResponse "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse" 'type)
  #:schema (type-schema 'CoverageEligibilityResponse #f 'DomainResource "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.identifier" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.status" #f)
    (schema-field 'purpose 1 '* (vector 'prim "code") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.purpose" #f)
    (schema-field 'patient 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.patient" #f)
    (schema-field 'event 0 '* (vector 'type 'CoverageEligibilityResponseEvent) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event" #f)
    (schema-field 'created 1 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.created" #f)
    (schema-field 'requestor 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.requestor" #f)
    (schema-field 'request 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.request" #f)
    (schema-field 'outcome 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.outcome" #f)
    (schema-field 'disposition 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.disposition" #f)
    (schema-field 'insurer 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurer" #f)
    (schema-field 'insurance 0 '* (vector 'type 'CoverageEligibilityResponseInsurance) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance" #f)
    (schema-field 'preAuthRef 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.preAuthRef" #f)
    (schema-field 'form 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.form" #f)
    (schema-field 'error 0 '* (vector 'type 'CoverageEligibilityResponseError) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error" #f)
    (schema-field 'servicedDate 0 1 (vector 'prim "date") 'serviced "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.serviced[x]" #f)
    (schema-field 'servicedPeriod 0 1 (vector 'type 'Period) 'serviced "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.serviced[x]" #f)
             ) #f #f))
(register-element! "CoverageEligibilityResponse.identifier" (fhir-spec (string->symbol "CoverageEligibilityResponse.identifier") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.identifier" 'element))
(register-element! "CoverageEligibilityResponse.status" (fhir-spec (string->symbol "CoverageEligibilityResponse.status") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.status" 'element))
(register-element! "CoverageEligibilityResponse.purpose" (fhir-spec (string->symbol "CoverageEligibilityResponse.purpose") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.purpose" 'element))
(register-element! "CoverageEligibilityResponse.patient" (fhir-spec (string->symbol "CoverageEligibilityResponse.patient") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.patient" 'element))
(register-element! "CoverageEligibilityResponse.event" (fhir-spec (string->symbol "CoverageEligibilityResponse.event") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event" 'element))
(register-element! "CoverageEligibilityResponse.created" (fhir-spec (string->symbol "CoverageEligibilityResponse.created") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.created" 'element))
(register-element! "CoverageEligibilityResponse.requestor" (fhir-spec (string->symbol "CoverageEligibilityResponse.requestor") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.requestor" 'element))
(register-element! "CoverageEligibilityResponse.request" (fhir-spec (string->symbol "CoverageEligibilityResponse.request") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.request" 'element))
(register-element! "CoverageEligibilityResponse.outcome" (fhir-spec (string->symbol "CoverageEligibilityResponse.outcome") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.outcome" 'element))
(register-element! "CoverageEligibilityResponse.disposition" (fhir-spec (string->symbol "CoverageEligibilityResponse.disposition") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.disposition" 'element))
(register-element! "CoverageEligibilityResponse.insurer" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurer") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurer" 'element))
(register-element! "CoverageEligibilityResponse.insurance" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance" 'element))
(register-element! "CoverageEligibilityResponse.preAuthRef" (fhir-spec (string->symbol "CoverageEligibilityResponse.preAuthRef") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.preAuthRef" 'element))
(register-element! "CoverageEligibilityResponse.form" (fhir-spec (string->symbol "CoverageEligibilityResponse.form") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.form" 'element))
(register-element! "CoverageEligibilityResponse.error" (fhir-spec (string->symbol "CoverageEligibilityResponse.error") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error" 'element))
(register-element! "CoverageEligibilityResponse.serviced[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.serviced[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.serviced[x]" 'element))
(register-element! "CoverageEligibilityResponse.serviced[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.serviced[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.serviced[x]" 'element))

(register-type! 'CoverageEligibilityResponseEvent (fhir-spec 'CoverageEligibilityResponseEvent "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event" 'type)
  #:schema (type-schema 'CoverageEligibilityResponseEvent #f 'BackboneElement "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event.type" #f)
    (schema-field 'whenDateTime 0 1 (vector 'prim "dateTime") 'when "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event.when[x]" #f)
    (schema-field 'whenPeriod 0 1 (vector 'type 'Period) 'when "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event.when[x]" #f)
             ) #f #f))
(register-element! "CoverageEligibilityResponse.event.type" (fhir-spec (string->symbol "CoverageEligibilityResponse.event.type") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event.type" 'element))
(register-element! "CoverageEligibilityResponse.event.when[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.event.when[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event.when[x]" 'element))
(register-element! "CoverageEligibilityResponse.event.when[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.event.when[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.event.when[x]" 'element))

(register-type! 'CoverageEligibilityResponseInsurance (fhir-spec 'CoverageEligibilityResponseInsurance "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance" 'type)
  #:schema (type-schema 'CoverageEligibilityResponseInsurance #f 'BackboneElement "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance"
             (list
    (schema-field 'coverage 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.coverage" #f)
    (schema-field 'inforce 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.inforce" #f)
    (schema-field 'benefitPeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.benefitPeriod" #f)
    (schema-field 'item 0 '* (vector 'type 'CoverageEligibilityResponseInsuranceItem) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item" #f)
             ) #f #f))
(register-element! "CoverageEligibilityResponse.insurance.coverage" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.coverage") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.coverage" 'element))
(register-element! "CoverageEligibilityResponse.insurance.inforce" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.inforce") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.inforce" 'element))
(register-element! "CoverageEligibilityResponse.insurance.benefitPeriod" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.benefitPeriod") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.benefitPeriod" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item" 'element))

(register-type! 'CoverageEligibilityResponseInsuranceItem (fhir-spec 'CoverageEligibilityResponseInsuranceItem "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item" 'type)
  #:schema (type-schema 'CoverageEligibilityResponseInsuranceItem #f 'BackboneElement "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item"
             (list
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.category" #f)
    (schema-field 'productOrService 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.productOrService" #f)
    (schema-field 'modifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.modifier" #f)
    (schema-field 'provider 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.provider" #f)
    (schema-field 'excluded 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.excluded" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.name" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.description" #f)
    (schema-field 'network 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.network" #f)
    (schema-field 'unit 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.unit" #f)
    (schema-field 'term 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.term" #f)
    (schema-field 'benefit 0 '* (vector 'type 'CoverageEligibilityResponseInsuranceItemBenefit) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit" #f)
    (schema-field 'authorizationRequired 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.authorizationRequired" #f)
    (schema-field 'authorizationSupporting 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.authorizationSupporting" #f)
    (schema-field 'authorizationUrl 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.authorizationUrl" #f)
             ) #f #f))
(register-element! "CoverageEligibilityResponse.insurance.item.category" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.category") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.category" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.productOrService" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.productOrService") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.productOrService" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.modifier" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.modifier") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.modifier" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.provider" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.provider") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.provider" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.excluded" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.excluded") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.excluded" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.name" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.name") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.name" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.description" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.description") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.description" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.network" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.network") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.network" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.unit" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.unit") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.unit" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.term" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.term") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.term" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.authorizationRequired" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.authorizationRequired") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.authorizationRequired" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.authorizationSupporting" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.authorizationSupporting") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.authorizationSupporting" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.authorizationUrl" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.authorizationUrl") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.authorizationUrl" 'element))

(register-type! 'CoverageEligibilityResponseInsuranceItemBenefit (fhir-spec 'CoverageEligibilityResponseInsuranceItemBenefit "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit" 'type)
  #:schema (type-schema 'CoverageEligibilityResponseInsuranceItemBenefit #f 'BackboneElement "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.type" #f)
    (schema-field 'allowedUnsignedInt 0 1 (vector 'prim "unsignedInt") 'allowed "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" #f)
    (schema-field 'allowedString 0 1 (vector 'prim "string") 'allowed "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" #f)
    (schema-field 'allowedMoney 0 1 (vector 'type 'Money) 'allowed "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" #f)
    (schema-field 'usedUnsignedInt 0 1 (vector 'prim "unsignedInt") 'used "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.used[x]" #f)
    (schema-field 'usedString 0 1 (vector 'prim "string") 'used "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.used[x]" #f)
    (schema-field 'usedMoney 0 1 (vector 'type 'Money) 'used "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.used[x]" #f)
             ) #f #f))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit.type" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit.type") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.type" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit.allowed[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit.allowed[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit.allowed[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.allowed[x]" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit.used[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit.used[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.used[x]" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit.used[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit.used[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.used[x]" 'element))
(register-element! "CoverageEligibilityResponse.insurance.item.benefit.used[x]" (fhir-spec (string->symbol "CoverageEligibilityResponse.insurance.item.benefit.used[x]") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.insurance.item.benefit.used[x]" 'element))

(register-type! 'CoverageEligibilityResponseError (fhir-spec 'CoverageEligibilityResponseError "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error" 'type)
  #:schema (type-schema 'CoverageEligibilityResponseError #f 'BackboneElement "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error.code" #f)
    (schema-field 'expression 0 '* (vector 'prim "string") #f "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error.expression" #f)
             ) #f #f))
(register-element! "CoverageEligibilityResponse.error.code" (fhir-spec (string->symbol "CoverageEligibilityResponse.error.code") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error.code" 'element))
(register-element! "CoverageEligibilityResponse.error.expression" (fhir-spec (string->symbol "CoverageEligibilityResponse.error.expression") "https://hl7.org/fhir/R5/coverageeligibilityresponse.html#CoverageEligibilityResponse.error.expression" 'element))

