#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'DeviceUsage (fhir-spec 'DeviceUsage "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage" 'type)
  #:schema (type-schema 'DeviceUsage #f 'DomainResource "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.basedOn" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.status" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.category" #f)
    (schema-field 'patient 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.patient" #f)
    (schema-field 'derivedFrom 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.derivedFrom" #f)
    (schema-field 'context 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.context" #f)
    (schema-field 'dateAsserted 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.dateAsserted" #f)
    (schema-field 'usageStatus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.usageStatus" #f)
    (schema-field 'usageReason 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.usageReason" #f)
    (schema-field 'adherence 0 1 (vector 'type 'DeviceUsageAdherence) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence" #f)
    (schema-field 'informationSource 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.informationSource" #f)
    (schema-field 'device 1 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.device" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.reason" #f)
    (schema-field 'bodySite 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.bodySite" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.note" #f)
    (schema-field 'timingTiming 0 1 (vector 'type 'Timing) 'timing "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.timing[x]" #f)
    (schema-field 'timingPeriod 0 1 (vector 'type 'Period) 'timing "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.timing[x]" #f)
    (schema-field 'timingDateTime 0 1 (vector 'prim "dateTime") 'timing "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.timing[x]" #f)
             ) #f #f))
(register-element! "DeviceUsage.identifier" (fhir-spec (string->symbol "DeviceUsage.identifier") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.identifier" 'element))
(register-element! "DeviceUsage.basedOn" (fhir-spec (string->symbol "DeviceUsage.basedOn") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.basedOn" 'element))
(register-element! "DeviceUsage.status" (fhir-spec (string->symbol "DeviceUsage.status") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.status" 'element))
(register-element! "DeviceUsage.category" (fhir-spec (string->symbol "DeviceUsage.category") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.category" 'element))
(register-element! "DeviceUsage.patient" (fhir-spec (string->symbol "DeviceUsage.patient") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.patient" 'element))
(register-element! "DeviceUsage.derivedFrom" (fhir-spec (string->symbol "DeviceUsage.derivedFrom") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.derivedFrom" 'element))
(register-element! "DeviceUsage.context" (fhir-spec (string->symbol "DeviceUsage.context") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.context" 'element))
(register-element! "DeviceUsage.dateAsserted" (fhir-spec (string->symbol "DeviceUsage.dateAsserted") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.dateAsserted" 'element))
(register-element! "DeviceUsage.usageStatus" (fhir-spec (string->symbol "DeviceUsage.usageStatus") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.usageStatus" 'element))
(register-element! "DeviceUsage.usageReason" (fhir-spec (string->symbol "DeviceUsage.usageReason") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.usageReason" 'element))
(register-element! "DeviceUsage.adherence" (fhir-spec (string->symbol "DeviceUsage.adherence") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence" 'element))
(register-element! "DeviceUsage.informationSource" (fhir-spec (string->symbol "DeviceUsage.informationSource") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.informationSource" 'element))
(register-element! "DeviceUsage.device" (fhir-spec (string->symbol "DeviceUsage.device") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.device" 'element))
(register-element! "DeviceUsage.reason" (fhir-spec (string->symbol "DeviceUsage.reason") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.reason" 'element))
(register-element! "DeviceUsage.bodySite" (fhir-spec (string->symbol "DeviceUsage.bodySite") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.bodySite" 'element))
(register-element! "DeviceUsage.note" (fhir-spec (string->symbol "DeviceUsage.note") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.note" 'element))
(register-element! "DeviceUsage.timing[x]" (fhir-spec (string->symbol "DeviceUsage.timing[x]") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.timing[x]" 'element))
(register-element! "DeviceUsage.timing[x]" (fhir-spec (string->symbol "DeviceUsage.timing[x]") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.timing[x]" 'element))
(register-element! "DeviceUsage.timing[x]" (fhir-spec (string->symbol "DeviceUsage.timing[x]") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.timing[x]" 'element))

(register-type! 'DeviceUsageAdherence (fhir-spec 'DeviceUsageAdherence "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence" 'type)
  #:schema (type-schema 'DeviceUsageAdherence #f 'BackboneElement "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence.code" #f)
    (schema-field 'reason 1 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence.reason" #f)
             ) #f #f))
(register-element! "DeviceUsage.adherence.code" (fhir-spec (string->symbol "DeviceUsage.adherence.code") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence.code" 'element))
(register-element! "DeviceUsage.adherence.reason" (fhir-spec (string->symbol "DeviceUsage.adherence.reason") "https://hl7.org/fhir/R5/deviceusage.html#DeviceUsage.adherence.reason" 'element))

