#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'DeviceDispense (fhir-spec 'DeviceDispense "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense" 'type)
  #:schema (type-schema 'DeviceDispense #f 'DomainResource "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.basedOn" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.statusReason" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.category" #f)
    (schema-field 'device 1 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.device" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.subject" #f)
    (schema-field 'receiver 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.receiver" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.encounter" #f)
    (schema-field 'supportingInformation 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.supportingInformation" #f)
    (schema-field 'performer 0 '* (vector 'type 'DeviceDispensePerformer) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.location" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.type" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.quantity" #f)
    (schema-field 'preparedDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.preparedDate" #f)
    (schema-field 'whenHandedOver 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.whenHandedOver" #f)
    (schema-field 'destination 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.destination" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.note" #f)
    (schema-field 'usageInstruction 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.usageInstruction" #f)
    (schema-field 'eventHistory 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.eventHistory" #f)
             ) #f #f))
(register-element! "DeviceDispense.identifier" (fhir-spec (string->symbol "DeviceDispense.identifier") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.identifier" 'element))
(register-element! "DeviceDispense.basedOn" (fhir-spec (string->symbol "DeviceDispense.basedOn") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.basedOn" 'element))
(register-element! "DeviceDispense.partOf" (fhir-spec (string->symbol "DeviceDispense.partOf") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.partOf" 'element))
(register-element! "DeviceDispense.status" (fhir-spec (string->symbol "DeviceDispense.status") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.status" 'element))
(register-element! "DeviceDispense.statusReason" (fhir-spec (string->symbol "DeviceDispense.statusReason") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.statusReason" 'element))
(register-element! "DeviceDispense.category" (fhir-spec (string->symbol "DeviceDispense.category") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.category" 'element))
(register-element! "DeviceDispense.device" (fhir-spec (string->symbol "DeviceDispense.device") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.device" 'element))
(register-element! "DeviceDispense.subject" (fhir-spec (string->symbol "DeviceDispense.subject") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.subject" 'element))
(register-element! "DeviceDispense.receiver" (fhir-spec (string->symbol "DeviceDispense.receiver") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.receiver" 'element))
(register-element! "DeviceDispense.encounter" (fhir-spec (string->symbol "DeviceDispense.encounter") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.encounter" 'element))
(register-element! "DeviceDispense.supportingInformation" (fhir-spec (string->symbol "DeviceDispense.supportingInformation") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.supportingInformation" 'element))
(register-element! "DeviceDispense.performer" (fhir-spec (string->symbol "DeviceDispense.performer") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer" 'element))
(register-element! "DeviceDispense.location" (fhir-spec (string->symbol "DeviceDispense.location") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.location" 'element))
(register-element! "DeviceDispense.type" (fhir-spec (string->symbol "DeviceDispense.type") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.type" 'element))
(register-element! "DeviceDispense.quantity" (fhir-spec (string->symbol "DeviceDispense.quantity") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.quantity" 'element))
(register-element! "DeviceDispense.preparedDate" (fhir-spec (string->symbol "DeviceDispense.preparedDate") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.preparedDate" 'element))
(register-element! "DeviceDispense.whenHandedOver" (fhir-spec (string->symbol "DeviceDispense.whenHandedOver") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.whenHandedOver" 'element))
(register-element! "DeviceDispense.destination" (fhir-spec (string->symbol "DeviceDispense.destination") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.destination" 'element))
(register-element! "DeviceDispense.note" (fhir-spec (string->symbol "DeviceDispense.note") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.note" 'element))
(register-element! "DeviceDispense.usageInstruction" (fhir-spec (string->symbol "DeviceDispense.usageInstruction") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.usageInstruction" 'element))
(register-element! "DeviceDispense.eventHistory" (fhir-spec (string->symbol "DeviceDispense.eventHistory") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.eventHistory" 'element))

(register-type! 'DeviceDispensePerformer (fhir-spec 'DeviceDispensePerformer "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer" 'type)
  #:schema (type-schema 'DeviceDispensePerformer #f 'BackboneElement "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer.actor" #f)
             ) #f #f))
(register-element! "DeviceDispense.performer.function" (fhir-spec (string->symbol "DeviceDispense.performer.function") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer.function" 'element))
(register-element! "DeviceDispense.performer.actor" (fhir-spec (string->symbol "DeviceDispense.performer.actor") "https://hl7.org/fhir/R5/devicedispense.html#DeviceDispense.performer.actor" 'element))

