#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Device (fhir-spec 'Device "https://hl7.org/fhir/R5/device.html#Device" 'type)
  #:schema (type-schema 'Device #f 'DomainResource "https://hl7.org/fhir/R5/device.html#Device"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/device.html#Device.identifier" #f)
    (schema-field 'displayName 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.displayName" #f)
    (schema-field 'definition 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/device.html#Device.definition" #f)
    (schema-field 'udiCarrier 0 '* (vector 'type 'DeviceUdiCarrier) #f "https://hl7.org/fhir/R5/device.html#Device.udiCarrier" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/device.html#Device.status" #f)
    (schema-field 'availabilityStatus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.availabilityStatus" #f)
    (schema-field 'biologicalSourceEvent 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/device.html#Device.biologicalSourceEvent" #f)
    (schema-field 'manufacturer 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.manufacturer" #f)
    (schema-field 'manufactureDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/device.html#Device.manufactureDate" #f)
    (schema-field 'expirationDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/device.html#Device.expirationDate" #f)
    (schema-field 'lotNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.lotNumber" #f)
    (schema-field 'serialNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.serialNumber" #f)
    (schema-field 'name 0 '* (vector 'type 'DeviceName) #f "https://hl7.org/fhir/R5/device.html#Device.name" #f)
    (schema-field 'modelNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.modelNumber" #f)
    (schema-field 'partNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.partNumber" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.category" #f)
    (schema-field 'type 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.type" #f)
    (schema-field 'version 0 '* (vector 'type 'DeviceVersion) #f "https://hl7.org/fhir/R5/device.html#Device.version" #f)
    (schema-field 'conformsTo 0 '* (vector 'type 'DeviceConformsTo) #f "https://hl7.org/fhir/R5/device.html#Device.conformsTo" #f)
    (schema-field 'property 0 '* (vector 'type 'DeviceProperty) #f "https://hl7.org/fhir/R5/device.html#Device.property" #f)
    (schema-field 'mode 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.mode" #f)
    (schema-field 'cycle 0 1 (vector 'type 'Count) #f "https://hl7.org/fhir/R5/device.html#Device.cycle" #f)
    (schema-field 'duration 0 1 (vector 'type 'Duration) #f "https://hl7.org/fhir/R5/device.html#Device.duration" #f)
    (schema-field 'owner 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/device.html#Device.owner" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactPoint) #f "https://hl7.org/fhir/R5/device.html#Device.contact" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/device.html#Device.location" #f)
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/device.html#Device.url" #f)
    (schema-field 'endpoint 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/device.html#Device.endpoint" #f)
    (schema-field 'gateway 0 '* (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/device.html#Device.gateway" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/device.html#Device.note" #f)
    (schema-field 'safety 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.safety" #f)
    (schema-field 'parent 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/device.html#Device.parent" #f)
             ) #f #f))
(register-element! "Device.identifier" (fhir-spec (string->symbol "Device.identifier") "https://hl7.org/fhir/R5/device.html#Device.identifier" 'element))
(register-element! "Device.displayName" (fhir-spec (string->symbol "Device.displayName") "https://hl7.org/fhir/R5/device.html#Device.displayName" 'element))
(register-element! "Device.definition" (fhir-spec (string->symbol "Device.definition") "https://hl7.org/fhir/R5/device.html#Device.definition" 'element))
(register-element! "Device.udiCarrier" (fhir-spec (string->symbol "Device.udiCarrier") "https://hl7.org/fhir/R5/device.html#Device.udiCarrier" 'element))
(register-element! "Device.status" (fhir-spec (string->symbol "Device.status") "https://hl7.org/fhir/R5/device.html#Device.status" 'element))
(register-element! "Device.availabilityStatus" (fhir-spec (string->symbol "Device.availabilityStatus") "https://hl7.org/fhir/R5/device.html#Device.availabilityStatus" 'element))
(register-element! "Device.biologicalSourceEvent" (fhir-spec (string->symbol "Device.biologicalSourceEvent") "https://hl7.org/fhir/R5/device.html#Device.biologicalSourceEvent" 'element))
(register-element! "Device.manufacturer" (fhir-spec (string->symbol "Device.manufacturer") "https://hl7.org/fhir/R5/device.html#Device.manufacturer" 'element))
(register-element! "Device.manufactureDate" (fhir-spec (string->symbol "Device.manufactureDate") "https://hl7.org/fhir/R5/device.html#Device.manufactureDate" 'element))
(register-element! "Device.expirationDate" (fhir-spec (string->symbol "Device.expirationDate") "https://hl7.org/fhir/R5/device.html#Device.expirationDate" 'element))
(register-element! "Device.lotNumber" (fhir-spec (string->symbol "Device.lotNumber") "https://hl7.org/fhir/R5/device.html#Device.lotNumber" 'element))
(register-element! "Device.serialNumber" (fhir-spec (string->symbol "Device.serialNumber") "https://hl7.org/fhir/R5/device.html#Device.serialNumber" 'element))
(register-element! "Device.name" (fhir-spec (string->symbol "Device.name") "https://hl7.org/fhir/R5/device.html#Device.name" 'element))
(register-element! "Device.modelNumber" (fhir-spec (string->symbol "Device.modelNumber") "https://hl7.org/fhir/R5/device.html#Device.modelNumber" 'element))
(register-element! "Device.partNumber" (fhir-spec (string->symbol "Device.partNumber") "https://hl7.org/fhir/R5/device.html#Device.partNumber" 'element))
(register-element! "Device.category" (fhir-spec (string->symbol "Device.category") "https://hl7.org/fhir/R5/device.html#Device.category" 'element))
(register-element! "Device.type" (fhir-spec (string->symbol "Device.type") "https://hl7.org/fhir/R5/device.html#Device.type" 'element))
(register-element! "Device.version" (fhir-spec (string->symbol "Device.version") "https://hl7.org/fhir/R5/device.html#Device.version" 'element))
(register-element! "Device.conformsTo" (fhir-spec (string->symbol "Device.conformsTo") "https://hl7.org/fhir/R5/device.html#Device.conformsTo" 'element))
(register-element! "Device.property" (fhir-spec (string->symbol "Device.property") "https://hl7.org/fhir/R5/device.html#Device.property" 'element))
(register-element! "Device.mode" (fhir-spec (string->symbol "Device.mode") "https://hl7.org/fhir/R5/device.html#Device.mode" 'element))
(register-element! "Device.cycle" (fhir-spec (string->symbol "Device.cycle") "https://hl7.org/fhir/R5/device.html#Device.cycle" 'element))
(register-element! "Device.duration" (fhir-spec (string->symbol "Device.duration") "https://hl7.org/fhir/R5/device.html#Device.duration" 'element))
(register-element! "Device.owner" (fhir-spec (string->symbol "Device.owner") "https://hl7.org/fhir/R5/device.html#Device.owner" 'element))
(register-element! "Device.contact" (fhir-spec (string->symbol "Device.contact") "https://hl7.org/fhir/R5/device.html#Device.contact" 'element))
(register-element! "Device.location" (fhir-spec (string->symbol "Device.location") "https://hl7.org/fhir/R5/device.html#Device.location" 'element))
(register-element! "Device.url" (fhir-spec (string->symbol "Device.url") "https://hl7.org/fhir/R5/device.html#Device.url" 'element))
(register-element! "Device.endpoint" (fhir-spec (string->symbol "Device.endpoint") "https://hl7.org/fhir/R5/device.html#Device.endpoint" 'element))
(register-element! "Device.gateway" (fhir-spec (string->symbol "Device.gateway") "https://hl7.org/fhir/R5/device.html#Device.gateway" 'element))
(register-element! "Device.note" (fhir-spec (string->symbol "Device.note") "https://hl7.org/fhir/R5/device.html#Device.note" 'element))
(register-element! "Device.safety" (fhir-spec (string->symbol "Device.safety") "https://hl7.org/fhir/R5/device.html#Device.safety" 'element))
(register-element! "Device.parent" (fhir-spec (string->symbol "Device.parent") "https://hl7.org/fhir/R5/device.html#Device.parent" 'element))

(register-type! 'DeviceUdiCarrier (fhir-spec 'DeviceUdiCarrier "https://hl7.org/fhir/R5/device.html#Device.udiCarrier" 'type)
  #:schema (type-schema 'DeviceUdiCarrier #f 'BackboneElement "https://hl7.org/fhir/R5/device.html#Device.udiCarrier"
             (list
    (schema-field 'deviceIdentifier 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.deviceIdentifier" #f)
    (schema-field 'issuer 1 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.issuer" #f)
    (schema-field 'jurisdiction 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.jurisdiction" #f)
    (schema-field 'carrierAIDC 0 1 (vector 'prim "base64Binary") #f "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.carrierAIDC" #f)
    (schema-field 'carrierHRF 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.carrierHRF" #f)
    (schema-field 'entryType 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.entryType" #f)
             ) #f #f))
(register-element! "Device.udiCarrier.deviceIdentifier" (fhir-spec (string->symbol "Device.udiCarrier.deviceIdentifier") "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.deviceIdentifier" 'element))
(register-element! "Device.udiCarrier.issuer" (fhir-spec (string->symbol "Device.udiCarrier.issuer") "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.issuer" 'element))
(register-element! "Device.udiCarrier.jurisdiction" (fhir-spec (string->symbol "Device.udiCarrier.jurisdiction") "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.jurisdiction" 'element))
(register-element! "Device.udiCarrier.carrierAIDC" (fhir-spec (string->symbol "Device.udiCarrier.carrierAIDC") "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.carrierAIDC" 'element))
(register-element! "Device.udiCarrier.carrierHRF" (fhir-spec (string->symbol "Device.udiCarrier.carrierHRF") "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.carrierHRF" 'element))
(register-element! "Device.udiCarrier.entryType" (fhir-spec (string->symbol "Device.udiCarrier.entryType") "https://hl7.org/fhir/R5/device.html#Device.udiCarrier.entryType" 'element))

(register-type! 'DeviceName (fhir-spec 'DeviceName "https://hl7.org/fhir/R5/device.html#Device.name" 'type)
  #:schema (type-schema 'DeviceName #f 'BackboneElement "https://hl7.org/fhir/R5/device.html#Device.name"
             (list
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.name.value" #f)
    (schema-field 'type 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/device.html#Device.name.type" #f)
    (schema-field 'display 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/device.html#Device.name.display" #f)
             ) #f #f))
(register-element! "Device.name.value" (fhir-spec (string->symbol "Device.name.value") "https://hl7.org/fhir/R5/device.html#Device.name.value" 'element))
(register-element! "Device.name.type" (fhir-spec (string->symbol "Device.name.type") "https://hl7.org/fhir/R5/device.html#Device.name.type" 'element))
(register-element! "Device.name.display" (fhir-spec (string->symbol "Device.name.display") "https://hl7.org/fhir/R5/device.html#Device.name.display" 'element))

(register-type! 'DeviceVersion (fhir-spec 'DeviceVersion "https://hl7.org/fhir/R5/device.html#Device.version" 'type)
  #:schema (type-schema 'DeviceVersion #f 'BackboneElement "https://hl7.org/fhir/R5/device.html#Device.version"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.version.type" #f)
    (schema-field 'component 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/device.html#Device.version.component" #f)
    (schema-field 'installDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/device.html#Device.version.installDate" #f)
    (schema-field 'value 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.version.value" #f)
             ) #f #f))
(register-element! "Device.version.type" (fhir-spec (string->symbol "Device.version.type") "https://hl7.org/fhir/R5/device.html#Device.version.type" 'element))
(register-element! "Device.version.component" (fhir-spec (string->symbol "Device.version.component") "https://hl7.org/fhir/R5/device.html#Device.version.component" 'element))
(register-element! "Device.version.installDate" (fhir-spec (string->symbol "Device.version.installDate") "https://hl7.org/fhir/R5/device.html#Device.version.installDate" 'element))
(register-element! "Device.version.value" (fhir-spec (string->symbol "Device.version.value") "https://hl7.org/fhir/R5/device.html#Device.version.value" 'element))

(register-type! 'DeviceConformsTo (fhir-spec 'DeviceConformsTo "https://hl7.org/fhir/R5/device.html#Device.conformsTo" 'type)
  #:schema (type-schema 'DeviceConformsTo #f 'BackboneElement "https://hl7.org/fhir/R5/device.html#Device.conformsTo"
             (list
    (schema-field 'category 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.conformsTo.category" #f)
    (schema-field 'specification 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.conformsTo.specification" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/device.html#Device.conformsTo.version" #f)
             ) #f #f))
(register-element! "Device.conformsTo.category" (fhir-spec (string->symbol "Device.conformsTo.category") "https://hl7.org/fhir/R5/device.html#Device.conformsTo.category" 'element))
(register-element! "Device.conformsTo.specification" (fhir-spec (string->symbol "Device.conformsTo.specification") "https://hl7.org/fhir/R5/device.html#Device.conformsTo.specification" 'element))
(register-element! "Device.conformsTo.version" (fhir-spec (string->symbol "Device.conformsTo.version") "https://hl7.org/fhir/R5/device.html#Device.conformsTo.version" 'element))

(register-type! 'DeviceProperty (fhir-spec 'DeviceProperty "https://hl7.org/fhir/R5/device.html#Device.property" 'type)
  #:schema (type-schema 'DeviceProperty #f 'BackboneElement "https://hl7.org/fhir/R5/device.html#Device.property"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/device.html#Device.property.type" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" #f)
             ) #f #f))
(register-element! "Device.property.type" (fhir-spec (string->symbol "Device.property.type") "https://hl7.org/fhir/R5/device.html#Device.property.type" 'element))
(register-element! "Device.property.value[x]" (fhir-spec (string->symbol "Device.property.value[x]") "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" 'element))
(register-element! "Device.property.value[x]" (fhir-spec (string->symbol "Device.property.value[x]") "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" 'element))
(register-element! "Device.property.value[x]" (fhir-spec (string->symbol "Device.property.value[x]") "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" 'element))
(register-element! "Device.property.value[x]" (fhir-spec (string->symbol "Device.property.value[x]") "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" 'element))
(register-element! "Device.property.value[x]" (fhir-spec (string->symbol "Device.property.value[x]") "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" 'element))
(register-element! "Device.property.value[x]" (fhir-spec (string->symbol "Device.property.value[x]") "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" 'element))
(register-element! "Device.property.value[x]" (fhir-spec (string->symbol "Device.property.value[x]") "https://hl7.org/fhir/R5/device.html#Device.property.value[x]" 'element))

