#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'EvidenceVariable (fhir-spec 'EvidenceVariable "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable" 'type)
  #:schema (type-schema 'EvidenceVariable #f 'DomainResource "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.url" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.title" #f)
    (schema-field 'shortTitle 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.shortTitle" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.note" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.useContext" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.effectivePeriod" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.endorser" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.relatedArtifact" #f)
    (schema-field 'actual 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.actual" #f)
    (schema-field 'characteristic 0 '* (vector 'type 'EvidenceVariableCharacteristic) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic" #f)
    (schema-field 'handling 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.handling" #f)
    (schema-field 'category 0 '* (vector 'type 'EvidenceVariableCategory) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "EvidenceVariable.url" (fhir-spec (string->symbol "EvidenceVariable.url") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.url" 'element))
(register-element! "EvidenceVariable.identifier" (fhir-spec (string->symbol "EvidenceVariable.identifier") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.identifier" 'element))
(register-element! "EvidenceVariable.version" (fhir-spec (string->symbol "EvidenceVariable.version") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.version" 'element))
(register-element! "EvidenceVariable.name" (fhir-spec (string->symbol "EvidenceVariable.name") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.name" 'element))
(register-element! "EvidenceVariable.title" (fhir-spec (string->symbol "EvidenceVariable.title") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.title" 'element))
(register-element! "EvidenceVariable.shortTitle" (fhir-spec (string->symbol "EvidenceVariable.shortTitle") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.shortTitle" 'element))
(register-element! "EvidenceVariable.status" (fhir-spec (string->symbol "EvidenceVariable.status") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.status" 'element))
(register-element! "EvidenceVariable.experimental" (fhir-spec (string->symbol "EvidenceVariable.experimental") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.experimental" 'element))
(register-element! "EvidenceVariable.date" (fhir-spec (string->symbol "EvidenceVariable.date") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.date" 'element))
(register-element! "EvidenceVariable.publisher" (fhir-spec (string->symbol "EvidenceVariable.publisher") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.publisher" 'element))
(register-element! "EvidenceVariable.contact" (fhir-spec (string->symbol "EvidenceVariable.contact") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.contact" 'element))
(register-element! "EvidenceVariable.description" (fhir-spec (string->symbol "EvidenceVariable.description") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.description" 'element))
(register-element! "EvidenceVariable.note" (fhir-spec (string->symbol "EvidenceVariable.note") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.note" 'element))
(register-element! "EvidenceVariable.useContext" (fhir-spec (string->symbol "EvidenceVariable.useContext") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.useContext" 'element))
(register-element! "EvidenceVariable.purpose" (fhir-spec (string->symbol "EvidenceVariable.purpose") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.purpose" 'element))
(register-element! "EvidenceVariable.copyright" (fhir-spec (string->symbol "EvidenceVariable.copyright") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.copyright" 'element))
(register-element! "EvidenceVariable.copyrightLabel" (fhir-spec (string->symbol "EvidenceVariable.copyrightLabel") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.copyrightLabel" 'element))
(register-element! "EvidenceVariable.approvalDate" (fhir-spec (string->symbol "EvidenceVariable.approvalDate") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.approvalDate" 'element))
(register-element! "EvidenceVariable.lastReviewDate" (fhir-spec (string->symbol "EvidenceVariable.lastReviewDate") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.lastReviewDate" 'element))
(register-element! "EvidenceVariable.effectivePeriod" (fhir-spec (string->symbol "EvidenceVariable.effectivePeriod") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.effectivePeriod" 'element))
(register-element! "EvidenceVariable.author" (fhir-spec (string->symbol "EvidenceVariable.author") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.author" 'element))
(register-element! "EvidenceVariable.editor" (fhir-spec (string->symbol "EvidenceVariable.editor") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.editor" 'element))
(register-element! "EvidenceVariable.reviewer" (fhir-spec (string->symbol "EvidenceVariable.reviewer") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.reviewer" 'element))
(register-element! "EvidenceVariable.endorser" (fhir-spec (string->symbol "EvidenceVariable.endorser") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.endorser" 'element))
(register-element! "EvidenceVariable.relatedArtifact" (fhir-spec (string->symbol "EvidenceVariable.relatedArtifact") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.relatedArtifact" 'element))
(register-element! "EvidenceVariable.actual" (fhir-spec (string->symbol "EvidenceVariable.actual") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.actual" 'element))
(register-element! "EvidenceVariable.characteristic" (fhir-spec (string->symbol "EvidenceVariable.characteristic") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic" 'element))
(register-element! "EvidenceVariable.handling" (fhir-spec (string->symbol "EvidenceVariable.handling") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.handling" 'element))
(register-element! "EvidenceVariable.category" (fhir-spec (string->symbol "EvidenceVariable.category") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category" 'element))
(register-element! "EvidenceVariable.versionAlgorithm[x]" (fhir-spec (string->symbol "EvidenceVariable.versionAlgorithm[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.versionAlgorithm[x]" 'element))
(register-element! "EvidenceVariable.versionAlgorithm[x]" (fhir-spec (string->symbol "EvidenceVariable.versionAlgorithm[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.versionAlgorithm[x]" 'element))

(register-type! 'EvidenceVariableCharacteristic (fhir-spec 'EvidenceVariableCharacteristic "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic" 'type)
  #:schema (type-schema 'EvidenceVariableCharacteristic #f 'BackboneElement "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic"
             (list
    (schema-field 'linkId 0 1 (vector 'prim "id") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.linkId" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.note" #f)
    (schema-field 'exclude 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.exclude" #f)
    (schema-field 'definitionReference 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionReference" #f)
    (schema-field 'definitionCanonical 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionCanonical" #f)
    (schema-field 'definitionCodeableConcept 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionCodeableConcept" #f)
    (schema-field 'definitionExpression 0 1 (vector 'type 'Expression) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionExpression" #f)
    (schema-field 'definitionId 0 1 (vector 'prim "id") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionId" #f)
    (schema-field 'definitionByTypeAndValue 0 1 (vector 'type 'EvidenceVariableCharacteristicDefinitionByTypeAndValue) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue" #f)
    (schema-field 'definitionByCombination 0 1 (vector 'type 'EvidenceVariableCharacteristicDefinitionByCombination) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination" #f)
    (schema-field 'timeFromEvent 0 '* (vector 'type 'EvidenceVariableCharacteristicTimeFromEvent) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent" #f)
    (schema-field 'instancesQuantity 0 1 (vector 'type 'Quantity) 'instances "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.instances[x]" #f)
    (schema-field 'instancesRange 0 1 (vector 'type 'Range) 'instances "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.instances[x]" #f)
    (schema-field 'durationQuantity 0 1 (vector 'type 'Quantity) 'duration "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.duration[x]" #f)
    (schema-field 'durationRange 0 1 (vector 'type 'Range) 'duration "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.duration[x]" #f)
             ) #f #f))
(register-element! "EvidenceVariable.characteristic.linkId" (fhir-spec (string->symbol "EvidenceVariable.characteristic.linkId") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.linkId" 'element))
(register-element! "EvidenceVariable.characteristic.description" (fhir-spec (string->symbol "EvidenceVariable.characteristic.description") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.description" 'element))
(register-element! "EvidenceVariable.characteristic.note" (fhir-spec (string->symbol "EvidenceVariable.characteristic.note") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.note" 'element))
(register-element! "EvidenceVariable.characteristic.exclude" (fhir-spec (string->symbol "EvidenceVariable.characteristic.exclude") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.exclude" 'element))
(register-element! "EvidenceVariable.characteristic.definitionReference" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionReference") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionReference" 'element))
(register-element! "EvidenceVariable.characteristic.definitionCanonical" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionCanonical") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionCanonical" 'element))
(register-element! "EvidenceVariable.characteristic.definitionCodeableConcept" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionCodeableConcept") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionCodeableConcept" 'element))
(register-element! "EvidenceVariable.characteristic.definitionExpression" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionExpression") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionExpression" 'element))
(register-element! "EvidenceVariable.characteristic.definitionId" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionId") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionId" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByCombination" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByCombination") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent" 'element))
(register-element! "EvidenceVariable.characteristic.instances[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.instances[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.instances[x]" 'element))
(register-element! "EvidenceVariable.characteristic.instances[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.instances[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.instances[x]" 'element))
(register-element! "EvidenceVariable.characteristic.duration[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.duration[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.duration[x]" 'element))
(register-element! "EvidenceVariable.characteristic.duration[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.duration[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.duration[x]" 'element))

(register-type! 'EvidenceVariableCharacteristicDefinitionByTypeAndValue (fhir-spec 'EvidenceVariableCharacteristicDefinitionByTypeAndValue "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue" 'type)
  #:schema (type-schema 'EvidenceVariableCharacteristicDefinitionByTypeAndValue #f 'BackboneElement "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.type" #f)
    (schema-field 'method 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.method" #f)
    (schema-field 'device 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.device" #f)
    (schema-field 'offset 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.offset" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" #f)
             ) #f #f))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.type" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.type") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.type" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.method" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.method") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.method" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.device" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.device") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.device" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.offset" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.offset") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.offset" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByTypeAndValue.value[x]" 'element))

(register-type! 'EvidenceVariableCharacteristicDefinitionByCombination (fhir-spec 'EvidenceVariableCharacteristicDefinitionByCombination "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination" 'type)
  #:schema (type-schema 'EvidenceVariableCharacteristicDefinitionByCombination #f 'BackboneElement "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination.code" #f)
    (schema-field 'threshold 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination.threshold" #f)
    (schema-field 'characteristic 1 '* (vector 'type 'EvidenceVariableCharacteristic) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination.characteristic" #f)
             ) #f #f))
(register-element! "EvidenceVariable.characteristic.definitionByCombination.code" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByCombination.code") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination.code" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByCombination.threshold" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByCombination.threshold") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination.threshold" 'element))
(register-element! "EvidenceVariable.characteristic.definitionByCombination.characteristic" (fhir-spec (string->symbol "EvidenceVariable.characteristic.definitionByCombination.characteristic") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.definitionByCombination.characteristic" 'element))

(register-type! 'EvidenceVariableCharacteristicTimeFromEvent (fhir-spec 'EvidenceVariableCharacteristicTimeFromEvent "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent" 'type)
  #:schema (type-schema 'EvidenceVariableCharacteristicTimeFromEvent #f 'BackboneElement "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent"
             (list
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.description" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.note" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.quantity" #f)
    (schema-field 'range 0 1 (vector 'type 'Range) #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.range" #f)
    (schema-field 'eventCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'event "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" #f)
    (schema-field 'eventReference 0 1 (vector 'type 'Reference) 'event "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" #f)
    (schema-field 'eventDateTime 0 1 (vector 'prim "dateTime") 'event "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" #f)
    (schema-field 'eventId 0 1 (vector 'prim "id") 'event "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" #f)
             ) #f #f))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.description" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.description") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.description" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.note" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.note") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.note" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.quantity" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.quantity") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.quantity" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.range" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.range") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.range" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.event[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.event[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.event[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.event[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.event[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.event[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" 'element))
(register-element! "EvidenceVariable.characteristic.timeFromEvent.event[x]" (fhir-spec (string->symbol "EvidenceVariable.characteristic.timeFromEvent.event[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.characteristic.timeFromEvent.event[x]" 'element))

(register-type! 'EvidenceVariableCategory (fhir-spec 'EvidenceVariableCategory "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category" 'type)
  #:schema (type-schema 'EvidenceVariableCategory #f 'BackboneElement "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category"
             (list
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.name" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.value[x]" #f)
             ) #f #f))
(register-element! "EvidenceVariable.category.name" (fhir-spec (string->symbol "EvidenceVariable.category.name") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.name" 'element))
(register-element! "EvidenceVariable.category.value[x]" (fhir-spec (string->symbol "EvidenceVariable.category.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.value[x]" 'element))
(register-element! "EvidenceVariable.category.value[x]" (fhir-spec (string->symbol "EvidenceVariable.category.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.value[x]" 'element))
(register-element! "EvidenceVariable.category.value[x]" (fhir-spec (string->symbol "EvidenceVariable.category.value[x]") "https://hl7.org/fhir/R5/evidencevariable.html#EvidenceVariable.category.value[x]" 'element))

