#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'EvidenceReport (fhir-spec 'EvidenceReport "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport" 'type)
  #:schema (type-schema 'EvidenceReport #f 'DomainResource "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.url" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.status" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.useContext" #f)
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.identifier" #f)
    (schema-field 'relatedIdentifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatedIdentifier" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.type" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.note" #f)
    (schema-field 'relatedArtifact 0 '* (vector 'type 'RelatedArtifact) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatedArtifact" #f)
    (schema-field 'subject 1 1 (vector 'type 'EvidenceReportSubject) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.contact" #f)
    (schema-field 'author 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.author" #f)
    (schema-field 'editor 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.editor" #f)
    (schema-field 'reviewer 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.reviewer" #f)
    (schema-field 'endorser 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.endorser" #f)
    (schema-field 'relatesTo 0 '* (vector 'type 'EvidenceReportRelatesTo) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo" #f)
    (schema-field 'section 0 '* (vector 'type 'EvidenceReportSection) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section" #f)
    (schema-field 'citeAsReference 0 1 (vector 'type 'Reference) 'citeAs "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.citeAs[x]" #f)
    (schema-field 'citeAsMarkdown 0 1 (vector 'prim "markdown") 'citeAs "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.citeAs[x]" #f)
             ) #f #f))
(register-element! "EvidenceReport.url" (fhir-spec (string->symbol "EvidenceReport.url") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.url" 'element))
(register-element! "EvidenceReport.status" (fhir-spec (string->symbol "EvidenceReport.status") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.status" 'element))
(register-element! "EvidenceReport.useContext" (fhir-spec (string->symbol "EvidenceReport.useContext") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.useContext" 'element))
(register-element! "EvidenceReport.identifier" (fhir-spec (string->symbol "EvidenceReport.identifier") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.identifier" 'element))
(register-element! "EvidenceReport.relatedIdentifier" (fhir-spec (string->symbol "EvidenceReport.relatedIdentifier") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatedIdentifier" 'element))
(register-element! "EvidenceReport.type" (fhir-spec (string->symbol "EvidenceReport.type") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.type" 'element))
(register-element! "EvidenceReport.note" (fhir-spec (string->symbol "EvidenceReport.note") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.note" 'element))
(register-element! "EvidenceReport.relatedArtifact" (fhir-spec (string->symbol "EvidenceReport.relatedArtifact") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatedArtifact" 'element))
(register-element! "EvidenceReport.subject" (fhir-spec (string->symbol "EvidenceReport.subject") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject" 'element))
(register-element! "EvidenceReport.publisher" (fhir-spec (string->symbol "EvidenceReport.publisher") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.publisher" 'element))
(register-element! "EvidenceReport.contact" (fhir-spec (string->symbol "EvidenceReport.contact") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.contact" 'element))
(register-element! "EvidenceReport.author" (fhir-spec (string->symbol "EvidenceReport.author") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.author" 'element))
(register-element! "EvidenceReport.editor" (fhir-spec (string->symbol "EvidenceReport.editor") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.editor" 'element))
(register-element! "EvidenceReport.reviewer" (fhir-spec (string->symbol "EvidenceReport.reviewer") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.reviewer" 'element))
(register-element! "EvidenceReport.endorser" (fhir-spec (string->symbol "EvidenceReport.endorser") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.endorser" 'element))
(register-element! "EvidenceReport.relatesTo" (fhir-spec (string->symbol "EvidenceReport.relatesTo") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo" 'element))
(register-element! "EvidenceReport.section" (fhir-spec (string->symbol "EvidenceReport.section") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section" 'element))
(register-element! "EvidenceReport.citeAs[x]" (fhir-spec (string->symbol "EvidenceReport.citeAs[x]") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.citeAs[x]" 'element))
(register-element! "EvidenceReport.citeAs[x]" (fhir-spec (string->symbol "EvidenceReport.citeAs[x]") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.citeAs[x]" 'element))

(register-type! 'EvidenceReportSubject (fhir-spec 'EvidenceReportSubject "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject" 'type)
  #:schema (type-schema 'EvidenceReportSubject #f 'BackboneElement "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject"
             (list
    (schema-field 'characteristic 0 '* (vector 'type 'EvidenceReportSubjectCharacteristic) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.note" #f)
             ) #f #f))
(register-element! "EvidenceReport.subject.characteristic" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic" 'element))
(register-element! "EvidenceReport.subject.note" (fhir-spec (string->symbol "EvidenceReport.subject.note") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.note" 'element))

(register-type! 'EvidenceReportSubjectCharacteristic (fhir-spec 'EvidenceReportSubjectCharacteristic "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic" 'type)
  #:schema (type-schema 'EvidenceReportSubjectCharacteristic #f 'BackboneElement "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.code" #f)
    (schema-field 'exclude 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.exclude" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.period" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" #f)
             ) #f #f))
(register-element! "EvidenceReport.subject.characteristic.code" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.code") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.code" 'element))
(register-element! "EvidenceReport.subject.characteristic.exclude" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.exclude") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.exclude" 'element))
(register-element! "EvidenceReport.subject.characteristic.period" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.period") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.period" 'element))
(register-element! "EvidenceReport.subject.characteristic.value[x]" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.value[x]") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" 'element))
(register-element! "EvidenceReport.subject.characteristic.value[x]" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.value[x]") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" 'element))
(register-element! "EvidenceReport.subject.characteristic.value[x]" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.value[x]") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" 'element))
(register-element! "EvidenceReport.subject.characteristic.value[x]" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.value[x]") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" 'element))
(register-element! "EvidenceReport.subject.characteristic.value[x]" (fhir-spec (string->symbol "EvidenceReport.subject.characteristic.value[x]") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.subject.characteristic.value[x]" 'element))

(register-type! 'EvidenceReportRelatesTo (fhir-spec 'EvidenceReportRelatesTo "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo" 'type)
  #:schema (type-schema 'EvidenceReportRelatesTo #f 'BackboneElement "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo"
             (list
    (schema-field 'code 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.code" #f)
    (schema-field 'target 1 1 (vector 'type 'EvidenceReportRelatesToTarget) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target" #f)
             ) #f #f))
(register-element! "EvidenceReport.relatesTo.code" (fhir-spec (string->symbol "EvidenceReport.relatesTo.code") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.code" 'element))
(register-element! "EvidenceReport.relatesTo.target" (fhir-spec (string->symbol "EvidenceReport.relatesTo.target") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target" 'element))

(register-type! 'EvidenceReportRelatesToTarget (fhir-spec 'EvidenceReportRelatesToTarget "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target" 'type)
  #:schema (type-schema 'EvidenceReportRelatesToTarget #f 'BackboneElement "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.url" #f)
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.identifier" #f)
    (schema-field 'display 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.display" #f)
    (schema-field 'resource 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.resource" #f)
             ) #f #f))
(register-element! "EvidenceReport.relatesTo.target.url" (fhir-spec (string->symbol "EvidenceReport.relatesTo.target.url") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.url" 'element))
(register-element! "EvidenceReport.relatesTo.target.identifier" (fhir-spec (string->symbol "EvidenceReport.relatesTo.target.identifier") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.identifier" 'element))
(register-element! "EvidenceReport.relatesTo.target.display" (fhir-spec (string->symbol "EvidenceReport.relatesTo.target.display") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.display" 'element))
(register-element! "EvidenceReport.relatesTo.target.resource" (fhir-spec (string->symbol "EvidenceReport.relatesTo.target.resource") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.relatesTo.target.resource" 'element))

(register-type! 'EvidenceReportSection (fhir-spec 'EvidenceReportSection "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section" 'type)
  #:schema (type-schema 'EvidenceReportSection #f 'BackboneElement "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section"
             (list
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.title" #f)
    (schema-field 'focus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.focus" #f)
    (schema-field 'focusReference 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.focusReference" #f)
    (schema-field 'author 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.author" #f)
    (schema-field 'text 0 1 (vector 'type 'Narrative) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.text" #f)
    (schema-field 'mode 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.mode" #f)
    (schema-field 'orderedBy 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.orderedBy" #f)
    (schema-field 'entryClassifier 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.entryClassifier" #f)
    (schema-field 'entryReference 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.entryReference" #f)
    (schema-field 'entryQuantity 0 '* (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.entryQuantity" #f)
    (schema-field 'emptyReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.emptyReason" #f)
    (schema-field 'section 0 '* (vector 'type 'EvidenceReportSection) #f "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.section" #f)
             ) #f #f))
(register-element! "EvidenceReport.section.title" (fhir-spec (string->symbol "EvidenceReport.section.title") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.title" 'element))
(register-element! "EvidenceReport.section.focus" (fhir-spec (string->symbol "EvidenceReport.section.focus") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.focus" 'element))
(register-element! "EvidenceReport.section.focusReference" (fhir-spec (string->symbol "EvidenceReport.section.focusReference") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.focusReference" 'element))
(register-element! "EvidenceReport.section.author" (fhir-spec (string->symbol "EvidenceReport.section.author") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.author" 'element))
(register-element! "EvidenceReport.section.text" (fhir-spec (string->symbol "EvidenceReport.section.text") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.text" 'element))
(register-element! "EvidenceReport.section.mode" (fhir-spec (string->symbol "EvidenceReport.section.mode") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.mode" 'element))
(register-element! "EvidenceReport.section.orderedBy" (fhir-spec (string->symbol "EvidenceReport.section.orderedBy") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.orderedBy" 'element))
(register-element! "EvidenceReport.section.entryClassifier" (fhir-spec (string->symbol "EvidenceReport.section.entryClassifier") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.entryClassifier" 'element))
(register-element! "EvidenceReport.section.entryReference" (fhir-spec (string->symbol "EvidenceReport.section.entryReference") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.entryReference" 'element))
(register-element! "EvidenceReport.section.entryQuantity" (fhir-spec (string->symbol "EvidenceReport.section.entryQuantity") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.entryQuantity" 'element))
(register-element! "EvidenceReport.section.emptyReason" (fhir-spec (string->symbol "EvidenceReport.section.emptyReason") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.emptyReason" 'element))
(register-element! "EvidenceReport.section.section" (fhir-spec (string->symbol "EvidenceReport.section.section") "https://hl7.org/fhir/R5/evidencereport.html#EvidenceReport.section.section" 'element))

