#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'FamilyMemberHistory (fhir-spec 'FamilyMemberHistory "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory" 'type)
  #:schema (type-schema 'FamilyMemberHistory #f 'DomainResource "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.identifier" #f)
    (schema-field 'instantiatesCanonical 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 '* (vector 'prim "uri") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.instantiatesUri" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.status" #f)
    (schema-field 'dataAbsentReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.dataAbsentReason" #f)
    (schema-field 'patient 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.patient" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.date" #f)
    (schema-field 'participant 0 '* (vector 'type 'FamilyMemberHistoryParticipant) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.name" #f)
    (schema-field 'relationship 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.relationship" #f)
    (schema-field 'sex 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.sex" #f)
    (schema-field 'estimatedAge 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.estimatedAge" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.reason" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.note" #f)
    (schema-field 'condition 0 '* (vector 'type 'FamilyMemberHistoryCondition) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition" #f)
    (schema-field 'procedure 0 '* (vector 'type 'FamilyMemberHistoryProcedure) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure" #f)
    (schema-field 'bornPeriod 0 1 (vector 'type 'Period) 'born "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.born[x]" #f)
    (schema-field 'bornDate 0 1 (vector 'prim "date") 'born "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.born[x]" #f)
    (schema-field 'bornString 0 1 (vector 'prim "string") 'born "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.born[x]" #f)
    (schema-field 'ageAge 0 1 (vector 'type 'Age) 'age "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.age[x]" #f)
    (schema-field 'ageRange 0 1 (vector 'type 'Range) 'age "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.age[x]" #f)
    (schema-field 'ageString 0 1 (vector 'prim "string") 'age "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.age[x]" #f)
    (schema-field 'deceasedBoolean 0 1 (vector 'prim "boolean") 'deceased "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" #f)
    (schema-field 'deceasedAge 0 1 (vector 'type 'Age) 'deceased "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" #f)
    (schema-field 'deceasedRange 0 1 (vector 'type 'Range) 'deceased "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" #f)
    (schema-field 'deceasedDate 0 1 (vector 'prim "date") 'deceased "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" #f)
    (schema-field 'deceasedString 0 1 (vector 'prim "string") 'deceased "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" #f)
             ) #f #f))
(register-element! "FamilyMemberHistory.identifier" (fhir-spec (string->symbol "FamilyMemberHistory.identifier") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.identifier" 'element))
(register-element! "FamilyMemberHistory.instantiatesCanonical" (fhir-spec (string->symbol "FamilyMemberHistory.instantiatesCanonical") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.instantiatesCanonical" 'element))
(register-element! "FamilyMemberHistory.instantiatesUri" (fhir-spec (string->symbol "FamilyMemberHistory.instantiatesUri") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.instantiatesUri" 'element))
(register-element! "FamilyMemberHistory.status" (fhir-spec (string->symbol "FamilyMemberHistory.status") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.status" 'element))
(register-element! "FamilyMemberHistory.dataAbsentReason" (fhir-spec (string->symbol "FamilyMemberHistory.dataAbsentReason") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.dataAbsentReason" 'element))
(register-element! "FamilyMemberHistory.patient" (fhir-spec (string->symbol "FamilyMemberHistory.patient") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.patient" 'element))
(register-element! "FamilyMemberHistory.date" (fhir-spec (string->symbol "FamilyMemberHistory.date") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.date" 'element))
(register-element! "FamilyMemberHistory.participant" (fhir-spec (string->symbol "FamilyMemberHistory.participant") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant" 'element))
(register-element! "FamilyMemberHistory.name" (fhir-spec (string->symbol "FamilyMemberHistory.name") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.name" 'element))
(register-element! "FamilyMemberHistory.relationship" (fhir-spec (string->symbol "FamilyMemberHistory.relationship") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.relationship" 'element))
(register-element! "FamilyMemberHistory.sex" (fhir-spec (string->symbol "FamilyMemberHistory.sex") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.sex" 'element))
(register-element! "FamilyMemberHistory.estimatedAge" (fhir-spec (string->symbol "FamilyMemberHistory.estimatedAge") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.estimatedAge" 'element))
(register-element! "FamilyMemberHistory.reason" (fhir-spec (string->symbol "FamilyMemberHistory.reason") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.reason" 'element))
(register-element! "FamilyMemberHistory.note" (fhir-spec (string->symbol "FamilyMemberHistory.note") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.note" 'element))
(register-element! "FamilyMemberHistory.condition" (fhir-spec (string->symbol "FamilyMemberHistory.condition") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition" 'element))
(register-element! "FamilyMemberHistory.procedure" (fhir-spec (string->symbol "FamilyMemberHistory.procedure") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure" 'element))
(register-element! "FamilyMemberHistory.born[x]" (fhir-spec (string->symbol "FamilyMemberHistory.born[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.born[x]" 'element))
(register-element! "FamilyMemberHistory.born[x]" (fhir-spec (string->symbol "FamilyMemberHistory.born[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.born[x]" 'element))
(register-element! "FamilyMemberHistory.born[x]" (fhir-spec (string->symbol "FamilyMemberHistory.born[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.born[x]" 'element))
(register-element! "FamilyMemberHistory.age[x]" (fhir-spec (string->symbol "FamilyMemberHistory.age[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.age[x]" 'element))
(register-element! "FamilyMemberHistory.age[x]" (fhir-spec (string->symbol "FamilyMemberHistory.age[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.age[x]" 'element))
(register-element! "FamilyMemberHistory.age[x]" (fhir-spec (string->symbol "FamilyMemberHistory.age[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.age[x]" 'element))
(register-element! "FamilyMemberHistory.deceased[x]" (fhir-spec (string->symbol "FamilyMemberHistory.deceased[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" 'element))
(register-element! "FamilyMemberHistory.deceased[x]" (fhir-spec (string->symbol "FamilyMemberHistory.deceased[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" 'element))
(register-element! "FamilyMemberHistory.deceased[x]" (fhir-spec (string->symbol "FamilyMemberHistory.deceased[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" 'element))
(register-element! "FamilyMemberHistory.deceased[x]" (fhir-spec (string->symbol "FamilyMemberHistory.deceased[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" 'element))
(register-element! "FamilyMemberHistory.deceased[x]" (fhir-spec (string->symbol "FamilyMemberHistory.deceased[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.deceased[x]" 'element))

(register-type! 'FamilyMemberHistoryParticipant (fhir-spec 'FamilyMemberHistoryParticipant "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant" 'type)
  #:schema (type-schema 'FamilyMemberHistoryParticipant #f 'BackboneElement "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant.actor" #f)
             ) #f #f))
(register-element! "FamilyMemberHistory.participant.function" (fhir-spec (string->symbol "FamilyMemberHistory.participant.function") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant.function" 'element))
(register-element! "FamilyMemberHistory.participant.actor" (fhir-spec (string->symbol "FamilyMemberHistory.participant.actor") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.participant.actor" 'element))

(register-type! 'FamilyMemberHistoryCondition (fhir-spec 'FamilyMemberHistoryCondition "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition" 'type)
  #:schema (type-schema 'FamilyMemberHistoryCondition #f 'BackboneElement "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.code" #f)
    (schema-field 'outcome 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.outcome" #f)
    (schema-field 'contributedToDeath 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.contributedToDeath" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.note" #f)
    (schema-field 'onsetAge 0 1 (vector 'type 'Age) 'onset "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" #f)
    (schema-field 'onsetRange 0 1 (vector 'type 'Range) 'onset "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" #f)
    (schema-field 'onsetPeriod 0 1 (vector 'type 'Period) 'onset "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" #f)
    (schema-field 'onsetString 0 1 (vector 'prim "string") 'onset "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" #f)
             ) #f #f))
(register-element! "FamilyMemberHistory.condition.code" (fhir-spec (string->symbol "FamilyMemberHistory.condition.code") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.code" 'element))
(register-element! "FamilyMemberHistory.condition.outcome" (fhir-spec (string->symbol "FamilyMemberHistory.condition.outcome") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.outcome" 'element))
(register-element! "FamilyMemberHistory.condition.contributedToDeath" (fhir-spec (string->symbol "FamilyMemberHistory.condition.contributedToDeath") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.contributedToDeath" 'element))
(register-element! "FamilyMemberHistory.condition.note" (fhir-spec (string->symbol "FamilyMemberHistory.condition.note") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.note" 'element))
(register-element! "FamilyMemberHistory.condition.onset[x]" (fhir-spec (string->symbol "FamilyMemberHistory.condition.onset[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" 'element))
(register-element! "FamilyMemberHistory.condition.onset[x]" (fhir-spec (string->symbol "FamilyMemberHistory.condition.onset[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" 'element))
(register-element! "FamilyMemberHistory.condition.onset[x]" (fhir-spec (string->symbol "FamilyMemberHistory.condition.onset[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" 'element))
(register-element! "FamilyMemberHistory.condition.onset[x]" (fhir-spec (string->symbol "FamilyMemberHistory.condition.onset[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.condition.onset[x]" 'element))

(register-type! 'FamilyMemberHistoryProcedure (fhir-spec 'FamilyMemberHistoryProcedure "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure" 'type)
  #:schema (type-schema 'FamilyMemberHistoryProcedure #f 'BackboneElement "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.code" #f)
    (schema-field 'outcome 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.outcome" #f)
    (schema-field 'contributedToDeath 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.contributedToDeath" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.note" #f)
    (schema-field 'performedAge 0 1 (vector 'type 'Age) 'performed "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" #f)
    (schema-field 'performedRange 0 1 (vector 'type 'Range) 'performed "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" #f)
    (schema-field 'performedPeriod 0 1 (vector 'type 'Period) 'performed "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" #f)
    (schema-field 'performedString 0 1 (vector 'prim "string") 'performed "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" #f)
    (schema-field 'performedDateTime 0 1 (vector 'prim "dateTime") 'performed "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" #f)
             ) #f #f))
(register-element! "FamilyMemberHistory.procedure.code" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.code") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.code" 'element))
(register-element! "FamilyMemberHistory.procedure.outcome" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.outcome") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.outcome" 'element))
(register-element! "FamilyMemberHistory.procedure.contributedToDeath" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.contributedToDeath") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.contributedToDeath" 'element))
(register-element! "FamilyMemberHistory.procedure.note" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.note") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.note" 'element))
(register-element! "FamilyMemberHistory.procedure.performed[x]" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.performed[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" 'element))
(register-element! "FamilyMemberHistory.procedure.performed[x]" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.performed[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" 'element))
(register-element! "FamilyMemberHistory.procedure.performed[x]" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.performed[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" 'element))
(register-element! "FamilyMemberHistory.procedure.performed[x]" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.performed[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" 'element))
(register-element! "FamilyMemberHistory.procedure.performed[x]" (fhir-spec (string->symbol "FamilyMemberHistory.procedure.performed[x]") "https://hl7.org/fhir/R5/familymemberhistory.html#FamilyMemberHistory.procedure.performed[x]" 'element))

