#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Immunization (fhir-spec 'Immunization "https://hl7.org/fhir/R5/immunization.html#Immunization" 'type)
  #:schema (type-schema 'Immunization #f 'DomainResource "https://hl7.org/fhir/R5/immunization.html#Immunization"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.identifier" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.basedOn" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.statusReason" #f)
    (schema-field 'vaccineCode 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.vaccineCode" #f)
    (schema-field 'administeredProduct 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.administeredProduct" #f)
    (schema-field 'manufacturer 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.manufacturer" #f)
    (schema-field 'lotNumber 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.lotNumber" #f)
    (schema-field 'expirationDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.expirationDate" #f)
    (schema-field 'patient 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.patient" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.encounter" #f)
    (schema-field 'supportingInformation 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.supportingInformation" #f)
    (schema-field 'primarySource 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.primarySource" #f)
    (schema-field 'informationSource 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.informationSource" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.location" #f)
    (schema-field 'site 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.site" #f)
    (schema-field 'route 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.route" #f)
    (schema-field 'doseQuantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.doseQuantity" #f)
    (schema-field 'performer 0 '* (vector 'type 'ImmunizationPerformer) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.performer" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.note" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.reason" #f)
    (schema-field 'isSubpotent 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.isSubpotent" #f)
    (schema-field 'subpotentReason 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.subpotentReason" #f)
    (schema-field 'programEligibility 0 '* (vector 'type 'ImmunizationProgramEligibility) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility" #f)
    (schema-field 'fundingSource 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.fundingSource" #f)
    (schema-field 'reaction 0 '* (vector 'type 'ImmunizationReaction) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction" #f)
    (schema-field 'protocolApplied 0 '* (vector 'type 'ImmunizationProtocolApplied) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://hl7.org/fhir/R5/immunization.html#Immunization.occurrence[x]" #f)
    (schema-field 'occurrenceString 0 1 (vector 'prim "string") 'occurrence "https://hl7.org/fhir/R5/immunization.html#Immunization.occurrence[x]" #f)
             ) #f #f))
(register-element! "Immunization.identifier" (fhir-spec (string->symbol "Immunization.identifier") "https://hl7.org/fhir/R5/immunization.html#Immunization.identifier" 'element))
(register-element! "Immunization.basedOn" (fhir-spec (string->symbol "Immunization.basedOn") "https://hl7.org/fhir/R5/immunization.html#Immunization.basedOn" 'element))
(register-element! "Immunization.status" (fhir-spec (string->symbol "Immunization.status") "https://hl7.org/fhir/R5/immunization.html#Immunization.status" 'element))
(register-element! "Immunization.statusReason" (fhir-spec (string->symbol "Immunization.statusReason") "https://hl7.org/fhir/R5/immunization.html#Immunization.statusReason" 'element))
(register-element! "Immunization.vaccineCode" (fhir-spec (string->symbol "Immunization.vaccineCode") "https://hl7.org/fhir/R5/immunization.html#Immunization.vaccineCode" 'element))
(register-element! "Immunization.administeredProduct" (fhir-spec (string->symbol "Immunization.administeredProduct") "https://hl7.org/fhir/R5/immunization.html#Immunization.administeredProduct" 'element))
(register-element! "Immunization.manufacturer" (fhir-spec (string->symbol "Immunization.manufacturer") "https://hl7.org/fhir/R5/immunization.html#Immunization.manufacturer" 'element))
(register-element! "Immunization.lotNumber" (fhir-spec (string->symbol "Immunization.lotNumber") "https://hl7.org/fhir/R5/immunization.html#Immunization.lotNumber" 'element))
(register-element! "Immunization.expirationDate" (fhir-spec (string->symbol "Immunization.expirationDate") "https://hl7.org/fhir/R5/immunization.html#Immunization.expirationDate" 'element))
(register-element! "Immunization.patient" (fhir-spec (string->symbol "Immunization.patient") "https://hl7.org/fhir/R5/immunization.html#Immunization.patient" 'element))
(register-element! "Immunization.encounter" (fhir-spec (string->symbol "Immunization.encounter") "https://hl7.org/fhir/R5/immunization.html#Immunization.encounter" 'element))
(register-element! "Immunization.supportingInformation" (fhir-spec (string->symbol "Immunization.supportingInformation") "https://hl7.org/fhir/R5/immunization.html#Immunization.supportingInformation" 'element))
(register-element! "Immunization.primarySource" (fhir-spec (string->symbol "Immunization.primarySource") "https://hl7.org/fhir/R5/immunization.html#Immunization.primarySource" 'element))
(register-element! "Immunization.informationSource" (fhir-spec (string->symbol "Immunization.informationSource") "https://hl7.org/fhir/R5/immunization.html#Immunization.informationSource" 'element))
(register-element! "Immunization.location" (fhir-spec (string->symbol "Immunization.location") "https://hl7.org/fhir/R5/immunization.html#Immunization.location" 'element))
(register-element! "Immunization.site" (fhir-spec (string->symbol "Immunization.site") "https://hl7.org/fhir/R5/immunization.html#Immunization.site" 'element))
(register-element! "Immunization.route" (fhir-spec (string->symbol "Immunization.route") "https://hl7.org/fhir/R5/immunization.html#Immunization.route" 'element))
(register-element! "Immunization.doseQuantity" (fhir-spec (string->symbol "Immunization.doseQuantity") "https://hl7.org/fhir/R5/immunization.html#Immunization.doseQuantity" 'element))
(register-element! "Immunization.performer" (fhir-spec (string->symbol "Immunization.performer") "https://hl7.org/fhir/R5/immunization.html#Immunization.performer" 'element))
(register-element! "Immunization.note" (fhir-spec (string->symbol "Immunization.note") "https://hl7.org/fhir/R5/immunization.html#Immunization.note" 'element))
(register-element! "Immunization.reason" (fhir-spec (string->symbol "Immunization.reason") "https://hl7.org/fhir/R5/immunization.html#Immunization.reason" 'element))
(register-element! "Immunization.isSubpotent" (fhir-spec (string->symbol "Immunization.isSubpotent") "https://hl7.org/fhir/R5/immunization.html#Immunization.isSubpotent" 'element))
(register-element! "Immunization.subpotentReason" (fhir-spec (string->symbol "Immunization.subpotentReason") "https://hl7.org/fhir/R5/immunization.html#Immunization.subpotentReason" 'element))
(register-element! "Immunization.programEligibility" (fhir-spec (string->symbol "Immunization.programEligibility") "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility" 'element))
(register-element! "Immunization.fundingSource" (fhir-spec (string->symbol "Immunization.fundingSource") "https://hl7.org/fhir/R5/immunization.html#Immunization.fundingSource" 'element))
(register-element! "Immunization.reaction" (fhir-spec (string->symbol "Immunization.reaction") "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction" 'element))
(register-element! "Immunization.protocolApplied" (fhir-spec (string->symbol "Immunization.protocolApplied") "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied" 'element))
(register-element! "Immunization.occurrence[x]" (fhir-spec (string->symbol "Immunization.occurrence[x]") "https://hl7.org/fhir/R5/immunization.html#Immunization.occurrence[x]" 'element))
(register-element! "Immunization.occurrence[x]" (fhir-spec (string->symbol "Immunization.occurrence[x]") "https://hl7.org/fhir/R5/immunization.html#Immunization.occurrence[x]" 'element))

(register-type! 'ImmunizationPerformer (fhir-spec 'ImmunizationPerformer "https://hl7.org/fhir/R5/immunization.html#Immunization.performer" 'type)
  #:schema (type-schema 'ImmunizationPerformer #f 'BackboneElement "https://hl7.org/fhir/R5/immunization.html#Immunization.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.performer.actor" #f)
             ) #f #f))
(register-element! "Immunization.performer.function" (fhir-spec (string->symbol "Immunization.performer.function") "https://hl7.org/fhir/R5/immunization.html#Immunization.performer.function" 'element))
(register-element! "Immunization.performer.actor" (fhir-spec (string->symbol "Immunization.performer.actor") "https://hl7.org/fhir/R5/immunization.html#Immunization.performer.actor" 'element))

(register-type! 'ImmunizationProgramEligibility (fhir-spec 'ImmunizationProgramEligibility "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility" 'type)
  #:schema (type-schema 'ImmunizationProgramEligibility #f 'BackboneElement "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility"
             (list
    (schema-field 'program 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility.program" #f)
    (schema-field 'programStatus 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility.programStatus" #f)
             ) #f #f))
(register-element! "Immunization.programEligibility.program" (fhir-spec (string->symbol "Immunization.programEligibility.program") "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility.program" 'element))
(register-element! "Immunization.programEligibility.programStatus" (fhir-spec (string->symbol "Immunization.programEligibility.programStatus") "https://hl7.org/fhir/R5/immunization.html#Immunization.programEligibility.programStatus" 'element))

(register-type! 'ImmunizationReaction (fhir-spec 'ImmunizationReaction "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction" 'type)
  #:schema (type-schema 'ImmunizationReaction #f 'BackboneElement "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction"
             (list
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction.date" #f)
    (schema-field 'manifestation 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction.manifestation" #f)
    (schema-field 'reported 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction.reported" #f)
             ) #f #f))
(register-element! "Immunization.reaction.date" (fhir-spec (string->symbol "Immunization.reaction.date") "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction.date" 'element))
(register-element! "Immunization.reaction.manifestation" (fhir-spec (string->symbol "Immunization.reaction.manifestation") "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction.manifestation" 'element))
(register-element! "Immunization.reaction.reported" (fhir-spec (string->symbol "Immunization.reaction.reported") "https://hl7.org/fhir/R5/immunization.html#Immunization.reaction.reported" 'element))

(register-type! 'ImmunizationProtocolApplied (fhir-spec 'ImmunizationProtocolApplied "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied" 'type)
  #:schema (type-schema 'ImmunizationProtocolApplied #f 'BackboneElement "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied"
             (list
    (schema-field 'series 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.series" #f)
    (schema-field 'authority 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.authority" #f)
    (schema-field 'targetDisease 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.targetDisease" #f)
    (schema-field 'doseNumber 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.doseNumber" #f)
    (schema-field 'seriesDoses 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.seriesDoses" #f)
             ) #f #f))
(register-element! "Immunization.protocolApplied.series" (fhir-spec (string->symbol "Immunization.protocolApplied.series") "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.series" 'element))
(register-element! "Immunization.protocolApplied.authority" (fhir-spec (string->symbol "Immunization.protocolApplied.authority") "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.authority" 'element))
(register-element! "Immunization.protocolApplied.targetDisease" (fhir-spec (string->symbol "Immunization.protocolApplied.targetDisease") "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.targetDisease" 'element))
(register-element! "Immunization.protocolApplied.doseNumber" (fhir-spec (string->symbol "Immunization.protocolApplied.doseNumber") "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.doseNumber" 'element))
(register-element! "Immunization.protocolApplied.seriesDoses" (fhir-spec (string->symbol "Immunization.protocolApplied.seriesDoses") "https://hl7.org/fhir/R5/immunization.html#Immunization.protocolApplied.seriesDoses" 'element))

