#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'NutritionIntake (fhir-spec 'NutritionIntake "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake" 'type)
  #:schema (type-schema 'NutritionIntake #f 'DomainResource "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.identifier" #f)
    (schema-field 'instantiatesCanonical 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 '* (vector 'prim "uri") #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.instantiatesUri" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.basedOn" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.partOf" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.status" #f)
    (schema-field 'statusReason 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.statusReason" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.code" #f)
    (schema-field 'subject 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.subject" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.encounter" #f)
    (schema-field 'recorded 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.recorded" #f)
    (schema-field 'consumedItem 1 '* (vector 'type 'NutritionIntakeConsumedItem) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem" #f)
    (schema-field 'ingredientLabel 0 '* (vector 'type 'NutritionIntakeIngredientLabel) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel" #f)
    (schema-field 'performer 0 '* (vector 'type 'NutritionIntakePerformer) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.location" #f)
    (schema-field 'derivedFrom 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.derivedFrom" #f)
    (schema-field 'reason 0 '* (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.reason" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.note" #f)
    (schema-field 'occurrenceDateTime 0 1 (vector 'prim "dateTime") 'occurrence "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.occurrence[x]" #f)
    (schema-field 'occurrencePeriod 0 1 (vector 'type 'Period) 'occurrence "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.occurrence[x]" #f)
    (schema-field 'reportedBoolean 0 1 (vector 'prim "boolean") 'reported "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.reported[x]" #f)
    (schema-field 'reportedReference 0 1 (vector 'type 'Reference) 'reported "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.reported[x]" #f)
             ) #f #f))
(register-element! "NutritionIntake.identifier" (fhir-spec (string->symbol "NutritionIntake.identifier") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.identifier" 'element))
(register-element! "NutritionIntake.instantiatesCanonical" (fhir-spec (string->symbol "NutritionIntake.instantiatesCanonical") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.instantiatesCanonical" 'element))
(register-element! "NutritionIntake.instantiatesUri" (fhir-spec (string->symbol "NutritionIntake.instantiatesUri") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.instantiatesUri" 'element))
(register-element! "NutritionIntake.basedOn" (fhir-spec (string->symbol "NutritionIntake.basedOn") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.basedOn" 'element))
(register-element! "NutritionIntake.partOf" (fhir-spec (string->symbol "NutritionIntake.partOf") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.partOf" 'element))
(register-element! "NutritionIntake.status" (fhir-spec (string->symbol "NutritionIntake.status") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.status" 'element))
(register-element! "NutritionIntake.statusReason" (fhir-spec (string->symbol "NutritionIntake.statusReason") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.statusReason" 'element))
(register-element! "NutritionIntake.code" (fhir-spec (string->symbol "NutritionIntake.code") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.code" 'element))
(register-element! "NutritionIntake.subject" (fhir-spec (string->symbol "NutritionIntake.subject") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.subject" 'element))
(register-element! "NutritionIntake.encounter" (fhir-spec (string->symbol "NutritionIntake.encounter") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.encounter" 'element))
(register-element! "NutritionIntake.recorded" (fhir-spec (string->symbol "NutritionIntake.recorded") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.recorded" 'element))
(register-element! "NutritionIntake.consumedItem" (fhir-spec (string->symbol "NutritionIntake.consumedItem") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem" 'element))
(register-element! "NutritionIntake.ingredientLabel" (fhir-spec (string->symbol "NutritionIntake.ingredientLabel") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel" 'element))
(register-element! "NutritionIntake.performer" (fhir-spec (string->symbol "NutritionIntake.performer") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer" 'element))
(register-element! "NutritionIntake.location" (fhir-spec (string->symbol "NutritionIntake.location") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.location" 'element))
(register-element! "NutritionIntake.derivedFrom" (fhir-spec (string->symbol "NutritionIntake.derivedFrom") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.derivedFrom" 'element))
(register-element! "NutritionIntake.reason" (fhir-spec (string->symbol "NutritionIntake.reason") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.reason" 'element))
(register-element! "NutritionIntake.note" (fhir-spec (string->symbol "NutritionIntake.note") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.note" 'element))
(register-element! "NutritionIntake.occurrence[x]" (fhir-spec (string->symbol "NutritionIntake.occurrence[x]") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.occurrence[x]" 'element))
(register-element! "NutritionIntake.occurrence[x]" (fhir-spec (string->symbol "NutritionIntake.occurrence[x]") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.occurrence[x]" 'element))
(register-element! "NutritionIntake.reported[x]" (fhir-spec (string->symbol "NutritionIntake.reported[x]") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.reported[x]" 'element))
(register-element! "NutritionIntake.reported[x]" (fhir-spec (string->symbol "NutritionIntake.reported[x]") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.reported[x]" 'element))

(register-type! 'NutritionIntakeConsumedItem (fhir-spec 'NutritionIntakeConsumedItem "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem" 'type)
  #:schema (type-schema 'NutritionIntakeConsumedItem #f 'BackboneElement "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.type" #f)
    (schema-field 'nutritionProduct 1 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.nutritionProduct" #f)
    (schema-field 'schedule 0 1 (vector 'type 'Timing) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.schedule" #f)
    (schema-field 'amount 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.amount" #f)
    (schema-field 'rate 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.rate" #f)
    (schema-field 'notConsumed 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.notConsumed" #f)
    (schema-field 'notConsumedReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.notConsumedReason" #f)
             ) #f #f))
(register-element! "NutritionIntake.consumedItem.type" (fhir-spec (string->symbol "NutritionIntake.consumedItem.type") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.type" 'element))
(register-element! "NutritionIntake.consumedItem.nutritionProduct" (fhir-spec (string->symbol "NutritionIntake.consumedItem.nutritionProduct") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.nutritionProduct" 'element))
(register-element! "NutritionIntake.consumedItem.schedule" (fhir-spec (string->symbol "NutritionIntake.consumedItem.schedule") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.schedule" 'element))
(register-element! "NutritionIntake.consumedItem.amount" (fhir-spec (string->symbol "NutritionIntake.consumedItem.amount") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.amount" 'element))
(register-element! "NutritionIntake.consumedItem.rate" (fhir-spec (string->symbol "NutritionIntake.consumedItem.rate") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.rate" 'element))
(register-element! "NutritionIntake.consumedItem.notConsumed" (fhir-spec (string->symbol "NutritionIntake.consumedItem.notConsumed") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.notConsumed" 'element))
(register-element! "NutritionIntake.consumedItem.notConsumedReason" (fhir-spec (string->symbol "NutritionIntake.consumedItem.notConsumedReason") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.consumedItem.notConsumedReason" 'element))

(register-type! 'NutritionIntakeIngredientLabel (fhir-spec 'NutritionIntakeIngredientLabel "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel" 'type)
  #:schema (type-schema 'NutritionIntakeIngredientLabel #f 'BackboneElement "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel"
             (list
    (schema-field 'nutrient 1 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel.nutrient" #f)
    (schema-field 'amount 1 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel.amount" #f)
             ) #f #f))
(register-element! "NutritionIntake.ingredientLabel.nutrient" (fhir-spec (string->symbol "NutritionIntake.ingredientLabel.nutrient") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel.nutrient" 'element))
(register-element! "NutritionIntake.ingredientLabel.amount" (fhir-spec (string->symbol "NutritionIntake.ingredientLabel.amount") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.ingredientLabel.amount" 'element))

(register-type! 'NutritionIntakePerformer (fhir-spec 'NutritionIntakePerformer "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer" 'type)
  #:schema (type-schema 'NutritionIntakePerformer #f 'BackboneElement "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer"
             (list
    (schema-field 'function 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer.function" #f)
    (schema-field 'actor 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer.actor" #f)
             ) #f #f))
(register-element! "NutritionIntake.performer.function" (fhir-spec (string->symbol "NutritionIntake.performer.function") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer.function" 'element))
(register-element! "NutritionIntake.performer.actor" (fhir-spec (string->symbol "NutritionIntake.performer.actor") "https://hl7.org/fhir/R5/nutritionintake.html#NutritionIntake.performer.actor" 'element))

