#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'ObservationDefinition (fhir-spec 'ObservationDefinition "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition" 'type)
  #:schema (type-schema 'ObservationDefinition #f 'DomainResource "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition"
             (list
    (schema-field 'url 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.url" #f)
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.version" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.name" #f)
    (schema-field 'title 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.title" #f)
    (schema-field 'status 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.status" #f)
    (schema-field 'experimental 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.experimental" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.date" #f)
    (schema-field 'publisher 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.publisher" #f)
    (schema-field 'contact 0 '* (vector 'type 'ContactDetail) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.contact" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.description" #f)
    (schema-field 'useContext 0 '* (vector 'type 'UsageContext) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.useContext" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.jurisdiction" #f)
    (schema-field 'purpose 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.purpose" #f)
    (schema-field 'copyright 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.copyright" #f)
    (schema-field 'copyrightLabel 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.copyrightLabel" #f)
    (schema-field 'approvalDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.approvalDate" #f)
    (schema-field 'lastReviewDate 0 1 (vector 'prim "date") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.lastReviewDate" #f)
    (schema-field 'effectivePeriod 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.effectivePeriod" #f)
    (schema-field 'derivedFromCanonical 0 '* (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.derivedFromCanonical" #f)
    (schema-field 'derivedFromUri 0 '* (vector 'prim "uri") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.derivedFromUri" #f)
    (schema-field 'subject 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.subject" #f)
    (schema-field 'performerType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.performerType" #f)
    (schema-field 'category 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.category" #f)
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.code" #f)
    (schema-field 'permittedDataType 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.permittedDataType" #f)
    (schema-field 'multipleResultsAllowed 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.multipleResultsAllowed" #f)
    (schema-field 'bodySite 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.bodySite" #f)
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.method" #f)
    (schema-field 'specimen 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.specimen" #f)
    (schema-field 'device 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.device" #f)
    (schema-field 'preferredReportName 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.preferredReportName" #f)
    (schema-field 'permittedUnit 0 '* (vector 'type 'Coding) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.permittedUnit" #f)
    (schema-field 'qualifiedValue 0 '* (vector 'type 'ObservationDefinitionQualifiedValue) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue" #f)
    (schema-field 'hasMember 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.hasMember" #f)
    (schema-field 'component 0 '* (vector 'type 'ObservationDefinitionComponent) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component" #f)
    (schema-field 'versionAlgorithmString 0 1 (vector 'prim "string") 'versionAlgorithm "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.versionAlgorithm[x]" #f)
    (schema-field 'versionAlgorithmCoding 0 1 (vector 'type 'Coding) 'versionAlgorithm "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.versionAlgorithm[x]" #f)
             ) #f #f))
(register-element! "ObservationDefinition.url" (fhir-spec (string->symbol "ObservationDefinition.url") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.url" 'element))
(register-element! "ObservationDefinition.identifier" (fhir-spec (string->symbol "ObservationDefinition.identifier") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.identifier" 'element))
(register-element! "ObservationDefinition.version" (fhir-spec (string->symbol "ObservationDefinition.version") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.version" 'element))
(register-element! "ObservationDefinition.name" (fhir-spec (string->symbol "ObservationDefinition.name") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.name" 'element))
(register-element! "ObservationDefinition.title" (fhir-spec (string->symbol "ObservationDefinition.title") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.title" 'element))
(register-element! "ObservationDefinition.status" (fhir-spec (string->symbol "ObservationDefinition.status") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.status" 'element))
(register-element! "ObservationDefinition.experimental" (fhir-spec (string->symbol "ObservationDefinition.experimental") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.experimental" 'element))
(register-element! "ObservationDefinition.date" (fhir-spec (string->symbol "ObservationDefinition.date") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.date" 'element))
(register-element! "ObservationDefinition.publisher" (fhir-spec (string->symbol "ObservationDefinition.publisher") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.publisher" 'element))
(register-element! "ObservationDefinition.contact" (fhir-spec (string->symbol "ObservationDefinition.contact") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.contact" 'element))
(register-element! "ObservationDefinition.description" (fhir-spec (string->symbol "ObservationDefinition.description") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.description" 'element))
(register-element! "ObservationDefinition.useContext" (fhir-spec (string->symbol "ObservationDefinition.useContext") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.useContext" 'element))
(register-element! "ObservationDefinition.jurisdiction" (fhir-spec (string->symbol "ObservationDefinition.jurisdiction") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.jurisdiction" 'element))
(register-element! "ObservationDefinition.purpose" (fhir-spec (string->symbol "ObservationDefinition.purpose") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.purpose" 'element))
(register-element! "ObservationDefinition.copyright" (fhir-spec (string->symbol "ObservationDefinition.copyright") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.copyright" 'element))
(register-element! "ObservationDefinition.copyrightLabel" (fhir-spec (string->symbol "ObservationDefinition.copyrightLabel") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.copyrightLabel" 'element))
(register-element! "ObservationDefinition.approvalDate" (fhir-spec (string->symbol "ObservationDefinition.approvalDate") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.approvalDate" 'element))
(register-element! "ObservationDefinition.lastReviewDate" (fhir-spec (string->symbol "ObservationDefinition.lastReviewDate") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.lastReviewDate" 'element))
(register-element! "ObservationDefinition.effectivePeriod" (fhir-spec (string->symbol "ObservationDefinition.effectivePeriod") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.effectivePeriod" 'element))
(register-element! "ObservationDefinition.derivedFromCanonical" (fhir-spec (string->symbol "ObservationDefinition.derivedFromCanonical") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.derivedFromCanonical" 'element))
(register-element! "ObservationDefinition.derivedFromUri" (fhir-spec (string->symbol "ObservationDefinition.derivedFromUri") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.derivedFromUri" 'element))
(register-element! "ObservationDefinition.subject" (fhir-spec (string->symbol "ObservationDefinition.subject") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.subject" 'element))
(register-element! "ObservationDefinition.performerType" (fhir-spec (string->symbol "ObservationDefinition.performerType") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.performerType" 'element))
(register-element! "ObservationDefinition.category" (fhir-spec (string->symbol "ObservationDefinition.category") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.category" 'element))
(register-element! "ObservationDefinition.code" (fhir-spec (string->symbol "ObservationDefinition.code") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.code" 'element))
(register-element! "ObservationDefinition.permittedDataType" (fhir-spec (string->symbol "ObservationDefinition.permittedDataType") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.permittedDataType" 'element))
(register-element! "ObservationDefinition.multipleResultsAllowed" (fhir-spec (string->symbol "ObservationDefinition.multipleResultsAllowed") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.multipleResultsAllowed" 'element))
(register-element! "ObservationDefinition.bodySite" (fhir-spec (string->symbol "ObservationDefinition.bodySite") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.bodySite" 'element))
(register-element! "ObservationDefinition.method" (fhir-spec (string->symbol "ObservationDefinition.method") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.method" 'element))
(register-element! "ObservationDefinition.specimen" (fhir-spec (string->symbol "ObservationDefinition.specimen") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.specimen" 'element))
(register-element! "ObservationDefinition.device" (fhir-spec (string->symbol "ObservationDefinition.device") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.device" 'element))
(register-element! "ObservationDefinition.preferredReportName" (fhir-spec (string->symbol "ObservationDefinition.preferredReportName") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.preferredReportName" 'element))
(register-element! "ObservationDefinition.permittedUnit" (fhir-spec (string->symbol "ObservationDefinition.permittedUnit") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.permittedUnit" 'element))
(register-element! "ObservationDefinition.qualifiedValue" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue" 'element))
(register-element! "ObservationDefinition.hasMember" (fhir-spec (string->symbol "ObservationDefinition.hasMember") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.hasMember" 'element))
(register-element! "ObservationDefinition.component" (fhir-spec (string->symbol "ObservationDefinition.component") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component" 'element))
(register-element! "ObservationDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "ObservationDefinition.versionAlgorithm[x]") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.versionAlgorithm[x]" 'element))
(register-element! "ObservationDefinition.versionAlgorithm[x]" (fhir-spec (string->symbol "ObservationDefinition.versionAlgorithm[x]") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.versionAlgorithm[x]" 'element))

(register-type! 'ObservationDefinitionQualifiedValue (fhir-spec 'ObservationDefinitionQualifiedValue "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue" 'type)
  #:schema (type-schema 'ObservationDefinitionQualifiedValue #f 'BackboneElement "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue"
             (list
    (schema-field 'context 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.context" #f)
    (schema-field 'appliesTo 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.appliesTo" #f)
    (schema-field 'gender 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.gender" #f)
    (schema-field 'age 0 1 (vector 'type 'Range) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.age" #f)
    (schema-field 'gestationalAge 0 1 (vector 'type 'Range) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.gestationalAge" #f)
    (schema-field 'condition 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.condition" #f)
    (schema-field 'rangeCategory 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.rangeCategory" #f)
    (schema-field 'range 0 1 (vector 'type 'Range) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.range" #f)
    (schema-field 'validCodedValueSet 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.validCodedValueSet" #f)
    (schema-field 'normalCodedValueSet 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.normalCodedValueSet" #f)
    (schema-field 'abnormalCodedValueSet 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.abnormalCodedValueSet" #f)
    (schema-field 'criticalCodedValueSet 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.criticalCodedValueSet" #f)
             ) #f #f))
(register-element! "ObservationDefinition.qualifiedValue.context" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.context") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.context" 'element))
(register-element! "ObservationDefinition.qualifiedValue.appliesTo" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.appliesTo") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.appliesTo" 'element))
(register-element! "ObservationDefinition.qualifiedValue.gender" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.gender") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.gender" 'element))
(register-element! "ObservationDefinition.qualifiedValue.age" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.age") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.age" 'element))
(register-element! "ObservationDefinition.qualifiedValue.gestationalAge" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.gestationalAge") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.gestationalAge" 'element))
(register-element! "ObservationDefinition.qualifiedValue.condition" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.condition") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.condition" 'element))
(register-element! "ObservationDefinition.qualifiedValue.rangeCategory" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.rangeCategory") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.rangeCategory" 'element))
(register-element! "ObservationDefinition.qualifiedValue.range" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.range") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.range" 'element))
(register-element! "ObservationDefinition.qualifiedValue.validCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.validCodedValueSet") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.validCodedValueSet" 'element))
(register-element! "ObservationDefinition.qualifiedValue.normalCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.normalCodedValueSet") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.normalCodedValueSet" 'element))
(register-element! "ObservationDefinition.qualifiedValue.abnormalCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.abnormalCodedValueSet") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.abnormalCodedValueSet" 'element))
(register-element! "ObservationDefinition.qualifiedValue.criticalCodedValueSet" (fhir-spec (string->symbol "ObservationDefinition.qualifiedValue.criticalCodedValueSet") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.qualifiedValue.criticalCodedValueSet" 'element))

(register-type! 'ObservationDefinitionComponent (fhir-spec 'ObservationDefinitionComponent "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component" 'type)
  #:schema (type-schema 'ObservationDefinitionComponent #f 'BackboneElement "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component"
             (list
    (schema-field 'code 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.code" #f)
    (schema-field 'permittedDataType 0 '* (vector 'prim "code") #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.permittedDataType" #f)
    (schema-field 'permittedUnit 0 '* (vector 'type 'Coding) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.permittedUnit" #f)
    (schema-field 'qualifiedValue 0 '* (vector 'type 'ObservationDefinitionQualifiedValue) #f "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.qualifiedValue" #f)
             ) #f #f))
(register-element! "ObservationDefinition.component.code" (fhir-spec (string->symbol "ObservationDefinition.component.code") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.code" 'element))
(register-element! "ObservationDefinition.component.permittedDataType" (fhir-spec (string->symbol "ObservationDefinition.component.permittedDataType") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.permittedDataType" 'element))
(register-element! "ObservationDefinition.component.permittedUnit" (fhir-spec (string->symbol "ObservationDefinition.component.permittedUnit") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.permittedUnit" 'element))
(register-element! "ObservationDefinition.component.qualifiedValue" (fhir-spec (string->symbol "ObservationDefinition.component.qualifiedValue") "https://hl7.org/fhir/R5/observationdefinition.html#ObservationDefinition.component.qualifiedValue" 'element))

