#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Specimen (fhir-spec 'Specimen "https://hl7.org/fhir/R5/specimen.html#Specimen" 'type)
  #:schema (type-schema 'Specimen #f 'DomainResource "https://hl7.org/fhir/R5/specimen.html#Specimen"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.identifier" #f)
    (schema-field 'accessionIdentifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.accessionIdentifier" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/specimen.html#Specimen.status" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.type" #f)
    (schema-field 'subject 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.subject" #f)
    (schema-field 'receivedTime 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/specimen.html#Specimen.receivedTime" #f)
    (schema-field 'parent 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.parent" #f)
    (schema-field 'request 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.request" #f)
    (schema-field 'combined 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/specimen.html#Specimen.combined" #f)
    (schema-field 'role 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.role" #f)
    (schema-field 'feature 0 '* (vector 'type 'SpecimenFeature) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.feature" #f)
    (schema-field 'collection 0 1 (vector 'type 'SpecimenCollection) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection" #f)
    (schema-field 'processing 0 '* (vector 'type 'SpecimenProcessing) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.processing" #f)
    (schema-field 'container 0 '* (vector 'type 'SpecimenContainer) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.container" #f)
    (schema-field 'condition 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.condition" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.note" #f)
             ) #f #f))
(register-element! "Specimen.identifier" (fhir-spec (string->symbol "Specimen.identifier") "https://hl7.org/fhir/R5/specimen.html#Specimen.identifier" 'element))
(register-element! "Specimen.accessionIdentifier" (fhir-spec (string->symbol "Specimen.accessionIdentifier") "https://hl7.org/fhir/R5/specimen.html#Specimen.accessionIdentifier" 'element))
(register-element! "Specimen.status" (fhir-spec (string->symbol "Specimen.status") "https://hl7.org/fhir/R5/specimen.html#Specimen.status" 'element))
(register-element! "Specimen.type" (fhir-spec (string->symbol "Specimen.type") "https://hl7.org/fhir/R5/specimen.html#Specimen.type" 'element))
(register-element! "Specimen.subject" (fhir-spec (string->symbol "Specimen.subject") "https://hl7.org/fhir/R5/specimen.html#Specimen.subject" 'element))
(register-element! "Specimen.receivedTime" (fhir-spec (string->symbol "Specimen.receivedTime") "https://hl7.org/fhir/R5/specimen.html#Specimen.receivedTime" 'element))
(register-element! "Specimen.parent" (fhir-spec (string->symbol "Specimen.parent") "https://hl7.org/fhir/R5/specimen.html#Specimen.parent" 'element))
(register-element! "Specimen.request" (fhir-spec (string->symbol "Specimen.request") "https://hl7.org/fhir/R5/specimen.html#Specimen.request" 'element))
(register-element! "Specimen.combined" (fhir-spec (string->symbol "Specimen.combined") "https://hl7.org/fhir/R5/specimen.html#Specimen.combined" 'element))
(register-element! "Specimen.role" (fhir-spec (string->symbol "Specimen.role") "https://hl7.org/fhir/R5/specimen.html#Specimen.role" 'element))
(register-element! "Specimen.feature" (fhir-spec (string->symbol "Specimen.feature") "https://hl7.org/fhir/R5/specimen.html#Specimen.feature" 'element))
(register-element! "Specimen.collection" (fhir-spec (string->symbol "Specimen.collection") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection" 'element))
(register-element! "Specimen.processing" (fhir-spec (string->symbol "Specimen.processing") "https://hl7.org/fhir/R5/specimen.html#Specimen.processing" 'element))
(register-element! "Specimen.container" (fhir-spec (string->symbol "Specimen.container") "https://hl7.org/fhir/R5/specimen.html#Specimen.container" 'element))
(register-element! "Specimen.condition" (fhir-spec (string->symbol "Specimen.condition") "https://hl7.org/fhir/R5/specimen.html#Specimen.condition" 'element))
(register-element! "Specimen.note" (fhir-spec (string->symbol "Specimen.note") "https://hl7.org/fhir/R5/specimen.html#Specimen.note" 'element))

(register-type! 'SpecimenFeature (fhir-spec 'SpecimenFeature "https://hl7.org/fhir/R5/specimen.html#Specimen.feature" 'type)
  #:schema (type-schema 'SpecimenFeature #f 'BackboneElement "https://hl7.org/fhir/R5/specimen.html#Specimen.feature"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.feature.type" #f)
    (schema-field 'description 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/specimen.html#Specimen.feature.description" #f)
             ) #f #f))
(register-element! "Specimen.feature.type" (fhir-spec (string->symbol "Specimen.feature.type") "https://hl7.org/fhir/R5/specimen.html#Specimen.feature.type" 'element))
(register-element! "Specimen.feature.description" (fhir-spec (string->symbol "Specimen.feature.description") "https://hl7.org/fhir/R5/specimen.html#Specimen.feature.description" 'element))

(register-type! 'SpecimenCollection (fhir-spec 'SpecimenCollection "https://hl7.org/fhir/R5/specimen.html#Specimen.collection" 'type)
  #:schema (type-schema 'SpecimenCollection #f 'BackboneElement "https://hl7.org/fhir/R5/specimen.html#Specimen.collection"
             (list
    (schema-field 'collector 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.collector" #f)
    (schema-field 'duration 0 1 (vector 'type 'Duration) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.duration" #f)
    (schema-field 'quantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.quantity" #f)
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.method" #f)
    (schema-field 'device 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.device" #f)
    (schema-field 'procedure 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.procedure" #f)
    (schema-field 'bodySite 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.bodySite" #f)
    (schema-field 'collectedDateTime 0 1 (vector 'prim "dateTime") 'collected "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.collected[x]" #f)
    (schema-field 'collectedPeriod 0 1 (vector 'type 'Period) 'collected "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.collected[x]" #f)
    (schema-field 'fastingStatusCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'fastingStatus "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.fastingStatus[x]" #f)
    (schema-field 'fastingStatusDuration 0 1 (vector 'type 'Duration) 'fastingStatus "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.fastingStatus[x]" #f)
             ) #f #f))
(register-element! "Specimen.collection.collector" (fhir-spec (string->symbol "Specimen.collection.collector") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.collector" 'element))
(register-element! "Specimen.collection.duration" (fhir-spec (string->symbol "Specimen.collection.duration") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.duration" 'element))
(register-element! "Specimen.collection.quantity" (fhir-spec (string->symbol "Specimen.collection.quantity") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.quantity" 'element))
(register-element! "Specimen.collection.method" (fhir-spec (string->symbol "Specimen.collection.method") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.method" 'element))
(register-element! "Specimen.collection.device" (fhir-spec (string->symbol "Specimen.collection.device") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.device" 'element))
(register-element! "Specimen.collection.procedure" (fhir-spec (string->symbol "Specimen.collection.procedure") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.procedure" 'element))
(register-element! "Specimen.collection.bodySite" (fhir-spec (string->symbol "Specimen.collection.bodySite") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.bodySite" 'element))
(register-element! "Specimen.collection.collected[x]" (fhir-spec (string->symbol "Specimen.collection.collected[x]") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.collected[x]" 'element))
(register-element! "Specimen.collection.collected[x]" (fhir-spec (string->symbol "Specimen.collection.collected[x]") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.collected[x]" 'element))
(register-element! "Specimen.collection.fastingStatus[x]" (fhir-spec (string->symbol "Specimen.collection.fastingStatus[x]") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.fastingStatus[x]" 'element))
(register-element! "Specimen.collection.fastingStatus[x]" (fhir-spec (string->symbol "Specimen.collection.fastingStatus[x]") "https://hl7.org/fhir/R5/specimen.html#Specimen.collection.fastingStatus[x]" 'element))

(register-type! 'SpecimenProcessing (fhir-spec 'SpecimenProcessing "https://hl7.org/fhir/R5/specimen.html#Specimen.processing" 'type)
  #:schema (type-schema 'SpecimenProcessing #f 'BackboneElement "https://hl7.org/fhir/R5/specimen.html#Specimen.processing"
             (list
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.description" #f)
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.method" #f)
    (schema-field 'additive 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.additive" #f)
    (schema-field 'timeDateTime 0 1 (vector 'prim "dateTime") 'time "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.time[x]" #f)
    (schema-field 'timePeriod 0 1 (vector 'type 'Period) 'time "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.time[x]" #f)
             ) #f #f))
(register-element! "Specimen.processing.description" (fhir-spec (string->symbol "Specimen.processing.description") "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.description" 'element))
(register-element! "Specimen.processing.method" (fhir-spec (string->symbol "Specimen.processing.method") "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.method" 'element))
(register-element! "Specimen.processing.additive" (fhir-spec (string->symbol "Specimen.processing.additive") "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.additive" 'element))
(register-element! "Specimen.processing.time[x]" (fhir-spec (string->symbol "Specimen.processing.time[x]") "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.time[x]" 'element))
(register-element! "Specimen.processing.time[x]" (fhir-spec (string->symbol "Specimen.processing.time[x]") "https://hl7.org/fhir/R5/specimen.html#Specimen.processing.time[x]" 'element))

(register-type! 'SpecimenContainer (fhir-spec 'SpecimenContainer "https://hl7.org/fhir/R5/specimen.html#Specimen.container" 'type)
  #:schema (type-schema 'SpecimenContainer #f 'BackboneElement "https://hl7.org/fhir/R5/specimen.html#Specimen.container"
             (list
    (schema-field 'device 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.container.device" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.container.location" #f)
    (schema-field 'specimenQuantity 0 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/specimen.html#Specimen.container.specimenQuantity" #f)
             ) #f #f))
(register-element! "Specimen.container.device" (fhir-spec (string->symbol "Specimen.container.device") "https://hl7.org/fhir/R5/specimen.html#Specimen.container.device" 'element))
(register-element! "Specimen.container.location" (fhir-spec (string->symbol "Specimen.container.location") "https://hl7.org/fhir/R5/specimen.html#Specimen.container.location" 'element))
(register-element! "Specimen.container.specimenQuantity" (fhir-spec (string->symbol "Specimen.container.specimenQuantity") "https://hl7.org/fhir/R5/specimen.html#Specimen.container.specimenQuantity" 'element))

