#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'SubstanceDefinition (fhir-spec 'SubstanceDefinition "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition" 'type)
  #:schema (type-schema 'SubstanceDefinition #f 'DomainResource "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.identifier" #f)
    (schema-field 'version 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.version" #f)
    (schema-field 'status 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.status" #f)
    (schema-field 'classification 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.classification" #f)
    (schema-field 'domain 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.domain" #f)
    (schema-field 'grade 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.grade" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.description" #f)
    (schema-field 'informationSource 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.informationSource" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.note" #f)
    (schema-field 'manufacturer 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.manufacturer" #f)
    (schema-field 'supplier 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.supplier" #f)
    (schema-field 'moiety 0 '* (vector 'type 'SubstanceDefinitionMoiety) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety" #f)
    (schema-field 'characterization 0 '* (vector 'type 'SubstanceDefinitionCharacterization) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization" #f)
    (schema-field 'property 0 '* (vector 'type 'SubstanceDefinitionProperty) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property" #f)
    (schema-field 'referenceInformation 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.referenceInformation" #f)
    (schema-field 'molecularWeight 0 '* (vector 'type 'SubstanceDefinitionMolecularWeight) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight" #f)
    (schema-field 'structure 0 1 (vector 'type 'SubstanceDefinitionStructure) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure" #f)
    (schema-field 'code 0 '* (vector 'type 'SubstanceDefinitionCode) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code" #f)
    (schema-field 'name 0 '* (vector 'type 'SubstanceDefinitionName) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name" #f)
    (schema-field 'relationship 0 '* (vector 'type 'SubstanceDefinitionRelationship) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship" #f)
    (schema-field 'nucleicAcid 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.nucleicAcid" #f)
    (schema-field 'polymer 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.polymer" #f)
    (schema-field 'protein 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.protein" #f)
    (schema-field 'sourceMaterial 0 1 (vector 'type 'SubstanceDefinitionSourceMaterial) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.identifier" (fhir-spec (string->symbol "SubstanceDefinition.identifier") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.identifier" 'element))
(register-element! "SubstanceDefinition.version" (fhir-spec (string->symbol "SubstanceDefinition.version") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.version" 'element))
(register-element! "SubstanceDefinition.status" (fhir-spec (string->symbol "SubstanceDefinition.status") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.status" 'element))
(register-element! "SubstanceDefinition.classification" (fhir-spec (string->symbol "SubstanceDefinition.classification") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.classification" 'element))
(register-element! "SubstanceDefinition.domain" (fhir-spec (string->symbol "SubstanceDefinition.domain") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.domain" 'element))
(register-element! "SubstanceDefinition.grade" (fhir-spec (string->symbol "SubstanceDefinition.grade") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.grade" 'element))
(register-element! "SubstanceDefinition.description" (fhir-spec (string->symbol "SubstanceDefinition.description") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.description" 'element))
(register-element! "SubstanceDefinition.informationSource" (fhir-spec (string->symbol "SubstanceDefinition.informationSource") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.informationSource" 'element))
(register-element! "SubstanceDefinition.note" (fhir-spec (string->symbol "SubstanceDefinition.note") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.note" 'element))
(register-element! "SubstanceDefinition.manufacturer" (fhir-spec (string->symbol "SubstanceDefinition.manufacturer") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.manufacturer" 'element))
(register-element! "SubstanceDefinition.supplier" (fhir-spec (string->symbol "SubstanceDefinition.supplier") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.supplier" 'element))
(register-element! "SubstanceDefinition.moiety" (fhir-spec (string->symbol "SubstanceDefinition.moiety") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety" 'element))
(register-element! "SubstanceDefinition.characterization" (fhir-spec (string->symbol "SubstanceDefinition.characterization") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization" 'element))
(register-element! "SubstanceDefinition.property" (fhir-spec (string->symbol "SubstanceDefinition.property") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property" 'element))
(register-element! "SubstanceDefinition.referenceInformation" (fhir-spec (string->symbol "SubstanceDefinition.referenceInformation") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.referenceInformation" 'element))
(register-element! "SubstanceDefinition.molecularWeight" (fhir-spec (string->symbol "SubstanceDefinition.molecularWeight") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight" 'element))
(register-element! "SubstanceDefinition.structure" (fhir-spec (string->symbol "SubstanceDefinition.structure") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure" 'element))
(register-element! "SubstanceDefinition.code" (fhir-spec (string->symbol "SubstanceDefinition.code") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code" 'element))
(register-element! "SubstanceDefinition.name" (fhir-spec (string->symbol "SubstanceDefinition.name") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name" 'element))
(register-element! "SubstanceDefinition.relationship" (fhir-spec (string->symbol "SubstanceDefinition.relationship") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship" 'element))
(register-element! "SubstanceDefinition.nucleicAcid" (fhir-spec (string->symbol "SubstanceDefinition.nucleicAcid") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.nucleicAcid" 'element))
(register-element! "SubstanceDefinition.polymer" (fhir-spec (string->symbol "SubstanceDefinition.polymer") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.polymer" 'element))
(register-element! "SubstanceDefinition.protein" (fhir-spec (string->symbol "SubstanceDefinition.protein") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.protein" 'element))
(register-element! "SubstanceDefinition.sourceMaterial" (fhir-spec (string->symbol "SubstanceDefinition.sourceMaterial") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial" 'element))

(register-type! 'SubstanceDefinitionMoiety (fhir-spec 'SubstanceDefinitionMoiety "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety" 'type)
  #:schema (type-schema 'SubstanceDefinitionMoiety #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety"
             (list
    (schema-field 'role 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.role" #f)
    (schema-field 'identifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.identifier" #f)
    (schema-field 'name 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.name" #f)
    (schema-field 'stereochemistry 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.stereochemistry" #f)
    (schema-field 'opticalActivity 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.opticalActivity" #f)
    (schema-field 'molecularFormula 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.molecularFormula" #f)
    (schema-field 'measurementType 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.measurementType" #f)
    (schema-field 'amountQuantity 0 1 (vector 'type 'Quantity) 'amount "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.amount[x]" #f)
    (schema-field 'amountString 0 1 (vector 'prim "string") 'amount "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.amount[x]" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.moiety.role" (fhir-spec (string->symbol "SubstanceDefinition.moiety.role") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.role" 'element))
(register-element! "SubstanceDefinition.moiety.identifier" (fhir-spec (string->symbol "SubstanceDefinition.moiety.identifier") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.identifier" 'element))
(register-element! "SubstanceDefinition.moiety.name" (fhir-spec (string->symbol "SubstanceDefinition.moiety.name") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.name" 'element))
(register-element! "SubstanceDefinition.moiety.stereochemistry" (fhir-spec (string->symbol "SubstanceDefinition.moiety.stereochemistry") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.stereochemistry" 'element))
(register-element! "SubstanceDefinition.moiety.opticalActivity" (fhir-spec (string->symbol "SubstanceDefinition.moiety.opticalActivity") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.opticalActivity" 'element))
(register-element! "SubstanceDefinition.moiety.molecularFormula" (fhir-spec (string->symbol "SubstanceDefinition.moiety.molecularFormula") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.molecularFormula" 'element))
(register-element! "SubstanceDefinition.moiety.measurementType" (fhir-spec (string->symbol "SubstanceDefinition.moiety.measurementType") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.measurementType" 'element))
(register-element! "SubstanceDefinition.moiety.amount[x]" (fhir-spec (string->symbol "SubstanceDefinition.moiety.amount[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.amount[x]" 'element))
(register-element! "SubstanceDefinition.moiety.amount[x]" (fhir-spec (string->symbol "SubstanceDefinition.moiety.amount[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.moiety.amount[x]" 'element))

(register-type! 'SubstanceDefinitionCharacterization (fhir-spec 'SubstanceDefinitionCharacterization "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization" 'type)
  #:schema (type-schema 'SubstanceDefinitionCharacterization #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization"
             (list
    (schema-field 'technique 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.technique" #f)
    (schema-field 'form 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.form" #f)
    (schema-field 'description 0 1 (vector 'prim "markdown") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.description" #f)
    (schema-field 'file 0 '* (vector 'type 'Attachment) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.file" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.characterization.technique" (fhir-spec (string->symbol "SubstanceDefinition.characterization.technique") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.technique" 'element))
(register-element! "SubstanceDefinition.characterization.form" (fhir-spec (string->symbol "SubstanceDefinition.characterization.form") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.form" 'element))
(register-element! "SubstanceDefinition.characterization.description" (fhir-spec (string->symbol "SubstanceDefinition.characterization.description") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.description" 'element))
(register-element! "SubstanceDefinition.characterization.file" (fhir-spec (string->symbol "SubstanceDefinition.characterization.file") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.characterization.file" 'element))

(register-type! 'SubstanceDefinitionProperty (fhir-spec 'SubstanceDefinitionProperty "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property" 'type)
  #:schema (type-schema 'SubstanceDefinitionProperty #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.type" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.property.type" (fhir-spec (string->symbol "SubstanceDefinition.property.type") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.type" 'element))
(register-element! "SubstanceDefinition.property.value[x]" (fhir-spec (string->symbol "SubstanceDefinition.property.value[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" 'element))
(register-element! "SubstanceDefinition.property.value[x]" (fhir-spec (string->symbol "SubstanceDefinition.property.value[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" 'element))
(register-element! "SubstanceDefinition.property.value[x]" (fhir-spec (string->symbol "SubstanceDefinition.property.value[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" 'element))
(register-element! "SubstanceDefinition.property.value[x]" (fhir-spec (string->symbol "SubstanceDefinition.property.value[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" 'element))
(register-element! "SubstanceDefinition.property.value[x]" (fhir-spec (string->symbol "SubstanceDefinition.property.value[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.property.value[x]" 'element))

(register-type! 'SubstanceDefinitionMolecularWeight (fhir-spec 'SubstanceDefinitionMolecularWeight "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight" 'type)
  #:schema (type-schema 'SubstanceDefinitionMolecularWeight #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight"
             (list
    (schema-field 'method 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight.method" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight.type" #f)
    (schema-field 'amount 1 1 (vector 'type 'Quantity) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight.amount" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.molecularWeight.method" (fhir-spec (string->symbol "SubstanceDefinition.molecularWeight.method") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight.method" 'element))
(register-element! "SubstanceDefinition.molecularWeight.type" (fhir-spec (string->symbol "SubstanceDefinition.molecularWeight.type") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight.type" 'element))
(register-element! "SubstanceDefinition.molecularWeight.amount" (fhir-spec (string->symbol "SubstanceDefinition.molecularWeight.amount") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.molecularWeight.amount" 'element))

(register-type! 'SubstanceDefinitionStructure (fhir-spec 'SubstanceDefinitionStructure "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure" 'type)
  #:schema (type-schema 'SubstanceDefinitionStructure #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure"
             (list
    (schema-field 'stereochemistry 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.stereochemistry" #f)
    (schema-field 'opticalActivity 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.opticalActivity" #f)
    (schema-field 'molecularFormula 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.molecularFormula" #f)
    (schema-field 'molecularFormulaByMoiety 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.molecularFormulaByMoiety" #f)
    (schema-field 'molecularWeight 0 1 (vector 'type 'SubstanceDefinitionMolecularWeight) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.molecularWeight" #f)
    (schema-field 'technique 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.technique" #f)
    (schema-field 'sourceDocument 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.sourceDocument" #f)
    (schema-field 'representation 0 '* (vector 'type 'SubstanceDefinitionStructureRepresentation) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.structure.stereochemistry" (fhir-spec (string->symbol "SubstanceDefinition.structure.stereochemistry") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.stereochemistry" 'element))
(register-element! "SubstanceDefinition.structure.opticalActivity" (fhir-spec (string->symbol "SubstanceDefinition.structure.opticalActivity") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.opticalActivity" 'element))
(register-element! "SubstanceDefinition.structure.molecularFormula" (fhir-spec (string->symbol "SubstanceDefinition.structure.molecularFormula") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.molecularFormula" 'element))
(register-element! "SubstanceDefinition.structure.molecularFormulaByMoiety" (fhir-spec (string->symbol "SubstanceDefinition.structure.molecularFormulaByMoiety") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.molecularFormulaByMoiety" 'element))
(register-element! "SubstanceDefinition.structure.molecularWeight" (fhir-spec (string->symbol "SubstanceDefinition.structure.molecularWeight") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.molecularWeight" 'element))
(register-element! "SubstanceDefinition.structure.technique" (fhir-spec (string->symbol "SubstanceDefinition.structure.technique") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.technique" 'element))
(register-element! "SubstanceDefinition.structure.sourceDocument" (fhir-spec (string->symbol "SubstanceDefinition.structure.sourceDocument") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.sourceDocument" 'element))
(register-element! "SubstanceDefinition.structure.representation" (fhir-spec (string->symbol "SubstanceDefinition.structure.representation") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation" 'element))

(register-type! 'SubstanceDefinitionStructureRepresentation (fhir-spec 'SubstanceDefinitionStructureRepresentation "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation" 'type)
  #:schema (type-schema 'SubstanceDefinitionStructureRepresentation #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.type" #f)
    (schema-field 'representation 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.representation" #f)
    (schema-field 'format 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.format" #f)
    (schema-field 'document 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.document" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.structure.representation.type" (fhir-spec (string->symbol "SubstanceDefinition.structure.representation.type") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.type" 'element))
(register-element! "SubstanceDefinition.structure.representation.representation" (fhir-spec (string->symbol "SubstanceDefinition.structure.representation.representation") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.representation" 'element))
(register-element! "SubstanceDefinition.structure.representation.format" (fhir-spec (string->symbol "SubstanceDefinition.structure.representation.format") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.format" 'element))
(register-element! "SubstanceDefinition.structure.representation.document" (fhir-spec (string->symbol "SubstanceDefinition.structure.representation.document") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.structure.representation.document" 'element))

(register-type! 'SubstanceDefinitionCode (fhir-spec 'SubstanceDefinitionCode "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code" 'type)
  #:schema (type-schema 'SubstanceDefinitionCode #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code"
             (list
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.code" #f)
    (schema-field 'status 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.status" #f)
    (schema-field 'statusDate 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.statusDate" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.note" #f)
    (schema-field 'source 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.source" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.code.code" (fhir-spec (string->symbol "SubstanceDefinition.code.code") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.code" 'element))
(register-element! "SubstanceDefinition.code.status" (fhir-spec (string->symbol "SubstanceDefinition.code.status") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.status" 'element))
(register-element! "SubstanceDefinition.code.statusDate" (fhir-spec (string->symbol "SubstanceDefinition.code.statusDate") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.statusDate" 'element))
(register-element! "SubstanceDefinition.code.note" (fhir-spec (string->symbol "SubstanceDefinition.code.note") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.note" 'element))
(register-element! "SubstanceDefinition.code.source" (fhir-spec (string->symbol "SubstanceDefinition.code.source") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.code.source" 'element))

(register-type! 'SubstanceDefinitionName (fhir-spec 'SubstanceDefinitionName "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name" 'type)
  #:schema (type-schema 'SubstanceDefinitionName #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name"
             (list
    (schema-field 'name 1 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.name" #f)
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.type" #f)
    (schema-field 'status 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.status" #f)
    (schema-field 'preferred 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.preferred" #f)
    (schema-field 'language 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.language" #f)
    (schema-field 'domain 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.domain" #f)
    (schema-field 'jurisdiction 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.jurisdiction" #f)
    (schema-field 'synonym 0 '* (vector 'type 'SubstanceDefinitionName) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.synonym" #f)
    (schema-field 'translation 0 '* (vector 'type 'SubstanceDefinitionName) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.translation" #f)
    (schema-field 'official 0 '* (vector 'type 'SubstanceDefinitionNameOfficial) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official" #f)
    (schema-field 'source 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.source" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.name.name" (fhir-spec (string->symbol "SubstanceDefinition.name.name") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.name" 'element))
(register-element! "SubstanceDefinition.name.type" (fhir-spec (string->symbol "SubstanceDefinition.name.type") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.type" 'element))
(register-element! "SubstanceDefinition.name.status" (fhir-spec (string->symbol "SubstanceDefinition.name.status") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.status" 'element))
(register-element! "SubstanceDefinition.name.preferred" (fhir-spec (string->symbol "SubstanceDefinition.name.preferred") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.preferred" 'element))
(register-element! "SubstanceDefinition.name.language" (fhir-spec (string->symbol "SubstanceDefinition.name.language") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.language" 'element))
(register-element! "SubstanceDefinition.name.domain" (fhir-spec (string->symbol "SubstanceDefinition.name.domain") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.domain" 'element))
(register-element! "SubstanceDefinition.name.jurisdiction" (fhir-spec (string->symbol "SubstanceDefinition.name.jurisdiction") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.jurisdiction" 'element))
(register-element! "SubstanceDefinition.name.synonym" (fhir-spec (string->symbol "SubstanceDefinition.name.synonym") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.synonym" 'element))
(register-element! "SubstanceDefinition.name.translation" (fhir-spec (string->symbol "SubstanceDefinition.name.translation") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.translation" 'element))
(register-element! "SubstanceDefinition.name.official" (fhir-spec (string->symbol "SubstanceDefinition.name.official") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official" 'element))
(register-element! "SubstanceDefinition.name.source" (fhir-spec (string->symbol "SubstanceDefinition.name.source") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.source" 'element))

(register-type! 'SubstanceDefinitionNameOfficial (fhir-spec 'SubstanceDefinitionNameOfficial "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official" 'type)
  #:schema (type-schema 'SubstanceDefinitionNameOfficial #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official"
             (list
    (schema-field 'authority 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official.authority" #f)
    (schema-field 'status 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official.status" #f)
    (schema-field 'date 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official.date" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.name.official.authority" (fhir-spec (string->symbol "SubstanceDefinition.name.official.authority") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official.authority" 'element))
(register-element! "SubstanceDefinition.name.official.status" (fhir-spec (string->symbol "SubstanceDefinition.name.official.status") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official.status" 'element))
(register-element! "SubstanceDefinition.name.official.date" (fhir-spec (string->symbol "SubstanceDefinition.name.official.date") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.name.official.date" 'element))

(register-type! 'SubstanceDefinitionRelationship (fhir-spec 'SubstanceDefinitionRelationship "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship" 'type)
  #:schema (type-schema 'SubstanceDefinitionRelationship #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.type" #f)
    (schema-field 'isDefining 0 1 (vector 'prim "boolean") #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.isDefining" #f)
    (schema-field 'ratioHighLimitAmount 0 1 (vector 'type 'Ratio) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.ratioHighLimitAmount" #f)
    (schema-field 'comparator 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.comparator" #f)
    (schema-field 'source 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.source" #f)
    (schema-field 'substanceDefinitionReference 0 1 (vector 'type 'Reference) 'substanceDefinition "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.substanceDefinition[x]" #f)
    (schema-field 'substanceDefinitionCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'substanceDefinition "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.substanceDefinition[x]" #f)
    (schema-field 'amountQuantity 0 1 (vector 'type 'Quantity) 'amount "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.amount[x]" #f)
    (schema-field 'amountRatio 0 1 (vector 'type 'Ratio) 'amount "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.amount[x]" #f)
    (schema-field 'amountString 0 1 (vector 'prim "string") 'amount "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.amount[x]" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.relationship.type" (fhir-spec (string->symbol "SubstanceDefinition.relationship.type") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.type" 'element))
(register-element! "SubstanceDefinition.relationship.isDefining" (fhir-spec (string->symbol "SubstanceDefinition.relationship.isDefining") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.isDefining" 'element))
(register-element! "SubstanceDefinition.relationship.ratioHighLimitAmount" (fhir-spec (string->symbol "SubstanceDefinition.relationship.ratioHighLimitAmount") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.ratioHighLimitAmount" 'element))
(register-element! "SubstanceDefinition.relationship.comparator" (fhir-spec (string->symbol "SubstanceDefinition.relationship.comparator") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.comparator" 'element))
(register-element! "SubstanceDefinition.relationship.source" (fhir-spec (string->symbol "SubstanceDefinition.relationship.source") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.source" 'element))
(register-element! "SubstanceDefinition.relationship.substanceDefinition[x]" (fhir-spec (string->symbol "SubstanceDefinition.relationship.substanceDefinition[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.substanceDefinition[x]" 'element))
(register-element! "SubstanceDefinition.relationship.substanceDefinition[x]" (fhir-spec (string->symbol "SubstanceDefinition.relationship.substanceDefinition[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.substanceDefinition[x]" 'element))
(register-element! "SubstanceDefinition.relationship.amount[x]" (fhir-spec (string->symbol "SubstanceDefinition.relationship.amount[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.amount[x]" 'element))
(register-element! "SubstanceDefinition.relationship.amount[x]" (fhir-spec (string->symbol "SubstanceDefinition.relationship.amount[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.amount[x]" 'element))
(register-element! "SubstanceDefinition.relationship.amount[x]" (fhir-spec (string->symbol "SubstanceDefinition.relationship.amount[x]") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.relationship.amount[x]" 'element))

(register-type! 'SubstanceDefinitionSourceMaterial (fhir-spec 'SubstanceDefinitionSourceMaterial "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial" 'type)
  #:schema (type-schema 'SubstanceDefinitionSourceMaterial #f 'BackboneElement "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial"
             (list
    (schema-field 'type 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.type" #f)
    (schema-field 'genus 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.genus" #f)
    (schema-field 'species 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.species" #f)
    (schema-field 'part 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.part" #f)
    (schema-field 'countryOfOrigin 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.countryOfOrigin" #f)
             ) #f #f))
(register-element! "SubstanceDefinition.sourceMaterial.type" (fhir-spec (string->symbol "SubstanceDefinition.sourceMaterial.type") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.type" 'element))
(register-element! "SubstanceDefinition.sourceMaterial.genus" (fhir-spec (string->symbol "SubstanceDefinition.sourceMaterial.genus") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.genus" 'element))
(register-element! "SubstanceDefinition.sourceMaterial.species" (fhir-spec (string->symbol "SubstanceDefinition.sourceMaterial.species") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.species" 'element))
(register-element! "SubstanceDefinition.sourceMaterial.part" (fhir-spec (string->symbol "SubstanceDefinition.sourceMaterial.part") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.part" 'element))
(register-element! "SubstanceDefinition.sourceMaterial.countryOfOrigin" (fhir-spec (string->symbol "SubstanceDefinition.sourceMaterial.countryOfOrigin") "https://hl7.org/fhir/R5/substancedefinition.html#SubstanceDefinition.sourceMaterial.countryOfOrigin" 'element))

