#lang racket/base
;;; GENERATED from hl7.fhir.r5.core#5.0.0 — DO NOT EDIT (verified by raco fhir check).
(require fhir/model/schema fhir/model/registry)

(register-type! 'Transport (fhir-spec 'Transport "https://hl7.org/fhir/R5/transport.html#Transport" 'type)
  #:schema (type-schema 'Transport #f 'DomainResource "https://hl7.org/fhir/R5/transport.html#Transport"
             (list
    (schema-field 'identifier 0 '* (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/transport.html#Transport.identifier" #f)
    (schema-field 'instantiatesCanonical 0 1 (vector 'prim "canonical") #f "https://hl7.org/fhir/R5/transport.html#Transport.instantiatesCanonical" #f)
    (schema-field 'instantiatesUri 0 1 (vector 'prim "uri") #f "https://hl7.org/fhir/R5/transport.html#Transport.instantiatesUri" #f)
    (schema-field 'basedOn 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.basedOn" #f)
    (schema-field 'groupIdentifier 0 1 (vector 'type 'Identifier) #f "https://hl7.org/fhir/R5/transport.html#Transport.groupIdentifier" #f)
    (schema-field 'partOf 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.partOf" #f)
    (schema-field 'status 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/transport.html#Transport.status" #f)
    (schema-field 'statusReason 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/transport.html#Transport.statusReason" #f)
    (schema-field 'intent 1 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/transport.html#Transport.intent" #f)
    (schema-field 'priority 0 1 (vector 'prim "code") #f "https://hl7.org/fhir/R5/transport.html#Transport.priority" #f)
    (schema-field 'code 0 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/transport.html#Transport.code" #f)
    (schema-field 'description 0 1 (vector 'prim "string") #f "https://hl7.org/fhir/R5/transport.html#Transport.description" #f)
    (schema-field 'focus 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.focus" #f)
    (schema-field 'for 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.for" #f)
    (schema-field 'encounter 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.encounter" #f)
    (schema-field 'completionTime 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/transport.html#Transport.completionTime" #f)
    (schema-field 'authoredOn 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/transport.html#Transport.authoredOn" #f)
    (schema-field 'lastModified 0 1 (vector 'prim "dateTime") #f "https://hl7.org/fhir/R5/transport.html#Transport.lastModified" #f)
    (schema-field 'requester 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.requester" #f)
    (schema-field 'performerType 0 '* (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/transport.html#Transport.performerType" #f)
    (schema-field 'owner 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.owner" #f)
    (schema-field 'location 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.location" #f)
    (schema-field 'insurance 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.insurance" #f)
    (schema-field 'note 0 '* (vector 'type 'Annotation) #f "https://hl7.org/fhir/R5/transport.html#Transport.note" #f)
    (schema-field 'relevantHistory 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.relevantHistory" #f)
    (schema-field 'restriction 0 1 (vector 'type 'TransportRestriction) #f "https://hl7.org/fhir/R5/transport.html#Transport.restriction" #f)
    (schema-field 'input 0 '* (vector 'type 'TransportInput) #f "https://hl7.org/fhir/R5/transport.html#Transport.input" #f)
    (schema-field 'output 0 '* (vector 'type 'TransportOutput) #f "https://hl7.org/fhir/R5/transport.html#Transport.output" #f)
    (schema-field 'requestedLocation 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.requestedLocation" #f)
    (schema-field 'currentLocation 1 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.currentLocation" #f)
    (schema-field 'reason 0 1 (vector 'type 'CodeableReference) #f "https://hl7.org/fhir/R5/transport.html#Transport.reason" #f)
    (schema-field 'history 0 1 (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.history" #f)
             ) #f #f))
(register-element! "Transport.identifier" (fhir-spec (string->symbol "Transport.identifier") "https://hl7.org/fhir/R5/transport.html#Transport.identifier" 'element))
(register-element! "Transport.instantiatesCanonical" (fhir-spec (string->symbol "Transport.instantiatesCanonical") "https://hl7.org/fhir/R5/transport.html#Transport.instantiatesCanonical" 'element))
(register-element! "Transport.instantiatesUri" (fhir-spec (string->symbol "Transport.instantiatesUri") "https://hl7.org/fhir/R5/transport.html#Transport.instantiatesUri" 'element))
(register-element! "Transport.basedOn" (fhir-spec (string->symbol "Transport.basedOn") "https://hl7.org/fhir/R5/transport.html#Transport.basedOn" 'element))
(register-element! "Transport.groupIdentifier" (fhir-spec (string->symbol "Transport.groupIdentifier") "https://hl7.org/fhir/R5/transport.html#Transport.groupIdentifier" 'element))
(register-element! "Transport.partOf" (fhir-spec (string->symbol "Transport.partOf") "https://hl7.org/fhir/R5/transport.html#Transport.partOf" 'element))
(register-element! "Transport.status" (fhir-spec (string->symbol "Transport.status") "https://hl7.org/fhir/R5/transport.html#Transport.status" 'element))
(register-element! "Transport.statusReason" (fhir-spec (string->symbol "Transport.statusReason") "https://hl7.org/fhir/R5/transport.html#Transport.statusReason" 'element))
(register-element! "Transport.intent" (fhir-spec (string->symbol "Transport.intent") "https://hl7.org/fhir/R5/transport.html#Transport.intent" 'element))
(register-element! "Transport.priority" (fhir-spec (string->symbol "Transport.priority") "https://hl7.org/fhir/R5/transport.html#Transport.priority" 'element))
(register-element! "Transport.code" (fhir-spec (string->symbol "Transport.code") "https://hl7.org/fhir/R5/transport.html#Transport.code" 'element))
(register-element! "Transport.description" (fhir-spec (string->symbol "Transport.description") "https://hl7.org/fhir/R5/transport.html#Transport.description" 'element))
(register-element! "Transport.focus" (fhir-spec (string->symbol "Transport.focus") "https://hl7.org/fhir/R5/transport.html#Transport.focus" 'element))
(register-element! "Transport.for" (fhir-spec (string->symbol "Transport.for") "https://hl7.org/fhir/R5/transport.html#Transport.for" 'element))
(register-element! "Transport.encounter" (fhir-spec (string->symbol "Transport.encounter") "https://hl7.org/fhir/R5/transport.html#Transport.encounter" 'element))
(register-element! "Transport.completionTime" (fhir-spec (string->symbol "Transport.completionTime") "https://hl7.org/fhir/R5/transport.html#Transport.completionTime" 'element))
(register-element! "Transport.authoredOn" (fhir-spec (string->symbol "Transport.authoredOn") "https://hl7.org/fhir/R5/transport.html#Transport.authoredOn" 'element))
(register-element! "Transport.lastModified" (fhir-spec (string->symbol "Transport.lastModified") "https://hl7.org/fhir/R5/transport.html#Transport.lastModified" 'element))
(register-element! "Transport.requester" (fhir-spec (string->symbol "Transport.requester") "https://hl7.org/fhir/R5/transport.html#Transport.requester" 'element))
(register-element! "Transport.performerType" (fhir-spec (string->symbol "Transport.performerType") "https://hl7.org/fhir/R5/transport.html#Transport.performerType" 'element))
(register-element! "Transport.owner" (fhir-spec (string->symbol "Transport.owner") "https://hl7.org/fhir/R5/transport.html#Transport.owner" 'element))
(register-element! "Transport.location" (fhir-spec (string->symbol "Transport.location") "https://hl7.org/fhir/R5/transport.html#Transport.location" 'element))
(register-element! "Transport.insurance" (fhir-spec (string->symbol "Transport.insurance") "https://hl7.org/fhir/R5/transport.html#Transport.insurance" 'element))
(register-element! "Transport.note" (fhir-spec (string->symbol "Transport.note") "https://hl7.org/fhir/R5/transport.html#Transport.note" 'element))
(register-element! "Transport.relevantHistory" (fhir-spec (string->symbol "Transport.relevantHistory") "https://hl7.org/fhir/R5/transport.html#Transport.relevantHistory" 'element))
(register-element! "Transport.restriction" (fhir-spec (string->symbol "Transport.restriction") "https://hl7.org/fhir/R5/transport.html#Transport.restriction" 'element))
(register-element! "Transport.input" (fhir-spec (string->symbol "Transport.input") "https://hl7.org/fhir/R5/transport.html#Transport.input" 'element))
(register-element! "Transport.output" (fhir-spec (string->symbol "Transport.output") "https://hl7.org/fhir/R5/transport.html#Transport.output" 'element))
(register-element! "Transport.requestedLocation" (fhir-spec (string->symbol "Transport.requestedLocation") "https://hl7.org/fhir/R5/transport.html#Transport.requestedLocation" 'element))
(register-element! "Transport.currentLocation" (fhir-spec (string->symbol "Transport.currentLocation") "https://hl7.org/fhir/R5/transport.html#Transport.currentLocation" 'element))
(register-element! "Transport.reason" (fhir-spec (string->symbol "Transport.reason") "https://hl7.org/fhir/R5/transport.html#Transport.reason" 'element))
(register-element! "Transport.history" (fhir-spec (string->symbol "Transport.history") "https://hl7.org/fhir/R5/transport.html#Transport.history" 'element))

(register-type! 'TransportRestriction (fhir-spec 'TransportRestriction "https://hl7.org/fhir/R5/transport.html#Transport.restriction" 'type)
  #:schema (type-schema 'TransportRestriction #f 'BackboneElement "https://hl7.org/fhir/R5/transport.html#Transport.restriction"
             (list
    (schema-field 'repetitions 0 1 (vector 'prim "positiveInt") #f "https://hl7.org/fhir/R5/transport.html#Transport.restriction.repetitions" #f)
    (schema-field 'period 0 1 (vector 'type 'Period) #f "https://hl7.org/fhir/R5/transport.html#Transport.restriction.period" #f)
    (schema-field 'recipient 0 '* (vector 'type 'Reference) #f "https://hl7.org/fhir/R5/transport.html#Transport.restriction.recipient" #f)
             ) #f #f))
(register-element! "Transport.restriction.repetitions" (fhir-spec (string->symbol "Transport.restriction.repetitions") "https://hl7.org/fhir/R5/transport.html#Transport.restriction.repetitions" 'element))
(register-element! "Transport.restriction.period" (fhir-spec (string->symbol "Transport.restriction.period") "https://hl7.org/fhir/R5/transport.html#Transport.restriction.period" 'element))
(register-element! "Transport.restriction.recipient" (fhir-spec (string->symbol "Transport.restriction.recipient") "https://hl7.org/fhir/R5/transport.html#Transport.restriction.recipient" 'element))

(register-type! 'TransportInput (fhir-spec 'TransportInput "https://hl7.org/fhir/R5/transport.html#Transport.input" 'type)
  #:schema (type-schema 'TransportInput #f 'BackboneElement "https://hl7.org/fhir/R5/transport.html#Transport.input"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/transport.html#Transport.input.type" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueInteger64 0 1 (vector 'prim "integer64") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueCodeableReference 0 1 (vector 'type 'CodeableReference) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueRatioRange 0 1 (vector 'type 'RatioRange) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueAvailability 0 1 (vector 'type 'Availability) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueExtendedContactDetail 0 1 (vector 'type 'ExtendedContactDetail) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" #f)
             ) #f #f))
(register-element! "Transport.input.type" (fhir-spec (string->symbol "Transport.input.type") "https://hl7.org/fhir/R5/transport.html#Transport.input.type" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))
(register-element! "Transport.input.value[x]" (fhir-spec (string->symbol "Transport.input.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.input.value[x]" 'element))

(register-type! 'TransportOutput (fhir-spec 'TransportOutput "https://hl7.org/fhir/R5/transport.html#Transport.output" 'type)
  #:schema (type-schema 'TransportOutput #f 'BackboneElement "https://hl7.org/fhir/R5/transport.html#Transport.output"
             (list
    (schema-field 'type 1 1 (vector 'type 'CodeableConcept) #f "https://hl7.org/fhir/R5/transport.html#Transport.output.type" #f)
    (schema-field 'valueBase64Binary 0 1 (vector 'prim "base64Binary") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueBoolean 0 1 (vector 'prim "boolean") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueCanonical 0 1 (vector 'prim "canonical") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueCode 0 1 (vector 'prim "code") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueDate 0 1 (vector 'prim "date") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueDateTime 0 1 (vector 'prim "dateTime") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueDecimal 0 1 (vector 'prim "decimal") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueId 0 1 (vector 'prim "id") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueInstant 0 1 (vector 'prim "instant") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueInteger 0 1 (vector 'prim "integer") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueInteger64 0 1 (vector 'prim "integer64") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueMarkdown 0 1 (vector 'prim "markdown") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueOid 0 1 (vector 'prim "oid") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valuePositiveInt 0 1 (vector 'prim "positiveInt") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueString 0 1 (vector 'prim "string") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueTime 0 1 (vector 'prim "time") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueUnsignedInt 0 1 (vector 'prim "unsignedInt") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueUri 0 1 (vector 'prim "uri") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueUrl 0 1 (vector 'prim "url") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueUuid 0 1 (vector 'prim "uuid") 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueAddress 0 1 (vector 'type 'Address) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueAge 0 1 (vector 'type 'Age) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueAnnotation 0 1 (vector 'type 'Annotation) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueAttachment 0 1 (vector 'type 'Attachment) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueCodeableConcept 0 1 (vector 'type 'CodeableConcept) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueCodeableReference 0 1 (vector 'type 'CodeableReference) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueCoding 0 1 (vector 'type 'Coding) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueContactPoint 0 1 (vector 'type 'ContactPoint) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueCount 0 1 (vector 'type 'Count) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueDistance 0 1 (vector 'type 'Distance) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueDuration 0 1 (vector 'type 'Duration) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueHumanName 0 1 (vector 'type 'HumanName) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueIdentifier 0 1 (vector 'type 'Identifier) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueMoney 0 1 (vector 'type 'Money) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valuePeriod 0 1 (vector 'type 'Period) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueQuantity 0 1 (vector 'type 'Quantity) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueRange 0 1 (vector 'type 'Range) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueRatio 0 1 (vector 'type 'Ratio) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueRatioRange 0 1 (vector 'type 'RatioRange) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueReference 0 1 (vector 'type 'Reference) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueSampledData 0 1 (vector 'type 'SampledData) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueSignature 0 1 (vector 'type 'Signature) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueTiming 0 1 (vector 'type 'Timing) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueContactDetail 0 1 (vector 'type 'ContactDetail) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueDataRequirement 0 1 (vector 'type 'DataRequirement) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueExpression 0 1 (vector 'type 'Expression) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueParameterDefinition 0 1 (vector 'type 'ParameterDefinition) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueRelatedArtifact 0 1 (vector 'type 'RelatedArtifact) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueTriggerDefinition 0 1 (vector 'type 'TriggerDefinition) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueUsageContext 0 1 (vector 'type 'UsageContext) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueAvailability 0 1 (vector 'type 'Availability) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueExtendedContactDetail 0 1 (vector 'type 'ExtendedContactDetail) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueDosage 0 1 (vector 'type 'Dosage) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
    (schema-field 'valueMeta 0 1 (vector 'type 'Meta) 'value "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" #f)
             ) #f #f))
(register-element! "Transport.output.type" (fhir-spec (string->symbol "Transport.output.type") "https://hl7.org/fhir/R5/transport.html#Transport.output.type" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))
(register-element! "Transport.output.value[x]" (fhir-spec (string->symbol "Transport.output.value[x]") "https://hl7.org/fhir/R5/transport.html#Transport.output.value[x]" 'element))

