#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide condition_occurrence)
(define-syntax (condition_occurrence stx)
  (build-fhir-form stx 'condition_occurrence
    '(#s(field-spec condition_occurrence_id 1 1 #(prim "integer") #f)
      #s(field-spec person_id 1 1 #(prim "integer") #f)
      #s(field-spec condition_concept_id 1 1 #(prim "code") #f)
      #s(field-spec condition_start_date 1 1 #(prim "date") #f)
      #s(field-spec condition_start_datetime 0 1 #(prim "dateTime") #f)
      #s(field-spec condition_end_date 0 1 #(prim "date") #f)
      #s(field-spec condition_end_datetime 0 1 #(prim "dateTime") #f)
      #s(field-spec condition_type_concept_id 1 1 #(prim "code") #f)
      #s(field-spec condition_status_concept_id 0 1 #(prim "code") #f)
      #s(field-spec stop_reason 0 1 #(prim "string") #f)
      #s(field-spec provider_id 0 1 #(prim "integer") #f)
      #s(field-spec visit_occurrence_id 0 1 #(prim "integer") #f)
      #s(field-spec visit_detail_id 0 1 #(prim "integer") #f)
      #s(field-spec condition_source_value 0 1 #(prim "string") #f)
      #s(field-spec condition_source_concept_id 0 1 #(prim "code") #f)
      #s(field-spec condition_status_source_value 0 1 #(prim "string") #f)
      )
    #:parent 'Base))
