#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide measurement)
(define-syntax (measurement stx)
  (build-fhir-form stx 'measurement
    '(#s(field-spec measurement_id 1 1 #(prim "code") #f)
      #s(field-spec person_id 1 1 #(prim "integer") #f)
      #s(field-spec measurement_concept_id 1 1 #(prim "code") #f)
      #s(field-spec measurement_date 1 1 #(prim "date") #f)
      #s(field-spec measurement_datetime 0 1 #(prim "dateTime") #f)
      #s(field-spec measurement_time 0 1 #(prim "string") #f)
      #s(field-spec measurement_type_concept_id 1 1 #(prim "code") #f)
      #s(field-spec operator_concept_id 0 1 #(prim "code") #f)
      #s(field-spec value_as_number 0 1 #(prim "decimal") #f)
      #s(field-spec value_as_concept_id 0 1 #(prim "code") #f)
      #s(field-spec unit_concept_id 0 1 #(prim "code") #f)
      #s(field-spec range_low 0 1 #(prim "decimal") #f)
      #s(field-spec range_high 0 1 #(prim "decimal") #f)
      #s(field-spec provider_id 0 1 #(prim "integer") #f)
      #s(field-spec visit_occurrence_id 0 1 #(prim "integer") #f)
      #s(field-spec visit_detail_id 0 1 #(prim "integer") #f)
      #s(field-spec measurement_source_value 0 1 #(prim "string") #f)
      #s(field-spec measurement_source_concept_id 0 1 #(prim "code") #f)
      #s(field-spec unit_source_value 0 1 #(prim "string") #f)
      #s(field-spec unit_source_concept_id 0 1 #(prim "code") #f)
      #s(field-spec value_source_value 0 1 #(prim "string") #f)
      #s(field-spec measurement_event_id 0 1 #(prim "string") #f)
      #s(field-spec meas_event_field_concept_id 0 1 #(prim "code") #f)
      )
    #:parent 'Base))
