#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide note)
(define-syntax (note stx)
  (build-fhir-form stx 'note
    '(#s(field-spec note_id 1 1 #(prim "code") #f)
      #s(field-spec person_id 1 1 #(prim "integer") #f)
      #s(field-spec note_date 1 1 #(prim "date") #f)
      #s(field-spec note_datetime 0 1 #(prim "dateTime") #f)
      #s(field-spec note_type_concept_id 1 1 #(prim "code") #f)
      #s(field-spec note_class_concept_id 1 1 #(prim "code") #f)
      #s(field-spec note_title 0 1 #(prim "string") #f)
      #s(field-spec note_text 1 1 #(prim "string") #f)
      #s(field-spec encoding_concept_id 1 1 #(prim "code") #f)
      #s(field-spec language_concept_id 1 1 #(prim "code") #f)
      #s(field-spec provider_id 0 1 #(prim "integer") #f)
      #s(field-spec visit_occurrence_id 0 1 #(prim "integer") #f)
      #s(field-spec visit_detail_id 0 1 #(prim "integer") #f)
      #s(field-spec note_source_value 0 1 #(prim "string") #f)
      #s(field-spec note_event_id 0 1 #(prim "integer") #f)
      #s(field-spec note_event_field_concept_id 0 1 #(prim "code") #f)
      )
    #:parent 'Base))
