#lang racket/base
;;; GENERATED from hl7.fhir.uv.omop#2.0.0-ballot — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide visit_occurrence)
(define-syntax (visit_occurrence stx)
  (build-fhir-form stx 'visit_occurrence
    '(#s(field-spec visit_occurrence_id 1 1 #(prim "integer") #f)
      #s(field-spec person_id 1 1 #(prim "integer") #f)
      #s(field-spec visit_concept_id 1 1 #(prim "code") #f)
      #s(field-spec visit_start_date 1 1 #(prim "date") #f)
      #s(field-spec visit_start_datetime 0 1 #(prim "dateTime") #f)
      #s(field-spec visit_end_date 1 1 #(prim "date") #f)
      #s(field-spec visit_end_datetime 0 1 #(prim "dateTime") #f)
      #s(field-spec visit_type_concept_id 1 1 #(prim "code") #f)
      #s(field-spec provider_id 0 1 #(prim "integer") #f)
      #s(field-spec care_site_id 0 1 #(prim "integer") #f)
      #s(field-spec visit_source_value 0 1 #(prim "string") #f)
      #s(field-spec visit_source_concept_id 0 1 #(prim "code") #f)
      #s(field-spec admitted_from_concept_id 0 1 #(prim "code") #f)
      #s(field-spec admitted_from_source_value 0 1 #(prim "string") #f)
      #s(field-spec discharged_to_concept_id 0 1 #(prim "code") #f)
      #s(field-spec discharged_to_source_value 0 1 #(prim "string") #f)
      #s(field-spec preceding_visit_occurrence_id 0 1 #(prim "integer") #f)
      )
    #:parent 'Base))
