#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Account AccountCoverage AccountGuarantor AccountDiagnosis AccountProcedure AccountBalance)
(define-syntax (Account stx)
  (build-fhir-form stx 'Account
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/account-status"))
      #s(field-spec billingStatus 0 1 #(type CodeableConcept) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec subject 0 * #(type Reference) #f)
      #s(field-spec servicePeriod 0 1 #(type Period) #f)
      #s(field-spec covers 0 * #(type Reference) #f)
      #s(field-spec coverage 0 * #(type AccountCoverage) #f)
      #s(field-spec owner 0 1 #(type Reference) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec guarantor 0 * #(type AccountGuarantor) #f)
      #s(field-spec diagnosis 0 * #(type AccountDiagnosis) #f)
      #s(field-spec procedure 0 * #(type AccountProcedure) #f)
      #s(field-spec parent 0 1 #(type Reference) #f)
      #s(field-spec currency 0 1 #(type CodeableConcept) #f)
      #s(field-spec balance 0 * #(type AccountBalance) #f)
      #s(field-spec calculatedAt 0 1 #(prim "instant") #f)
      )
    #:parent 'DomainResource))
(define-syntax (AccountCoverage stx)
  (build-fhir-form stx 'AccountCoverage
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec coverage 1 1 #(type Reference) #f)
      #s(field-spec priority 0 1 #(prim "positiveInt") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AccountGuarantor stx)
  (build-fhir-form stx 'AccountGuarantor
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec party 0 1 #(type Reference) #f)
      #s(field-spec onHold 0 1 #(prim "boolean") #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec account 0 1 #(type Reference) #f)
      #s(field-spec responsibility 0 1 #(type Quantity) #f)
      #s(field-spec limit 0 1 #(type Money) #f)
      #s(field-spec rank 0 1 #(prim "positiveInt") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AccountDiagnosis stx)
  (build-fhir-form stx 'AccountDiagnosis
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec sequence 0 1 #(prim "positiveInt") #f)
      #s(field-spec condition 1 1 #(type CodeableReference) #f)
      #s(field-spec dateOfDiagnosis 0 1 #(prim "dateTime") #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec onAdmission 0 1 #(prim "boolean") #f)
      #s(field-spec packageCode 0 * #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AccountProcedure stx)
  (build-fhir-form stx 'AccountProcedure
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec sequence 0 1 #(prim "positiveInt") #f)
      #s(field-spec code 1 1 #(type CodeableReference) #f)
      #s(field-spec dateOfService 0 1 #(prim "dateTime") #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec packageCode 0 * #(type CodeableConcept) #f)
      #s(field-spec device 0 * #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AccountBalance stx)
  (build-fhir-form stx 'AccountBalance
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec aggregate 0 1 #(type CodeableConcept) #f)
      #s(field-spec term 0 1 #(type CodeableConcept) #f)
      #s(field-spec estimate 0 1 #(prim "boolean") #f)
      #s(field-spec amount 1 1 #(type Money) #f)
      )
    #:parent 'BackboneElement))
