#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide ActivityDefinition ActivityDefinitionParticipant ActivityDefinitionDynamicValue)
(define-syntax (ActivityDefinition stx)
  (build-fhir-form stx 'ActivityDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec subtitle 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec usage 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec approvalDate 0 1 #(prim "date") #f)
      #s(field-spec lastReviewDate 0 1 #(prim "date") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(field-spec topic 0 * #(type CodeableConcept) #f)
      #s(field-spec author 0 * #(type ContactDetail) #f)
      #s(field-spec editor 0 * #(type ContactDetail) #f)
      #s(field-spec reviewer 0 * #(type ContactDetail) #f)
      #s(field-spec endorser 0 * #(type ContactDetail) #f)
      #s(field-spec relatedArtifact 0 * #(type RelatedArtifact) #f)
      #s(field-spec library 0 * #(prim "canonical") #f)
      #s(field-spec kind 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-resource-types"))
      #s(field-spec profile 0 1 #(prim "canonical") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec intent 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-intent"))
      #s(field-spec priority 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-priority"))
      #s(field-spec doNotPerform 0 1 #(prim "boolean") #f)
      #s(field-spec location 0 1 #(type CodeableReference) #f)
      #s(field-spec participant 0 * #(type ActivityDefinitionParticipant) #f)
      #s(field-spec quantity 0 1 #(type Quantity) #f)
      #s(field-spec dosage 0 * #(type Dosage) #f)
      #s(field-spec bodySite 0 * #(type CodeableConcept) #f)
      #s(field-spec specimenRequirement 0 * #(prim "canonical") #f)
      #s(field-spec observationRequirement 0 * #(prim "canonical") #f)
      #s(field-spec observationResultRequirement 0 * #(prim "canonical") #f)
      #s(field-spec transform 0 1 #(prim "canonical") #f)
      #s(field-spec dynamicValue 0 * #(type ActivityDefinitionDynamicValue) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(field-spec subjectCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec subjectReference 0 1 #(type Reference) #f)
      #s(field-spec subjectCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec timingTiming 0 1 #(type Timing) #f)
      #s(field-spec timingAge 0 1 #(type Age) #f)
      #s(field-spec timingRange 0 1 #(type Range) #f)
      #s(field-spec timingDuration 0 1 #(type Duration) #f)
      #s(field-spec timingRelativeTime 0 1 #(type RelativeTime) #f)
      #s(field-spec asNeededBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec asNeededCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec productReference 0 1 #(type Reference) #f)
      #s(field-spec productCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      #s(choice-group 0 1 (subjectCodeableConcept subjectReference subjectCanonical))
      #s(choice-group 0 1 (timingTiming timingAge timingRange timingDuration timingRelativeTime))
      #s(choice-group 0 1 (asNeededBoolean asNeededCodeableConcept))
      #s(choice-group 0 1 (productReference productCodeableConcept))
      )
    #:parent 'DomainResource))
(define-syntax (ActivityDefinitionParticipant stx)
  (build-fhir-form stx 'ActivityDefinitionParticipant
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-participant-type"))
      #s(field-spec typeCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec typeReference 0 1 #(type Reference) #f)
      #s(field-spec role 0 1 #(type CodeableConcept) #f)
      #s(field-spec function 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ActivityDefinitionDynamicValue stx)
  (build-fhir-form stx 'ActivityDefinitionDynamicValue
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 1 1 #(prim "string") #f)
      #s(field-spec expression 1 1 #(type Expression) #f)
      )
    #:parent 'BackboneElement))
