#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide AdministrableProductDefinition AdministrableProductDefinitionProperty AdministrableProductDefinitionRouteOfAdministration AdministrableProductDefinitionRouteOfAdministrationTargetSpecies AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod)
(define-syntax (AdministrableProductDefinition stx)
  (build-fhir-form stx 'AdministrableProductDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec formOf 0 * #(type Reference) #f)
      #s(field-spec administrableDoseForm 0 1 #(type CodeableConcept) #f)
      #s(field-spec unitOfPresentation 0 1 #(type CodeableConcept) #f)
      #s(field-spec producedFrom 0 * #(type Reference) #f)
      #s(field-spec ingredient 0 * #(type CodeableConcept) #f)
      #s(field-spec device 0 1 #(type Reference) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec code 0 * #(type Coding) #f)
      #s(field-spec property 0 * #(type AdministrableProductDefinitionProperty) #f)
      #s(field-spec routeOfAdministration 1 * #(type AdministrableProductDefinitionRouteOfAdministration) #f)
      )
    #:parent 'DomainResource))
(define-syntax (AdministrableProductDefinitionProperty stx)
  (build-fhir-form stx 'AdministrableProductDefinitionProperty
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec status 0 1 #(type CodeableConcept) #f)
      #s(field-spec valueCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec valueQuantity 0 1 #(type Quantity) #f)
      #s(field-spec valueRange 0 1 #(type Range) #f)
      #s(field-spec valueDate 0 1 #(prim "date") #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueMarkdown 0 1 #(prim "markdown") #f)
      #s(field-spec valueAttachment 0 1 #(type Attachment) #f)
      #s(field-spec valueReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (valueCodeableConcept valueQuantity valueRange valueDate valueBoolean valueMarkdown valueAttachment valueReference))
      )
    #:parent 'BackboneElement))
(define-syntax (AdministrableProductDefinitionRouteOfAdministration stx)
  (build-fhir-form stx 'AdministrableProductDefinitionRouteOfAdministration
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec firstDose 0 1 #(type Quantity) #f)
      #s(field-spec maxSingleDose 0 1 #(type Quantity) #f)
      #s(field-spec maxDosePerDay 0 1 #(type Quantity) #f)
      #s(field-spec maxDosePerTreatmentPeriod 0 1 #(type Ratio) #f)
      #s(field-spec maxTreatmentPeriod 0 1 #(type Duration) #f)
      #s(field-spec targetSpecies 0 * #(type AdministrableProductDefinitionRouteOfAdministrationTargetSpecies) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AdministrableProductDefinitionRouteOfAdministrationTargetSpecies stx)
  (build-fhir-form stx 'AdministrableProductDefinitionRouteOfAdministrationTargetSpecies
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec withdrawalPeriod 0 * #(type AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod stx)
  (build-fhir-form stx 'AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec tissue 1 1 #(type CodeableConcept) #f)
      #s(field-spec value 1 1 #(type Quantity) #f)
      #s(field-spec supportingInformation 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
