#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide AdverseEvent AdverseEventParticipant AdverseEventSuspectEntity AdverseEventSuspectEntityCausality)
(define-syntax (AdverseEvent stx)
  (build-fhir-form stx 'AdverseEvent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/adverse-event-status"))
      #s(field-spec actuality 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/adverse-event-actuality"))
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec subject 1 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec detected 0 1 #(prim "dateTime") #f)
      #s(field-spec recordedDate 0 1 #(prim "dateTime") #f)
      #s(field-spec resultingEffect 0 * #(type CodeableReference) #f)
      #s(field-spec location 0 1 #(type Reference) #f)
      #s(field-spec seriousness 0 1 #(type CodeableConcept) #f)
      #s(field-spec outcome 0 * #(type CodeableConcept) #f)
      #s(field-spec recorder 0 1 #(type Reference) #f)
      #s(field-spec participant 0 * #(type AdverseEventParticipant) #f)
      #s(field-spec study 0 * #(type Reference) #f)
      #s(field-spec expectedInResearchStudy 0 1 #(prim "boolean") #f)
      #s(field-spec suspectEntity 0 * #(type AdverseEventSuspectEntity) #f)
      #s(field-spec contributingFactor 0 * #(type CodeableReference) #f)
      #s(field-spec preventiveAction 0 * #(type CodeableReference) #f)
      #s(field-spec mitigatingAction 0 * #(type CodeableReference) #f)
      #s(field-spec supportingInfo 0 * #(type CodeableReference) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec effectDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec effectPeriod 0 1 #(type Period) #f)
      #s(choice-group 0 1 (effectDateTime effectPeriod))
      )
    #:parent 'DomainResource))
(define-syntax (AdverseEventParticipant stx)
  (build-fhir-form stx 'AdverseEventParticipant
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec function 0 1 #(type CodeableConcept) #f)
      #s(field-spec actor 1 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AdverseEventSuspectEntity stx)
  (build-fhir-form stx 'AdverseEventSuspectEntity
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec instance 1 1 #(type CodeableReference) #f)
      #s(field-spec causality 0 1 #(type AdverseEventSuspectEntityCausality) #f)
      #s(field-spec occurrenceDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec occurrencePeriod 0 1 #(type Period) #f)
      #s(choice-group 0 1 (occurrenceDateTime occurrencePeriod))
      )
    #:parent 'BackboneElement))
(define-syntax (AdverseEventSuspectEntityCausality stx)
  (build-fhir-form stx 'AdverseEventSuspectEntityCausality
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec assessmentMethod 0 1 #(type CodeableConcept) #f)
      #s(field-spec entityRelatedness 0 1 #(type CodeableConcept) #f)
      #s(field-spec author 0 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
