#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide AllergyIntolerance AllergyIntoleranceReaction)
(define-syntax (AllergyIntolerance stx)
  (build-fhir-form stx 'AllergyIntolerance
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec clinicalStatus 0 1 #(type CodeableConcept) #f)
      #s(field-spec verificationStatus 0 1 #(type CodeableConcept) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec category 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/allergy-intolerance-category"))
      #s(field-spec criticality 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/allergy-intolerance-criticality"))
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec patient 1 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec recordedDate 0 1 #(prim "dateTime") #f)
      #s(field-spec recorder 0 1 #(type Reference) #f)
      #s(field-spec asserter 0 1 #(type Reference) #f)
      #s(field-spec lastReactionOccurrence 0 1 #(prim "dateTime") #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec reaction 0 * #(type AllergyIntoleranceReaction) #f)
      #s(field-spec onsetDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec onsetAge 0 1 #(type Age) #f)
      #s(field-spec onsetPeriod 0 1 #(type Period) #f)
      #s(field-spec onsetRange 0 1 #(type Range) #f)
      #s(field-spec onsetString 0 1 #(prim "string") #f)
      #s(choice-group 0 1 (onsetDateTime onsetAge onsetPeriod onsetRange onsetString))
      )
    #:parent 'DomainResource))
(define-syntax (AllergyIntoleranceReaction stx)
  (build-fhir-form stx 'AllergyIntoleranceReaction
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec substance 0 1 #(type CodeableConcept) #f)
      #s(field-spec manifestation 1 * #(type CodeableReference) #f)
      #s(field-spec description 0 1 #(prim "string") #f)
      #s(field-spec onset 0 1 #(prim "dateTime") #f)
      #s(field-spec severity 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/reaction-event-severity"))
      #s(field-spec exposureRoute 0 1 #(type CodeableConcept) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      )
    #:parent 'BackboneElement))
