#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide AppointmentResponse)
(define-syntax (AppointmentResponse stx)
  (build-fhir-form stx 'AppointmentResponse
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec appointment 1 1 #(type Reference) #f)
      #s(field-spec proposedNewTime 0 1 #(prim "boolean") #f)
      #s(field-spec start 0 1 #(prim "instant") #f)
      #s(field-spec end 0 1 #(prim "instant") #f)
      #s(field-spec participantType 0 * #(type CodeableConcept) #f)
      #s(field-spec actor 0 1 #(type Reference) #f)
      #s(field-spec participantStatus 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/appointmentresponse-status"))
      #s(field-spec comment 0 1 #(prim "markdown") #f)
      #s(field-spec recurring 0 1 #(prim "boolean") #f)
      #s(field-spec occurrenceDate 0 1 #(prim "date") #f)
      #s(field-spec recurrenceId 0 1 #(prim "positiveInt") #f)
      )
    #:parent 'DomainResource))
