#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Appointment AppointmentParticipant AppointmentRecurrenceTemplate AppointmentRecurrenceTemplateWeeklyTemplate AppointmentRecurrenceTemplateMonthlyTemplate AppointmentRecurrenceTemplateYearlyTemplate)
(define-syntax (Appointment stx)
  (build-fhir-form stx 'Appointment
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/appointmentstatus"))
      #s(field-spec cancellationReason 0 1 #(type CodeableConcept) #f)
      #s(field-spec class 0 * #(type CodeableConcept) #f)
      #s(field-spec serviceCategory 0 * #(type CodeableConcept) #f)
      #s(field-spec serviceType 0 * #(type CodeableReference) #f)
      #s(field-spec specialty 0 * #(type CodeableConcept) #f)
      #s(field-spec appointmentType 0 1 #(type CodeableConcept) #f)
      #s(field-spec reason 0 * #(type CodeableReference) #f)
      #s(field-spec priority 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "string") #f)
      #s(field-spec replaces 0 * #(type Reference) #f)
      #s(field-spec virtualService 0 * #(type VirtualServiceDetail) #f)
      #s(field-spec supportingInformation 0 * #(type Reference) #f)
      #s(field-spec previousAppointment 0 1 #(type Reference) #f)
      #s(field-spec originatingAppointment 0 1 #(type Reference) #f)
      #s(field-spec start 0 1 #(prim "instant") #f)
      #s(field-spec end 0 1 #(prim "instant") #f)
      #s(field-spec minutesDuration 0 1 #(prim "positiveInt") #f)
      #s(field-spec requestedPeriod 0 * #(type Period) #f)
      #s(field-spec slot 0 * #(type Reference) #f)
      #s(field-spec account 0 * #(type Reference) #f)
      #s(field-spec created 0 1 #(prim "dateTime") #f)
      #s(field-spec cancellationDate 0 1 #(prim "dateTime") #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec patientInstruction 0 * #(type CodeableReference) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec participant 1 * #(type AppointmentParticipant) #f)
      #s(field-spec recurrenceId 0 1 #(prim "positiveInt") #f)
      #s(field-spec occurrenceChanged 0 1 #(prim "boolean") #f)
      #s(field-spec recurrenceTemplate 0 * #(type AppointmentRecurrenceTemplate) #f)
      )
    #:parent 'DomainResource))
(define-syntax (AppointmentParticipant stx)
  (build-fhir-form stx 'AppointmentParticipant
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec actor 0 1 #(type Reference) #f)
      #s(field-spec required 0 1 #(prim "boolean") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/participationstatus"))
      )
    #:parent 'BackboneElement))
(define-syntax (AppointmentRecurrenceTemplate stx)
  (build-fhir-form stx 'AppointmentRecurrenceTemplate
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec timezone 0 1 #(type CodeableConcept) #f)
      #s(field-spec recurrenceType 1 1 #(type CodeableConcept) #f)
      #s(field-spec lastOccurrenceDate 0 1 #(prim "date") #f)
      #s(field-spec occurrenceCount 0 1 #(prim "positiveInt") #f)
      #s(field-spec occurrenceDate 0 * #(prim "date") #f)
      #s(field-spec weeklyTemplate 0 1 #(type AppointmentRecurrenceTemplateWeeklyTemplate) #f)
      #s(field-spec monthlyTemplate 0 1 #(type AppointmentRecurrenceTemplateMonthlyTemplate) #f)
      #s(field-spec yearlyTemplate 0 1 #(type AppointmentRecurrenceTemplateYearlyTemplate) #f)
      #s(field-spec excludingDate 0 * #(prim "date") #f)
      #s(field-spec excludingRecurrenceId 0 * #(prim "positiveInt") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AppointmentRecurrenceTemplateWeeklyTemplate stx)
  (build-fhir-form stx 'AppointmentRecurrenceTemplateWeeklyTemplate
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec monday 0 1 #(prim "boolean") #f)
      #s(field-spec tuesday 0 1 #(prim "boolean") #f)
      #s(field-spec wednesday 0 1 #(prim "boolean") #f)
      #s(field-spec thursday 0 1 #(prim "boolean") #f)
      #s(field-spec friday 0 1 #(prim "boolean") #f)
      #s(field-spec saturday 0 1 #(prim "boolean") #f)
      #s(field-spec sunday 0 1 #(prim "boolean") #f)
      #s(field-spec weekInterval 0 1 #(prim "positiveInt") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AppointmentRecurrenceTemplateMonthlyTemplate stx)
  (build-fhir-form stx 'AppointmentRecurrenceTemplateMonthlyTemplate
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec dayOfMonth 0 1 #(prim "positiveInt") #f)
      #s(field-spec nthWeekOfMonth 0 1 #(type Coding) #f)
      #s(field-spec dayOfWeek 0 1 #(type Coding) #f)
      #s(field-spec monthInterval 1 1 #(prim "positiveInt") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AppointmentRecurrenceTemplateYearlyTemplate stx)
  (build-fhir-form stx 'AppointmentRecurrenceTemplateYearlyTemplate
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec yearInterval 1 1 #(prim "positiveInt") #f)
      )
    #:parent 'BackboneElement))
