#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide AuditEvent AuditEventOutcome AuditEventAgent AuditEventSource AuditEventEntity AuditEventEntityDetail)
(define-syntax (AuditEvent stx)
  (build-fhir-form stx 'AuditEvent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec subtype 0 * #(type CodeableConcept) #f)
      #s(field-spec action 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/audit-event-action"))
      #s(field-spec severity 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/audit-event-severity"))
      #s(field-spec recorded 1 1 #(prim "instant") #f)
      #s(field-spec outcome 0 1 #(type AuditEventOutcome) #f)
      #s(field-spec authorization 0 * #(type CodeableConcept) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec patient 0 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec agent 1 * #(type AuditEventAgent) #f)
      #s(field-spec source 1 1 #(type AuditEventSource) #f)
      #s(field-spec entity 0 * #(type AuditEventEntity) #f)
      #s(field-spec occurredPeriod 0 1 #(type Period) #f)
      #s(field-spec occurredDateTime 0 1 #(prim "dateTime") #f)
      #s(choice-group 0 1 (occurredPeriod occurredDateTime))
      )
    #:parent 'DomainResource))
(define-syntax (AuditEventOutcome stx)
  (build-fhir-form stx 'AuditEventOutcome
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type Coding) #f)
      #s(field-spec detail 0 * #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AuditEventAgent stx)
  (build-fhir-form stx 'AuditEventAgent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec role 0 * #(type CodeableConcept) #f)
      #s(field-spec who 1 1 #(type Reference) #f)
      #s(field-spec requestor 0 1 #(prim "boolean") #f)
      #s(field-spec location 0 1 #(type Reference) #f)
      #s(field-spec policy 0 * #(prim "uri") #f)
      #s(field-spec authorization 0 * #(type CodeableConcept) #f)
      #s(field-spec networkReference 0 1 #(type Reference) #f)
      #s(field-spec networkUri 0 1 #(prim "uri") #f)
      #s(field-spec networkString 0 1 #(prim "string") #f)
      #s(choice-group 0 1 (networkReference networkUri networkString))
      )
    #:parent 'BackboneElement))
(define-syntax (AuditEventSource stx)
  (build-fhir-form stx 'AuditEventSource
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec site 0 1 #(type Reference) #f)
      #s(field-spec observer 1 1 #(type Reference) #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AuditEventEntity stx)
  (build-fhir-form stx 'AuditEventEntity
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec what 0 1 #(type Reference) #f)
      #s(field-spec role 0 1 #(type CodeableConcept) #f)
      #s(field-spec securityLabel 0 * #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "string") #f)
      #s(field-spec query 0 1 #(prim "base64Binary") #f)
      #s(field-spec detail 0 * #(type AuditEventEntityDetail) #f)
      #s(field-spec agent 0 * #(type AuditEventAgent) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (AuditEventEntityDetail stx)
  (build-fhir-form stx 'AuditEventEntityDetail
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec valueQuantity 0 1 #(type Quantity) #f)
      #s(field-spec valueCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueRange 0 1 #(type Range) #f)
      #s(field-spec valueRatio 0 1 #(type Ratio) #f)
      #s(field-spec valueTime 0 1 #(prim "time") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec valuePeriod 0 1 #(type Period) #f)
      #s(field-spec valueBase64Binary 0 1 #(prim "base64Binary") #f)
      #s(choice-group 1 1 (valueQuantity valueCodeableConcept valueString valueBoolean valueInteger valueRange valueRatio valueTime valueDateTime valuePeriod valueBase64Binary))
      )
    #:parent 'BackboneElement))
