#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide BiologicallyDerivedProduct BiologicallyDerivedProductCollection BiologicallyDerivedProductProperty)
(define-syntax (BiologicallyDerivedProduct stx)
  (build-fhir-form stx 'BiologicallyDerivedProduct
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec productCategory 0 * #(type CodeableConcept) #f)
      #s(field-spec productCode 0 1 #(type CodeableConcept) #f)
      #s(field-spec parent 0 * #(type Reference) #f)
      #s(field-spec request 0 * #(type Reference) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec therapyIdentifier 0 * #(type Identifier) #f)
      #s(field-spec biologicalSourceEvent 0 1 #(type Identifier) #f)
      #s(field-spec processingFacility 0 * #(type Reference) #f)
      #s(field-spec division 0 1 #(prim "string") #f)
      #s(field-spec productStatus 0 1 #(type Coding) #f)
      #s(field-spec expirationDate 0 1 #(prim "dateTime") #f)
      #s(field-spec collection 0 1 #(type BiologicallyDerivedProductCollection) #f)
      #s(field-spec storageTempRequirements 0 1 #(type Range) #f)
      #s(field-spec property 0 * #(type BiologicallyDerivedProductProperty) #f)
      )
    #:parent 'DomainResource))
(define-syntax (BiologicallyDerivedProductCollection stx)
  (build-fhir-form stx 'BiologicallyDerivedProductCollection
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec collector 0 1 #(type Reference) #f)
      #s(field-spec sourcePatient 0 1 #(type Reference) #f)
      #s(field-spec sourceOrganization 0 1 #(type Reference) #f)
      #s(field-spec procedure 0 1 #(type Reference) #f)
      #s(field-spec collectedDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec collectedPeriod 0 1 #(type Period) #f)
      #s(choice-group 0 1 (collectedDateTime collectedPeriod))
      )
    #:parent 'BackboneElement))
(define-syntax (BiologicallyDerivedProductProperty stx)
  (build-fhir-form stx 'BiologicallyDerivedProductProperty
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec valuePeriod 0 1 #(type Period) #f)
      #s(field-spec valueQuantity 0 1 #(type Quantity) #f)
      #s(field-spec valueRange 0 1 #(type Range) #f)
      #s(field-spec valueRatio 0 1 #(type Ratio) #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valueAttachment 0 1 #(type Attachment) #f)
      #s(choice-group 1 1 (valueBoolean valueInteger valueCodeableConcept valuePeriod valueQuantity valueRange valueRatio valueString valueAttachment))
      )
    #:parent 'BackboneElement))
