#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Bundle BundleLink BundleEntry BundleEntrySearch BundleEntryRequest BundleEntryResponse)
(define-syntax (Bundle stx)
  (build-fhir-form stx 'Bundle
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec identifier 0 1 #(type Identifier) #f)
      #s(field-spec type 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/bundle-type"))
      #s(field-spec timestamp 0 1 #(prim "instant") #f)
      #s(field-spec total 0 1 #(prim "unsignedInt") #f)
      #s(field-spec link 0 * #(type BundleLink) #f)
      #s(field-spec entry 0 * #(type BundleEntry) #f)
      #s(field-spec signature 0 1 #(type Signature) #f)
      #s(field-spec issues 0 1 #(resource) #f)
      )
    #:parent 'Resource))
(define-syntax (BundleLink stx)
  (build-fhir-form stx 'BundleLink
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec relation 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/iana-link-relations"))
      #s(field-spec url 1 1 #(prim "uri") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (BundleEntry stx)
  (build-fhir-form stx 'BundleEntry
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec link 0 * #(type BundleLink) #f)
      #s(field-spec fullUrl 0 1 #(prim "uri") #f)
      #s(field-spec resource 0 1 #(resource) #f)
      #s(field-spec search 0 1 #(type BundleEntrySearch) #f)
      #s(field-spec request 0 1 #(type BundleEntryRequest) #f)
      #s(field-spec response 0 1 #(type BundleEntryResponse) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (BundleEntrySearch stx)
  (build-fhir-form stx 'BundleEntrySearch
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec mode 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/search-entry-mode"))
      #s(field-spec score 0 1 #(prim "decimal") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (BundleEntryRequest stx)
  (build-fhir-form stx 'BundleEntryRequest
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec method 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/http-verb"))
      #s(field-spec url 1 1 #(prim "uri") #f)
      #s(field-spec ifNoneMatch 0 1 #(prim "string") #f)
      #s(field-spec ifModifiedSince 0 1 #(prim "instant") #f)
      #s(field-spec ifMatch 0 1 #(prim "string") #f)
      #s(field-spec ifNoneExist 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (BundleEntryResponse stx)
  (build-fhir-form stx 'BundleEntryResponse
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec status 1 1 #(prim "string") #f)
      #s(field-spec location 0 1 #(prim "uri") #f)
      #s(field-spec etag 0 1 #(prim "string") #f)
      #s(field-spec lastModified 0 1 #(prim "instant") #f)
      #s(field-spec outcome 0 1 #(resource) #f)
      )
    #:parent 'BackboneElement))
