#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide CarePlan CarePlanActivity)
(define-syntax (CarePlan stx)
  (build-fhir-form stx 'CarePlan
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec replaces 0 * #(type Reference) #f)
      #s(field-spec partOf 0 * #(type Reference) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-status"))
      #s(field-spec intent 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/care-plan-intent"))
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "string") #f)
      #s(field-spec subject 1 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec created 0 1 #(prim "dateTime") #f)
      #s(field-spec custodian 0 1 #(type Reference) #f)
      #s(field-spec contributor 0 * #(type Reference) #f)
      #s(field-spec careTeam 0 * #(type Reference) #f)
      #s(field-spec addresses 0 * #(type CodeableReference) #f)
      #s(field-spec supportingInfo 0 * #(type Reference) #f)
      #s(field-spec goal 0 * #(type Reference) #f)
      #s(field-spec activity 0 * #(type CarePlanActivity) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      )
    #:parent 'DomainResource))
(define-syntax (CarePlanActivity stx)
  (build-fhir-form stx 'CarePlanActivity
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec performedActivity 0 * #(type CodeableReference) #f)
      #s(field-spec progress 0 * #(type Annotation) #f)
      #s(field-spec plannedActivityReference 0 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
