#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide ClinicalUseDefinition ClinicalUseDefinitionUndesirableEffect ClinicalUseDefinitionIndication ClinicalUseDefinitionIndicationOtherTherapy ClinicalUseDefinitionContraindication ClinicalUseDefinitionInteraction ClinicalUseDefinitionInteractionInteractant ClinicalUseDefinitionWarning)
(define-syntax (ClinicalUseDefinition stx)
  (build-fhir-form stx 'ClinicalUseDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec type 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/clinical-use-definition-type"))
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec subject 1 * #(type CodeableReference) #f)
      #s(field-spec status 0 1 #(type CodeableConcept) #f)
      #s(field-spec undesirableEffect 0 1 #(type ClinicalUseDefinitionUndesirableEffect) #f)
      #s(field-spec indication 0 1 #(type ClinicalUseDefinitionIndication) #f)
      #s(field-spec contraindication 0 1 #(type ClinicalUseDefinitionContraindication) #f)
      #s(field-spec interaction 0 1 #(type ClinicalUseDefinitionInteraction) #f)
      #s(field-spec population 0 * #(type Reference) #f)
      #s(field-spec library 0 * #(prim "canonical") #f)
      #s(field-spec warning 0 1 #(type ClinicalUseDefinitionWarning) #f)
      )
    #:parent 'DomainResource))
(define-syntax (ClinicalUseDefinitionUndesirableEffect stx)
  (build-fhir-form stx 'ClinicalUseDefinitionUndesirableEffect
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec symptomConditionEffect 0 1 #(type CodeableReference) #f)
      #s(field-spec classification 0 1 #(type CodeableConcept) #f)
      #s(field-spec frequencyOfOccurrence 0 1 #(type CodeableConcept) #f)
      #s(field-spec management 0 * #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ClinicalUseDefinitionIndication stx)
  (build-fhir-form stx 'ClinicalUseDefinitionIndication
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec diseaseSymptomProcedure 0 1 #(type CodeableReference) #f)
      #s(field-spec diseaseStatus 0 1 #(type CodeableReference) #f)
      #s(field-spec comorbidity 0 * #(type CodeableReference) #f)
      #s(field-spec intendedEffect 0 * #(type CodeableReference) #f)
      #s(field-spec undesirableEffect 0 * #(type ClinicalUseDefinitionUndesirableEffect) #f)
      #s(field-spec applicability 0 1 #(type Expression) #f)
      #s(field-spec otherTherapy 0 * #(type ClinicalUseDefinitionIndicationOtherTherapy) #f)
      #s(field-spec durationRange 0 1 #(type Range) #f)
      #s(field-spec durationString 0 1 #(prim "string") #f)
      #s(choice-group 0 1 (durationRange durationString))
      )
    #:parent 'BackboneElement))
(define-syntax (ClinicalUseDefinitionIndicationOtherTherapy stx)
  (build-fhir-form stx 'ClinicalUseDefinitionIndicationOtherTherapy
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec relationshipType 1 1 #(type CodeableConcept) #f)
      #s(field-spec treatment 1 1 #(type CodeableReference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ClinicalUseDefinitionContraindication stx)
  (build-fhir-form stx 'ClinicalUseDefinitionContraindication
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec diseaseSymptomProcedure 0 1 #(type CodeableReference) #f)
      #s(field-spec diseaseStatus 0 1 #(type CodeableReference) #f)
      #s(field-spec comorbidity 0 * #(type CodeableReference) #f)
      #s(field-spec indication 0 * #(type ClinicalUseDefinitionIndication) #f)
      #s(field-spec applicability 0 1 #(type Expression) #f)
      #s(field-spec management 0 * #(type CodeableConcept) #f)
      #s(field-spec otherTherapy 0 * #(type ClinicalUseDefinitionIndicationOtherTherapy) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ClinicalUseDefinitionInteraction stx)
  (build-fhir-form stx 'ClinicalUseDefinitionInteraction
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec interactant 0 * #(type ClinicalUseDefinitionInteractionInteractant) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec effect 0 1 #(type CodeableReference) #f)
      #s(field-spec incidence 0 1 #(type CodeableConcept) #f)
      #s(field-spec management 0 * #(type CodeableConcept) #f)
      #s(field-spec severity 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ClinicalUseDefinitionInteractionInteractant stx)
  (build-fhir-form stx 'ClinicalUseDefinitionInteractionInteractant
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec route 0 1 #(type CodeableConcept) #f)
      #s(field-spec itemReference 0 1 #(type Reference) #f)
      #s(field-spec itemCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(choice-group 1 1 (itemReference itemCodeableConcept))
      )
    #:parent 'BackboneElement))
(define-syntax (ClinicalUseDefinitionWarning stx)
  (build-fhir-form stx 'ClinicalUseDefinitionWarning
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
