#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide CommunicationRequest CommunicationRequestPayload)
(define-syntax (CommunicationRequest stx)
  (build-fhir-form stx 'CommunicationRequest
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec replaces 0 * #(type Reference) #f)
      #s(field-spec groupIdentifier 0 1 #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-status"))
      #s(field-spec statusReason 0 1 #(type CodeableConcept) #f)
      #s(field-spec intent 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-intent"))
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec priority 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-priority"))
      #s(field-spec doNotPerform 0 1 #(prim "boolean") #f)
      #s(field-spec medium 0 * #(type CodeableConcept) #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec about 0 * #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec payload 0 * #(type CommunicationRequestPayload) #f)
      #s(field-spec authoredOn 0 1 #(prim "dateTime") #f)
      #s(field-spec requester 0 1 #(type Reference) #f)
      #s(field-spec recipient 0 * #(type Reference) #f)
      #s(field-spec informationProvider 0 * #(type Reference) #f)
      #s(field-spec reason 0 * #(type CodeableReference) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec occurrenceDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec occurrencePeriod 0 1 #(type Period) #f)
      #s(choice-group 0 1 (occurrenceDateTime occurrencePeriod))
      )
    #:parent 'DomainResource))
(define-syntax (CommunicationRequestPayload stx)
  (build-fhir-form stx 'CommunicationRequestPayload
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec contentAttachment 0 1 #(type Attachment) #f)
      #s(field-spec contentReference 0 1 #(type Reference) #f)
      #s(field-spec contentCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(choice-group 1 1 (contentAttachment contentReference contentCodeableConcept))
      )
    #:parent 'BackboneElement))
