#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Contract ContractContentDefinition ContractTerm ContractTermSecurityLabel ContractTermOffer ContractTermOfferParty ContractTermOfferAnswer ContractTermAsset ContractTermAssetContext ContractTermAssetValuedItem ContractTermAction ContractTermActionSubject ContractSigner ContractFriendly ContractLegal ContractRule)
(define-syntax (Contract stx)
  (build-fhir-form stx 'Contract
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec status 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/contract-status"))
      #s(field-spec legalState 0 1 #(type CodeableConcept) #f)
      #s(field-spec instantiatesCanonical 0 1 #(type Reference) #f)
      #s(field-spec instantiatesUri 0 1 #(prim "uri") #f)
      #s(field-spec contentDerivative 0 1 #(type CodeableConcept) #f)
      #s(field-spec issued 0 1 #(prim "dateTime") #f)
      #s(field-spec applies 0 1 #(type Period) #f)
      #s(field-spec expirationType 0 1 #(type CodeableConcept) #f)
      #s(field-spec subject 0 * #(type Reference) #f)
      #s(field-spec authority 0 * #(type Reference) #f)
      #s(field-spec domain 0 * #(type Reference) #f)
      #s(field-spec site 0 * #(type Reference) #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec subtitle 0 1 #(prim "string") #f)
      #s(field-spec alias 0 * #(prim "string") #f)
      #s(field-spec author 0 1 #(type Reference) #f)
      #s(field-spec scope 0 1 #(type CodeableConcept) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec subType 0 * #(type CodeableConcept) #f)
      #s(field-spec contentDefinition 0 1 #(type ContractContentDefinition) #f)
      #s(field-spec term 0 * #(type ContractTerm) #f)
      #s(field-spec supportingInfo 0 * #(type Reference) #f)
      #s(field-spec relevantHistory 0 * #(type Reference) #f)
      #s(field-spec signer 0 * #(type ContractSigner) #f)
      #s(field-spec friendly 0 * #(type ContractFriendly) #f)
      #s(field-spec legal 0 * #(type ContractLegal) #f)
      #s(field-spec rule 0 * #(type ContractRule) #f)
      #s(field-spec topicCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec topicReference 0 1 #(type Reference) #f)
      #s(field-spec legallyBindingAttachment 0 1 #(type Attachment) #f)
      #s(field-spec legallyBindingReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (topicCodeableConcept topicReference))
      #s(choice-group 0 1 (legallyBindingAttachment legallyBindingReference))
      )
    #:parent 'DomainResource))
(define-syntax (ContractContentDefinition stx)
  (build-fhir-form stx 'ContractContentDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec subType 0 1 #(type CodeableConcept) #f)
      #s(field-spec publisher 0 1 #(type Reference) #f)
      #s(field-spec publicationDate 0 1 #(prim "dateTime") #f)
      #s(field-spec publicationStatus 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/contract-publicationstatus"))
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTerm stx)
  (build-fhir-form stx 'ContractTerm
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 1 #(type Identifier) #f)
      #s(field-spec issued 0 1 #(prim "dateTime") #f)
      #s(field-spec applies 0 1 #(type Period) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec subType 0 1 #(type CodeableConcept) #f)
      #s(field-spec text 0 1 #(prim "markdown") #f)
      #s(field-spec securityLabel 0 * #(type ContractTermSecurityLabel) #f)
      #s(field-spec offer 1 1 #(type ContractTermOffer) #f)
      #s(field-spec asset 0 * #(type ContractTermAsset) #f)
      #s(field-spec action 0 * #(type ContractTermAction) #f)
      #s(field-spec group 0 * #(type ContractTerm) #f)
      #s(field-spec topicCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec topicReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (topicCodeableConcept topicReference))
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermSecurityLabel stx)
  (build-fhir-form stx 'ContractTermSecurityLabel
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec number 0 * #(prim "unsignedInt") #f)
      #s(field-spec classification 1 1 #(type Coding) #f)
      #s(field-spec category 0 * #(type Coding) #f)
      #s(field-spec control 0 * #(type Coding) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermOffer stx)
  (build-fhir-form stx 'ContractTermOffer
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec party 0 * #(type ContractTermOfferParty) #f)
      #s(field-spec topic 0 1 #(type Reference) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec decision 0 1 #(type CodeableConcept) #f)
      #s(field-spec decisionMode 0 * #(type CodeableConcept) #f)
      #s(field-spec answer 0 * #(type ContractTermOfferAnswer) #f)
      #s(field-spec text 0 1 #(prim "string") #f)
      #s(field-spec linkId 0 * #(prim "string") #f)
      #s(field-spec securityLabelNumber 0 * #(prim "unsignedInt") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermOfferParty stx)
  (build-fhir-form stx 'ContractTermOfferParty
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec reference 1 * #(type Reference) #f)
      #s(field-spec role 1 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermOfferAnswer stx)
  (build-fhir-form stx 'ContractTermOfferAnswer
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueDecimal 0 1 #(prim "decimal") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueDate 0 1 #(prim "date") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec valueTime 0 1 #(prim "time") #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valueUri 0 1 #(prim "uri") #f)
      #s(field-spec valueAttachment 0 1 #(type Attachment) #f)
      #s(field-spec valueCoding 0 1 #(type Coding) #f)
      #s(field-spec valueQuantity 0 1 #(type Quantity) #f)
      #s(field-spec valueReference 0 1 #(type Reference) #f)
      #s(choice-group 1 1 (valueBoolean valueDecimal valueInteger valueDate valueDateTime valueTime valueString valueUri valueAttachment valueCoding valueQuantity valueReference))
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermAsset stx)
  (build-fhir-form stx 'ContractTermAsset
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec scope 0 1 #(type CodeableConcept) #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec typeReference 0 * #(type Reference) #f)
      #s(field-spec subtype 0 * #(type CodeableConcept) #f)
      #s(field-spec relationship 0 1 #(type Coding) #f)
      #s(field-spec context 0 * #(type ContractTermAssetContext) #f)
      #s(field-spec condition 0 1 #(prim "string") #f)
      #s(field-spec periodType 0 * #(type CodeableConcept) #f)
      #s(field-spec period 0 * #(type Period) #f)
      #s(field-spec usePeriod 0 * #(type Period) #f)
      #s(field-spec text 0 1 #(prim "string") #f)
      #s(field-spec linkId 0 * #(prim "string") #f)
      #s(field-spec answer 0 * #(type ContractTermOfferAnswer) #f)
      #s(field-spec securityLabelNumber 0 * #(prim "unsignedInt") #f)
      #s(field-spec valuedItem 0 * #(type ContractTermAssetValuedItem) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermAssetContext stx)
  (build-fhir-form stx 'ContractTermAssetContext
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec reference 0 1 #(type Reference) #f)
      #s(field-spec code 0 * #(type CodeableConcept) #f)
      #s(field-spec text 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermAssetValuedItem stx)
  (build-fhir-form stx 'ContractTermAssetValuedItem
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 1 #(type Identifier) #f)
      #s(field-spec effectiveTime 0 1 #(prim "dateTime") #f)
      #s(field-spec quantity 0 1 #(type Quantity) #f)
      #s(field-spec unitPrice 0 1 #(type Money) #f)
      #s(field-spec factor 0 1 #(prim "decimal") #f)
      #s(field-spec points 0 1 #(prim "decimal") #f)
      #s(field-spec net 0 1 #(type Money) #f)
      #s(field-spec payment 0 1 #(prim "string") #f)
      #s(field-spec paymentDate 0 1 #(prim "dateTime") #f)
      #s(field-spec responsible 0 1 #(type Reference) #f)
      #s(field-spec recipient 0 1 #(type Reference) #f)
      #s(field-spec linkId 0 * #(prim "string") #f)
      #s(field-spec securityLabelNumber 0 * #(prim "unsignedInt") #f)
      #s(field-spec entityCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec entityReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (entityCodeableConcept entityReference))
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermAction stx)
  (build-fhir-form stx 'ContractTermAction
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec doNotPerform 0 1 #(prim "boolean") #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec subject 0 * #(type ContractTermActionSubject) #f)
      #s(field-spec intent 1 1 #(type CodeableConcept) #f)
      #s(field-spec linkId 0 * #(prim "string") #f)
      #s(field-spec status 1 1 #(type CodeableConcept) #f)
      #s(field-spec context 0 1 #(type Reference) #f)
      #s(field-spec contextLinkId 0 * #(prim "string") #f)
      #s(field-spec requester 0 * #(type Reference) #f)
      #s(field-spec requesterLinkId 0 * #(prim "string") #f)
      #s(field-spec performerType 0 * #(type CodeableConcept) #f)
      #s(field-spec performerRole 0 1 #(type CodeableConcept) #f)
      #s(field-spec performer 0 1 #(type Reference) #f)
      #s(field-spec performerLinkId 0 * #(prim "string") #f)
      #s(field-spec reason 0 * #(type CodeableReference) #f)
      #s(field-spec reasonLinkId 0 * #(prim "string") #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec securityLabelNumber 0 * #(prim "unsignedInt") #f)
      #s(field-spec occurrenceDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec occurrencePeriod 0 1 #(type Period) #f)
      #s(field-spec occurrenceTiming 0 1 #(type Timing) #f)
      #s(choice-group 0 1 (occurrenceDateTime occurrencePeriod occurrenceTiming))
      )
    #:parent 'BackboneElement))
(define-syntax (ContractTermActionSubject stx)
  (build-fhir-form stx 'ContractTermActionSubject
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec reference 1 * #(type Reference) #f)
      #s(field-spec role 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractSigner stx)
  (build-fhir-form stx 'ContractSigner
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type Coding) #f)
      #s(field-spec party 1 1 #(type Reference) #f)
      #s(field-spec signature 1 * #(type Signature) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ContractFriendly stx)
  (build-fhir-form stx 'ContractFriendly
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec contentAttachment 0 1 #(type Attachment) #f)
      #s(field-spec contentReference 0 1 #(type Reference) #f)
      #s(choice-group 1 1 (contentAttachment contentReference))
      )
    #:parent 'BackboneElement))
(define-syntax (ContractLegal stx)
  (build-fhir-form stx 'ContractLegal
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec contentAttachment 0 1 #(type Attachment) #f)
      #s(field-spec contentReference 0 1 #(type Reference) #f)
      #s(choice-group 1 1 (contentAttachment contentReference))
      )
    #:parent 'BackboneElement))
(define-syntax (ContractRule stx)
  (build-fhir-form stx 'ContractRule
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec contentAttachment 0 1 #(type Attachment) #f)
      #s(field-spec contentReference 0 1 #(type Reference) #f)
      #s(choice-group 1 1 (contentAttachment contentReference))
      )
    #:parent 'BackboneElement))
