#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide DetectedIssue DetectedIssueEvidence DetectedIssueMitigation)
(define-syntax (DetectedIssue stx)
  (build-fhir-form stx 'DetectedIssue
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/detectedissue-status"))
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec severity 0 1 #(type CodeableConcept) #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec author 0 1 #(type Reference) #f)
      #s(field-spec implicated 0 * #(type Reference) #f)
      #s(field-spec evidence 0 * #(type DetectedIssueEvidence) #f)
      #s(field-spec detail 0 1 #(prim "markdown") #f)
      #s(field-spec reference 0 1 #(prim "uri") #f)
      #s(field-spec qualityOfEvidence 0 1 #(type CodeableConcept) #f)
      #s(field-spec expectedOnsetType 0 1 #(type CodeableConcept) #f)
      #s(field-spec medicationClass 0 * #(type CodeableConcept) #f)
      #s(field-spec managementCode 0 1 #(type CodeableConcept) #f)
      #s(field-spec mitigation 0 * #(type DetectedIssueMitigation) #f)
      #s(field-spec identifiedDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec identifiedPeriod 0 1 #(type Period) #f)
      #s(field-spec identifiedTiming 0 1 #(type Timing) #f)
      #s(choice-group 0 1 (identifiedDateTime identifiedPeriod identifiedTiming))
      )
    #:parent 'DomainResource))
(define-syntax (DetectedIssueEvidence stx)
  (build-fhir-form stx 'DetectedIssueEvidence
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 0 * #(type CodeableConcept) #f)
      #s(field-spec detail 0 * #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (DetectedIssueMitigation stx)
  (build-fhir-form stx 'DetectedIssueMitigation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec action 1 1 #(type CodeableConcept) #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec author 0 1 #(type Reference) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      )
    #:parent 'BackboneElement))
