#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide DeviceMetric DeviceMetricCalibration)
(define-syntax (DeviceMetric stx)
  (build-fhir-form stx 'DeviceMetric
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/metric-status"))
      #s(field-spec operationalStatus 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/metric-operational-status"))
      #s(field-spec category 1 1 #(type CodeableConcept) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec device 1 1 #(type Reference) #f)
      #s(field-spec unit 0 1 #(type CodeableConcept) #f)
      #s(field-spec color 0 1 #(type CodeableConcept) #f)
      #s(field-spec measurementFrequency 0 1 #(type Quantity) #f)
      #s(field-spec availability 0 1 #(type CodeableConcept) #f)
      #s(field-spec calibration 0 * #(type DeviceMetricCalibration) #f)
      )
    #:parent 'DomainResource))
(define-syntax (DeviceMetricCalibration stx)
  (build-fhir-form stx 'DeviceMetricCalibration
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec state 0 1 #(type CodeableConcept) #f)
      #s(field-spec time 0 1 #(prim "instant") #f)
      )
    #:parent 'BackboneElement))
