#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide DiagnosticReport DiagnosticReportSupportingInfo DiagnosticReportMedia)
(define-syntax (DiagnosticReport stx)
  (build-fhir-form stx 'DiagnosticReport
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/diagnostic-report-status"))
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec relatesTo 0 * #(type RelatedArtifact) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec issued 0 1 #(prim "dateTime") #f)
      #s(field-spec procedure 0 * #(type Reference) #f)
      #s(field-spec performer 0 * #(type Reference) #f)
      #s(field-spec resultsInterpreter 0 * #(type Reference) #f)
      #s(field-spec specimen 0 * #(type Reference) #f)
      #s(field-spec result 0 * #(type Reference) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec study 0 * #(type Reference) #f)
      #s(field-spec supportingInfo 0 * #(type DiagnosticReportSupportingInfo) #f)
      #s(field-spec media 0 * #(type DiagnosticReportMedia) #f)
      #s(field-spec composition 0 1 #(type Reference) #f)
      #s(field-spec conclusion 0 1 #(prim "markdown") #f)
      #s(field-spec conclusionCode 0 * #(type CodeableReference) #f)
      #s(field-spec recommendation 0 * #(type CodeableReference) #f)
      #s(field-spec presentedForm 0 * #(type Attachment) #f)
      #s(field-spec communication 0 * #(type Reference) #f)
      #s(field-spec comparison 0 1 #(type Reference) #f)
      #s(field-spec effectiveDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(choice-group 0 1 (effectiveDateTime effectivePeriod))
      )
    #:parent 'DomainResource))
(define-syntax (DiagnosticReportSupportingInfo stx)
  (build-fhir-form stx 'DiagnosticReportSupportingInfo
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec reference 1 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (DiagnosticReportMedia stx)
  (build-fhir-form stx 'DiagnosticReportMedia
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec comment 0 1 #(prim "string") #f)
      #s(field-spec link 1 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
