#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Encounter EncounterBusinessStatus EncounterParticipant EncounterReason EncounterDiagnosis EncounterAdmission EncounterLocation)
(define-syntax (Encounter stx)
  (build-fhir-form stx 'Encounter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/encounter-status"))
      #s(field-spec businessStatus 0 * #(type EncounterBusinessStatus) #f)
      #s(field-spec class 0 * #(type CodeableConcept) #f)
      #s(field-spec priority 0 1 #(type CodeableConcept) #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec serviceType 0 * #(type CodeableReference) #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec subjectStatus 0 1 #(type CodeableConcept) #f)
      #s(field-spec episodeOfCare 0 * #(type Reference) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec careTeam 0 * #(type Reference) #f)
      #s(field-spec partOf 0 1 #(type Reference) #f)
      #s(field-spec serviceProvider 0 1 #(type Reference) #f)
      #s(field-spec participant 0 * #(type EncounterParticipant) #f)
      #s(field-spec appointment 0 * #(type Reference) #f)
      #s(field-spec virtualService 0 * #(type VirtualServiceDetail) #f)
      #s(field-spec actualPeriod 0 1 #(type Period) #f)
      #s(field-spec plannedStartDate 0 1 #(prim "dateTime") #f)
      #s(field-spec plannedEndDate 0 1 #(prim "dateTime") #f)
      #s(field-spec length 0 1 #(type Duration) #f)
      #s(field-spec reason 0 * #(type EncounterReason) #f)
      #s(field-spec diagnosis 0 * #(type EncounterDiagnosis) #f)
      #s(field-spec account 0 * #(type Reference) #f)
      #s(field-spec dietPreference 0 * #(type CodeableConcept) #f)
      #s(field-spec specialArrangement 0 * #(type CodeableConcept) #f)
      #s(field-spec specialCourtesy 0 * #(type CodeableConcept) #f)
      #s(field-spec admission 0 1 #(type EncounterAdmission) #f)
      #s(field-spec location 0 * #(type EncounterLocation) #f)
      )
    #:parent 'DomainResource))
(define-syntax (EncounterBusinessStatus stx)
  (build-fhir-form stx 'EncounterBusinessStatus
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec type 0 1 #(type Coding) #f)
      #s(field-spec effectiveDate 0 1 #(prim "dateTime") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (EncounterParticipant stx)
  (build-fhir-form stx 'EncounterParticipant
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec actor 0 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (EncounterReason stx)
  (build-fhir-form stx 'EncounterReason
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec use 0 * #(type CodeableConcept) #f)
      #s(field-spec value 0 * #(type CodeableReference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (EncounterDiagnosis stx)
  (build-fhir-form stx 'EncounterDiagnosis
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec condition 0 * #(type CodeableReference) #f)
      #s(field-spec use 0 * #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (EncounterAdmission stx)
  (build-fhir-form stx 'EncounterAdmission
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec preAdmissionIdentifier 0 1 #(type Identifier) #f)
      #s(field-spec origin 0 1 #(type Reference) #f)
      #s(field-spec admitSource 0 1 #(type CodeableConcept) #f)
      #s(field-spec reAdmission 0 1 #(type CodeableConcept) #f)
      #s(field-spec destination 0 1 #(type Reference) #f)
      #s(field-spec dischargeDisposition 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (EncounterLocation stx)
  (build-fhir-form stx 'EncounterLocation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec location 1 1 #(type Reference) #f)
      #s(field-spec status 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/encounter-location-status"))
      #s(field-spec form 0 1 #(type CodeableConcept) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      )
    #:parent 'BackboneElement))
