#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide EnrollmentResponse)
(define-syntax (EnrollmentResponse stx)
  (build-fhir-form stx 'EnrollmentResponse
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/fm-status"))
      #s(field-spec request 0 1 #(type Reference) #f)
      #s(field-spec outcome 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/enrollment-outcome"))
      #s(field-spec disposition 0 1 #(prim "string") #f)
      #s(field-spec created 0 1 #(prim "dateTime") #f)
      #s(field-spec organization 0 1 #(type Reference) #f)
      #s(field-spec requestProvider 0 1 #(type Reference) #f)
      #s(field-spec candidate 0 1 #(type Reference) #f)
      )
    #:parent 'DomainResource))
