#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Group GroupCharacteristic GroupMember)
(define-syntax (Group stx)
  (build-fhir-form stx 'Group
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec status 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec type 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/group-type"))
      #s(field-spec membership 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/group-membership-basis"))
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec quantity 0 1 #(prim "unsignedInt") #f)
      #s(field-spec managingEntity 0 1 #(type Reference) #f)
      #s(field-spec combinationMethod 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/group-characteristic-combination"))
      #s(field-spec combinationThreshold 0 1 #(prim "positiveInt") #f)
      #s(field-spec characteristic 0 * #(type GroupCharacteristic) #f)
      #s(field-spec member 0 * #(type GroupMember) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      )
    #:parent 'DomainResource))
(define-syntax (GroupCharacteristic stx)
  (build-fhir-form stx 'GroupCharacteristic
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec exclude 1 1 #(prim "boolean") #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec method 0 * #(type CodeableConcept) #f)
      #s(field-spec formula 0 1 #(type Expression) #f)
      #s(field-spec determiner 0 1 #(type Reference) #f)
      #s(field-spec offset 0 1 #(type CodeableConcept) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec relativeTime 0 * #(type RelativeTime) #f)
      #s(field-spec valueCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueQuantity 0 1 #(type Quantity) #f)
      #s(field-spec valueRange 0 1 #(type Range) #f)
      #s(field-spec valueReference 0 1 #(type Reference) #f)
      #s(field-spec valueUri 0 1 #(prim "uri") #f)
      #s(field-spec valueExpression 0 1 #(type Expression) #f)
      #s(field-spec instancesUnsignedInt 0 1 #(prim "unsignedInt") #f)
      #s(field-spec instancesRange 0 1 #(type Range) #f)
      #s(field-spec durationDuration 0 1 #(type Duration) #f)
      #s(field-spec durationRange 0 1 #(type Range) #f)
      #s(choice-group 1 1 (valueCodeableConcept valueBoolean valueQuantity valueRange valueReference valueUri valueExpression))
      #s(choice-group 0 1 (instancesUnsignedInt instancesRange))
      #s(choice-group 0 1 (durationDuration durationRange))
      )
    #:parent 'BackboneElement))
(define-syntax (GroupMember stx)
  (build-fhir-form stx 'GroupMember
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec entity 1 1 #(type Reference) #f)
      #s(field-spec involvement 0 * #(type CodeableConcept) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec inactive 0 1 #(prim "boolean") #f)
      )
    #:parent 'BackboneElement))
