#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide ImplementationGuide ImplementationGuideDependsOn ImplementationGuideGlobal ImplementationGuideDefinition ImplementationGuideDefinitionGrouping ImplementationGuideDefinitionResource ImplementationGuideDefinitionPage ImplementationGuideDefinitionParameter ImplementationGuideDefinitionTemplate ImplementationGuideManifest ImplementationGuideManifestResource ImplementationGuideManifestPage)
(define-syntax (ImplementationGuide stx)
  (build-fhir-form stx 'ImplementationGuide
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 1 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec packageId 1 1 #(prim "id") #f)
      #s(field-spec license 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/spdx-license"))
      #s(field-spec fhirVersion 1 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/FHIR-version"))
      #s(field-spec dependsOn 0 * #(type ImplementationGuideDependsOn) #f)
      #s(field-spec global 0 * #(type ImplementationGuideGlobal) #f)
      #s(field-spec definition 0 1 #(type ImplementationGuideDefinition) #f)
      #s(field-spec manifest 0 1 #(type ImplementationGuideManifest) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      )
    #:parent 'DomainResource))
(define-syntax (ImplementationGuideDependsOn stx)
  (build-fhir-form stx 'ImplementationGuideDependsOn
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec uri 1 1 #(prim "canonical") #f)
      #s(field-spec packageId 0 1 #(prim "id") #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec reason 0 1 #(prim "markdown") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideGlobal stx)
  (build-fhir-form stx 'ImplementationGuideGlobal
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/resource-types"))
      #s(field-spec profile 1 1 #(prim "canonical") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideDefinition stx)
  (build-fhir-form stx 'ImplementationGuideDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec grouping 0 * #(type ImplementationGuideDefinitionGrouping) #f)
      #s(field-spec resource 0 * #(type ImplementationGuideDefinitionResource) #f)
      #s(field-spec page 0 1 #(type ImplementationGuideDefinitionPage) #f)
      #s(field-spec parameter 0 * #(type ImplementationGuideDefinitionParameter) #f)
      #s(field-spec template 0 * #(type ImplementationGuideDefinitionTemplate) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideDefinitionGrouping stx)
  (build-fhir-form stx 'ImplementationGuideDefinitionGrouping
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideDefinitionResource stx)
  (build-fhir-form stx 'ImplementationGuideDefinitionResource
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec reference 1 1 #(type Reference) #f)
      #s(field-spec fhirVersion 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/FHIR-version"))
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec isExample 0 1 #(prim "boolean") #f)
      #s(field-spec profile 0 * #(prim "canonical") #f)
      #s(field-spec groupingId 0 1 #(prim "id") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideDefinitionPage stx)
  (build-fhir-form stx 'ImplementationGuideDefinitionPage
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "url") #f)
      #s(field-spec title 1 1 #(prim "string") #f)
      #s(field-spec generation 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/guide-page-generation"))
      #s(field-spec page 0 * #(type ImplementationGuideDefinitionPage) #f)
      #s(field-spec sourceUrl 0 1 #(prim "url") #f)
      #s(field-spec sourceString 0 1 #(prim "string") #f)
      #s(field-spec sourceMarkdown 0 1 #(prim "markdown") #f)
      #s(choice-group 0 1 (sourceUrl sourceString sourceMarkdown))
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideDefinitionParameter stx)
  (build-fhir-form stx 'ImplementationGuideDefinitionParameter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type Coding) #f)
      #s(field-spec value 1 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideDefinitionTemplate stx)
  (build-fhir-form stx 'ImplementationGuideDefinitionTemplate
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(prim "code") #f)
      #s(field-spec source 1 1 #(prim "string") #f)
      #s(field-spec scope 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideManifest stx)
  (build-fhir-form stx 'ImplementationGuideManifest
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec rendering 0 1 #(prim "url") #f)
      #s(field-spec resource 1 * #(type ImplementationGuideManifestResource) #f)
      #s(field-spec page 0 * #(type ImplementationGuideManifestPage) #f)
      #s(field-spec image 0 * #(prim "string") #f)
      #s(field-spec other 0 * #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideManifestResource stx)
  (build-fhir-form stx 'ImplementationGuideManifestResource
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec reference 1 1 #(type Reference) #f)
      #s(field-spec isExample 0 1 #(prim "boolean") #f)
      #s(field-spec profile 0 * #(prim "canonical") #f)
      #s(field-spec relativePath 0 1 #(prim "url") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ImplementationGuideManifestPage stx)
  (build-fhir-form stx 'ImplementationGuideManifestPage
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec anchor 0 * #(prim "string") #f)
      )
    #:parent 'BackboneElement))
