#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide InsuranceProduct InsuranceProductCoverage InsuranceProductCoverageBenefit InsuranceProductCoverageBenefitLimit InsuranceProductRelated)
(define-syntax (InsuranceProduct stx)
  (build-fhir-form stx 'InsuranceProduct
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec alias 0 * #(prim "string") #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec ownedBy 0 1 #(type Reference) #f)
      #s(field-spec administeredBy 0 1 #(type Reference) #f)
      #s(field-spec coverageArea 0 * #(type Reference) #f)
      #s(field-spec contact 0 * #(type ExtendedContactDetail) #f)
      #s(field-spec endpoint 0 * #(type Reference) #f)
      #s(field-spec network 0 * #(type Reference) #f)
      #s(field-spec coverage 0 * #(type InsuranceProductCoverage) #f)
      #s(field-spec related 0 * #(type InsuranceProductRelated) #f)
      )
    #:parent 'DomainResource))
(define-syntax (InsuranceProductCoverage stx)
  (build-fhir-form stx 'InsuranceProductCoverage
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec network 0 * #(type Reference) #f)
      #s(field-spec benefit 1 * #(type InsuranceProductCoverageBenefit) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (InsuranceProductCoverageBenefit stx)
  (build-fhir-form stx 'InsuranceProductCoverageBenefit
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec requirement 0 1 #(prim "string") #f)
      #s(field-spec limit 0 * #(type InsuranceProductCoverageBenefitLimit) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (InsuranceProductCoverageBenefitLimit stx)
  (build-fhir-form stx 'InsuranceProductCoverageBenefitLimit
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec value 0 1 #(type Quantity) #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (InsuranceProductRelated stx)
  (build-fhir-form stx 'InsuranceProductRelated
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec product 0 1 #(type Reference) #f)
      #s(field-spec relationship 0 1 #(type CodeableConcept) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      )
    #:parent 'BackboneElement))
