#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Location LocationPosition)
(define-syntax (Location stx)
  (build-fhir-form stx 'Location
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/location-status"))
      #s(field-spec operationalStatus 0 1 #(type Coding) #f)
      #s(field-spec code 0 * #(type CodeableConcept) #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec alias 0 * #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec mode 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/location-mode"))
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec contact 0 * #(type ExtendedContactDetail) #f)
      #s(field-spec address 0 1 #(type Address) #f)
      #s(field-spec form 0 1 #(type CodeableConcept) #f)
      #s(field-spec position 0 1 #(type LocationPosition) #f)
      #s(field-spec managingOrganization 0 1 #(type Reference) #f)
      #s(field-spec partOf 0 1 #(type Reference) #f)
      #s(field-spec characteristic 0 * #(type CodeableConcept) #f)
      #s(field-spec hoursOfOperation 0 1 #(type Availability) #f)
      #s(field-spec virtualService 0 * #(type VirtualServiceDetail) #f)
      #s(field-spec endpoint 0 * #(type Reference) #f)
      )
    #:parent 'DomainResource))
(define-syntax (LocationPosition stx)
  (build-fhir-form stx 'LocationPosition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec longitude 1 1 #(prim "decimal") #f)
      #s(field-spec latitude 1 1 #(prim "decimal") #f)
      #s(field-spec altitude 0 1 #(prim "decimal") #f)
      )
    #:parent 'BackboneElement))
