#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Measure MeasureTerm MeasureGroup MeasureGroupComponent MeasureGroupPopulation MeasureGroupStratifier MeasureGroupStratifierComponent MeasureSupplementalData)
(define-syntax (Measure stx)
  (build-fhir-form stx 'Measure
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec subtitle 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec usage 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec approvalDate 0 1 #(prim "date") #f)
      #s(field-spec lastReviewDate 0 1 #(prim "date") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(field-spec reportingFrequency 0 1 #(type Quantity) #f)
      #s(field-spec author 0 * #(type ContactDetail) #f)
      #s(field-spec editor 0 * #(type ContactDetail) #f)
      #s(field-spec reviewer 0 * #(type ContactDetail) #f)
      #s(field-spec endorser 0 * #(type ContactDetail) #f)
      #s(field-spec relatedArtifact 0 * #(type RelatedArtifact) #f)
      #s(field-spec library 0 * #(prim "canonical") #f)
      #s(field-spec disclaimer 0 1 #(prim "markdown") #f)
      #s(field-spec riskAdjustment 0 1 #(prim "markdown") #f)
      #s(field-spec rateAggregation 0 1 #(prim "markdown") #f)
      #s(field-spec rationale 0 1 #(prim "markdown") #f)
      #s(field-spec clinicalRecommendationStatement 0 1 #(prim "markdown") #f)
      #s(field-spec term 0 * #(type MeasureTerm) #f)
      #s(field-spec group 0 * #(type MeasureGroup) #f)
      #s(field-spec supplementalData 0 * #(type MeasureSupplementalData) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(field-spec subjectCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec subjectReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      #s(choice-group 0 1 (subjectCodeableConcept subjectReference))
      )
    #:parent 'DomainResource))
(define-syntax (MeasureTerm stx)
  (build-fhir-form stx 'MeasureTerm
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec definition 0 1 #(prim "markdown") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureGroup stx)
  (build-fhir-form stx 'MeasureGroup
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec type 0 * #(type CodeableConcept) #f)
      #s(field-spec basis 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/fhir-types"))
      #s(field-spec basisRequirement 0 * #(type DataRequirement) #f)
      #s(field-spec scoring 0 1 #(type CodeableConcept) #f)
      #s(field-spec scoringUnit 0 1 #(type CodeableConcept) #f)
      #s(field-spec scoringPrecision 0 1 #(prim "positiveInt") #f)
      #s(field-spec compositeScoring 0 1 #(type CodeableConcept) #f)
      #s(field-spec component 0 * #(type MeasureGroupComponent) #f)
      #s(field-spec rateAggregation 0 1 #(prim "markdown") #f)
      #s(field-spec improvementNotation 0 1 #(type CodeableConcept) #f)
      #s(field-spec improvementNotationGuidance 0 1 #(prim "markdown") #f)
      #s(field-spec library 0 * #(prim "canonical") #f)
      #s(field-spec population 0 * #(type MeasureGroupPopulation) #f)
      #s(field-spec stratifier 0 * #(type MeasureGroupStratifier) #f)
      #s(field-spec subjectCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec subjectReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (subjectCodeableConcept subjectReference))
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureGroupComponent stx)
  (build-fhir-form stx 'MeasureGroupComponent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec measure 0 1 #(prim "canonical") #f)
      #s(field-spec groupId 0 1 #(prim "string") #f)
      #s(field-spec weight 0 1 #(prim "decimal") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureGroupPopulation stx)
  (build-fhir-form stx 'MeasureGroupPopulation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec criteria 0 1 #(type Expression) #f)
      #s(field-spec groupDefinition 0 1 #(type Reference) #f)
      #s(field-spec inputPopulationId 0 1 #(prim "string") #f)
      #s(field-spec aggregateMethod 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureGroupStratifier stx)
  (build-fhir-form stx 'MeasureGroupStratifier
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec criteria 0 1 #(type Expression) #f)
      #s(field-spec groupDefinition 0 1 #(type Reference) #f)
      #s(field-spec component 0 * #(type MeasureGroupStratifierComponent) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureGroupStratifierComponent stx)
  (build-fhir-form stx 'MeasureGroupStratifierComponent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec criteria 0 1 #(type Expression) #f)
      #s(field-spec groupDefinition 0 1 #(type Reference) #f)
      #s(field-spec valueSet 0 1 #(prim "canonical") #f)
      #s(field-spec unit 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureSupplementalData stx)
  (build-fhir-form stx 'MeasureSupplementalData
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec usage 0 * #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec criteria 1 1 #(type Expression) #f)
      #s(field-spec valueSet 0 1 #(prim "canonical") #f)
      #s(field-spec unit 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
