#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide MeasureReport MeasureReportGroup MeasureReportGroupPopulation MeasureReportGroupStratifier MeasureReportGroupStratifierStratum MeasureReportGroupStratifierStratumComponent MeasureReportGroupStratifierStratumPopulation)
(define-syntax (MeasureReport stx)
  (build-fhir-form stx 'MeasureReport
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec category 0 1 #(type CodeableConcept) #f)
      #s(field-spec messages 0 1 #(type Reference) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/measure-report-status"))
      #s(field-spec type 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/measure-report-type"))
      #s(field-spec dataUpdateType 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/submit-data-update-type"))
      #s(field-spec measure 0 1 #(prim "canonical") #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec reporter 0 1 #(type Reference) #f)
      #s(field-spec reportingVendor 0 1 #(type Reference) #f)
      #s(field-spec location 0 * #(type Reference) #f)
      #s(field-spec period 1 1 #(type Period) #f)
      #s(field-spec inputParameters 0 1 #(type Reference) #f)
      #s(field-spec group 0 * #(type MeasureReportGroup) #f)
      #s(field-spec supplementalData 0 * #(type Reference) #f)
      #s(field-spec evaluatedResource 0 * #(type Reference) #f)
      )
    #:parent 'DomainResource))
(define-syntax (MeasureReportGroup stx)
  (build-fhir-form stx 'MeasureReportGroup
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec calculatedDate 0 1 #(prim "dateTime") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec scoring 0 1 #(type CodeableConcept) #f)
      #s(field-spec compositeScoring 0 1 #(type CodeableConcept) #f)
      #s(field-spec improvementNotation 0 1 #(type CodeableConcept) #f)
      #s(field-spec improvementNotationGuidance 0 1 #(prim "markdown") #f)
      #s(field-spec population 0 * #(type MeasureReportGroupPopulation) #f)
      #s(field-spec stratifier 0 * #(type MeasureReportGroupStratifier) #f)
      #s(field-spec measureScoreQuantity 0 1 #(type Quantity) #f)
      #s(field-spec measureScoreDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec measureScoreCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec measureScorePeriod 0 1 #(type Period) #f)
      #s(field-spec measureScoreRange 0 1 #(type Range) #f)
      #s(field-spec measureScoreDuration 0 1 #(type Duration) #f)
      #s(field-spec measureScoreBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec measureScoreRatio 0 1 #(type Ratio) #f)
      #s(choice-group 0 1 (measureScoreQuantity measureScoreDateTime measureScoreCodeableConcept measureScorePeriod measureScoreRange measureScoreDuration measureScoreBoolean measureScoreRatio))
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureReportGroupPopulation stx)
  (build-fhir-form stx 'MeasureReportGroupPopulation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec count 0 1 #(prim "integer") #f)
      #s(field-spec countQuantity 0 1 #(type Quantity) #f)
      #s(field-spec subjectResults 0 1 #(type Reference) #f)
      #s(field-spec subjectReport 0 * #(type Reference) #f)
      #s(field-spec subjects 0 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureReportGroupStratifier stx)
  (build-fhir-form stx 'MeasureReportGroupStratifier
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec stratum 0 * #(type MeasureReportGroupStratifierStratum) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureReportGroupStratifierStratum stx)
  (build-fhir-form stx 'MeasureReportGroupStratifierStratum
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec component 0 * #(type MeasureReportGroupStratifierStratumComponent) #f)
      #s(field-spec population 0 * #(type MeasureReportGroupStratifierStratumPopulation) #f)
      #s(field-spec valueCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueQuantity 0 1 #(type Quantity) #f)
      #s(field-spec valueRange 0 1 #(type Range) #f)
      #s(field-spec valueReference 0 1 #(type Reference) #f)
      #s(field-spec measureScoreQuantity 0 1 #(type Quantity) #f)
      #s(field-spec measureScoreDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec measureScoreCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec measureScorePeriod 0 1 #(type Period) #f)
      #s(field-spec measureScoreRange 0 1 #(type Range) #f)
      #s(field-spec measureScoreDuration 0 1 #(type Duration) #f)
      #s(field-spec measureScoreBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec measureScoreRatio 0 1 #(type Ratio) #f)
      #s(choice-group 0 1 (valueCodeableConcept valueBoolean valueQuantity valueRange valueReference))
      #s(choice-group 0 1 (measureScoreQuantity measureScoreDateTime measureScoreCodeableConcept measureScorePeriod measureScoreRange measureScoreDuration measureScoreBoolean measureScoreRatio))
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureReportGroupStratifierStratumComponent stx)
  (build-fhir-form stx 'MeasureReportGroupStratifierStratumComponent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec valueCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueQuantity 0 1 #(type Quantity) #f)
      #s(field-spec valueRange 0 1 #(type Range) #f)
      #s(field-spec valueReference 0 1 #(type Reference) #f)
      #s(choice-group 1 1 (valueCodeableConcept valueBoolean valueQuantity valueRange valueReference))
      )
    #:parent 'BackboneElement))
(define-syntax (MeasureReportGroupStratifierStratumPopulation stx)
  (build-fhir-form stx 'MeasureReportGroupStratifierStratumPopulation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec count 0 1 #(prim "integer") #f)
      #s(field-spec countQuantity 0 1 #(type Quantity) #f)
      #s(field-spec subjectResults 0 1 #(type Reference) #f)
      #s(field-spec subjectReport 0 * #(type Reference) #f)
      #s(field-spec subjects 0 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
