#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide MedicationAdministration MedicationAdministrationPerformer MedicationAdministrationDosage)
(define-syntax (MedicationAdministration stx)
  (build-fhir-form stx 'MedicationAdministration
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec partOf 0 * #(type Reference) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/medication-admin-status"))
      #s(field-spec statusReason 0 * #(type CodeableConcept) #f)
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec medication 1 1 #(type CodeableReference) #f)
      #s(field-spec subject 1 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec supportingInformation 0 * #(type Reference) #f)
      #s(field-spec recorded 0 1 #(prim "dateTime") #f)
      #s(field-spec isSubPotent 0 1 #(prim "boolean") #f)
      #s(field-spec subPotentReason 0 * #(type CodeableConcept) #f)
      #s(field-spec performer 0 * #(type MedicationAdministrationPerformer) #f)
      #s(field-spec reason 0 * #(type CodeableReference) #f)
      #s(field-spec request 0 1 #(type Reference) #f)
      #s(field-spec device 0 * #(type CodeableReference) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec dosage 0 1 #(type MedicationAdministrationDosage) #f)
      #s(field-spec eventHistory 0 * #(type Reference) #f)
      #s(field-spec occurrenceDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec occurrencePeriod 0 1 #(type Period) #f)
      #s(field-spec occurrenceTiming 0 1 #(type Timing) #f)
      #s(choice-group 1 1 (occurrenceDateTime occurrencePeriod occurrenceTiming))
      )
    #:parent 'DomainResource))
(define-syntax (MedicationAdministrationPerformer stx)
  (build-fhir-form stx 'MedicationAdministrationPerformer
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec function 0 1 #(type CodeableConcept) #f)
      #s(field-spec actor 1 1 #(type CodeableReference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (MedicationAdministrationDosage stx)
  (build-fhir-form stx 'MedicationAdministrationDosage
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec text 0 1 #(prim "string") #f)
      #s(field-spec site 0 1 #(type CodeableConcept) #f)
      #s(field-spec route 0 1 #(type CodeableConcept) #f)
      #s(field-spec method 0 1 #(type CodeableConcept) #f)
      #s(field-spec dose 0 1 #(type Quantity) #f)
      #s(field-spec rateRatio 0 1 #(type Ratio) #f)
      #s(field-spec rateQuantity 0 1 #(type Quantity) #f)
      #s(choice-group 0 1 (rateRatio rateQuantity))
      )
    #:parent 'BackboneElement))
