#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide MedicationStatement MedicationStatementAdherence)
(define-syntax (MedicationStatement stx)
  (build-fhir-form stx 'MedicationStatement
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec partOf 0 * #(type Reference) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/medication-statement-status"))
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec medication 1 1 #(type CodeableReference) #f)
      #s(field-spec subject 1 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec dateAsserted 0 1 #(prim "dateTime") #f)
      #s(field-spec author 0 1 #(type Reference) #f)
      #s(field-spec informationSource 0 * #(type Reference) #f)
      #s(field-spec derivedFrom 0 * #(type Reference) #f)
      #s(field-spec reason 0 * #(type CodeableReference) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec relatedClinicalInformation 0 * #(type Reference) #f)
      #s(field-spec dosage 0 1 #(type DosageDetails) #f)
      #s(field-spec adherence 0 1 #(type MedicationStatementAdherence) #f)
      #s(field-spec effectiveDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(field-spec effectiveTiming 0 1 #(type Timing) #f)
      #s(choice-group 0 1 (effectiveDateTime effectivePeriod effectiveTiming))
      )
    #:parent 'DomainResource))
(define-syntax (MedicationStatementAdherence stx)
  (build-fhir-form stx 'MedicationStatementAdherence
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec reason 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
