#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide ObservationDefinition ObservationDefinitionQualifiedValue ObservationDefinitionComponent)
(define-syntax (ObservationDefinition stx)
  (build-fhir-form stx 'ObservationDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec approvalDate 0 1 #(prim "date") #f)
      #s(field-spec lastReviewDate 0 1 #(prim "date") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(field-spec derivedFromCanonical 0 * #(prim "canonical") #f)
      #s(field-spec derivedFromUri 0 * #(prim "uri") #f)
      #s(field-spec subject 0 * #(type CodeableConcept) #f)
      #s(field-spec performerType 0 1 #(type CodeableConcept) #f)
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec permittedDataType 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/permitted-data-type"))
      #s(field-spec multipleResultsAllowed 0 1 #(prim "boolean") #f)
      #s(field-spec bodyStructure 0 1 #(type CodeableReference) #f)
      #s(field-spec method 0 1 #(type CodeableConcept) #f)
      #s(field-spec specimen 0 * #(type Reference) #f)
      #s(field-spec preferredReportName 0 1 #(prim "string") #f)
      #s(field-spec permittedUnit 0 * #(type Coding) #f)
      #s(field-spec qualifiedValue 0 * #(type ObservationDefinitionQualifiedValue) #f)
      #s(field-spec hasMember 0 * #(type Reference) #f)
      #s(field-spec component 0 * #(type ObservationDefinitionComponent) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(field-spec deviceReference 0 1 #(type Reference) #f)
      #s(field-spec deviceCanonical 0 1 #(prim "canonical") #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      #s(choice-group 0 1 (deviceReference deviceCanonical))
      )
    #:parent 'DomainResource))
(define-syntax (ObservationDefinitionQualifiedValue stx)
  (build-fhir-form stx 'ObservationDefinitionQualifiedValue
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec context 0 1 #(type CodeableConcept) #f)
      #s(field-spec appliesTo 0 * #(type CodeableConcept) #f)
      #s(field-spec sexParameterForClinicalUse 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/administrative-gender"))
      #s(field-spec age 0 1 #(type Range) #f)
      #s(field-spec gestationalAge 0 1 #(type Range) #f)
      #s(field-spec condition 0 1 #(prim "string") #f)
      #s(field-spec rangeCategory 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/observation-range-category"))
      #s(field-spec range 0 1 #(type Range) #f)
      #s(field-spec validCodedValueSet 0 1 #(prim "canonical") #f)
      #s(field-spec normalCodedValueSet 0 1 #(prim "canonical") #f)
      #s(field-spec abnormalCodedValueSet 0 1 #(prim "canonical") #f)
      #s(field-spec criticalCodedValueSet 0 1 #(prim "canonical") #f)
      #s(field-spec interpretation 0 * #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ObservationDefinitionComponent stx)
  (build-fhir-form stx 'ObservationDefinitionComponent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec permittedDataType 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/permitted-data-type"))
      #s(field-spec permittedUnit 0 * #(type Coding) #f)
      #s(field-spec qualifiedValue 0 * #(type ObservationDefinitionQualifiedValue) #f)
      )
    #:parent 'BackboneElement))
