#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide PlanDefinition PlanDefinitionGoal PlanDefinitionGoalTarget PlanDefinitionActor PlanDefinitionActorOption PlanDefinitionAction PlanDefinitionActionCondition PlanDefinitionActionInput PlanDefinitionActionOutput PlanDefinitionActionRelatedAction PlanDefinitionActionParticipant PlanDefinitionActionDynamicValue)
(define-syntax (PlanDefinition stx)
  (build-fhir-form stx 'PlanDefinition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec subtitle 0 1 #(prim "string") #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec usage 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec approvalDate 0 1 #(prim "date") #f)
      #s(field-spec lastReviewDate 0 1 #(prim "date") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(field-spec topic 0 * #(type CodeableConcept) #f)
      #s(field-spec author 0 * #(type ContactDetail) #f)
      #s(field-spec editor 0 * #(type ContactDetail) #f)
      #s(field-spec reviewer 0 * #(type ContactDetail) #f)
      #s(field-spec endorser 0 * #(type ContactDetail) #f)
      #s(field-spec relatedArtifact 0 * #(type RelatedArtifact) #f)
      #s(field-spec library 0 * #(prim "canonical") #f)
      #s(field-spec goal 0 * #(type PlanDefinitionGoal) #f)
      #s(field-spec actor 0 * #(type PlanDefinitionActor) #f)
      #s(field-spec action 0 * #(type PlanDefinitionAction) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(field-spec subjectCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec subjectReference 0 1 #(type Reference) #f)
      #s(field-spec subjectCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec asNeededBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec asNeededCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      #s(choice-group 0 1 (subjectCodeableConcept subjectReference subjectCanonical))
      #s(choice-group 0 1 (asNeededBoolean asNeededCodeableConcept))
      )
    #:parent 'DomainResource))
(define-syntax (PlanDefinitionGoal stx)
  (build-fhir-form stx 'PlanDefinitionGoal
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec category 0 1 #(type CodeableConcept) #f)
      #s(field-spec description 1 1 #(type CodeableConcept) #f)
      #s(field-spec priority 0 1 #(type CodeableConcept) #f)
      #s(field-spec start 0 1 #(type CodeableConcept) #f)
      #s(field-spec addresses 0 * #(type CodeableConcept) #f)
      #s(field-spec documentation 0 * #(type RelatedArtifact) #f)
      #s(field-spec target 0 * #(type PlanDefinitionGoalTarget) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionGoalTarget stx)
  (build-fhir-form stx 'PlanDefinitionGoalTarget
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec measure 0 1 #(type CodeableConcept) #f)
      #s(field-spec due 0 1 #(type Duration) #f)
      #s(field-spec detailQuantity 0 1 #(type Quantity) #f)
      #s(field-spec detailRange 0 1 #(type Range) #f)
      #s(field-spec detailCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec detailString 0 1 #(prim "string") #f)
      #s(field-spec detailBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec detailInteger 0 1 #(prim "integer") #f)
      #s(field-spec detailRatio 0 1 #(type Ratio) #f)
      #s(choice-group 0 1 (detailQuantity detailRange detailCodeableConcept detailString detailBoolean detailInteger detailRatio))
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActor stx)
  (build-fhir-form stx 'PlanDefinitionActor
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec option 1 * #(type PlanDefinitionActorOption) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActorOption stx)
  (build-fhir-form stx 'PlanDefinitionActorOption
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-participant-type"))
      #s(field-spec typeCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec typeReference 0 1 #(type Reference) #f)
      #s(field-spec role 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionAction stx)
  (build-fhir-form stx 'PlanDefinitionAction
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec linkId 0 1 #(prim "string") #f)
      #s(field-spec prefix 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec textEquivalent 0 1 #(prim "markdown") #f)
      #s(field-spec priority 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/request-priority"))
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec reason 0 * #(type CodeableConcept) #f)
      #s(field-spec documentation 0 * #(type RelatedArtifact) #f)
      #s(field-spec goalId 0 * #(prim "string") #f)
      #s(field-spec trigger 0 * #(type TriggerDefinition) #f)
      #s(field-spec condition 0 * #(type PlanDefinitionActionCondition) #f)
      #s(field-spec input 0 * #(type PlanDefinitionActionInput) #f)
      #s(field-spec output 0 * #(type PlanDefinitionActionOutput) #f)
      #s(field-spec relatedAction 0 * #(type PlanDefinitionActionRelatedAction) #f)
      #s(field-spec location 0 1 #(type CodeableReference) #f)
      #s(field-spec participant 0 * #(type PlanDefinitionActionParticipant) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec applicabilityBehavior 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-applicability-behavior"))
      #s(field-spec groupingBehavior 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-grouping-behavior"))
      #s(field-spec selectionBehavior 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-selection-behavior"))
      #s(field-spec requiredBehavior 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-required-behavior"))
      #s(field-spec precheckBehavior 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-precheck-behavior"))
      #s(field-spec cardinalityBehavior 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-cardinality-behavior"))
      #s(field-spec transform 0 1 #(prim "canonical") #f)
      #s(field-spec dynamicValue 0 * #(type PlanDefinitionActionDynamicValue) #f)
      #s(field-spec action 0 * #(type PlanDefinitionAction) #f)
      #s(field-spec subjectCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec subjectReference 0 1 #(type Reference) #f)
      #s(field-spec subjectCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec timingAge 0 1 #(type Age) #f)
      #s(field-spec timingDuration 0 1 #(type Duration) #f)
      #s(field-spec timingRange 0 1 #(type Range) #f)
      #s(field-spec timingTiming 0 1 #(type Timing) #f)
      #s(field-spec timingRelativeTime 0 1 #(type RelativeTime) #f)
      #s(field-spec definitionCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec definitionUri 0 1 #(prim "uri") #f)
      #s(choice-group 0 1 (subjectCodeableConcept subjectReference subjectCanonical))
      #s(choice-group 0 1 (timingAge timingDuration timingRange timingTiming timingRelativeTime))
      #s(choice-group 0 1 (definitionCanonical definitionUri))
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActionCondition stx)
  (build-fhir-form stx 'PlanDefinitionActionCondition
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec kind 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-condition-kind"))
      #s(field-spec expression 0 1 #(type Expression) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActionInput stx)
  (build-fhir-form stx 'PlanDefinitionActionInput
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec requirement 0 1 #(type DataRequirement) #f)
      #s(field-spec relatedData 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActionOutput stx)
  (build-fhir-form stx 'PlanDefinitionActionOutput
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec requirement 0 1 #(type DataRequirement) #f)
      #s(field-spec relatedData 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActionRelatedAction stx)
  (build-fhir-form stx 'PlanDefinitionActionRelatedAction
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec targetId 1 1 #(prim "string") #f)
      #s(field-spec relationship 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-relationship-type"))
      #s(field-spec endRelationship 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-relationship-type"))
      #s(field-spec offsetDuration 0 1 #(type Duration) #f)
      #s(field-spec offsetRange 0 1 #(type Range) #f)
      #s(choice-group 0 1 (offsetDuration offsetRange))
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActionParticipant stx)
  (build-fhir-form stx 'PlanDefinitionActionParticipant
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec actorId 0 1 #(prim "string") #f)
      #s(field-spec type 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/action-participant-type"))
      #s(field-spec typeCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec typeReference 0 1 #(type Reference) #f)
      #s(field-spec role 0 1 #(type CodeableConcept) #f)
      #s(field-spec function 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PlanDefinitionActionDynamicValue stx)
  (build-fhir-form stx 'PlanDefinitionActionDynamicValue
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec path 0 1 #(prim "string") #f)
      #s(field-spec expression 0 1 #(type Expression) #f)
      )
    #:parent 'BackboneElement))
