#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide PractitionerRole)
(define-syntax (PractitionerRole stx)
  (build-fhir-form stx 'PractitionerRole
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec active 0 1 #(prim "boolean") #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec practitioner 0 1 #(type Reference) #f)
      #s(field-spec organization 0 1 #(type Reference) #f)
      #s(field-spec network 0 * #(type Reference) #f)
      #s(field-spec code 0 * #(type CodeableConcept) #f)
      #s(field-spec display 0 1 #(prim "string") #f)
      #s(field-spec specialty 0 * #(type CodeableConcept) #f)
      #s(field-spec location 0 * #(type Reference) #f)
      #s(field-spec healthcareService 0 * #(type Reference) #f)
      #s(field-spec contact 0 * #(type ExtendedContactDetail) #f)
      #s(field-spec characteristic 0 * #(type CodeableConcept) #f)
      #s(field-spec communication 0 * #(type CodeableConcept) #f)
      #s(field-spec availability 0 1 #(type Availability) #f)
      #s(field-spec endpoint 0 * #(type Reference) #f)
      )
    #:parent 'DomainResource))
