#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Practitioner PractitionerQualification PractitionerCommunication)
(define-syntax (Practitioner stx)
  (build-fhir-form stx 'Practitioner
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec active 0 1 #(prim "boolean") #f)
      #s(field-spec name 0 * #(type HumanName) #f)
      #s(field-spec telecom 0 * #(type ContactPoint) #f)
      #s(field-spec gender 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/administrative-gender"))
      #s(field-spec birthDate 0 1 #(prim "date") #f)
      #s(field-spec address 0 * #(type Address) #f)
      #s(field-spec photo 0 * #(type Attachment) #f)
      #s(field-spec qualification 0 * #(type PractitionerQualification) #f)
      #s(field-spec communication 0 * #(type PractitionerCommunication) #f)
      #s(field-spec deceasedBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec deceasedDateTime 0 1 #(prim "dateTime") #f)
      #s(choice-group 0 1 (deceasedBoolean deceasedDateTime))
      )
    #:parent 'DomainResource))
(define-syntax (PractitionerQualification stx)
  (build-fhir-form stx 'PractitionerQualification
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec status 0 1 #(type CodeableConcept) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec issuer 0 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (PractitionerCommunication stx)
  (build-fhir-form stx 'PractitionerCommunication
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec language 1 1 #(type CodeableConcept) #f)
      #s(field-spec preferred 0 1 #(prim "boolean") #f)
      )
    #:parent 'BackboneElement))
