#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Procedure ProcedurePerformer ProcedureFocalDevice)
(define-syntax (Procedure stx)
  (build-fhir-form stx 'Procedure
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec partOf 0 * #(type Reference) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/event-status"))
      #s(field-spec statusReason 0 1 #(type CodeableConcept) #f)
      #s(field-spec category 0 * #(type CodeableConcept) #f)
      #s(field-spec code 0 1 #(type CodeableConcept) #f)
      #s(field-spec subject 1 1 #(type Reference) #f)
      #s(field-spec focus 0 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec recorded 0 1 #(prim "dateTime") #f)
      #s(field-spec recorder 0 1 #(type Reference) #f)
      #s(field-spec performer 0 * #(type ProcedurePerformer) #f)
      #s(field-spec location 0 1 #(type Reference) #f)
      #s(field-spec reason 0 * #(type CodeableReference) #f)
      #s(field-spec bodySite 0 * #(type CodeableConcept) #f)
      #s(field-spec bodyStructure 0 1 #(type Reference) #f)
      #s(field-spec outcome 0 * #(type CodeableReference) #f)
      #s(field-spec report 0 * #(type Reference) #f)
      #s(field-spec complication 0 * #(type CodeableReference) #f)
      #s(field-spec followUp 0 * #(type CodeableReference) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      #s(field-spec focalDevice 0 * #(type ProcedureFocalDevice) #f)
      #s(field-spec used 0 * #(type CodeableReference) #f)
      #s(field-spec supportingInfo 0 * #(type Reference) #f)
      #s(field-spec occurrenceDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec occurrencePeriod 0 1 #(type Period) #f)
      #s(field-spec occurrenceString 0 1 #(prim "string") #f)
      #s(field-spec occurrenceAge 0 1 #(type Age) #f)
      #s(field-spec occurrenceRange 0 1 #(type Range) #f)
      #s(field-spec occurrenceTiming 0 1 #(type Timing) #f)
      #s(field-spec reportedBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec reportedReference 0 1 #(type Reference) #f)
      #s(choice-group 0 1 (occurrenceDateTime occurrencePeriod occurrenceString occurrenceAge occurrenceRange occurrenceTiming))
      #s(choice-group 0 1 (reportedBoolean reportedReference))
      )
    #:parent 'DomainResource))
(define-syntax (ProcedurePerformer stx)
  (build-fhir-form stx 'ProcedurePerformer
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec function 0 1 #(type CodeableConcept) #f)
      #s(field-spec actor 1 1 #(type Reference) #f)
      #s(field-spec onBehalfOf 0 1 #(type Reference) #f)
      #s(field-spec period 0 1 #(type Period) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ProcedureFocalDevice stx)
  (build-fhir-form stx 'ProcedureFocalDevice
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec action 0 1 #(type CodeableConcept) #f)
      #s(field-spec manipulated 1 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
