#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Provenance ProvenanceAgent ProvenanceEntity)
(define-syntax (Provenance stx)
  (build-fhir-form stx 'Provenance
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec target 1 * #(type Reference) #f)
      #s(field-spec recorded 0 1 #(prim "instant") #f)
      #s(field-spec policy 0 * #(prim "uri") #f)
      #s(field-spec location 0 1 #(type Reference) #f)
      #s(field-spec authorization 0 * #(type CodeableConcept) #f)
      #s(field-spec why 0 1 #(prim "markdown") #f)
      #s(field-spec activity 0 1 #(type CodeableConcept) #f)
      #s(field-spec basedOn 0 * #(type Reference) #f)
      #s(field-spec patient 0 1 #(type Reference) #f)
      #s(field-spec encounter 0 1 #(type Reference) #f)
      #s(field-spec agent 1 * #(type ProvenanceAgent) #f)
      #s(field-spec entity 0 * #(type ProvenanceEntity) #f)
      #s(field-spec signature 0 * #(type Signature) #f)
      #s(field-spec occurredPeriod 0 1 #(type Period) #f)
      #s(field-spec occurredDateTime 0 1 #(prim "dateTime") #f)
      #s(choice-group 0 1 (occurredPeriod occurredDateTime))
      )
    #:parent 'DomainResource))
(define-syntax (ProvenanceAgent stx)
  (build-fhir-form stx 'ProvenanceAgent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec role 0 * #(type CodeableConcept) #f)
      #s(field-spec who 1 1 #(type Reference) #f)
      #s(field-spec onBehalfOf 0 1 #(type Reference) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ProvenanceEntity stx)
  (build-fhir-form stx 'ProvenanceEntity
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec role 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/provenance-entity-role"))
      #s(field-spec what 1 1 #(type Reference) #f)
      #s(field-spec agent 0 * #(type ProvenanceAgent) #f)
      )
    #:parent 'BackboneElement))
