#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide ResearchSubject ResearchSubjectSubjectState ResearchSubjectSubjectMilestone)
(define-syntax (ResearchSubject stx)
  (build-fhir-form stx 'ResearchSubject
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec period 0 1 #(type Period) #f)
      #s(field-spec study 1 1 #(type Reference) #f)
      #s(field-spec subject 1 1 #(type Reference) #f)
      #s(field-spec subjectState 0 * #(type ResearchSubjectSubjectState) #f)
      #s(field-spec subjectMilestone 0 * #(type ResearchSubjectSubjectMilestone) #f)
      #s(field-spec comparisonGroup 0 * #(type CodeableReference) #f)
      #s(field-spec consent 0 * #(type Reference) #f)
      )
    #:parent 'DomainResource))
(define-syntax (ResearchSubjectSubjectState stx)
  (build-fhir-form stx 'ResearchSubjectSubjectState
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(type CodeableConcept) #f)
      #s(field-spec startDate 1 1 #(prim "dateTime") #f)
      #s(field-spec endDate 0 1 #(prim "dateTime") #f)
      #s(field-spec reason 0 1 #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ResearchSubjectSubjectMilestone stx)
  (build-fhir-form stx 'ResearchSubjectSubjectMilestone
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec milestone 1 1 #(type CodeableConcept) #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec reason 0 * #(type CodeableConcept) #f)
      )
    #:parent 'BackboneElement))
