#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Schedule)
(define-syntax (Schedule stx)
  (build-fhir-form stx 'Schedule
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec active 0 1 #(prim "boolean") #f)
      #s(field-spec serviceCategory 0 * #(type CodeableConcept) #f)
      #s(field-spec serviceType 0 * #(type CodeableReference) #f)
      #s(field-spec specialty 0 * #(type CodeableConcept) #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec actor 1 * #(type Reference) #f)
      #s(field-spec planningHorizon 0 1 #(type Period) #f)
      #s(field-spec comment 0 1 #(prim "markdown") #f)
      )
    #:parent 'DomainResource))
