#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide SearchParameter SearchParameterComponent)
(define-syntax (SearchParameter stx)
  (build-fhir-form stx 'SearchParameter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 1 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec derivedFrom 0 1 #(prim "canonical") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 1 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec code 1 1 #(prim "code") #f)
      #s(field-spec aliasCode 0 * #(prim "code") #f)
      #s(field-spec base 1 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/version-independent-all-resource-types"))
      #s(field-spec type 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/search-param-type"))
      #s(field-spec expression 0 1 #(prim "string") #f)
      #s(field-spec processingMode 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/search-processingmode"))
      #s(field-spec constraint 0 1 #(prim "string") #f)
      #s(field-spec target 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/version-independent-all-resource-types"))
      #s(field-spec multipleOr 0 1 #(prim "boolean") #f)
      #s(field-spec multipleAnd 0 1 #(prim "boolean") #f)
      #s(field-spec comparator 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/search-comparator"))
      #s(field-spec modifier 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/search-modifier-all-codes"))
      #s(field-spec chain 0 * #(prim "string") #f)
      #s(field-spec component 0 * #(type SearchParameterComponent) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      )
    #:parent 'DomainResource))
(define-syntax (SearchParameterComponent stx)
  (build-fhir-form stx 'SearchParameterComponent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec definition 1 1 #(prim "canonical") #f)
      #s(field-spec expression 1 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
