#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide Specimen SpecimenFeature SpecimenCollection SpecimenProcessing SpecimenContainer)
(define-syntax (Specimen stx)
  (build-fhir-form stx 'Specimen
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec status 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/specimen-status"))
      #s(field-spec type 0 1 #(type CodeableConcept) #f)
      #s(field-spec subject 0 1 #(type Reference) #f)
      #s(field-spec focus 0 1 #(type Reference) #f)
      #s(field-spec receivedTime 0 1 #(prim "dateTime") #f)
      #s(field-spec parent 0 * #(type Reference) #f)
      #s(field-spec request 0 * #(type Reference) #f)
      #s(field-spec combined 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/specimen-combined"))
      #s(field-spec role 0 * #(type CodeableConcept) #f)
      #s(field-spec feature 0 * #(type SpecimenFeature) #f)
      #s(field-spec collection 0 1 #(type SpecimenCollection) #f)
      #s(field-spec processing 0 * #(type SpecimenProcessing) #f)
      #s(field-spec container 0 * #(type SpecimenContainer) #f)
      #s(field-spec condition 0 * #(type CodeableConcept) #f)
      #s(field-spec note 0 * #(type Annotation) #f)
      )
    #:parent 'DomainResource))
(define-syntax (SpecimenFeature stx)
  (build-fhir-form stx 'SpecimenFeature
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec type 1 1 #(type CodeableConcept) #f)
      #s(field-spec description 1 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (SpecimenCollection stx)
  (build-fhir-form stx 'SpecimenCollection
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec collector 0 1 #(type Reference) #f)
      #s(field-spec duration 0 1 #(type Duration) #f)
      #s(field-spec quantity 0 1 #(type Quantity) #f)
      #s(field-spec method 0 1 #(type CodeableConcept) #f)
      #s(field-spec procedure 0 1 #(type Reference) #f)
      #s(field-spec bodySite 0 1 #(type CodeableReference) #f)
      #s(field-spec collectedDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec collectedPeriod 0 1 #(type Period) #f)
      #s(field-spec deviceCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec deviceReference 0 1 #(type Reference) #f)
      #s(field-spec deviceCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec fastingStatusCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec fastingStatusDuration 0 1 #(type Duration) #f)
      #s(choice-group 0 1 (collectedDateTime collectedPeriod))
      #s(choice-group 0 1 (deviceCodeableConcept deviceReference deviceCanonical))
      #s(choice-group 0 1 (fastingStatusCodeableConcept fastingStatusDuration))
      )
    #:parent 'BackboneElement))
(define-syntax (SpecimenProcessing stx)
  (build-fhir-form stx 'SpecimenProcessing
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec description 0 1 #(prim "string") #f)
      #s(field-spec method 0 1 #(type CodeableConcept) #f)
      #s(field-spec performer 0 1 #(type Reference) #f)
      #s(field-spec additive 0 * #(type CodeableReference) #f)
      #s(field-spec deviceCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec deviceReference 0 1 #(type Reference) #f)
      #s(field-spec deviceCanonical 0 1 #(prim "canonical") #f)
      #s(field-spec timeDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec timePeriod 0 1 #(type Period) #f)
      #s(field-spec timeDuration 0 1 #(type Duration) #f)
      #s(choice-group 0 1 (deviceCodeableConcept deviceReference deviceCanonical))
      #s(choice-group 0 1 (timeDateTime timePeriod timeDuration))
      )
    #:parent 'BackboneElement))
(define-syntax (SpecimenContainer stx)
  (build-fhir-form stx 'SpecimenContainer
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec specimenQuantity 0 1 #(type Quantity) #f)
      #s(field-spec deviceCodeableConcept 0 1 #(type CodeableConcept) #f)
      #s(field-spec deviceReference 0 1 #(type Reference) #f)
      #s(field-spec deviceCanonical 0 1 #(prim "canonical") #f)
      #s(choice-group 1 1 (deviceCodeableConcept deviceReference deviceCanonical))
      )
    #:parent 'BackboneElement))
