#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide StructureMap StructureMapStructure StructureMapConst StructureMapGroup StructureMapGroupInput StructureMapGroupRule StructureMapGroupRuleSource StructureMapGroupRuleTarget StructureMapGroupRuleTargetParameter StructureMapGroupRuleDependent)
(define-syntax (StructureMap stx)
  (build-fhir-form stx 'StructureMap
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 1 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec structure 0 * #(type StructureMapStructure) #f)
      #s(field-spec import 0 * #(prim "canonical") #f)
      #s(field-spec const 0 * #(type StructureMapConst) #f)
      #s(field-spec group 1 * #(type StructureMapGroup) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      )
    #:parent 'DomainResource))
(define-syntax (StructureMapStructure stx)
  (build-fhir-form stx 'StructureMapStructure
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 1 1 #(prim "canonical") #f)
      #s(field-spec mode 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/map-model-mode"))
      #s(field-spec alias 0 1 #(prim "string") #f)
      #s(field-spec documentation 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapConst stx)
  (build-fhir-form stx 'StructureMapConst
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 0 1 #(prim "id") #f)
      #s(field-spec value 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapGroup stx)
  (build-fhir-form stx 'StructureMapGroup
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "id") #f)
      #s(field-spec extends 0 1 #(prim "id") #f)
      #s(field-spec typeMode 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/map-group-type-mode"))
      #s(field-spec documentation 0 1 #(prim "string") #f)
      #s(field-spec input 1 * #(type StructureMapGroupInput) #f)
      #s(field-spec rule 0 * #(type StructureMapGroupRule) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapGroupInput stx)
  (build-fhir-form stx 'StructureMapGroupInput
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "id") #f)
      #s(field-spec type 0 1 #(prim "string") #f)
      #s(field-spec mode 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/map-input-mode"))
      #s(field-spec documentation 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapGroupRule stx)
  (build-fhir-form stx 'StructureMapGroupRule
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 0 1 #(prim "id") #f)
      #s(field-spec source 1 * #(type StructureMapGroupRuleSource) #f)
      #s(field-spec target 0 * #(type StructureMapGroupRuleTarget) #f)
      #s(field-spec rule 0 * #(type StructureMapGroupRule) #f)
      #s(field-spec dependent 0 * #(type StructureMapGroupRuleDependent) #f)
      #s(field-spec documentation 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapGroupRuleSource stx)
  (build-fhir-form stx 'StructureMapGroupRuleSource
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec context 1 1 #(prim "id") #f)
      #s(field-spec min 0 1 #(prim "unsignedInt") #f)
      #s(field-spec max 0 1 #(prim "string") #f)
      #s(field-spec type 0 1 #(prim "string") #f)
      #s(field-spec defaultValue 0 1 #(prim "string") #f)
      #s(field-spec element 0 1 #(prim "string") #f)
      #s(field-spec listMode 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/map-source-list-mode"))
      #s(field-spec variable 0 1 #(prim "id") #f)
      #s(field-spec condition 0 1 #(prim "string") #f)
      #s(field-spec check 0 1 #(prim "string") #f)
      #s(field-spec logMessage 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapGroupRuleTarget stx)
  (build-fhir-form stx 'StructureMapGroupRuleTarget
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec context 0 1 #(prim "string") #f)
      #s(field-spec element 0 1 #(prim "string") #f)
      #s(field-spec variable 0 1 #(prim "id") #f)
      #s(field-spec listMode 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/map-target-list-mode"))
      #s(field-spec listRuleId 0 1 #(prim "id") #f)
      #s(field-spec transform 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/map-transform"))
      #s(field-spec parameter 0 * #(type StructureMapGroupRuleTargetParameter) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapGroupRuleTargetParameter stx)
  (build-fhir-form stx 'StructureMapGroupRuleTargetParameter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec valueId 0 1 #(prim "id") #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueDecimal 0 1 #(prim "decimal") #f)
      #s(field-spec valueDate 0 1 #(prim "date") #f)
      #s(field-spec valueTime 0 1 #(prim "time") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(choice-group 1 1 (valueId valueString valueBoolean valueInteger valueDecimal valueDate valueTime valueDateTime))
      )
    #:parent 'BackboneElement))
(define-syntax (StructureMapGroupRuleDependent stx)
  (build-fhir-form stx 'StructureMapGroupRuleDependent
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "id") #f)
      #s(field-spec parameter 1 * #(type StructureMapGroupRuleTargetParameter) #f)
      )
    #:parent 'BackboneElement))
