#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide TerminologyCapabilities TerminologyCapabilitiesSoftware TerminologyCapabilitiesImplementation TerminologyCapabilitiesCodeSystem TerminologyCapabilitiesCodeSystemVersion TerminologyCapabilitiesCodeSystemVersionFilter TerminologyCapabilitiesSupplements TerminologyCapabilitiesExpansion TerminologyCapabilitiesExpansionParameter TerminologyCapabilitiesValidateCode TerminologyCapabilitiesTranslation)
(define-syntax (TerminologyCapabilities stx)
  (build-fhir-form stx 'TerminologyCapabilities
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 1 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec kind 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/capability-statement-kind"))
      #s(field-spec software 0 1 #(type TerminologyCapabilitiesSoftware) #f)
      #s(field-spec implementation 0 1 #(type TerminologyCapabilitiesImplementation) #f)
      #s(field-spec lockedDate 0 1 #(prim "boolean") #f)
      #s(field-spec codeSystem 0 * #(type TerminologyCapabilitiesCodeSystem) #f)
      #s(field-spec supplements 0 1 #(type TerminologyCapabilitiesSupplements) #f)
      #s(field-spec expansion 0 1 #(type TerminologyCapabilitiesExpansion) #f)
      #s(field-spec codeSearch 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/code-search-support"))
      #s(field-spec validateCode 0 1 #(type TerminologyCapabilitiesValidateCode) #f)
      #s(field-spec translation 0 1 #(type TerminologyCapabilitiesTranslation) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      )
    #:parent 'DomainResource))
(define-syntax (TerminologyCapabilitiesSoftware stx)
  (build-fhir-form stx 'TerminologyCapabilitiesSoftware
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesImplementation stx)
  (build-fhir-form stx 'TerminologyCapabilitiesImplementation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec description 1 1 #(prim "markdown") #f)
      #s(field-spec url 0 1 #(prim "url") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesCodeSystem stx)
  (build-fhir-form stx 'TerminologyCapabilitiesCodeSystem
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec uri 0 1 #(prim "canonical") #f)
      #s(field-spec supplement 0 * #(prim "canonical") #f)
      #s(field-spec version 0 * #(type TerminologyCapabilitiesCodeSystemVersion) #f)
      #s(field-spec content 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/codesystem-content-mode"))
      #s(field-spec subsumption 0 1 #(prim "boolean") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesCodeSystemVersion stx)
  (build-fhir-form stx 'TerminologyCapabilitiesCodeSystemVersion
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 0 1 #(prim "string") #f)
      #s(field-spec isDefault 0 1 #(prim "boolean") #f)
      #s(field-spec supplement 0 * #(prim "canonical") #f)
      #s(field-spec compositional 0 1 #(prim "boolean") #f)
      #s(field-spec language 0 * #(prim "code") (required "http://hl7.org/fhir/ValueSet/all-languages"))
      #s(field-spec filter 0 * #(type TerminologyCapabilitiesCodeSystemVersionFilter) #f)
      #s(field-spec property 0 * #(prim "code") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesCodeSystemVersionFilter stx)
  (build-fhir-form stx 'TerminologyCapabilitiesCodeSystemVersionFilter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(prim "code") #f)
      #s(field-spec op 1 * #(prim "code") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesSupplements stx)
  (build-fhir-form stx 'TerminologyCapabilitiesSupplements
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec globals 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/global-langpack-support"))
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesExpansion stx)
  (build-fhir-form stx 'TerminologyCapabilitiesExpansion
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec hierarchical 0 1 #(prim "boolean") #f)
      #s(field-spec paging 0 1 #(prim "boolean") #f)
      #s(field-spec incomplete 0 1 #(prim "boolean") #f)
      #s(field-spec parameter 0 * #(type TerminologyCapabilitiesExpansionParameter) #f)
      #s(field-spec textFilter 0 1 #(prim "markdown") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesExpansionParameter stx)
  (build-fhir-form stx 'TerminologyCapabilitiesExpansionParameter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "code") #f)
      #s(field-spec documentation 0 1 #(prim "markdown") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesValidateCode stx)
  (build-fhir-form stx 'TerminologyCapabilitiesValidateCode
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec translations 1 1 #(prim "boolean") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (TerminologyCapabilitiesTranslation stx)
  (build-fhir-form stx 'TerminologyCapabilitiesTranslation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec needsMap 1 1 #(prim "boolean") #f)
      )
    #:parent 'BackboneElement))
