#lang racket/base
;;; GENERATED from hl7.fhir.r6.core#6.0.0-ballot4 — DO NOT EDIT (verified by raco fhir check).
(require (for-syntax racket/base fhir/lang-gen/form-syntax))
(provide ValueSet ValueSetCompose ValueSetComposeInclude ValueSetComposeIncludeConcept ValueSetComposeIncludeConceptDesignation ValueSetComposeIncludeFilter ValueSetExpansion ValueSetExpansionParameter ValueSetExpansionProperty ValueSetExpansionContains ValueSetExpansionContainsProperty ValueSetExpansionContainsPropertySubProperty)
(define-syntax (ValueSet stx)
  (build-fhir-form stx 'ValueSet
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec meta 0 1 #(type Meta) #f)
      #s(field-spec implicitRules 0 1 #(raw) #f)
      #s(field-spec language 0 1 #(raw) #f)
      #s(field-spec text 0 1 #(type Narrative) #f)
      #s(field-spec contained 0 * #(resource) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec url 0 1 #(prim "uri") #f)
      #s(field-spec identifier 0 * #(type Identifier) #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec name 0 1 #(prim "string") #f)
      #s(field-spec title 0 1 #(prim "string") #f)
      #s(field-spec status 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/publication-status"))
      #s(field-spec experimental 0 1 #(prim "boolean") #f)
      #s(field-spec date 0 1 #(prim "dateTime") #f)
      #s(field-spec publisher 0 1 #(prim "string") #f)
      #s(field-spec contact 0 * #(type ContactDetail) #f)
      #s(field-spec description 0 1 #(prim "markdown") #f)
      #s(field-spec useContext 0 * #(type UsageContext) #f)
      #s(field-spec jurisdiction 0 * #(type CodeableConcept) #f)
      #s(field-spec immutable 0 1 #(prim "boolean") #f)
      #s(field-spec purpose 0 1 #(prim "markdown") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      #s(field-spec copyrightLabel 0 1 #(prim "string") #f)
      #s(field-spec approvalDate 0 1 #(prim "date") #f)
      #s(field-spec lastReviewDate 0 1 #(prim "date") #f)
      #s(field-spec effectivePeriod 0 1 #(type Period) #f)
      #s(field-spec topic 0 * #(type CodeableConcept) #f)
      #s(field-spec author 0 * #(type ContactDetail) #f)
      #s(field-spec editor 0 * #(type ContactDetail) #f)
      #s(field-spec reviewer 0 * #(type ContactDetail) #f)
      #s(field-spec endorser 0 * #(type ContactDetail) #f)
      #s(field-spec relatedArtifact 0 * #(type RelatedArtifact) #f)
      #s(field-spec compose 0 1 #(type ValueSetCompose) #f)
      #s(field-spec expansion 0 1 #(type ValueSetExpansion) #f)
      #s(field-spec versionAlgorithmString 0 1 #(prim "string") #f)
      #s(field-spec versionAlgorithmCoding 0 1 #(type Coding) #f)
      #s(choice-group 0 1 (versionAlgorithmString versionAlgorithmCoding))
      )
    #:parent 'DomainResource))
(define-syntax (ValueSetCompose stx)
  (build-fhir-form stx 'ValueSetCompose
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec lockedDate 0 1 #(prim "date") #f)
      #s(field-spec inactive 0 1 #(prim "boolean") #f)
      #s(field-spec include 1 * #(type ValueSetComposeInclude) #f)
      #s(field-spec exclude 0 * #(type ValueSetComposeInclude) #f)
      #s(field-spec property 0 * #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetComposeInclude stx)
  (build-fhir-form stx 'ValueSetComposeInclude
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec system 0 1 #(prim "uri") #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec concept 0 * #(type ValueSetComposeIncludeConcept) #f)
      #s(field-spec filter 0 * #(type ValueSetComposeIncludeFilter) #f)
      #s(field-spec valueSet 0 * #(prim "canonical") #f)
      #s(field-spec copyright 0 1 #(prim "markdown") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetComposeIncludeConcept stx)
  (build-fhir-form stx 'ValueSetComposeIncludeConcept
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(prim "code") #f)
      #s(field-spec display 0 1 #(prim "string") #f)
      #s(field-spec designation 0 * #(type ValueSetComposeIncludeConceptDesignation) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetComposeIncludeConceptDesignation stx)
  (build-fhir-form stx 'ValueSetComposeIncludeConceptDesignation
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec language 0 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/all-languages"))
      #s(field-spec use 0 1 #(type Coding) #f)
      #s(field-spec additionalUse 0 * #(type Coding) #f)
      #s(field-spec value 1 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetComposeIncludeFilter stx)
  (build-fhir-form stx 'ValueSetComposeIncludeFilter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec property 1 1 #(prim "code") #f)
      #s(field-spec op 1 1 #(prim "code") (required "http://hl7.org/fhir/ValueSet/filter-operator"))
      #s(field-spec value 1 1 #(prim "string") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetExpansion stx)
  (build-fhir-form stx 'ValueSetExpansion
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec identifier 0 1 #(prim "uri") #f)
      #s(field-spec next 0 1 #(prim "uri") #f)
      #s(field-spec timestamp 1 1 #(prim "dateTime") #f)
      #s(field-spec total 0 1 #(prim "integer") #f)
      #s(field-spec offset 0 1 #(prim "integer") #f)
      #s(field-spec parameter 0 * #(type ValueSetExpansionParameter) #f)
      #s(field-spec property 0 * #(type ValueSetExpansionProperty) #f)
      #s(field-spec contains 0 * #(type ValueSetExpansionContains) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetExpansionParameter stx)
  (build-fhir-form stx 'ValueSetExpansionParameter
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec name 1 1 #(prim "string") #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueDecimal 0 1 #(prim "decimal") #f)
      #s(field-spec valueUri 0 1 #(prim "uri") #f)
      #s(field-spec valueCode 0 1 #(prim "code") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(choice-group 0 1 (valueString valueBoolean valueInteger valueDecimal valueUri valueCode valueDateTime))
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetExpansionProperty stx)
  (build-fhir-form stx 'ValueSetExpansionProperty
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(prim "code") #f)
      #s(field-spec uri 0 1 #(prim "uri") #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetExpansionContains stx)
  (build-fhir-form stx 'ValueSetExpansionContains
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec system 0 1 #(prim "uri") #f)
      #s(field-spec abstract 0 1 #(prim "boolean") #f)
      #s(field-spec inactive 0 1 #(prim "boolean") #f)
      #s(field-spec version 0 1 #(prim "string") #f)
      #s(field-spec code 0 1 #(prim "code") #f)
      #s(field-spec display 0 1 #(prim "string") #f)
      #s(field-spec designation 0 * #(type ValueSetComposeIncludeConceptDesignation) #f)
      #s(field-spec property 0 * #(type ValueSetExpansionContainsProperty) #f)
      #s(field-spec contains 0 * #(type ValueSetExpansionContains) #f)
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetExpansionContainsProperty stx)
  (build-fhir-form stx 'ValueSetExpansionContainsProperty
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(prim "code") #f)
      #s(field-spec subProperty 0 * #(type ValueSetExpansionContainsPropertySubProperty) #f)
      #s(field-spec valueCode 0 1 #(prim "code") #f)
      #s(field-spec valueCoding 0 1 #(type Coding) #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec valueDecimal 0 1 #(prim "decimal") #f)
      #s(choice-group 1 1 (valueCode valueCoding valueString valueInteger valueBoolean valueDateTime valueDecimal))
      )
    #:parent 'BackboneElement))
(define-syntax (ValueSetExpansionContainsPropertySubProperty stx)
  (build-fhir-form stx 'ValueSetExpansionContainsPropertySubProperty
    '(#s(field-spec id 0 1 #(raw) #f)
      #s(field-spec extension 0 * #(type Extension) #f)
      #s(field-spec modifierExtension 0 * #(type Extension) #f)
      #s(field-spec code 1 1 #(prim "code") #f)
      #s(field-spec valueCode 0 1 #(prim "code") #f)
      #s(field-spec valueCoding 0 1 #(type Coding) #f)
      #s(field-spec valueString 0 1 #(prim "string") #f)
      #s(field-spec valueInteger 0 1 #(prim "integer") #f)
      #s(field-spec valueBoolean 0 1 #(prim "boolean") #f)
      #s(field-spec valueDateTime 0 1 #(prim "dateTime") #f)
      #s(field-spec valueDecimal 0 1 #(prim "decimal") #f)
      #s(choice-group 1 1 (valueCode valueCoding valueString valueInteger valueBoolean valueDateTime valueDecimal))
      )
    #:parent 'BackboneElement))
